os-autoinst/openQA

lib/OpenQA.pm, lib/OpenQA/API/V1/JobTemplate.pm, lib/OpenQA/API/V1/Table.pm, lib/OpenQA/Plugin/HashedParams.pm, t/api/05-machines.t, t/api/06-products.t, t/api/07-testsuites.t, t/api/08-jobtemplates.t
https://progress.opensuse.org/issues/5568
The API works OK for web pages where the main entry (machine. product, test suite) is created first and the variables are added later. For load_tempates script it is usable but not efficient so I will probably have to add
another function that creates whole entry at once.
=> Administration API

systemd/openqa-worker@.service
the default for systemd is sending all processes in the control group
a TERM, but we want a defined shut down procedure, so only send the
worker a TERM
If the process doesn't go away after a timeout, systemd will send
SIGKILL to all processes again, so no worries there
=> make sure systemd kills the worker first

script/worker
sending a TERM twice while isotovideo is shuting down makes it likely
that we leave qemu running and this can lead to desaster. so better
be patient
In case isotovideo won't shut down, systemd will kill the whole cgroup
and we have something to debug
=> don't stop isotovideo while shutting down

lib/OpenQA/API/V1/Iso.pm, lib/OpenQA/API/V1/Job.pm, lib/OpenQA/WebSockets.pm, lib/OpenQA/modules/Scheduler.pm, script/worker, t/04-scheduler.t, t/11-commands.t
* When new job is scheduled, 'job_available' command is send to all connected workers. Depending if they are idle or not workers will try to grab a job.
* In case of POST isos command, job notification is send after all jobs are scheduled.
* After worker finish its job, immediately asks for new one if available. This is to solve when all jobs are scheduled and notifications were already sent.
* There is backup call to grab job each 10s.
=> action 5792 - job notify command

profiles/apparmor.d/usr.share.openqa.script.worker
lscpu: cannot open /proc/self/status: Permission denied
=> update apparmor profile

lib/OpenQA/Scheduler.pm, script/worker
If job_cancel (and maybe other functions) is called too fast, it can send duplicate "cancel" commands to the worker. The worker then kills the next job too.
This pach allows cancel commands in form "cancel job_id=1234" and checks if the job_id is the current one.
=> add job_id to worker commands

lib/OpenQA/Scheduler.pm
So we better require a fixed DBIx::Class (unfortunately 13.2 is affected by this)
Also don't put 2 now() in one update call to avoid the harmless but still ugly
warning about possibly corrupt data (I don't see any value in setting the started == finished)
also fix one -in call
=> search()->update() can wipe the entire table

lib/OpenQA.pm, lib/OpenQA/Controller/API/V1.pm, lib/OpenQA/Controller/API/V1/Job.pm, lib/OpenQA/Scheduler.pm, lib/OpenQA/Schema/Result/Jobs.pm, t/04-scheduler.t, t/05-scheduler-dependencies.t, t/07-api_jobtokens.t, t/fixtures/02-jobs.pl
This adds simple job token authentication. Token is stored as JOBTOKEN key in JobSettings table for running jobs only (added during job_grab and removed when job_done and cloning).
For testing purposes added route /api/v1/whoami returning jobid.
added function job_set_settings($jobid, $key, [$value]) for adding (and removing if $value is undef) job settings data
=> add job token auth and job mapping

DEPENDENCIES.txt, dbicdh/MySQL/deploy/25/001-auto-__VERSION.sql, dbicdh/MySQL/deploy/25/001-auto.sql, dbicdh/MySQL/upgrade/24-25/001-auto.sql, dbicdh/PostgreSQL/deploy/25/001-auto-__VERSION.sql, dbicdh/PostgreSQL/deploy/25/001-auto.sql, dbicdh/PostgreSQL/upgrade/24-25/001-auto.sql, dbicdh/SQLite/deploy/25/001-auto-__VERSION.sql, dbicdh/SQLite/deploy/25/001-auto.sql, dbicdh/SQLite/upgrade/24-25/001-auto.sql, dbicdh/_source/deploy/25/001-auto-__VERSION.yml, dbicdh/_source/deploy/25/001-auto.yml, lib/OpenQA.pm, lib/OpenQA/Controller/API/V1/Locks.pm, lib/OpenQA/Locks.pm, lib/OpenQA/Schema/Result/JobLocks.pm, lib/OpenQA/Schema/Result/Jobs.pm, lib/OpenQA/Schema/Schema.pm, lib/OpenQA/Worker.pm, lib/OpenQA/Worker/Commands.pm, t/07-api_jobtokens.t, t/13-joblocks.t, t/api/01-workers.t, t/api/04-jobs.t, t/fixtures/01-workers.pl, t/fixtures/02-jobs.pl, t/ui/10-tests_overview.t
This does **not** pass tests yet since it depends on #188 (and even after merge, there are some renames todo).
**only for *idea* review currently**
One thing I'm considering is to move locking functions (from OpenQA::Locks) directly to DB Object (OpenQA::Schema::Result::JobLocks)
* API is /api/v1/mutex/$cmd/:lockname behind jobtoken auth
* DB consistency managed by optimistic locking
* OpenQA::Worker daemon is removed
=> add DB backed mutex locks

lib/OpenQA/Controller/Running.pm, lib/OpenQA/Controller/Test.pm
This mismatch broke the live log and live view for running tests, and result files and thumbnails for completed tests.
=> fix testdirname for Running and Test (#209)

lib/OpenQA.pm, lib/OpenQA/Controller/API/V1/Mm.pm, t/05-scheduler-dependencies.t
- /api/v1/mm/children/[running|scheduled|done]
+ uses jobtoken auth
+ returns JSON {jobs => [jobids]} or 404 when job not found (can't
happen currently, but after preforking everything is possible)
- test included
- added as first snippet of potential MultiMachine API
=> add checking for children status

lib/OpenQA/Controller/API/V1.pm, lib/OpenQA/Scheduler.pm, t/04-scheduler.t, t/05-scheduler-dependencies.t, t/05-scheduler-restart-and-duplicate.t, t/13-joblocks.t, t/api/04-jobs.t, t/fixtures/01-workers.pl, t/fixtures/02-jobs.pl, t/fixtures/06-job_dependencies.pl
- store JOBTOKEN as WorkerProperty instead of JobSetting
- add dependencies fixtures
- adapt tests
=> action#6344 - prevent JOBTOKEN leak

templates/test/running.html.ep
after 83975e9e , the returned resultset search object looks are different than job_get(), then we missed job id here
=> fix buttons rendering with job id

lib/OpenQA/Controller/Test.pm, lib/OpenQA/Scheduler.pm, lib/OpenQA/Schema/Result/Jobs.pm, public/javascripts/tests.js, public/stylesheets/openqa.css, t/05-scheduler-dependencies.t, t/api/02-iso.t, t/api/04-jobs.t, t/ui/01-list.t
https://progress.opensuse.org/issues/6148
This is not yet ready for production, the UI part is missing. 
plan for UI:
- add cancelled jobs to the list of results
- allow filtering by any combination of results (maybe a multiple selection combobox with all possible results), use reasonable default
=> Job states and results cleanup

lib/OpenQA/Controller/Test.pm, lib/OpenQA/Schema/Result/Jobs.pm, t/ui/10-tests_overview.t, templates/test/overview.html.ep
only look at the DB and only check details of failed modules
while I was at it:
- I moved the link from results to test (also makes sense for
running and scheduled tests)
- I made the failed test jump to the proper step
=> improve speed of tests/overview page

public/javascripts/needlediff.js, public/javascripts/openqa.js, public/javascripts/running.js, templates/layouts/head.html.ep, templates/step/moduleslist.html.ep, templates/step/viewimg.html.ep
while doing this I noticed that the step/src route also used prototype
indirectly through moduleslist.html fragement. So fixing this to
use jquery on jquery routes too
This leaves step/edit and test/running as prototype users (our toughest ones :)
=> needlediff is not really prototype, so porting it to jquery

lib/OpenQA/Controller/Admin/Table.pm, t/ui/13-admin.t
this makes it a bit more useful in real life settings
=> reshuffle the admin tables to allow short values under long texts

lib/OpenQA/Worker/Common.pm
fixes
Use of uninitialized value $_[1] in string at /usr/lib/perl5/vendor_perl/5.20.1/Mojo/Util.pm line 114.
=> don't pass worker class if none is set

systemd/openqa-worker@.service
This seems to be the new plan, as `/var/lib/openqa/pool/*` are now owned by _openqa-worker. Without this change, worker instances cannot create their lock file and fail to start.
Note there's a follow-up issue: workers require the API credentials, but those are in file `/etc/openqa/client.conf` which is owned by geekotest.root with 0640 permissions. I don't know what the most appropriate fix for that is, as presumably we can't just change it to be owned by _openqa-worker.
=> run workers as _openqa-worker, not geekotest

lib/OpenQA/Worker/Commands.pm, lib/OpenQA/Worker/Jobs.pm
I no longer see any undefined vars and obvious recursive 'inceptionisms', but I suspect the weak point now is when job is being stopped, upload_status is called which esp. in case of connection problems with scheduler can cause problems.
=> Worker api_call hotfix

lib/OpenQA/Schema/Result/Jobs.pm
When calculating the overall job result from the modules, check
whether each module's result equals the const PASSED, not the
string 'ok'. Fixes the problem where jobs would show overall
result 'failed' even when all tests passed.
=> fix overall result calculation: check for PASSED not 'ok'

etc/openqa/openqa.ini, templates/layouts/admin.html.ep
proposing just use current->name, the logic inside of schema is nickname first than username, also it's the same way in default view. for fake login it's not a problem, but for openid login is too long.
=> Misc fix 0311

Makefile, lib/OpenQA/Controller/API/V1/Job.pm, lib/OpenQA/Schema/Result/JobModules.pm, lib/OpenQA/Schema/Result/Jobs.pm, lib/OpenQA/Utils.pm, lib/OpenQA/Worker/Commands.pm, lib/OpenQA/Worker/Jobs.pm, profiles/apparmor.d/usr.share.openqa.script.openqa, script/migrate_images, script/optimize_images
- only upload log and screenshot if livelog is wanted
- only update status if there is some, e.g. stay silent if nothing
to say
- upload only the md5sum of the images and wait for the webui
to tell the worker which of these md5sums it already knows
- upload uknown images one by one to avoid long wait times for other
workers/users
- these images are stored in /var/lib/openqa/images under their
md5 and the testresults only get a symlink
=> Trying to get a grip on our worker->webui bandwidth:

lib/OpenQA/Scheduler.pm
make sure that the result PARALLEL_RESTARTED is set only for dependencies,
the caller of job_duplicate is responsible for the main job
=> do not set result of duplicated job

lib/OpenQA/Controller/Running.pm
this reduces the number of redraw events in browser
=> send livelog in bigger chunks

lib/OpenQA/Controller/Test.pm, public/javascripts/tests.js, templates/test/running_table.html.ep, templates/test/scheduled_table.html.ep
- job->parents returns JobDependencies, so job->id still points to ourselves
=> fix dependency ids and links

public/javascripts/needlediff.js
- at least on firefox, jQuery event does not have offsetX so calculate
it from canvas
=> fix needlediff offsets

public/javascripts/tests.js
- because row['deps'] is now ( since #259 ) always passed (usually empty array) check
for length instead of value
=> add tooltips to icons, fix deps detecting

lib/OpenQA/Worker/Common.pm
- simple check if json data are there. I briefly checked and all api calls used by worker should return some json data on success
=> check for json data on success to mark it as success

lib/OpenQA/Controller/API/V1/Job.pm, lib/OpenQA/Scheduler.pm, lib/OpenQA/Schema/Result/Jobs.pm, lib/OpenQA/WebSockets.pm, lib/OpenQA/Worker/Commands.pm, lib/OpenQA/Worker/Common.pm, lib/OpenQA/Worker/Jobs.pm, t/11-commands.t
- by default status updates are send by POST requests, use env var WORKER_USE_WEBSOCKETS to use WS path
- enabled compression for websockets ~~so this needs to be deployed on openqa scheduler and worker at once else nothing will work (I should rewrite this I guess)~~ - should be autonegotiated
=> use websockets for status update

lib/OpenQA/Plugin/Helpers.pm
This changes the format_time() helper which is used in a few
places to produce a human-readable date/time string to specify
the timezone. We could try doing something cleverer using
JavaScript to display them in the user's local time, but that's
more complicated, and this is an easy improvement for now.
This format is not compliant with ISO8601 or RFC2822 or any
other such standard, it's strictly intended for human reading.
=> when formatting a date/time for display, specify the timezone

templates/test/result.html.ep, templates/test/running_table.html.ep
This fixes the display of the 'Testtime' column in the 'running
tests' table and the 'Started' and 'Finished' values in single
test pages, when the browser's timezone is not UTC. The openQA
t_started and t_finished values are always UTC, but when it
passes the values to JScript's timeago() it uses the perl date
objects' datetime() method. This produces a valid ISO8601 date/
time string but with no timezone offset, and an ISO8601 string
with no timezone offset is presumed (per the spec) to be in
the 'local' time. Thus JQuery goes ahead and calculates the
'time ago' value as if the started or finished time was given
in the local timezone, not UTC.
A simple 'Z' as the timezone offset indicates that the date/
time is in UTC, so this simply stuffs a 'Z' on the end of the
datetime() call's …
=> fix 'timeago' display in various places for timezones

lib/OpenQA.pm
If you have CSS::Sass installed, it will take preference - but our packages
will continue building without to avoid one more dependency (and rubygem-sass
was in the distro first :)
=> since mojo-assetpack 0.42 the perl binding works for me

templates/test/scheduled_table.html.ep
983e9de33d7fac0db36a3c980754356b6ac536bf removed the deps table, so we
need to adapt the index of the priority column
=> Fix pagination of scheduled table

lib/OpenQA/Controller/Test.pm, lib/OpenQA/Scheduler.pm, lib/OpenQA/Schema/Result/JobModules.pm
Personal note: Flightplan (2005) is a horribly stupid and boring moving allowing all kind of hacks :)
avoid building hashes that some values are used from and avoid huge
joins. The joins (caused by prefetch) cause a lot of result rows to
be evaluated and dbix needs to pick out the duplicates
In my tests avoiding this leads to a load time reduction from 4s to 0.8s
on /tests (including ajax)
=> speed up lists_ajax by calculating only what we need

lib/OpenQA/Auth/Fake.pm
Makes it easier to keep client.conf around in development
=> always use the same API keys for demo

docs/WritingTests.asciidoc, lib/OpenQA/Schema/Result/Jobs.pm
If there is only one important test at the beginning, it can happen that
half the test suite doesn't run, but the test is considered passed. This
is highly confusing, so make fatal have an impact on the overall state
too
The original documentation is
"whole test suite is in danger if this fails" - so it clearly gives the
impression it *does* have impact on the whole
=> make failing fatal tests have an impact on overall state

lib/OpenQA/Scheduler.pm, lib/OpenQA/Schema/Result/Jobs.pm, public/javascripts/tests.js, t/05-scheduler-restart-and-duplicate.t, t/09-job_clone.t, templates/test/result.html.ep, templates/test/running_table.html.ep, templates/test/scheduled_table.html.ep
- append (cancelled) when job is cancelled from test list
- redirect to new test if test is restarted from result view
- use $job->can_be_duplicated to check if even to display restart icon
- use test name as link even for scheduled tests
There is things I'm not happy about:
- I had a problem with firing double events for restart link until I stopped using $(document).on(..) and moved to $('#restart-result').click. This however needs to be called when restart-result id is know so I added it directly to result.html.ep. I don't think this is right approach.
=> action 6440 - canceling reactions

lib/OpenQA.pm, lib/OpenQA/Controller/API/V1/Iso.pm, lib/OpenQA/Controller/API/V1/Worker.pm, lib/OpenQA/Scheduler.pm, lib/OpenQA/Schema/Result/Workers.pm, lib/OpenQA/Worker/Common.pm, t/04-scheduler.t, t/05-scheduler-capabilities.t, t/05-scheduler-dependencies.t
machines have now a worker_class as can have tests (less likely for products, but possible) - this gives jobs a list of classes to expect
and workers have a list of classes they support and only workers that fullfill all job classes can grab a job. CPU_ARCH is by now only a mean to define a default WORKER_CLASS (e.g. qemu_x86_64)
=> Change backend logic

lib/OpenQA/Scheduler.pm
nasty workaround for regressions of 8caa395
=> don't treat all coma separated values as array

lib/OpenQA/Worker/Common.pm, lib/OpenQA/Worker/Jobs.pm
- reported by maxlin, worker api-call timed out on inactivity from
scheduler side. This does not solve the issue itself, but at least
worker should not force it through with undefined vars
- also die in timer only kills the timer, not the app itself
=> properly exit when scheduler misbehaves

lib/OpenQA.pm, t/13-joblocks.t
- using GET for lock operations was a bad idea (due to possible GET caching by proxy), so get it fixed before wider usage (action#6478)
- has os-autoinst part, so worker&scheduler needs to be redeployed at the same time
=> change lock api to POST method

public/javascripts/running.js
Use the size of the raw image - not of the (already resized) canvas.
=> fix raw image size info in running.js

lib/OpenQA/Scheduler.pm, lib/OpenQA/Schema/Result/Jobs.pm, t/05-scheduler-dependencies.t, t/05-scheduler-restart-and-duplicate.t, t/09-job_clone.t, t/15-assets.t
- move cloning of test dependencies to Jobs schema
- scheduler's job is to set proper states and notify workers
- add asset dependency cloning
+ all children using any asset created by duping job will get
duplicated as well
=> refactor cloning from Scheduler to Jobs schema

lib/OpenQA.pm, lib/OpenQA/Plugin/Helpers.pm
if the plugins create log output, they set the handle in Mojo::Log to STDERR
and it won't be reset afterwards
=> initialize the log path as first step

lib/OpenQA/Controller/Main.pm
our staging prjs have <CI_CNT>.<BUILD_CNT> which makes sorting by number
much harder. So just give up and sort by the timestamp of the oldest job
per build id
This will lead to other use cases being wrongly sorted, but unless we inject
a correct sort externally, there is no perfect sorting
=> sort the build numbers according to time not actual number

docker/README.md, docker/openqa_data/Dockerfile, docker/webui/Dockerfile, docker/worker/Dockerfile
I have updated Dockerfiles according to comments in #340. Changed perl-libs repo to openQA-devel repo (as suggested). Removed `--gpg-auto-import-keys` where is not necessary. Imported openQA repo GPG key rather than accepting it automatically.
There are still some caveats with this. `ca-certificates` is now included in opensuse Docker image, but `ca-certificates-mozilla` is missing, so SSL still doesn't work.
This creates chicken and egg situation - we could download and import GPG keys for repositories instead of importing them with `--gpg-auto-import-keys`, but we are unable to do so, because we are unable to verify destination from where we are downloading them. And passing `--insecure` to curl is in my opinion worse than using `--gpg-auto-import-keys`.
Another problem is that I don't …
=> add correct OpenQA repos to Dockerfiles

lib/OpenQA/Controller/Admin/JobGroup.pm
If $ng is not exist then definitely no $ng->name there, just use $groupname here.
=> Avoid using uninitialed variable

lib/OpenQA/Schema/Result/Jobs.pm, t/fixtures/02-jobs.pl
- action#7442 - LIVETEST variable is not cloned
=> require equal job setting key when cloning

systemd/openqa-worker.target
This makes sure the shared openqa directory gets mounted even if
remote-fs.target is not enabled explicitly on the machine.
=> add var-lib-openqa-share.mount as dependency

lib/OpenQA/Controller/Step.pm, lib/OpenQA/Controller/Test.pm, lib/OpenQA/Worker/Jobs.pm, templates/step/moduleslisttabs.html.ep, templates/step/moduleslistthumbnails.html.ep, templates/step/viewtext.html.ep, templates/test/result.html.ep
- support screenshots (png), audio (wav) and text (txt)
- use md5 for all these files
- dropped broken ocr results, use more generic 'text' instead
=> fixed support for results other than screenshots

lib/OpenQA/Schema/Result/Assets.pm
the creating time of the asset is not important, we want to make sure
it's not used in a while - and that's coded in the relationship to the jobs
=> fix limit_assets

lib/OpenQA/Schema/Result/Jobs.pm
name must be unique, it is also used in step url
script does not have to be unique, one script can upload more
modules (for example parsed from junit file)
=> identify job module by name

templates/test/running_table.html.ep, templates/test/scheduled_table.html.ep
- the time is now always in the last column
- the creation time of scheduled tests is now shown
=> fix issue #6826: make columns consistent on /test

lib/OpenQA/Schema/Result/Jobs.pm, t/05-scheduler-dependencies.t
My previous refactoring attempt had an unintentional side effect of ignoring siblings (and distant relatives too) of cloning job. This was not tested before, now I added test case for this.
Again, diff seems big, but that's mainly due to indentation change. Core of cloning is the same, now cloning just doesn't pass 'ignore_children | ignore_parents' but creates ignore list of cloned jobs and traverse whole family tree.
There is also special treatment (as it was in original @nadvornik's implementation) of *PARALLEL* children when they not running. In that case they are ignored. (Use case is optimization for autoyast test when numerous jobs share one parent (support server) and when some are *DONE* we are happy (even if *failed*) and don't need to rerun them when others are cloned. I …
=> cloning of siblings

lib/OpenQA/Scheduler/Scheduler.pm, t/api/02-iso.t
I did two things here:
1) refactored algorithm to at first create all jobs and create mappings *TESTNAME* -> job_id and then create dependencies
2) put this all as one DB transaction
At first I tried to put the whole original routine to coderef for transaction, but that didn't work. I thought because of mixing create and search calls (which still may be the reason) so I did the refactoring 1).
Initially I put only job creation to transaction, that made perfect sense. But then I added dependency creation to the same transaction and I'm wondering why that works? I thought DBIx transaction worked by executing the perl code and intercepting DB calls, but in that case this workflow should not work (job ids shouldn't be available when dependencies are about to be created). Can this be that i.e. …
=> action#7966 - transactionalize job_schedule_iso

templates/step/src.html.ep
The white spaces in <textarea></textarea> are considered as real white space rather than the indentation. This patch fixes the weird indentation at the souce code view.
=> Do not have the white spaces inside of textarea

templates/main/index.html.ep
When you install a new openQA front end, the title page has just the
project advertisement, without linking to the actual results most people
are interested in.
Groups only help once you learn how to define some.
Therefore a link to /tests is added.
=> Link to All Test Results from the front page.

etc/openqa/openqa.ini, lib/OpenQA/WebAPI.pm, t/config.t
If you need to deal with two or more instances of openQA at the same
time it will help if all the browser tabs start with something more
unique than "openQA".
Tested to work on https://mrakoplas.suse.cz
=> Made website name (openQA) customizable.

templates/test/list.html.ep
casting dbix queries seems to translate into COUNT(*) calls now, which
are not what we want - we want the limit of 500 to take into account
=> make sure we take the limit into account

DEPENDENCIES.txt, lib/OpenQA/Utils.pm, lib/OpenQA/WebAPI/Controller/Step.pm, t/16-utils-runcmd.t
Adds new dependency: perl(IPC::Run::Debug)
This patch is not tested, yet.
=> fix issue #6394: capture git stderr/stdout

lib/OpenQA/Schema/Result/Assets.pm
We shouldn't just blindly die if we can't open a directory
that doesn't even exist, just in order to check if some files
in it are registered assets. If it doesn't exist, it's not going
to contain non-registered assets.
This is perhaps a bit academic for /iso, which is probably
always going to exist, but it isn't for /repo, which is SUSE-
specific at present and entirely optional.
NOTE: shouldn't this also be using `OpenQA::Utils::isodir` not `$OpenQA::Utils::assetdir . "/iso"`?
=> limit_assets: check asset dirs exist before accessing them

docs/GettingStarted.asciidoc, lib/OpenQA/Scheduler/Scheduler.pm, t/api/02-iso.t, t/api/07-testsuites.t, t/fixtures/04-products.pl
This allows easy building of images with naming scheme
distribution-architecture-variant.qcow2
which was requested by Eric for slenkins.
=> preprocess hdd image names

lib/OpenQA/Scheduler/Scheduler.pm, lib/OpenQA/WebAPI/Controller/API/V1/Job.pm, t/04-scheduler.t
The main thing I wanted to do here was allow for specifying job IDs when searching. Sometimes we just want to query some specific set of jobs; this lets us do it with one query instead of running a single query for each job.
While I was working on it I noticed there's kind of an inconsistency in how `query_jobs()` handles args which can be lists of values (`ids` and `state`, for now). For `state` it expects a comma-separated list, but for `ids` it expects (I think) an array reference. I thought it would be a good idea to clean that up a bit: the safest thing to do seemed to be to handle both of the styles for both cases (and make it so others can be added if wanted). With this, comma-separated lists get turned into array refs right at the start, everything further down can assume it's …
=> Query job ids

templates/step/edit.html.ep
fix https://progress.opensuse.org/issues/8800
=> fix ticket #8800: add needle editor readonly mode

dbicdh/MySQL/deploy/33/001-auto-__VERSION.sql, dbicdh/MySQL/deploy/33/001-auto.sql, dbicdh/MySQL/upgrade/32-33/001-auto.sql, dbicdh/PostgreSQL/deploy/33/001-auto-__VERSION.sql, dbicdh/PostgreSQL/deploy/33/001-auto.sql, dbicdh/PostgreSQL/upgrade/32-33/001-auto.sql, dbicdh/SQLite/deploy/33/001-auto-__VERSION.sql, dbicdh/SQLite/deploy/33/001-auto.sql, dbicdh/SQLite/upgrade/32-33/001-auto.sql, dbicdh/_source/deploy/33/001-auto-__VERSION.yml, dbicdh/_source/deploy/33/001-auto.yml, lib/OpenQA/Scheduler/Scheduler.pm, lib/OpenQA/Schema/Result/Assets.pm, lib/OpenQA/Schema/Result/GruDependencies.pm, lib/OpenQA/Schema/Result/GruTasks.pm, lib/OpenQA/Schema/Result/Jobs.pm, lib/OpenQA/Schema/Schema.pm, lib/OpenQA/WebAPI.pm, templates/test/result.html.ep
This is an extremely stupid PoC implementation; it blocks the
POST request until the download is done, which likely isn't
what we want. But for some value of 'work', it does work: when
I tried it, the 'client' command returned some ERROR, but the
ISO was downloaded and the job scheduled and ran successfully.
I think a sane implementation might use this 'GRU' thing I'm
now trying to grok. It might look something like 'create the
jobs, tell the GRU to download the ISO and notify workers when
it's done, return job IDs'. It occurs to me that might be
rather racy, though - if any other job-create-y type thing
happens while the ISO is downloading, workers will presumably
try and pick up the jobs and Bad Stuff will happen.
Perhaps jobs should have some kind of 'not ready yet' attribute
which …
=> allow ISO to be a URL, download if needed

script/create_admin
This is to aid automated deployments, to avoid the need to use
the web UI to create the initial admin account and an API key
for worker deployment. Instead you can run this script to create
an initial user account and an API key.
=> add a script to create admin user and API key

script/initdb
=> the sqlite database should be only readable by the owner.

lib/OpenQA/WebAPI/Controller/Step.pm
Can't locate object method "scm" via package "git" (perhaps you
forgot to load "git"?) at
/usr/share/openqa/script/../lib/OpenQA/WebAPI/Controller/Step.pm
line 367.
=> add missing quotes

docs/Branding.asciidoc, lib/OpenQA/WebAPI/Plugin/Helpers.pm, templates/branding/openSUSE/head_stylesheet.html.ep, templates/branding/openSUSE/header.html.ep, templates/branding/openSUSE/navbar.html.ep, templates/branding/openSUSE/sponsorbox.html.ep, templates/branding/plain/head_stylesheet.html.ep, templates/branding/plain/header.html.ep, templates/layouts/bootstrap.html.ep, templates/layouts/default.html.ep, templates/layouts/head.html.ep, templates/main/index.html.ep
The very SUSE-y topbar is still present on all pages even if you set branding to 'generic'. header.html.ep has some kind of similar thing which *is* conditional on the branding setting, so it seems reasonable to do the same here.
We don't mind crediting openSUSE at all! So we wouldn't actually mind if the 'generic' branding had some kinda nice credit thing somewhere. But the navigation bar seems much more SUSE-specific chrome than really credits, it seems reasonable to remove it for the 'generic' branding.
I also made the file use all spaces rather than mixed spaces and tabs, you can see the functional change in the *second* commit.
=> More branding

lib/OpenQA/Scheduler/Scheduler.pm, lib/OpenQA/Schema/Result/Assets.pm, lib/OpenQA/Schema/Result/Jobs.pm, lib/OpenQA/Utils.pm
posting to the iso controller may not generate jobs if job templates
don't exist. Still the assets might already be there but unknown to
openQA.
=> register assets directly when posting an iso

lib/OpenQA/Worker/Engines/isotovideo.pm, script/openqa, script/worker
adam made me install perl-EV and now I know it's broken. Once it's in,
it will install a SIGCHLD handler reaping all children and we no longer
have any way to get the exit status of isotovideo
=> Make sure EV is not polluting our signals

t/ui/05-auth.t, t/ui/12-needle-edit.t, t/ui/13-admin.t, t/ui/15-admin-workers.t, templates/layouts/bootstrap.html.ep, templates/layouts/default.html.ep
The description when a user is logged in was "Logged as". This change corrects all code references by providing the more usual "Logged in as" as text.
=> Replace 'Logged as' with 'Logged in as'

docs/GettingStarted.asciidoc
Looking through the documentation and at a recently installed OpenQA instance, I didn't find the term 'Product' in the admin interface. I realized that the 'Medium type' menu entry corresponds to the seemingly previous 'Product' menu entry and decided to update the docs. Please consider.
=> Adding "medium type" as an interchangeable term with "product"

docs/GettingStarted.asciidoc
I was trying to load the templates using the script and kept getting *missing apisecret and/or apikey at /usr/share/openqa/script/load_templates line 204.*. Decided to had documentation on setting them, after reading the docs for */usr/share/openqa/script/load_templates*. Please consider.
=> Adding argument docs to template loading script

Makefile
openqa.ini doesn't contain anything particularly secret so far
as I can tell, but database.ini may contain a password, for
mysql / pgsql cases. So it seems to make much more sense this
way around.
=> adjust config permissions: openqa.ini 0644, database.ini 0640

lib/OpenQA/Schema/Result/Assets.pm
95bdd266 should've set up cleanup of job-created HDD snapshots
in limit_assets, only it didn't quite, because remove_from_disk
doesn't work for hdd assets; the upshot is that the asset gets
removed from the database but the file is left on disk.
It's also worth noting that two other checks in limit_assets
don't work for job-created HDD snapshots: the check for assets
that aren't in any job group, and the check for files that are
not registered assets. I took a shot at fixing those but it
seems like it doesn't really work for the snapshot assets, I'm
not entirely sure why, probably something to do with the file
names that include job IDs.
=> Assets remove_from_disk: actually delete hdd images

docker/webui/Dockerfile
The package "apache2" need to be installed which did not a dependency of openQA.
=> Add apache2 because it will not autoselected as dependency

lib/OpenQA/Schema/Result/Comments.pm
Can also be splitted into individual commits as desired
=> Add comment autoreplace for t#, poo# and generic http(s)

lib/OpenQA/Schema/ResultSet/Jobs.pm, lib/OpenQA/WebAPI/Controller/API/V1/Job.pm, lib/OpenQA/WebAPI/Controller/Test.pm, t/10-jobs.t
This is my first cut at #436. It takes the 'latest jobs' logic
from the 'overview' web UI function and makes it into a method
in ResultSet::Jobs. Then it exposes it via the web API: you
can pass 'latest' as a query parameter (set to anything) and
only the latest jobs will be included in the results. The logic
works as before.
This is broadly along the lines suggested by @coolo in #436,
but I'm not sure how happy I am with the result, improvement
suggestions welcome. We *could* still put this in query_jobs
by having it iterate through the resultset and find the IDs of
the 'latest' jobs then produce a new resultset filtered by
those IDs, but I'm not sure if that'd be better.
=> move 'latest jobs' logic from overview to ResultSet::Jobs

etc/openqa/openqa.ini, lib/OpenQA/WebAPI.pm, lib/OpenQA/WebAPI/Controller/Admin/AuditLog.pm, lib/OpenQA/WebAPI/Plugin/AuditLog.pm, t/config.t, templates/admin/audit_log/index.html.ep
- use [global]:audit_enabled to switch auditing off/on
- use [audit]:blacklist to list events which should not be logged
(by default job_grab and job_done)
- audit log admin page prints "auditing disabled" if auditing is globaly
disabled
=> auditing configuration

lib/OpenQA/Schema/Result/JobModules.pm, lib/OpenQA/Schema/Result/Jobs.pm
Need to update the symbolic link of screenshot in interactive mode if
the screen is changed, therefore updating the symbolic link once the
screenshot's md5 was changed.
=> Re-create the symbolic link of screenshot in interactive mode

etc/openqa/openqa.ini
this avoids people setting only httpsonly = 0
which gets ignored when the [openid] tag is commented
and confuses+frustrates people
=> uncomment [openid] tag

lib/OpenQA/WebAPI/Controller/File.pm
Going through DBUS for every thumbnail on the test result page is a
pretty interesting way to slow down openQA
=> Don't rely on IPC for thumbnails

lib/OpenQA/WebAPI/Controller/Admin/AuditLog.pm
- else audit log prints first 300 events instead of latest
=> Reverse auditlog event sorting order

.gitignore, .travis.yml, Makefile, cpanfile, lib/OpenQA/Schema/Result/Comments.pm, lib/OpenQA/WebAPI/Controller/Step.pm, t/ui/15-comments.t
WebAPI: Correct typo in comment
Extend URL replace for 't#' references into test modules
Correct rendering of URLs in comments
Makefile: Prevent double call of 'tidy --check'
Call same style checks from both Makefile and .travis.yml
.gitignore: Ignore all test generated data
=> Comment URL rendering; Merge Makefile/travis style checks; gitignore

.travis.yml, Makefile
The Makefile now features separate target to execute tests and gather coverage
data plus explicit target names for the report generation in 'coveralls'
format for travis CI and coveralls checks and 'html' format which we can use
for displaying locally.
Related issue: https://progress.opensuse.org/issues/10262
=> Add make targets for coverage analysis

docker/webui/Dockerfile, docker/worker/Dockerfile
According to issus #524  , the old ones in Dockerfile were outdated.
=> Change _pubkey url for devel:openQA and Virtualization repository

lib/OpenQA/Schema/Result/Assets.pm
ensure_size on hdd images returned always zero and gru task limit_assets deleted them immediately.
=> fixed asset ensure_size

Makefile, script/check_coverage
Prevent test coverage drop with automatic check
The Makefile now features separate target to execute tests and gather coverage
data plus explicit target names for the report generation in 'coveralls'
format for travis CI and coveralls checks and 'html' format which we can use
for displaying locally.
We can now also call the new script 'check_coverage' which parses the HTML
coverage report for the 'total' coverage. The check fails with an error
message if the coverage drops below the threshold defined in the Makefile.
This way we can prevent further unintended coverage drop while allowing to
adjust the threshold when necessary. However we should try to increase the
threshold over time which could also be done by marking "uncoverable"
statements.
Fixes …
=> Prevent test coverage drop with automatic check

lib/OpenQA/Scheduler/Scheduler.pm, lib/OpenQA/WebAPI/Controller/API/V1/Job.pm, lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm, lib/OpenQA/WebAPI/Controller/Test.pm, t/04-scheduler.t, t/ui/10-tests_overview.t
This allows e.g. to show only failed builds. Could be included like in http://lists.opensuse.org/opensuse-factory/2016-02/msg00018.html for "known defects"
* WebAPI: Test: Provide advanced query parameters for filtering
* Scheduler: Allow build filtering by result
* WebAPI: Test: Simplify group search
* WebAPI: Test: Simplify use of args
* Delete obsolete references to 'fulldetail'
* Fix api/v1/job_templates for empty groups/machines
=> Allow group overview query by result

lib/OpenQA/Schema/Result/Jobs.pm, lib/OpenQA/Utils.pm, lib/OpenQA/Worker/Engines/isotovideo.pm
Allow to accomodate multiple "main.pm" and accompanying needles directory
depending on product while still sharing same tests.
PRODUCTDIR is discovered from trying to find directories inside "casedir".
PRODUCTDIR is forwarded to os-autoinst along with CASEDIR.
If a test distribution with the new folder structure is used it needs support
for PRODUCTDIR in os-autoinst. It should be save to install this new version
of openQA in an environment with old os-autoinst as well as an old set of
test.
Verified with a local installation of os-autoinst, openQA and
os-autoinst-distri-opensuse.
os-autoinst added support for a productdir in:
https://github.com/os-autoinst/os-autoinst/pull/376
=> Add PRODUCTDIR variable to support multiple main.pm/needles - Alt. to #505

lib/OpenQA/Scheduler/Scheduler.pm, lib/OpenQA/Schema/Result/JobSettings.pm
Split the JobSettings query into a subquery. This helps the query analyzer
getting the jobs with the right settings in one loop instead of 3 intersected
loops.
Reduces the runtime from 55s to 0.02s
=> Improve query_jobs performance

docker/openqa_data/data.template/conf/openqa.ini, etc/openqa/openqa.ini, lib/OpenQA/WebAPI.pm
in Fedora package review it became apparent that logging to a
file is rather more complex in terms of packaging and system
security than it might appear. Logging to the journal is kinda
a good practice on systemd distros (i.e. all the ones we care
about) in any case, and we can easily default to it by leaving
the 'file' setting undefined by default. Admins who want to log
to a file still easily can by defining the 'file' setting, and
then the security issues are all theirs to deal with...
This isn't very sophisticated (the severity of the messages
isn't transmitted to journald, for instance) but works well
enough, seemingly.
This change will affect existing deployments which do not have
the `file` setting in the config file explicitly specified.
This is a trivial change technically …
=> log to stderr (so journal) by default

.travis.yml
The coverage analysis with 'make coverage-check' has been working for some
commits and the 'coveralls' integration is still not reporting anything on
pull requests. This change enables checking coverage against the threshold as
defined in the Makefile and will make the travis builds report a failure if
the coverage is decreased below the threshold. Acceptable coverage drops can
be accepted by decreasing the threshold.
=> .travis.yml: Arm coverage check against threshold after tests

lib/OpenQA/Schema/ResultSet/Jobs.pm, lib/OpenQA/WebAPI/Controller/Test.pm, public/stylesheets/openqa.css, t/api/04-jobs.t, t/fixtures/02-jobs.pl, t/ui/01-list.t, t/ui/10-tests_overview.t, t/ui/15-comments.t, templates/step/edit.html.ep, templates/test/overview.html.ep, templates/test/result.html.ep
The availability of comments on the test result page is shown on the test
result overview page next to the status icon and failed modules if available and if selected with the corresponding query parameter "show_comment=1".
The icon only appears if comments are available. This way it should be much
easier for reviewers of test runs to exchange and see if an issue has already
been noticed by someone else.
Be aware that so far the comments are per test result not per test case or
scenario.
Related issue: https://progress.opensuse.org/issues/10212
see screenshot for example with hover info:
=> Highlight available test result comments on overview

script/initdb
Fedora package review pointed out that `database.ini` should
probably be owned by root with permissions 0640 - there is no
need for geekotest to be able to write to it. However, if we
do this, `initdb` has problems. If you pass --user it wants to
switch to that user; then, when writing an sqlite file, it
tries to switch to the user and group that owns the directory
the file will live in (so it writes the file owned by that user
and group).
This kinda breaks if we do the initial user switch before
reading the config file (i.e. calling `connect_db`). If the
config file is root.geekotest 0640 and we `setuid` to geekotest
because we were called with `--user geekotest`, we now cannot
read the config file and we fail. If we `setgid` to geekotest's
GID as well, then we can read the config file, …
=> initdb: when --user set, setgid and don't guess db owner

script/upgradedb
This just matches the recent change for initdb, so we switch to
the appropriate GID for the user specified with --user as well
as the appropriate UID.
=> setgid as well in upgradedb (like in initdb)

lib/OpenQA/Schema/Result/Comments.pm, lib/OpenQA/Utils.pm, lib/OpenQA/WebAPI/Controller/Test.pm, lib/OpenQA/WebAPI/Plugin/Helpers.pm, public/stylesheets/openqa.css, t/ui/15-comments.t, templates/test/overview.html.ep
* Show bug icon with URL if mentioned in test comments
* Show bug or label icon on overview if labeled
Example for a generic label:
Example for bug label:
I would like to update documentation and help texts accordingly if someone could provide me a hint where this would be appropriate or how we can add the corresponding user documentation.
Related issue: https://progress.opensuse.org/issues/10212
Tested against production database dump from openqa.opensuse.org, querying with
```
time sudo -u geekotest OPENQA_CONFIG=local/stage OPENQA_DATABASE=stage script/openqa get '/tests/overview?version=Tumbleweed&groupid=1&build=20160130&distri=opensuse' >/dev/null 2>&1 | grep real ; time sudo -u geekotest OPENQA_CONFIG=local/stage OPENQA_DATABASE=stage script/openqa get '/tests/117629' >/dev/null …
```
=> Show bug or label icon on overview if labeled

docs/Contributing.asciidoc
"rules for commits" is an adaption of
https://github.com/os-autoinst/os-autoinst#rules-for-commits
for openQA. Initially I thought we should reference
"os-autoinst" rules but as the tidy path as different as
well as the Makefile and the tests take longer than
os-autoinst I adapted the section for openQA and included
it as another subsection splitting the current
"Development" guidelines in a general section and two
subsections "Rules for commits" and
"Getting involved into development".
Old references to two-week sprints and google hangout
calls are removed and replaced by a reference to the IRC
channel and a notice about a "jangouts" call for the
core developer team without further details.
One reference to "openQAv2" which was pointing to
"openqav3" on progress.opensuse.org is corrected …
=> docs: Update Contributing guide

systemd/openqa-worker@.service
systemd interprets %u differently now:
https://github.com/systemd/systemd/commit/79413b673b45adc98dfeaec882bbdda2343cb2f9
That results in pool directories owned by root
=> adjust openqa-worker service for new systemd

lib/OpenQA/WebAPI/Controller/Session.pm
When `/login` path is entered manually then there is no referral and final redirect is either back to '/login' in case of Fake and iChain auth, or to '/response' in case of openID auth. Either way it results in openQA error.
Redirect to index if referral is missing.
=> Redirect to index page when referral is missing

script/generate-packed-assets
This is to support Zbigniew's proposal to do asset generation
with RPM triggers instead of in %install; if we think that's a
good idea, it makes sense to me to have the script in openQA
rather than adding it to packages as a separate SOURCE. I even
tried to make it so this could also be used for %install-style
generation if someone doesn't want to use triggers or their
distro's equivalent, so at least we're all using the same code
and there's less ugly crap in spec files.
I can't personally see any security implications in allowing
specification of the prefix as an arg like this, but please yell
if you can. I *think* anyone who could manipulate the call to
the script to call some other executable would have much easier
ways to exec stuff anyway - they'd have to be able to modify
the …
=> add generate-packed-assets script for asset generation

Makefile
the openSUSE spec file removes these after 'make install'. Why
not just fix the Makefile instead?
=> don't install tidy and check_coverage

systemd/openqa-gru.service, systemd/openqa-scheduler.service, systemd/openqa-websockets.service, systemd/openqa-webui.service
If the database is running on the same system, we want to make
sure it's up before we try and start the scheduler, webUI and
websockets. As we support both postgre and mariadb, list both.
gru already has postgresql, but add mariadb for it.
webui and websockets currently are ordered after scheduler, so
we don't really need to do this in all three, but we may as
well just in case that changes.
=> systemd: start scheduler (and webui and websockets) after dbs

etc/openqa/openqa.ini, lib/OpenQA/Scheduler/Scheduler.pm, lib/OpenQA/Schema/Result/Assets.pm, lib/OpenQA/Utils.pm, lib/OpenQA/WebAPI.pm, lib/OpenQA/WebAPI/Controller/API/V1/Iso.pm, lib/OpenQA/Worker/Common.pm, lib/OpenQA/Worker/Engines/isotovideo.pm, t/05-scheduler-iso.t
this is to make it possible to do 'remote scheduling' (where
the scheduler runs on some machine which does not have access
to the openQA 'factory' directory) of jobs that boot using a
kernel and/or initrd and/or hdd image, just as the 'ISOURL'
feature made it possible for jobs that boot using an ISO. I had
to change a few other things to be happy with it, though.
The convention now is you can request openQA download for any
asset type, by adding _URL to the appropriate setting name. To
download the ISO set 'ISO_URL', to download a kernel set
'KERNEL_URL', and so on. The POST will error out if you try to
download something that is *not* an asset type. This is because
we can't really guess where we should store non-assets.
As with the old ISOURL code, if you set the normal setting
(ISO, …
=> treat kernels / initrds as assets, allow download of all assets

cpanfile, t/05-scheduler-iso.t
Cleanup test to not spill expected warnings. Also use better test comparison
methods with better feedback on the expected and actual values when a test
fails.
=> t: Catch expected warnings in 05-scheduler-iso

lib/OpenQA/WebAPI/Controller/Main.pm, public/stylesheets/openqa.css, t/ui/15-comments.t, templates/main/group_builds.html.ep
Based on comments in the individual job results for each build a certificate
icon is shown on the group overview page as well as the index page to indicate
that every failure has been reviewed, e.g. a bug reference or a test issue
reason is stated. Only the failed and incomplete jobs are regarded for the
evaluation if a build is considered "reviewed".
Tested against a production database dump and no performance impact could be
found when rendering the index page.
=> Show certificate next to builds on overview if all failures are labeled

docs/Installing.asciidoc
supersedes https://github.com/os-autoinst/openQA/pull/474
=> Add links to Leap and TW repositories to installation instructions

.travis.yml
Before this travis CI tests fail with ugly warnings like
```
./t/05-scheduler-dependencies.t ........... 5/155 Can not create MOJO_TMPDIR :
mkdir /var/lib/openqa: Permission denied at lib/OpenQA/WebAPI.pm line 267.
```
like in https://travis-ci.org/os-autoinst/openQA/builds/111199183
=> .travis.yml: Fix warning about unwriteable MOJO_TMPDIR in travis CI

Makefile
* Makefile: Make prove arguments overridable from outside
* Makefile: Prevent double coverage evaluations
=> Makefile extensions for test and coverage

lib/OpenQA/Utils.pm
Scheduler doesn't have Mojo::app, so either this to print stdout/stderr and let it capture by journald or introduce Mojo::Log.
=> Log to stdout/stderr when Mojo::Log is unavailable

lib/OpenQA/WebAPI/Controller/Test.pm
The 'latest_jobs' are queried anyway and gathering job module stats as well
as calculating the preferred machines should be done on latest jobs. Acting
on all potential jobs returned by the query is a stupid idea especially if
there are many jobs within a build but not necessarily the latest.
This fixes a performance regression when calling the overview page on
openqa.suse.de for some builds.
Performance was measured retrieving
'/tests/overview?distri=sle&version=12-SP2&build=1204&groupid=25'
with a database dump from openqa.suse.de from 2016-02-26.
Performance results:
before: 120s
after: 27s
Obviously "27s" is still not what we would desire or what we are used to in
other builds but this is the "worst case scenario" I found.
The four most expensive queries are:
```
before:
12.45848107 …
```
=> Optimize overview page rendering by only acting on latest jobs

lib/OpenQA/WebAPI/Controller/Main.pm, lib/OpenQA/WebAPI/Controller/Test.pm, t/ui/01-list.t, t/ui/02-list-group.t, t/ui/14-dashboard.t
* Add optional query parameters to configure builds limit
* t: Delete dead code
* Add optional query parameters for showing previous builds
=> Add more query parameters for configuring last builds

cpanfile, lib/OpenQA/Scheduler/Scheduler.pm, t/05-scheduler-iso.t
When *_URL variable is not meant to be downloaded from and doesn't contain
file name part, `$args{$short}` would be undef. job_create then fail when
writing new job to database.
=> Prevent undef in job settings

script/fetchneedles
Depending on the location of main.pm in the cloned test distribution
fetchneedles selects the corresponding needles directory.
See
https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/920
for the corresponding os-autoinst-distri-opensuse change.
=> fetchneedles: Also support "productdir" layout

etc/apache2/vhosts.d/openqa-common.inc, lib/OpenQA/Client.pm, systemd/openqa-webui.service
To make scheduling our ISOs more reliable, we need to bump timeouts - our API is just not made for short timeouts ;(
=> Remove timeout

README.asciidoc
No need to confuse people with a 'random' last PR build status.
=> Travis badge should show only master branch

lib/OpenQA/WebAPI.pm, t/12-profiler.t
Without it the prefork workers pollute each other and it makes hard to follow
what's going on
=> Add the PID to the log output

lib/OpenQA/Worker/Jobs.pm
If the worker is not setup to allow it, the webui can't take it over
=> Do not allow the job to inject a GENERAL_HW_CMD_DIR variable

lib/OpenQA/Schema.pm, lib/OpenQA/Test/Database.pm, lib/OpenQA/WebAPI.pm, script/initdb, script/upgradedb, t/deploy.t
Preparing the database upgrade is the same as before, but manual
initdb resp. upgradedb call to perform initialization resp. upgrade
is not needed.
Upon first connect, openQA will check if database contain schema version.
If none is found, db is initialized. Else it is compared to current available
schema version and if not matching, upgrade is done automatically.
=> Init or upgrade schema from openQA

docs/GettingStarted.asciidoc, docs/Installing.asciidoc
This updates InstallGuide and GettingStarted to be a little
more distro-agnostic (i.e. include instructions for Fedora, and
flag up openSUSE-specific things like some variables). It also
just brings a few things up to date, and adds some missing bits
like instructions on how to set up pgsql/mysql.
=> make docs more distro-agnostic, update a bit

docs/GettingStarted.asciidoc
The path for script  loading opensuse templates has changed:
-/var/lib/openqa/share/tests/opensuse/templates
+/var/lib/openqa/share/tests/opensuse/products/opensuse/templates
/var/lib/openqa/share/tests/fedora/templates
=> Update  GettingStarted.asciidoc - fix path of template load script

lib/OpenQA/WebAPI/Controller/Main.pm, t/ui/14-dashboard.t
In case too many jobs are found, the group result parsing truncates the number
to prevent a query on too many jobs to cope with in reasonable time.
Related progress issue: https://progress.opensuse.org/issues/10960
=> Truncate the number of jobs parsed to prevent overload

etc/openqa/openqa.ini, lib/OpenQA/WebAPI.pm
For now this only loads plugins for openqa-webui, and expects
them to be placed in WebAPI/Plugin . You can specify the config
setting 'plugins' as a space-separated list of module names of
plugins to be loaded, e.g. 'plugins = Fedmsg' would cause the
plugin WebAPI::Plugin::Fedmsg to be loaded.
We might want to define a different location for external
plugins, or allow loading of plugins for other bits of openQA,
or allow some kind of way to specify arguments to be passed to
the plugin...this is just a simple starting point for a PR.
The motivation here is to let me load a fedmsg plugin for
Fedora's openQA; I could just send a PR with a special config
key like the one for the AuditLog plugin, but that doesn't
seem like a particularly extensible approach, and it'd be odd
for openQA to have …
=> allow loading of arbitrary plugins from config file

lib/OpenQA/WebAPI/Controller/API/V1/Job.pm, t/api/04-jobs.t
@k0da would like this for some TTM hacking and I think it's generally useful.
This allow `/api/v1/jobs` to accept result parameter either with single value or comma separated values.
=> Allow /api/v1/jobs get request to filter by result

lib/OpenQA/Utils.pm, lib/OpenQA/WebAPI.pm, lib/OpenQA/WebAPI/Controller/File.pm, lib/OpenQA/WebAPI/Controller/Step.pm, public/javascripts/needleedit.js, script/clean_needles, templates/step/edit.html.ep
This is a part of implementation (together with a patch for os-autoinst <https://github.com/os-autoinst/os-autoinst/pull/452>) that adds the foundations for directory nesting of needles. The problem is initially described in this issue: https://github.com/os-autoinst/os-autoinst/issues/426
Overall, the implementation strives to make backward-compatible changes, so although new testruns will store additional information, there should not be errors in viewing older results.
This patch uses the newly added `file` item from the result's matchfile, which contains path to the respective needle's json file definition. This item is then used in the OpenQA's needle editor to provide the desired functionality.
Most of the changes are about handling the (possible) reference to the needle's json …
=> Foundations for directory nesting for needles

lib/OpenQA/WebAPI.pm, t/ui/06-operator_links.t, t/ui/13-admin.t, t/ui/15-admin-workers.t, templates/layouts/admin_nav.html.ep, templates/layouts/bootstrap.html.ep
Operators can change things like test templates, media, machines already, but only using API. This PR allows operators to use web ui to view and modify test templates, job groups, product media, etc.
User management, audit log and needle management remain as admin only.
Screen from admin perspective:
Screen from operator perspective:
=> Admin UI for operators

lib/OpenQA/Schema/Result/Jobs.pm, t/05-scheduler-dependencies.t
Ignorelist used as a means to prevent endless duplication in case
of loops also prevented of recreating such loops, thus removing
dependencies.
Here we properly track graph traversal - mark jobs in process of
cloning, already cloned jobs and the rest is not yet touched:
When job with cloning in process is encountered it is ignored,
that job is then responsible for creating proper dependency.
When already cloned job is encountered, we're the one
responsible for dependency creation so create it.
When job is not yet tracked, we are visiting it first time,
move processing to this job (DFS approach as before
Tests included
=> Fix cloning of jobs when they were in multiple dependencies (action#10456)

lib/OpenQA/WebAPI.pm, lib/OpenQA/WebAPI/Controller/API/V1.pm, public/javascripts/admintable.js, public/javascripts/assets.js, t/api/02-assets.t, t/api/02-iso.t, t/api/05-machines.t, t/api/06-products.t, t/api/07-testsuites.t, t/api/08-jobtemplates.t, t/fixtures/03-users.pl, t/ui/04-api_keys.t, t/ui/13-admin.t, templates/admin/group/index.html.ep, templates/admin/job_template/index.html.ep, templates/admin/machine/index.html.ep, templates/admin/product/index.html.ep, templates/admin/test_suite/index.html.ep
Operators are supposed to handle job management and not managing admin templates. But it is useful for them to see how is it all set up. This PR at first limit API and UI access to modifying operations for operators and then set all admin tables as disabled to signal r/o access.
Tests are adapted and extended.
Action#11368
=> limit operators ability to modify admin tables

lib/OpenQA/WebAPI.pm, lib/OpenQA/WebAPI/Controller/API/V1/Job.pm, templates/step/edit.html.ep, templates/step/src.html.ep, templates/step/viewaudio.html.ep, templates/step/viewimg.html.ep, templates/step/viewtext.html.ep, templates/test/list.html.ep, templates/test/result.html.ep, templates/test/running.html.ep, templates/test/running_table.html.ep, templates/test/scheduled_table.html.ep, templates/test/tr_job_result.html.ep
- for some reason the comment suggested one can use job name instead of
job id, but mentioned routes called functions which doesn't work with
jobs names quite a long time so move them to retular jobid based route
- also ensure that passed jobid is interpretted as numeric value ( this solves https://github.com/os-autoinst/openQA/pull/617#discussion_r57637315 )
=> API for job cancel|restart|duplicate can use only job ids

lib/OpenQA/WebAPI.pm, lib/OpenQA/WebAPI/Plugin/Fedmsg.pm, t/18-fedmsg.t
As @aaannz is interested in using this plugin, we may as well
make it part of upstream openQA. It simply relays some openQA
signals as fedmsg signals, for now using the 'fedmsg-logger'
command as we don't have Perl bindings for fedmsg and I don't
feel a lot like writing them. You need to have a correct fedmsg
relay config in place to use this; for local testing it will
suffice to install fedmsg-relay with its default config and run
it, that will emit the messages on the local fedmsg instance.
For production use, you need an appropriate relay_inbound
setting which points to an active->passive relay for the real
fedmsg instance, and probably you'll want to ensure a cert and
key are in place for message signing, with prefix 'openqa'.
The logic for adding the 'remaining' count could perhaps …
=> add fedmsg emitter plugin, bit more commenting for plugin load

cpanfile
this requirement comes with the fedmsg plugin tests, I forgot
to add it in that commit. Sorry!
=> cpanfile: require Test::MockModule for tests

lib/OpenQA/Scheduler/Scheduler.pm, lib/OpenQA/WebAPI/Controller/API/V1/Job.pm, t/api/04-jobs.t, t/fixtures/02-jobs.pl
This fixes #636. We need to be able to list jobs with specified `HDD_1` (because some of our tests will not have `ISO` set). This adds this functionality rather trivially - being able to specify what HDD to query would make code more complex and it's not needed by us, but it's doable if required.
=> Add possibility to query jobs by HDD_1

lib/OpenQA/Schema/Result/Jobs.pm, t/17-labels_carry_over.t
Iterate through the last 20 jobs of that scenario and consider all
failures that failed the same as the current job if the job didn't
change failure reason 5 times in between
So temporarly broken builds don't erase our carry over line.
Also add an extra line to the comment marking where it taken over so
the reviewer can check if it's indeed the same failure
=> Extend the carry over logic

lib/OpenQA/WebAPI/Controller/Test.pm
for bug references it's important we look for the comments in the right order
=> Fix bug references in overview:

lib/OpenQA/Schema/Result/Jobs.pm
Hopefully this will help us keep them synced up.
=> add a note that job constants are duped in Python client

lib/OpenQA/WebAPI/Controller/Test.pm
This filters out all jobs that are (most likely) not necessary to review
=> Overview: support optional parameter todo=1

lib/OpenQA/WebAPI.pm, lib/OpenQA/WebAPI/Controller/API/V1/Job.pm, t/api/04-jobs.t
This adds possibility to cancel jobs by settings, for example to cancel all jobs for specified BUILD. This functionality was already provided by `job_cancel_by_settings` call, but it wasn't in API.
Note that although I tried to add tests, they fail - canceling running jobs in tests doesn't work for some reason (even canceling by `id`).
=> Add possibility to cancel jobs by settings via API

docs/WritingTests.asciidoc
Please check this over as I still might be missing something,
but as they stand these are definitely wrong. If the lock does
not exist `mutex_unlock` returns immediately, it does not block
until it exists as the doc claims. Actual SUSE practice confirms
this, their tests all do the 'lock and immediately unlock' thing
AFAICS.
Also mention `wait_for_children`, which is totally a thing now.
=> update (fix) the docs on mutex locking

cpanfile, lib/OpenQA/WebAPI/Controller/File.pm
As a followup to 8016a44b4d2591a50764731f38c94c58e78a69e2 this change allows
to symlink e.g. the needle directory into the tests distribution directory
within the filesystem while still not allowing to inject outside paths over
URL requests.
It would be ok to not support this feature but 403/404 responses to needle
images are not properly handled in the javascript code which would leave users
stumbled why the images don't update unless looking at server logs.
=> Allow symlinked test and needle directory structure

lib/OpenQA/WebAPI/Plugin/HashedParams.pm, t/api/05-machines.t
- escape quotes for values
- remove quotes for keys
partly fixes gh#666
Note: this preserve the API, but I'm not very happy with that since the `eval` is still there. This only tries to prevent escaping '' enclosure. I have another fix for that using JSON instead of perl-like strings for data transfer, but that would break API. How much we insist on not braking it?
=> Do not allow passing unescaped quotes in admin tables

lib/OpenQA/WebAPI.pm, lib/OpenQA/WebAPI/Controller/Main.pm, lib/OpenQA/WebAPI/Controller/Test.pm, public/javascripts/comments.js, public/stylesheets/comments.css, public/stylesheets/openqa.css, t/17-labels_carry_over.t, t/ui/15-comments.t, templates/comments/add_comment_form_groups.html.ep, templates/comments/comment_row.html.ep, templates/main/group_overview.html.ep, templates/test/comments.html.ep, templates/test/result.html.ep
- This PR implements editable comments: https://progress.opensuse.org/issues/10622
- I also fixed some other details regarding the comments (see the different commit messages).
- I'm not sure where to put the required CSS and JavaScript, so I decided to create separate files.
- I'm not sure about ```$self->emit_event('openqa_user_comment', {id => $self->param("comment_id")});```
- When testing, I also noticed that Non-ASCII characters aren't displayed correctly: https://github.com/os-autoinst/openQA/issues/655
- Allowing admins to edit comments (and not only the initial author) would required an "last_editor" field in the database. However, I don't know how to add an additional field. Hence currently only the user itself can edit comments.
- Only admins can remove comments completely.
=> Editable comments

script/client
- adding/modifying test_suites by client script requires user to be able
to put keys in format 'settings[$key]=value'
=> Enable brackets inside keys in client script

lib/OpenQA/WebAPI/Controller/API/V1/Iso.pm, t/api/02-iso.t
I hope you actually use 'poo' as a short form of 'progress.opensuse.org' ;)
=> Extend iso post TEST parameter to support a list of tests (poo#10482)

public/javascripts/needlediff.js
I just noticed that the white rectangle below the similarity display looks weird and displaced
and reporting that would've taken the same amount of time as fixing.
Draw a 3px wide black stroke around the similarity on needles
instead of a white rectangle which doesn't even match the text size.
Result (new on the right):
=> Quick fix for needlediff.js: Improve similarity text look

public/stylesheets/openqa.css
- to avoid accidental click on job restart or cancel icon increase left
padding of job status icons
=> Increase left padding of status icons

etc/openqa/openqa.ini, lib/OpenQA/Schema/Result/Assets.pm, lib/OpenQA/WebAPI.pm, t/config.t, templates/test/result.html.ep
We (Fedora) really don't want .iso files to be linked in the
Logs & Assets tab. Fedora's openQA is not a download server and
there is a more appropriate place to download those ISOs from.
So this changes things a bit so the admin can specify a list of
types not to include links to, rather than just hardcoding it.
=> add a config setting to specify asset types not to link to

lib/OpenQA/WebAPI/Controller/Main.pm, t/17-build_tagging.t
Calling 'delete $res->{$build}->{tag};' in case $res->{$build} does not
exist will actually create $res->{$build} as '{}' causing the build structure
to be defined but incomplete causing an error in
templates/main/group_builds.html.ep
Corresponding lightning talk:
https://www.destroyallsoftware.com/talks/wat
Fixes https://progress.opensuse.org/issues/12028
=> Prevent error in group_overview with '-important' builds

lib/OpenQA/Schema.pm
Instead of a ambiguous message "You did not provide any connection_info" the
configuration file 'database.ini' is now checked for a properly configured
database section matching the specified mode.
Helps when running against a customized database configuration, e.g. for
crosschecking with database dumps.
=> Check database configuration with better user feedback

lib/OpenQA/WebAPI/Controller/Main.pm, lib/OpenQA/WebAPI/Controller/Test.pm, public/javascripts/comments.js
- Fixes the issue https://progress.opensuse.org/issues/12116 as far as I can reproduce it.
- Editing buttons are now shown correctly when not logged-in as an admin.
=> Fix issues with editable comments

etc/openqa/database.ini, t/ui/15-comments.t
- Fix issue https://github.com/os-autoinst/openQA/issues/655
- Test non-ASCII characters in t/ui/15-comments.t
- Decode UTF-8 strings because Mojo doesn't seem
to expect UTF-8 strings (the website is still rendered
as UTF-8 after all)
- Comments added before this fix are  correctly displayed, too.
=> Fix non-ASCII characters in comments

lib/OpenQA/Worker/Engines/isotovideo.pm, lib/OpenQA/Worker/Jobs.pm, t/05-scheduler-restart-and-duplicate.t
The detailed error message what happens on
the "infamous" 'setup failure' was already
there but lost in system logs not easily
accessible. As the statement 'setup failure'
is already forwarded and ends up in
autoinst-log.txt which is accessible over
the WebUI now the detailed explanation
is returned and displayed.
**Example output:**
*old:* `result: setup failure`
*new:* `result: setup failure: /var/lib/openqa/ \
share/factory/iso/openSUSE-Tumbleweed-DVD-x86_64-Snapshot20160105-Media.iso \
does not exist!`
**Manual test procedure:**
* Pre: Any existing job result
* Remove/rename used ISO asset
* Reschedule job over WebUI
* Post: Observe result using logfile over WebUI
Related issue: https://progress.opensuse.org/issues/10314
=> Improve log message about 'setup failure'

public/javascripts/admin_user.js
The current user role is now re-enabled after the confirm box has been rejected.
=> Fix re-enabling current user role

templates/layouts/bootstrap.html.ep, templates/layouts/default.html.ep, templates/layouts/subheader_user.html.ep, templates/test/running.html.ep
I am repeating myself here: DRY!
Fixes an irregularity introduced with 7e5333ba for operators not having access
to the "operators page" using the admin link depending on the template being
used for individual subpages, e.g. for edit, running, src, screenshot view.
I am sure this was not intended.
=> templates: Use common code for bootstrap+default layout

templates/test/result.html.ep
`$('[data-toggle="tooltip"]').tooltip({html: true})` must be called to enable bootstrap tooltips (like in overview.js).
=> Fix bootstrap tooltips in testresults

assets/assetpack.def
This is actually a technique from the rails stack, but we can easily use it
in mojoliocus too. I just wasn't aware we relied on it (as we have no phantomjs
test cases for it)
=> Fix unobtrusive scripting by reincluding jquery-ujs

assets/stylesheets/openqa.css, lib/OpenQA/WebAPI/Plugin/Helpers.pm, t/ui/15-comments.t, templates/test/tr_job_result_details.html.ep
Progress is used to track test issues, bugzilla for product issues, at least
for SUSE/openSUSE. This might be a lot different for other groups so a more
flexible approach could be thought of but probably it is not as easy as
just distinguishing on the issue tracker URL being used, e.g. if a group
uses just one issue tracker but different components or issue types to
differentiate, it is not that easy. That is why this simple solution is
done here, first. At least others can follow the approach and have a test
and CSS rule available ;-)
*Alternative 1*: Inverted bug icon, vote for this, if you like it more than what has been currently implemented:
=> Distinguish product and test issues bugref

lib/OpenQA/WebAPI/Controller/Test.pm, t/ui/01-list.t
't_finished' is more meaningful for "finished" jobs than 't_created' which
would be the time when the job was initially scheduled but not yet started.
Fixes https://progress.opensuse.org/issues/12238
=> Show more intuitive finished time on finished jobs

lib/OpenQA/Schema/Result/Jobs.pm
The undef is only meant as last resort not as part of a list, so the
template either expects undef and a counter or a list, not a mix.
=> Don't sort undef (avoid warning and empty dot in tooltip)

lib/OpenQA/IPC.pm, lib/OpenQA/Schema/Result/Workers.pm, lib/OpenQA/WebAPI/Controller/Admin/Workers.pm, templates/admin/workers/index.html.ep, templates/admin/workers/show.html.ep, templates/admin/workers/worker_status.html.ep
Fixes the problem that no real error was shown in the web UI in case of an
IPC, e.g. websockets, not being available.
The error message and backtrace from "confess" call actually end up in the
rendered error page.
=> IPC: Catch unavailable service properly

lib/OpenQA/Schema/Result/Jobs.pm, t/04-scheduler.t, t/19-tests-export.t, t/ui/01-list.t, t/ui/12-needle-edit.t, t/ui/15-comments.t, templates/test/result.html.ep
$job->name is used in the result view where the MACHINE tag was added
explicitly. Also it is used for git commit messages. Adding the MACHINE should
not harm but makes the use of it more consistent.
=> Harmonize use of MACHINE in 'name' of job

lib/OpenQA/Scheduler/Scheduler.pm, t/api/02-iso.t
All tests in a build that has been tagged are not obsoleted if a new build
is triggered. Actually any tag is regarded as 'important' but if it has been
tagged there is not much lost if we finish this build. The obsoletion feature
is especially important for fast paced re-scheduling when no one cares to
put a comment anywhere.
As a tag comment can be created at any time regardless if the corresponding
build exists or not builds to come can be marked to be important already
upfront.
Related progress issue: https://progress.opensuse.org/issues/11072
=> Always finish tagged aka. 'important' builds

lib/OpenQA/Schema/Result/Jobs.pm
It's actually log_warning - and importing it is actually checking if
it's spelled correctly, otherwise perl will only check if it exists
when it's called (which is hard to cover in tests)
=> Fix my use of log_warn

script/clone_job.pl
In case all dependencies on a job are cloned including a parent job which will
generate an asset which is used by the cloned child there is no need to
download the corresponding asset when it will get overwritten by the new
scheduled parent job anyway.
This might also help to prevent confusion when the option
'--skip-chained-deps' is not used as the qcow image is downloaded but not
used.
Example test run:
```
$ clone_job.pl --from https://openqa 1002                           
Cloning dependencies of foo
downloading                                                    
https://openqa/tests/1002/asset/iso/foo.iso
to                                                             
/var/lib/openqa/factory/iso/foo.iso
Created job #1: bar
downloading
https://openqa/tests/1002/asset/iso/foo.iso
to …
```
=> clone_job.pl: Skip downloading assets generated by parent jobs

assets/javascripts/test_result.js, assets/stylesheets/result_preview.scss, t/ui/18-tests-details.t, templates/step/viewaudio.html.ep, templates/test/result.html.ep
- Resize live canvas, when the layout is too small (css: max-width: 100%) (Progress 12390)
- Skip fadein animation for needle diff box on page resize
- Fix padding for text result box
- Remove audiodiv (not needed with new container anymore)
- Fix edge case where live and running tab content are both visible (when #step link was used)
=> Some fixes for the new results / running page

lib/OpenQA/Scheduler/Scheduler.pm
This works in test DB:
SELECT * from jobs where (select group_id from jobs);
but gives an exception "where needs a boolean not a number" in
postgresql. (Unfortunately) this exception was caught rather
globally in ISO controller and only resulted in a "job couldn't be
cancelled" - which led to tons of builds with unfinished jobs
=> Fix SQL query to query important jobs

docs/Installing.asciidoc
openSUSE 13.2 is not provided anymore in the current development version but
only in the stable version.
I would prefer a version-agnostic reference, e.g.
http://software.opensuse.org/download.html?project=devel:openQA&package=openQA
could work but requires manual clicking in browsers and not simple command
line execution so I did not change this now.
=> docs: Update OBS references

script/clone_job.pl
When controlling remote host downloading the assets to a local machine at
first often does not make much sense.
=> clone_job.pl: Add option '--skip-download'

t/ui/16-tests_previous_results.t, templates/test/previous.html.ep
The query parameter 'limit_previous' allows to show more than the default 10
previous results on demand for some time. The current commit adds web UI
selections below the table of the previous build to reload the same page with
higher number of previous results on demand.
=> Add web UI controls to select 20/50/100/400 previous results

lib/OpenQA/Schema/Result/Assets.pm, t/14-grutasks.t, t/15-assets.t, t/data/openqa/factory/repo/.gitignore
We still occasionally seem to hit edge cases with this. When I wrote this patch
we had a lot of jobs running simultaneously and one uploaded
hdd image went missing, even though we've reduced the number of
tests that upload images as far as possible and upped the asset
size limit to 300GB. I think this may help deal with it. This
makes limit_assets reduce total asset size to 80% of the limit
when the limit is exceeded, instead of just removing enough to
get back under the limit (which, if you think about it, means
any long-lived openQA instance is perpetually teetering on the
brink of exceeding its asset size limit). This way there's a
bit of breathing room each time the size limit is hit, so it
doesn't immediately get hit *again* the next time any ISO is
downloaded or hdd image uploaded. …
=> limit_assets: when sizelimit is exceeded, remove more

lib/OpenQA/Scheduler.pm, lib/OpenQA/Scheduler/Scheduler.pm, lib/OpenQA/Schema/Result/Jobs.pm, lib/OpenQA/Schema/Result/Workers.pm, lib/OpenQA/Schema/ResultSet/Jobs.pm, lib/OpenQA/Utils.pm, lib/OpenQA/WebAPI/Controller/API/V1/Command.pm, lib/OpenQA/WebAPI/Controller/API/V1/Iso.pm, lib/OpenQA/WebAPI/Controller/API/V1/Job.pm, lib/OpenQA/WebAPI/Plugin/AuditLog.pm, lib/OpenQA/WebAPI/Plugin/Helpers.pm, lib/OpenQA/WebSockets/Server.pm, lib/OpenQA/Worker/Commands.pm, t/04-scheduler.t, t/05-scheduler-cancel.t, t/05-scheduler-dependencies.t, t/05-scheduler-restart-and-duplicate.t, t/11-commands.t, t/15-assets.t, t/18-fedmsg.t
- job_set_done recomputes overall job result, return this new value
back so correct job result is used in event
- moved job_set_done to OpenQA::Schema::Result::Jobs::done, to do so I needed also to move cancel and supporting subroutines
- OpenQA::Schema::Result::Jobs::cancel is pretty simple, the complexity of cancel by settings is now in OpenQA::Schema::ResultSet::Jobs::cancel_by_settings which is usually called from ISO controller
- command_enqueue moved to OpenQA::Schema::Result::Worker::send_command and added proper auditing
- added some more auditing places and enabled job_cancel_by_settings event
- important change which wasn't really needed but I did it anyway is when interactive mode and/or wait for needle requested, previously worker property was set immediately by websockets …
=> Use correct job result in openqa events

etc/openqa/openqa.ini, templates/branding/openSUSE/docbox.html.ep, templates/branding/openqa.suse.de/docbox.html.ep, templates/branding/openqa.suse.de/sponsorbox.html.ep, templates/branding/plain/docbox.html.ep, templates/main/index.html.ep
Related issue: [bsc#973842](https://bugzilla.suse.com/show_bug.cgi?id=973842)
screenshot:
=> Add SUSE internal branding with more links

lib/OpenQA/Client.pm, script/worker
Solves a copy-paste fail and removes the reference to the obsolete
OPENQA_CLIENT_CONFIG variable.
=> Correct description for use of OPENQA_CONFIG

assets/javascripts/test_result.js, t/testresults/00099937-opensuse-13.1-DVD-i586-Build0091-kde/details-partitioning.json, t/testresults/00099937-opensuse-13.1-DVD-i586-Build0091-kde/details-partitioning_finish.json, t/ui/18-tests-details.t, t/ui/21-admin-needles.t
- Only redirect to running tab when no `#` is in the url
- Clear url hash on test step result preview close
- Test for url hash cleanup after preview close
=> Url tab cleanups for result details

assets/javascripts/needleeditor.js
- Every time when a new base image was selected, a new CanvasState
object was created by the editor.init() method.
- Each cs object would register its own event handlers on the `<canvas>`
- Now the init() method will only update the base image and return,
as soon as an instance of CanvasState has been created by the first init() call
https://progress.opensuse.org/issues/12984
=> Prevent needle editor flickering (progress #12984)

assets/javascripts/test_result.js
Dominik originally wanted no history for steps either, but I added it to
make going back work especially with tabs. Now Ludwig asked for the exact
same behaviour Dominik implemented in #details, so I replace the history
now all the time when it's about previews
=> Remove history for step navigations

lib/OpenQA/WebAPI/Controller/Test.pm, t/ui/18-tests-details.t, templates/test/details.html.ep, templates/test/infopanel.html.ep
This allows a '/latest' link also used as a permalink to the always latest job, especially for local machines. http://<openqa>/tests/latest w/o query parameters already gave just the job with highest id but as a temporary redirect, i.e. reloading the page does not update the job. This way for example the browser can be configured to always reload the same page to have the always recent job displayed for local test development.
To still provide a link to the specific job the infobox now has a link to the '/tests/[:jobid:]' route. We could also put this link somewhere else, however, if it is preferred.
=> [WIP] Render links on 'latest' route directly instead of redirect

templates/admin/asset/index.html.ep, templates/admin/job_template/index.html.ep, templates/admin/workers/index.html.ep, templates/layouts/bootstrap.html.ep, templates/layouts/dependencies.html.ep, templates/main/group_builds.html.ep, templates/step/edit.html.ep, templates/test/infopanel.html.ep, templates/test/previous.html.ep, templates/test/running_table.html.ep
* Using '%=' instead of '<%= ... %>' where feasible
* Deleting redundant ';' on single line 'url_for, link_to'
=> templates: Simplify single line statements

lib/OpenQA/WebAPI/Controller/Main.pm, t/17-build_tagging.t, t/ui/14-dashboard.t, templates/main/group_overview.html.ep
Using a new query parameter 'only_tagged=[0|1]' the list can be filtered.
Related progress issue: https://progress.opensuse.org/issues/11052
Obsoletes #804
=> Add web UI controls to filter only tagged or all builds

lib/OpenQA/WebAPI/Controller/Main.pm, t/ui/14-dashboard.t, templates/main/group_overview.html.ep
The query parameter 'limit_builds' allows to show more than the default 10
builds on demand. Just like we have for configuring previous results, the
current commit adds web UI selections to reload the same page with
higher number of builds on demand. For this, the limit of days is increased
to show more builds but still limited by the selected number.
=> Add web UI controls to select more builds in group_overview

lib/OpenQA/Worker/Jobs.pm
Auto-duplication of jobs just hides errors which we want to learn and improve
on. A worker might be right to retry when any web API call fails temporarily
so we might want to add back some auto-duplication unless we can handle a
retry even at a lower level to not discard the whole job which is another
story.
=> Disable auto-duplication of jobs (poo#13042)

etc/apache2/vhosts.d/openqa-common.inc
Required to avoid stuff like https://openqa.suse.de/tests/523246#step/zypper_migration/6
Already hotfixed on openqa.suse.de and resolved the issue - https://openqa.suse.de/tests/523871
=> Make apache follow symlinks for assets directory

assets/javascripts/comments.js, lib/OpenQA/WebAPI/Controller/Main.pm, t/ui/15-comments.t, templates/comments/comment_row.html.ep, templates/main/group_overview.html.ep
Implements the feature requested here: https://progress.opensuse.org/issues/12400
=> Allow pinning comments as group description

assets/sass/theme.scss
Change 18px bottom margin (bootstrap default) into 8 top 8 bottom.
=> Vertically align progress bar with build number

dbicdh/PostgreSQL/deploy/43/001-auto-__VERSION.sql, dbicdh/PostgreSQL/deploy/43/001-auto.sql, dbicdh/PostgreSQL/upgrade/42-43/001-auto.sql, dbicdh/SQLite/deploy/43/001-auto-__VERSION.sql, dbicdh/SQLite/deploy/43/001-auto.sql, dbicdh/SQLite/upgrade/42-43/001-auto.sql, dbicdh/_source/deploy/43/001-auto-__VERSION.yml, dbicdh/_source/deploy/43/001-auto.yml, lib/OpenQA/Schema.pm, script/initdb, script/upgradedb
-  jobs columns TEST, DISTRI, etc.. were for pgsql translated as  "TEST", "DISTRI", etc.. This lead to errors with column not found  since unquoted strings are autotranslated to lowercase in pgsql
=> Do not quote identifiers, solves problem with uppercase column

docs/GettingStarted.asciidoc
to use same canonical location as before (not the symlink)
Signed-off-by: Michel Normand <normand@linux.vnet.ibm.com>
=> use /var/lib/openqa/share/factory/iso path

assets/javascripts/needlediff.js
This prevents match boxes from covering up labels of other boxes.
https://progress.opensuse.org/issues/12296
=> Draw needle match labels after match boxes

templates/exception.html.ep, templates/layouts/error.html.ep, templates/not_found.html.ep
Issue: https://progress.opensuse.org/issues/13192
The content of the pages could still be improved. Currently there is (beside the error message) just a link to 'New ticket' form under progress.opensuse.org.
Not sure how I would implement the last point mentioned in the issue. Just inserting the message via JavaScript is not possible due to cross-site security.
=> Show custom error pages

lib/OpenQA/Schema/Result/Jobs.pm, lib/OpenQA/WebAPI.pm, lib/OpenQA/WebAPI/Controller/Step.pm, lib/OpenQA/Worker/Jobs.pm, profiles/apparmor.d/usr.share.openqa.script.openqa, profiles/apparmor.d/usr.share.openqa.script.worker, t/14-grutasks.t
the workers just have more CPUs, so doing it remotely just scales better
=> Run optipng on the worker while uploading images

lib/OpenQA/WebSockets/Server.pm, t/20-workers-ws.t
the return was just not done for uploading, so we always killed
these jobs. And while I'm at it, I also increased the timeout we
give to jobs
=> Fix the dead job calculation for uploading jobs

lib/OpenQA/WebAPI.pm, lib/OpenQA/WebAPI/Controller/API/V1.pm
By using the build_tx hook to register an additional header to compare
against that time in HMAC check. The auth check only runs after the request
is completely uploaded
=> Avoid HMAC timestamp mismatch during large file upload

assets/javascripts/overview.js, assets/stylesheets/overview.scss, t/ui/10-tests_overview.t, templates/test/overview.html.ep
Fix https://progress.opensuse.org/issues/13640
=> Fix filter for running jobs in test overview

assets/stylesheets/openqa.scss, lib/OpenQA/WebAPI/Controller/Main.pm, t/17-build_tagging.t, t/api/04-jobs.t, t/fixtures/01-jobs.pl, t/ui/01-list.t, t/ui/14-dashboard.t, t/ui/15-comments.t, t/ui/16-tests_previous_results.t, templates/main/group_builds.html.ep
As proposed by @okurz
For better distinction review icons for such builds are green and have an appropriate tool tip.
For testing I had to insert another job to the fixtures. That's the reason for all the adjustments in all the tests.
=> Label builds where all tests passed as reviewed

lib/OpenQA/Utils.pm, lib/OpenQA/WebAPI/Controller/API/V1/Comment.pm, t/ui/15-comments.t
- Prevent detecting occurrences like bsc#2436346bla as bugref
- Replace URLs with the appropriate bugref pattern (fixes https://progress.opensuse.org/issues/11110)
=> Improve bug references in comments

lib/OpenQA/Schema/Result/Jobs.pm
Issue https://progress.opensuse.org/issues/13588
=> Test whether job still exists in reduce_result

lib/OpenQA/Schema/Result/JobModules.pm, lib/OpenQA/Schema/Result/Needles.pm, t/21-needles.t
Save relative path to needle from needledir to `filename` in database - that means that `needledir + filename` should point to needle even if needle is in subdirectory. Fixes #786.
=> Save relative path from needledir in needle's filename in database

script/client
Recently I added openqa-client link to openqa-client package pointing
to /usr/share/openqa/script/client. Without resolving this link
calling openqa-client fails due to missing OpenQA::Client module.
=> Use $FindBin::RealBin to resolve links for client script

lib/OpenQA/Scheduler.pm, lib/OpenQA/Scheduler/Scheduler.pm, lib/OpenQA/Schema/Result/Assets.pm, lib/OpenQA/Schema/Result/Jobs.pm, lib/OpenQA/WebAPI/Controller/API/V1/Iso.pm, lib/OpenQA/WebAPI/Controller/API/V1/Job.pm, lib/OpenQA/WebSockets.pm
This should resolve POO #13746. When a job with chained
children passes (or soft fails) we should notify workers to
ensure the child jobs are picked up promptly. Since we're now
using this 'passed or softfailed is OK' logic in two places,
make it another result array constant.
=> notify workers when job with chained children done (POO #13746)

lib/OpenQA/Scheduler/Scheduler.pm, lib/OpenQA/Schema/Result/Jobs.pm, t/04-scheduler.t
If many workers grab a job at the same time, they all go through the
scheduler bottleneck, wo will assign every worker a job one by one.
But the last couple of job_grab requests will actually get a timeout
and the worker will believe it didn't get a job.
if it then later grabs another job, we need to do something with the
previously assigned job. Just saying no is a problem as both the worker
keeps being unused and the job stays in running (pre-processing).
So now I set the previous job to incomplete and duplicate it. Beside
that I also made sure that cancelling a job kills the worker reference,
so it can grab another one.
=> Try harder to avoid long running pre-processing

lib/OpenQA/IPC.pm, lib/OpenQA/Scheduler.pm, lib/OpenQA/Scheduler/Scheduler.pm, lib/OpenQA/Schema/Result/Assets.pm, lib/OpenQA/Schema/Result/Jobs.pm, lib/OpenQA/Utils.pm, lib/OpenQA/WebAPI/Controller/API/V1/Iso.pm, lib/OpenQA/WebAPI/Controller/API/V1/Job.pm, lib/OpenQA/WebAPI/Controller/API/V1/Worker.pm, lib/OpenQA/WebSockets.pm, lib/OpenQA/WebSockets/Server.pm
Instead of calling blocking DBUS methods into websockets when notifying the worker,
we do a non blocking call into the scheduler, which then emits a signal.
This signal is then listened from websockets (whenever it has time :) to notify
the workers. None of that blocks and as such can't deadlock
=> Avoid DBUS dead locks

lib/OpenQA/WebSockets/Server.pm
This extra content actually confused the websocket parser on the
clients. It's unclear why this worked before, but the documentation
clearly indicates that this is not necessary to do any render
=> Do not manually render anything on websocket creation

lib/OpenQA/Utils.pm, lib/OpenQA/WebAPI/Controller/API/V1/Iso.pm, t/api/02-iso.t
I've deleted fork from which I've created #673 and it looks like I cannot update that pull request anymore, so I have created new pull request. It's rebased on top of master and with updated tests. You can find discussion in #673.
Basically, this code fixes problem with functionality that should enable you to specify both `ASSET` and `ASSET_URL` with intention of downloading from `ASSET_URL`, but then saving it into `ASSET` filename. We need it to be able to download from https://kojipkgs.fedoraproject.org/compose/branched/Fedora-25-20161004.n.0/compose/Everything/armhfp/os/images/pxeboot/vmlinuz but then save it as `vmlinuz.Fedora-25-20161004.n.0`.
This code works, but shows `asset name 'vmlinuz.Fedora-25-20161004.n.0' invalid or does not exist` during scheduling. @aaannz suggested to …
=> fix downloading assets to different filename

lib/OpenQA/BuildResults.pm, lib/OpenQA/WebAPI/Controller/Main.pm, templates/main/group_builds.html.ep, templates/main/group_overview.html.ep, templates/main/index.html.ep
JSON response can be triggered by adding HTTP header 'Accept: application/json'
Eg.:
```
curl -H 'Accept: application/json' http://localhost:9526?time_limit_days=48 | json_pp
curl -H 'Accept: application/json' http://localhost:9526/group_overview/25?time_limit_days=48 | json_pp
```
Like the former approach, this is meant for the openQA review script.
I don't know how to add the magic for `.json` routes but this variant (proposed by @coolo) looks good as well in my opinion.
Note that this can not be done generically for each page because currently database objects are stashed and those are not rendered as JSON automatically.
=> Add JSON representation of index and group overview

lib/OpenQA/WebAPI.pm, t/ui/14-dashboard.t
/index.json matches the route but doesn't know it has to reply with json.
So just use /index with given formats
=> Fix /index.json route to pass the format

assets/javascripts/tests.js, t/fixtures/05-job_modules.pl, t/ui/01-list.t
Fixes a regression introduced by commit 37d549e "Make softfailed a proper
final result". As there was no test for softfailed modules this was not
catched. Fixtures changed accordingly.
Fixes https://progress.opensuse.org/issues/14132
=> Fix softfailed results not showing in tests list

lib/OpenQA/BuildResults.pm, lib/OpenQA/WebAPI/Controller/Main.pm, t/17-build_tagging.t, t/ui/14-dashboard.t, templates/main/group_builds.html.ep, templates/main/group_overview.html.ep
* Fix https://progress.opensuse.org/issues/14136
* Also group name was missing in heading
=> Fix group overview when no builds shown

assets/javascripts/job_templates.js, assets/stylesheets/openqa.scss, dbicdh/PostgreSQL/deploy/47/001-auto-__VERSION.sql, dbicdh/PostgreSQL/deploy/47/001-auto.sql, dbicdh/PostgreSQL/upgrade/46-47/001-auto.sql, dbicdh/SQLite/deploy/47/001-auto-__VERSION.sql, dbicdh/SQLite/deploy/47/001-auto.sql, dbicdh/SQLite/upgrade/46-47/001-auto.sql, dbicdh/_source/deploy/47/001-auto-__VERSION.yml, dbicdh/_source/deploy/47/001-auto.yml, docs/Contributing.asciidoc, lib/OpenQA/Schema.pm, lib/OpenQA/Schema/JobGroupDefaults.pm, lib/OpenQA/Schema/Result/JobGroupParents.pm, lib/OpenQA/Schema/Result/JobGroups.pm, lib/OpenQA/WebAPI.pm, lib/OpenQA/WebAPI/Controller/API/V1/JobGroup.pm, t/api/10-jobgroups.t, t/ui/13-admin.t, templates/admin/group/index.html.ep, templates/admin/job_template/index.html.ep
Required to implement further features mainly regarding cleanup and grouping.
I think we still have to discuss the default values.
Not sure whether it is possible to enforce a flat hierarchy on database level (so that only a group can be a parent which has no parent itself).
I also altered `docs/Contributing.asciidoc`.
=> Extend schema of JobGroups

lib/OpenQA/Worker/Jobs.pm
While looking into a problem with corrupted uploads, i've noticed that the boundary workaround in `OpenQA::Worker::Jobs` uses a randomly generated string. This seems like a bad idea without actually checking the content of the file to be uploaded, and incredibly hard to debug should it ever fail. So, this patch replaces the random string with a constant one that is very unlikely to appear out in the wild.
Reasons against applying this patch might be security concerns, like the possibility of creating a DoS attack vector. Sadly i'm not familiar enough with the code base yet to find out. But should it be the case, i would recommend using a constant string as a base and combining it with a randomly generated salt.
=> Reuse a constant boundary to make debugging failed uploads a little easier

lib/OpenQA/Schema/Result/Assets.pm
This is a fix for https://progress.opensuse.org/issues/13846. The problem was that the test fixtures had no timestamps, and timestamps generated automatically by the database can overlap, which in very very rare cases will result in assets being retrieved in a different order. By itself that's not a problem, but in the current "keep bucket" code order matters, assets retrieved first will be preserved, while at the same time different groups can prevent certain assets from being deleted. Making the number of assets being removed random.
I see two solutions here, add timestamps to fixtures and mask the problem, or order assets by id to avoid race conditions like this more broadly. My preference in general would be to avoid ordering by timestamps, so that's what i went with here.
=> fix loch ness monster bug in 14-grutasks.t

assets/javascripts/overview.js, assets/javascripts/test_result.js, assets/javascripts/tests.js, lib/OpenQA/Schema/Result/Jobs.pm, lib/OpenQA/WebAPI.pm, lib/OpenQA/WebAPI/Controller/Test.pm, t/ui/10-tests_overview.t, templates/test/previous.html.ep, templates/test/tr_job_result_failedmodules.html.ep
This change shall reduce filesystem accesses.
- Load on first mouseover
- Update step index in link url
- Insert failed needles into tooltip
See: https://progress.opensuse.org/issues/13986
=> Load step and needles for failedmodules link async

assets/javascripts/running.js, assets/javascripts/test_result.js, templates/test/result.html.ep
See https://progress.opensuse.org/issues/2238
=> Auto reload result page on state change from  scheduled to running

docs/GettingStarted.asciidoc, docs/Installing.asciidoc, lib/OpenQA/Scheduler/Scheduler.pm, lib/OpenQA/Schema/Result/Assets.pm, lib/OpenQA/Schema/ResultSet/Assets.pm, lib/OpenQA/Utils.pm, lib/OpenQA/WebAPI.pm, lib/OpenQA/WebAPI/Controller/API/V1/Iso.pm, lib/OpenQA/Worker.pm, lib/OpenQA/Worker/Common.pm, lib/OpenQA/Worker/Engines/isotovideo.pm, t/14-grutasks.t, t/15-assets.t
This adjusts all the places that look for asset files to check
both in the current location and in a new possible location,
which is in a 'fixed/' subdirectory of the normal asset folder
for that asset type. It also adjusts the `limit_assets` gru
task to ignore files in the 'fixed' subdirectories. This
replaces the current special-casing of disk image assets created
by user '0'. That approach has become problematic now both SUSE
and Fedora are testing disk images that come from the distro
composes; these disk images are never getting cleaned up and
that causes disk space exhaustion. This also allows for 'fixed'
ISO and other assets, which the current approach does not.
Note: this is kind of a rough first cut, I haven't tested it manually or extended the tests to cover it yet. I wanted to …
=> Add 'fixed' asset subdirectories for fixed assets (#928)

lib/OpenQA/Schema/ResultSet/Assets.pm, lib/OpenQA/Utils.pm, lib/OpenQA/WebAPI/Controller/API/V1/Iso.pm
The change in 0905559b which made `parse_assets_from_settings`
skip any setting with a `_URL` partner was a bad idea. It was
an attempt to fix a real problem, but it went too far.
When `schedule_iso` is run, it calls `parse_assets_from_settings`
and attempts to register all the discovered assets. The problem
is that when an ISO is POSTed with, say, both `KERNEL` and
`KERNEL_URL` specified, `parse_assets_from_settings` will find
the `KERNEL` asset and so `schedule_iso` will try to register
it, but because the download has not run yet, the asset does not
exist yet. The `Schema::ResultSet::Assets->register()` method
which `schedule_iso` calls checks whether the asset file exists
and logs a warning if it doesn't.
The problem with fixing it this way is that every subsequent
effort to register …
=> Fix registration of downloaded assets (broken by 0905559b)

lib/OpenQA/Worker/Engines/isotovideo.pm
I introduced a problem in baac24bc by using `locate_asset` here.
Previously when the asset wasn't found, the variable (`$iso` or
whatever) would be the path where we were looking for it; now,
it's undef, and that actually causes the worker process to error
out trying to produce the error string. So let's keep the asset
filename around for the purpose of creating the error message,
and tweak the wording a bit.
=> Fix worker error reporting when asset cannot be found

lib/OpenQA/BuildResults.pm, lib/OpenQA/Schema/Result/Comments.pm, lib/OpenQA/WebAPI/Controller/Main.pm, t/api/04-jobs.t, t/api/09-comments.t, templates/main/group_builds.html.ep, templates/main/group_overview.html.ep, templates/main/index.html.ep
The current json output is painful to parse as it violates the hierarchical principle of json.
- Don't keep data structures of different types in the same hash (move `_group` and `_max` one level up)
- Expose comments via job_group .json
=> Make .json easier to use and include more data

lib/OpenQA/Schema/Result/JobGroups.pm, lib/OpenQA/WebAPI.pm, lib/OpenQA/WebAPI/Controller/API/V1/JobGroup.pm, t/api/10-jobgroups.t
* Works in the same way as the API for
regular groups and shares the same code
* When deleting a parent group, all groups
inside remain parentless
* Still TODO
* List all job groups inside a parent
* List all jobs inside a group
=> Add API routes for job group parents

script/clone_job.pl
Variables on command line like 'BACKEND=svirt' are in case of chained
jobs being inherited by the child job only. With this option parent has
command line options as well (e.g. when cloning extratests test,
create_hdd test gets cloned as well - and runs before extratests - but
it won't inherit command line options). Building virtualisation specific
images (not Qemu images for all) is now possible.
=>  Inherit command line variables in parent as well

lib/OpenQA/Schema/Result/JobModules.pm
This might not be typical, but if you rsync a testresult from one
instance to another, it's easier to just detach the symlinks.
The helper already made a difference between link to /image and
file in testresults, but at some refactoring this was lost
=> Only store md5_dirname if the image is in /images

etc/openqa/workers.ini, profiles/apparmor.d/usr.share.openqa.script.worker
It doesn't work yet, isotovideo is not allowed to mkdir, but I know too little about apparmor
=> Prepare CACHEDIRECTORY example in workers.ini and provide profile

lib/OpenQA/Schema/Result/Comments.pm, lib/OpenQA/Utils.pm, lib/OpenQA/WebAPI/Plugin/Helpers.pm, t/16-utils-runcmd.t, t/16-utils.t, t/ui/12-needle-edit.t, t/ui/15-comments.t
Add support for generic github repo markers as 'bugrefs
Using the generic profile
'<marker>[#<project/repo>]#<id>'
for all bugrefs, especially for github, allows to
track all issues reported on github and especially
test fixing pull requests to be recorded as 'bugrefs'
with the same icon as for "test issues", i.e. poo#.
This way there is no need to create a ticket just
to track a test issue for which already a github
pull request exist because otherwise the URL to the
github PR would not mean anything special to github
and therefore not mark a job as "labeled".
Also, pasting full github URLs is supported, same as
for all other bugrefs, meaning that the URL is
abbreviated into short form bugrefs.
The pattern follows the openSUSE/OBS recommendation.
=> Add support for github 'bugrefs'

lib/OpenQA/Schema/ResultSet/Assets.pm
This prevents warnings on assets with a '@' in name as is common for
SUSE/openSUSE. This has been made obvious just by a recent change baac24b
which introduced explicit checking for a "correct name" separated from the
existance of an asset on the filesystem.
Fixes https://progress.opensuse.org/issues/14650
=> Allow '@' in asset name

assets/javascripts/test_result.js, templates/step/viewimg.html.ep
Use a proper `<ul>` instead of manually adding
list entries.
=> Fix list of needle tags in needle info popover

assets/javascripts/openqa.js, assets/stylesheets/openqa.scss, lib/OpenQA/WebAPI/Plugin/Helpers.pm, t/ui/14-dashboard.t, templates/comments/add_comment_form_groups.html.ep, templates/comments/comment_row.html.ep, templates/main/index.html.ep, templates/step/edit.html.ep
* edit: Add help popovers
* edit: Add placeholder help text for new tags
* Add help popover for comment writing
* Show placeholder text for comment textedit
* Also show name/nickname for existing comments gravatar hover
* Show name/nickname on hover over own gravatar
* Extract help popover into helper function
* Add help popover for 'only_tagged' checkbox
=> Add help text using popovers, title and placeholder

lib/OpenQA/BuildResults.pm, t/ui/15-comments.t
softfails are listed as TODO, so their presence should require a label
to receive a no-TODO icon
This fixes https://progress.opensuse.org/issues/14362 documenting user expectations. Back in the days we only cared for failures, but meanwhile softfailures are considered bugs worth labeling
=> Fix softfail logic for no-TODO flag

lib/OpenQA/Schema/Result/Assets.pm, lib/OpenQA/Schema/Result/Jobs.pm, lib/OpenQA/Schema/ResultSet/Assets.pm, lib/OpenQA/Utils.pm, lib/OpenQA/WebAPI.pm, lib/OpenQA/WebAPI/Controller/API/V1/Iso.pm, lib/OpenQA/WebAPI/Controller/File.pm, lib/OpenQA/Worker/Engines/isotovideo.pm, t/15-assets.t, t/api/02-assets.t, t/api/02-iso.t, t/data/openqa/factory/repo/.gitignore, t/data/openqa/factory/repo/testrepo/README, t/fixtures/01-jobs.pl, t/ui/07-file.t
Instead of returning self constructed URLs from helper functions, return
a relative path passed to URL helpers in the controller.
This way we don't hard code the /fixed/ part anywhere but the utility
function and still use URL helpers
=> Trying to make peace with adamw over locate_asset

lib/OpenQA/Worker/Engines/isotovideo.pm
If the hdd variable is not set, the 'if' does not evaluate.
=> isotovideo: Remove redundant '|| undef'

assets/assetpack.def, assets/javascripts/openqa.js, templates/layouts/bootstrap.html.ep
* Since there is currently no parent group overview
the link just leads to the editor.
* Parentless groups are still displayed (at the top).
=> Show parent groups in navbar

docs/GettingStarted.asciidoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/os-autoinst/openqa/915)
=> docs: Add instructions for personal credentials

lib/OpenQA/Schema/ResultSet/Assets.pm
We just do not see a reason why we should limit the names. And as we have
assets which are considered 'invalid' we just have a lot of warnings but do
not plan to do anything about it.
Related progress issue: https://progress.opensuse.org/issues/14650
=> Do not enforce any asset name at all

lib/OpenQA/Schema/ResultSet/Jobs.pm, lib/OpenQA/WebAPI/Controller/API/V1/Job.pm, t/api/04-jobs.t
I want to do something like 'find the job before job X that has
the same scenario' - this is something we do internally in a
few places, e.g. the 'previous results' page in the web UI. But
it's very difficult to do via the API, because you really can't
say "I only want jobs with IDs lower than X".
It's easy enough to add, though! So add 'before' and 'after'
params for the API method and also for the `complex_query`
method which backs it. While I'm at it, add `page` to the args
for the API method too (it's pretty useless to support `limit`
without `page`, and `complex_query` already handles it) and
cover all these bits in the tests, plus test the variant forms
for specifying multiple `ids` args (since I wrote that a while
back but it's not tested yet).
=> API jobs list: add params 'before' and 'after'

docs/Installing.asciidoc, docs/Pitfalls.asciidoc
Add documentation for the needle caching, now that it has been
deployed, it is useful to have it documented.
Add a pitfall i run myself into every time i update my openQA packages
(which is probably a bad practice).
=> Update docs for caching, test writing and pitfalls

assets/stylesheets/openqa.scss, lib/OpenQA/Schema/Result/Jobs.pm, lib/OpenQA/WebAPI/Controller/Test.pm, lib/OpenQA/WebAPI/Plugin/Helpers.pm, t/ui/18-tests-details.t, templates/branding/openSUSE/external_reporting.html.ep, templates/step/viewimg.html.ep
Using the available context of test results a URL for
corresponding issue tracker can be generated. The
fields in the to be opened issue can already be
prefilled. This can be extended later on even more.
The configuration in openqa.ini must accomodate the
corresponding issue tracker type and URL for creating
new tickets. For now bugzilla and redmine are
supported, more can be added. If no configuration is
set at all no links are generated.
As at least in bugzilla the product field is mandatory
to end up with a pre-filled bug the mapping from job
group to bugzilla product can be done in the config
file, too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/os-autoinst/op …
=> Add issue reporting links to needle preview screen

docs/Branding.asciidoc, docs/Contributing.asciidoc, docs/GettingStarted.asciidoc, docs/Installing.asciidoc, docs/Networking.asciidoc, docs/Pitfalls.asciidoc, docs/WritingTests.asciidoc, docs/index.asciidoc
I updated a bit the documentation's formatting, the main idea behind this is to be able to generate a full document from the index, that can be published or distributed through the open.qa website. 
I kept in most cases the same structure as it was before, so looking individually at the documentation directly on the repo should render in most cases almost the same content as before. 
One thing to note is that not everything is perfect, still a lot of formatting to do (And this is just in the openQA documentation... backend is still in progress)... But a html single page can be generated now, with better navigation, and also a single pdf file.
One idea I have is to move the documentation to os-autoinst/documentation, but I guess we're too early in time for this. 
In future changes (i.e …
=> Major changes on the documentation's formatting

.perltidyrc, script/tidy
Personally, i like to perltidy files while working on them in my editor of choice. Having a separate `.perltidyrc` file makes that a lot easier. Additionally, Perl developers working on their first contribution to openQA can read the `.perltidyrc` file to get up to speed on formatting rules used by the project.
One of the 3rd party tools benefitting from this change would be my [perltidy package for the Atom text editor](https://atom.io/packages/perltidy).
=> .perltidyrc file for use in 3rd party tools

assets/stylesheets/openqa.scss
The unicode characters make the sass conversion in OBS too fragile
=> Do not use unicode characters but unicode entities

lib/OpenQA/BuildResults.pm, lib/OpenQA/Schema/Result/JobGroupParents.pm, lib/OpenQA/Schema/Result/JobGroups.pm, lib/OpenQA/WebAPI/Controller/Main.pm, t/ui/14-dashboard.t, templates/main/index.html.ep, templates/main/more_builds.html.ep
- by default show 10 builds, no matter how old they are
- if 'only tagged' is requested, show 10 tagged builds. no matter how old they are
=> Make group_overview behave as expected

templates/branding/openSUSE/external_reporting.html.ep
Fixes https://progress.opensuse.org/issues/14836
=> external_reporting: Fix differing header level in description

docs/Installing.asciidoc
The 'stable' repository of openSUSE is currently not maintained.
openSUSE Leap 42.2 as the current stable version should suffice, too.
=> docs: Update openSUSE repos to current supported

assets/assetpack.def, templates/layouts/bootstrap.html.ep
Also change link to parent group overview, which has effect when opening in new tab via context menu or copying the link
=> Show submenus on click

docs/Branding.asciidoc, docs/Contributing.asciidoc, docs/GettingStarted.asciidoc, docs/Installing.asciidoc, docs/Networking.asciidoc, docs/Pitfalls.asciidoc, docs/WritingTests.asciidoc, docs/index.asciidoc
i'm adding some changes that were missing with my last rebase mess (Pitfalls and WritingTests), and also unified code blocks so there's only usage of sh instead of bash  which is basically the same coloring.
Results have been generated using [this script](https://github.com/foursixnine/openQA/blob/doc/generator_script/script/generate-documentation):
- https://w3.nue.suse.com/~szarate/openQA/docs/openqa-documentation-20161122_66e4f8c.html
- https://w3.nue.suse.com/~szarate/openQA/docs/openqa-documentation-20161122_66e4f8c.pdf
=> More fixes to documentation formating

assets/javascripts/test_result.js
An uploading job is like a running one, just not updating. So show
the live tab for the log - and more importantely wait for the state
to change to passed/failed
There is unfortunately no test coverage for this :(
=> Treat uploading jobs like running

systemd/openqa-webui.service
To avoid the worker growing memory usage we restart it after 200*10
requests and give it a lot of time to finish requests. Mojolocious 7.10
has a bug, that during restart it will still accept more requests from
apache, so we need to limit the number of requests accepted (-r)
and give the restart enough time to finish all of them (-G).
This bug caused several sudden deaths in uploads, e.g. see
https://progress.opensuse.org/issues/13876
=> Restart the mojo worker every 2000 requests

lib/OpenQA/BuildResults.pm, t/22-dashboard.t, templates/main/group_builds.html.ep, templates/main/review_badge.html.ep
Show review badges also in the foldable job group entries on index page and parent group overview
After this all TODOs regarding parent groups should be done: https://progress.opensuse.org/issues/14814
=> Show review badges also on group-level

lib/OpenQA/Schema/ResultSet/Jobs.pm, lib/OpenQA/WebAPI/Controller/API/V1/Iso.pm, lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm, lib/OpenQA/WebAPI/Controller/Admin/JobGroup.pm, t/api/02-iso.t, t/api/04-jobs.t, templates/admin/group/group_property_editor.html.ep
* When creating a new job in a job group, priority is set to the default of the job group
* Does not affect
* existing jobs
* new jobs without a job group
* new jobs added when a new ISO is scheduled (then still the priority from the job template is taken)
Because of the last point I guess this is not too useful actually. But it was on the TODO list because we decided to add the `default_priority` column for job/parent groups.
=> Use default priority of job groups

lib/OpenQA/Worker/Common.pm
The method `Mojo::IOLoop->one_tick` is no longer allowed to be called
recursively in Mojolicious 7.11. For now we can use
`Mojo::IOLoop->singleton->reactor->one_tick` as a workaround, even though
long term we should just get rid of event loop recursion, which is
considered an anti-pattern that can make Perl explode in very funny ways.
=> Workaround for Mojolicious 7.11

cpanfile, etc/openqa/openqa.ini, lib/OpenQA/Schema/Result/Comments.pm, lib/OpenQA/ServerStartup.pm, lib/OpenQA/WebAPI/Controller/API/V1/Comment.pm, lib/OpenQA/WebAPI/Controller/API/V1/Job.pm, lib/OpenQA/WebAPI/Plugin/AMQP.pm, lib/OpenQA/WebAPI/Plugin/Fedmsg.pm, t/23-amqp.t, t/config.t
This will add a plugin to send the events via AMQP (RabbitMQ).
The plugin depends on `Mojo::RabbitMQ::Client`.
@AdamWill: We did some changes on the comment event names.
The PR also has some fixes for problems with `comment->hash` that were hidden by the too friendly mojo internal json encoder.
Also the `jobs_reset` event was removed (it was broken in the Fedmsg plugin anyway) and replaced by multiple `job_reset` events. This removes some edge cases that violated the `object.action` event name pattern. Sticking to that pattern allows easy rabbitmq serverside event filtering.
=> Add RabbitMQ support

lib/OpenQA/Utils.pm, lib/OpenQA/Worker/Jobs.pm
Ensure that if the upload failed due to server being unavailable (status 5xx) that will be executed
up to $retry_limit times for $tics of 1 second each.
This one in particular is related to: [poo#13876](https://progress.opensuse.org/issues/13876). The missing autoinst.log is a bit unrelated.
=> Add retry for failed uploads on server errors (5xx)

script/fetchneedles
In most cases the full history is not needed and only slows down initial
download time. The full history can always be fetched with `git fetch
--unshallow`.
=> fetchneedles: Optimize initial clone time by stripping history

dbicdh/PostgreSQL/deploy/50/001-auto-__VERSION.sql, dbicdh/PostgreSQL/deploy/50/001-auto.sql, dbicdh/PostgreSQL/upgrade/49-50/001-auto.sql, dbicdh/SQLite/deploy/50/001-auto-__VERSION.sql, dbicdh/SQLite/deploy/50/001-auto.sql, dbicdh/SQLite/upgrade/49-50/001-auto.sql, dbicdh/_common/upgrade/49-50/01-add-system-user.pl, dbicdh/_source/deploy/50/001-auto-__VERSION.yml, dbicdh/_source/deploy/50/001-auto.yml, etc/openqa/openqa.ini, lib/OpenQA/Schema.pm, lib/OpenQA/Schema/Result/JobGroups.pm, lib/OpenQA/ServerStartup.pm, lib/OpenQA/Utils.pm, lib/OpenQA/WebAPI.pm, lib/OpenQA/WebAPI/Controller/Test.pm, script/initdb, script/upgradedb, t/06-users.t, t/10-jobs.t, t/14-grutasks.t, t/config.t
First commit adds `system` openqa user. This user is meant to be used for actions which requires some user, but at that time cannot use real one - startup/shutdown events in audit, and for jobs labeling introduced in second commit.
Then new config file entry `recognized_referers` is added (open for discussion about naming ;) ). When GET request to show test job comes from one of these referers, job is automatically labeled as linked. So far no other message is added, but I'll add back url.
Last commit tend to cleanup routing where linked jobs are meant to be regarded as important. (*missing tests*)
[issue#14926](https://progress.opensuse.org/issues/14926)
=> Detect jobs linked from other sources and regard as important

lib/OpenQA/WebAPI/Plugin/AMQP.pm, lib/OpenQA/WebAPI/Plugin/Fedmsg.pm, t/18-fedmsg.t
This touches both Fedmsg and AMQP comment event emitters. We
no longer need the conditional in the Fedmsg plugin to produce
a different hash in the case of comment deletion, as the API
code was changed to event the mojo event *before* rather than
after deleting the comment. Also include the comment ID in the
emitted events, since it doesn't hurt anything and could be
useful (seems odd to emit an event with lots of info on the
subject of the event, but not its actual ID).
=> comment events: drop unneeded fedmsg conditional, include id

lib/OpenQA/Schema/Result/Jobs.pm, lib/OpenQA/WebAPI/Controller/Test.pm, t/17-labels_carry_over.t, t/22-dashboard.t, templates/comments/add_comment_form_groups.html.ep
Labels - in contrast to normal comments or issue references - did not find a
very common use case when used by us. With d806699 we now add a `label:linked`
to jobs to mark them as important when referenced from outside. To make this
approach sensible a carry-over does not make sense not to regard all following
jobs as important. This commit changes the behaviour to disable the carry-over
on job labels. So now only issue references, or "bugrefs" are carried over.
However job 'labels' still retain their other properties, for example they
infuence the appearence of a certificate icon, unlike simple comments.
Related progress issue: https://progress.opensuse.org/issues/14926
=> Disable carry-over for job 'labels' to support new use cases

lib/OpenQA/WebAPI/Controller/Step.pm, t/testresults/00099/00099946-opensuse-13.1-DVD-i586-Build0091-textmode/details-yast2_lan.json, t/ui/18-tests-details.t, templates/step/viewimg.html.ep
So far we sorted the needles while displaying them by the minimum of the
similiarity of the match areas. The problem is that this makes needles
more equal than they are. In case if you have 2 needles that both mismatch
Needle A:
Area 1 matches 0%
Needle B:
Area 1 matches 100%
Area 2 matches 0%
Both needles have a minimum of 0% and so they would display as:
0%: A
0%: B
With this change, we display the needles by their root mean square error,
which results in:
71%: B
0%: A
See https://progress.opensuse.org/issues/14886
=> Sort needles by RMSE instead of MIN

lib/OpenQA/Worker/Common.pm
See https://progress.opensuse.org/issues/15240
Only tested manually (by just killing and restarting ws daemon).
=> worker: Re-establish ws connection in any error case

lib/OpenQA/Worker/Commands.pm, lib/OpenQA/Worker/Jobs.pm
With this commit the worker will write live_log, as a mark in the pool directory, so that the backend
can know when there is a live view on demand.
See https://github.com/os-autoinst/os-autoinst/pull/664
=> Have the worker to touch live_log file on demand

lib/OpenQA/WebAPI/Controller/Main.pm, t/22-dashboard.t, t/ui/14-dashboard-parents.t, t/ui/14-dashboard.t, t/ui/15-comments.t, templates/main/group_overview.html.ep
So it shows now, eg.
`Last Builds for SLE Server 12 SP3 / Acceptance: Server`
instead of just
`Last Builds for Group Acceptance: Server`
to make it more clear which group overview page is actually shown
=> Show parent name in group overview heading

lib/OpenQA/Schema/Result/Jobs.pm, lib/OpenQA/Utils.pm, lib/OpenQA/WebAPI.pm, lib/OpenQA/WebAPI/Controller/API/V1/Job.pm, t/api/04-jobs.t
Route expects JSON, eg.
```
{"group_id": 5,
"settings": {"ARCH": "x86_64", "DESKTOP": "kde"}
}
```
Note that currently all settings are replaced. However,
regular properties like priority and group are only updated.
Previous approach and comments: https://github.com/os-autoinst/openQA/pull/1081
=> Add API route to update job properties/settings

lib/OpenQA/Schema.pm, script/initdb, t/deploy.t
022553fd made `initdb --init_database` silently return 0,
instead of crashing with an uncaught exception, when the db
is already initialized. The exception was bad, of course, but
the new behaviour is a bit of a problem for things like ansible
or puppet or salt, where it's Good Practice for actions to be
aware of whether they changed anything. It's not longer possible
to know whether a run of `initdb` a) initialized the database, b)
upgraded the database or c) did nothing because the database was
fine.
So, this makes it print an informative message about what it did
and exit 0 if it actually did anything; if the db was already
initialized and up to date, it exits 4 (a distinctive code that
ansible plays etc. can recognize).
=> Have initdb exit 4 when no init or upgrade is done

docs/WritingTests.asciidoc
The current formatting has a rendering problem when using example blocks
on the GH web rendering (a gollum issue), this will fix these formating
problems. Which fixes the problems described in #1086
=> Change the format for developing with snapshots

docs/GettingStarted.asciidoc, docs/WritingTests.asciidoc
Signed-off-by: Petr Vorel <pvorel@suse.cz>
Fix just one typo + missing space.
=> doc: fix typo

lib/OpenQA/WebAPI/Controller/Admin/AuditLog.pm, t/ui/23-audit-log.t
* and finally add a test for this simple use case
* however, sleeps in the test are still present
I'm unable to find a way to get rid of the sleeps so far.
I tried:
```
while ($driver->execute_script('return $($("#audit_log_table").dataTable().fnSettings().aanFeatures.r).is(":visible")')) {
sleep 0.1;
}
```
It actually waits (one iteration) till the 'processing' indication is hidden. However, this is not sufficient as the table isn't updated at this time.
=> audit log: Fix filtering event data by default

lib/OpenQA/WebAPI/Controller/API/V1/Iso.pm, t/api/02-iso.t
A 'warn' does not really help here as the corresponding code is a check on
settings provided by the user. This way the output is also properly catched
during test execution and does not spill on the console. The warning is still
visible e.g. if 'prove -v' is used for executing the test.
=> Replace 'warn' by log_warning to catch it properly in tests

lib/OpenQA/Schema.pm, lib/OpenQA/Test/Database.pm, lib/OpenQA/WebAPI.pm, script/initdb, script/upgradedb, t/11-commands.t, t/deploy.t
This is an attempt to address POO #15540. There are two major
changes.
First, we `flock` the db config file (chosen as we must be
able to read it, and the code to find it was already present)
to try and ensure that only one openQA process (one of the
server processes, gru, or any of the admin scripts that handle
the database) can run the deployment check at a time; this is
to ensure multiple processes don't try to deploy or upgrade the
db schema at once.
Second, we have the first call to `connect_db` for any given
process run the deployment check (because `connect_db` caches
the schema, subsequent calls won't run the check). This should
ensure that the db is always checked, and deployed or upgraded
if needed, when *any* openQA server process tries to use it.
Previously, only the webui …
=> Use locking for db check, run check on most db connections

t/ui/18-tests-details.t
The fade in animation might be the reason the tests fails sometimes
=> Disable popover animation in t/ui/18-tests-details.t

assets/sass/theme_overwrites.scss, assets/sass/theme_variables.scss
So it looks like this
instead of
=> Fix appearance of popover arrow

README.asciidoc, docs/WritingTests.asciidoc, script/generate-documentation
Changes on the `generate-documentation` script should fix the problems we've found regarding documentation publishing. 
Changes to the Readme and WritingTests.asciidoc are just an update to links.
=> Fix asciidoctor call and changes to documents

lib/OpenQA/WebAPI/Plugin/AMQP.pm
The ioloop is not yet running when the plugin's register function is called.
So we need to wait.
This should prevent AMQP connection timeouts.
=> Delay AMQP connection init until ioloop is running

assets/javascripts/admintable.js, assets/stylesheets/openqa.scss, lib/OpenQA/WebAPI/Controller/Test.pm, t/api/07-testsuites.t, t/fixtures/04-products.pl, t/ui/10-tests_overview.t, t/ui/13-admin.t, templates/admin/test_suite/index.html.ep, templates/test/overview.html.ep
Add API CRUD operations for a description field for test suites, machines, products.
Also deletes 'variables' field which has not been in use for test suites,
machines, products for quite some time now.
Add UI elements for CRUD on test suite description.
Show description as popover on each test row.
Screenshot how the test suite description shows up in the admin table:
Screenshot of edit:
Screenshot of popover in test overview with content as configured in the test suites database (i.e. over admin view):
=> Description for test suites

assets/javascripts/openqa.js, lib/OpenQA/WebAPI/Controller/Test.pm, lib/OpenQA/WebAPI/Plugin/Helpers.pm, t/10-tests_overview.t, templates/admin/test_suite/index.html.ep, templates/step/viewtext.html.ep, templates/test/overview.html.ep
* Add help popover for '/tests/overview'
* Add defaults for all job attributes used for sorting
* Allow selecting multiple job groups in overview query
* Delete unused variable '$failedid' from overview template
* Use word wrap for title in test suite popover
* Add test suite description to overview page
* Get rid of redundant @configs array in favor of keys
=> Alternative to #1040 based on #1094

lib/OpenQA/Worker/Common.pm
This does not fix the full stack test for me (test just scheduled and never executed), but prevents the endless
```
```
=> worker: Handle websocket redirection correctly

.travis.yml
we spend 2 minutes on each run installing cpan modules. So safe this time and cache them. 
The downside is that our dependencies get old - so travis will no longer test with latest mojolicious, but with a rather random one that was latest when the cache was created. IMO the benefit outweights that.
Before:
https://travis-ci.org/coolo/openQA/builds/188818032 - Elapsed time 13 min 38 sec
After:
https://travis-ci.org/coolo/openQA/builds/188827391 - Elapsed time 11 min 34 sec
=> Enable Travis cache for perl dependencies

Makefile
Possibly this reenables codecov reports
=> Don't pass filters to cover -report

cpanfile
7.14 deprecates a function that Mojo::Plugin::AssetPack uses and this
leads to tons of warnings all over our code base - which breaks
tests using Test::Warnings.
So we need to stay with 7.13 until this is resolved
=> Hardcode mojo requirement to < 7.14 for now

lib/OpenQA/BuildResults.pm, lib/OpenQA/WebAPI/Controller/Main.pm, t/22-dashboard.t, t/api/04-jobs.t, t/ui/14-dashboard-parents.t, t/ui/14-dashboard.t, templates/main/group_builds.html.ep
* Distinguish builds also by version
* Consider version for sorting
* Improve escaping build IDs when used in HTML-IDs
=> Support multiple version per job group

Makefile
As we can't mark branches uncoverable, we should not care at the
beginning
=> Only care for statements covered and ignore branches

codecov.yml, cpanfile, t/testrules.yml, t/ui/PhantomTest.pm
The main benefit is that we can switch drivers easily.
=> Switch to Selenium::Remote::Driver > 1, which starts phantomjs itself

t/ui/12-needle-edit.t, templates/step/viewimg.html.ep
Otherwise the stack icon receives the click - and the chrome driver will
not accept a click on the underlying icon
=> Add css class to click on action

lib/OpenQA/Schema.pm, t/full-stack.t
Another tweak to the database deployment locking stuff. As
discussed in #1095, using the db config file for locking is not
a great idea; it requires the server be able to write to the
config file, which is denied by the AppArmor config on SUSE,
and that's probably a sensible precaution (it's never wise to
let webapps write to more stuff than is strictly needed).
So here's yet another try: let's rely on the fact that prjdir/db
(usually /var/lib/openqa/db) is made writeable by the server in
the install process and the SUSE/Fedora packages, and put the
lock file there, just assuming we are able to write to that
location.
=> Don't use config file as database lock file

lib/OpenQA/Worker/Jobs.pm
The method `Mojo::Message::Response::is_status_class` has been deprecated in Mojolicious 7.13. Its replacement is `Mojo::Message::Response::is_server_error`, which has been added in the same release.
=> Fix use of a deprecated method in OpenQA::Worker::Jobs

.travis.yml
SELENIUM_CHROME is very useful locally, but we don't really need to test
both on travis - especially as chrome runs into timeouts from time to time
=> Disable chrome again - phantomjs on travis will do

t/22-dashboard.t
Test should cover all version schemes for build numbers found on openqa.suse.de and openqa.opensuse.com now
=> Add more tests for sort order

lib/OpenQA/BuildResults.pm, lib/OpenQA/WebAPI/Controller/Main.pm, t/17-build_tagging.t, t/22-dashboard.t, t/api/04-jobs.t, t/ui/14-dashboard.t, t/ui/15-comments.t, templates/main/group_builds.html.ep, templates/main/group_overview.html.ep, templates/main/index.html.ep, templates/main/parent_group_overview.html.ep
Previously builds where sorted by creation time before applying limit
BTW: Likely to break review script if it used `.json` routes.
=> Sort builds by version before applying limit

lib/OpenQA/Schema/Result/Comments.pm
So builds like GMC can be tagged
=> build tagging: Allow digits, word chars and @ in each section

.travis.yml, script/generate-documentation
The generate documentation script and .travis.yml have now been fix to
only run on a separate travis job.
The generate-documentation script can be still called on demand.
=> Fix documentation generation

script/generate-documentation
The images were just not being added to the git branch, but were being
used correctly by the pdf-generator.
This commit will fix that problem. (fixes #1179)
=> Fix missing images in documentation

docs/GettingStarted.asciidoc, docs/WritingTests.asciidoc
Signed-off-by: Petr Vorel <pvorel@suse.cz>
Just a tiny typo fix.
=> Fix typo in documentation

etc/openqa/workers.ini, lib/OpenQA/Schema/Result/Needles.pm, lib/OpenQA/Utils.pm, lib/OpenQA/WebAPI/Controller/File.pm, lib/OpenQA/Worker.pm, lib/OpenQA/Worker/Commands.pm, lib/OpenQA/Worker/Common.pm, lib/OpenQA/Worker/Engines/isotovideo.pm, lib/OpenQA/Worker/Jobs.pm, lib/OpenQA/Worker/Pool.pm, script/worker, t/20-workers-ws.t, t/24-worker.t, t/full-stack.t
Allows worker to register and work on jobs from multiple openQA servers.
Hosts to register with are configured in `workers.ini` in global section `HOST` key. Accepts space separated hostnames. Optionally specific share directory can be configured in respective host sections. See example in `workers.ini`. If share directory is not configured, worker will check if `/var/lib/openqa/$hostname` does not exist or use default `/var/lib/openqa/share`.
There are also changes in `api_call` method, now accepts named options `json, params, callback`. Callback is used to queue actions dependent on result of api call.
=> Worker support for multiple webUIs

assets/javascripts/running.js, codecov.yml, lib/OpenQA/WebAPI/Controller/Running.pm, lib/OpenQA/Worker.pm, t/full-stack.t
There is nothing running, but we still know the job, so 404 is incorrect
=> Avoid 404 errors on scheduled jobs

lib/OpenQA/Schema/Result/Needles.pm, lib/OpenQA/Worker/Common.pm, lib/OpenQA/Worker/Engines/isotovideo.pm, lib/OpenQA/Worker/Jobs.pm
- new isotovideo will store jsonfile path already relative to
$prjdir, no need to process further.
- add an error log if needle can not be found even after adding
$prjdir prefix
- fixes https://progress.opensuse.org/issues/1609
- expects os-autoinst/os-autoinst#703
=> Do not do any jsonfile path processing

lib/OpenQA/WebAPI/Plugin/AMQP.pm
This will allow the rabbitmq user to use less privileges.
The exchange needs to be created by the rabbitmq admin.
See also: https://w3.suse.de/~dheidler/amqp.html
=> AMQP: Declare exchange passive and durable

lib/OpenQA/WebAPI/Controller/Test.pm, t/10-tests_overview.t
Fixes a problem for '/tests/overview' when no build is specified, for example
to show the most recent build. Problem was that an 'unrelated' build could
show up as the groupid was not forwarded to the database query.
Also introduces a check for multiple groups and no build which is currently
not supported.
Probably introduced by dce250d.
Related progress issue: https://progress.opensuse.org/issues/15988
=> Fix build lookup for single groups (poo#15988)

lib/OpenQA/Worker.pm, lib/OpenQA/Worker/Jobs.pm, t/full-stack.t
There was a problem when a job could not find an asset, giving the reason as
setup failure. The job would go into a forever uploading state and would inhibit
the worker to quit.
=> Fix an error when job result is "setup failure"

docs/GettingStarted.asciidoc, lib/OpenQA/WebAPI/Controller/API/V1/Iso.pm, lib/OpenQA/WebAPI/Plugin/HashedParams.pm, t/api/02-iso.t, t/api/07-testsuites.t, t/fixtures/04-products.pl
As suggested by @aaannz in #684, allow specifying a variable
as `+VARIABLE` to signify that it should not be overridden by
another setting of `VARIABLE` later in the usual precedence
order. For instance, usually if the same variable is set in both
a product and a test suite, the test suite setting wins; with
this change, if the product specified `+VARIABLE` and the test
suite `VARIABLE`, the product setting would win. One major use
for this could be to prevent an `HDD_1` set from an ISO post
request overriding the value set in templates for a test which
uses a disk image uploaded by another test.
If multiple things specify `+VARIABLE`, I believe the one that
comes highest in the normal precedence order should win out. We
could, of course, extend this to give `++VARIABLE` even greater …
=> Allow override of the usual setting precedence order

lib/OpenQA/Worker/Jobs.pm
$update_status_running can be undefined somehow, so to avoid unwanted
warnings, better check first before printing anything.
=> Fix undefined warning for _stop_job_finish

lib/OpenQA/Worker/Common.pm, lib/OpenQA/Worker/Jobs.pm
- job_timeout was registered as one shot timer and after
recent changes, one shot timers are no longer stored in
internal mapping. Stop job then was not able to find
proper timer id for removal
- this commit stores even non-recurrent timer mapping
- job_timeout now also checks if the job id matches the
expected one
=> Fix job_timeout timer not being removed after stop_job

t/full-stack.t, t/ui/01-list.t, t/ui/02-list-group.t, t/ui/06-operator_links.t, t/ui/10-tests_overview.t, t/ui/12-needle-edit.t, t/ui/13-admin.t, t/ui/14-dashboard-parents.t, t/ui/14-dashboard.t, t/ui/15-admin-workers.t, t/ui/15-comments.t, t/ui/17-product-log.t, t/ui/18-tests-details.t, t/ui/19-tests-links.t, t/ui/21-admin-needles.t, t/ui/23-audit-log.t, t/ui/PhantomTest.pm
Also don't require Chrome when testing with PhantomJS, and vice
versa. @coolo broke this pretty bad recently; please be careful
not to just throw `use` around in this stuff, it breaks the
case where Selenium is unavailable entirely.
I also took the chance to clean up the implementation and the
message a bit.
=> Fix UI test skipping when modules not available

lib/OpenQA/Schema/Result/Jobs.pm, t/05-scheduler-dependencies.t
- certain multi-dependency configurations duplication can traverse
jobs graph more than once and tries to recreate already existing
dependencies. Instead of adding 4 array greps use find_or_create
function to avoid writing new dependencies into db if already
exists
- example scenario included in test
=> Avoid creating duplicit dependencies

docs/Installing.asciidoc
While helping a colleague with his openQA installation, there were some
steps that weren't that obvious, apache configuration and the
authentication methods for example. This fixes that.
=> Update documentation for a more obvious flow

lib/OpenQA/WebAPI/Plugin/AMQP.pm
Learn from python and generate 7bit ascii encoded json.
Fixes https://progress.opensuse.org/issues/16602
=> Fix AMQP SSL wide character JSON encoding

script/create_admin
The `create_admin` script consistently fails, as a result of the presence of the system user (added in 2ceda908 ). Paradoxically, the user created by this script was not flagged as an admin user.
The script now looks for _admin_ users, and creates one if none are present.
=> Update create_admin script

dbicdh/PostgreSQL/deploy/53/001-auto-__VERSION.sql, dbicdh/PostgreSQL/deploy/53/001-auto.sql, dbicdh/PostgreSQL/upgrade/52-53/001-auto.sql, dbicdh/SQLite/deploy/53/001-auto-__VERSION.sql, dbicdh/SQLite/deploy/53/001-auto.sql, dbicdh/SQLite/upgrade/52-53/001-auto.sql, dbicdh/_source/deploy/53/001-auto-__VERSION.yml, dbicdh/_source/deploy/53/001-auto.yml, lib/OpenQA/BuildResults.pm, lib/OpenQA/Schema.pm, lib/OpenQA/Schema/Result/JobGroups.pm, t/22-dashboard.t, t/api/10-jobgroups.t, t/deploy.t, templates/admin/group/group_property_editor.html.ep, templates/main/index.html.ep
Currently, openQA assumes that `BUILD` values can be sorted in
'version number' style, when sorting the lists of builds for the
web UI index page and job group overview pages. SUSE follows
this convention, but Fedora doesn't and never has. Our compose
`BUILD` values are productmd 'compose IDs', like this:
Fedora-26-20170301.n.0
Fedora-Rawhide-20170301.n.0
and we have recently started testing updates, whose `BUILD`
values look like this:
FEDORA-2017-561942797a
Where the final string is just a randomly-generated identifier,
it cannot be relied upon to sort in any way at all. It's not
really plausible to change these `BUILD` values into ones that
can be sorted like version numbers, so instead, let's make it
possible to specify at the job group level whether `BUILD`
values for jobs in that …
=> Allow configuration of how builds are sorted in web UI

lib/OpenQA/WebAPI/Controller/Test.pm, t/10-tests_overview.t
* First introduced with fe2fa2b
* All softfails except ones with unreviewed failed modules
are filtered out
See https://progress.opensuse.org/issues/17172
But we should discuss how to improve this in general, because that there are 2 different softfails is too confusing. Actually, I'm hoping to do the right thing this time.
=> Fix synchronization of TODO with badges

lib/OpenQA/Schema/Result/Comments.pm, t/api/09-comments.t
For example for deleting comments over API it makes sense if they identify
themselves on retrieval. Let's say we retrieve comments on a job and we want
to delete a comment on the job. For that we need the id of the comment.
=> Add id to comments over API to allow referencing

lib/OpenQA/Utils.pm
- when DISTRI test directory didn't exist, $dir variable was not set
and following DISTRI-VERSION directory lookup was not successful
- this patch adds DISTRI-VERSION dir as the first one to try if
VERSION is set
=> Do correct DISTRI-VERSION case dir lookup

docs/GettingStarted.asciidoc, docs/UsersGuide.asciidoc, lib/OpenQA/Schema/ResultSet/Jobs.pm, lib/OpenQA/WebAPI/Controller/API/V1/Iso.pm, t/api/02-iso.t
Instead of obsoleting an older build and getting incomplete results for builds
we can now deprioritize unfinished jobs and let them running. The newly
triggered build is executed with priority, i.e. scheduled tests of the new
build get started before still scheduled jobs of the old job but the old jobs
still get the chance to finish. This especially makes sense when one has
more specific ressources so that a special worker might be already
free again even though other jobs within the same job are still running.
During this time one can make good use of the available ressources and finish
builds.
Related progress issue: https://progress.opensuse.org/issues/15844
=> Add option for 'isos post' route to deprioritize old builds rather than obsolete

assets/javascripts/job_templates.js, lib/OpenQA/WebAPI.pm, t/api/03-auth.t, t/ui/05-auth.t, t/ui/06-operator_links.t, t/ui/17-product-log.t, templates/admin/group/group_property_editor.html.ep, templates/admin/job_template/index.html.ep, templates/layouts/bootstrap.html.ep
See https://progress.opensuse.org/issues/13858
Concerning tables
* Medium types
* Machines
* Test suites
* Job groups and job templates
* Scheduled products
=> Allow anonymous read access to operator tables

docs/Installing.asciidoc
Added some instructions about turning on SSL for apache on openSUSE that aren't obvious when coming from other distros.
=> [docs]: added documentation about setting up ssl

script/client, t/api/09-comments.t
This prevents the client script to encode URLs twice. Seems like Mojo::URL encodes (again) so doing this manually isn't required anymore. To test, just call the script like:
```
script/client --host http://localhost:9526 jobs/128/comments post text=http://open.qa
```
Automatic tests are still missing (the extension in the first commit does not test for the client issue). I could add them to the full stack test where the client script is already executed or create a new test only for the client script.
=> client script: Don't encode URL twice

assets/javascripts/admin_worker.js, assets/javascripts/tests.js, t/ui/15-admin-workers.t
Since the table is server-side, the buttons must be
initialized again when the table is redrawn.
See https://progress.opensuse.org/issues/17830
=> Fix restarting jobs from worker page

t/ui/15-admin-workers.t, templates/admin/workers/index.html.ep, templates/admin/workers/worker_status.html.ep
Status column was mistakenly printing Dead even for live workers
due to quering database instead of websocket connection as
Connected status was.
This PR merge information of both into the Status. When worker
is idle, websockets connection is queried and Online/Offline is
displayed, else information about job is available.
=> Merge 'Status' and 'Connected' columns in workers overview

docs/UsersGuide.asciidoc, lib/OpenQA/WebAPI/Controller/Test.pm, t/10-tests_overview.t
Just lookup the latest build from the first group so that we have useful URLs
e.g. for bookmarking.
Related progress issue: https://progress.opensuse.org/issues/13712
=> Add support for multiple group, no build on /tests/overview

lib/OpenQA/Schema/Result/Jobs.pm
Done in terms of https://progress.opensuse.org/issues/17950 to lower the chance such
to happen. For this we lower the quantity of reviewed jobs and allow only 2 state
changes
=> Lower down quantity of automatic carryover

t/14-grutasks.t, t/full-stack.t, t/ui/06-operator_links.t, t/ui/12-needle-edit.t, t/ui/13-admin.t, t/ui/17-product-log.t, t/ui/18-tests-details.t, t/ui/19-tests-links.t, t/ui/21-admin-needles.t, t/ui/23-audit-log.t
OBS does not allow network access to build hosts, we must skip tests requiring network access to succeed.
Also for some reason my branch tests are frequently failing on matching text of complete dropdown menu instead of logged in line. I added one more commit that makes it specific we are interested only in logged in line.
=> Add environmental variable to skip online tests

lib/OpenQA/Schema/Result/Comments.pm, lib/OpenQA/Schema/ResultSet/Jobs.pm, t/17-build_tagging.t, t/api/02-iso.t
This regex was still too restrictive, even after the last time
it was loosened. It rejects BUILD values with a period after
the final dash, which all Fedora BUILDs have, because they look
like this:
Fedora-25-20170327.n.0
I don't see any value to this restriction, so I think we can
just simplify the regex to allow any string consisting only of
dashes, periods, @s, digits and word characters.
This was preventing tagging builds as 'important' working for
Fedora.
=> Relax the regex for build values in tag: comments again, handle `VERSION-BUILD` format tags when exempting jobs for important builds from obsoletion

assets/javascripts/needleeditor.js, t/ui/12-needle-edit.t
Fixes the verification in the needle editor when not copying areas.
Might also fix https://progress.opensuse.org/issues/16596
=> needle editor: Distinguish tag/area selection in check

lib/OpenQA/Worker.pm
Fix poo#17812 introduced by 00108e5813187e9616612130d4174b1947df59b0
so now thests are able to find assets in the share/factory asset dir.
http://deimos.suse.de/tests/550 has a sucessful run.
=> Fix overriden shared $dir worker registration

templates/main/group_builds.html.ep
See https://progress.opensuse.org/issues/12942
This shows how the width of the progress bars is adjusted (the larger progress bar shows how it was before for comparison):
Alternative would be wrapping. It would look like this (not part of the PR):
Advantage would be that it works with any text length. The problem with indentation could be solved. However, it doesn't look very nice.
=> WIP/Feedback: Adjust media queries and progress bar width

docs/WritingTests.asciidoc, lib/OpenQA/Schema/Result/Jobs.pm, t/10-jobs.t
This partly reverts commit
487fcdbd56f5e46bd569a5ffcbbbb0e90da5744a, which made openQA's
result calculation ignore the 'important' test flag entirely.
This is really inconvenient to Fedora, we found the ability to
have 'unimportant' tests quite handy and have used it in a few
different ways. Adapting to its removal has proved very hard.
So this partly restores the 'important' behaviour, but with an
'ignore_failure' flag instead of 'important'. This both inverts
the default from before, and behaves slightly differently: no
soft failure mode is involved. 'ignore_failure' does exactly
what it sounds like - a failure or soft failure of the module
will never result in failure of the overall test. If a test is
made up entirely of 'ignore_failure' modules, it will always
have 'PASSED' as its …
=> Replace old 'important' behaviour with 'ignore_failure'

templates/test/details.html.ep
The code that shows little flags for each module on the Details
page was still set up for the 'important' flag that got removed
a bit ago. This adjusts it to instead show a 'ignore_failure'
flag with an appropriate description.
=> Adjust test module flags on Details page for ignore_failure

docs/WritingTests.asciidoc
This flag has existed for a long time, but this comment block
(which pops up both here and in os-autoinst) has never explained
it.
=> Document the 'norollback' flag in WritingTests

script/client
Fixes [poo#18494](https://progress.opensuse.org/issues/18494)
Error for missing module:
```
ERROR:  - IO::Socket::SSL 1.94+ required for TLS support
```
Server error:
```
ERROR: 403 - Forbidden
{ error => "no api key", error_status => 403 }
```
=> Better error msg for openqa client

assets/stylesheets/openqa.scss
Related to https://progress.opensuse.org/issues/12942
Now the text gets shortend by dots before overlapping.
=> Shorten build-numbers with dots to prevent overlapping

lib/OpenQA/WebAPI/Controller/Test.pm
Generally we enable the virtio terminal through the Machine settings which
means it is enabled for many tests which don't use it. QEMU creates a log file
for the virtio serial device whether it is used or not, so we have a lot of
empty log files. This was reported to be confusing so this commit only
uploads the file if it has data in it.
The behavior for other files is deliberately left unchanged so as to avoid
hiding the existence of an empty file when it might be used to diagnose a
problem.
https://progress.opensuse.org/issues/17962
=> Do not upload empty serial_terminal.txt

Makefile
As the 'checkstyle' test can take some time provide a switch to skip it on
demand which can be useful when for example one wants to collect coverage from
a single test and execute this in a faster manner.
Example use: `make CHECKSTYLE=0 PROVE_ARGS=t/full-stack.t coverage-html` to
execute the full stack test and collect coverage without needing to conduct
the long-running style check every time.
=> Makefile: Allow to skip checkstyle

lib/OpenQA/Schema/Result/Jobs.pm, lib/OpenQA/Schema/ResultSet/Jobs.pm, t/api/02-iso.t
the function used to return from the function even if only one out of 3 assets
was not to be registered. Now moved the check to the loop
See https://progress.opensuse.org/issues/18862
=> Register job assets even if one of the assets need to be skipped

script/clone_job.pl
```
$ clone_job.pl …
Created job #123456: openSUSE-Tumbleweed-DVD-Build1234-gnome -> https://openqa.opensuse.org/t123456
```
=> clone_job.pl: Print URL of generated job for easy access

assets/javascripts/audit_log.js, lib/OpenQA/WebAPI/Controller/API/V1/Iso.pm, t/api/02-iso.t, t/api/08-jobtemplates.t, t/fixtures/04-products.pl, t/ui/17-product-log.t
See commit messages and https://progress.opensuse.org/issues/10902
=> Handle wrong/missing job dependencies appropriately

profiles/apparmor.d/usr.share.openqa.script.worker
Fixing https://progress.opensuse.org/issues/18078
=> Allow lscpu to read all of /proc - but only lscpu

assets/javascripts/comments.js, t/ui/14-dashboard-parents.t, templates/branding/plain/docbox.html.ep, templates/comments/comment_row.html.ep, templates/main/group_overview.html.ep, templates/main/index.html.ep, templates/main/parent_group_overview.html.ep
* Replace anchor links with an id attribute at the right place
* Fix minor mistakes
* Also note that
* using `/>` is not allowed to close an empty link
* we are using HTML and not XHTML anyways
* the markdown renderer still produces bad HTML which is not fixed
in this commit
* implicitely closing `<p>` via `<hr>` and then adding a
surplus `</p>`
* using obsolete `<font ...` tag
=> Fix invalid HTML

assets/stylesheets/overview.scss
Wrapping looks much better than spilling the text over the popup border:
See https://progress.opensuse.org/issues/14732
=> Fix showing long needle name in hover popup

templates/admin/workers/index.html.ep
"Current step" was shown along with the test status and also in the column status. The only reason why it was shown with the status is to be shown on the worker view, but I added it as a new point.
With these changes the status field, only shows the status.
=> Remove duplicate "current step"

lib/OpenQA/Utils.pm, lib/OpenQA/WebAPI.pm, t/16-utils.t, templates/layouts/bootstrap.html.ep
Adding helper to cache and return the current running version.
Currently:
Git:
Installed from rpm:
Related progress issue: [Poo#16232](https://progress.opensuse.org/issues/16232)
=> Add helper to get current version of openQA and display it in the footer

lib/OpenQA/Worker/Cache.pm, t/full-stack.t
This changes in the Cache.pm attempt to solve the race condition where
more than two workers downloading one file, could try to remove the
same lockfile.
This refactor attempts to solve the situation, by using sqlite, since
it is able to handle on it's own database locking and atomic
transactions (With AutoCommit), so once a DDL is issued, sqlite handles
automatically the persistance of those bits.
In case the cache.db file is not present, it will be deployed from
scratch.
Since we are saving now size and etag, we can now easily know if an
asset has been changed, by sending the etag during the first request
and bailing out if there are no changes.
The limiting of assets is done in two stages: at the init of the cache
and after the download of an asset (304 for now are ignored).
Once this …
=> Refactor Cache.pm to use SQLite instead of json

Makefile
A service file that starts a worker service dedicated for debugging test with snapshots.
=> Add service file for workers with "no cleanup" option

assets/stylesheets/openqa.scss, t/22-dashboard.t, templates/main/group_builds.html.ep
Related to https://progress.opensuse.org/issues/12942
Already fixed the issue with those long build numbers by shorten them with dots. But then the tags got cut aswell. Now the tags are always visible and just the text and timeago part gets shortend.
=> Prevent tags from getting cut by long build numbers

lib/OpenQA/Worker/Engines/isotovideo.pm
Prevents the syncing to abort e.g. for workers running with '--no-cleanup'.
=> Unlink existing asset symlinks on syncing

cpanfile, etc/openqa/openqa.ini, lib/OpenQA/WebAPI.pm, systemd/openqa-webui.service
Actual code is from @kraih for cavil - I adopted it only to openQA.
=>  Implement a config option to restart workers that grew too big

assets/javascripts/overview.js, lib/OpenQA/Schema/ResultSet/Jobs.pm, lib/OpenQA/WebAPI/Controller/Test.pm, t/10-tests_overview.t, t/ui/10-tests_overview.t, templates/test/overview.html.ep
Add query parameter 'failed_modules' on /tests/overview yielding only jobs where the supplied modules have failures (including soft failures)
The parameter can be set in the UI, or directly from the url:
`/tests/overview?distri=sle&version=12-SP2&build=1629&groupid=25&arch=aarch64&result=failed&failed_modules=install_and_reboot,shutdown`
(in the image there was only a failure with shutdown and not with install_and_reboot)
Not sure if soft-failures should be listed as well, so in this implementation are showed.
@okurz can you also shed some light on AC3? (not very sure what's the suggested behavior) aside from that i think i've covered the other ACs
Would be also maybe a good idea to be able to filter also with different states per-module?
Progress related issue: …
=> Inspect failed modules in /tests/overview

lib/OpenQA/Worker/Jobs.pm
I sometimes see something like this when asset upload of ISO image with
svirt backend fails:
```
[DEBUG] uploading my.iso
[WARN] Upload attempts remaining: 5/5 for my.iso, in 5 seconds
.....
print() on closed filehandle $log at /usr/share/openqa/script/../lib/OpenQA/Worker/Jobs.pm line 263.
```
=> Fix print() on closed filehandle $log

lib/OpenQA/Utils.pm, lib/OpenQA/WebAPI/Controller/Running.pm, lib/OpenQA/WebAPI/Controller/Step.pm, lib/OpenQA/Worker/Jobs.pm, t/api/04-jobs.t, t/lib/OpenQA/Test/Database.pm
As discussed in https://github.com/os-autoinst/openQA/pull/1316 OpenQA::Utils contains `file_content()` , that can be replaced with Mojo::File pretty straightforward.
Aside from that, `file_content()` it's not tested while Mojo::File is.
=> Replace file_content() with Mojo::File

templates/branding/openSUSE/external_reporting.html.ep
The project name was changed in bugzilla and clicking on "Report product bug" links to an inexistence page.
=> Fix bugzilla reporting link for SLE-12-SP1

lib/OpenQA/ServerStartup.pm, t/25-serverstartup.t, t/config.t
If a file for log is supplied, then format the logger to print also the time, otherwise don't.
Related Progress issue: [Poo#13866](https://progress.opensuse.org/issues/13866)
~~WIP until i figure out why unit test is failing on travis (but succeds locally)~~
Added tests cases as well to cover why CI was failing
=> Disable printing time when logging to STDERR.

dbicdh/PostgreSQL/deploy/54/001-auto-__VERSION.sql, dbicdh/PostgreSQL/deploy/54/001-auto.sql, dbicdh/PostgreSQL/upgrade/53-54/002-auto.sql, dbicdh/SQLite/deploy/54/001-auto-__VERSION.sql, dbicdh/SQLite/deploy/54/001-auto.sql, dbicdh/SQLite/upgrade/53-54/002-auto.sql, dbicdh/_common/upgrade/53-54/001-migrate-jobs.pl, dbicdh/_source/deploy/54/001-auto-__VERSION.yml, dbicdh/_source/deploy/54/001-auto.yml, lib/OpenQA/Schema.pm, lib/OpenQA/Schema/Result/Jobs.pm, lib/OpenQA/Schema/ResultSet/Jobs.pm, lib/OpenQA/WebAPI/Controller/API/V1/Job.pm, t/14-grutasks.t, t/21-needles.t, t/api/04-jobs.t, t/fixtures/01-jobs.pl, t/ui/01-list.t, t/ui/18-tests-details.t
In before there was no real check for most settings implicitly allowing
undefined settings but causing perl warnings. This commit now properly
tests job results where no setting is set besides the name composed of
'TEST' itself. It is not pretty in all cases when the individual
string components are empty but it works.
Related progress issue: https://progress.opensuse.org/issues/6762
=> Make 'TEST' the only proper mandatory test setting

t/18-fedmsg.t, t/23-amqp.t, t/24-worker.t, t/basic.t, t/full-stack.t
Utilize Mojo::File to create specific sandboxes folders to avoid polluting source code directory with data needed for unit testing generated by local tests.
Related Progress issue: [Poo#15138](https://progress.opensuse.org/issues/15138)
=> Avoid unit test to write on source code directory

t/04-scheduler.t
ensure with tests that OpenQA::Scheduler::FakeApp is strictly mimicking a Mojolicious application (was about to add them in the other PR, sorry for the noise ). 
Also if this test is not full, it's a start to avoid future breakages
=> Add tests to scheduler to cover OpenQA::Scheduler::FakeApp

t/24-worker.t, t/26-controllerrunning.t
Mock test the Running controller to get rid of codecov unexpected coverage
See [discussion](https://github.com/os-autoinst/openQA/pull/1331#issuecomment-302682216) and related progress issue: https://progress.opensuse.org/issues/18796
~~WIP: plan to cover also lib/OpenQA/Worker/Jobs.pm L 157/158~~ 
Edit: sorry, just noticed (after opening the PR) that @Martchus was assigned to it, not sure if i should continue on that
=> Add unit test to fix codecov "uncovered changes"

lib/OpenQA/Worker/Cache.pm
This PR fixes poo#19270 and poo#19278
=> Minor fixes to the cache: Deadlock and Perl structure

lib/OpenQA/Utils.pm
For consistency with bugzilla and OBS.
=> Also recognize kde bugrefs in Utils.pm

script/clone_job.pl
I wasn't able to clone a job because the apache2 service was disabled on my machine, so i added a message at this place.
=> Add error message for missing webserver

docs/Contributing.asciidoc, lib/OpenQA/ServerStartup.pm, lib/OpenQA/Utils.pm, lib/OpenQA/WebAPI.pm, lib/OpenQA/WebAPI/Auth/Fake.pm, lib/OpenQA/WebAPI/Auth/OpenID.pm, lib/OpenQA/WebAPI/Auth/iChain.pm, t/16-utils.t, t/25-serverstartup.t, t/lib/OpenQA/FakePlugin/Foo.pm, t/lib/OpenQA/FakePlugin/FooBar.pm, t/lib/OpenQA/FakePlugin/FooBaz.pm, t/lib/OpenQA/FakePlugin/FooFoo.pm
With this change we allow the plugins (and not only) to require specific configurations to be loaded.
A Perl module or a Mojolicious Plugin (based on Mojo::Base or Mojolicious::Plugin) if has the method (or attribute, in case of Mojolicious::Plugin) "configuration_fields" and returns a HASH reference, the key/value pairs are cycled to get the relevant configuration from the Ini file parser, and then fill the application config instance appropriately.
E.g. if we declare a plugin like so:
package OpenQA::MyPlugin::Foo;
use Mojo::Base -base;
has 'configuration_fields' => sub {
{
auth => {
method => 1
}};
};
1;
The server application will fetch the "auth" section and "method" parameter from the Ini parser object, populating the configuration structure inside the application.
See related …
=> Allow plugins to load specific configurations from Ini file

dbicdh/PostgreSQL/deploy/55/001-auto-__VERSION.sql, dbicdh/PostgreSQL/deploy/55/001-auto.sql, dbicdh/PostgreSQL/upgrade/54-55/001-auto.sql, dbicdh/SQLite/deploy/55/001-auto-__VERSION.sql, dbicdh/SQLite/deploy/55/001-auto.sql, dbicdh/SQLite/upgrade/54-55/001-auto.sql, dbicdh/_source/deploy/55/001-auto-__VERSION.yml, dbicdh/_source/deploy/55/001-auto.yml, lib/OpenQA/Schema.pm, lib/OpenQA/Schema/Result/Bugs.pm, lib/OpenQA/WebAPI.pm, lib/OpenQA/WebAPI/Controller/API/V1/Bug.pm, t/25-bugs.t, t/api/11-bugs.t, t/ui/10-tests_overview.t
See https://progress.opensuse.org/issues/12092
> we really need the icons on the matrix view to also show the status of the bug in bugzilla. Its particually important to identify bugs which Bugzilla reports as closed but are still present in the product - These should probably be flagged with a red bug icon or something similar. ~rbrown
=> Show bug status in openQA test result matrix

dbicdh/PostgreSQL/deploy/56/001-auto-__VERSION.sql, dbicdh/PostgreSQL/deploy/56/001-auto.sql, dbicdh/PostgreSQL/upgrade/55-56/001-auto.sql, dbicdh/SQLite/deploy/56/001-auto-__VERSION.sql, dbicdh/SQLite/deploy/56/001-auto.sql, dbicdh/SQLite/upgrade/55-56/001-auto.sql, dbicdh/_source/deploy/56/001-auto-__VERSION.yml, dbicdh/_source/deploy/56/001-auto.yml, lib/OpenQA/Schema.pm, lib/OpenQA/Schema/Result/JobGroupParents.pm, t/22-dashboard.t, t/api/10-jobgroups.t, templates/admin/group/group_property_editor.html.ep
Required a schema upgrade to add `build_version_sort` to `JobGroupParents`.
For the form, i kept the same ordering of fields as we already use for `JobGroup` to avoid confusing the user (and that's why the doubled-`if $parent` in the template).
See related progress issue: https://progress.opensuse.org/issues/18082
=> Extend sorting by time to parent group overview

lib/OpenQA/Utils.pm, t/ui/15-comments.t
* To prevent this not only at the end regex isn't good enough
* So this does not fix the whole problem, only the particular
case in https://progress.opensuse.org/issues/19776
=> Prevent bugref_to_href replacement at end of title

t/full-stack.t
By adding the control variable `INTEGRATION_TESTS=1` we allow now openQA to control the test plan generated by isotovideo, and therefore allowing the enhancement of both, without affecting eachoter.
This requires https://github.com/os-autoinst/os-autoinst/pull/826
=> Enable INTEGRATION_TESTS

script/fetchneedles
Sync the fetch needles script with commit
c7c37edc2f63b96bedfb68d83c6da603b1435bf2 where shared workers have
been introduced, and moved all the contents from /var/lib/openqa/tests
to /var/lib/openqa/share/tests
=> Fix test directory to share/tests

assets/javascripts/needlediff.js, assets/javascripts/needleeditor.js, docs/GettingStarted.asciidoc, t/ui/12-needle-edit.t, templates/step/edit.html.ep
* See particular commit messages and https://progress.opensuse.org/issues/16058
* Showing exclude areas in diff has been tested manually because it is hard to check whether the canvas elements are drawn correctly. The concerning JavaScript code is covered at least. Might be a test case for openQA in openQA test.
=> Better support exclude areas

lib/OpenQA/Schema/ResultSet/Jobs.pm, lib/OpenQA/WebAPI/Controller/API/V1/Job.pm, t/api/02-iso.t
Currently when clone_jobs is being spammed to the web ui
there might be some jobs that go Entrepreneurial, and end
up in the wrong worker.
This is caused most likely by notify_workers being called
by another clone_job call, while the current one is being
still created, this definitely solves poo#18684 but would
need some validation for poo#20002
=> Create jobs from settings within a transaction

lib/OpenQA/WebAPI/Auth/OpenID.pm
Supply error text in one argument to `Mojo::Log error()`, avoids to
clutter log file with multi-lines.
A change in https://github.com/os-autoinst/openqa-logwarn will follow to ignore login error reports
=> Avoid OpenID login to clutter log files

script/dump_templates, script/load_templates
I noticed that the error messages are not very helpful in some cases, eg. invalid JSON returned by the server. (In my case starting openQA via morbo caused long responses like job templates of osd/o3 being truncated and hence invalid JSON.)
=> Improve load_templates/dump_templates

lib/OpenQA/WebAPI/Controller/API/V1/Bug.pm
t_updated will be set to current time
even if the new values are identical to the old ones
This is necessary because `t_updated` is used to track when the update script updated the bug tha last time via the API to ensure that the bug isn't updated again, before some time intervall has passed.
=> Enforce t_updated incr for bugs

t/full-stack.t, t/ui/01-list.t, t/ui/02-list-group.t, t/ui/06-operator_links.t, t/ui/10-tests_overview.t, t/ui/12-needle-edit.t, t/ui/13-admin.t, t/ui/14-dashboard-parents.t, t/ui/14-dashboard.t, t/ui/15-admin-workers.t, t/ui/15-comments.t, t/ui/17-product-log.t, t/ui/18-tests-details.t, t/ui/19-tests-links.t, t/ui/21-admin-needles.t, t/ui/23-audit-log.t
As with https://github.com/os-autoinst/os-autoinst/pull/820 ,
Perl 5.26 not including the current working directory in INC
breaks loading of modules in some tests.
=> Add . to INC for tests that use local modules (perl 5.26 doesn't)

dbicdh/PostgreSQL/deploy/57/001-auto-__VERSION.sql, dbicdh/PostgreSQL/deploy/57/001-auto.sql, dbicdh/PostgreSQL/upgrade/56-57/001-auto.sql, dbicdh/SQLite/deploy/57/001-auto-__VERSION.sql, dbicdh/SQLite/deploy/57/001-auto.sql, dbicdh/SQLite/upgrade/56-57/001-auto.sql, dbicdh/_common/upgrade/56-57/001-migrate-jobs.pl, dbicdh/_source/deploy/57/001-auto-__VERSION.yml, dbicdh/_source/deploy/57/001-auto.yml, lib/OpenQA/Schema.pm, lib/OpenQA/Schema/Result/JobModules.pm, lib/OpenQA/Schema/Result/Jobs.pm, lib/OpenQA/WebAPI/Controller/Test.pm, t/10-jobs.t
See comments in https://github.com/os-autoinst/openQA/pull/1375.
Basically, this adds 4 columns to the jobs table:
```
+    passed_module_count => {
+        data_type     => 'integer',
+        default_value => 0,
+    },
+    failed_module_count => {
+        data_type     => 'integer',
+        default_value => 0,
+    },
+    softfailed_module_count => {
+        data_type     => 'integer',
+        default_value => 0,
+    },
+    skipped_module_count => {
+        data_type     => 'integer',
+        default_value => 0,
+    },
```
* The columns are used by the 'All tests' table instead of always counting the statistics on the fly as before. This should increase the performance and ease making the 'All tests' table server-side.
* The columns are automatically updated when job …
=> Add job module statistics in jobs table

templates/branding/openSUSE/external_reporting.html.ep
Old name: SUSE Container as a  Service Platform 1 .0 (CaaSP/MicroOS)
New name: SUSE Container as a Service Platform 1.0
=> Fix bugzilla links for CaaSP

lib/OpenQA/ServerStartup.pm
If you set a log level but not a log file in your openqa.ini
(or environment variables), because of this conditional, the
log level is not respected by at least openqa-scheduler and
openqa-websockets; they will log at debug level. I can't see
any justification for this, and it's a problem for my usage.
Intentionally setting no log file means that messages wind up
in the system journal when started as systemd services, but I
still want to be able to set the log *level* so the journal
isn't stuffed with debug messages.
=> Respect log level configuration even when no log file is set

assets/stylesheets/openqa.scss
Followup to https://github.com/os-autoinst/openQA/pull/1376/files#r130724832
=> More prominent color for closed bug references, old ones for open bugs

codecov.yml, lib/OpenQA/Scheduler.pm, lib/OpenQA/Scheduler/Scheduler.pm, lib/OpenQA/Schema/ResultSet/Jobs.pm, lib/OpenQA/Utils.pm, lib/OpenQA/WebAPI/Controller/API/V1/Job.pm, lib/OpenQA/Worker/Jobs.pm, systemd/openqa-scheduler.service, t/full-stack.t
- Before considering that the worker haven't accepted the job (can be optionally enabled), attempt by retrial mechanism
- Build a run-time cache of seen workers, periodically reset (can be optionally enabled) to try to allocate jobs even if workers are slow and thought dead
- Adds the ability to wake up the scheduler when we receive new jobs or restarts (optionally enabled)
- Handle gracefully quit/restarts
Let's see also if we get some coverage back
=> Scheduler: low aggressivity on slow workers

t/ui/24-feature-tour.t
This test was recently added, and uses the PhantomTest module,
but didn't include the workaround for loading it with Perl 5.26
that we recently committed to all the other tests (see #1406).
=> Include '.' in INC for 24-feature-tour.t

lib/OpenQA/Worker/Common.pm
Before:
```
Aug 04 13:57:53 monteverdi worker[34702]: [INFO] registering worker with openQA http://10.160.65.204...
Aug 04 13:57:53 monteverdi worker[34702]: [INFO] registering worker with openQA http://openqa.glados.qa.suse.de...
Aug 04 13:57:53 monteverdi worker[34702]: [INFO] registering worker with openQA http://10.160.66.147...
Aug 04 13:57:53 monteverdi worker[34702]: [INFO] registering worker with openQA http://e13.suse.de...
Aug 04 13:57:54 monteverdi worker[34702]: Unable to upgrade connection to WebSocket: 503. proxy_wstunnel enabled? at /usr/share/openqa/script/../lib/OpenQA/Worker/Common.pm line 368.
```
After:
```
Aug 04 14:34:33 monteverdi worker[37800]: [INFO] registering worker with openQA http://10.160.65.204...
Aug 04 14:34:33 monteverdi worker[37800]: [INFO] registering …
```
=> Improve error if a worker cannot connect to a WebSocket

Makefile
Right now the service files for "--no-cleanup" worker and "normal" worker are totally independent of each other. This results in errors if you try to start a normal worker instance while a no-cleanup worker runs with the same instance name.
The "Conflicts" directive takes care of stopping one of them if you try to start the other and vice versa.
I've chosen another sed-call to continue the "don't repeat yourself thought" from one line above and will always add the directive under "Wants=" - this hopefully ensures independence of the main service in the future.
=> Conflict no-cleanup worker with normal worker

t/10-jobs.t, t/21-needles.t
More tests now need to use the dummy IPC stuff due to the recent
scheduler changes (these tests fail in Fedora's package build
environment without this change).
=> Use OPENQA_TEST_IPC in more tests due to scheduler changes

assets/stylesheets/openqa.scss, templates/layouts/bootstrap.html.ep
Related to https://progress.opensuse.org/issues/13954
Added the possibility to show links in the footer section by adding a file to the brandings folder.
It would look like the following screenshot:
Please checkout out  https://gitlab.suse.de/openqa/salt-states-openqa/merge_requests/19 since it is related to this pull request.
=> Add support for custom links in footer

systemd/openqa-websockets.service
openqa-websockets/openqa-webui sometimes don't start
during boot.
See https://progress.opensuse.org/issues/21004 for
more information.
Simply add a dependency to network.target in
openqa-websockets.service.
Note: the same dependency exists in openqa-worker.service, so I used network.target like openqa-worker instead of  network.service.
=> Fix sporadic problem of systemd service start (poo#21004)

cpanfile, lib/OpenQA/Utils.pm, lib/OpenQA/WebSockets/Server.pm, lib/OpenQA/Worker/Common.pm, t/05-scheduler-full.t, t/10-jobs.t, t/25-cache.t, t/27-websockets.t, t/full-stack.t, t/lib/OpenQA/Test/Utils.pm
When we receive worker connections without prior registration, a message is displayed but no action is performed. This happens mostly when WebUI have been restarted, but not the workers associated with it. 
This is a big issue related to scheduler, since latest changes dispatch jobs completely over ws, and  if no connection between worker and WebUI is present, dispatching of jobs will stop with regard to those workers, even if we see them as online. With the changes in this PR we close the connection gracefully - so the worker is forced to re-register to the WebUI.
As a side change of this PR - prints to STDERR/STDOUT from `log_*` calls inside `OpenQA::Utils` are flushed to avoid misleading messages (see https://progress.opensuse.org/issues/23334).
See (main) related progress issue: …
=> Websocket: terminate worker connection when it's not registered

lib/OpenQA/Worker/Commands.pm, lib/OpenQA/Worker/Common.pm
Also, print the reason only when websocket server gives one.
=> Subscribe start_job/stop_job events before we call send on websocket connection

lib/OpenQA/Worker/Common.pm, lib/OpenQA/Worker/Pool.pm
When we have Websocket disconnections the $host gets removed, resulting
in the impossibility to update the status of the job to the WebUI.
Previously we used just to let the worker loop die in this case, this lead
the worker to send messages of the previous job status, even if worker is not
working on it. In that case the WebUI would reap the job after the timeout expired.
Now we need to be sure from the worker that the status sent to the
server is consistent, and not leak previous jobs information: with this change we
reset the state of worker instead of leaving the state unpredictable.
See related progress issue: https://progress.opensuse.org/issues/25124
=> Worker: reset internal state if we fail contacting the WebUI

lib/OpenQA/WebAPI/Controller/Test.pm, t/10-tests_overview.t, templates/test/overview.html.ep, templates/test/overview_result_table.html.ep
Add support for multiple distri/version/group on /tests/overview
This adds support to specify zero to multiple of distri/version/group
parameters to show multiple ones as well as look up corresponding entries from
the job results table. Every group of results will be displayed just as before
as a table on the tests overview page. Previously the title for each table was
just the "flavor" where now the "distri" as well as "version" is also
specified. For the special case of having just one "distri" and/or "version"
it is displayed just as before, i.e. only the "flavor" is shown. This also
works if "distri" and/or "version" have not been specified as query parameters
but the search in the job results based on the other parameters resolved to
just one value of these.
With this change also no …
=> Add support for multiple distri/version/group on /tests/overview

lib/OpenQA/WebSockets/Server.pm
Timeout inactivity in websockets are mostly meant for browsers and to close connection when we do not receive more data (e.g. the user leave the page open but it's AFK and such). With this change we disable the timeout from the websocket server.
Traces of frequent disconnections due to timeout are visible in websocket logs, e.g. : https://progress.opensuse.org/issues/25124
=> Websocket: Do not kill connections due to inactivity (meant mostly for browsers)

lib/OpenQA/Worker/Commands.pm, lib/OpenQA/Worker/Common.pm, t/24-worker.t, t/29-openqa_commands.t
That code already called for refactoring since it was duplicated in the codebase, so let's make the code more readable as well and add unit test for checking message construction.
This commits also remove the stop_job event subscription to notify
immediately that the worker is free, leaving that to the timer. As adamw noted, it is creating some
sorta of race condition and message is not garanted to include the updated status of the job.
That would give also a bit more time to the worker before picking up a new job, and decrease the ws server load.
=> Refactor worker status messages

lib/OpenQA/Worker.pm, lib/OpenQA/Worker/Commands.pm, lib/OpenQA/Worker/Common.pm
This is a quick try to solve poo#19408
A verification run: http://deimos.suse.de/tests/6104#step/bootloader/6 that's showing just the needle that was created in interactive mode.
=> Sync needles when caching is enabled

assets/stylesheets/openqa.scss, lib/OpenQA/WebAPI/Plugin/Helpers.pm, t/10-tests_overview.t, templates/test/overview_result_table.html.ep, templates/test/tr_job_result_failedmodules.html.ep
Alternative to https://github.com/os-autoinst/openQA/pull/1090
=> Trim less text in overview tables by using CSS instead of custom code

assets/javascripts/test_result.js, lib/OpenQA/Schema/Result/Jobs.pm, lib/OpenQA/WebAPI/Controller/Test.pm, templates/test/running_table.html.ep, templates/test/scheduled_table.html.ep
This is an approach of adding all the states to the /tests route, so that wen can see all tests that can be represented through any of `OpenQA::Schema::Result::Jobs::STATES`. 
While it seems to be feasible, there are few things that migh need to change (Including how we are representing the tests at all). Also not to do unnecesary queries thatspam the database every time someone is opening /tests.
=> Add all job states to be monitored from /tests route

lib/OpenQA/Schema/Result/Jobs.pm, lib/OpenQA/Utils.pm, lib/OpenQA/WebAPI.pm, lib/OpenQA/WebAPI/Controller/API/V1/Job.pm, lib/OpenQA/WebAPI/Controller/Test.pm, t/api/04-jobs.t
This allows to be able to use the json api to get not only a job information but also the details if there are any
=> Add support for getting test results as json on the job json api

script/clone_job.pl, script/dump_templates, script/load_templates
Using the same approach as in client we can symlink clone_job.pl and others to
somewhere else which allows easier packaging of the according tools as
applications within a standalone client package.
=> Ensure use of symlinked applications for clone_job/dump_templates/load_templates

Makefile
On Debian/Ubuntu, /bin/sh is not bash, and cannot use {a,b}
=> make Makefile non-bash environment friendly

docs/Contributing.asciidoc
* Add "Starting the webserver from local Git checkout"
* Update "Managing the database"
---
I'm not sure whether the provided info is correct, but when starting the web server from local Git checkout I noticed some time ago that there are now some extra steps are required. The openQA in openQA tests also contains similar commands for that purpose.
I also updated the steps for database migration because some of the mentioned steps seem to be irrelevant/outdated and some other useful hints like creating a backup were missing. But I'm not sure whether the info is correct, especially concerning the notes at the end.
=> Improve documentation for contributors

assets/javascripts/running.js, assets/javascripts/test_result.js, assets/stylesheets/openqa.scss, assets/stylesheets/overview.scss, lib/OpenQA/WebAPI/Controller/Running.pm, t/full-stack.t, t/ui/PhantomTest.pm, templates/test/live.html.ep
See https://progress.opensuse.org/issues/20606
This disables the live log and the live terminal by default. The user can expand it similar to the filter boxes.
Since currently the live stream is not available unless the live log is consumed as well, this prevents the live stream to work. The 2nd commit should to fix that.
Additionally, this ensures that the streams for the live view are only consumed when the 'Live view' tab is shown.
Tested manually:
* If entering the 'Live view' tab the last message in openQA web UI
log is `Telling worker to start providing livestream`
* If leaving the 'Live view' tab the last message in openQA web UI
log is `Telling worker to stop providing livestream`
* Developer console in browser shows requests for stream/livelog
accordingly
* If there are two …
=> Disable live log by default

assets/javascripts/openqa.js, assets/javascripts/tests.js, assets/stylesheets/openqa.scss, t/ui/01-list.t, templates/test/list.html.ep
See https://progress.opensuse.org/issues/19388
I could not use the approach from the job results overview page. The
structure of the pages are just too different.
However, this implementation using the filtering of the data table
is quite simple and will not cause any performance regressions.
WIP because tests are missing. But maybe it is better to get some feedback before anyways.
=> Allow filtering by result on 'All tests' page

script/tidy
Debian patches use "quilt" patch system and it saves files pre-patched
files under .pc directory. Accidentaly prove works for directory and
tidy check fails, so ignore this .pc directory.
=> ignore .pc directory

lib/OpenQA/FakeApp.pm, lib/OpenQA/Utils.pm, lib/OpenQA/Worker.pm, lib/OpenQA/Worker/Commands.pm, lib/OpenQA/Worker/Common.pm, lib/OpenQA/Worker/Engines/isotovideo.pm, lib/OpenQA/Worker/Jobs.pm, script/worker, t/24-worker.t, t/28-logging.t
Changes the log level to debug if --debug or --verbose is applied. Default is info level.
The command line switches have precedence over workers.ini settings.
In the case no value is set in the workers.ini:
* if no --verbose or no --debug  is set then the default log level is info.
* if --verbose of --debug is set then the log level is set to debug
In the case a value is set in the workers.ini:
* if no --verbose or no --debug  is set then the default log level will be
what's specified in the workers.ini file
* if --verbose of --debug is set then the log level is set to debug
=> Changes the log level

etc/openqa/openqa.ini, lib/OpenQA/WebAPI/Plugin/AMQP.pm, t/23-amqp.t
The default is 60 seconds in Mojo::Client::RabbitMQ, but this is too
long for our HA proxy's ssl tunnel
=> Make heartbeat timeout for rabbitmq configurable

docs/Installing.asciidoc
The documentation only shows info about Leap 42.2 and Tumbleweed.
Since the openQA version on official Leap 42.3 repositories is not compatible with the new versions and it will not be supported or maintain, I think it should be a good idea to promote installing openQA on Leap 42.3 from devel repos as on Tumbleweed.
=> Mention repos for Leap 42.3

templates/layouts/dependencies.html.ep
Job names are displayed in link title now, which makes hard to find correct one
=> Display job name on dependencies list

lib/OpenQA/Utils.pm, lib/OpenQA/WebSockets/Server.pm, lib/OpenQA/Worker/Commands.pm, lib/OpenQA/Worker/Common.pm, script/openqa-websockets, script/worker, t/05-scheduler-full.t, t/20-workers-ws.t, t/24-worker.t, t/27-websockets.t, t/lib/OpenQA/Test/Utils.pm
Having a fixed timer to send messages generates load on WebSockets server side when we have a large number of worker, this proposal tries to partially avoid this introducing dynamic timers allocations (as in slots) and enlarging the time window in which an instance can be detected as dead.
See [Poo](https://progress.opensuse.org/issues/25960) for more informations.
This PR is not introducing any form of clock syncronizations yet, but makes easier to introduce them in a second time. 
Giving as assumption that most likely workers are started all together (hence, **no form of worker clock sync yet**, but this method would be still more performant than having a fixed value)  this PR is creating the possibility to modify on-demand and with relatively small changes the behavior of all workers …
=> Worker worker_status timer optimizations

docs/UsersGuide.asciidoc, lib/OpenQA/WebAPI/Controller/API/V1/Iso.pm, t/api/02-iso.t
By default, whenever openQA receives an ISO POST request and
schedules a set of jobs for the posted image, any pending jobs
with the same DISTRI, VERSION, FLAVOR and ARCH are canceled.
This can be too aggressive, so a _NOOBSOLETEBUILD parameter is
available which disables this behaviour entirely. However, there
may be a need for a happy medium.
For instance, in Fedora, it's too aggressive to cancel any job
with the same DISTRI, VERSION, FLAVOR and ARCH as a newly-POSTed
ISO, especially at present, since we are currently producing two
streams of composes for the same release (VERSION), modular and
non-modular; we don't want pending jobs for a non-modular
compose to be canceled when a modular compose with the same
VERSION lands, and vice versa. However, there's also a problem
with …
=> Add _ONLYOBSOLETESAME parameter, obsolete only same BUILD jobs

script/generate-documentation
A commit on gh-pages is created every time a new commit is added
to HEAD, avoid creating new ones, when the git diff shows a very
well known pattern.
=> Avoid creating useless commits on GH-pages

assets/stylesheets/openqa.scss, lib/OpenQA/Setup.pm, lib/OpenQA/WebAPI.pm, lib/OpenQA/WebAPI/Controller/Main.pm, t/config.t, t/ui/05-auth.t, templates/layouts/bootstrap.html.ep, templates/main/changelog.html.ep
See https://progress.opensuse.org/issues/16062
Still to improve:
* formatting
* more generic approach for getting change logs or at least handle case where logs can not be queried via `rpm`
* maybe some caching
* also show os-autoinst log for worker
=> Add link for docs, show changelog

profiles/apparmor.d/usr.share.openqa.script.worker
See related Progress issue: https://progress.opensuse.org/issues/27934
=> Extend apparmor permissions for /usr/share/openqa/lib/** 

t/api/12-admin-workers.t
A test recently added by @coolo causes it to hit DBus, so we
need this or the test fails in package build environments. The
call that gets made is `ws_is_worker_connected`, so also set
up the test WebSockets service. The test will actually still
pass even if the calls fail, but let's be 'correct'.
=> Use OPENQA_TEST_IPC for 12-admin-workers.t

templates/step/src.html.ep
We don't save changes to the source code anyway so there is no real reason to not be read-only.
Line wrapping was also enabled because, in the current implementation, it is barely visible if a line is cut off by the maximum width of the editor if the horizontal scroll bar gets pushed off the screen (due to many lines of source code).
There is a second solution for this problem: limiting the size of the editor field to the height of the screen so that the horizontal scrollbar is always visible. 
I've split up the line wrapping into a separate commit for easy cherry-picking of not desired.
=> Improve web editor

t/fixtures/01-jobs.pl, t/fixtures/05-job_modules.pl
Postgresql has a different logic than Sqlite has for how to assign IDs
=> Remove IDs from fixtures if they are in sequence

lib/OpenQA/Worker.pm, script/generate-documentation, t/05-scheduler-full.t, t/full-stack.t, t/lib/OpenQA/Test/Utils.pm
Ensure that upon failure to setup the worker's project dir (due to missing directory)
print what were the attempts via debug, and send to the error the reason for the failure.
=> Print project directory

lib/OpenQA/Setup.pm, t/28-logging.t, t/data/logging/openqa.ini
The openqa.ini log level wasn't being set correctly.
This caused for the server components (resource allocator, scheduler...) to ignore the level defined in the openqa.ini file. Only when the level was set on the constructor it was being set correctly.
No issues for the worker.ini
=> Apply openqa.ini log level correctly

dbicdh/PostgreSQL/deploy/60/001-auto-__VERSION.sql, dbicdh/PostgreSQL/deploy/60/001-auto.sql, dbicdh/PostgreSQL/upgrade/59-60/001-auto.sql, dbicdh/SQLite/deploy/60/001-auto-__VERSION.sql, dbicdh/SQLite/deploy/60/001-auto.sql, dbicdh/SQLite/upgrade/59-60/001-auto.sql, dbicdh/_source/deploy/60/001-auto-__VERSION.yml, dbicdh/_source/deploy/60/001-auto.yml, lib/OpenQA/Schema.pm, lib/OpenQA/Schema/Result/JobGroups.pm, lib/OpenQA/WebAPI/Controller/API/V1/JobGroup.pm, t/api/10-jobgroups.t, t/ui/14-dashboard-parents.t
see: https://progress.opensuse.org/issues/17846
feedback and advices please
=> Allow same group name within different parent groups

lib/OpenQA/Worker/Cache.pm, lib/OpenQA/Worker/Engines/isotovideo.pm, lib/OpenQA/Worker/Jobs.pm, t/full-stack.t
There are some activities that are better suited as info than as debug.
Such activities include: starting worker, worker downloading/uploading files
All of these information is usefull although we don't care most of the time.
It also addresses the bug in which we if we override the default verbosity level with MOJO_LOG_LEVEL, the fullstack.t test will fail, because the autoinst-log.tx file won't be created (as there is nothing to be written).
=> Not everything is debug information

lib/OpenQA/Schema/ResultSet/JobSettings.pm, lib/OpenQA/Schema/ResultSet/Jobs.pm, lib/OpenQA/WebAPI/Controller/API/V1/Job.pm, lib/OpenQA/Worker/Engines/isotovideo.pm, t/api/04-jobs.t
In order to allow better filtering and proper grouping of jobs when
they belong to an instance in another location, so that bridged
worker can query all the jobs available to be "proxied", without
extra need for more worker settings and redefinition of worker
classes. This allows to use :my_location:our_worker_class
Ends up being something like this: http://deimos.suse.de/api/v1/jobs.json?limit=100&worker_class=:provo:qemu_aarch64
=> Add support for colons on worker class

.gitignore, assets/javascripts/assets.js, dbicdh/PostgreSQL/deploy/61/001-auto-__VERSION.sql, dbicdh/PostgreSQL/deploy/61/001-auto.sql, dbicdh/PostgreSQL/upgrade/60-61/001-auto.sql, dbicdh/_source/deploy/61/001-auto-__VERSION.yml, dbicdh/_source/deploy/61/001-auto.yml, lib/OpenQA/Schema.pm, lib/OpenQA/Schema/Result/Assets.pm, lib/OpenQA/Schema/Result/JobGroups.pm, t/04-scheduler.t, t/14-grutasks.t, t/api/02-assets.t, t/api/10-jobgroups.t, t/ui/13-admin.t, templates/admin/asset/index.html.ep, templates/admin/group/group_property_editor.html.ep
Also contains now accumulating size of exclusively used assets per job group. It is currently only shown in the job group property editor beside next to the size limit setting.
=> Write info about assets kept during cleanup to db

Makefile, systemd/openqa-gru.service, systemd/openqa-resource-allocator.service, systemd/openqa-scheduler.service, systemd/openqa-setup-db.service, systemd/openqa-websockets.service, systemd/openqa-webui.service
and make the other service 'want' it. So if's there (packaged in an extra package)
it will start postgresql and add the database for openqa. This way all
the user has to do is: zypper in openQA (and tons of apache mocking)
Verification run: https://tortuga.suse.de/tests/15#live
Idea: @lnussel
=> Add openqa-setup-db service that will create postgresql database

lib/OpenQA/Schema/Result/Assets.pm
We did this for assets in job groups, but the assets not assigned were filling
the DB. This was especially troublesome with the TEMP files from upload laying
in the database for 14 days
=> Remove all assets from DB that are gone

lib/OpenQA/WebAPI/Controller/API/V1/JobGroup.pm, t/api/10-jobgroups.t
See: https://progress.opensuse.org/issues/29110
=> Fix job group update issue

cpanfile, lib/OpenQA/Setup.pm, lib/OpenQA/Utils.pm, t/24-worker.t, t/25-serverstartup.t, t/28-logging.t
This change will make sure that all the logs (except when logging to stdout/stderr) will respect
ISO8601 date format.
This is achieved by overriding the Mojo::Log format callback.
poo#29304
=> Change the logs timestamp to ISO8601

t/25-serverstartup.t
The variable MOJO_LOG_LEVEL can alter what's logged into the logs.
The variables OPENQA_WORKER_LOGDIR and OPENQA_LOGFILE, can change
where the information will be logged.
With this change, the tests will stop relying on the default
behaviour, set by these variables in the Makefile
=> Deal properly with environment variables that can change logging

docs/Networking.asciidoc
We answer questions about openqa setup for multimachine jobs too often, this is attempt to extract basic parts of documentation into simple how-to.
=> Add basic setup of multi-machine worker

lib/OpenQA/Schema/Result/Assets.pm, lib/OpenQA/WebAPI/Controller/API/V1/Asset.pm, t/14-grutasks.t, t/api/02-assets.t, t/ui/13-admin.t
See https://github.com/os-autoinst/openQA/pull/1551#issuecomment-353311600
Note: This changes the meaning of the DELETE route as it now actually deletes
the files on the file system. In don't think that this is a bad thing because
this way we can not forget to actually delete the file.
It also simplifies the GRU task code a little bit, because it
currently always removes the file from disk and then deletes the database
entry.
=> Remove assets from disk when deleting database entry

lib/OpenQA/WebAPI/Controller/Main.pm
So an invalid group results in a simple 404 error.
Previously a 500 error was possible and a database exception was logged:
```
[error] DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::Pg::st execute failed
```
=> Improve error handling in group overview

cpanfile
Which break our tests as well
I was wrong with https://github.com/os-autoinst/openQA/pull/1566#issuecomment-360817342 , it selected 1.12 instead of 1.20 (wanted) which resulted in skip of the UI tests (it's friday 🎉 )
This should also bring back codecov to normal as well
=> Apparently the only version available on cpan is 1.12

lib/OpenQA/Worker/Pool.pm
If the worker was started with --no-cleanup and the isotovideo died, leaving a qemu running in the background all the jobs would get errored and the worker would continue like everything is ok.
The verification for a running qemu was not being done if the --no-cleanup
was being used.
Before the changes: https://openqa.suse.de/tests/1389513/file/autoinst-log.txt
After the changes: 
When the worker starts doing the next job, it will check the qemu and the job will be cancelled, and the worker will die with the error:
> [error] QEMU (4109 -> /usr/bin/qemu-system-x86_64) should be dead - WASUP?
The same error will happen if the admin tries to start the worker again.
=> Check qemu pid before starting job

lib/OpenQA/WebAPI/Controller/Test.pm, templates/test/overview_result_table.html.ep
This fixes displaying the testsuite descriptions in the overview
page for configurations with '@' in the case the 'general config'
(without @) is not present as well.
I tested this manually, but I can also add a PhantomJS test if wanted.
=> Fix testsuite descriptions if default config not present

docs/Branding.asciidoc, docs/Contributing.asciidoc, docs/GettingStarted.asciidoc, docs/Installing.asciidoc, docs/Networking.asciidoc, docs/Pitfalls.asciidoc, docs/UsersGuide.asciidoc, docs/WritingTests.asciidoc
Some relative links didn't work in single HTML/PDF file
unless put asciidocs to the same directory, but it is
duplicate and is not a good behaviour to link asciidocs
which their content are already in the single HTML/PDF
document.
Using cross references to reach location within HTML/PDF
document as well as across asciidocs.
See: https://progress.opensuse.org/issues/19790
=> Fix broken links in openQA documents

assets/javascripts/assets.js, assets/stylesheets/openqa.scss, lib/OpenQA/Schema/Result/Assets.pm, lib/OpenQA/Schema/ResultSet/Assets.pm, lib/OpenQA/Utils.pm, lib/OpenQA/WebAPI/Controller/Admin/Asset.pm, t/14-grutasks.t, t/ui/13-admin.t, templates/admin/asset/index.html.ep
Instead of querying the groups one by one and decide what to delete, we
now collect all assets, sort them by how important they are overall and
then assign groups to them before deleting.
This allows to use the same infos also to display in the admin/assets
page and to apply the size limit exclusively. Finally it's possible to
explain what GRU deletes exactly as the web page displays the same
infos that GRU sees.
I dropped the 80% logic though - the admin will have to adjust the
job group sizes to match his file system anyway and can't have all
disk space eaten up by job groups to account for uploads and overcommits
due to pending jobs.
One additional change I did was take fixed/ assets into the calculcation
to give a better overview what is taking up the disk space, they won't
be deleted …
=> Big rework of the GRU limit_asset task

cpanfile, t/ui/18-tests-details.t
Selenium::Remote::Driver 1.23 fixed our issue, so take the latest version
1.21 introduced the regresion, so technically we forbid 1.21 and 1.22,
but testing with the latest sounds more reasonable - especially as Tumbleweed
is already at the broken 1.21 version
=> Take latest version of Selenium::Remote::Driver

cpanfile, lib/OpenQA/WebAPI.pm, lib/OpenQA/WebAPI/Controller/API/V1/Asset.pm, lib/OpenQA/WebAPI/Controller/API/V1/Bug.pm, lib/OpenQA/WebAPI/Controller/API/V1/Command.pm, lib/OpenQA/WebAPI/Controller/API/V1/Comment.pm, lib/OpenQA/WebAPI/Controller/API/V1/Feature.pm, lib/OpenQA/WebAPI/Controller/API/V1/Iso.pm, lib/OpenQA/WebAPI/Controller/API/V1/Job.pm, lib/OpenQA/WebAPI/Controller/API/V1/JobGroup.pm, lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm, lib/OpenQA/WebAPI/Controller/API/V1/Locks.pm, lib/OpenQA/WebAPI/Controller/API/V1/Mm.pm, lib/OpenQA/WebAPI/Controller/API/V1/Table.pm, lib/OpenQA/WebAPI/Controller/API/V1/Worker.pm, lib/OpenQA/WebAPI/Description.pm, t/27-errorpages.t, t/31-api_descriptions.t, t/testrules.yml
This PR adds the package OpenQA::WebAPI::Description which contains methods to be used on lib/OpenQA/WebAPI.pm to parse the Controller/API/V1 module files for POD documentation, and extract from there API descriptions to be shown in the GUI's help page.
In order to parse POD, the module Pod::POM was also added to the required modules for the project.
POD documentation was added to three API controller modules:
lib/OpenQA/WebAPI/Controller/API/V1/Feature.pm
lib/OpenQA/WebAPI/Controller/API/V1/JobGroup.pm
lib/OpenQA/WebAPI/Controller/API/V1/Worker.pm
lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
lib/OpenQA/WebAPI/Controller/API/V1/Locks.pm
Adding POD documentation to the remaining modules, should populate API descriptions in the help page automatically.
=> WebAPI: Add API description from Controller's POD

lib/OpenQA/WebSockets/Server.pm, lib/OpenQA/Worker.pm, lib/OpenQA/Worker/Commands.pm, lib/OpenQA/Worker/Common.pm, lib/OpenQA/Worker/Engines/isotovideo.pm, t/20-workers-ws.t, t/24-worker.t, t/27-websockets.t, t/full-stack.t, templates/admin/workers/index.html.ep
If the worker have a lower version than the minimal version required by the
server the worker will disconnect and shutdown.
The worker's status message, now contains an extra parameter: The current
worker version.
This version is then updated in the database by the openqa server, and displayed
in the workers list.
Both versions (worker version, and the minimal required version) are
just a simple number and the version comparison number is just a simple
"different than" (!=).
Related: poo#7086, poo#26890, poo#10474
=> Add worker version check on the server.

lib/OpenQA/Parser/Format/JUnit.pm, lib/OpenQA/Parser/Format/XUnit.pm
Not needed while in openQA, but otherwise makes parser fail loading
when using it separately.
```perl
use lib '/usr/share/openqa/lib';
use OpenQA::Parser qw(parser);
my $file = "slenkins_control-junit-results.xml";
my $data = parser( JUnit => $file );
use Data::Dumper;
print Dumper($data->results);
```
=> Add use Mojo::DOM in JUnit and XUnit Parser

cpanfile, lib/OpenQA/Worker/Engines/isotovideo.pm, lib/OpenQA/Worker/Jobs.pm, systemd/openqa-worker@.service, t/10-jobs.t
This change will compare the exit code and if it's not a clean exit the worker will die, so the systemd can collect all the grandchildren.
Please be aware that this change makes systemd as a dependency.
=> Force a restart when the children or grandchildren processes die

cpanfile, lib/OpenQA/Scheduler/Scheduler.pm, lib/OpenQA/Schema/Result/JobGroups.pm, lib/OpenQA/WebAPI/Controller/API/V1/Mm.pm, lib/OpenQA/WebAPI/Controller/API/V1/Table.pm, lib/OpenQA/WebAPI/Controller/Admin/Workers.pm, lib/OpenQA/Worker/Common.pm, lib/OpenQA/Worker/Engines/isotovideo.pm, lib/OpenQA/Worker/Jobs.pm, t/10-jobs.t, t/24-worker.t, t/fixtures/01-jobs.pl
This is still a wip, and commit message will be replaced :) - needs also new RWP release as sessions were introduced recently - and there was a typo preventing orphaned child resolution during event firing when using subreapers, not in the feature itself (and update cpanfile accordingly once its done).
=> Don't fear the (sub)reaper

assets/stylesheets/overview.scss
Disabled wrapping looks nice, but can hide bug icons.
=> Enable wrapping cells in overview table

lib/OpenQA/WebAPI/Controller/API/V1/Iso.pm, lib/OpenQA/WebAPI/Plugin/Fedmsg.pm, t/18-fedmsg.t
We currently don't actually emit any openqa_job_create events
when posting an ISO - only a batch openqa_iso_create event. It
is easy to also emit an openqa_job_create event for each of the
newly-created jobs, so let's do that.
=> Emit openqa_job_create events when an ISO is posted

docs/WritingTests.asciidoc
https://progress.opensuse.org/issues/31777
=> Expand the serial terminal console documentation

lib/OpenQA/Scheduler.pm, lib/OpenQA/Scheduler/Scheduler.pm, t/05-scheduler-full.t, t/10-jobs.t
This PR is addressing the race condition in _prefer_parallel.
~~To guarantee the cluster execution in one scheduling round it is also introducing a new variable ```PARALLEL_CLUSTER``` - when this is defined in the job settings, it will ensure the job to be assigned ONLY if the child/parents are going in the same scheduling round.~~ will be default
This has been already tested ( and still deployed ) on staging: http://e122.suse.de/tests
See related progress issue: https://progress.opensuse.org/issues/25892
Created https://progress.opensuse.org/issues/32725 for refactoring, since now that area calls for it
=> Ensure parallel jobs get assigned in one round

lib/OpenQA/Scheduler.pm
Thanks to @ldevulder for noticing this
See: https://github.com/os-autoinst/openQA/pull/1592#discussion_r172836272
=> Fix scheduler comment - now default MAX_JOB_ALLOCATION is 80

.travis.yml, lib/OpenQA/WebAPI/Controller/Step.pm
related poo#17706
The validation didn't allowed to save a needle for an OS
with a dot (.) in the name (for example: Opensuse leap 42.3)
if the VERSION was set.
This new change in the validation allows for 1 dot, but not consecutive
dots.
The version is only used to find the location in the FS to save the
needle.
=> Allow saving needles for OS with dots in the version

lib/OpenQA/Client.pm, lib/OpenQA/Client/Archive.pm, lib/OpenQA/Schema/Result/Jobs.pm, lib/OpenQA/UserAgent.pm, lib/OpenQA/Utils.pm, lib/OpenQA/WebAPI/Controller/Test.pm, script/client, t/31-client.t, t/api/04-jobs.t
This is meant to add support for the openQA::Client to support download of all the assets and generated data from a job. 
In theory this is another stepping stone for the worker_bridge/federation
https://progress.opensuse.org/issues/14580
=> Allow download of a full job data from the client

dbicdh/PostgreSQL/deploy/63/001-auto-__VERSION.sql, dbicdh/PostgreSQL/deploy/63/001-auto.sql, dbicdh/PostgreSQL/upgrade/62-63/001-auto.sql, dbicdh/_source/deploy/63/001-auto-__VERSION.yml, dbicdh/_source/deploy/63/001-auto.yml, docs/Pitfalls.asciidoc, lib/OpenQA/Schema.pm, lib/OpenQA/Schema/Result/NeedleDirs.pm, lib/OpenQA/Schema/Result/Needles.pm, lib/OpenQA/Schema/ResultSet/Needles.pm, lib/OpenQA/WebAPI/Controller/Admin/Needle.pm, lib/OpenQA/WebAPI/Controller/Step.pm, t/ui/12-needle-edit.t, templates/step/edit.html.ep
See https://progress.opensuse.org/issues/9906
---
<s>The PR is still WIP:</s>
=> Show added/updated needles in editor

docs/WritingTests.asciidoc
Improvement on openqa Documentation with examples on how to make the tests
yield a soft or a hard exception according to the pattern in
the serial console.
=> Capture serial patterns documentation

lib/OpenQA/Schema/ResultSet/Assets.pm, templates/admin/asset/index.html.ep
Since this link would not work without job group ID
=> Don't show configure button for untracked assets

lib/OpenQA/Scheduler/Scheduler.pm, t/10-jobs.t
This would not make the scheduler behave exactly as proposed in
https://progress.opensuse.org/issues/25892, but should avoid cluster
jobs to get stuck.
When there are not enough workers available, it would still not allocate the whole cluster, but if some part of it is already running,  it will start allocate them as long as there is capacity (without going 'stuck')
Seems to work here but needs still tests, changes are deployed in staging (e212).
=> Consider running jobs in filter_jobs

cpanfile, lib/OpenQA/Worker/Engines/isotovideo.pm, systemd/openqa-worker@.service
See related Progress issue: https://progress.opensuse.org/issues/33037
Test run: http://e122.suse.de/tests/15282
Another test run : http://e122.suse.de/tests/15284 - in the [worker log](http://e122.suse.de/tests/15284/file/worker-log.txt) you can see 'Registered process' at the end, which is the event emitted by the session manager when there are processes left in the cgroup.
(Here isotovideo crashed with similar [coredumps](http://e122.suse.de/tests/15284/file/autoinst-log.txt) seen in the poo, but the machine didn't left any qemu process behind )
Requires new RWP in obs and in the openQA specfile.
=> Start isotovideo and control it with cgroups

lib/OpenQA/Utils.pm
The status file that is created when an exception is launched isn't
immediatly available and the display of the details page doesn't
take that into consideration, creating a race condition when someone
is following the test in the live tab, and then suddenly the test
have a hard failure.
The race condition is created, because the web interface will change
immediatly to the details page, and the exception information might
not be available.
This creates an exception and the interface is redirected to the
exception.html.ep template.
=> Checks if failure status file exists before trying to slurp it

t/full-stack.t
In this case the isotovideo version can be detected also when
the isotovideo parameter is missing.
The use-case is running the full stack test locally where isotovideo
is likely installed via os-autoinst package.
=> Fix fullstack test in case /usr/bin/isotovideo is present

lib/OpenQA/Schema/Result/Needles.pm, lib/OpenQA/Schema/ResultSet/Needles.pm, lib/OpenQA/Utils.pm, lib/OpenQA/WebAPI/Controller/Step.pm, t/ui/12-needle-edit.t
See https://progress.opensuse.org/issues/33856
Tested locally, I can add a test case test later.
Note: The diff looks huge due to the indentation. The only new thing is the check `if (@$tags)`.
=> Fix showing needle editor when no tags present AND massive refactoring

lib/OpenQA/WebAPI/Controller/Step.pm
The selection was broken during the last refactoring.
I can also add a test case later.
=> Fix 'Take image from' selection in needle editor

lib/OpenQA/WebAPI/Controller/Step.pm, t/ui/18-tests-details.t, templates/step/viewimg.html.ep
It currently looks like this: ![candidates grouped by tags](https://user-images.githubusercontent.com/10248953/37907892-b2ff44ec-3106-11e8-9caf-d7b25a25efe5.png)
I haven't implemented/adjusted tests so far, but I'll do as soon as I have feedback.
See https://progress.opensuse.org/issues/15030
=> Group candidate needles by tag

lib/OpenQA/Worker/Jobs.pm
* See https://progress.opensuse.org/issues/13524
* Only one half of the implementation. The other half is done
in os-autoinst (see https://github.com/os-autoinst/os-autoinst/pull/941).
---
<s>When canceling a job locally it actually works. But it can't be that easy :-)  
So let's see what tests this breaks on travis.</s>
Ok, the previous approach wasn't really working. The module must have just finished regularly when I canceled.
=> Update current test module details when cancelling running job

t/05-scheduler-dependencies.t
This change deals with some test failures that happens from time to time in the tests.
We're sorting the results because is_deeply needs the elements to be with the same order ais_deeply needs the elements to be with the same order
=> Enforce sorting the results returned by the sql query to use in is_deeply

assets/assetpack.def, assets/javascripts/needlediff.js, assets/javascripts/test_result.js, assets/stylesheets/openqa.scss, assets/stylesheets/result_preview.scss, lib/OpenQA/WebAPI/Controller/Step.pm, t/ui/18-tests-details.t, templates/step/viewimg.html.ep
* Still WIP. Missing:
* Select 'None' again
* Actually implement 'Full diff'
* Show whether needle is excluded
* Fix tests
* Built on top of https://github.com/os-autoinst/openQA/pull/1619#issuecomment-380857309.
* Can be tested on e212, eg. http://e212.suse.de/tests/11171#step/disable_grub_timeout/6.
* Main point is that the combo box content is now fully customizable.
=> Customize selection for candidate needles + full diff view

lib/OpenQA/Schema/Result/Jobs.pm, t/05-scheduler-dependencies.t
This change will avoid skipping **relationships** when cloning jobs.
=> Avoid skipping relationships when cloning jobs.

profiles/apparmor.d/usr.share.openqa.script.openqa
Without it openQA fails in `use Archive::Extract;` which apparently probes for `/usr/bin/unzip-plain`.
=> Add unzip-plain to AppArmor profile

lib/OpenQA/WebAPI.pm, script/generate-packed-assets
This should avoid to run the openQA application for generating cache assets. Deployed [Staging](http://e122.suse.de/) with https://build.opensuse.org/package/show/home:EDiGiacinto:branches:devel:openQA/openQA , no issue noticed so far
=> Do not load full application to generate assetpack data

assets/stylesheets/overview.scss, templates/main/group_builds.html.ep
The smaller font doesn't really make a difference, but the dotted line looks better in chromium - firefox doesn't seem to have this problem.
Before:
After:
=> Use a smaller font for the 'ago time' to fix chromium rendering

lib/OpenQA/WebAPI/Controller/API/V1/Iso.pm, lib/OpenQA/WebAPI/Plugin/Gru.pm, t/14-grutasks.t
With this change, while enqueueing GRU tasks it can be supplied a ttl option to specify the task expiration time.
This is also setting the limit of 2 days for limit_assets and limit_results_and_logs since they can be accumulated pretty easily with subsequent iso posts.
[Staging tests](http://e122.suse.de/minion/jobs?state=failed)
See: https://progress.opensuse.org/issues/23318
=> Limit gru tasks

lib/OpenQA/Parser/Format/JUnit.pm, lib/OpenQA/Parser/Format/LTP.pm, lib/OpenQA/Parser/Format/XUnit.pm
If an element of text details points to a file with dots, the webapi will get confused and will not load the text.
[With dot](http://phobos.suse.de/tests/11062#step/LTP_net_stress.interface_if4-addr-change_ifconfig/1) vs [Without dot](http://phobos.suse.de/tests/11063#step/LTP_net_stress_interface_if4-addr-change_ifconfig/1)
=> Replace extra dots in the filenames

lib/OpenQA/Parser/Format/JUnit.pm, lib/OpenQA/Utils.pm, lib/OpenQA/Worker/Jobs.pm, t/10-jobs.t
When the worker is invoked with --nocleanup, it will append previus runs
making it a bit difficult to debug or read the logs, ensure this doesn't
happen anymore, but keep other result files.
=> Avoid appening multile runs with --nocleanup

lib/OpenQA/Parser/Result/OpenQA.pm, t/30-test_parser.t
Overload constructor and do apply the custom _source field to all parser formats details using Result::OpenQA
I'm testing this on staging, but should not have any regression, this should help https://github.com/os-autoinst/openQA/pull/1639 to figure out which details were generated by the parser
=> Add _source field to every detail generated by parsers implementations

assets/stylesheets/overall.scss, templates/layouts/bootstrap.html.ep, templates/layouts/navbar.html.ep
This makes better usage of the screen space, but can look displaced on
very wide screens. But especially in /tests and /tests/X it looks better
IMO
Before:
After:
=> Make the layout use 100% width (aka 'fluid')

assets/javascripts/openqa.js, templates/main/group_builds.html.ep, templates/main/index.html.ep, templates/main/parent_group_overview.html.ep
Instead of using fixed size grid columns, we use flexible columns and
set the width to the largest build column using javascript (possibly there
is a css way, but I don't know of any)
See https://progress.opensuse.org/issues/35697
=> All your badge are belong to us!

lib/OpenQA/Utils.pm, lib/OpenQA/WebAPI.pm, lib/OpenQA/WebAPI/Controller/API/V1/Job.pm, lib/OpenQA/WebAPI/Controller/Test.pm, script/client, t/api/04-jobs.t
See https://progress.opensuse.org/issues/33892
---
It would work like this:
```
openqa-client jobs/overview build=589.1 distri=sle version=15 groupid=123
[
{
id => 28,
name => "sle-15-Installer-DVD-x86_64-Build589.1-create_hdd_minimal_base+sdk\@64bit",
},
{
id => 27,
name => "sle-15-Installer-DVD-x86_64-Build589.1-install_ltp+sle+15+Installer-DVD\@64bit",
},
]
openqa-client jobs/overview/restart build=589.1 distri=sle version=15 groupid=123
[
{
id => 28,
name => "sle-15-Installer-DVD-x86_64-Build589.1-create_hdd_minimal_base+sdk\@64bit",
},
{
id => 27,
name => "sle-15-Installer-DVD-x86_64-Build589.1-install_ltp+sle+15+Installer-DVD\@64bit",
},
]
http://localhost:9526/api/v1/jobs/restart?jobs=28&jobs=27
{ result => [37], test_url => ["/tests/37"] }
```
That should already cover AC1:
> AC1: …
=> Allow client to restart a build for a jobgroup

t/22-dashboard.t
Here https://www.suse.com redirects to https://www.suse.com/de-de
causing the test to fail.
So just exclude external links when checking for dead links.
Note that the only other external link we have on the page is
currently http://open.qa/.
=> Exclude external links in 22-dashboard.t

docs/Networking.asciidoc
The commit updates current Networking documentation with the
up-to-date step-by-step guide on how to configure openQA
and host machine to run multimachine tests.
Related ticket: [poo#20674](https://progress.opensuse.org/issues/20674)
Passed multi-machine tests, that were set up with the updated steps: [autoyast_lvm](http://10.160.67.126/tests/6) & [autoyast-supportserver](http://10.160.67.126/tests/5)
=> Update documentation for multimachine tests setup

etc/nginx/vhosts.d/openqa.conf
I use this config on my local development instance.
What works right now:
- Navigation in the webui (Login, overview page and so on)
- Register remote worker
- Cloning jobs
What does not work yet:
- ~Cloning jobs~
My instance can be seen here: http://openqa.glados.qa.suse.de
=> Add basic http-only config for nginx

docs/UsersGuide.asciidoc, lib/OpenQA/WebAPI/Controller/API/V1/Iso.pm, t/api/02-iso.t, t/fixtures/04-products.pl
See https://progress.opensuse.org/issues/33892
AC1 is tested and works. Job templates *not* matching the given group ID are ignored when creating new jobs via `POST isos`.
Not sure about AC2. Does "Builds that were triggered in the normal way" mean "jobs that were spawned before, but without explicit group filtering"? If yes, that wouldn't be completely trivial to implement because we would need to save whether the group filtering was used when spawning a job.
Also not sure about AC3. For me it sounds like I don't have to do anything further here. This PR just introduces a filter. The usual behavior for obsoletion isn't changed - just limited to the specified group.
=> Add _GROUP filter to isos post

docs/WritingTests.asciidoc, lib/OpenQA/Schema.pm, lib/OpenQA/Schema/Result/Jobs.pm, lib/OpenQA/Setup.pm, lib/OpenQA/WebAPI/Controller/API/V1/Job.pm, t/04-scheduler.t, t/05-scheduler-dependencies.t, t/05-scheduler-restart-and-duplicate.t, t/09-job_clone.t, t/20-workers-ws.t, t/fixtures/01-jobs.pl
Related issues:
https://progress.opensuse.org/issues/34504
https://progress.opensuse.org/issues/35914
https://progress.opensuse.org/issues/30361
I removed the recursive nature of duplicate, which now that I looked into it was very dangerous as the DB transactions happened per job within that recursion, but there was no global rollback - but dependencies were already added partly.
I also removed some - let's say - optimizations that reused scheduled jobs for the new cluster jobs, which lead to unclear dependencies of the chain (*especially* if partly jobs failed to duplicate).
I also revisted one decision that makes restarting multimachine jobs very hard in practise: done parents were excluded from restarting. I don't know what use case lead to that decision, but in our daily practise we …
=> Refactor jobs::duplicate 

assets/javascripts/job_next_previous.js, lib/OpenQA/Schema/ResultSet/Jobs.pm, lib/OpenQA/WebAPI/Controller/Test.pm, t/ui/16-tests_job_next_previous.t, templates/test/job_next_previous.html.ep
Set default to 400 previous jobs and 100 next jobs.
For more or less previous & next jobs query, use link with query parameters like following example:
/tests/99945?previous_limit=10&next_limit=10#next_previous
=> Remove limit option in next&previous tab UI

t/16-utils-runcmd.t
A git error message that 16-utils-runcmd.t expects to run into
has had its case changed in upstream git - formerly it was "Not
a git repository...", now it's "not a git repository...". This
was changed in fc045fe , "Mark messages for translations"; the
discussion on the upstream git mailing list indicates this is
to stay in line with a general policy on error messages for the
git project. As we're fairly likely to want this test to pass
with versions of git both before and after the change, let's
accept either form.
=> runcmd tests: handle differently-cased git error message

.travis.yml, Makefile
This PR solves the SCHEDULER_FULLSTACK typo, and fixes the test false positives.
Unfortunately propagating the exit code doesn't work all the times as shown in test, https://travis-ci.org/dasantiago/openQA/jobs/385108697#L881
So we are checking all the ways perl or prove can exit with error:
1. [not ok](https://travis-ci.org/dasantiago/openQA/jobs/385108697)
2. [Result: FAIL](https://travis-ci.org/foursixnine/openQA/jobs/389227774#L2067) 
3. [Looks like you failed](https://travis-ci.org/foursixnine/openQA/jobs/389227774#L1714)
=> Typo in travis and improvement of the Makefile

lib/OpenQA/Utils.pm
Allow UEFI firmware code and variable images to be stored in the HDD
folder. They are block devices the same as the other contents of the HDD
folder.
This is related to: https://github.com/os-autoinst/os-autoinst/pull/942
Without this change absolute paths need to be given for the UEFI_PFLASH_CODE and UEFI_PFLASH_VARS variables. The variables could be put in a different folder if necessary.
=> Categorize UEFI PFLASH drives as HDD assets

docs/Networking.asciidoc
We ship openSUSE with firewalld now, so we include instructions how to
configure NAT with firewalld too.
=> Update documentation with NAT configuration using firewalld

systemd/tmpfiles-openqa.conf
With caching enabled worker still requires /var/lib/openqa/share
- https://progress.opensuse.org/issues/32632
=> Let tmpfiles.d create the mount point "share"

assets/javascripts/running.js, assets/javascripts/test_result.js, lib/OpenQA/Schema/Result/Jobs.pm, templates/test/infopanel.html.ep, templates/test/result.html.ep
Since waiting state is deprecated, and isotovideo now is able to
report the state of the test via /status, running_or_waiting is now
useless, so remove it
=> Wipe out waiting state

assets/stylesheets/test-details.scss
See https://progress.opensuse.org/issues/37519
The problem is that the parser output contains too long, unbreakable lines.
Looks good when using `min-width: fit-content` which currently requires vendor prefixes for Firefox and WebKit-based browsers:  
Not sure how to fix this otherwise without JavaScript or even some server-side adjustments. Note that this won't work with IE, but I don't think we care.
=> Fix wrapping of parser results

t/full-stack.t
Since we're only polling for the status it can be easily missed so the job already be assigned on this check.
=> Allow 'assigned' state in fullstack.t

t/full-stack.t, t/lib/OpenQA/Test/FullstackUtils.pm
* Decrease the polling interval so it is less likely to miss the scheduled state.
* Skip test for cancelling a scheduled job when the job is already assigned.
---
Follow-up of https://github.com/os-autoinst/openQA/pull/1699
=> Make full-stack test more stable

docs/Contributing.asciidoc
Maybe there's a more secure way, but this works at least.
=> Document running UI tests with Docker in non-headless mode 

assets/stylesheets/dashboard.scss
This prevents the text to overlap:
* Before:  
* After:
=> Adjust overflow behavior of dashboard progress bars

assets/javascripts/needleeditor.js
This should not affect the behavior.
However, it hopefully makes the test 12-needle-edit.t more stable to prevent wrong failures like `not ok 10 - new needle image shown`.
Note that this issue is hard to reproduce, so I'm not sure whether this change will help (we will have to try out).
=> needle editor: Assign new background image instantly

assets/javascripts/running.js, t/ui/25-developer_mode.t
Because pausing at a module which is currently running or has already been completed isn't possible anyways.
(I think this was also mentioned in the review by @foursixnine and I postponed it because the PR was so big already.)
=> developer mode: Show only modules which are still ahead

script/clone_job.pl
See https://progress.opensuse.org/issues/38279
---
Tested locally with production data and job mentioned in the ticket.
=> clone_job: Make _GROUP and _GROUP_ID override each other

lib/OpenQA/LiveHandler.pm, lib/OpenQA/WebAPI/Controller/LiveViewHandler.pm, t/34-developer_mode-unit.t, t/full-stack.t
* Use constant for allowed os-autoinst commands
(the hash won't be const, only the reference to it)
* Use attributes on application-scope to store web socket
transactions
=> Prevent use of global variables in LiveViewHandler.pm

assets/javascripts/openqa.js, etc/apache2/vhosts.d/openqa-ssl.conf.template
<s>Not working yet because Apache doesn't proxy wss so far.</s> Apparently it is actually working for me locally. Tested Apache reverse proxy without SSL, Apache reverse proxy with SSL and accessing the Mojo servers directly.
I'll enable SSL on e212 and deploy. Let's see whether it works there, too.
=> Use wss protocol for websocket connection when page loaded via https

lib/OpenQA/Worker/Engines/isotovideo.pm, t/24-worker-engine.t, t/testrules.yml
Allow the worker cache code to download the PFLASH by treating them as
an hdd
=> Add UEFI_PFLASH_VARS to detect_asset_keys

lib/OpenQA/Worker/Cache.pm, t/full-stack.t
We need the UEFI_PFLASH_VARS to be treated as non critical, to avoid tests failing only because they are not able to be downloaded, regardless of wether the tests will use them or not. 
So let it hard fail instead if the asset is not downloaded, and the test uses it. 
As a bonus, allow full paths to be used as a valid asset, this will search for said file in the worker after failing to download it from the webui.
=> Treat UEFI_PFLASH_VARS as non critical asset

.travis.yml, script/docker-tests
Maybe useful to debug failing fullstack tests. Let's see whether it works.
=> Print autoinst-log.txt after Travis testrun

lib/OpenQA/Schema/Result/Jobs.pm, lib/OpenQA/WebAPI/Controller/Developer.pm, lib/OpenQA/Worker/Jobs.pm, t/34-developer_mode-unit.t
* Allows the proxy for developer mode to connect
also when the worker's hostname in the database
is not fully qualified.
* See https://progress.opensuse.org/issues/39119
=> Pass worker setting WORKER_HOSTNAME to web UI

docs/WritingTests.asciidoc, lib/OpenQA/Schema/Result/Jobs.pm, t/17-labels_carry_over.t
Follows [PR#998](https://github.com/os-autoinst/os-autoinst/pull/998) in os-autoinst (not yet merged).
Our use case is that we have kernel bug, which fails different modules,
depending on our luck. Therefore, automatic comment carryover won't help
to the reviewers and they have to do monkey job to label them.
With this change, if failure reason will be marked with bug reference,
it will be treated as a reason of test suite failure. Therefore, if same
failure is thrown in multiple runs, irregardless the module where it was
detected, last comment will be taken over.
See [poo#36448](https://progress.opensuse.org/issues/36448).
[Verification run](http://g226.suse.de/tests/2176#next_previous). Here you can see that test failed in 2 different modules, but comment from the first one was added to …
=> Carry comment over if test suite failed with same serial failure

assets/javascripts/openqa.js, assets/javascripts/running.js, t/lib/OpenQA/SeleniumTest.pm, t/ui/14-dashboard-parents.t, t/ui/18-tests-details.t, t/ui/25-developer_mode.t, templates/test/result.html.ep
Because errors regarding the developer mode are currently completely hidden from the user and the page looks like it is just stuck in "retrieving status" (see https://progress.opensuse.org/issues/38447).
It basically works, but still requires a little bit tuning to avoid spamming the user with too many error messages. It would likely be the best if an error occurs again, only a counter is increased rather than adding another message.
=> developer mode: Show flash messages on errors

openQA.spec
- Ticket: https://progress.opensuse.org/issues/39032
- Build verification: https://build.opensuse.org/package/show/home:SLindoMansilla:branches:devel:openQA/openQA
- Verification run: (coming soon)
=> Require at least IO Socket SSL 2.009

templates/test/list.html.ep
Otherwise we get 'Experimental keys on scalar is now forbidden at
template test/list.html.ep line 21.'
=> Fix usage of $blocked in test results template

lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
With Mojo 7.88 Subprocesses are started not immediately anymore, but
inside the IOLoop, a bit later. To avoid transaction to vanish since it's weakened,
explictly force it
=> Upload: Keep the transaction around

Makefile
Hard to debug in travis :( but on fork/PR this doesn't seem to happen, only on upstream/master for me
=> Makefile: Avoid also to parse env with spaces to travis

cpanfile, openQA.spec
The Mojolicious releases between 7.82 and 7.92 were unfortunately very unstable and would cause openQA to fail randomly. https://github.com/kraih/mojo/commit/61f6cbf22c7bf8eb4787bd1014d91ee2416c73e7
=> Fix Mojolicious version requirement

t/33-developer_mode.t, t/full-stack.t
change in os-autoinst: https://github.com/os-autoinst/os-autoinst/pull/993/commits/67e21e3e732104a1652dc71e767632e5858985de
---
Note that I haven't tested this because the condition where 2nd pattern is required is hard to hit. (The 2nd pattern is supposed to match if a disconnect occurs and the client is therefore disconnected in the moment where the pause is propagated.)
=> Adapt fullstack tests to changes in os-autoinst

assets/javascripts/needleeditor.js, assets/javascripts/running.js, assets/stylesheets/overview.scss, assets/stylesheets/test-details.scss, lib/OpenQA/WebAPI/Controller/LiveViewHandler.pm, lib/OpenQA/WebAPI/Controller/Running.pm, lib/OpenQA/WebAPI/Controller/Step.pm, lib/OpenQA/WebAPI/Plugin/Helpers.pm, lib/OpenQA/Worker/Jobs.pm, t/26-controllerrunning.t, t/33-developer_mode.t, t/lib/OpenQA/Test/FullstackUtils.pm, t/ui/12-needle-edit.t, t/ui/25-developer_mode.t, templates/main/specific_not_found.html.ep, templates/test/live.html.ep
* based on https://github.com/os-autoinst/openQA/pull/1724
* requires https://github.com/os-autoinst/os-autoinst/pull/993
---
=> Add UI for pausing on assert screen timeout

lib/OpenQA/Utils.pm, lib/OpenQA/WebAPI/Controller/Step.pm
Git commits were failing if the needle directory wasn't the root of the git repository. However, there's no reason to require that and `git` can reliably walk up the tree to figure out the repository structure.
=> Allow needle commits in git repo subdirectory

lib/OpenQA/Schema/Result/Comments.pm
Otherwise unicode characters are not handled correctly.
=> Avoid using Mojo::ByteStream directly when rendering JSON

assets/javascripts/openqa.js, assets/javascripts/running.js, assets/javascripts/scheduler.js, t/lib/OpenQA/Test/FullstackUtils.pm
Because on page reload elements found via `find_element()` are invalidated
which is hard to handle and otherwise causes random failures.
=> fullstack test: Prevent auto page reload when waiting for result panel

script/tidy
Allow to use `script/tidy --assume-already-tidy` to only look at changes files because perltidy is just horribly slow.
=> Make tidy fast by only looking at changed files

etc/openqa/openqa.ini, lib/OpenQA/Setup.pm, lib/OpenQA/WebAPI.pm, t/config.t
Btw, it looks like this:
I made it only available to operators/admins, so you can enable it on the production instance.
=> Allow to enable monitoring using mojo-status

lib/OpenQA/Schema/Result/Jobs.pm, lib/OpenQA/WebAPI/Controller/Test.pm, t/05-scheduler-dependencies.t
blocked_by means: either one job in the parallel cluster or
a parent of a chained parent is not final. So looking at
chained_children of the cluster gives us possibly a cycle
As such don't look at the full cluster's chained deps, but
only of those pointing up
=> Fixed blocked_by calculation not to create loops

docs/WritingTests.asciidoc
Changes to reflect changes introduced in [PR#1014](https://github.com/os-autoinst/os-autoinst/pull/1014) to os-autoinst, describing `fatal` type.
=> Update serial failures detection documentation

lib/OpenQA/WebAPI/Plugin/Fedmsg.pm, t/18-fedmsg.t
There is a Red Hat-ish universe standard being established for
'CI'-ish message bus messages, the idea being that if many
different test systems emit messages in a common format, it
makes things much easier for other systems trying to follow
what all the test systems are doing. This makes the openQA
fedmsg plugin emit messages in this standardized format (at
least, in an initial approximation of it, with as-yet unapproved
extensions...) as well as the existing messages.
https://pagure.io/fedora-ci/messages
=> Fedmsg plugin: emit 'standardized' fedmsg

lib/OpenQA/WebAPI/Controller/Test.pm
Because sorting in Perl is usually slower
=> Sort scheduled jobs via database

templates/main/group_builds.html.ep
Break the progress bars below the title on medium size screens (<992px)
See https://progress.opensuse.org/issues/39896
=> Make the overview page responsive again

lib/OpenQA/Schema/Result/Jobs.pm, t/04-scheduler.t, t/api/02-iso.t
If a cluster depends on 2 independent parents, we need to make
sure to sort this out before looking at the cluster as a whole.
The situation is basically:
```
+------------+      +----------------+
|  Upgrade   |      |   Node 1       |
|  Node1     +------>                +---+------------------+
+------------+      +----------------+   | Supportserver    |
|   |                  |
+------------+      +--------------------+------------------+
| Upgrade    |      |   Node 2       |
| Node 2     +------>                |
+------------+      +----------------+
```
And if you look at the cluster triggered by 'Upgrade Node1' you
might end up believing the whole cluster depends on 'Upgrade Node2',
while (of course) the Upgrades happen unblocked in parallel.
The cluster itself is blocked by …
=> Fix one more corner case for blocked_by

lib/OpenQA/Schema/Result/Assets.pm, lib/OpenQA/Schema/ResultSet/Assets.pm, lib/OpenQA/Task/Asset/Limit.pm, lib/OpenQA/WebAPI/Controller/Admin/Asset.pm, t/14-grutasks.t, t/37-limit_assets.t, t/ui/13-admin.t, templates/admin/asset/index.html.ep
See https://progress.opensuse.org/issues/35389
---
* Do sorting in database
* Don't stat if filesize is already known  
FIXME: take casre limit_assets still works as before
* Reduce misc inefficiency in code
Performance improvement (tested with OSD data locally for serving data as JSON):
* before: 42 seconds
* after:  15 seconds
=> Optimize query for asset table (first step improve performance)

lib/OpenQA/Utils.pm, lib/OpenQA/WebSockets/Server.pm, script/openqa-livehandler, script/openqa-websockets
This ensures the daemons listen on IPv4 and if available also on IPv6.
=> Make web socket and livehandler daemons listen on IPv4 and IPv6

cpanfile, lib/OpenQA/WebAPI/Plugin/AMQP.pm, openQA.spec, t/23-amqp.t
Instead of keeping an AMQP connection alive all the time (and risk losing it
on subprocess forks), just create a Publisher on events and fire it
See  https://progress.opensuse.org/issues/40652
=> Make amqp less fragile

lib/OpenQA/Schema/Result/Jobs.pm
This 'hides' it from postgresql error logs - which otherwise fill up
with things we handle just fine (and hide other, real errors)
See https://progress.opensuse.org/issues/34525
=> Run inserting screenshots in a transaction

lib/OpenQA/Task/Asset/Limit.pm
This is probably the most stupid bug ever - we basically only deleted untracked
assets by chance. delta_ms returns a Duration object - and that Duration object's
in_units only supports certain conversions. If the conversion is not supported,
0 is returned. So all these assets had basically all the time an age of 0
Using delta_days returns just that: the age in days and we happily remove them
=> Fix removal of untracked assets

lib/OpenQA/Schema/Result/JobGroups.pm, lib/OpenQA/Task/Job/Limit.pm
So far we only removed old jobs of job groups - jobs that were posted
through the jobs controller or moved to group 0 afterwards weren't
taken care of.
As we have a default setting for result removal, use it to remove
jobs without group.
See https://progress.opensuse.org/issues/41174
=> Limit logs and results for groupless jobs

docs/Installing.asciidoc
Current version of installation documentation mention that for development repo  you need to install  devel-openQA:openQA which is not true
=> doc: remove mention of openQA-devel package

lib/OpenQA/WebAPI/Controller/Admin/Needle.pm
* See https://progress.opensuse.org/issues/41399
* Bug was introduced in 2a50aa7c9f42e72bd95f89378fcb5c745f76a22f
=> Fix 'last_match' param of AJAX route for needle table

profiles/apparmor.d/usr.share.openqa.script.worker
Hit the following errors on openqaworker1 on o3
the rk for /usr/share/qemu is needed to handle qemu-img properly on Leap 15
the changes for /sys are to based on a broad amount of apparmor blocks detected in those paths.
=> Update AppArmor profile for Leap 15.0

lib/OpenQA/Schema/ResultSet/Assets.pm, lib/OpenQA/Task/Asset/Limit.pm
See https://progress.opensuse.org/issues/41483#note-17 - the webui
schedules assets while GRU tries to calculate if the asset should
be removed. And in between 2 queries the situation changes - causing
an early removal
=> Fix removal of scheduling assets

openQA.spec
See
* https://progress.opensuse.org/issues/40898
* https://progress.opensuse.org/issues/38351
I executed `grep 'use ' $(rpm -ql openQA-client)` and added all modules we're using. I excluded those which are provided by an already existing `Requires`, `perl-base` or `perl`.
=> Fix openQA-client package for openSUSE

lib/OpenQA/Schema/Result/Users.pm
Related progress issue: https://progress.opensuse.org/issues/30124
=> Use less-ugly gravatar icons already used in OBS and progress

lib/OpenQA/Worker/Engines/isotovideo.pm
Related progress issue: https://progress.opensuse.org/issues/42329
=> Fix misleading error message on non-UEFI jobs

assets/javascripts/openqa.js, assets/javascripts/running.js, assets/stylesheets/test-details.scss, t/ui/25-developer_mode.t, templates/test/live.html.ep
* So the context of those messages is clear and the messages are less disturbing
* Remove obsolete error messages when the error is gone
* See https://progress.opensuse.org/issues/39227
=> Move errors regarding developer mode into the devel panel

assets/javascripts/test_result.js, lib/OpenQA/WebAPI/Controller/Test.pm, t/ui/16-tests_dependencies.t, templates/test/dependencies.html.ep, templates/test/result.html.ep
See https://progress.opensuse.org/issues/42563
* Don't show cloned jobs in the dependency tree
* Don't show dependency tab for cloned jobs
(otherwise we would show a dependency tree where the
job itself isn't part of)
=> Hide cloned jobs from job dependency graph

lib/OpenQA/Schema/Result/Jobs.pm, lib/OpenQA/WebAPI/Controller/Step.pm, lib/OpenQA/WebAPI/Controller/Test.pm, t/ui/01-list.t
See https://progress.opensuse.org/issues/42560
---
I also refactored/simplified the code a little bit because as far as I see `running_modinfo` is only used in `/tests` which doesn't need all the info it produces.
=> Fix progress bars on /tests

assets/javascripts/admintable.js, t/ui/13-admin.t, templates/admin/machine/index.html.ep, templates/admin/product/index.html.ep, templates/admin/test_suite/index.html.ep
This introduces a way to find a testsuite as the current search is completely unusable.
Even using `CTRL+F` for searching a testsuite doesn't really help as eg `textmode` is a too common string that also appears as substring within other testsuite names.
With this patch it is possible to query for an exact testsuite name using a regex:
```
/admin/test_suites?filter_name=^textmode$
```
=> Add regex filter for admin tables

assets/javascripts/test_result.js
and require SHIFT for the shortcut to switch between candidates
See https://progress.opensuse.org/issues/39275
=> Allow to scroll up and down using arrow keys on test details

assets/javascripts/test_result.js, lib/OpenQA/WebAPI/Controller/Test.pm, t/ui/16-tests_dependencies.t
So it becomes transparent by which setting on which test the
dependencies have been specified.
See https://progress.opensuse.org/issues/40772#note-13
=> Add START_AFTER_TEST/PARALLEL_WITH to dep graph tooltip

assets/javascripts/running.js, lib/OpenQA/WebAPI/Controller/LiveViewHandler.pm, t/34-developer_mode-unit.t, t/ui/25-developer_mode.t
* See https://progress.opensuse.org/issues/39227
* If there's no running module according to
OpenQA::WebAPI::Controller::Running::status we can assume that
the os-autoinst command server is inavailable because it just
hasn't been started yet and suppress the error message.
=> devel mode: Suppress connection errors if no module running

docker/travis_test/Dockerfile
Basically, I want to update the docker image used to conduct the tests in the os-autoinst repository for https://github.com/os-autoinst/os-autoinst/pull/1048.
I'm not sure how our Docker/OBS setup works, but I suppose if I add the dependency to the CPAN file here, it will update the Docker image which is used in os-autoinst, too.
If this is true:
* There shouldn't be cyclic dependencies between os-autoinst and openQA - also not for the testing environment. So it would make sense to move the files for the Travis/Docker test environment to a separate repository.
* Document the current weirdness for the time being.
=> Add dependency for test in os-autoinst

lib/OpenQA/Worker/Jobs.pm
The worker typically cleans up after itself on stop already.
=> Do not log an error when trying to unlink an nonexisting file

profiles/apparmor.d/usr.share.openqa.script.worker
On some hosts we may want to make use of hugepages. For those, we want access
to the standardized /dev/hugepages directory.
Beware that to make this useful, you will also need to adapt permissions for
the /dev/hugepages mount. For that, do
$ systemctl edit dev-hugepages.mount
and add
[Mount]
DirectoryMode=1777
Options=mode=1777
so that on boot the mount point comes up as world writable.
Signed-off-by: Alexander Graf <agraf@suse.de>
=> Apparmor: Add /dev/hugepages

assets/javascripts/admin_groups.js, assets/javascripts/job_templates.js, lib/OpenQA/WebAPI/Controller/API/V1/JobGroup.pm, t/api/10-jobgroups.t, t/ui/13-admin.t, templates/admin/group/group_property_editor.html.ep, templates/admin/group/index.html.ep, templates/admin/group/parent_group_property_editor.html.ep
Job group name can be updated with empty or blank that lead to no link clickable, add constraint to refuse it.
See: https://progress.opensuse.org/issues/42947
=> Refuse updating job group name with empty or blank

t/26-controllerrunning.t
In Mojolicious 8.03, the `tx` and `app` attributes of the
Controller class were weakened. This appears to mean that you
must set them using an object that's referenced elsewhere, or
else they just sort of...disappear, and the test blows up, with
rather cryptic errors about calling methods on undefined values.
=> Handle `app` and `tx` attributes of Controller being weakened

lib/OpenQA/Task/Asset/Download.pm, lib/OpenQA/WebSockets/Server.pm, lib/OpenQA/Worker/Cache/Client.pm, lib/OpenQA/Worker/Common.pm, lib/OpenQA/Worker/Jobs.pm, script/clone_job.pl, t/api/01-workers.t
`Mojo::Transaction::success` has been deprecated in Mojolicious 8.02. Using `!$tx->error` is a short term fix for that. Long term it is recommended to use `$tx->result` instead, which has very different semantics and will therefore require quite a bit more work. But there are no plans to get rid of `Mojo::Transaction::error`, so this is fine for now.
=> Mojolicious 8.02 support

t/ui/16-tests_dependencies.t
Seems like the remaining `success -> !error` substitutions of https://github.com/os-autoinst/openQA/pull/1867 were not correct.
I'm wondering why the tests were not red when I merged it. Maybe my browser tab was outdated.
=> Revert "Fix deprecation warnings regarding Mojo::Transaction::error"

assets/stylesheets/dashboard.scss, t/22-dashboard.t, templates/main/group_builds.html.ep
Add link to test results for multiple job grops
There were no link to Test Results Page for parent job groups on
Dashboard Page.
The PR adds the link to the parent job group item. It allows to open
Test Results Page in new browser tab by performing middle mouse click or
by calling context menu and selecting 'Open link in new tab'.
Old behavior remains the same while doing left button mouse click.
Related ticket: [42851](https://progress.opensuse.org/issues/42851)
=> Add link to test results for multiple job grops

t/34-developer_mode-unit.t
It hits dbus during "register developer session", so it needs
this or else it will fail in Fedora's Koji build env (and other
similar envs, most likely).
=> Use OPENQA_TEST_IPC in developer mode unit test

lib/OpenQA/WebAPI/Controller/Step.pm, t/27-errorpages.t, t/ui/18-tests-details.t
* Improve error handling of Step controller and clean up the code a little bit.
* See https://progress.opensuse.org/issues/14904
=> Improve error handling of Step controller

lib/OpenQA/WebAPI/Plugin/Helpers.pm, t/ui/13-admin-no-login.t, templates/admin/group/parent_group_property_editor.html.ep, templates/admin/machine/index.html.ep, templates/admin/product/index.html.ep, templates/admin/test_suite/index.html.ep
The `is_admin` helper returns a Perl boolean, but was used to generate JavaScript booleans directly here. There was one more use of `<%= is_admin %>` for `setupJobTemplates`, but that function does not actually use that argument at all, so i opted to remove it.
While the fix was very simple, i'm still trying to find a good place to test this and am learning Selenium in the process. So please consider this pull request a work in progress for now.
Progress issue: https://progress.opensuse.org/issues/44039
=> Fix various uses of the is_admin helper in templates

openQA.spec
With the recent worker caching changes, the tests now fail
unless the rsync binary is present, so we should BuildRequires
rsync. It also seems logical to have the server and worker
Recommends it, as both ends need it installed if worker caching
is used.
=> Add rsync BuildRequires and Recommends to RPM spec

assets/javascripts/running.js, t/33-developer_mode.t, t/ui/25-developer_mode.t
See https://progress.opensuse.org/issues/43952
=> Expand devel controls by default if paused and owning the session

assets/stylesheets/tables.scss, templates/test/overview_result_table.html.ep
See: https://progress.opensuse.org/issues/42779
=> Use fixed header for overview table

lib/OpenQA/Worker.pm, script/worker
So systemd tries to restart the worker (instead of keeping it "inactive").
E.g. I had to restart workers manually after issues with the new cache service: https://progress.opensuse.org/issues/44351
Tested locally by manually inserting some wrong code.
=> Exit worker with non-zero return code in error cases

docs/Installing.asciidoc
HOSTS variable doesn't exist in workers.ini, only HOST.
Tested on my lab (that's how I saw the mistake :)).
=> Fix typo in installation documentation

docs/WritingTests.asciidoc
Related progress issue: https://progress.opensuse.org/issues/36994
=> docs: Extend development tricks with dynamic test override

lib/OpenQA/WebAPI.pm
Since Mojolicious 5.76 `srand` is called by `Mojo::Server::Prefork` whenever a new worker is spawned. So this workaround does not serve a purpose anymore.
=> Remove srand workaround that does nothing anymore

systemd/openqa-worker-cacheservice.service
Maybe this makes @coolo more happy :)
=> Fix network dependency for cache service

lib/OpenQA/Worker/Cache/Service.pm, t/25-cache-service.t, t/25-cache.t, t/lib/OpenQA/Test/Utils.pm
You can now actually see the output of other tests again. 😉
Progress: https://progress.opensuse.org/issues/44387.
=> Fix production mode setting for cache service tests

lib/OpenQA/BuildResults.pm, lib/OpenQA/IPC.pm, lib/OpenQA/Scheduler/Scheduler.pm, lib/OpenQA/Schema/Result/Jobs.pm, lib/OpenQA/Schema/Result/ScreenshotLinks.pm, lib/OpenQA/Schema/ResultSet/Assets.pm, lib/OpenQA/Task/Job/Modules.pm, lib/OpenQA/Task/Screenshot/Scan.pm, lib/OpenQA/Worker/Common.pm, lib/db_helpers.pm, lib/db_profiler.pm
Running `perlcritic --theme freenode --stern lib` against openQA showed some interesting potential bugs. Using the varibles `$a`/`$b` outside of their intended purpose, or doing `for my $item (%hash) {` would have most defnitely resulted in unintended side effects (maybe already have). Similarly the use of implicit `$_` is fine for one-liners, but has no place in real applications.
If there are no objections i would like to propose that we try to follow the rules from [Perl::Critic::Freenode](https://metacpan.org/pod/Perl::Critic::Freenode) in the future for openQA. (I have made no changes in that regard yet, and will be waiting for feedback first) There are still quite [a few rules that openQA breaks](https://gist.github.com/kraih/09ebe5083b52eb62a5e17c4f520ae748), but they are all low …
=> Make all modules pass Perl::Critic::Freenode with severity level 4

assets/javascripts/running.js, lib/OpenQA/WebAPI/Controller/LiveViewHandler.pm, t/33-developer_mode.t, t/ui/25-developer_mode.t, templates/test/live.html.ep
* See https://progress.opensuse.org/issues/44249
* Requires https://github.com/os-autoinst/os-autoinst/pull/1067
---
=> devel mode: Allow to skip assert/check_screen timeout

.perlcriticrc, Makefile, cpanfile, dbicdh/_common/upgrade/36-37/02-convert_audit_toJSON.pl, lib/OpenQA/Client/Archive.pm, lib/OpenQA/Schema/Result/Workers.pm, lib/OpenQA/WebAPI/Controller/LiveViewHandler.pm, lib/OpenQA/Worker/Cache.pm, openQA.spec, script/client, script/clone_job.pl, script/load_templates, script/modify_needle, t/17-labels_carry_over.t, t/23-amqp.t, t/ui/18-tests-details.t
This should be a well balanced set of rules to encourage a slightly better coding style. I've also fixed the dependency on `JSON`, which was missing from `cpanfile`, and removed the dependency on `List::MoreUtils`, which was unnecessary.
Progress: https://progress.opensuse.org/issues/44597.
=> Use Perl::Critic::Freenode to determine good coding style

lib/OpenQA/WebAPI/Plugin/Fedmsg.pm, t/18-fedmsg.t
I'm busy migrating all the Fedora openQA infrastructure to
Python 3, so let's do the plugin. We could make this all fancy
and have it check whether fedmsg-logger-3 is available and fall
back on fedmsg-logger if not, but...let's not!
=> Fedmsg: use Python 3 logger command

assets/javascripts/test_result.js, assets/stylesheets/test-details.scss, lib/OpenQA/Schema/Result/Jobs.pm, lib/OpenQA/Utils.pm, lib/OpenQA/WebAPI/Controller/Test.pm, t/ui/18-tests-details.t, templates/test/details.html.ep, templates/test/external.html.ep, templates/test/module_table.html.ep, templates/test/result.html.ep
A revival of my old branch for an extra table to display external test results, see https://progress.opensuse.org/issues/36232
Unlike https://github.com/os-autoinst/openQA/pull/1492, it renders the generic data from the openQA parser and not a specific format.
---
The current details page would stay as it is, eg.:  
The additional tab "External results" would show test results from external testsuites which have been parsed by openQA to a generic JSON representation:
* It *only* contains the external results.
* It can be sorted and filtered on the level of the particular test details (and not only on  test module level).
* The tab is only shown if external results are available.
* The table is not updated while the test is running. That would be too much effort for such a feature in my …
=> Add extra table for external results

docker/travis_test/Dockerfile
Needed for https://github.com/os-autoinst/os-autoinst/pull/1070.
=> Add Perl::Critic::Freenode to the test container

lib/OpenQA/Worker/Engines/isotovideo.pm
In aee5e58, @foursixnine attempted to fix the use of `ASSET_`-
type assets with asset caching. However, I think the fix was
wrong and will not work.
If you look at all the other asset types in this code, they do
*not* look for the `_URL` form of the asset parameter. This is
the only one that tries to do it that way. Doing it that way is
just not going to work, because the value of the `_URL` form
is an entire URL, not just a filename. I'm pretty sure this is
going to wind up looking for `factory/other/http://blah/moo.pm`,
or something along those lines, and is never going to find it.
The `_URL` download stuff has already been handled by the time
we hit this point, and the file it pointed to should already
have been downloaded to the asset directory, and the 'bare'
form of the parameter …
=> When detecting asset keys, don't use the _URL form for ASSET

openQA.spec
The perl is just too old and missing too many modules
=> Do not require perlcritic on sle-12

t/14-grutasks.t
Since ea55d577, this subtest in grutasks creates a limit_assets
task, but doesn't run it. If the following subtest *does* run,
then it flushes the limit_assets task as well, and there's no
problem. But if the following subtest is skipped, because OBS_RUN
is set, then the limit_assets task just sorta hangs around in
gru's task queue...and the *next* time we actually run gru, which
happens to be in 17-build_tagging.t, the limit_assets task gets
picked up and run. Because the Assets schema `remove_from_disk`
sub is not mocked out in build_tagging as it is in grutasks, this
means gru actually goes ahead and wipes out several asset files.
That then causes 37-limit_assets.t to fail because it relies on
all the expected assets being present.
=> Don't leave a limit_assets task hanging after 14-grutasks.t

docker/openqa/entrypoint.sh, script/docker-tests
We really need to see if cpanfile changes need to be moved into the
container. While this is not the case, developers can set INSTALL_FROM_CPAN
in their dev branches - to be removed before merge
=> Disable INSTALL_FROM_CPAN by default

lib/OpenQA/Schema/Result/Jobs.pm, lib/OpenQA/Schema/ResultSet/Assets.pm, lib/OpenQA/WebAPI/Controller/API/V1/Asset.pm, lib/OpenQA/WebAPI/Controller/API/V1/Iso.pm, t/37-limit_assets.t, t/api/02-assets.t
See https://progress.opensuse.org/issues/44690
=> Prevent empty asset names

openQA-test.spec
See https://build.opensuse.org/request/show/656943 for reasoning. I am
not sure how and why coolo created
https://build.opensuse.org/request/show/655987 for manual update but now
we would revert to old license identifier format.
=> Update license of test spec-file to current SPDX format

assets/javascripts/admin_worker.js, dbicdh/PostgreSQL/deploy/72/001-auto-__VERSION.sql, dbicdh/PostgreSQL/deploy/72/001-auto.sql, dbicdh/PostgreSQL/upgrade/71-72/001-auto.sql, dbicdh/_source/deploy/72/001-auto-__VERSION.yml, dbicdh/_source/deploy/72/001-auto.yml, lib/OpenQA/Scheduler/Scheduler.pm, lib/OpenQA/Schema.pm, lib/OpenQA/Schema/Result/Workers.pm, lib/OpenQA/WebAPI/Controller/API/V1/Worker.pm, lib/OpenQA/WebAPI/Controller/Admin/Workers.pm, lib/OpenQA/WebSockets/Server.pm, lib/OpenQA/Worker/Cache.pm, lib/OpenQA/Worker/Cache/Client.pm, lib/OpenQA/Worker/Commands.pm, lib/OpenQA/Worker/Common.pm, lib/OpenQA/Worker/Engines/isotovideo.pm, t/25-cache-service.t, t/27-websockets.t, t/api/01-workers.t, t/lib/OpenQA/SeleniumTest.pm, t/ui/15-admin-workers.t, templates/admin/workers/worker_status.html.ep
That should prevent 'tons of incompletes' in case the worker cache isn't working: https://progress.opensuse.org/issues/44105
This introduces the concept of detecting worker misconfiguration *before* starting a job. This could by extended by further sanity checks in the future.
=> Add 'broken' state to the worker 

lib/OpenQA/Schema/ResultSet/Assets.pm
See https://progress.opensuse.org/issues/45041
=> Fix error/inconsistency in asset cleanup

lib/OpenQA/Events.pm, lib/OpenQA/IPC.pm, lib/OpenQA/Setup.pm, lib/OpenQA/WebAPI.pm, lib/OpenQA/WebAPI/Controller/API/V1/Job.pm, lib/OpenQA/WebAPI/Plugin/AMQP.pm, lib/OpenQA/WebAPI/Plugin/AuditLog.pm, lib/OpenQA/WebAPI/Plugin/Fedmsg.pm, lib/OpenQA/WebAPI/Plugin/Helpers.pm, lib/OpenQA/WebAPI/Plugin/MemoryLimit.pm, lib/OpenQA/Worker/Commands.pm, lib/OpenQA/Worker/Jobs.pm, t/32-openqa_client.t, t/api/04-jobs.t
So far Mojo::IOLoop and Mojo::Reactor have been used to emit global events. That's very risky since it's not officially supported upstream and can therefore break at any time. This pull request adds a new module OpenQA::Events that will serve as the global openQA event emitter from now on.
I've also moved the memory limit code that looked a bit put of place in OpenQA::WebAPI into the plugin OpenQA::WebAPI::Plugin::MemoryLimit since i was cleaning up plugins anyway.
Both shouldn't be too controversial. 😄
Progress: https://progress.opensuse.org/issues/45014.
=> Add a new module for global events

lib/OpenQA/Worker/Commands.pm, lib/OpenQA/Worker/Jobs.pm
Built on top of https://github.com/os-autoinst/openQA/pull/1911
---
* Refuse to accept jobs which have no ID and settings
* Log invalid job object
---
This should allow us to further investigate https://progress.opensuse.org/issues/28714. I tested the change manually by letting the web UI send an invalid job object. Otherwise I could not reproduce the sporadic issue.
So the worker would no produce log lines like:  
```
[error] [pid:27379] Refusing 'grab_job' because job is invalid: "HASH(0x563f2430c328)"
```
It won't even try to start the job and is free to take another.
=>  worker: Validate job sent by web UI "job_grab" 

lib/OpenQA/IPC.pm, lib/OpenQA/ResourceAllocator.pm, lib/OpenQA/Scheduler.pm, lib/OpenQA/Scheduler/Scheduler.pm, lib/OpenQA/Schema.pm, lib/OpenQA/WebAPI/Plugin/Gru.pm
The use of sigtrap just got in the way when i was trying to simplify Gru a bit. Merely loading a module like OpenQA::Scheduler shouldn't change global state like signal handlers (action at a distance etc.). A better way to handle signals in modules is to localize them to the method/function that runs the mainloop. Unless some part of openQA depends on sigtrap magic, this change should not result in any noticeable differences in behaviour.
=> Use localized signal handling instead of global sigtrap for modules

docs/UsersGuide.asciidoc, lib/OpenQA/Utils.pm, lib/OpenQA/Worker/Engines/isotovideo.pm, t/16-utils.t, t/24-worker-engine.t
It seems we have two possible ways of using UEFI_PFLASH_VARS.
It may refer to the absolute filesystem location of a template
file, e.g. the ones shipped by edk2, or it may refer to an
image uploaded as an asset by a parent test (in the case that
we want a child test to 'inherit' the modifications to UEFI
vars that occurred during its parent's run).
We need to treat it as an asset when it really is an asset, so
it can be cached and found correctly - but we also need to *not*
treat it as an asset when it is not one, so openQA doesn't fail
to find it as an asset and cause the test to die. I think it
should be safe to simply go off whether the value looks like an
absolute path or not (i.e. starts with '/', since I don't think
anyone's doing this stuff on Windows...)
Signed-off-by: Adam …
=> Don't treat UEFI_PFLASH_VARS as asset if path is absolute

docker/openqa/entrypoint.sh, docker/testing/test.sh, openQA.spec
In Travis the test logs are still way too verbose to find anything (in fact Travis will refuse to display them completely https://travis-ci.org/os-autoinst/openQA/jobs/467944626). You might have noticed that when testing locally the test output is much more manageable. The reason for that is the global `MOJO_LOG_LEVEL=debug` environment variable we are setting for docker tests.
`MOJO_LOG_LEVEL` is a sledge hammer that overrides all other settings, including the Mojolicious application mode, which many tests use to decide what makes sense to log. I think by default we should leave it up to the tests to make this decision. `MOJO_LOG_LEVEL=debug` can still be used for debugging purposes by developers, but only on-demand.
=> Do not set the MOJO_LOG_LEVEL environment variable by default

cpanfile
We should avoid suprises on travis - but update explicitly whenever
we feel the need to do so
(in accordance with https://github.com/os-autoinst/os-autoinst/pull/927)
=> Use a fixed version of perltidy

lib/OpenQA/WebAPI/Controller/Test.pm, t/ui/10-tests_overview.t, templates/test/overview.html.ep
* Move logic for summary name into controller
* Show multiple distris or versions separated by '/'
=> Prevent 'Summary of HASH(...)' if multiple distris/versions specified

lib/OpenQA/Events.pm
This pull request is less about the actual change, and more about getting a discussion started about module documentation.
While we might not be in a state yet where we can document every individual method/attribute/function, i think it would make sense to at least have a basic description for every Perl module in the openQA repo. As an example i've used the module OpenQA::Events (which i just added). And the POD skeleton is the same Mojolicious uses upstream (and which is considered rather good style in the community).
Thoughts/Ideas?
=> Add basic documentation for OpenQA::Events

t/37-limit_assets.t
Since 71172fc, this test hits IPC, I think when it calls
`schedule_iso` with an invalid repo name. We need to mock the
IPC or the test will fail in package build environments.
=> Use OPENQA_TEST_IPC mock in 37-limit_assets.t

assets/javascripts/running.js, lib/OpenQA/WebAPI/Controller/LiveViewHandler.pm, t/33-developer_mode.t, t/34-developer_mode-unit.t, t/lib/OpenQA/Test/FakeWebSocketTransaction.pm, t/ui/25-developer_mode.t, templates/test/live.html.ep, templates/test/module_select.html.ep
os-autoinst already has (almost) the code to pause on `check_screen` timeouts so I thought making this accessible via the web UI would make sense.
This is still WIP and would look like this:
There's no ticket requesting this feature (and defining how it is supposed to look like) so some feedback would be nice.
Another improvement I could do (when I'm already over it) is a "Pause after current command" checkbox. I suppose this feature (combined with "Skip current assert/check_screen timeout") was present in the previous interactive mode as well.
=> developer mode: versioning, pause on check_screen timeout

dbicdh/PostgreSQL/deploy/73/001-auto-__VERSION.sql, dbicdh/PostgreSQL/deploy/73/001-auto.sql, dbicdh/PostgreSQL/upgrade/72-73/001-auto.sql, dbicdh/_source/deploy/73/001-auto-__VERSION.yml, dbicdh/_source/deploy/73/001-auto.yml, lib/OpenQA/Schema.pm, lib/OpenQA/Schema/Result/Needles.pm, lib/OpenQA/Schema/ResultSet/Needles.pm, t/21-needles.t
See https://progress.opensuse.org/issues/44969
---
I just add an additional `last_update` column here which will only be refreshed on actual updates of the needle. Tests are still TODO.
=> Prevent wrong 'New needle ...' notifications in needle editor

lib/OpenQA/WebAPI.pm, lib/OpenQA/WebAPI/Command/gru.pm, lib/OpenQA/WebAPI/Command/gru/list.pm, lib/OpenQA/WebAPI/Command/gru/run.pm, lib/OpenQA/WebAPI/GruJob.pm, lib/OpenQA/WebAPI/Plugin/Gru.pm, t/14-grutasks.t, t/17-build_tagging.t, t/lib/OpenQA/Test/Database.pm
While learning the Gru code i noticed that it's actually not too hard to remove all the workarounds and make `gru run` start a normal Minion worker. With all the available features activated, such as processing each job in a separate process (which will free up the memory each job used after it is done). Currently there is still a hardcoded limit since some tasks can't handle parallel execution yet, but theoretically once that is fixed Gru could also run jobs in parallel (which should make it easier to move more work into background processes).
I've introduced a new `OpenQA::WebAPI::Command` namespace so there is no need anymore to hide secondary classes in the plugins.
There were also some fork related issues in `t/14-grutasks.t` (mock IPC) and `t/lib/OpenQA/Test/Database.t` (didn't …
=> Actually use a Minion worker for Gru
