os-autoinst/openQA

t/01-compile-check-all.t

I didn't find procedural way soon enough so OO way be it.

switch off compile test verbose output

---

lib/OpenQA/Controller/Step.pm

it should have a check like "Same file already exists! Replacing it? Yes/No", but before I implementing and finish it just disallow it for now.

do not overwrite the exist needle

---

templates/admin/workers/index.html.ep

the id within the worker table is pretty uninteresting to humans,
so just name the worker like "$HOST:$INSTANCE" and sort accordingly

sort the workers logically

---

lib/OpenQA/Controller/Test.pm
lib/OpenQA/Plugin/Helpers.pm
lib/OpenQA/modules/openqa.pm
templates/test/result.html.ep

* Remove res_css and res_display from openqa.pm
* Merge screenshots, audio and ocrs in a single column

UI polishing in job result page

---

lib/OpenQA/Controller/Test.pm

we need this for sle11 where server-dvd and desktop-dvd have different build
numbers

support optional filter for flavor

---

lib/OpenQA/Controller/API/V1/JobTemplate.pm
script/dump_templates
script/load_templates
t/api/08-jobtemplates.t

https://progress.opensuse.org/issues/6090

use API in load_templates and dump_templates

---

etc/apache2/vhosts.d/openqa-common.inc
script/clean_needles
script/dump_templates
script/initdb
script/load_templates
script/upgradedb

Wait till tests finish, I didn't test scripts without lib/OpenQA in libpath yet (some problems with Mojo 5.74 :) )

small fixes

---

docs/WritingTests.asciidoc

For https://github.com/os-autoinst/os-autoinst/pull/169

added a new API function

---

lib/OpenQA/Scheduler.pm
lib/OpenQA/Schema/Result/JobDependencies.pm
t/05-scheduler-dependencies.t

this is not fully finished
it might break chained jobs - that part of code is not covered by automatic tests yet

parallel dependency

---

lib/OpenQA/Controller/Step.pm

this is apparently broken since f0226cecb9e2a

fix for needle editor: stash('results') no longer exists

---

lib/OpenQA.pm
lib/OpenQA/Controller/File.pm
lib/OpenQA/Utils.pm

noticed the uncovered functions

assets replaced /diskimages long ago - get rid of it

---

lib/OpenQA/Schema/Result/JobModules.pm
templates/test/result.html.ep

- readd auto stripeto the (non-jquery) table
- give the job modules an order

restore the /tests/:id route

---

lib/OpenQA/Controller/Running.pm

take worker id and running module from DB - and remove TODO
fixing #185

fix the status in live view

---

t/ui/13-admin.t
t/ui/PhantomTest.pm

not only create a new machine, but also a new product and a new test
suite and that new test suite to all machines on this new product
and save

extend the admin test

---

lib/OpenQA/Controller/API/V1/Iso.pm
t/api/02-iso.t
t/api/07-testsuites.t
t/api/08-jobtemplates.t
t/fixtures/04-products.pl

I improved the code a bit and added some tests.
(creating new pull request, I had some problems with changing the original one)

parallel dependencies configuration via variables - try2

---

lib/OpenQA/Locks.pm
t/13-joblocks.t

- avoid writing to db when double locking our locked lock
- add relevant test

return success when unlocking unlocked lock

---

lib/OpenQA/Controller/Test.pm
templates/test/running_table.html.ep

https://progress.opensuse.org/issues/6450

don't display null for empty build numbers

---

t/ui/01-list.t
templates/test/running_table.html.ep

https://progress.opensuse.org/issues/6448

make sure the running tests show a proper start time

---

templates/test/result.html.ep
templates/test/running.html.ep

For scheduled job the backend is a setting like any other - nothing special
about it
As a matter of fact the whole box is only there to show some kvm2usb things we don't support atm.

show backend infos only if there is a backend

---

docs/WritingTests.asciidoc
lib/OpenQA/Scheduler.pm
lib/OpenQA/Worker/Common.pm
t/05-scheduler-capabilities.t

https://progress.opensuse.org/issues/6438

explicitly assign certain jobs to certain worker

---

public/javascripts/needleedit.js
templates/step/edit.html.ep

while I was it I fixed another issue

fix issue 6610: background radio buttons are not exclusive

---

public/javascripts/needleedit.js

if http://api.jquery.com/prop/ doesn't lie me then it should work, and actually tested it on my machine.

use .prop instead of .attr for checked property

---

script/migrate_images
script/optimize_images

our directories are way too big for globs ;(

use File::Find instead of globs for the images scripts

---

lib/OpenQA/Scheduler.pm
lib/OpenQA/Worker.pm
lib/OpenQA/Worker/Common.pm
lib/OpenQA/Worker/Jobs.pm
script/worker

delay stop_job if needed to wait fo update_status

recursive api_calls are forbidden

---

lib/OpenQA/Scheduler.pm

parallel jobs can block each other so call job_notify_workers
in case some jobs are unblocked

notify workers after parallel job is started

---

templates/admin/user/index.html.ep

as users are paginated we can't bind only visible radio buttons but also those
appearing only on page 2

Fix role selection for multiple pages

---

public/javascripts/needleedit.js
public/javascripts/needleeditor.js

for issue#6656.
yeah, I'll start working on https://progress.opensuse.org/issues/6562

update textarea after switched tags button; keep modified tags values

---

lib/OpenQA/Scheduler.pm

The condition in commit ef8f1b9f872 was not correct, this one is better.

better condition for notify_workers

---

lib/OpenQA/Worker/Jobs.pm

we need to upload the remaining test modules

accept running='' as last module

---

lib/OpenQA/Worker/Pool.pm

We should have qemu killing under control now

ignore stale qemu.pid files

---

lib/OpenQA/Controller/Running.pm
lib/OpenQA/Controller/Test.pm
lib/OpenQA/Schema/Result/JobModules.pm
lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/Worker/Jobs.pm
public/javascripts/running.js
templates/test/running.html.ep

- store the WAITING state when needinput is set
- show the proper icon for interactive mode

some (incomplete) fixes for interactive mode:

---

lib/OpenQA.pm
public/javascripts/dataTables.bootstrap.js
public/javascripts/tests.js
public/stylesheets/dataTables.bootstrap.css
public/stylesheets/openqa.css
t/ui/01-list.t
t/ui/02-csrf.t
t/ui/10-tests_overview.t
templates/test/list.html.ep
templates/test/overview.html.ep
templates/test/running_table.html.ep
templates/test/scheduled_table.html.ep

introducing bootstrap integration for jquery.datatables - so the diff
looks a bit bigger

port /tests route to bootstrap

---

t/05-scheduler-capabilities.t

this covers the case discussed in pull request 311

test worker class together with parallel dependencies

---

dbicdh/MySQL/deploy/29/001-auto-__VERSION.sql
dbicdh/MySQL/deploy/29/001-auto.sql
dbicdh/MySQL/upgrade/28-29/001-auto.sql
dbicdh/PostgreSQL/deploy/29/001-auto-__VERSION.sql
dbicdh/PostgreSQL/deploy/29/001-auto.sql
dbicdh/PostgreSQL/upgrade/28-29/001-auto.sql
dbicdh/SQLite/deploy/29/001-auto-__VERSION.sql
dbicdh/SQLite/deploy/29/001-auto.sql
dbicdh/SQLite/upgrade/28-29/001-auto.sql
dbicdh/_common/upgrade/28-29/10-add-worker-class.pl
dbicdh/_source/deploy/29/001-auto-__VERSION.yml
dbicdh/_source/deploy/29/001-auto.yml
lib/OpenQA/Schema/Schema.pm
lib/OpenQA/Worker/Common.pm
templates/admin/workers/show.html.ep

needed as usual for i586 on x86_64 hosts

make worker also report compatible classes

---

lib/OpenQA/Controller/Test.pm

make overview page able to adapt with group param

---

lib/OpenQA/Schema/Result/Jobs.pm
t/api/04-jobs.t

fixed a bug in db update, added tests

Assets fix

---

t/01-compile-check-all.t
t/api/04-jobs.t

- after psladek's DBIx refactoring, all modules should pass compile check now
- change some tests to be readable

remove compile test exceptions

---

lib/OpenQA/Controller/API/V1/Job.pm
t/api/04-jobs.t

the user story is, I hope we can allow limit pram as well, then I can just query the last 10 or 20 jobs instead of all  jobs, querying all jobs is a heavy loading for server...

allow the limit parameter

---

templates/test/running_table.html.ep

Use bootstrap progress bars: http://getbootstrap.com/components/#progress-label

use bootstrap progress bars

---

lib/OpenQA/Controller/Main.pm
lib/OpenQA/Controller/Test.pm
lib/OpenQA/Plugin/Helpers.pm
t/ui/14-dashboard.t
templates/main/index.html.ep

Requirs distri and version param from now, modified the affect area as well.

Refactor overview's params requirement

---

lib/OpenQA/Worker/Engines/isotovideo.pm

- they are used for generating unique TAP dev and its MAC address
- move generating code to isotovideo

pass instance and workerid to isotovideo

---

docs/Networking.asciidoc
docs/WritingTests.asciidoc

- updated and moved from os-autoinst

add networking info from os-autoinst

---

lib/OpenQA/Schema/Result/Jobs.pm
t/05-scheduler-dependencies.t
t/05-scheduler-restart-and-duplicate.t

- this change behaviour when cloning parents with CHAINED children.
Originally, children were left intact and only dependency recreated (but not 
in case of cloning due to job asset dependency). Now, when
parent is being cloned, all children are also cloned.
- reason is to consistently solve cloning issue due to job asset
previously when job with job asset dependency was cloned, the mandatory
CHAINED dependency was not recreated. Just recreating it however lead
to confusion when CHAINED child is cloned and when not (asset
dependencies are not visualized in WebUI). So we decided to clone
CHAINED child every time parent is cloned (also useful during test development).
- PARALLEL dependency cloning behaviour is not affected

clone CHAINED children on parent cloning

---

lib/OpenQA/Worker/Jobs.pm

use common function and add error handling for uploading assets

refactor log upload

---

Makefile
lib/OpenQA/IPC.pm
lib/OpenQA/WebSockets/Server.pm
script/openqa-scheduler
script/openqa-websockets
systemd/openqa-scheduler.service
systemd/openqa-websockets.service
systemd/openqa-webui.service

- this uses D-Bus **system bus**, since systemd service *type=dbus* requires it
- autostarting is not enabled here yet

split openqa services to dependent systemd units

---

script/client

- https://github.com/kraih/mojo/commit/aab2f1f320056cb14c4666854ef357dc4347942e

Mojo::URL no longer escapes / in URL

---

lib/OpenQA/IPC.pm

- previous implementation keep polling for writable bus all the time
which consumes way too much cpu cycles since I didn't implement watch
toggle and watch removal
- this commits add them in the same manner as in Net::DBus::Reactor only
for Mojo::Reactor
- this commit also add dup for fd when trying to get fh so that
Mojo::Reactor does not get confused and toggling read/write

fix excess cpu usage by websockets dbus handlers

---

lib/OpenQA/Scheduler/Scheduler.pm

- Scheduler does not have access to WebAPI plugins anymore so
replace gru->enqueue by direct call to db
- don't enqueue gru tasks after each job_create when in batch mode

fix gru enqueue in scheduler

---

lib/OpenQA/Worker/Commands.pm

- after livelog is decremented recheck the status

stop nonstop livelog

---

lib/OpenQA/WebAPI/Controller/Test.pm

- avoid 500 variables sqlite limit (issue#421) in dependency query

replace multiple DB queries by single one

---

lib/OpenQA/WebAPI/Controller/Test.pm

- multiple joins were significantly regressing performance (from ~second to 8s)
so keep modules and settings in their own queries (this is back to < second for
db query, ~1s for mojo response for full 500 results)
- keep joins for dependencies to avoid variable limit on sqlite (#421)

partial revert of 6dfbea2e2

---

profiles/apparmor.d/usr.share.openqa.script.worker

used for converting qemu images

allow ionice in apparmor profile

---

public/sass/bento/footer.scss
templates/layouts/bootstrap.html.ep

... but make sure that the footer still will be shown at the bottom of the page when there is no scrollbar

Remove footer css-fixed property

---

lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
t/api/02-iso.t

there is just too much going on
*note* though that this is not the original problem I was hunting :)

prefetch more values for jobs/list

---

lib/OpenQA/WebAPI/Controller/API/V1/Iso.pm
lib/OpenQA/WebAPI/Controller/API/V1/Job.pm

I thought it is done automatically by Mojo, apparently not. Needed for maintenance tests.

decode URL encoded %2F back to /

---

dbicdh/MySQL/deploy/34/001-auto-__VERSION.sql
dbicdh/MySQL/deploy/34/001-auto.sql
dbicdh/MySQL/upgrade/33-34/001-auto.sql
dbicdh/PostgreSQL/deploy/34/001-auto-__VERSION.sql
dbicdh/PostgreSQL/deploy/34/001-auto.sql
dbicdh/PostgreSQL/upgrade/33-34/001-auto.sql
dbicdh/SQLite/deploy/34/001-auto-__VERSION.sql
dbicdh/SQLite/deploy/34/001-auto.sql
dbicdh/SQLite/upgrade/33-34/001-auto.sql
dbicdh/_common/upgrade/33-34/02-scan_needles.pl
dbicdh/_source/deploy/34/001-auto-__VERSION.yml
dbicdh/_source/deploy/34/001-auto.yml
lib/OpenQA/Schema/Result/JobModuleNeedles.pm
lib/OpenQA/Schema/Result/JobModules.pm
lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/Schema/Result/NeedleDirs.pm
lib/OpenQA/Schema/Result/Needles.pm
lib/OpenQA/Schema/Schema.pm
lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Controller/Admin/Needle.pm
public/javascripts/admin_needle.js
templates/admin/needle/index.html.ep
templates/layouts/admin_nav.html.ep

To be discussed. There is no delete functionality, because we need to come up with a definition of what is an obsolete needle.

Needle management

---

lib/OpenQA/WebAPI.pm
profiles/apparmor.d/usr.share.openqa.script.openqa

Try to create MOJO_TMPDIR at least, but don't die if the tmpdir is
failed to create, just throw a error and continue, let MOJO to decide
where is the tmpdir.

Try to create MOJO_TMPDIR if it doesn't exist

---

dbicdh/_common/upgrade/33-34/02-trigger_gru.pl
lib/OpenQA/Schema/Result/JobModules.pm
lib/OpenQA/Schema/Result/Needles.pm
lib/OpenQA/WebAPI.pm

We just have way too many jobs to justify the outage

delay the actual parsing to a gru task

---

lib/OpenQA/WebAPI/Controller/File.pm

Not sure why this is not using the model ($job->test_resultdir) though

fix calling testresultdir(undef)

---

lib/OpenQA/Schema/Result/JobModules.pm

Details are pushed possibly twice from the worker, so take care of that

avoid duplicates in the job_module_needles table

---

lib/OpenQA/WebAPI/Controller/Step.pm

fixes https://progress.opensuse.org/issues/8802

suggest a better name needle name if we have no previous needles

---

dbicdh/MySQL/deploy/35/001-auto-__VERSION.sql
dbicdh/MySQL/deploy/35/001-auto.sql
dbicdh/MySQL/upgrade/34-35/001-auto.sql
dbicdh/PostgreSQL/deploy/35/001-auto-__VERSION.sql
dbicdh/PostgreSQL/deploy/35/001-auto.sql
dbicdh/PostgreSQL/upgrade/34-35/001-auto.sql
dbicdh/SQLite/deploy/35/001-auto-__VERSION.sql
dbicdh/SQLite/deploy/35/001-auto.sql
dbicdh/SQLite/upgrade/34-35/001-auto.sql
dbicdh/_common/upgrade/34-35/02-trigger_gru.pl
dbicdh/_source/deploy/35/001-auto-__VERSION.yml
dbicdh/_source/deploy/35/001-auto.yml
lib/OpenQA/Schema.pm
lib/OpenQA/Schema/Result/Needles.pm
lib/OpenQA/Utils.pm
lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Controller/Admin/Needle.pm
lib/OpenQA/WebAPI/Controller/Step.pm
lib/OpenQA/WebAPI/Plugin/Helpers.pm
public/javascripts/admin_needle.js
templates/admin/needle/index.html.ep

It worked (tested locally and git removed locally) - but I don't like it. I rather have the needle marked as gone, so that if it reappears (git revert), we still have the information which module used it.
So I need to create a new schema version - but not on friday evening ;)

add functionality to remove needles seen on the list

---

profiles/apparmor.d/usr.share.openqa.script.worker

drop quite some allowed tools in apparmor profile

---

lib/OpenQA/WebAPI/Plugin/AuditLog.pm

audit_log option was removed from config file.

remove useless line

---

lib/OpenQA/Scheduler/Scheduler.pm

when an individual job is selected using
client isos post TEST=name, schedule also it's parents

Schedule jobs with dependecies

---

script/clone_job.pl

- it seems it's not used anywhere anymore

remove useless loading of JSON::RPC modules

---

script/modify_needle

used to fix https://progress.opensuse.org/issues/9816, but might be useful
in the future for other cases

add script to add tags to needles

---

Makefile
lib/OpenQA/IPC.pm
lib/OpenQA/Scheduler/Locks.pm
lib/OpenQA/Scheduler/Scheduler.pm
lib/OpenQA/Schema/Result/JobModules.pm
lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Auth/OpenID.pm
lib/OpenQA/WebAPI/Controller/API/V1.pm
lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
lib/OpenQA/WebAPI/Controller/API/V1/Table.pm
lib/OpenQA/WebAPI/Controller/Admin/AuditLog.pm
lib/OpenQA/WebAPI/Controller/Main.pm
lib/OpenQA/WebAPI/Controller/Running.pm
lib/OpenQA/WebAPI/Controller/Session.pm
lib/OpenQA/WebAPI/Controller/Step.pm
lib/OpenQA/WebAPI/Controller/Test.pm
lib/OpenQA/WebAPI/Plugin/Helpers.pm
lib/OpenQA/Worker.pm
lib/OpenQA/Worker/Commands.pm
lib/OpenQA/Worker/Common.pm
lib/OpenQA/Worker/Jobs.pm
lib/db_profiler.pm
lib/perlcritic/Perl/Critic/Policy/HashKeyQuotes.pm
script/worker
t/07-api_keys.t

Needed for https://progress.opensuse.org/issues/8082

Return job state

---

lib/OpenQA/WebAPI/Plugin/Helpers.pm
public/stylesheets/openqa.css

https://progress.opensuse.org/issues/9922

Mark workaround needles as such in the overview

---

docs/WritingTests.asciidoc

- documentation for https://github.com/os-autoinst/os-autoinst/pull/374

Update documentation about TESTDEBUG usage

---

templates/test/running.html.ep

Fixes https://progress.opensuse.org/issues/10118

Add mouse over help text for interactive mode

---

lib/OpenQA/Schema/Result/JobModules.pm

On Fedora's openQA instance, some of these JSON files are
malformed, for some reason. This causes the GRU scan_old_jobs
task to fail, and GRU tasks failing is really bad, they just
repeat on an endless loop. We already guard against not being
able to open the file and return an empty list, so it seems to
make sense to do the same if the file is malformed.

JobModules details(): catch malformed JSON files (#517)

---

lib/OpenQA/Scheduler/Scheduler.pm

so, er, oops. this has been broken since initial commit. I
always intended it to be possible to post a request with just
ISOURL set, but not ISO, if you just wanted openQA to download
the ISO with its original filename; setting ISO along with
ISOURL is supposed to be optional and only necessary if you
want to download the ISO with a *different* filename. However,
I must have wound up only testing the case where both are set.
If only ISOURL was set, then two things wound up broken:
* the download target location was incorrect as the code to
set it assumes $args{ISO} is specified, so the download
subroutine would never download the image because the target
location already exists (it winds up being just `isodir`)
* the generated jobs don't have an ISO setting, so even if you
fixed the first …

job_schedule_iso: fix when ISOURL is set but not ISO

---

t/ui/10-tests_overview.t
t/ui/15-comments.t

* tests: Add test for commenting on test results page
* tests: Check for failed modules on overview page

More tests

---

lib/OpenQA/WebAPI.pm

Apparently menu route is no longer valid.

Remove unused/useless menu route

---

lib/OpenQA/WebAPI/Controller/File.pm

Instead of DBus query database directly.
I also fixed the #FIXME so assets are now fetched through job
relations thus ensuring they indeed belongs to the job specified.

Remove unneeded DBus roundtrip for asset getter

---

script/clone_job.pl

Add 3 good examples to clonejob.pl when invoked the usage function on command line

Add examples usages for clonejob.pl

---

lib/OpenQA/Schema/Result/Assets.pm

We just have too many jobs with too many assets - so the join results
in a *huge* list that we went through in perl because a distinct is not
possible in that join. So now do it in 2 steps, first get the distinct
number of job_assets and then grab the asset information about them

GRU limit_assets: Only check assets once to avoid a CPU hog

---

lib/OpenQA/WebAPI/Controller/Main.pm

Same functionality as in before but faster as comments are prefetched for all
jobs in each build in each group. Obviously this could be further optimized
by prefetching comments for all jobs at once but we do not know the jobs
before iterating the builds.
Tested with a production database dump from openqa.suse.de from
2016-02-25 fetching the page 'group_overview/25'. Comparing the number of
queries for comments and the user space time.
Before: 356 @ 2.6s
After: 11 @ 1.9s
*WIP*: It looks like the database from o.s.d is much more demanding and should be used for testing. But the current state of the database seems to have yet another problem so I am not sure against which database dump I should test.

Optimize comment lookup for group_result by prefetch

---

lib/OpenQA/Utils.pm
t/16-utils-runcmd.t

Delete unused testresultdir and data_name subs

---

downloads.html

Fixes https://progress.opensuse.org/issues/9436

Delete obsolete OBS devel link

---

lib/OpenQA/Scheduler.pm
lib/OpenQA/WebAPI/Controller/API/V1/Job.pm

My refactoring caught uncovered code ;(

Fix scheduling of jobs

---

lib/OpenQA/Schema.pm

Restore original umask after DB deployment

---

lib/OpenQA/Schema/Result/Jobs.pm

This crash leaves me very unsure about how well this whole thing was
tested ;(

Fix crash by passing the right argument type to enqueue

---

lib/OpenQA/WebAPI/Controller/Main.pm
t/ui/14-dashboard.t

This reverts commit ec0a4b0c6e2e168146c2f94453537d22b7da4c8c.

Revert "Truncate the number of jobs parsed to prevent overload"

---

lib/OpenQA/WebAPI.pm

- need to ensure OpenQA::Schema::deployment_check($schema) runs as soon
as possible to avoid other part trying to write to non-existing db (ie.
Auditing plugin writing startup event)
- move some other log and tmp dir related stuff to the front too
- this is needed before I can safely push openQA package with removed db handling

Reorder init code to the start of startup subroutine

---

lib/OpenQA/WebAPI/Controller/Test.pm
templates/test/result.html.ep

Show the category headers in the test results table.
Similar to the test list on the running page.

Show test categories in test result

---

cpanfile

- according to http://cpansearch.perl.org/src/JHTHORSEN/Mojolicious-Plugin-AssetPack-1.00/Changes
v1.0 is rewrite with some API changes, lets wait for a while before switch

Use v0.69 of AssetPack mojo plugin

---

docs/Networking.asciidoc

- provided ifcfg-tap0 config for wicked (works in leap and tumbleweed)
- added info about openvswitch service file modification (fixed in tumbleweed already, needed for leap)

Changes in Networking documentation

---

lib/OpenQA/WebAPI/Controller/Test.pm
t/ui/16-tests_previous_results.t
templates/test/result.html.ep

the machine is part of the scenario

Fix the previous results

---

lib/OpenQA/WebAPI/Plugin/Helpers.pm
public/stylesheets/overview.scss
templates/test/overview.html.ep
templates/test/tr_job_result_failedmodules.html.ep

the table is now a fixed layout and every cell is limited to 25 characters

Apply some CSS insanity to tidy up the overview page

---

lib/OpenQA/Schema/Result/Jobs.pm

GRU: Do not crash if a job has no group

---

docs/Installing.asciidoc

Fixed typo in line 128. Added a line to resolve write permission error while trying to write in client.conf

Updates install.asciidoc

---

Makefile

related to [issue#11946](https://progress.opensuse.org/issues/11946)

Create iso, hdd, repo and other subdirs under factory

---

public/javascripts/admintable.js
t/ui/13-admin.t

HTML escape form data before showing

---

t/ui/12-needle-edit.t
t/ui/13-admin.t

t: Use helper function to wait for ajax

---

templates/test/result.html.ep

This fixes some small ui issue.

Add css class no_hover to all /thumbs/

---

assets/javascripts/needlediff.js
assets/javascripts/shapes.js

Prototype for https://github.com/os-autoinst/openQA/issues/707 - not really finished, e.g. much too slow in firefox

Color needle diff differently

---

dbicdh/MySQL/deploy/38/001-auto-__VERSION.sql
dbicdh/MySQL/deploy/38/001-auto.sql
dbicdh/MySQL/upgrade/37-38/001-auto.sql
dbicdh/PostgreSQL/deploy/38/001-auto-__VERSION.sql
dbicdh/PostgreSQL/deploy/38/001-auto.sql
dbicdh/PostgreSQL/upgrade/37-38/001-auto.sql
dbicdh/SQLite/deploy/38/001-auto-__VERSION.sql
dbicdh/SQLite/deploy/38/001-auto.sql
dbicdh/SQLite/upgrade/37-38/001-auto.sql
dbicdh/_source/deploy/38/001-auto-__VERSION.yml
dbicdh/_source/deploy/38/001-auto.yml
lib/OpenQA/Scheduler/Scheduler.pm
lib/OpenQA/Schema.pm
lib/OpenQA/Schema/Result/JobSettings.pm
lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/Schema/Result/Workers.pm
lib/OpenQA/WebAPI/Controller/API/V1/Worker.pm
lib/OpenQA/WebAPI/Controller/Running.pm
t/fixtures/01-jobs.pl
t/fixtures/02-workers.pl

And add unique constraint to the job_id in the workers table (which is
much smaller)

Move Jobs::worker_id to Worker::job_id

---

assets/javascripts/result_preview.js
assets/stylesheets/openqa.scss
assets/stylesheets/result_preview.css

Animate preview show/hide 

---

assets/javascripts/needlediff.js
assets/javascripts/openqa.js
assets/javascripts/result_preview.js
lib/OpenQA/WebAPI/Controller/Step.pm
templates/step/viewimg.html.ep
templates/test/result.html.ep

The previous way turned out too be fragile (at least in phantomjs 1.9.8
as used in Travis)

Refactor the result_preview relation with needle diff

---

dbicdh/MySQL/upgrade/37-38/001-auto.sql
dbicdh/MySQL/upgrade/37-38/003-drop_worker_from_jobs.sql
dbicdh/PostgreSQL/upgrade/37-38/001-auto.sql
dbicdh/PostgreSQL/upgrade/37-38/003-drop_worker_from_jobs.sql
dbicdh/SQLite/upgrade/37-38/001-auto.sql
dbicdh/SQLite/upgrade/37-38/003-drop_worker_from_jobs.sql
dbicdh/_common/upgrade/37-38/002-migrate-jobs.pl

- 1. create the job_id column in workers table
- 2. copy jobs::worker_id into workers::job_id
- 3. remove jobs::worker_id

Split the 37-38 schema upgrade

---

lib/OpenQA/Schema/Result/Jobs.pm

I don't understand the underlying problem and it doesn't happen in testing,
so I want to see more details in the log

Replace 'seen called on undef' warning with something explicit

---

t/05-scheduler-dependencies.t

test for https://github.com/os-autoinst/openQA/pull/694

test for _PARALLEL_JOBS as comma separated string

---

templates/admin/workers/index.html.ep

Fixes perl warning on more recent version.

Prevent experimental use of keys on scalar

---

lib/OpenQA/WebAPI/Controller/Step.pm

one is always called and one only whenever we want a result to avoid
getting a 404 when receiving the module source (issue  12392)

Step controller: split init into 2 functions

---

Makefile

Fix coverage skipping files with 't/' in path

---

assets/javascripts/running.js
assets/stylesheets/openqa.scss
assets/stylesheets/result_preview.scss

Live view: simplify drawImage

---

lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Controller/ApiKey.pm
templates/api_key/index.html.ep

fixing https://github.com/os-autoinst/openQA/issues/770

Give the user better hints on what we expect for the expiry date

---

docker/openqa_data/Dockerfile
docker/webui/Dockerfile
docker/webui/run_openqa.sh
docker/worker/Dockerfile

Tested, it can be built and worked without problem.

Upgrade to Leap 42.1, and fix apache2 starting problem

---

assets/javascripts/running.js
lib/OpenQA/Schema/Result/JobModules.pm
lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/Worker.pm
lib/OpenQA/Worker/Commands.pm
lib/OpenQA/Worker/Engines/isotovideo.pm
lib/OpenQA/Worker/Jobs.pm
t/17-build_tagging.t
t/api/02-iso.t
templates/layouts/bootstrap.html.ep

This depends on https://github.com/os-autoinst/os-autoinst/pull/524

Rework interactive mode

---

lib/OpenQA/Scheduler/Scheduler.pm
lib/OpenQA/Schema/Result/Jobs.pm
t/05-scheduler-cancel.t

Also reset all the running modules of it to none
https://progress.opensuse.org/issues/12238

Always set a t_finished to now if the job has a final state

---

dbicdh/MySQL/deploy/40/001-auto-__VERSION.sql
dbicdh/MySQL/deploy/40/001-auto.sql
dbicdh/MySQL/upgrade/39-40/001-auto.sql
dbicdh/PostgreSQL/deploy/40/001-auto-__VERSION.sql
dbicdh/PostgreSQL/deploy/40/001-auto.sql
dbicdh/PostgreSQL/upgrade/39-40/001-auto.sql
dbicdh/SQLite/deploy/40/001-auto-__VERSION.sql
dbicdh/SQLite/deploy/40/001-auto.sql
dbicdh/SQLite/upgrade/39-40/001-auto.sql
dbicdh/_common/upgrade/39-40/002-set-finished.pl
dbicdh/_source/deploy/40/001-auto-__VERSION.yml
dbicdh/_source/deploy/40/001-auto.yml
lib/OpenQA/Schema.pm
lib/OpenQA/WebAPI/Controller/Test.pm
t/ui/01-list.t

And migrate the finished jobs without finish time to set t_created (which
used to be the previous "testtime" we displayed

Sort the finished jobs by their finished time

---

lib/OpenQA/Test/Case.pm
t/ui/05-auth.t
t/ui/07-file.t
t/ui/10-tests_overview.t
t/ui/16-tests_previous_results.t

- squish function was removed from Mojo7 in commit https://github.com/kraih/mojo/commit/3e1051a7822331cf03e98db3274aa8b5e89698d0

Add custom whitespace squish

---

assets/javascripts/openqa.js
assets/javascripts/running.js
assets/javascripts/test_result.js
lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Controller/Running.pm
lib/OpenQA/WebAPI/Controller/Test.pm
templates/step/moduleslist.html.ep

Update the `#details` view of the test result page while the test is running when a module is finished.

Refresh running modules

---

assets/stylesheets/openqa.scss
dbicdh/MySQL/deploy/41/001-auto-__VERSION.sql
dbicdh/MySQL/deploy/41/001-auto.sql
dbicdh/MySQL/upgrade/40-41/002-auto.sql
dbicdh/PostgreSQL/deploy/41/001-auto-__VERSION.sql
dbicdh/PostgreSQL/deploy/41/001-auto.sql
dbicdh/PostgreSQL/upgrade/40-41/002-auto.sql
dbicdh/SQLite/deploy/41/001-auto-__VERSION.sql
dbicdh/SQLite/deploy/41/001-auto.sql
dbicdh/SQLite/upgrade/40-41/002-auto.sql
dbicdh/_common/upgrade/40-41/001-set-softfails.pl
dbicdh/_source/deploy/41/001-auto-__VERSION.yml
dbicdh/_source/deploy/41/001-auto.yml
lib/OpenQA/Schema.pm
lib/OpenQA/Schema/Result/JobModules.pm
lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
lib/OpenQA/WebAPI/Controller/Main.pm
lib/OpenQA/WebAPI/Controller/Test.pm
lib/OpenQA/WebAPI/Plugin/Helpers.pm
t/api/04-jobs.t
t/fixtures/01-jobs.pl
t/fixtures/05-job_modules.pl
t/ui/01-list.t
t/ui/10-tests_overview.t
t/ui/16-tests_previous_results.t
t/ui/19-tests-links.t
templates/test/overview.html.ep

So far we had plenty of places that calculated a different result for
those.

Make softfailed a proper final result

---

profiles/apparmor.d/usr.share.openqa.script.worker

apparmor: Add missing /usr/lib/git/git

---

assets/stylesheets/openqa.scss
templates/test/infopanel.html.ep

Make softfailed tests show the right colour

---

dbicdh/PostgreSQL/deploy/42/001-auto-__VERSION.sql
dbicdh/PostgreSQL/deploy/42/001-auto.sql
dbicdh/PostgreSQL/upgrade/41-42/001-auto.sql
dbicdh/SQLite/deploy/42/001-auto-__VERSION.sql
dbicdh/SQLite/deploy/42/001-auto.sql
dbicdh/SQLite/upgrade/41-42/001-auto.sql
dbicdh/_common/upgrade/41-42/002-change-overall-softfailed.pl
dbicdh/_source/deploy/42/001-auto-__VERSION.yml
dbicdh/_source/deploy/42/001-auto.yml
lib/OpenQA/Schema.pm
lib/OpenQA/Schema/Result/Jobs.pm
t/10-jobs.t

This way failed modules have at least *some* significance

Make non-important failures at least a general softfail

---

assets/javascripts/comments.js
assets/stylesheets/comments.css
lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Controller/API/V1.pm
lib/OpenQA/WebAPI/Controller/API/V1/Comment.pm
lib/OpenQA/WebAPI/Controller/Main.pm
lib/OpenQA/WebAPI/Controller/Test.pm
t/api/09-comments.t
t/fixtures/01-jobs.pl
t/ui/15-comments.t
templates/comments/comment_row.html.ep
templates/main/group_overview.html.ep
templates/test/comments.html.ep

Allows reading, adding, updating and deletion of comments via V1 API.

Add V1 API for comments

---

t/ui/12-needle-edit.t

In before the test t/ui/12-needle-edit.t would fail othen but not every time
depending on the environment. With this change the test passes consistently.
Conducted 40 runs for verification.

t: 12-needle-edit.t: Try to find overwrite warning more often (poo#12980)

---

assets/javascripts/needleeditor.js
templates/step/edit.html.ep

Should fix: https://progress.opensuse.org/issues/11840
I'm currently still figuring out how to test this.
BTW: Also fixed label which was referencing by name (must reference by ID).

Fix taking over tags from a workaround needle

---

lib/OpenQA/Utils.pm
lib/OpenQA/WebAPI/Controller/Step.pm
t/ui/12-needle-edit.t
templates/step/edit.html.ep

to fix https://progress.opensuse.org/issues/13194

Ignore deleted needles when showing needle editor

---

assets/stylesheets/openqa.scss

Currently test suites slenkins-tests-ceph-control and s390_hsi-l2

Fix admin layout for test suites with long keys

---

assets/javascripts/job_templates.js
assets/stylesheets/openqa.scss

Fix layout of job templates
Before: ![screenshot from 2016-08-23 14-40-28](https://cloud.githubusercontent.com/assets/538604/17892088/cc3b5cc4-693f-11e6-8d5b-ca255bf657f9.png)
After: ![screenshot from 2016-08-23 14-41-41](https://cloud.githubusercontent.com/assets/538604/17892089/cc3f1efe-693f-11e6-9473-a19a6d5a2dbf.png)

Fix jobs templates layout

---

lib/OpenQA/Worker/Jobs.pm

- partially reverted f2547e9bcc0, the boundary calculation has
not changed in new Mojo so this might be still useful.
On my machine I have seen upload failures even with this
patch, but maybe it improves the situation.
Please test.

Re-add boundary hack

---

dbicdh/PostgreSQL/deploy/44/001-auto-__VERSION.sql
dbicdh/PostgreSQL/deploy/44/001-auto.sql
dbicdh/PostgreSQL/upgrade/43-44/001-auto.sql
dbicdh/SQLite/deploy/44/001-auto-__VERSION.sql
dbicdh/SQLite/deploy/44/001-auto.sql
dbicdh/SQLite/upgrade/43-44/001-auto.sql
dbicdh/_source/deploy/44/001-auto-__VERSION.yml
dbicdh/_source/deploy/44/001-auto.yml
lib/OpenQA/Scheduler.pm
lib/OpenQA/Scheduler/Locks.pm
lib/OpenQA/Schema.pm
lib/OpenQA/Schema/Result/Assets.pm
lib/OpenQA/Schema/Result/Comments.pm
lib/OpenQA/Schema/Result/JobLocks.pm
lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Controller/API/V1/Locks.pm
t/04-scheduler.t
t/13-joblocks.t
t/api/02-assets.t

[merge only after #838 and subsequent rebase]
- POST /api/v1/barrier
- creates new barrier, takes mandatory form parameters
- name - name of the barrier
- tasks - number of tasks to wait for
- POST /api/v1/barrier/:barrier_name
- register itself as waiting for the barrier to be released
- DELETE /api/v1/barrier/:barrier_name
- destroy existing barrier

Add lock barriers

---

assets/stylesheets/openqa.scss
lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Controller/Main.pm
lib/OpenQA/WebSockets/Server.pm
lib/OpenQA/Worker/Common.pm
lib/OpenQA/Worker/Engines/isotovideo.pm
lib/OpenQA/Worker/Jobs.pm
lib/db_profiler.pm
t/20-workers-ws.t

This is what I'm currently testing - just to mark my progress :)

Add new job state

---

lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Controller/Main.pm
lib/OpenQA/WebAPI/Controller/Test.pm
t/17-build_tagging.t
t/17-labels_carry_over.t

Comments are handled completely via API now.

Remove old comment code

---

lib/OpenQA/Scheduler/FakeApp.pm

I don't think it's necessary to make it more complicated. But I didn't test this path as I have OPENQA_CONFIG set in my development ;(

Give the scheduler a home

---

lib/OpenQA/Schema/Result/Jobs.pm

Log status update without worker instead of possibly throwing an exception.
Prevents errors like
```
[Thu Sep  8 21:15:50 2016] [16102:error] Can't call method "get_property" on 
an undefined value at /local/openQA/script/../lib/OpenQA/Schema/Result/Jobs.pm 
line 715.
[Thu Sep  8 21:15:50 2016] [16102:debug] 404 Not Found (0.0217s, 46.083/s)
[Thu Sep  8 21:15:55 2016] [16102:error] Can't call method "get_property" on 
an undefined value at /local/openQA/script/../lib/OpenQA/Schema/Result/Jobs.pm 
line 715.
[Thu Sep  8 21:16:01 2016] [16102:error] Can't call method "get_property" on 
an undefined value at /local/openQA/script/../lib/OpenQA/Schema/Result/Jobs.pm 
line 715.
```
Of course this will not fix the actual problem which might be related to this issue: …

Log status update without worker

---

lib/OpenQA/WebSockets/Server.pm

As discussed in #848, it's kind of racy to have the workers
POST a status update every 10 seconds, and have the dead worker
check consider any worker which hasn't updated in the last 10
seconds 'dead'. It doesn't allow for there being a slight delay
in POSTing the update (which can happen if the worker is busy
doing something else when the 10 second timer should trigger
the update) or in the update being actually received and
processed by the server. So let's just change the threshold for
the check to 15 seconds.
While I'm at it, I figured we could make the subroutine names
a bit clearer: since the DB query subroutine isn't really the
ultimate arbiter of whether the worker is truly 'dead' or not
any more, let's call that `_get_stale_worker_jobs` instead of
`_get_dead_worker_jobs` (and …

dead worker check: use 15 secs not 10, better names, comments

---

lib/OpenQA/Scheduler/FakeApp.pm
script/openqa-scheduler
script/openqa-websockets
script/tidy

... so they find the proper /etc and stuff

Give Websockets and Scheduler the home of the webapi

---

lib/OpenQA/Scheduler/FakeApp.pm

Fixing https://progress.opensuse.org/issues/13736

Add more faking to FakeApp - so restarting jobs works again

---

script/openqa-scheduler
script/openqa-websockets

I think this deserves a fairly verbose comment because it's
pretty obscure; I can see us coming back to it in a few months
and wondering why the hell the 'require' is there. Also, if you
break this it's not really incredibly obvious, so someone could
take it out, not see that anything explodes, and think it must
be useless. So let's explain clearly what's going on.

comment the home detection for scheduler/websockets better

---

lib/OpenQA/Schema/Result/Comments.pm
lib/OpenQA/Utils.pm
t/ui/15-comments.t

Related progress issue: poo#11970

Prevent multiple bug refs per comment to yield incorrect URLs

---

lib/OpenQA/WebAPI/Controller/Main.pm
t/ui/14-dashboard.t

Related progress issue: https://progress.opensuse.org/issues/13742
Merge match and group filter parameter

Filter index page

---

lib/OpenQA/WebAPI/Controller/Main.pm
t/ui/14-dashboard.t

Related progress issue: https://progress.opensuse.org/issues/13742

Add 'match' query parameter for index page

---

assets/javascripts/overview.js
t/ui/10-tests_overview.t

Fix https://progress.opensuse.org/issues/13804

Pass encoded URL filter parameter correctly

---

lib/OpenQA/Scheduler.pm
lib/OpenQA/Scheduler/Scheduler.pm
lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
lib/OpenQA/WebAPI/Controller/API/V1/Worker.pm
lib/OpenQA/WebSockets/Server.pm
t/05-scheduler-cancel.t
t/05-scheduler-dependencies.t
t/05-scheduler-restart-and-duplicate.t
t/09-job_clone.t
t/18-fedmsg.t

Trying to fix https://progress.opensuse.org/issues/13684

Reintegrate job duplicate

---

lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/WebAPI/Controller/API/V1/Job.pm

(move the seen call into the controller to avoid duplicate it in 3 places)
Fixing https://progress.opensuse.org/issues/13814

Mark worker alive for all kind of artefacts

---

dbicdh/PostgreSQL/deploy/45/001-auto-__VERSION.sql
dbicdh/PostgreSQL/deploy/45/001-auto.sql
dbicdh/PostgreSQL/upgrade/44-45/001-auto.sql
dbicdh/SQLite/deploy/45/001-auto-__VERSION.sql
dbicdh/SQLite/deploy/45/001-auto.sql
dbicdh/SQLite/upgrade/44-45/001-auto.sql
dbicdh/_source/deploy/45/001-auto-__VERSION.yml
dbicdh/_source/deploy/45/001-auto.yml
lib/OpenQA/Schema.pm
lib/OpenQA/Schema/Result/GruTasks.pm

Fixing https://progress.opensuse.org/issues/13620 and the rest of 13152

Small schema change to add an index

---

lib/OpenQA/WebAPI.pm

https://progress.opensuse.org/issues/13854

Increase session expiration from 1 to 48 hours

---

lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/WebAPI/Controller/Test.pm
lib/OpenQA/WebAPI/Plugin/Helpers.pm
t/ui/16-tests_previous_results.t
templates/test/previous.html.ep

Fix https://progress.opensuse.org/issues/13810

Add scenario params to limit URLs for previous results

---

lib/OpenQA/Schema/Result/Comments.pm
lib/OpenQA/Utils.pm
t/ui/15-comments.t

Fix https://progress.opensuse.org/issues/13878

Handle links to bugs already formatted correctly

---

assets/javascripts/comments.js
assets/javascripts/test_result.js
assets/sass/theme_overwrites.scss
assets/stylesheets/comments.css
t/ui/15-comments.t
templates/comments/comment_row.html.ep

https://progress.opensuse.org/issues/10720

Add anchor links to comments

---

lib/OpenQA/Schema/Result/JobModules.pm
lib/OpenQA/WebAPI.pm

(and reduce the amount of debug output)

Readd the lost name of the thumb_nail route

---

lib/OpenQA/BuildResults.pm
lib/OpenQA/WebAPI/Controller/Main.pm
t/ui/14-dashboard.t
templates/main/group_builds.html.ep

First step to implement meta-groups for products: https://progress.opensuse.org/issues/13742

Refactor computing build results

---

assets/stylesheets/openqa.scss
lib/OpenQA/BuildResults.pm
lib/OpenQA/WebAPI/Plugin/Helpers.pm
t/ui/19-tests-links.t
templates/main/group_builds.html.ep

Implement https://progress.opensuse.org/issues/13910

Show incomplete/skipped bugs, show tooltip on progress bars

---

assets/javascripts/admin_needle.js
lib/OpenQA/WebAPI/Controller/Admin/Needle.pm

- Improve situation of unresponsive needle table:
https://progress.opensuse.org/issues/13196
- Next step is implementing server side paging.
- Also fix indentation in admin_needle.js

Show progress indication in admin needle table

---

assets/javascripts/admin_needle.js

Regression of 5ca5a22864c26cd587f4908529343b9f129866d8 not uncovered by
tests as the test only deletes single needle

Fix deletion of multiple needles at once

---

assets/assetpack.def
assets/javascripts/filter_form.js
assets/javascripts/index.js
assets/javascripts/overview.js
assets/stylesheets/openqa.scss
t/ui/10-tests_overview.t
t/ui/14-dashboard.t
templates/main/index.html.ep

- As proposed in: https://progress.opensuse.org/issues/13906
- Refactor code for filter form in test overview to share
common code
- Don't prevent empty URL query parameters anymore since this is
not bad behaviour but the hacks around it were bad

Add filter form for index page

---

assets/javascripts/tests.js

Apply the same spacing for every result type.

Fix test result info spacing

---

assets/assetpack.def
assets/javascripts/admin_groups.js
assets/stylesheets/openqa.scss
lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Controller/API/V1/JobGroup.pm
lib/OpenQA/WebAPI/Controller/Admin/JobGroup.pm
t/api/10-jobgroups.t
t/ui/13-admin.t
templates/admin/group/index.html.ep

Required for further development of parent groups

Complete API for job groups

---

lib/OpenQA/Utils.pm
t/ui/15-comments.t

This is what OBS does and this is what most old farts expect

Go to bugzilla.suse.com also for bnc#

---

assets/javascripts/admin_needle.js
assets/stylesheets/openqa.scss
lib/OpenQA/Schema/Result/Needles.pm
lib/OpenQA/Utils.pm
lib/OpenQA/WebAPI/Controller/Admin/Needle.pm
t/16-utils-runcmd.t
t/ui/21-admin-needles.t
templates/admin/needle/index.html.ep

Fix https://progress.opensuse.org/issues/11796

Improve error handling when deleting needle

---

lib/OpenQA/Schema/Result/Needles.pm
t/ui/21-admin-needles.t

Should fix issue mentioned in https://github.com/os-autoinst/openQA/pull/939#issuecomment-254601927
I had already tests for the concerning method itself but not for the correct invocation. Here's just the quick fix so far. I could also add the missing test but it would be a little bit more complex.

Fix needle deletion via Git

---

lib/OpenQA/WebAPI.pm

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/os-autoinst/openqa/947)

WebAPI: Delete comments stating the obvious + delete unused routes

---

lib/OpenQA/Schema/Result/Jobs.pm

This is a follow-up to baac24bc; I found another place where
we're checking for asset existence.

use locate_asset in register_assets_from_settings

---

assets/assetpack.def
assets/javascripts/test_result.js
assets/stylesheets/openqa.scss
lib/OpenQA/WebAPI/Controller/Step.pm
lib/OpenQA/WebAPI/Plugin/Helpers.pm
t/ui/12-needle-edit.t
t/ui/18-tests-details.t
templates/step/viewimg.html.ep

* Use an icon for detailed needles info, too
* List the needle tags that openqa was looking for
* Provide 'create new needle' on viewimg as icon
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/os-autoinst/openqa/944)

List needle tags + step icons

---

lib/OpenQA/WebAPI/Controller/Main.pm

Stash a scalar variable not a function

Fix job group overview without description

---

lib/OpenQA/Schema/Result/Jobs.pm

0b78fc5f broke artefact uploading on job cancellation. Because
the job `cancel()` method now frees the worker (so far as the
schema is concerned) immediately after telling the worker to
cancel the job, by the time the worker process reaches the
artefact upload bits of `_stop_job()`, the schema job instance
has no worker, and when the worker process tries to upload the
artefacts, the schema job instance `create_artefact()` method
throws a 404 because so far as it knows, it no longer has a
worker.
The change was intended to mitigate a problem caused by the
dbus deadlock issue, where the server never actually handled
the `set_done` API call the worker process sends at the end
of `_stop_job`, so the worker was never freed - but as the dbus
deadlock issue has now been addressed, we shouldn't …

Don't free worker before artefacts are uploaded (POO #14378)

---

assets/javascripts/needleeditor.js
lib/OpenQA/WebAPI/Controller/Step.pm
t/ui/12-needle-edit.t

Improve minor things around the needle editor and overriding tests
Actually I'm trying to solve https://progress.opensuse.org/issues/14358 but it turns out there are already tests for needle overriding so the source of the error is more likely something else.

Improve override needle test

---

assets/javascripts/admintable.js
assets/stylesheets/openqa.scss
t/ui/13-admin.t

Fix https://progress.opensuse.org/issues/14342

Use textareas in test suite editor

---

docs/WritingTests.asciidoc

Added assert_script_run description and modified the default timeout for script_run since it is 30s, not 9s.

Added assert_script_run description

---

assets/javascripts/index.js
assets/stylesheets/openqa.scss
assets/stylesheets/overview.scss
lib/OpenQA/BuildResults.pm
lib/OpenQA/WebAPI/Controller/Main.pm
lib/OpenQA/WebAPI/Plugin/Helpers.pm
t/17-build_tagging.t
templates/comments/add_comment_form_groups.html.ep
templates/main/index.html.ep
templates/step/edit.html.ep

Fix https://progress.opensuse.org/issues/13844

Show tags on index page

---

lib/OpenQA/Utils.pm
lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Plugin/Helpers.pm
t/ui/22-job_group_order.t
templates/layouts/bootstrap.html.ep

We want some groups at the top and the dead groups parent at the end

Intersect the ordering of parents and job groups

---

docs/Installing.asciidoc

README: Update Tumbleweed repo

---

lib/OpenQA/Schema/Result/JobGroups.pm
lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Controller/API/V1/JobGroup.pm
script/client
t/17-build_tagging.t
t/api/10-jobgroups.t
t/fixtures/01-jobs.pl
t/testresults/00099961-opensuse-13.1-DVD-x86_64-Build0091-kde/autoinst-log.txt

Important builds and non-important builds have independent expiration
times

Calculate expired jobs and allow to query them

---

lib/OpenQA/Schema/Result/Assets.pm

And warn about assets that are older than 24 days

Remove assets that have been registered 14 days ago

---

assets/javascripts/openqa.js
assets/stylesheets/openqa.scss
lib/OpenQA/BuildResults.pm
lib/OpenQA/Schema/Result/JobGroupParents.pm
lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Controller/Main.pm
t/api/04-jobs.t
t/ui/14-dashboard.t
templates/admin/group/parent_group_property_editor.html.ep
templates/admin/job_template/index.html.ep
templates/main/build_progressbar.html.ep
templates/main/group_builds.html.ep
templates/main/group_overview.html.ep
templates/main/index.html.ep
templates/main/more_builds.html.ep
templates/main/parent_group_overview.html.ep

Updated version of https://github.com/os-autoinst/openQA/pull/994
@coolo Removed the icons
I adapted the existing tests but still need to write tests for the new features.

WIP: Show parents on index and parent overview

---

templates/branding/openSUSE/external_reporting.html.ep

Fixes https://progress.opensuse.org/issues/14830

external_reporting: Fix duplicate bugzilla product entry

---

lib/OpenQA/BuildResults.pm
t/22-dashboard.t
t/ui/14-dashboard.t

Implements parts of https://progress.opensuse.org/issues/14814

Add test for parents on index page and parent group overview

---

lib/OpenQA/Schema/Result/JobGroupParents.pm
lib/OpenQA/WebAPI/Controller/Main.pm
t/22-dashboard.t

So build tags of groups inside parents are shown again

Show build tags on parent-level

---

lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/Schema/Result/Workers.pm
lib/OpenQA/Schema/ResultSet/Jobs.pm
lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
lib/OpenQA/WebAPI/Controller/Admin/Needle.pm
lib/OpenQA/WebAPI/Controller/File.pm
lib/OpenQA/WebAPI/Plugin/Helpers.pm
script/initdb
script/upgradedb
t/18-fedmsg.t

There were a few spots left from #1017 that still needed manual formatting
fixes. And since the method `list` in
`OpenQA::WebAPI::Controller::API::V1::JobTemplate` and the helper
`current_user` in `OpenQA::WebAPI::Plugin::Helpers` were affected by this
anyway, i've cleaned them up as well.
@okurz I think you were interested in how i would clean up the `list` method. 😉

Fix a few formatting mistakes and remove repetitive method calls

---

lib/OpenQA/BuildResults.pm
t/22-dashboard.t
templates/main/group_builds.html.ep

https://progress.opensuse.org/issues/14880

Fix URLs in dashboard when version/distri differ

---

lib/OpenQA/BuildResults.pm
t/22-dashboard.t

Fix https://progress.opensuse.org/issues/14934#change-32398 (without optional tasks)

Show review badge despite unreviewed softfails

---

t/ui/01-list.t
t/ui/PhantomTest.pm

For now we used two ways to setup a test database, either an empty one with
custom additions of entries tailored for a test or based on our fixtures which
have a good common set. Tests based on phantomjs so far always relied on the
database fixtures. The problem with that is by adding more entries to the
fixtures many tests need to be adapted, conflicting corner cases can not be
represented very well, the fixtures maintenance effort increases and the tests
become slower.
This commit provides a way to pass a custom hook for database creation
allowing a customization of database entries as necessary for the specific
tests, be it based on a clean database where one just wants to add what is
necessary or creating a database based on the fixtures and tailoring it for
the test in question. …

Add test database customization hook

---

t/22-dashboard.t
t/ui/14-dashboard-parents.t

Still about https://progress.opensuse.org/issues/14814

Implement remaining tests for dashboard with parents

---

lib/OpenQA/Utils.pm
t/testresults/00099/00099946-opensuse-13.1-DVD-i586-Build0091-textmode/logpackages-6.txt
t/ui/18-tests-details.t
templates/step/viewtext.html.ep

Fix https://progress.opensuse.org/issues/14544

Render href in text thumbnails (test results)

---

docs/WritingTests.asciidoc

Cover switching to another console and using a serial terminal

Add docs for using text consoles and serial term

---

dbicdh/PostgreSQL/deploy/49/001-auto-__VERSION.sql
dbicdh/PostgreSQL/deploy/49/001-auto.sql
dbicdh/PostgreSQL/upgrade/48-49/001-auto.sql
dbicdh/SQLite/deploy/49/001-auto-__VERSION.sql
dbicdh/SQLite/deploy/49/001-auto.sql
dbicdh/SQLite/upgrade/48-49/001-auto.sql
dbicdh/_common/upgrade/47-48/03-move-resultdirs.pl
dbicdh/_source/deploy/49/001-auto-__VERSION.yml
dbicdh/_source/deploy/49/001-auto.yml
lib/OpenQA/Schema.pm
lib/OpenQA/Schema/Result/JobGroups.pm
lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Controller/API/V1/Iso.pm
lib/OpenQA/WebAPI/Controller/API/V1/JobGroup.pm
t/14-grutasks.t
t/17-build_tagging.t
templates/admin/group/group_property_editor.html.ep

using `keep...` columns of job group

Clean logs and job results

---

templates/branding/openSUSE/external_reporting.html.ep

See https://progress.opensuse.org/issues/15018#change-32718

Fix report link for FLAVOR 'Server-DVD-Incidents'

---

docs/GettingStarted.asciidoc

Also add  basics about job groups because
cleanup properties work on job-group-level

Add documentation about cleanup properties

---

docs/GettingStarted.asciidoc

Not sure whether the provided description is correct.

Add documentation for softfailure result

---

script/client

this is useful when trying to upload some binary data like assets using
client script

Allow client script to post form data

---

lib/OpenQA/WebAPI.pm
script/client
t/ui/05-auth.t
templates/admin/api_help.html.ep
templates/layouts/bootstrap.html.ep

Add help for all options, better examples and a good introduction text.

client: Update help

---

lib/OpenQA/WebAPI/Plugin/Fedmsg.pm
t/18-fedmsg.t

Now I got around to checking on the comment events that were
added to the Fedmsg plugin, there are several problems. This
should fix most of them.
The modname for the comment events was entirely wrong, because
the modifications done for job events weren't being done for
comment events, so we got a modname with the useless 'openqa'
on the front and still with underscore separators instead of
dots. As a bonus, we now replace *all* underscores with dots,
not just the first (so `job_update_result` was actually also
broken before, I just didn't notice because we never much used
it).
We would never actually emit a message for comment deletion,
because `on_comment_event` tries to find the comment and bails
if it can't; obviously it won't find a comment that was just
deleted. For now, just send …

Fix various issues with fedmsg comment events

---

assets/javascripts/running.js
lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Controller/Running.pm
lib/OpenQA/WebAPI/Controller/Test.pm
lib/OpenQA/Worker/Jobs.pm
templates/test/live.html.ep

This is my initial attempt at adding serial console/terminal output to the live view in the same vein as Travis CI's output although much more simple.
Requires: https://github.com/os-autoinst/os-autoinst/pull/644
Feature request: https://progress.opensuse.org/issues/14690

Add serial terminal output to live view

---

t/18-fedmsg.t

Travis didn't complain about it when merging hence I'll fix the broken test now.

Fix fedmsg test

---

script/fetchneedles

fetchneedles: Correct to minimum depth of 1

---

assets/javascripts/job_templates.js

See https://progress.opensuse.org/issues/15190

Fix misleading allingment in job template editor

---

lib/OpenQA/Worker/Jobs.pm

Show more helpful error message instead

Worker/Jobs.pm: Prevent use of uninitialized value

---

lib/OpenQA/WebSockets/Server.pm

The main goal is to detect dead workers purely on their websocket activity,
but instead of writing everything into the database all the time, just
keep the last_seen timestamp in a local hash
This is once again deep in not covered code, but I tested this heavily for
performance on an unnamed instance with > 100 workers

Rework websocket server

---

script/client

client: Respect --json also in case of an error

---

lib/OpenQA/Client.pm
t/api/01-workers.t
t/api/03-auth.t

So fix for https://progress.opensuse.org/issues/14898 has effect when connecting to other hosts than localhost

client: Set 'Accept'-header in any case

---

lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
lib/OpenQA/WebAPI/Controller/API/V1/Worker.pm
lib/OpenQA/Worker/Common.pm
lib/OpenQA/Worker/Jobs.pm

Fix https://progress.opensuse.org/issues/13952

Fix dead worker warnings

---

dbicdh/PostgreSQL/deploy/51/001-auto-__VERSION.sql
dbicdh/PostgreSQL/deploy/51/001-auto.sql
dbicdh/PostgreSQL/upgrade/50-51/001-auto.sql
dbicdh/SQLite/deploy/51/001-auto-__VERSION.sql
dbicdh/SQLite/deploy/51/001-auto.sql
dbicdh/SQLite/upgrade/50-51/001-auto.sql
dbicdh/_common/upgrade/50-51/01-add-system-user.pl
dbicdh/_source/deploy/51/001-auto-__VERSION.yml
dbicdh/_source/deploy/51/001-auto.yml
lib/OpenQA/Scheduler/Scheduler.pm
lib/OpenQA/Schema.pm
lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/Schema/Result/Workers.pm
lib/OpenQA/WebAPI/Controller/Test.pm
t/04-scheduler.t
t/deploy.t
t/ui/14-dashboard-parents.t
t/ui/18-tests-details.t
templates/test/infopanel.html.ep
templates/test/result.html.ep

See https://progress.opensuse.org/issues/6564

Show worker also when job already done

---

profiles/apparmor.d/usr.share.openqa.script.worker

the important one is `pwd` for isotovideo.

Update worker apparmor file from production worker log

---

lib/OpenQA/Utils.pm
t/ui/15-comments.t

Note, I'm sending a PR to run the tests as I'm not set up to run the Selenium tests. I'm not 100% sure about the tests, so I might need to push this a few times.

Add brc (Red Hat Bugzilla) and bgo (GNOME Bugzilla) labels

---

t/api/03-auth.t

t: Add simple authentication test for no key/secret

---

assets/javascripts/running.js
lib/OpenQA/Scheduler/Scheduler.pm
lib/OpenQA/Schema/Result/Workers.pm
lib/OpenQA/WebAPI/Controller/API/V1/Command.pm
lib/OpenQA/WebAPI/Controller/API/V1/Worker.pm
lib/OpenQA/WebAPI/Controller/Running.pm
lib/OpenQA/WebSockets/Server.pm
templates/test/live.html.ep

* Show stop button in interactive mode (again)
* Remove spinner
* Builds on top of https://github.com/os-autoinst/openQA/pull/1082
* Still experimental / allows "exploring" further bugs

Improve buttons in interactive mode

---

lib/OpenQA/WebAPI/Controller/Admin/Needle.pm

This regression has been introduced with commit 2440dc9
And yes, seems like a test for this is missing.

Fix sorting of needle table

---

assets/stylesheets/openqa.scss
lib/OpenQA/WebAPI/Controller/Admin/AuditLog.pm
lib/OpenQA/WebAPI/Plugin/Helpers.pm
t/ui/23-audit-log.t
templates/admin/audit_log/index.html.ep

See particular commit messages. I could add further tests as it seems the present tests are not sufficient.
@aaannz I hope you're ok with the changes.
BTW: When adding further server side data tables we should refactor the code for sorting and paging.

Fix audit table

---

_includes/api.html
docs/api/header.asciidoc
documentation.html

Update to gh-pages so that we can have the documentation published within the website
Please see PR #1106

Add features needed for documentation auto-generation PR #1106

---

docker/openqa_data/data.template/conf/openqa.ini
etc/openqa/openqa.ini
lib/OpenQA/ServerStartup.pm
lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Controller/Session.pm
t/config.t

It's been a while that we droped the idea of authenitifcation by IP

Remove uncovered as unsed code from session

---

Makefile

These are scripts internal to git management

Do not install documentation scripts

---

assets/assetpack.def
assets/javascripts/admin_worker.js
lib/OpenQA/Schema/Result/Workers.pm
lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Controller/Admin/Workers.pm
t/ui/15-admin-workers.t
templates/admin/workers/index.html.ep
templates/admin/workers/show.html.ep

See https://progress.opensuse.org/issues/13144

Worker history

---

lib/OpenQA/WebAPI/Plugin/AMQP.pm

Also log actual channel error msg

AMQP: Log one message per error - not two

---

docker/testing/Dockerfile
docker/testing/README.md
docker/testing/perlw
docker/testing/test.sh

I developed this as mean to test the full-stack test without fearing
about my system - and being closer to travis-ci environment

Adding Dockerfile to build a testing container

---

lib/OpenQA/Worker/Common.pm

This is decoupling the WS logic from apache - the webui will redirect
to a different port (the websocket service), but the worker didn't
follow this advise as apache did it so far.

Have the worker follow WS redirects

---

lib/OpenQA/Schema/Result/Comments.pm
lib/OpenQA/Utils.pm
lib/OpenQA/WebAPI/Controller/Test.pm
t/16-utils.t
t/ui/15-comments.t
templates/test/tr_job_result_details.html.ep

See https://progress.opensuse.org/issues/11970

Support multiple bugrefs per job

---

.travis.yml
Makefile
codecov.yml
docker/testing/Dockerfile

Merely an experiment for now - but I'm tired of waiting

Split UI tests from !UI tests

---

lib/OpenQA/Schema.pm

On closer inspection of the `flock` documentation, I find that
we must open the lock file with write intent to make sure we
can get an exclusive lock (`LOCK_EX`); it *may* work if the
file is only open with read intent, but only if a native flock
function is being used (rather than emulation via lockf or
fcntl).
It's really *difficult*, though, to come up with a location
which will always be the same for the various openQA server
processes and which we can be sure they will all be able to
write to. In a typical deployment they should be able to write
the db config file, but there's no real *need* for this, it
*could* be read-only for them.
So to do our best, we try to open the file in append mode, and
if that doesn't work, open it in read mode and *try* to get an
exclusive lock on it. …

Improve database deployment locking

---

.travis.yml
Makefile

This reverts commit bca568d88fdd81076fbdab3b396a2405efb4b458. I still
don't understand codecov fully, sorry for the mess

Revert "Don't pass filters to cover -report (#1131)"

---

lib/db_helpers.pm
t/rand.t

Merely an experiment how to tweak uncoverable branches

Rework db_helpers to gain 100% coverage

---

Makefile
t/16-utils.t
t/full-stack.t
t/testrules.yml

Parallel jobs

---

script/client

See https://progress.opensuse.org/issues/15494

client: Support sending JSON data

---

cpanfile
lib/OpenQA/BuildResults.pm
lib/OpenQA/WebAPI/Controller/Main.pm
t/22-dashboard.t
templates/main/group_builds.html.ep
templates/main/group_overview.html.ep
templates/main/index.html.ep
templates/main/parent_group_overview.html.ep

* Build on top of https://github.com/os-autoinst/openQA/pull/1135
* Requires Perl module Sort::Versions

Sort build versions correctly

---

assets/javascripts/tests.js
t/ui/01-list.t

It is about this feature
First step to implement
* https://progress.opensuse.org/issues/15846
* https://progress.opensuse.org/issues/15850

Improve job relation icons

---

cpanfile

CGI
Cache::Cache
INET6 (at least not directly)

Cleanup cpanfiles

---

t/full-stack.t

In case there are problems with the setup, the full-stack test needs
to fail. So far it just exited and the coverage would drop. This is
not proper reporting

Make sure the full-stack test fails early

---

assets/javascripts/running.js
assets/javascripts/test_result.js
codecov.yml
t/full-stack.t
t/ui/PhantomTest.pm

do not rely on brand new endsWith - it was only added in 2015

Fix javascript error on phantomjs

---

lib/OpenQA/Schema/Result/Jobs.pm
t/05-scheduler-restart-and-duplicate.t
t/api/04-jobs.t

See https://progress.opensuse.org/issues/15998

Return original job ID via API

---

assets/stylesheets/openqa.scss
t/ui/13-admin.t
t/ui/15-comments.t
templates/admin/group/parent_group_property_editor.html.ep
templates/admin/job_template/index.html.ep
templates/main/group_overview.html.ep
templates/main/parent_group_overview.html.ep

See https://progress.opensuse.org/issues/16006

Fix corner buttons

---

assets/javascripts/needleeditor.js
t/ui/12-needle-edit.t

See https://progress.opensuse.org/issues/14770

needle editor: Validate needles/tags in JavaScript

---

cpanfile

Avoid version 7.19 of Mojolicious

Change the Mojolicious version requirements

---

lib/OpenQA/Utils.pm
lib/OpenQA/WebAPI/Controller/File.pm
t/ui/12-needle-edit.t

See https://progress.opensuse.org/issues/16120

Fix needle path check

---

.gitignore
t/full-stack.t

- this requires https://github.com/os-autoinst/os-autoinst/pull/709 so the fullstack test fails at the moment. Once merged, travis run should pass after restart.

Switch test distro from pitux to tinycore

---

assets/javascripts/admin_worker.js
assets/javascripts/tests.js
lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/WebAPI/Controller/Admin/Workers.pm
lib/OpenQA/WebAPI/Controller/Test.pm
t/ui/15-admin-workers.t
templates/admin/workers/show.html.ep

* don't show job ID
* allow retriggering jobs
See https://progress.opensuse.org/issues/16316

Enhance jobs list in worker page

---

lib/OpenQA/BuildResults.pm
lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/WebAPI/Controller/Test.pm
lib/OpenQA/WebAPI/Plugin/Helpers.pm
t/10-tests_overview.t
templates/test/overview.html.ep

See https://progress.opensuse.org/issues/16124

Improve 'TODO' filter

---

t/05-scheduler-dependencies.t

* Remove out-commented code
* Improve test helper _job_create
* Initialize settings in a more compact way
See https://progress.opensuse.org/issues/16394
There are more things to improve, but this is a start.

Refactor test for scheduler dependencies

---

docs/GettingStarted.asciidoc

We changed the Fedora repos around a bit recently, update the
docs for this. We should have a PR to update the Docker bits
coming soonish.

Update GettingStarted for some Fedora repo changes

---

docs/Installing.asciidoc

https://w3.nue.suse.com/~okurz/openQA_docs/Installing.html#_filesystem_layout

docs: Correct asciidoc syntax for pool instance table

---

assets/javascripts/needleeditor.js
assets/stylesheets/openqa.scss
templates/step/edit.html.ep

See commit descriptions and #1227

Fix details in needle editor

---

assets/javascripts/needleeditor.js
t/ui/12-needle-edit.t

See https://progress.opensuse.org/issues/17666

Fix needle editor when taking matches is disabled

---

assets/javascripts/needleeditor.js
templates/step/edit.html.ep

Minor adjustments in needle editor

---

lib/OpenQA/ServerStartup.pm
lib/OpenQA/WebAPI.pm
t/basic.t

issue https://progress.opensuse.org/issues/17664

Harden loading of auth modules with whitespaces

---

script/clone_job.pl

Fixes [poo#17182](https://progress.opensuse.org/issues/17182)

Follow redirects for clone_job requests (eg to ssl)

---

lib/OpenQA/Schema/Result/Jobs.pm
t/full-stack.t

see https://progress.opensuse.org/issues/17218

Ensure uploaded assets have correct perms

---

lib/OpenQA/Worker/Common.pm

see https://progress.opensuse.org/issues/17842

Change $testpoolserver only if passed as option

---

templates/main/index.html.ep

Allows easier direct linking for dashboard displays.

Add anchor for build results on index page

---

lib/OpenQA/Worker/Cache.pm
t/full-stack.t

Ensure that cache is working as expected, I.E Limits are being
followed correctly, that elements are deleted when they are removed
from the list of items, and that db file is updated accordingly.
Cache.db file was previously copied inside the pool directory where
the worker has no write permissions, this moves it to the proper value in
CACHEDIRECTORY where it can write.

Fix the cache and add tests

---

lib/OpenQA/Schema/Result/Jobs.pm

Improve label takeover 

---

assets/stylesheets/result_preview.scss
templates/test/details.html.ep

See https://progress.opensuse.org/issues/13820

Improve little triangle sign below a screenshot

---

README.asciidoc
script/generate-documentation

Since index.html and current.pdf are a hardlink, files will change if there is anything
new to add.
Make a bit more obvious where to reach developers and where to file
bugs, feature requests, et al.

Fix documentation generator script and add contributing section

---

assets/javascripts/admin_user.js
assets/javascripts/admintable.js
assets/javascripts/assets.js
assets/javascripts/audit_log.js
assets/javascripts/comments.js
assets/javascripts/needlediff.js
assets/javascripts/needleeditor.js
assets/javascripts/overview.js
assets/javascripts/running.js
assets/javascripts/shapes.js
assets/javascripts/tests.js

* Delete w/s at EOL in javascript files
* Use space indendation consistently in javascript files
* Ensure consistent naming of 'failed'+'softfailed' in all occurrences
* Correct 'softfailed' reference to passed (obsoleted)

softfail + javascript cleanup

---

t/05-scheduler-dependencies.t

See https://progress.opensuse.org/issues/16394

Refactor 05-scheduler-dependencies.t

---

lib/OpenQA/BuildResults.pm
lib/OpenQA/Schema/Result/Comments.pm
lib/OpenQA/Schema/Result/JobGroups.pm
t/22-dashboard.t

See https://progress.opensuse.org/issues/18408

Fix "only tagged" for tags with version

---

lib/OpenQA/Schema/Result/Needles.pm
t/ui/21-admin-needles.t

See https://progress.opensuse.org/issues/17942

Show needles in admin table which never matched

---

assets/javascripts/job_templates.js

Do not allow the user to add the same test in the same medium twice to prevent DB exception
See https://progress.opensuse.org/issues/15192
I tested this manually but can add automatic tests if required.

Prevent DB exception when adding tests in job templates

---

t/ui/13-admin.t

* Especially adding new tests to medium
* See https://progress.opensuse.org/issues/15192 and https://github.com/os-autoinst/openQA/pull/1318

Improve admin test

---

lib/OpenQA/Scheduler/FakeApp.pm

See https://openqa.opensuse.org/tests/408989#step/openqa_webui/26

Fix breakage introduced by 659464d

---

script/check_dependencies
script/clean_needles
script/client
script/create_admin
script/dump_templates
script/generate-documentation
script/generate-documentation-genapi.pl
script/generate-packed-assets
script/initdb
script/load_templates
script/openqa
script/upgradedb

* Make sure a valid up-to-date license in all files
* Fix documentation publishing on gh-pages

Fix doc generation

---

lib/OpenQA/Worker.pm
lib/OpenQA/Worker/Cache.pm

Meanwhile strictly check if we got asset size
See (possibly) related Progress issue: https://progress.opensuse.org/issues/19436

Cache: resolve to current host when host URL cannot be resolved

---

assets/javascripts/job_templates.js

See comments under https://progress.opensuse.org/issues/15192
This also includes 2 other small improvements (see particular commits).

job templates: Fix removing options when finalizing row

---

templates/branding/openqa.suse.de/docbox.html.ep

Local run: http://dhcp91.suse.cz/

Add link to CaaSP staging

---

docs/Networking.asciidoc

Documentation for GRE

---

assets/javascripts/index.js
assets/stylesheets/openqa.scss
lib/OpenQA/WebAPI/Controller/Main.pm
templates/main/index.html.ep

Added a "fullscreen" checkbox to the filtersection of the index page. Currently it just hide's the "welcoming box" and the footer.

Create full screen view option in openQA

---

t/ui/12-needle-edit.t

See https://progress.opensuse.org/issues/19652

Add workaround for PhantomJS in needle edit test

---

lib/OpenQA/Schema/Result/Jobs.pm
t/10-tests_overview.t
t/ui/10-tests_overview.t
templates/test/tr_job_result_failedmodules.html.ep

https://progress.opensuse.org/issues/20122

Sort the failed modules on their timestamp not by their name

---

lib/OpenQA/ServerSideDataTable.pm
lib/OpenQA/WebAPI/Controller/Admin/AuditLog.pm
lib/OpenQA/WebAPI/Controller/Admin/Needle.pm
lib/OpenQA/WebAPI/Controller/Admin/Workers.pm

See https://progress.opensuse.org/issues/16692

Refactor serverside

---

lib/OpenQA/WebAPI/Auth/OpenID.pm

When OpenID provider returns messages that cannot be recognized by
Net::OpenID::Consumer, inform the user about the failed login instead of
returning 500.
Related Progress issue: https://progress.opensuse.org/issues/20218

Inform user when OpenID login fails

---

lib/OpenQA/Worker/Cache.pm
t/25-cache.t
t/testrules.yml

Fixes the situation described in poo#19526 but does not solve the problem:
Download of assets can fail due to infraestructure problems
Also address some of the problems we've seen with caching and improve tests.

Improve cache and add unit tests

---

systemd/openqa-webui.service

See https://progress.opensuse.org/issues/16430 for details

Increase the grace timeout to have uploads finish

---

lib/OpenQA/WebAPI/Controller/API/V1.pm

Previous log output:
`[Mon Jun 19 12:55:35 2017] [18947:error] hmac check failed`
Log output with this PR:
`[Mon Jun 19 13:24:35 2017] [21137:error] Wrong api secret for key 'AABBCCDDEEFF0011' (belongs to user 'Demo') used.`
The error message only gets raised if the used secret for an existing key is wrong (hence the previous "hmac check failed"). If the log level is on debug, this information is also recorded in previous error messages. However if openQA runs on big production instances it is maybe not possible all the time to correlate previous messages correctly or it is not feasible to run with "debug". Therefore the increase of verbosity inside this specific message.

Increase information in logs if a wrong secret is used

---

assets/javascripts/needleeditor.js
docs/GettingStarted.asciidoc
t/ui/12-needle-edit.t

* Regression introduced in 6ce9f3accf1a8370b28d369ac406ec663a9f9615
* See https://progress.opensuse.org/issues/17666

Fix saving needle when taking matches

---

lib/OpenQA/Scheduler/Scheduler.pm
lib/OpenQA/Schema/Result/Jobs.pm

This is still WIP because needs more testing. Expecially changes wrt `allocate_network()` since that involves "testing multi-machine tests".
The changes regards two differents Poo issues that seems to be related somehow: [Poo#19806](https://progress.opensuse.org/issues/19806) and [Poo#20002](https://progress.opensuse.org/issues/20002)
In the last commits the `while(1)` loop has been refactorized to `do{...} until {...}` and the job search is retried for a number of attempts since seems having ` blocking=> 1 ` produces no changes, it just exits the loop anyway - can revert if necessary, or default number of attempts tweaked.

Scheduler race conditions

---

assets/javascripts/tests.js
lib/OpenQA/WebAPI/Controller/Test.pm
lib/OpenQA/WebAPI/Plugin/Helpers.pm
t/ui/01-list.t
templates/test/running_table.html.ep
templates/test/scheduled_table.html.ep
templates/test/tr_job_result_details.html.ep

AC1 of https://progress.opensuse.org/issues/19388

Show available comments under /tests

---

dbicdh/_common/upgrade/56-57/001-migrate-jobs.pl

to fix issue 20930.
Once the migration is done, there is no need more for the original function - but it's still in 3 places

Add the job module statistics to the migration code

---

codecov.yml
etc/apache2/vhosts.d/openqa-common.inc
lib/OpenQA/Scheduler.pm
lib/OpenQA/Scheduler/Scheduler.pm
lib/OpenQA/Schema/Result/Assets.pm
lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/Schema/Result/Workers.pm
lib/OpenQA/Utils.pm
lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Controller/API/V1/Iso.pm
lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
lib/OpenQA/WebAPI/Controller/API/V1/Worker.pm
lib/OpenQA/WebSockets.pm
lib/OpenQA/WebSockets/Server.pm
lib/OpenQA/Worker/Commands.pm
lib/OpenQA/Worker/Common.pm
lib/OpenQA/Worker/Jobs.pm
t/04-scheduler.t
t/05-scheduler-capabilities.t
t/05-scheduler-dependencies.t
t/11-commands.t
t/15-assets.t
t/full-stack.t

Basically https://progress.opensuse.org/issues/20546 but a lot more :)
Ettore and me spent 2 working days hunting stability issues and this is the result

Rework job assignment strategy

---

templates/branding/openqa.suse.de/docbox.html.ep

Fix staging link for CaaSP

---

templates/branding/openSUSE/external_reporting.html.ep

Added a report bug button for the openqa in openqa tests which leads
to progess/openqav3

Add 'report Bug' for OpenQA product

---

lib/OpenQA/WebSockets/Server.pm

Avoids unpleasant situations were the websocket server might be under
load and bail out - actually stopping the service entirely.
Wrap also dead job detection in a database transaction.
Even tho we observed that auto_duplicate in production caused the timer
to kill completely the dbus service, in this commit we won't disable it
until we can confirm it's the root of the problem. (production instance was hotpatched disabling it)
Important: we need to depend on new Net::DBus 1.1
Update:
Dbus is still heavly loaded from the websocket side - but we recover from errors - and sometime we loose messages, this comes from webui as well:
> [Fri Aug 18 12:22:58 2017] [18259:error] org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send …

Websocket: wrap database transactions in try catch so we can debug dbus service errors

---

templates/test/overview.html.ep

to fix test result overview in for Perl >= 5.23
See latest comments in https://github.com/os-autoinst/openQA/pull/1107

Dereference hashrefs before using 'keys'

---

lib/OpenQA/BuildResults.pm
t/22-dashboard.t
t/api/04-jobs.t
templates/main/group_builds.html.ep

* Required for Tumbleweed/Kubic's release process
* See https://progress.opensuse.org/issues/23914

Include all relevant distros when linking overview

---

lib/OpenQA/Schema/Result/Users.pm

See https://progress.opensuse.org/issues/23756

Fix use of undefined $email by using default icon instead

---

lib/OpenQA/WebAPI.pm
t/27-errorpages.t
t/testrules.yml
templates/not_found.html.ep

* See https://github.com/os-autoinst/openQA/pull/1439
* Includes original PR, required fixes and a test.

Add description part for api routes at not_found page

---

lib/OpenQA/IPC.pm
lib/OpenQA/Schema/Result/Workers.pm
lib/OpenQA/Utils.pm
lib/OpenQA/WebAPI/Controller/API/V1/Job.pm

See https://github.com/os-autoinst/openQA/pull/1460#discussion_r141369386

Log IPC errors

---

assets/javascripts/feature.js
dbicdh/PostgreSQL/deploy/59/001-auto-__VERSION.sql
dbicdh/PostgreSQL/deploy/59/001-auto.sql
dbicdh/PostgreSQL/upgrade/58-59/001-auto.sql
dbicdh/SQLite/deploy/59/001-auto-__VERSION.sql
dbicdh/SQLite/deploy/59/001-auto.sql
dbicdh/SQLite/upgrade/58-59/001-auto.sql
dbicdh/_source/deploy/59/001-auto-__VERSION.yml
dbicdh/_source/deploy/59/001-auto.yml
lib/OpenQA/Schema.pm
lib/OpenQA/Schema/Result/Users.pm
t/ui/24-feature-tour.t
templates/layouts/bootstrap.html.ep

Related to https://progress.opensuse.org/issues/16376

Add first feature tour to openQA

---

templates/branding/openSUSE/external_reporting.html.ep

Adapt bugzilla link to new SLE15 installer

---

lib/OpenQA/WebAPI/Controller/Running.pm

It caused no live view at all
See related Progress issue: https://progress.opensuse.org/issues/25954

Fix regression introduced in https://github.com/os-autoinst/openQA/pull/1460

---

t/ui/01-list.t
templates/test/list.html.ep

Thanks for merging https://github.com/os-autoinst/openQA/pull/1464 so quick. This PR contains further tests for the query parameter which haven't made it into https://github.com/os-autoinst/openQA/pull/1464 quick enough. There's also fixes a small issue I've just discovered during further tests.

Allow filtering by result on 'All tests' page followup

---

lib/OpenQA/Schema/Result/Screenshots.pm
lib/OpenQA/Worker/Commands.pm
t/24-worker.t
t/ui/12-needle-edit.t

https://github.com/os-autoinst/openQA/pull/1468

Cherry pick perltidy fixes from @henrich

---

lib/OpenQA/Worker/Cache.pm

See Related progress issue: https://progress.opensuse.org/issues/26088

Worker: Wrap asset_lookup() query in eval/if

---

docs/UsersGuide.asciidoc
lib/OpenQA/WebAPI.pm

Related progress issue: https://progress.opensuse.org/issues/26842

Add API description for worker route

---

lib/OpenQA/Schema/Result/Bugs.pm
lib/OpenQA/ServerSideDataTable.pm
lib/OpenQA/WebAPI/Controller/API/V1/Bug.pm
lib/OpenQA/WebAPI/Controller/Admin/Workers.pm
lib/OpenQA/WebAPI/Plugin/AMQP.pm
t/api/12-admin-workers.t

https://progress.opensuse.org/issues/26842

Allow admins to fetch the worker status by json

---

lib/OpenQA/WebAPI/Controller/Test.pm
t/ui/10-tests_overview.t
templates/test/tr_job_result_details.html.ep

See https://progress.opensuse.org/issues/18334

Prevent showing duplicated bugrefs twice

---

assets/assetpack.def
public/fonts/glyphicons-halflings-regular.woff

woff file is no longer fetched

Fixing the package to build with newer assetpack

---

etc/logrotate.d/openqa

superseding https://github.com/os-autoinst/openQA/pull/1438

Replace logrotate config with what we use in production

---

t/ui/10-tests_overview.t
templates/test/overview_result_table.html.ep

/tests/overview: Change sorting to show all machine variants together

---

templates/step/edit.html.ep

See related Progress issue: https://progress.opensuse.org/issues/28432

Use Cpanel::JSON::XS in step/edit.html

---

lib/OpenQA/Resource/Locks.pm
lib/OpenQA/ResourceAllocator.pm
lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/WebAPI/Controller/API/V1/Locks.pm
t/13-joblocks.t

See related Progress issue: https://progress.opensuse.org/issues/27409
Needs: https://github.com/os-autoinst/os-autoinst/pull/880

Make barrier option to automatically destroy the barrier if jobs belonging to it fails

---

lib/OpenQA/Utils.pm
lib/OpenQA/WebAPI/Controller/Test.pm
lib/OpenQA/Worker/Cache.pm
lib/OpenQA/Worker/Commands.pm
lib/OpenQA/Worker/Common.pm
lib/OpenQA/Worker/Engines/isotovideo.pm
lib/OpenQA/Worker/Jobs.pm
t/24-worker.t
t/25-cache.t
t/28-logging.t

The worker will now upload the logs it produces during the execution of a job to the web-ui
This feature makes use of log channels.

Upload workers log to the webUI

---

lib/OpenQA/Worker/Jobs.pm
t/24-worker.t

Also, replace hash slice which was sensible to random keys hash ordering (http://perldoc.perl.org/functions/keys.html).
This should prevent at least the worker to die in cases described by the Progress issue.
See related Progress issue: https://progress.opensuse.org/issues/28355

Check if job is valid before starting working on it.

---

lib/OpenQA/Schema/Result/Assets.pm
t/14-grutasks.t

This adds a protection in the limit_assets gru task that should
prevent it ever deleting an asset that's associated with a job
in any of the PENDING states.

limit_assets: don't wipe assets for PENDING jobs

---

templates/branding/openSUSE/external_reporting.html.ep

Related progress issue: https://progress.opensuse.org/issues/28642

branding: openSUSE: Add caasp (different bugzilla naming variant)

---

templates/branding/openqa.suse.de/docbox.html.ep

Related progress issue: https://progress.opensuse.org/issues/13954

branding: Update SLE staging link

---

docs/Contributing.asciidoc

Otherwise, since the use of PostgreSQL, initializing a single test
run takes quite long.

Document fast initialization of local tests

---

assets/assetpack.def
assets/javascripts/admin_worker.js
lib/OpenQA/Schema/Result/Workers.pm
lib/OpenQA/WebAPI/Controller/API/V1/Worker.pm
lib/OpenQA/WebAPI/Controller/Admin/Workers.pm
t/api/01-workers.t
t/ui/15-admin-workers.t
templates/admin/workers/index.html.ep
templates/admin/workers/show.html.ep
templates/admin/workers/worker_status.html.ep

~~WIP as i need to adapt tests.~~  [Preview](http://e122.suse.de/admin/workers)
Covers: [Poo#19996](https://progress.opensuse.org/issues/19996), [Poo#27832](https://progress.opensuse.org/issues/27832) and [Poo#25766](https://progress.opensuse.org/issues/25766)

Webui admin page revamp

---

lib/OpenQA/Schema/Result/Assets.pm
t/14-grutasks.t

At present, when looping through the assets for a given job
group, we decide whether to make the asset a deletion candidate
*before* we count its size against the limits. So effectively
we keep the minimum amount of assets needed to *exceed* the
size limit, rather than the maximum amount of assets that can
fit within it. This is clearly incorrect. We can fix it by
counting the asset's size against the limits *before* we decide
whether it should be a deletion candidate.
This is an alternative to #1532 by @coolo - I think this way
of fixing it is clearer and better. It also fixes the tests.
@coolo couldn't figure out what was going on with the tests,
and I don't blame him, because it was quite tricky. In fact
what happened is that my understanding of the interaction
between the code and the …

`limit_assets`: remove asset that breaks limit, not next one

---

t/ui/15-admin-workers.t
templates/admin/workers/show.html.ep

See: https://progress.opensuse.org/issues/18594

Hide worker properties if no login

---

lib/OpenQA/WebSockets/Server.pm

This was causing debug mode by default on ws server.
See related Progress issue: https://progress.opensuse.org/issues/29529

Set App mode in WebSocket server

---

dbicdh/PostgreSQL/deploy/62/001-auto-__VERSION.sql
dbicdh/PostgreSQL/deploy/62/001-auto.sql
dbicdh/PostgreSQL/upgrade/61-62/001-auto.sql
dbicdh/_source/deploy/62/001-auto-__VERSION.yml
dbicdh/_source/deploy/62/001-auto.yml
lib/OpenQA/Schema.pm
lib/OpenQA/Schema/Result/Assets.pm
lib/OpenQA/Schema/Result/Jobs.pm
t/10-jobs.t

See https://progress.opensuse.org/issues/29535.

Fix deletion of jobs referenced as last use of asset

---

assets/javascripts/assets.js
assets/javascripts/openqa.js
assets/stylesheets/openqa.scss
lib/OpenQA/WebAPI/Controller/Admin/Asset.pm
t/lib/OpenQA/SeleniumTest.pm
t/ui/13-admin.t
templates/admin/asset/index.html.ep

Built on top of https://github.com/os-autoinst/openQA/pull/1541
Looks like this (data from `openqa.suse.de/2017-12-11.dump`):
* http://imagebin.suse.de/2051/img
* http://imagebin.suse.de/2055/img

Show assets by group

---

t/api/02-assets.t

Those lines shouldn't have gotten into fa07a084b061da0576199093a457fabb318b7b6d

Remove leftovers in t/api/02-assets.t

---

assets/javascripts/tests.js
templates/test/list.html.ep
templates/test/running_table.html.ep
templates/test/scheduled_table.html.ep

* Seems like 7eebd17da did a little bit more than just fixing
indentation
* See https://progress.opensuse.org/issues/29241

Unify code for scheduled/running table and fix sorting

---

assets/javascripts/admin_worker.js

https://progress.opensuse.org/issues/29378

Prevent worker status selection to sort

---

cpanfile

Downgrading selenium drivers during test phase

---

assets/stylesheets/openqa.scss
lib/OpenQA/WebAPI/Controller/Main.pm
t/ui/15-comments.t
templates/comments/pagination.html.ep
templates/main/group_overview.html.ep

See https://progress.opensuse.org/issues/30400
Still needs to be tested.

Add pager for comments on group overview

---

assets/javascripts/index.js
lib/OpenQA/BuildResults.pm
lib/OpenQA/Schema/Result/JobGroupParents.pm
lib/OpenQA/Schema/Result/JobGroups.pm
lib/OpenQA/WebAPI/Controller/Main.pm
t/ui/14-dashboard-parents.t
t/ui/14-dashboard.t
templates/main/index.html.ep

Seems like I have to create a new PR. Here is how it looks like: http://imagebin.suse.de/2163/img
@okurz It should work now as discussed. One regex for everything, the "path" is separated by '/'.

Improve dashboard filter v2

---

lib/OpenQA/WebAPI/Controller/API/V1/Asset.pm
t/api/02-assets.t

See: https://progress.opensuse.org/issues/31045

Give 404 rather than 500 on invalid asset route

---

lib/OpenQA/WebAPI/Controller/Admin/Asset.pm

It was already laying in my branch for #1564

Fix perltidy complaints

---

lib/OpenQA/Client.pm
lib/OpenQA/Client/Handler.pm
lib/OpenQA/Client/Upload.pm
lib/OpenQA/File.pm
lib/OpenQA/Parser/Result.pm
lib/OpenQA/Parser/Results.pm
lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/UserAgent.pm
lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
lib/OpenQA/Worker/Common.pm
lib/OpenQA/Worker/Jobs.pm
t/30-test_parser.t
t/31-client_file.t
t/32-openqa_client.t
t/api/04-jobs.t

See: https://progress.opensuse.org/issues/27955, https://progress.opensuse.org/issues/17788
http://e122.suse.de/tests/6309/file/worker-log.txt
~~Still needs updating apparmor rules~~ Seems no action is required for apparmor http://e122.suse.de/tests/7202

Multi-chunk uploader

---

lib/OpenQA/Parser/Format/JUnit.pm
t/30-test_parser.t
t/data/slenkins_control-junit-results-fail.xml

Add also xml example and specific unit test. @thehejik

OpenQA::Parser::Format::JUnit mark testsuite failed if one of testcases fails

---

script/clone_job.pl

Fixes https://progress.opensuse.org/issues/31465

Show correct port for created job

---

Makefile
cpanfile

Update Perl Tidy

---

templates/main/group_overview.html.ep

See https://progress.opensuse.org/issues/32194

Fix sort order of the review comments

---

lib/OpenQA/Client/Upload.pm
lib/OpenQA/Worker/Jobs.pm
t/32-openqa_client.t

- Catch errors while sending the upload request
- Also sleep when we fail, to avoid choking the webui
See related Progress issue: https://progress.opensuse.org/issues/32602
~~Testing it, will remove WIP once have verification runs~~
[Worker Log, more failures](http://e122.suse.de/tests/14441/file/worker-log.txt)
[Another one](http://e122.suse.de/tests/14960/file/worker-log.txt) (grep for ERROR)

Always retry until chunk is uploaded and retrials exhausted

---

lib/OpenQA/WebSockets/Server.pm

When it's back, it's back - but the api version is still the same
until it changed
See https://progress.opensuse.org/issues/32887

Do not reset the api version just because the worker is offline

---

docs/WritingTests.asciidoc

Try to make it more clear which serial port I am referring to. Highlight that
we are logging into a TTY session on the SUT through a serial port. Discuss
sending signals to programs and send_key. Also fix some minor grammar issues.
Based mostly on comments by @SergioAtSUSE in #1586

docs: Clarify some serial terminal terminology and other elaboration

---

lib/OpenQA/WebAPI/Controller/Test.pm

@nicksinger This would be the required change to render the overview as JSON. Maybe it gets merged.

Enable JSON representation of the test overview

---

t/ui/12-needle-edit.t

Test for https://github.com/os-autoinst/openQA/pull/1616.

Test image selection of needle editor

---

lib/OpenQA/Worker/Jobs.pm

See: https://progress.opensuse.org/issues/28714

Prevent failures in worker reset_state()

---

assets/javascripts/fullscreen.js
assets/javascripts/overview.js
assets/javascripts/test_result.js
assets/javascripts/tests.js
assets/stylesheets/dashboard.scss
assets/stylesheets/overall.scss
assets/stylesheets/overview.scss
assets/stylesheets/tables.scss
t/10-tests_overview.t
t/ui/10-tests_overview.t
templates/main/group_builds.html.ep
templates/test/previous.html.ep
templates/test/tr_job_result.html.ep
templates/test/tr_job_result_failedmodules.html.ep

For the particular changes, just look at the commit messages.
Full screen mode:  
A bit more padding also on small screen width:  
Exact same colors for cards/panels as before:

Bootstrap 4 feedback

---

lib/OpenQA/Schema/Result/Jobs.pm
t/05-scheduler-dependencies.t

These changes will force to test for the specified case in the PR#1623

Improve the duplication tests

---

profiles/apparmor.d/usr.share.openqa.script.worker

- for svirt backend
----
@coolo, let's see if this makes sense

Update apparmor profile for worker

---

assets/javascripts/test_result.js

See https://progress.opensuse.org/issues/28018

Fix links to #live not starting live view

---

docs/GettingStarted.asciidoc
script/client

Things I've noticed when working on https://progress.opensuse.org/issues/33892.

Update documentation regarding isos API

---

assets/stylesheets/overall.scss
assets/stylesheets/result_preview.scss
lib/OpenQA/WebAPI/Controller/Step.pm
lib/OpenQA/WebAPI/Plugin/Helpers.pm
templates/step/viewimg.html.ep

See https://progress.opensuse.org/issues/35203

Small UI improvements

---

templates/main/group_overview.html.ep

Fix the alignment of the progress bars on group overview

---

lib/OpenQA/WebAPI/Plugin/Gru.pm

Add error logging in gru

---

assets/javascripts/test_result.js

See https://progress.opensuse.org/issues/36586

Fix broken navigability with arrow keys in test details

---

lib/OpenQA/Schema/Result/Jobs.pm
t/05-scheduler-cancel.t
t/05-scheduler-dependencies.t
t/05-scheduler-restart-and-duplicate.t

See https://progress.opensuse.org/issues/36565

Cancel full cluster on fails 

---

t/lib/OpenQA/SeleniumTest.pm

console.log is otherwise invisible

Add logggingPrefs to chromium to make sure we get browser logs

---

assets/javascripts/needleeditor.js
assets/javascripts/running.js
lib/OpenQA/Resource/Jobs.pm
lib/OpenQA/ResourceAllocator.pm
lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/Schema/Result/Workers.pm
lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
lib/OpenQA/WebAPI/Controller/API/V1/Worker.pm
lib/OpenQA/WebAPI/Controller/Running.pm
lib/OpenQA/WebAPI/Controller/Step.pm
lib/OpenQA/WebAPI/Plugin/AuditLog.pm
lib/OpenQA/WebSockets/Server.pm
lib/OpenQA/Worker/Commands.pm
t/04-scheduler.t
t/11-commands.t
t/20-workers-ws.t
t/27-websockets.t
templates/test/live.html.ep

I'm convinced it will never fully work, so first step to replace it with
something that scales

Remove current interactive mode

---

lib/OpenQA/Resource/Locks.pm
lib/OpenQA/ResourceAllocator.pm
lib/OpenQA/WebAPI/Controller/API/V1/Locks.pm
t/13-joblocks.t

Related PR: https://github.com/os-autoinst/os-autoinst/pull/969

Allow where parameter for mutex unlocking

---

assets/stylesheets/admin-pages.scss

popover on audit log is not clickable with old margin setting

Adjust popover margin on audit log

---

.travis.yml
Makefile

Try easier way to pass exit status

---

t/33-developer_mode.t
t/full-stack.t
t/lib/OpenQA/Test/FullstackUtils.pm
templates/test/live.html.ep

This link shouldn't be visible when we deploy because it is still experimental.

Remove link to developer console

---

assets/javascripts/ws_console.js
lib/OpenQA/WebAPI/Controller/LiveViewHandler.pm
t/33-developer_mode.t
t/full-stack.t
t/lib/OpenQA/SeleniumTest.pm
t/lib/OpenQA/Test/FullstackUtils.pm

Relies on https://github.com/os-autoinst/os-autoinst/pull/976

Make waiting for paused more robust against disconnects

---

lib/OpenQA/Utils.pm
lib/OpenQA/Worker/Cache.pm
lib/OpenQA/Worker/Engines/isotovideo.pm
t/25-cache.t
t/28-logging.t
t/api/04-jobs.t
t/full-stack.t
t/testrules.yml

Supersede changes in #1662, see https://progress.opensuse.org/issues/34597 for more details

REBASED: Fix race conditions in worker cache

---

assets/javascripts/running.js
lib/OpenQA/LiveHandler.pm
lib/OpenQA/WebAPI/Controller/Test.pm
t/34-developer_mode-unit.t
templates/test/live.html.ep

See https://progress.opensuse.org/issues/38120

Make developer mode accessible to operators

---

script/clone_job.pl
t/api/04-jobs.t

Use _GROUP_ID in clone_job.pl

---

t/30-test_parser.t

* See https://progress.opensuse.org/issues/37423
* Reduces output from ~6000 lines to ~2300

Make parser test less verbose

---

docs/WritingTests.asciidoc

Document another pitfall of communicating with a shell programatically.

docs: Add note on sending new lines to a serial terminal

---

Makefile
docs/Contributing.asciidoc
script/docker-tests
t/lib/OpenQA/Test/Utils.pm

see https://github.com/os-autoinst/openQA/pull/1709#discussion_r200543148

Move commands to run docker tests to separate script 

---

lib/OpenQA/Schema/ResultSet/Assets.pm

See https://progress.opensuse.org/issues/35749

Make registering assets transactional

---

assets/javascripts/running.js

(npm install -g jshint; jshint assets/javascripts/running.js)

Fix javascript errors on running.js

---

assets/javascripts/admin_worker.js
assets/javascripts/job_next_previous.js
assets/javascripts/needleeditor.js
assets/javascripts/overview.js
assets/javascripts/tests.js
lib/OpenQA/Resource/Jobs.pm
lib/OpenQA/ResourceAllocator.pm
lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
lib/OpenQA/WebAPI/Controller/Admin/Workers.pm
t/05-scheduler-restart-and-duplicate.t
t/15-assets.t
t/17-labels_carry_over.t
t/full-stack.t
t/ui/15-admin-workers.t
t/ui/26-jobs_restart.t
templates/test/infopanel.html.ep

See: https://progress.opensuse.org/issues/37453
Work instance:
[/tests](http://10.67.19.14/tests)
[group results overview](http://10.67.19.14/tests/overview?distri=sle&version=15&build=665.2&groupid=4)

Mark all restarted (cluster) jobs in UI

---

lib/OpenQA/Script.pm
script/clone_job.pl
t/35-script_clone_job.t

See: https://progress.opensuse.org/issues/25412

Add global settings support for clone job

---

lib/OpenQA/Worker/Engines/isotovideo.pm
t/full-stack.t

138294f0c61291b1bcfe713d7771314df6d765a2 broke the full stack tests

Make UEFI_PFLASH_VARS non critical on local workers

---

lib/OpenQA/Script.pm
t/35-script_clone_job.t

Some further refactoring I've come up with when reviewing https://github.com/os-autoinst/openQA/pull/1730.
@okurz Now you've got the reduced indentation you'd like to have in my previous PR :-)

Refactor clone job

---

dbicdh/PostgreSQL/deploy/67/001-auto-__VERSION.sql
dbicdh/PostgreSQL/deploy/67/001-auto.sql
dbicdh/PostgreSQL/upgrade/66-67/001-auto.sql
dbicdh/_source/deploy/67/001-auto-__VERSION.yml
dbicdh/_source/deploy/67/001-auto.yml
lib/OpenQA/Schema.pm
lib/OpenQA/Schema/Result/Comments.pm
lib/OpenQA/Schema/Result/JobGroupParents.pm
lib/OpenQA/Schema/Result/JobGroups.pm
lib/OpenQA/Utils.pm
lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Controller/API/V1/Comment.pm
lib/OpenQA/WebAPI/Controller/Main.pm
t/17-build_tagging.t
t/api/04-jobs.t
t/api/09-comments.t
t/ui/15-comments.t
templates/main/comment_area.html.ep
templates/main/group_overview.html.ep
templates/main/parent_group_overview.html.ep
templates/main/pinned_comments.html.ep

See https://progress.opensuse.org/issues/37255
---
It basically works, adjusting/extending the UI tests will be the annoying part.

Support commenting on parent-group level

---

lib/OpenQA/WebAPI/Controller/API/V1/Job.pm

Since we are there, give it a purpose (it will also fix tests complaining about warnings)
(WIP as i'm waiting for acceptance test)

Use the transaction to check if it's empty (and avoid warnings)

---

docs/Installing.asciidoc

Add repository name, or **zypper ar** will complain

Fix suggested command for adding devel repo

---

lib/OpenQA/WebAPI/Plugin/AMQP.pm
t/23-amqp.t

See https://progress.opensuse.org/issues/37255#note-8

Emit parent group ID in AMQP comment event

---

t/16-utils-runcmd.t

See https://github.com/os-autoinst/openQA/pull/1749

Adapt t/16-utils-runcmd.t for e2771ee

---

.gitignore
docs/Contributing.asciidoc
script/docker-tests
t/lib/OpenQA/SeleniumTest.pm

Things I had to come up with to fix my local Docker test setup.

Changes for my local Docker test setup

---

assets/javascripts/job_templates.js
assets/stylesheets/admin-pages.scss
dbicdh/PostgreSQL/deploy/68/001-auto-__VERSION.sql
dbicdh/PostgreSQL/deploy/68/001-auto.sql
dbicdh/PostgreSQL/upgrade/67-68/001-auto.sql
dbicdh/_source/deploy/68/001-auto-__VERSION.yml
dbicdh/_source/deploy/68/001-auto.yml
lib/OpenQA/Schema.pm
lib/OpenQA/Schema/Result/JobTemplates.pm
lib/OpenQA/WebAPI/Controller/API/V1/Iso.pm
lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
t/api/02-iso.t
t/api/08-jobtemplates.t
templates/admin/group/group_property_editor.html.ep

See https://progress.opensuse.org/issues/38522 and particular commit messages.  
Automatic tests are still TODO, but I've tested this manually with OSD data.

Improve prioritizing job templates

---

lib/OpenQA/WebAPI/Controller/API/V1/Iso.pm
t/api/02-iso.t

See https://progress.opensuse.org/issues/36727, the
fixtures are based on foursixnine's

Catch misconfigured test suites creating cycles

---

systemd/openqa-scheduler.service

websocket already requires scheduler

Do not require websocket in scheduler

---

lib/OpenQA/Parser/Format/JUnit.pm

OpenQA::Parser::Format::JUnit include error and skipped details

---

t/full-stack.t
t/lib/OpenQA/Test/FullstackUtils.pm
t/ui/15-comments.t

Debug random test failures / make tests more stable

---

lib/OpenQA/WebAPI/Plugin/AMQP.pm

* Distinguish different errors
* Append PID

Improve error log of AMQP plugin

---

assets/javascripts/running.js
dbicdh/PostgreSQL/deploy/69/001-auto-__VERSION.sql
dbicdh/PostgreSQL/deploy/69/001-auto.sql
dbicdh/PostgreSQL/upgrade/68-69/001-auto.sql
dbicdh/_source/deploy/69/001-auto-__VERSION.yml
dbicdh/_source/deploy/69/001-auto.yml
docker/webui/Dockerfile
docker/webui/openqa.conf
docs/Installing.asciidoc
etc/apache2/vhosts.d/openqa-common.inc
etc/apache2/vhosts.d/openqa.conf.template
lib/OpenQA/LiveHandler.pm
lib/OpenQA/Schema.pm
lib/OpenQA/Schema/Result/Workers.pm
lib/OpenQA/Schema/ResultSet/DeveloperSessions.pm
lib/OpenQA/Setup.pm
lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Controller/LiveViewHandler.pm
lib/OpenQA/Worker/Common.pm
lib/OpenQA/Worker/Jobs.pm
t/33-developer_mode.t
t/34-developer_mode-unit.t
t/lib/OpenQA/SeleniumTest.pm
t/ui/25-developer_mode.t
templates/test/live.html.ep

* Based on https://github.com/os-autoinst/openQA/pull/1727 (which would be ready to be merged).
* See https://progress.opensuse.org/issues/38510#note-7
---
Note that this will remove (I have no idea where this code was used and how it was supposed to work):  
```
if ($ENV{WORKER_USE_WEBSOCKETS}) {
my $job_id = $job->{id};
ws_call('status', $status);
```

Make developer mode aware of uploading results

---

lib/OpenQA/Worker/Common.pm

In particular, this should prevent the worker to endlessly post progress updated in case the live handler is not reachable.

Prevent worker to endlessly retry non-critical API calls

---

lib/OpenQA/Schema/Result/Workers.pm
lib/OpenQA/Schema/ResultSet/DeveloperSessions.pm
lib/OpenQA/Worker/Commands.pm
lib/OpenQA/Worker/Jobs.pm
t/11-commands.t
t/20-workers-ws.t
t/34-developer_mode-unit.t
t/ui/25-developer_mode.t

See https://progress.opensuse.org/issues/41015#note-4
WIP because I'd like to add a check in the full stack test that the POST isn't done anymore.

Inform worker about devel session to reduce posting status info

---

docs/Installing.asciidoc
openQA.spec

See https://progress.opensuse.org/issues/40904

Enable the scheduler on updates (and the webui is enabled)

---

lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/WebAPI/Controller/API/V1/Worker.pm

To avoid leaking vlans, see https://progress.opensuse.org/issues/41048

Release job networks more often

---

lib/OpenQA/Scheduler/Scheduler.pm

Increase a priority_offset whenever a job had to give up its
allocated worker due to other cluster jobs not getting one (starvation
in busy farms). Once this leads to a priority of 0 (or in case
the priority was 0 from the beginning), the worker won't be used
for other jobs so the cluster has a possibility to start
In case the cluster is too big for the worker farm, this will lead
to starvation in the other direction - but that's for the admin
to avoid. If we find this situation more often, we will need to
implement a timely degration of the priority_offset.

 Make sure multimachine jobs get a worker eventually

---

lib/OpenQA/Task/Asset/Limit.pm

* Print exact number of hours (might also prevent potential rounding
problems)
* Print assigned groups or age
* See https://progress.opensuse.org/issues/41483

Make asset cleanup more verbose

---

dbicdh/PostgreSQL/deploy/70/001-auto-__VERSION.sql
dbicdh/PostgreSQL/deploy/70/001-auto.sql
dbicdh/PostgreSQL/upgrade/69-70/001-auto.sql
dbicdh/_common/upgrade/69-70/001-set-finished-and-fix-state.pl
dbicdh/_source/deploy/70/001-auto-__VERSION.yml
dbicdh/_source/deploy/70/001-auto.yml
lib/OpenQA/Schema.pm
lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/Task/Asset/Limit.pm
t/05-scheduler-cancel.t
t/05-scheduler-dependencies.t

See https://progress.opensuse.org/issues/41543 and particular commit messages.

Fix wrong states

---

docs/UsersGuide.asciidoc
lib/OpenQA/WebAPI/Controller/API/V1/Iso.pm
t/api/02-iso.t

See https://progress.opensuse.org/issues/40661

Allow overwriting job priority when posting isos

---

lib/OpenQA/Schema/ResultSet/Assets.pm
lib/OpenQA/Task/Asset/Limit.pm
script/dump_templates
t/19-tests-export.t
t/fixtures/01-jobs.pl

See https://progress.opensuse.org/issues/41483

Increase debugging information in asset removal

---

docs/UsersGuide.asciidoc

See https://progress.opensuse.org/issues/40223
WIP because I want to read it again myself tomorrow :-)

Document asset cleanup

---

t/24-worker.t
t/25-serverstartup.t
t/lib/OpenQA/Test/Utils.pm

* See https://progress.opensuse.org/issues/41486
* Releated Mojolicous change: https://github.com/mojolicious/mojo/commit/7b1307c29607661bb2afac03706c502bfaf97dfb
* Still works with Mojolicious < 8

Adapt tests to logging behavior of Mojolicious 8

---

docker/travis_test/Dockerfile
lib/OpenQA/Schema/Result/Needles.pm
lib/OpenQA/Schema/ResultSet/Needles.pm
lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Controller/File.pm
lib/OpenQA/WebAPI/Controller/LiveViewHandler.pm
lib/OpenQA/WebAPI/Controller/Step.pm
t/34-developer_mode-unit.t
t/fixtures/07-needles.pl
t/ui/07-file.t
t/ui/12-needle-edit.t

see https://progress.opensuse.org/issues/41075  
os-autoinst: https://github.com/os-autoinst/os-autoinst/pull/1027

Allow command server to download new needles on resume

---

lib/OpenQA/Worker.pm

* This is better than keeping the timer alive and endlessly run into the same error again.
* See https://progress.opensuse.org/issues/34042

Stop worker when an unhandled exception occurs 

---

assets/javascripts/job_templates.js
assets/stylesheets/admin-pages.scss

See https://progress.opensuse.org/issues/42017

Use italic font to display default prio

---

lib/OpenQA/Utils.pm
t/28-logging.t

* Fallback to STDERR/STDOUT if logging to other channels fails
* See https://progress.opensuse.org/issues/34282

Handle logging errors

---

openQA.spec

* Move all client specific files into openQA-client itself
* Make it depend on openQA-common because is requires
OpenQA::File
---
<s>Not tested yet</s>

Fix dependencies of openQA-client package

---

assets/stylesheets/test-details.scss

It should have only been padding-right

Fix padding of tabs in testresults

---

lib/OpenQA/Worker/Jobs.pm

See https://progress.opensuse.org/issues/40004
Tested locally by making the error condition true after a certain number of status updates.

worker: Stop job if considered dead by the web UI

---

lib/OpenQA/Worker/Jobs.pm
t/24-worker.t

* Follow up of 3d1e3f38139519d5150cdd6a7e9103823e81488c
* See https://progress.opensuse.org/issues/40004

worker: Stop job if considered dead by the web UI (2)

---

assets/stylesheets/test-details.scss
templates/test/module_table.html.ep

See particular commit messages and https://progress.opensuse.org/issues/41510

Improve rendering test step result

---

lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Controller/Admin/Influxdb.pm
t/api/13-influxdb.t

https://progress.opensuse.org/issues/40583

Add influxdb route to poll stats of running and scheduled jobs

---

assets/javascripts/tests.js
t/ui/01-list.t

See https://progress.opensuse.org/issues/42584

Fix prio field in /tests and add a test for it

---

lib/OpenQA/Schema/Result/Screenshots.pm

See https://progress.opensuse.org/issues/19730

Make 'can't remove ...' warnings debug messages

---

assets/javascripts/running.js
assets/javascripts/test_result.js
t/33-developer_mode.t
t/ui/25-developer_mode.t
templates/test/live.html.ep

Helps decreasing the number of error messages (see https://progress.opensuse.org/issues/39227).

Lazy-initialize devel mode when switching to live view tab

---

assets/javascripts/admin_worker.js
t/ui/15-admin-workers.t

See https://progress.opensuse.org/issues/42614

Use 'not yet' instead of 'never started' on /admin/workers/X

---

assets/javascripts/job_templates.js
t/ui/13-admin.t

See https://progress.opensuse.org/issues/43031

Fix job templates JavaScript / Fix 13-admin.t

---

assets/javascripts/job_next_previous.js
lib/OpenQA/WebAPI/Controller/Test.pm
lib/OpenQA/WebAPI/Plugin/Helpers.pm
templates/test/tr_job_result_details.html.ep

Ticket: https://progress.opensuse.org/issues/34396

Show bug title on mouseover

---

lib/OpenQA/Schema/ResultSet/Jobs.pm
lib/OpenQA/Utils.pm
lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
lib/OpenQA/WebAPI/Controller/Test.pm
t/10-tests_overview.t
t/ui/10-tests_overview.t

See https://progress.opensuse.org/issues/41756

Prevent filter on test overview to reveal old jobs

---

docs/GettingStarted.asciidoc

Related progress issue: https://progress.opensuse.org/issues/39719

docs: Extend definition of *softfailed* to "known issues"

---

docker/travis_test/Dockerfile

Mojo::SQLite and Minion::Backend::SQLite

Add 2 new dependencies to the travis container:

---

lib/OpenQA/Worker/Jobs.pm

openQA side of os-autoinst/os-autoinst#1059, poo#42050.

Upload video timestamp file when it exists

---

t/26-controllerrunning.t

Seems like I was a bit to fast with merging https://github.com/os-autoinst/openQA/pull/1870. But it is just the formatting.

Fix formatting

---

lib/OpenQA/Worker/Jobs.pm
t/ui/16-tests_dependencies.t

This fixes various tests (tests assert that no warnings are present).

Fix deprecation warnings regarding Mojo::Transaction::error

---

assets/javascripts/admin_groups.js
lib/OpenQA/WebAPI/Controller/API/V1/JobGroup.pm

This fix the issue came from #1844

Do not check group name by dragging group

---

assets/stylesheets/tables.scss
templates/test/tr_job_result_failedmodules.html.ep

See https://progress.opensuse.org/issues/36823
Before:  
After:

Fix line break in failed module box

---

assets/javascripts/openqa.js
assets/javascripts/running.js
assets/stylesheets/test-details.scss
lib/OpenQA/WebAPI/Controller/Test.pm
t/33-developer_mode.t
t/lib/OpenQA/Test/FullstackUtils.pm
t/ui/18-tests-details.t
t/ui/25-developer_mode.t
templates/test/infopanel.html.ep
templates/test/live.html.ep

Move note about VNC into developer panel

---

docs/Pitfalls.asciidoc

See https://progress.opensuse.org/issues/44291

Document steps to debug developer mode setup

---

t/25-cache-service.t

See https://progress.opensuse.org/issues/44240

Debug 25-cache-service.t

---

systemd/openqa-worker-cacheservice-minion.service
systemd/openqa-worker-cacheservice.service

Related progress issue: https://progress.opensuse.org/issues/44105

Restart openqa-worker-cacheservice on failure/wait for network

---

openQA.spec

See https://gitlab.suse.de/okurz/scripts/-/jobs/53976

openQA.spec: Add missing runtime requirement for client

---

lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/Worker/Jobs.pm

This is the efficient way to merge two hashes.

Merge hashes properly

---

openQA.spec

See https://progress.opensuse.org/issues/44960

Update specfile line for restarting apparmor

---

.travis.yml
Makefile
docs/Contributing.asciidoc

Makefile: Delete unused Makefile and travis CI rules / Make code lines in docs more prominent

---

docs/WritingTests.asciidoc

For openQA users and newcomers.

Improve documentation for schedule control

---

assets/javascripts/needleeditor.js
assets/javascripts/openqa.js
assets/javascripts/running.js
assets/javascripts/tests.js
lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
t/33-developer_mode.t
t/ui/25-developer_mode.t
templates/step/edit.html.ep
templates/test/live.html.ep

* Built on top of https://github.com/os-autoinst/openQA/pull/1899 which should be merged first

Various improvements for devel mode and re-needling

---

docs/Installing.asciidoc

Ticket: https://progress.opensuse.org/issues/45365

DOC: Add bootstrap hint for Leap 15.0

---

assets/javascripts/running.js
lib/OpenQA/WebAPI/Controller/LiveViewHandler.pm
t/ui/25-developer_mode.t
templates/test/live.html.ep

See particular commit messages and https://progress.opensuse.org/issues/45278
---
---
---
WIP because it likely requires a bit more testing and polishing.

Allow to pause on next command, show currently executed function

---

script/clone_job.pl

clone_job: Add convenience option '--remote'

---

lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/WebAPI/Controller/Test.pm
t/10-jobs.t
templates/branding/openSUSE/external_reporting.html.ep

Add test suite description for bug reporting.
https://progress.opensuse.org/issues/45890
For example, try to open a bug in my openQA instance for this step: [](http://10.100.12.156/tests/2847#step/addon_products_via_SCC_yast2/37)

Add test suite description for bug reporting

---

assets/javascripts/admin_worker.js
assets/javascripts/comments.js
assets/javascripts/feature.js
assets/javascripts/fullscreen.js
assets/javascripts/keyevent.js
assets/javascripts/needlediff.js
assets/javascripts/needleeditor.js
assets/javascripts/running.js
assets/javascripts/test_result.js
assets/stylesheets/test-details.scss

Fixes that the developer mode freezes after a certain time. In fact, the live log has just gotten to long and Chromium and Firefox don't handle that well. I also allow line-wrapping in the live log and fixed some JavaScript errors reported by jshint.

Improve live log

---

.gitattributes

Related progress issue: https://progress.opensuse.org/issues/12802

Prevent github to think we have perl6 code

---

script/openqa-bootstrap-container

This will be useful for testing - eg. using the openQA TW snapshot repo.

Allow overwriting container bootstrap repo

---

script/openqa-bootstrap

Better check for existing DBs in bootstrap

---

lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/WebAPI/Plugin/AMQP.pm
t/23-amqp.t

See https://progress.opensuse.org/issues/16276

Add (carried over) bugref to job.done AMQP event

---

lib/OpenQA/Worker/Engines/isotovideo.pm

Related progress issue: https://progress.opensuse.org/issues/46658

Fix another regression from c9735699 when no sync is needed

---

t/21-needles.t

It is wrong to hard-code the needle ID.

Fix flaky test regarding needle update

---

profiles/apparmor.d/usr.share.openqa.script.worker

See https://progress.opensuse.org/issues/44327#note-8

apparmor: Fix access to git templates

---

lib/OpenQA/Schema/Result/JobGroups.pm
t/17-build_tagging.t

See https://progress.opensuse.org/issues/46598

Consider parent group comments for important builds

---

lib/OpenQA/Schema/Result/Users.pm
t/ui/18-tests-details.t
templates/test/infopanel.html.ep

https://progress.opensuse.org/issues/45887

Show scenario description on test job infopanel

---

t/ui/18-tests-details.t

See https://progress.opensuse.org/issues/45890

Add test check for scenario within error reporting

---

assets/javascripts/running.js
lib/OpenQA/Worker/Engines/isotovideo.pm
lib/OpenQA/Worker/Jobs.pm
t/10-jobs.t
t/33-developer_mode.t
t/ui/25-developer_mode.t
templates/test/live.html.ep

This is the worker and UI part for https://github.com/os-autoinst/os-autoinst/pull/1093. Both PRs must not necessarily be merged/deployed at the same time.
See https://github.com/os-autoinst/os-autoinst/pull/1093 for more details.

Prevent error about cmd srv connection when test ends

---

assets/javascripts/needleeditor.js
assets/stylesheets/overall.scss
lib/OpenQA/Schema/Result/Needles.pm
lib/OpenQA/Task/Needle/Save.pm
lib/OpenQA/Task/Needle/Scan.pm
lib/OpenQA/Utils.pm
lib/OpenQA/WebAPI/Controller/Step.pm
lib/OpenQA/WebAPI/Plugin/Gru.pm
t/16-utils-runcmd.t
t/lib/OpenQA/SeleniumTest.pm
t/lib/OpenQA/Test/Case.pm
t/lib/OpenQA/Test/Database.pm
t/ui/12-needle-edit.t

* Improve error handling when executing Git commands
* Before doing any changes, fetch the latest `master` from `origin` and hard-reset our local branch to it. This should decrease the likeliness of conflicts.
* Clean-up related code and add more tests.
* See https://progress.opensuse.org/issues/12128

Improve saving needles to Git repository

---

t/ui/18-tests-details.t
templates/step/viewtext.html.ep

See https://progress.opensuse.org/issues/46823
---

Show bug reporting links also on text results

---

assets/javascripts/tests.js

* Fix priority being stuck at 0 (see https://progress.opensuse.org/issues/47285)
* Use flash messages

Improve error handling when changing priority

---

lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
lib/OpenQA/Worker/Common.pm

Just 2 small improvements I've come up with when debugging the current worker issues.

Improve error handling in worker <=> web UI communication

---

lib/OpenQA/Schema/ResultSet/Jobs.pm
lib/OpenQA/WebAPI/Controller/API/V1/Iso.pm
t/04-scheduler.t
t/05-scheduler-dependencies.t
t/api/02-iso.t
t/api/04-jobs.t
t/data/workers.ini
t/full-stack.t

See https://progress.opensuse.org/issues/20812#note-7

Assign default worker class when creating new jobs

---

lib/OpenQA/Worker/Jobs.pm
t/24-worker.t

* Should at least fix the worker-side of: https://progress.opensuse.org/issues/48422
* I also did some cleanup which is included as separate commits (see the particular commit messages for details). One less `goto` :-)
---
WIP because I still need to run some tests.

Improve handling job finish

---

assets/stylesheets/test-details.scss
lib/OpenQA/WebAPI/Controller/Step.pm
templates/test/module_table.html.ep

See https://progress.opensuse.org/issues/48758

Prevent broken rendering of unknown result types

---

t/38-workers-table.t

Related to https://progress.opensuse.org/issues/37312. I think adding this test shouldn't hurt.

Test deleting job from worker's job history

---

lib/OpenQA/Schema/Result/Bugs.pm
lib/OpenQA/Schema/Result/Workers.pm
lib/OpenQA/Schema/ResultSet/Bugs.pm
lib/OpenQA/Utils.pm
lib/OpenQA/WebAPI/Controller/API/V1/Comment.pm
lib/OpenQA/WebAPI/Controller/Test.pm
t/16-utils.t
t/25-bugs.t
t/api/11-bugs.t

Ticket: https://progress.opensuse.org/issues/48218

Add support for links to jira tickets

---

lib/OpenQA/WebAPI.pm

There were actually quite a few places where we could use route placeholder types. In at least one case the existing regex was never applied because the placeholder name had a typo. Using placeholder types is safer, since they don't match if you make a typo.

Use route placeholder types whenever possible

---

assets/stylesheets/admin-pages.scss
dbicdh/PostgreSQL/deploy/76/001-auto-__VERSION.sql
dbicdh/PostgreSQL/deploy/76/001-auto.sql
dbicdh/PostgreSQL/upgrade/75-76/001-auto.sql
dbicdh/_source/deploy/76/001-auto-__VERSION.yml
dbicdh/_source/deploy/76/001-auto.yml
lib/OpenQA/Schema.pm
lib/OpenQA/Schema/JobGroupDefaults.pm
lib/OpenQA/Schema/Result/JobGroupParents.pm
lib/OpenQA/Schema/Result/JobGroups.pm
lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/WebAPI/Controller/API/V1/JobGroup.pm
t/17-labels_carry_over.t
t/api/10-jobgroups.t
t/ui/13-admin.t
templates/admin/group/group_property_editor.html.ep

* The default (carry over enabled) doesn't change of course
* See https://progress.opensuse.org/issues/48182
* Since I was already touching the code, I've also added 2 other small improvements (see further commits).

Allow to disable bug reference carry over on job group level

---

t/ui/16-tests_dependencies.t

See https://github.com/os-autoinst/openQA/pull/2003#issuecomment-473399003

Fix test for dependency graph

---

script/openqa-bootstrap

Requires https://build.opensuse.org/request/show/686466 to be accepted before merge.
Ticket: https://progress.opensuse.org/issues/49454

Install test distri deps on bootstrap

---

docs/images/architecture.graphml
docs/images/architecture.svg

to be merged after https://github.com/os-autoinst/openQA/pull/2043

Update architecture diagram in accordance with PR 2043

---

openQA.spec

Reverts os-autoinst/openQA#2041

Revert "openQA.spec: multiline macros for services and dependencies"

---

script/openqa-bootstrap
script/openqa-bootstrap-container

This fixes bootstrap on aarch64.

Remove deprecated qemu-kvm and use qemu-arm, qemu-ppc and qemu-x86 instead

---

assets/javascripts/needleeditor.js
assets/javascripts/shapes.js
lib/OpenQA/WebAPI/Controller/Step.pm
t/ui/12-needle-edit.t
templates/step/edit.html.ep

* See https://progress.opensuse.org/issues/49943
* See https://github.com/os-autoinst/os-autoinst/pull/1144
---
The appearance could be improved (suggestions?). So far it looks like this:  
The white circle is the click point and can be moved within the area it belongs to.

Allow adding click coordinates in the needle editor

---

lib/OpenQA/Worker/Engines/isotovideo.pm

See https://progress.opensuse.org/issues/46952
---
Tested locally by putting a fake `rsync` under `/usr/local/bin`.

Retry after rsync exits with status 24

---

lib/OpenQA/Schema/Result/ScheduledProducts.pm

instead of writing them (without context) to the web UI log.
See https://progress.opensuse.org/issues/18076

Add non-fatal messages during scheduling to results

---

lib/OpenQA/Git.pm
lib/OpenQA/Schema/Result/Needles.pm
lib/OpenQA/Task/Needle/Save.pm
t/16-utils-runcmd.t

See failed Minion jobs on OSD.

Set user correctly in OpenQA::Git instantiation

---

lib/OpenQA/WebAPI/Controller/API/V1/Bug.pm
t/api/11-bugs.t

The data is already there, `t_created` is automatically set. This just exposes (and documents) filtering bugs by `t_created` in addition to `t_updated` by specifying `created_since` with a timespan in seconds.
Fixes: [poo#50846](https://progress.opensuse.org/issues/50846)

Allow listing bugs by the time of reporting

---

assets/javascripts/job_next_previous.js
templates/test/tr_job_result_failedmodules.html.ep

List remaining failed modules on mouseover

---

script/openqa-bootstrap

Related: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/7505

Install qemu-uefi-aarch64 on aarch64 in bootstrap

---

lib/OpenQA/Utils.pm
t/10-jobs.t

Use less noisy perl style for $comment->label

---

assets/javascripts/admintable.js

See https://progress.opensuse.org/issues/52232

Fix filtering settings in admin tables

---

assets/javascripts/admintable.js
t/ui/13-admin.t

See https://progress.opensuse.org/issues/51719

Clear admin table filter before adding new row

---

docs/images/architecture.graphml
docs/images/architecture.svg

For https://github.com/os-autoinst/openQA/pull/2090

Update architecture diagram for D-Bus removal

---

docs/Networking.asciidoc

i added a few details and notes that i think it would be useful for the future setup for clarity of the process

Update MM setup documentation

---

lib/OpenQA/WebAPI/Plugin/AMQP.pm

The AMQP plugin relied on a memory leak previously present in older versions of `Mojo::RabbitMQ::Client` to keep publisher instances from getting destroyed too early. That has recently been fixed upstream, and we now need to keep a hard reference to those instances.
Progress: https://progress.opensuse.org/issues/52934

Fix AMQP not sending any events

---

.travis.yml

Fix travis cache permissions for docker user

---

lib/OpenQA/Schema/Result/Jobs.pm
t/05-scheduler-dependencies.t

Ignore all childrens when looking for parents. The code feels like it's
overcomplicating things, but I would like to have the tests working before
rethinking it

Blocked by calculation: Fix cyclic behaviour

---

docs/Networking.asciidoc
docs/WritingTests.asciidoc

* docs: Improve language of Networking document
* docs: Consistently use QEMU, the offical way of writing

docs: Improve language of Networking document; Consistently use QEMU

---

Makefile

Fixes the build of the package after d11bc166.

Fix deletion of scripts during install

---

lib/OpenQA/Setup.pm
lib/OpenQA/WebAPI/Controller/API/V1/Table.pm
lib/OpenQA/Worker/Common.pm
t/24-worker.t
t/api/05-machines.t
t/config.t

See: https://progress.opensuse.org/issues/51932

Trim whitespace characters from both ends of string

---

Makefile
docker/openqa/entrypoint.sh
docker/travis_test/Dockerfile
script/fetchneedles
script/generate-documentation
script/generate-packed-assets
script/openqa-bootstrap
script/openqa-bootstrap-container
script/openqa-clone-custom-git-refspec
script/run-tests-within-container
script/tidy

* Make all shell scripts pass default level (style) of shellcheck
* Make all shell scripts pass 'warning' level of shellcheck
* fetchneedles: Use consistent spaces style
* Makefile: Add test for shell scripts using "shellcheck"
* openqa-clone-custom-git-refspec: Include further suggestions by shellcheck
* openqa-clone-custom-git-refspec: Fix use of "-n" on GITHUB_TOKEN
OBS test project: https://build.opensuse.org/package/show/home:okurz:branches:devel:openQA:gh2134/openQA

shell style checks

---

docs/Contributing.asciidoc
t/24-worker-engine.t
t/full-stack.t

* t: Fix warning in full-stack.t
* t: Delete superfluous setting delete
* docs: Add hint how to get coverage for individual tests

Various test enhancements (alt to #2147 w/o fork workaround)

---

_includes/footer.html
documentation.html

Relevant progress issue: https://progress.opensuse.org/issues/52730

Point to single, complete documents first; Reference more up-to-date videos

---

docs/Contributing.asciidoc
t/24-worker-engine.t
t/full-stack.t

* t: Fix warning in full-stack.t
* t: Output isotovideo log files in case of incomplete jobs within the full stack test
* t: Delete superfluous setting delete
* docs: Add hint how to get coverage for individual tests

Various test enhancements

---

docker/travis_test/Dockerfile

See https://github.com/os-autoinst/openQA/pull/1969

travis_test: Add dependencies for 'python-scripts'

---

cpanfile
lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
t/api/08-jobtemplates.t
t/ui/13-admin.t

@@ -3,7 +3,7 @@
i586:
opensuse-13.1-DVD-i586: &1
- spam
-    - eggs
+    - foobar
ppc64:
opensuse-13.1-DVD-ppc64: *1
x86_64:
Fixes: https://progress.opensuse.org/issues/52490

Add YAML diff to jobtemplate_create events

---

README.asciidoc

Related progress issue: https://progress.opensuse.org/issues/45743

README: Clarify how releases are made

---

assets/javascripts/admintable.js
t/ui/13-admin.t

Improve usability for use-case described in https://github.com/os-autoinst/openQA/pull/2089#issuecomment-499017381
@Amrysliu So I have not forgotten this :-)

Extend filter for new/updated admin table rows

---

.travis.yml
docs/Contributing.asciidoc

* .travis.yml: Make documentation generation an explicit job, only on master
* .travis.yml: Give readable names to test jobs
* .travis.yml: Put handling of cache dir together

.travis.yml: Named test jobs; explicit documentation generation job

---

docker/travis_test/Dockerfile

for https://github.com/os-autoinst/openQA/pull/2180

Add Test::Strict to Docker container

---

t/api/03-auth.t

Seems to be forgotten tests from a refactoring [4 years ago](https://github.com/os-autoinst/openQA/commit/594c7a1ff6fb55340a93e152b07d89dbbbfb12e9).

Remove dead auth tests from a DBus refactoring 4 years ago

---

lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
t/api/04-jobs.t

See https://progress.opensuse.org/issues/53435

Ensure query in jobs API does not become too big

---

lib/OpenQA/Worker.pm
t/24-worker-overall.t

and extend worker tests
see https://progress.opensuse.org/issues/54203

Fix worker CLI option --no-cleanup

---

assets/javascripts/ws_console.js

This might not help in all cases but at least it is a start (see particular commit messages).

Reduce flakyness of developer mode test

---

codecov.yml
lib/OpenQA/Setup.pm
lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Plugin/ObsRsync.pm
lib/OpenQA/WebAPI/Plugin/ObsRsync/Controller.pm
lib/OpenQA/WebAPI/Plugin/ObsRsync/templates/ObsRsync_folder.html.ep
lib/OpenQA/WebAPI/Plugin/ObsRsync/templates/ObsRsync_index.html.ep
lib/OpenQA/WebAPI/Plugin/ObsRsync/templates/ObsRsync_logfiles.html.ep
lib/OpenQA/WebAPI/Plugin/ObsRsync/templates/ObsRsync_logs.html.ep
script/client
t/31-client_file.t
t/api/03-auth.t
t/api/14-plugin_obs_rsync.t
t/config.t
t/data/openqa-trigger-from-obs/Leap:15.1:ToTest/.run_190703_143010/files_iso.lst
t/data/openqa-trigger-from-obs/Leap:15.1:ToTest/.run_last/files_iso.lst
t/data/openqa-trigger-from-obs/README.txt
t/data/openqa-trigger-from-obs/rsync.sh
t/lib/OpenQA/SeleniumTest.pm
t/ui/06-operator_links.t

Plugin for triggering OBS synchronization and showing logs/config of https://github.com/andrii-suse/openqa-trigger-from-obs

ObsRsync plugin

---

docs/Contributing.asciidoc

* I know that some things I've mentioned will improve with https://github.com/os-autoinst/openQA/pull/2187 but so far I'm not sure how to fix with outstanding issues with it.

Improve documentation

---

docs/Contributing.asciidoc
templates/comments/add_comment_form_groups.html.ep
templates/main/index.html.ep
templates/test/overview.html.ep

* templates: Update references to documentation in help texts
* docs: Update references to target versions in our issue tracker

Update progress.o.o references

---

docs/Contributing.asciidoc

Since there was no documentation for openQA plugins yet i've just written down everything i could think of.

Start a documentation section on how to build openQA plugins

---

lib/OpenQA/Worker.pm
lib/OpenQA/Worker/Settings.pm
t/24-worker-overall.t
t/24-worker-settings.t
t/data/24-worker-settings-error/workers.ini

See https://progress.opensuse.org/issues/54485

Log errors when reading worker config

---

script/openqa-bootstrap

See https://github.com/koalaman/shellcheck/wiki/SC2230

openqa-bootstrap: Fix lookup of configure-web-proxy

---

t/api/03-auth.t

In testing whether we're allowed to or forbidden from deleting
assets in various cases, we actually wind up deleting an asset.
This is a problem if t/ui/07-file.t runs after this test,
because one of its subtests relies on that asset being present.
This doesn't show up in Travis runs because the UI and API tests
are run in separate jobs, but it *does* show up in package
builds - you can see the test failing in OBS openQA package
build logs, for instance.

t/api/03-auth.t: don't actually wipe asset files from disk

---

t/lib/OpenQA/Test/FullstackUtils.pm

This is making some CI runs on PRs run forever at the moment:
Instead of having the test run forever and time out in CI, the utility function itself should have a maximum timeout.

Timeout for wait_for_developer_console_contains_log_message

---

docs/Contributing.asciidoc
lib/OpenQA/LiveHandler.pm
lib/OpenQA/Scheduler.pm
lib/OpenQA/Setup.pm
lib/OpenQA/WebSockets.pm
t/34-developer_mode-unit.t

Just print 'internal error' or if in development mode the error message.

Improve exception handling of additional daemons

---

assets/javascripts/ws_console.js

Unfortunately my latest improvements to the developer fullstack test also introduced new bugs... hopefully this is now sufficient.

Handle reusing existing connection in devel fullstack test

---

Makefile
docs/Installing.asciidoc
etc/openqa/openqa.ini
lib/OpenQA/Schema/ResultSet/AuditEvents.pm
lib/OpenQA/Setup.pm
lib/OpenQA/Task/AuditEvents/Limit.pm
lib/OpenQA/WebAPI/Plugin/AuditLog.pm
lib/OpenQA/WebAPI/Plugin/Gru.pm
openQA.spec
systemd/openqa-enqueue-audit-event-cleanup.service
systemd/openqa-enqueue-audit-event-cleanup.timer
t/14-grutasks.t
t/41-audit-log.t
t/data/41-audit-log/openqa.ini
t/lib/OpenQA/Test/Case.pm

WIP because the GRU task is not triggered anywhere so far.
---
See https://progress.opensuse.org/issues/52487

Delete old audit events according to configured storage duration

---

lib/OpenQA/Worker.pm
t/24-worker-overall.t

Fixup for https://github.com/os-autoinst/openQA/pull/2227

Fix worker crash when sending job ID

---

lib/OpenQA/WebSockets.pm
lib/OpenQA/WebSockets/Controller/API.pm
lib/OpenQA/WebSockets/Controller/Worker.pm
lib/OpenQA/WebSockets/Model/Status.pm
t/27-websockets.t
t/lib/OpenQA/Test/FakeWebSocketTransaction.pm

See https://progress.opensuse.org/issues/19424 and particular commit messages.

Improve transaction handling in web socket server, improve tests

---

t/24-worker-job.t

* See https://progress.opensuse.org/issues/55238
* Since this does not reproduce the issue the problem must be inside `_upload_log_file` itself

Test worker behavior if _upload_log_file fails

---

assets/javascripts/overview.js
lib/OpenQA/WebAPI/Controller/Test.pm
t/ui/10-tests_overview.t
templates/test/overview.html.ep

See https://progress.opensuse.org/issues/52493

Add machine filter in 'Test result overview'

---

t/api/11-bugs.t

See https://progress.opensuse.org/issues/55457
If there is a short delay between the update and the fetching of
"created_since=500" the test fails.
Now with 10 seconds it should usually pass.

Fix flaky test t/api/11-bugs.t

---

lib/OpenQA/Schema/Result/Jobs.pm

Related progress issue: https://progress.opensuse.org/issues/55076

Fix warning about undefined $testresdir

---

lib/OpenQA/Scheduler/Model/Jobs.pm

Related progress issue: https://progress.opensuse.org/issues/55319

scheduler: Fix warnings about undefined variables

---

docs/GettingStarted.asciidoc
docs/Installing.asciidoc

Related progress issue: https://progress.opensuse.org/issues/52730

docs: Mention most simple installation instructions and "clone-job" first

---

lib/OpenQA/Task/Asset/Limit.pm

Do not delete newly created assets with empty size to avoid race condition

Do not delete assets based on empty size

---

assets/assetpack.def
assets/javascripts/job_templates.js
lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
t/api/08-jobtemplates.t
t/ui/13-admin.t

Fixes: [poo#54149](https://progress.opensuse.org/issues/54149)

Render a diff of the job group YAML in preview/ save

---

openQA.spec

This time properly tested, see https://build.opensuse.org/package/show/home:okurz:branches:devel:openQA:fix:devel/openQA

spec: Fix 'devel' package (for real) with proper macro definition

---

lib/OpenQA/Worker/Job.pm

Add log of second virtio console to upload list

worker job: Add log of second virtio console to upload list

---

lib/OpenQA/Worker/WebUIConnection.pm

Upload errors are currently lacking context.
```
[2019-09-03T09:44:54.0381 CEST] [info] Enqueued Rsync cache request from 'rsync://openqa-staging-1.qa.suse.de/tests' to '/var/lib/openqa/cache/openqa-staging-1.qa.suse.de'
[2019-09-03T09:44:59.0504 CEST] [info] Finished to rsync tests
[2019-09-03T09:44:59.0506 CEST] [info] Preparing cgroups to start isotovideo
[2019-09-03T09:44:59.0508 CEST] [info] Starting isotovideo container
[2019-09-03T09:44:59.0542 CEST] [info] isotovideo has been started (PID: 16814)
[2019-09-03T09:44:59.0564 CEST] [info] 16814: WORKING 70030
[2019-09-03T09:46:10.0005 CEST] [error] 502 response: Proxy Error (remaining tries: 2)
[2019-09-03T10:04:44.0837 CEST] [error] Artefact upload failed: Proxy Error
[2019-09-03T10:06:02.0842 CEST] [info] Uploading …
```

Show more context in logs to make debugging easier

---

script/openqa-clone-custom-git-refspec

See http://mywiki.wooledge.org/BashFAQ/031
`[[ ]]` is the recommened test operator in modern bash.
Also the workaround with +x seems to be for a very old bash bug.
Always quoting variables is usually a good thing too.

Modernize bash tests

---

docs/UsersGuide.asciidoc
lib/OpenQA/Schema/Result/ScheduledProducts.pm
t/api/02-iso.t

See https://progress.opensuse.org/issues/30274

Change iso scheduling behavior to not obsolete older jobs anymore

---

openQA.spec

Extend the requires of openQA-devel and make them easier to review

---

docker/travis_test/Dockerfile
openQA.spec

This reverts 2308 2310 and 2313 and adds minion require

Revert back to duplicating dependencies in dockerfile

---

.travis.yml
docs/Contributing.asciidoc
docs/ExternalResults.asciidoc
docs/Installing.asciidoc
docs/WritingTests.asciidoc
script/generate-documentation

- Build docs and update branch locally
- Mention all needed dependencies
- Show and fail on errors
- Leave (Travis)CI in charge of what to build/ generate
- Fix errors in documentation markup (which were previously hidden)
- Publish schema(s) as well ([poo#56426](https://progress.opensuse.org/issues/56426))

Docs generate fixes

---

lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
openQA.spec
t/api/08-jobtemplates.t

See https://progress.opensuse.org/issues/56876
The original settings hash was modified in the loop.
I sorted all keys in `JobTemplate.pm` to make behaviour reproducible in general.
The fix uses `Storable::dclone()` like discussed in chat to make a deep copy.
(Followup to #2329)

Yaml expansion

---

assets/javascripts/test_result.js
docs/UsersGuide.asciidoc
docs/WritingTests.asciidoc

We should only advertise this feature once it is complete. Hence a separate draft PR for the documentation.

Update documentation for START_DIRECTLY_AFTER_TEST

---

assets/javascripts/tests.js
lib/OpenQA/Scheduler/Model/Jobs.pm
lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/Schema/Result/ScheduledProducts.pm
lib/OpenQA/Schema/Result/Workers.pm
lib/OpenQA/Schema/ResultSet/Jobs.pm
lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
lib/OpenQA/WebAPI/Controller/API/V1/Worker.pm
lib/OpenQA/WebSockets.pm
lib/OpenQA/WebSockets/Client.pm
lib/OpenQA/WebSockets/Controller/API.pm
lib/OpenQA/WebSockets/Controller/Worker.pm
lib/OpenQA/Worker.pm
lib/OpenQA/Worker/CommandHandler.pm
lib/OpenQA/Worker/Job.pm
t/05-scheduler-cancel.t
t/05-scheduler-dependencies.t
t/24-worker-jobs.t
t/24-worker-overall.t
t/24-worker-webui-connection.t
t/27-websockets.t
t/api/02-iso.t
t/lib/OpenQA/Test/FakeWebSocketTransaction.pm

See https://progress.opensuse.org/issues/41066 and https://progress.opensuse.org/issues/55835

Take directly chained dependencies into account when scheduling jobs

---

lib/OpenQA/Resource/Locks.pm

As discussed in Rocket Chat, i've cleaned up the `barrier_wait` sub a little bit to make it easier to understand.

Clean up resource lock code a little bit

---

docs/WritingTests.asciidoc

@asmorodskyi I'm having a look at the looking API because we recently noticed a problem with it: https://progress.opensuse.org/issues/57017
Maybe you can have a look whether I understood/rephrased the documentation correctly.

Improve language of locking API documentation

---

lib/OpenQA/LiveHandler.pm
lib/OpenQA/Setup.pm

See https://progress.opensuse.org/issues/57113

Prevent loading arbitrary plugins in live view handler

---

assets/javascripts/admin_assets.js
lib/OpenQA/WebAPI/Controller/API/V1/Asset.pm
t/api/02-assets.t
t/ui/13-admin.t

See https://progress.opensuse.org/issues/55634

Improve deleting a single asset in WebUI

---

lib/OpenQA/WebAPI/Plugin/ObsRsync/Task.pm

Currently transport exception leads to a failed gru task and leaked active gru lock for the project.
This is urgent workaround, otherwise rsync will not work for a project for 10 hours after transport exception (until project lock expires).
Proper fix should come in https://progress.opensuse.org/issues/57233

Tolerate exceptions in OBS api call from ObsRsync plugin

---

lib/OpenQA/Scheduler.pm
lib/OpenQA/Scheduler/Client.pm
lib/OpenQA/Scheduler/Controller/API.pm
lib/OpenQA/WebSockets/Client.pm
lib/OpenQA/WebSockets/Controller/Worker.pm
t/05-scheduler-cancel.t
t/05-scheduler-dependencies.t
t/05-scheduler-full.t
t/05-scheduler-restart-and-duplicate.t
t/15-assets.t
t/api/01-workers.t
t/lib/OpenQA/Test/Utils.pm
t/ui/15-admin-workers.t

See https://progress.opensuse.org/issues/57017

Move incompletion logic when worker shows up again to scheduler

---

openQA-devel-test.spec

Tested in https://build.opensuse.org/project/show/home:okurz:branches:devel:openQA:feature:devel_test

Add package-test for openQA-devel allowing to check all dependencies in all repos

---

assets/javascripts/index.js

Fix issues with AJAX-enabled dashboard

---

assets/javascripts/tests.js

See https://progress.opensuse.org/issues/57413

Consider 'not yet' as most recent when sorting running tests by 'Started'

---

lib/OpenQA/Schema/Result/ScheduledProducts.pm
lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
t/api/08-jobtemplates.t

Fixes: [poo#56966](https://progress.opensuse.org/issues/56966)

Correctly propagate job template name from YAML

---

docs/WritingTests.asciidoc

* Rewrite sentences which were hard to understand
* Harmonize ASCII-art graphs with the way dependencies are displayed on the web UI
* Improve overall structure, e.g. "Worker requirements" is now sub heading of "Job dependencies"
---
It is still questionable whether the whole "Job dependencies" sub-tree belongs to "Writing multi-machine tests".

Improve job depencencies documentation

---

etc/openqa/openqa.ini

See https://progress.opensuse.org/issues/57662

Add note about plugins not to enable on typical production setups

---

docs/UsersGuide.asciidoc

Related to: [poo#57266](https://progress.opensuse.org/issues/57266)

Elaborate on differences between table and YAML

---

lib/OpenQA/Worker.pm
t/24-worker-overall.t
t/24-worker-webui-connection.t

See https://progress.opensuse.org/issues/56993 and particular commit messages

Improve the worker's brokenness detection

---

lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm

This makes the methods shorter and allows simpler unit tests in the future

Split data creation and update into two methods

---

lib/OpenQA/Schema/Result/JobModules.pm
lib/OpenQA/Schema/Result/ScreenshotLinks.pm
lib/OpenQA/Schema/ResultSet/Screenshots.pm
lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
t/42-screenshots.t

Followup to #2402, since Circle CI didn't work at the time it was opened.

Screenshots resultset

---

lib/OpenQA/WebAPI/Controller/Admin/JobTemplate.pm
t/ui/13-admin.t
templates/admin/job_template/index.html.ep

See https://progress.opensuse.org/issues/58133
---
Still a draft because at least the YAML editor tests are now failing.

Hide old job templates editor for new groups

---

docs/Contributing.asciidoc
docs/Installing.asciidoc

* Remove note about morbo (this is covered in Contributing)
* Mention the relevant variables

Extend filesystem documentation

---

lib/OpenQA/WebAPI/Controller/Test.pm
t/ui/25-developer_mode.t

See https://progress.opensuse.org/issues/58367

Fix VNC port info for ports > 99 in devel mode

---

lib/OpenQA/WebAPI/Controller/API/V1/JobGroup.pm
t/api/10-jobgroups.t

See: https://progress.opensuse.org/issues/58124

Deal with the error message when create/update job group

---

.circleci/dependencies.txt

Cpanel-JSON-XS to 4.15
Selenium-Remote-Driver to 1.35

Updates in CircleCI testing environment 28-Oct-2019

---

lib/OpenQA/CacheService/Model/Cache.pm
t/25-cache.t

See https://progress.opensuse.org/issues/55373

Calculate cache dir size if it is a symlink

---

.circleci/config.yml
script/generate-documentation

Need preserve GIT_ASKPASS between jobs
Fixes: [poo#57548](https://progress.opensuse.org/issues/57548)

Fix nightly job

---

codecov.yml
docs/Contributing.asciidoc
lib/OpenQA/Worker/Settings.pm
lib/OpenQA/Worker/WebUIConnection.pm

* Fix flaky coverage by use of uncoverable flag
* codecov: Simplify format

Coverage stabilization

---

script/client

See https://progress.opensuse.org/issues/58319

Document client's form parameter

---

script/fetchneedles

Tested on o3
Related progress issue: https://progress.opensuse.org/issues/58373

fetchneedles: Try to repair needle git repos on detached HEADs

---

.circleci/unstable_tests.txt

Related progress issue: https://progress.opensuse.org/issues/53858

Assume 25-cache-service.t to be stable since #2463

---

.circleci/unstable_tests.txt

Related progress issue: https://progress.opensuse.org/issues/59187

Assume 15-admin-workers is "stable" since a6dd3fee5

---

docker/travis_test/Dockerfile

See error in https://build.opensuse.org/package/show/devel:openQA/openqa_dev
Related progress issue: https://progress.opensuse.org/issues/53915

travis_test: Try to fix container on OBS

---

.circleci/config.yml

Related progress issue: https://progress.opensuse.org/issues/59984

Mark 05-scheduler-full.t as unstable due to recent instability

---

lib/OpenQA/Utils.pm
t/05-scheduler-full.t
t/25-cache-service.t
t/full-stack.t
t/lib/OpenQA/Test/Utils.pm

* t: Hide all output from diag calls in tests
* Prevent boilerplate text "$VAR1 =" in dumper output

Prevent boilerplate ; hide diag in terse test output mode

---

docs/UsersGuide.asciidoc

Fixes: [poo#60017](https://progress.opensuse.org/issues/60017)

Document typical issues with migration of job groups

---

lib/OpenQA/Task/Asset/Limit.pm
t/37-limit_assets.t

If a directory was modified after registration we need to keep it longer rather than relying on the initial time recorded in the database.
We also let DateTime calculate the days so we don't need magic numbers in seconds.
Fixes: https://progress.opensuse.org/issues/59888

Take directory mtime of assets into account

---

.circleci/unstable_tests.txt
t/data/openqa-trigger-from-obs/script/rsync.sh
t/lib/OpenQA/SeleniumTest.pm

https://progress.opensuse.org/issues/60035

Stabilize test t/api/plugin_obs_rsync_async.t

---

lib/OpenQA/Setup.pm
lib/OpenQA/WebAPI/Plugin/ObsRsync/Controller/Folders.pm
lib/OpenQA/WebAPI/Plugin/ObsRsync/Task.pm
t/config.t
t/ui/27-plugin_obs_rsync.t

Tweak configuration
Fix cosmetic bug when internal folders are shown as projects in '/admin/obs_rsync' route

Tweak obs rsync

---

docs/images/architecture.graphml
docs/images/architecture.svg

see particular commit messages
Fixes: https://progress.opensuse.org/issues/50531

Improve architecture diagram

---

docs/UsersGuide.asciidoc

Follow-up to #2530 documenting the enhanced behavior.
Fixes: https://progress.opensuse.org/issues/59888

Document the relevancy of file modifications for asset cleanup

---

t/api/14-plugin_obs_rsync_async.t
t/data/openqa-trigger-from-obs/script/rsync.sh

Control of timing of mock rsync.sh by presence of predefined file

Stabilize t/api/14-plugin_obs_rsync_async.t

---

lib/OpenQA/CacheService/Model/Cache.pm
t/25-cache.t

This is a possible solution for the problem where `/tmp` fills up with leftover temp files like `mojo.tmp.nq0vLzabb1zWmjGO`.
Turns out the cache service already was creating its own tmp directory under `/var/lib/openqa/cache/tmp`, but never actually used it. That means it always wrote all downloads to `/tmp` before moving them to `/var/lib/openqa/cache` after the download is finished. Since those directories are usually not on the same partition that can be quite costly.
Progress: https://progress.opensuse.org/issues/59391

Use the cache tmp directory for temporary download files

---

assets/assetpack.def

See https://progress.opensuse.org/issues/60413

Fix asset definition of SVG icon for running jobs
