os-autoinst/openQA

docs/Installing.asciidoc
openQA.spec
script/openqa-bootstrap
script/openqa-bootstrap-container

Ticket: https://progress.opensuse.org/issues/45365

Add tool to bootstrap openQA with only one command

---

lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
lib/OpenQA/Worker/Common.pm
lib/OpenQA/Worker/Jobs.pm
t/24-worker.t
t/api/04-jobs.t

Treat those errors as API failures so the worker does not try to
report connection issues with the web UI to the web UI.
See https://progress.opensuse.org/issues/45275
---
WIP because I still need to test.

worker: Fix handling errors caused by connection issues with web UI

---

script/tidy

Wrong version of perltidy. Found '20180220 ', expected '20181120'
Related progress issue: https://progress.opensuse.org/issues/45740

Check for correct perltidy version on execution

---

t/21-needles.t

This test seems to fail quite often in Fedora package builds, on
the "last_updated changed after updating needle from editor"
check. I'm not 100% sure, but I *think* this may be because
the test's `$needle` is not reliably refreshed by this approach
of calling `find` on the resultset again. Changing it to use
discard_changes instead seems to help.

21-needles.t: Use `discard_changes` instead of re-calling `find`

---

lib/OpenQA/Schema/Result/Jobs.pm

Otherwise their state will stay on assigned as only the result is updated
and then we reset it to scheduled if the worker finally wakes up
Related issue: https://progress.opensuse.org/issues/42986

Also set assigned jobs to parallel_failed

---

lib/OpenQA/Worker/Engines/isotovideo.pm

Tested locally together with
https://github.com/os-autoinst/os-autoinst/pull/1083
Local verification run:
```
openqa-clone-job --skip-chained-deps --from http://openqa.suse.de 2341662 \
WORKER_CLASS=qemu_x86_64_sle MAKETESTSNAPSHOTS=1 SKIPTO= \
EXIT_AFTER_START_INSTALL=1 \
CASEDIR=https://github.com/okurz/os-autoinst-distri-opensuse.git#test/custom_git_branch \
PRODUCTDIR=os-autoinst-distri-opensuse/products/sle _EXIT_AFTER_SCHEDULE=1
```
-> http://lord.arch/tests/1961/file/autoinst-log.txt
showing that the tests try to load the non-existing test module "not_welcome"
from the custom git repo and branch as specified instead of "welcome" which is
the module in the current master version of
os-autoinst/os-autoinst-distri-opensuse.
Related progress issue: …

Allow custom CASEDIR/PRODUCTDIR/ASSETDIR

---

profiles/apparmor.d/usr.share.openqa.script.worker

See https://openqa.opensuse.org/tests/829418/file/autoinst-log.txt
Verification run: https://openqa.opensuse.org/tests/829421
Related issue: https://progress.opensuse.org/issues/44327

apparmor: Fix custom git repo clone "env" denied

---

script/fetchneedles
script/openqa-bootstrap

I was running into some problems with `openqa-bootstrap`:
* the config file had been modified from a previous installation
* zypper failed due to a vendor change
* after the vendor change was fixed the script wouldn't re-run
With these changes, running the script
- will stop if eg. zypper is demanding attention
- existing user/database/needles are fine
- fetchneedles gained a log message which was invaluable for me to track down permission problems (due to the original very bad run)
- variables for database name/user

bootstrap: make errors fatal and deal with re-runs

---

lib/OpenQA/Worker/Engines/isotovideo.pm

Observed on power8:
```
Jan 17 20:23:54 power8 worker[15039]: Use of uninitialized value in concatenation (.) or string at /usr/share/openqa/script/../lib/OpenQA/Worker/Engines/isotovideo.pm line 245.
Jan 17 20:23:54 power8 worker[15039]: Use of uninitialized value $exit in numeric eq (==) at /usr/share/openqa/script/../lib/OpenQA/Worker/Engines/isotovideo.pm line 246.
```

worker: Fix two perl warnings

---

lib/OpenQA/Worker/Engines/isotovideo.pm

The exit code of "0" must not be evaluated in boolean context in perl.
Related progress issue: https://progress.opensuse.org/issues/46658

Fix regression of test caching failing introduced by c9735699

---

lib/OpenQA/Worker/Cache/Service.pm
lib/OpenQA/Worker/Engines/isotovideo.pm
t/25-cache-service.t

Prevents error like
openqaworker3 openqa-workercache[9158]: [e] Can't call method "info" on an undefined value at /usr/share/openqa/script/../lib/OpenQA/Worker/Cache/Service.pm line 101
on the cache service daemon.

Improve error handling in worker cache /status route

---

script/openqa-bootstrap-container

I was trying to run `openqa-bootstrap-container` on my TW but bumped into a few problems:
- Trying without root or sudo resulted in various commands being tried to be executed without checking that all of them errored out.
- Later on I kept getting error "Failed to create bus connection: Protocol error" and an apparent hang when trying to run the script as is, even though the container seemed to work fine when I manually looked at it.
These changes thus:
- Check if there are root rights and if not, asking to execute as root (sudo fine too)
- Exiting on error everywhere but in one place (zypper package installation causes error code even on success in this case)
- Checks existence of the container directory before continuing to allow trying a rerun of the command without causing problems. …

openqa-bootstrap-container: do more error checking, fix a hang

---

openQA.spec

Verification run: https://build.opensuse.org/package/live_build_log/home:okurz:branches:devel:openQA/openQA:openQA/openSUSE_Factory/x86_64

spec: Fix missing mention of 'openqa-clone-custom-git-refspec' in script/

---

docs/WritingTests.asciidoc

select_virtio_console() was replaced by select_serial_terminal()
in commit in os-autoinst-distri-opensuse 13018da1b ("Remove
select_virtio_console() and replace it with select_serial_terminal()")

Update serial terminal function

---

lib/OpenQA/Worker/Common.pm

This allows the HOST variable in `/etc/openqa/workers.ini` to be split by several white-spaces (including multiple spaces or tabs) instead of just only one single space (as before).

Split configured hosts by whitespace

---

lib/OpenQA/Task/Asset/Download.pm

The way scheduling works at least in Fedora, we may wind up with
multiple tasks to download the same asset. Since feef1726, this
may wind up causing them to run in parallel with each other, and
when this happens, the check which causes the task to bail if
the destination file already exists won't help, because the file
won't exist until one of the tasks *completes*. So we may well
go ahead and have multiple tasks all running in parallel and
downloading the same file, then all renaming it to the target
filename at the end. This probably won't break anything but it
sure will waste bandwidth. To avoid this happening, add the same
'guard' that was added to other non-self-parallel-safe tasks,
but using `$assetpath` as part of the guard name so download
tasks for *different* assets *can* run in …

Prevent download tasks for the same asset running in parallel

---

assets/javascripts/tests.js
assets/stylesheets/openqa_theme.scss
assets/stylesheets/test-details.scss
dbicdh/PostgreSQL/deploy/74/001-auto-__VERSION.sql
dbicdh/PostgreSQL/deploy/74/001-auto.sql
dbicdh/PostgreSQL/upgrade/73-74/001-auto.sql
dbicdh/_source/deploy/74/001-auto-__VERSION.yml
dbicdh/_source/deploy/74/001-auto.yml
lib/OpenQA/Schema.pm
lib/OpenQA/Schema/Result/JobModules.pm
lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/WebAPI/Controller/Test.pm
t/10-jobs.t
t/ui/01-list.t

If a test module has the result "skipped", it is currently treated as
failed.
This change ignore test module with result "skipped" to calculate the
overall result.
Ticket: https://progress.opensuse.org/issues/43259

Skip result "skipped" on calculate overall result

---

lib/OpenQA/Utils.pm
t/ui/10-tests_overview.t

Filter returned results only when one module was specified in the Module
filter field on Test Result Overview page. It returned no results while
using comma-separated module names.
The commit fixes the issue and allows to filter job groups by several
module names separated by comma (e.g. module1,module2).

Fix modules filter wrong results while using comma

---

script/openqa-clone-custom-git-refspec

Currently, `GROUP` var is not used and `_GROUP` is always set to `0`.

openqa-clone-custom-git-refspec: make use of GROUP var

---

lib/OpenQA/Worker/Engines/isotovideo.pm

For the time being seems that the dynamic schedule of tests with
caching seems a bit complicated. Mainly due to some tests using ASSET_\d
as part of an URL and others using it as a file to be expected to be
downloaded. The cache service should only treat assets as something to
download.
The feature introduced in #1855 is nice, but won't work with caching for
the time being. See https://progress.opensuse.org/issues/43511.
Note: This ~~feature~~ broke autoyast tests :)
One idea that I have is to introduce a separate [ASSET_LOCAL_](https://github.com/foursixnine/openQA/commit/304573d0d67dc029884831dad91404e0aca23082) for the cases when we _expect_ the cache service to actually download the thing and link it to the worker pool.
PS: With #1943 and subsequent related pr's, we wouldn't need to …

Revert support for ASSET_\d+_URL

---

lib/OpenQA/Worker/Engines/isotovideo.pm
lib/OpenQA/Worker/Jobs.pm

I think the most important case where the worker sometimes hangs is during, right before or right after the isotovideo startup. So I'd like to add a few more log lines in that stage. Compared to the length of the overall worker log this is actually nothing. But it would be useful to debug
* https://progress.opensuse.org/issues/47060
* https://progress.opensuse.org/issues/47087
---
@nicksinger Can you actually deploy this when it is merged? It would be sufficient to deploy on selected worker instances. We could reproduce the issue recently on `openqaworker2` and `grenache-1` so that would be good candidates.

Log isotovideo startup more detailed

---

cpanfile
docker/travis_test/Dockerfile
openQA.spec

Adding these dependencies is a prerequisite for #1999 which as I understand it has to be prepared before test cases can pass on the actual branch.

Add YAML::XS and JSON::Validator dependencies

---

lib/OpenQA/Worker/Cache.pm
lib/OpenQA/Worker/Cache/Service.pm
t/25-cache.t

While fixing our openQA staging machines for testing #1990 we stumbled over a problem with the cache service SQLite database. As it turns out there were no migrations used to manage the schema, so the commit https://github.com/os-autoinst/openQA/commit/bd72dca44f1a0e4d439be35ff109f0be3bfb28fb broke all workers that upgraded without clearing the `/var/lib/openqa/cache` directory. To make sure this doesn't happen again in the future i'm introducing `Mojo::SQLite` migrations in this pull request, so we have a versioned schema from now on.
This pull request also removes a call to `app->minion->reset;` from `OpenQA::Worker::Cache::Service`, which deleted all jobs from the job queue every time the cache service was restarted (even if the cache service minion was still running). That seemed …

Cache service migrations

---

lib/OpenQA/Utils.pm
t/16-utils-runcmd.t

I made openQA updating the needle Git repository before committing new needles. It seems that `git fetch origin master:master` does not work in production because the `master` branch is checked out there by default. The PR changes the command to `git remote update origin` which also works in that case. This change is hot-patched on OSD and seems to work.

Fix updating needle Git repository

---

script/openqa-clone-custom-git-refspec

Eg:
```
openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/6925 https://openqa.opensuse.org/tests/865136 INSTALLONLY=42 BETA=2
```

Allow specifying test vars for openqa-clone-custom-git-refspec

---

lib/OpenQA/Task/Asset/Limit.pm

These arguments were completely wrong, so far as I can tell.
Per https://mojolicious.org/perldoc/Minion#add_task , when you
add a task, the @_ array's contents are the job as the first
item, plus any items that were included in the array when
`enqueue()` is called. So in the example on the doc page,
the contents of @_ are the job, then 1, then 1 again.
When we enqueue `limit_assets` we just pass an empty array. So
the contents of @_ should be just the job. Then the subroutine
we use in the `add_task` call just calls `_limit` with the args
as $app and then the contents of @_. Put all that together, and
the args `_limit` actually receives should be just the app and
the job. There is no 'j' or 'url'.
This causes a real problem: if you go to the minion job monitor
UI and look at failed tasks, …

Correct limit_assets task arguments

---

lib/OpenQA/Utils.pm
t/16-utils.t

Just removing some more technical debt.

Remove safe_call from OpenQA::Utils since it is no longer needed

---

lib/OpenQA/WebAPI/GruJob.pm
t/14-grutasks.t

This should be the correct solution for #2008. It's ready for merging, but i might still add a few more test cases.
Progress: https://progress.opensuse.org/issues/48554

Gru tasks cleanup

---

docker/openqa_data/data.template/conf/openqa.ini
docs/Installing.asciidoc
etc/openqa/openqa.ini
lib/OpenQA/Setup.pm
lib/OpenQA/Utils.pm
t/16-utils-runcmd.t
t/config.t

It was already mentioned in the last PR that hard coding remote and branch names isn't nice.
So this reverts the behavior of openQA to not execute `git remote update <remote>` and `git rebase <branch>` by default. That would only happen anymore if openQA is configured to update from a given remote and branch.
---
Before deploying this we should adjust the config file on OSD and o3.

Don't hardcode remote and branch names for saving needles

---

dbicdh/PostgreSQL/deploy/75/001-auto-__VERSION.sql
dbicdh/PostgreSQL/deploy/75/001-auto.sql
dbicdh/PostgreSQL/upgrade/74-75/001-auto.sql
dbicdh/_source/deploy/75/001-auto-__VERSION.yml
dbicdh/_source/deploy/75/001-auto.yml
lib/OpenQA/Schema.pm
lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/Schema/Result/Workers.pm
t/38-workers-table.t

See https://progress.opensuse.org/issues/37312
---
The deletion was caused by a cascade delete in a relationship with the jobs table. This adds a test and fixes the problem by using `SET NULL` instead of cascade delete.

Prevent deletion of worker when deleting its current job

---

assets/javascripts/needleeditor.js
templates/step/edit.html.ep

Because it might take a few seconds on a production instance. Of course real-time feedback would be even better but this is a start.

Add loading indication when saving needle

---

lib/OpenQA/Parser.pm
lib/OpenQA/Parser/Result.pm
lib/OpenQA/Parser/Result/Node.pm
lib/OpenQA/Parser/Result/OpenQA.pm
lib/OpenQA/Parser/Result/OpenQA/Results.pm
lib/OpenQA/Parser/Result/Output.pm
lib/OpenQA/Parser/Result/Test.pm
lib/OpenQA/Parser/Results.pm
lib/OpenQA/WebAPI/Plugin/Gru.pm
t/30-test_parser.t

When i started removing all uses of the [Enterprise operator](https://metacpan.org/pod/distribution/perlsecret/lib/perlsecret.pod#Enterprise) (since it is not considered good style and hard to understand for those that are not Perl experts), i noticed that all related classes contain a lot more bad code. So i refactored them to a cleaner style and removed more technical debt in the process. There were various problems, convoluted map one-liners, multiple classes in a module, private functions being used across modules... and so on.

Remove all uses of the Enterprise operator

---

systemd/openqa-gru.service
systemd/openqa-webui.service

The GRU service is required for saving needles in the needle editor and might be required for other background tasks in the future.

Make openqa-webui.service depend on openqa-gru.service

---

lib/OpenQA/Schema.pm
lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Controller/Admin/Influxdb.pm
lib/OpenQA/WebAPI/Plugin/Gru.pm
t/api/13-influxdb.t
t/lib/OpenQA/Test/Database.pm
t/ui/12-needle-edit.t

This patch adds a new public API endpoint `/admin/influxdb/minion`, similar to `/admin/influxdb/jobs`. It should contain all the stats needed to improve monitoring. I've also fixed a small bug with tmp schema handling in tests, where Gru would still use the default schema. The `$SINGLETON` variable in `OpenQA::Schema` is only a first step for a more complete cleanup in a future pull request.

Allow monitoring of Gru/Minion

---

lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Controller/API/V1/Locks.pm
lib/OpenQA/WebAPI/Controller/Admin/JobGroup.pm
lib/OpenQA/WebAPI/Controller/Admin/JobTemplate.pm
lib/OpenQA/WebAPI/Plugin/Helpers.pm
t/13-joblocks.t
t/api/13-influxdb.t

While showing how to use validation properly earlier today i noticed that quite a few of the current uses in openQA did not actually work. Most could actually be replaced with a route placeholder type (`<job_id:num>`). But i was still a little unhappy that we did not have a clean example for how to do input validation right. So i also cleaned up `OpenQA::WebAPI::Controller::API::V1::Locks`, and i hope it can serve that purpose from now on.

Remove dead validation code and replace it with route placeholder types

---

lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
t/api/08-jobtemplates.t
t/lib/OpenQA/Test/Case.pm

Currently the audit log has messages like this:
{ "affected_rows": null }

Pass affected_rows correctly in openqa_jobtemplate_create

---

lib/OpenQA/LiveHandler.pm
lib/OpenQA/Resource/Jobs.pm
lib/OpenQA/Resource/Locks.pm
lib/OpenQA/Scheduler/Scheduler.pm
lib/OpenQA/Schema.pm
lib/OpenQA/Setup.pm
lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Plugin/Gru.pm
lib/OpenQA/WebSockets/Server.pm
script/clean_needles
script/create_admin

This should be a rather harmless change. Our `DBIx::Class` schema is used as a singleton object that we access from all over OpenQA. But so far we accessed it in various inconsistent ways, sometimes storing the object in attributes or state variables for no reason at all. That can result in unintended copies and hard to debug problems when you end up with multiple instances of the schema in different states. So i've replaced those with a single `OpenQA::Schema->singleton` class method that you can always use to get the right instance. `OpenQA::Schema::connect_db()` and `OpenQA::Schema::disconnect_db()` still exist, but are only used for controlling the actual database connection now. There are still a few `schema` shortcut methods, but they all just delegate to the singleton instance now.

Unify schema access with a singleton method

---

assets/javascripts/admin_needle.js
cpanfile
lib/OpenQA/Schema/Result/Needles.pm
lib/OpenQA/Task/Needle/Delete.pm
lib/OpenQA/Task/Needle/Save.pm
lib/OpenQA/WebAPI/Controller/Admin/Needle.pm
lib/OpenQA/WebAPI/Controller/Step.pm
lib/OpenQA/WebAPI/GruJob.pm
lib/OpenQA/WebAPI/Plugin/Gru.pm
lib/OpenQA/WebAPI/Plugin/Helpers.pm
openQA.spec
t/ui/21-admin-needles.t

* Avoid interference with saving needles via the needle editor by
preventing saving and deletion to run in parallel.
* Remove one more (potentially long) blocking operation from the event
loop
* Reduce number of API requests by deleting 5 needles at a time
* Change the commit message to "Remove $dir/$name"
(e.g. "Remove sle-15-SP1/password-prompt-20190313")
See https://progress.opensuse.org/issues/49175
---
I'm aware that common parts of `OpenQA::WebAPI::Controller::Admin::Needle::delete` and `OpenQA::WebAPI::Controller::Step::save_needle_ajax` should be extracted to avoid duplicating code.

Make needle deletion a Minion job

---

docs/Installing.asciidoc

When a user install openQA from official repositories, and then try to install the version from devel project, it often comes to the situation where dependency conflicts appear.
These hints should help the user to fix them and to be aware of the issue.

Add hints to fix dependencies when using devel

---

docs/WritingTests.asciidoc
lib/OpenQA/Schema/Result/Jobs.pm
t/05-scheduler-cancel.t

As discussed extensively in
https://progress.opensuse.org/issues/46295 , openQA job logic
makes an assumption that, any time a parallel child fails or is
cancelled, its parent and any other pending children of that
parent ought to be cancelled. This is the behaviour SUSE's tests
expect, but it is not the behaviour Fedora's tests expect. In
Fedora we have several cases of clusters where a parallel parent
acts as a server to multiple unrelated child tests; if one of
the children fails, that does not mean the parent and all other
children must be cancelled.
This patch adds a global config option to set whether parallel
parents with other pending children (and hence those children)
will be cancelled when one child fails or is cancelled. It
defaults to 1, i.e. the current behaviour. …

Option to not cancel parallel parents with still-pending children

---

docker/travis_test/Dockerfile
docs/WritingTests.asciidoc
lib/OpenQA/Worker/Jobs.pm

Unlike virtio console on qemu, which creates virtio_console.log
file which needs to be renamed to serial_terminal.txt svirt
creates this file directly.
This is a worker support for PR
https://github.com/os-autoinst/os-autoinst/pull/1109
PoC: 
http://quasar.suse.cz/tests/1892#downloads
http://quasar.suse.cz/tests/1892/file/serial_terminal.txt

worker: Upload serial_terminal.txt for svirt backend

---

lib/OpenQA/Schema/Result/Users.pm
lib/OpenQA/Schema/ResultSet/Users.pm
lib/OpenQA/WebAPI/Auth/Fake.pm
lib/OpenQA/WebAPI/Auth/OpenID.pm
lib/OpenQA/WebAPI/Auth/iChain.pm
script/create_admin
t/06-users.t
t/lib/OpenQA/Test/Case.pm

There was a pretty ugly hack in `OpenQA::Test::Case` for mock logins. That hack broke when Mojolicious got a little more secure recently. This PR reimplements the functionality, but only uses public Mojolicious APIs which are unlikely to break. And i've also used the opportunity to fix `create_user`, which shouldn't have been a function (but a resultset method).
Progress: https://progress.opensuse.org/issues/49946

Mojolicious 8.13 compatibility

---

lib/OpenQA/Task/Asset/Limit.pm
lib/OpenQA/Task/Job/Limit.pm

This should take care of the foreign key violation issues with multiple limit_* jobs running in parallel.
Progress: https://progress.opensuse.org/issues/49886

Prevent multiple limit_* tasks from running in parallel

---

assets/javascripts/admin_worker.js
lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Controller/API/V1/Worker.pm
lib/OpenQA/WebAPI/Controller/Admin/Workers.pm
lib/OpenQA/WebAPI/Plugin/AuditLog.pm
t/api/01-workers.t
t/ui/15-admin-workers.t
templates/admin/workers/index.html.ep

Add a delete function in Workers module. When worker status
is offline, and the login user is administrator, show the delete
action. Users can click delete action to remove the offline worker.
Related ticket: 
https://progress.opensuse.org/issues/48791
Signed-off-by: Liu Xiaojing <xiaojing.liu@suse.com>

Allow deleting offline workers via API and web UI

---

systemd/openqa-worker-cacheservice-minion.service
systemd/openqa-worker-cacheservice.service

This enables better control over the openQA units on servers.

Add cacheservice as part of openqa-worker.target

---

assets/javascripts/admin_worker.js
lib/OpenQA/Events.pm
lib/OpenQA/Schema/Result/ScheduledProducts.pm
lib/OpenQA/WebAPI/Controller/API/V1/Worker.pm

* Make OpenQA::Events::emit_event a non-static member function: https://github.com/os-autoinst/openQA/pull/2036/files/e5bcd1a5fdc391ce44bd909d582b93753e9ac1c8#r271654290
* Fix 2 details of https://github.com/os-autoinst/openQA/pull/2027 (indentation and HTTP status code).
---
@Amrysliu So keep in mind that `script/tidy` does not work for JavaScript (the function you've added had tabs and spaces mixed).
Unfortunately that are not the only bugs in the PR for deleting workers. But I've left the remaining issues for you:
* The line `$(deleteLink).parent().parent().remove();` does not really work. If you use the pagination or basically any data tables feature the row will be inserted again. You have to use the data tables API: https://datatables.net/reference/api/row().remove()
* I'd also use …

Fix PR leftovers

---

openQA.spec

The extremely long lines tend to cause confusion when it comes to
checking existing dependencies and if something needs to be added.
can use linebreaks here afterall?

openQA.spec: multiline macros for services and dependencies

---

assets/javascripts/admin_worker.js
t/ui/15-admin-workers.t
templates/admin/workers/index.html.ep

1. Use row(tr).remove.draw() instead of $(tr).remove(),
as it might remove the specified row from the DataTable completely.
2. Use a icon to replace the delete text link.
fixes: progress#48791
Signed-off-by: Liu Xiaojing <xiaojing.liu@suse.com>

Fix the remaining issues of deleting workers

---

profiles/apparmor.d/usr.share.openqa.script.worker

- bash moved to /usr/bin/ in Tumbleweed
- pkill didn't move yet, but being prepared can't hurt ;-)

Update AppArmor profile for usrMerge (boo#1132350)

---

script/openqa-bootstrap

Pulling the full repository is slower and requires more disk space than using shallow pull.
`$ time git clone --depth 1 https://gitlab.suse.de/openqa/os-autoinst-needles-sles.git`
Cloning into 'os-autoinst-needles-sles'...
remote: Counting objects: 17155, done.
remote: Compressing objects: 100% (15213/15213), done.
remote: Total 17155 (delta 2040), reused 16509 (delta 1942)
Receiving objects: 100% (17155/17155), 683.02 MiB | 910.00 KiB/s, done.
Resolving deltas: 100% (2040/2040), done.
Checking out files: 100% (17588/17588), done.
**real	12m58.397s**
user	0m43.839s
sys	0m23.478s
`$ time git clone  https://gitlab.suse.de/openqa/os-autoinst-needles-sles.git os-autoinst-needles-sles-full`
Cloning into 'os-autoinst-needles-sles-full'...
remote: Counting objects: 51293, done.
remote: …

Clone only the latest revision of the SLE needles

---

script/openqa-clone-custom-git-refspec

Avoid cases where the Custom git ref spec script fails to get details on the pull request due to rate limiting on the github api and creating tests that will inevitably fail
[sle-15-SP1-Installer-DVD-aarch64-Buildnull_os-autoinst-distri-opensuse_7330-extra_tests_in_textmode@null_os-autoinst-distri-opensuse_null@aarch64](https://openqa.suse.de/tests/2828324).

 Allow authenticated calls to the github api 

---

script/openqa-clone-custom-git-refspec

Otherwise one just gets `parse error: Invalid numeric literal at line 1, column 10` which is not very useful. This change also prints the the URL which was queried and the contents which couldn't be parsed.

Improve JSON parse errors in openqa-clone-custom-git-refspec

---

profiles/apparmor.d/usr.share.openqa.script.worker

Opening qcow2 image has denied by apparmor.
type=AVC msg=audit(1547117832.842:491): apparmor="DENIED" operation="file_lock" profile="/usr/share/openqa/script/worker" name="/var/lib/openqa/share/factory/hdd/opensuse-Tumbleweed-x86_64-20190108-gnome@64bit.qcow2" pid=21062 comm="qemu-img" requested_mask="k" denied_mask="k" fsuid=456 ouid=458

apparmor: rk permission on hdd contents

---

assets/javascripts/job_templates.js
assets/stylesheets/admin-pages.scss
lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
lib/OpenQA/WebAPI/Plugin/YAMLRenderer.pm
public/schema/JobTemplate.yaml
t/api/06-products.t
t/api/08-jobtemplates.t
t/fixtures/04-products.pl
t/ui/13-admin.t
templates/admin/job_template/index.html.ep

This is the route updating job templates according to YAML, which may include adding, modifying or deleting of test suites.
On the UI side, a text editor is provided as well as a little guide to the format. The "preview" mode allows trying out the changes without modifying the database.
Fixes: [poo#46670](https://progress.opensuse.org/issues/46670)

Import of job template specification from YAML

---

assets/javascripts/admintable.js
assets/javascripts/audit_log.js
assets/javascripts/openqa.js
assets/stylesheets/admin-pages.scss
t/ui/13-admin-no-login.t
t/ui/13-admin.t
templates/admin/audit_log/index.html.ep
templates/admin/machine/index.html.ep
templates/admin/product/index.html.ep
templates/admin/test_suite/index.html.ep

See https://progress.opensuse.org/issues/50963
Note that the way the editing works remains almost the same. I just embedded it into the DataTable.
---
WIP because tests likely need to be adapted. Also defaults like the number of rows per page could still be adjusted.
But I've tested already manually. Especially with the testsuites from OSD  the faster loading time is notable and that the page is responsive while loading the table contents is also a plus.

Make admin tables use DataTables correctly

---

lib/OpenQA/Git.pm
lib/OpenQA/Schema/Result/Needles.pm
lib/OpenQA/Task/Needle/Save.pm
lib/OpenQA/Utils.pm
t/16-utils-runcmd.t

* New Mojo class `OpenQA::Git`
* Use the new class for needle editing
* Adapt the unit tests
Related: [poo#50675](https://progress.opensuse.org/issues/50675)

Split off git support into its own class

---

lib/OpenQA/Worker/Engines/isotovideo.pm

Caching of the UEFI_PFLASH_VARS is often causing mixed messages to test
reviewers, as it will sometimes not be used and thus was declared non
critical on #1737 and #1732

Skip UEFI_PFLASH_VARS asset when UEFI is disabled

---

assets/stylesheets/test-details.scss
docs/GettingStarted.asciidoc
lib/OpenQA/BuildResults.pm
lib/OpenQA/Jobs/Constants.pm
lib/OpenQA/Schema/Result/JobNextPrevious.pm
lib/OpenQA/WebAPI/Plugin/Helpers.pm
lib/OpenQA/Worker/Jobs.pm
t/lib/OpenQA/Test/FullstackUtils.pm
templates/test/list.html.ep

This change aims to treat those jobs still like incomplete jobs. It makes it only more obvious in the web UI that the timeout exceeded.
See https://progress.opensuse.org/issues/50225

Add an own result jobs which exceeded the timeout

---

lib/OpenQA/WebAPI/Controller/Test.pm

Those IDs are not numerical so 'eq' must be used.
This is a 'spin off' of https://github.com/os-autoinst/openQA/pull/2067 because it makes sense to merge this tiny change soon so the dependency graph always works as expected and does not produce any Perl warnings on the log.

Fix comparision of cluster ID for dependency graph

---

docker/travis_test/Dockerfile
openQA.spec

When trying to preview/validate YAML in the editor on osd, the following error message can be seen:
[JSON::Validator] The optional YAML::XS module is missing or could not be loaded:
YAML::XS version 0.67 required--this is only version 0.38 at (eval 33558) line 1.
BEGIN failed--compilation aborted at (eval 33558) line 1.

Require YAML::XS >= 0.67

---

lib/OpenQA/Utils.pm
t/10-jobs.t

See https://progress.opensuse.org/issues/51749

Prevent accessing comment label without check for undef

---

lib/OpenQA/WebAPI/Controller/API/V1/Job.pm

While it was suggested I use `latest:1, scope: relevant` as arguments to the `jobs` API method, I realized these aren't documented anywhere. So based on reading the implementation of [complex_query](https://github.com/os-autoinst/openQA/blob/master/lib/OpenQA/Schema/ResultSet/Jobs.pm#L222) I'm attempting to fix that.

Document latest/scope{relevant,current}/limit in jobs

---

profiles/apparmor.d/usr.share.openqa.script.worker

After upgrading the o3 aarch64 worker the workers failed to startup due
to `lspci` failing to read /proc/cpuinfo as access to /proc/ was denied.
Profile tested locally on aarch64.o.o.
Related progress issue: https://progress.opensuse.org/issues/50453

apparmor: Fix worker startup on openSUSE Leap 15.1

---

lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
t/api/08-jobtemplates.t

See https://progress.opensuse.org/issues/52490
---
This does not implement the issue but prevents the immediate problem of polluting the database. Besides, it makes no sense to log events which didn't happen for real.

Don't log jobtemplate_create event if in preview mode

---

openQA.spec

Patch out Perl::Tidy dependency in spec-file to prevent mismatch in
build tests as we are not calling "tidy" during build-time anyway.
Fixes problems as observed in
https://build.opensuse.org/package/live_build_log/devel:openQA:tested/openQA/openSUSE_Factory/x86_64
```
[  191s] ! Couldn't find module or a distribution Perl::Tidy (== 20181120)
[  191s] ! Installing the dependencies failed: Installed version (20190601) of Perl::Tidy is not in range '== 20181120'
```
Tested locally by overwriting the spec-file of an OBS checkout.

spec: Fix Perl::Tidy mismatch in build tests

---

openQA.spec

It is no longer required since the it has been patched out from the CPAN file.

Remove tidy from spec file

---

docs/UsersGuide.asciidoc
docs/WritingTests.asciidoc
openQA.spec
script/openqa-clone-job

By providing a nicer script name already in source we can also reference
that path in the documentation. In before the script link
`openqa-clone-job` was only provided in the openSUSE package.
I verified the openSUSE package build locally.

Provide the script `openqa-clone-job` already in source

---

lib/OpenQA/Worker/Cache.pm

Fixes a regression introduced by 4f546904. See
https://openqa.suse.de/tests/2956457/file/autoinst-log.txt for an
example of the problem.

Cache: Fix missing download progress output and warning

---

lib/OpenQA/Scheduler.pm
lib/OpenQA/Shared/Controller/Auth.pm
lib/OpenQA/Shared/Plugin/Helpers.pm
lib/OpenQA/WebSockets.pm
t/27-websockets.t

This is a quick fix for the problem where the scheduler and websocket servers required an API key for localhost IPC if IPv6 was used instead of IPv4.

Treat IPv4 and IPv6 the same for localhost authentication

---

lib/OpenQA/Schema/Result/Jobs.pm
t/api/02-iso.t

the cluster_info already contains the full cluster, so we only need the parallel parts.

Don't take the full cluster as possibly blocked

---

docs/Installing.asciidoc

Since the systemd job openqa-gru is a dependency of openqa-webui just as
well as the livehandler we do not need to explicitly start or enable it.

docs: No need to start openqa-gru explicitly

---

lib/OpenQA/LiveHandler.pm
lib/OpenQA/Scheduler.pm
lib/OpenQA/Scheduler/Client.pm
lib/OpenQA/Utils.pm
lib/OpenQA/WebAPI.pm
lib/OpenQA/WebSockets.pm
lib/OpenQA/WebSockets/Client.pm
script/openqa
script/openqa-livehandler
script/openqa-scheduler
script/openqa-websockets
systemd/openqa-scheduler.service
systemd/openqa-websockets.service
t/16-utils.t
t/lib/OpenQA/Test/Utils.pm

This PR makes all our micro services on the webui side use the `OPENQA_BASE_PORT` environment variable. Allowing for multiple webui instances to run on the same host.
Additionally the websocket and scheduler services also use the Mojolicious command system consistently with the other services now. So the tooling available (routes command and the like) as well as configuration options for systemd task files are all the same.
Progress: https://progress.opensuse.org/issues/52685

Add support for OPENQA_BASE_PORT environment variable

---

lib/OpenQA/Schema/Profiler.pm

This should revert the profiler to the previous behaviour that prevented #2119 from happening.
Progress: https://progress.opensuse.org/issues/53285

Defer loading the schema in OpenQA::Schema::Profiler

---

openQA.spec

See
https://build.opensuse.org/package/live_build_log/devel:openQA/openQA/openSUSE_Tumbleweed/x86_64
failing on finding DBIx::Class::DeploymentHandler during build time test
execution.

Fix missing dependency in package buildtime tests as well

---

lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
public/schema/JobTemplate.yaml
t/api/08-jobtemplates.t
t/ui/13-admin.t
templates/admin/job_template/index.html.ep

User feedback included that it would make sense for the defaults to go first and the test suites to go last. There's also a consideration that the `architectures` key really specifies a list of test suites. So my solution is to rename the key to `test-suites` which automatically makes it the last top-level key.
Use of hyphes in YAML is preferred as I understand, and although it requires quoting in Perl I'd go by what users will be exposed to rather than what's less of a tiny inconvenience for developers in this case. User feedback is why I'm doing the renaming as well afterall.
- These are in fact a list of test suites
- They will appear at the bottom by default
Related: [poo#46673](https://progress.opensuse.org/issues/46673)

Rename architectures to scenarios

---

lib/OpenQA/Worker/Engines/isotovideo.pm

Normally `$asset_request->output` would be empty causing output in the
log file like in
https://openqa.opensuse.org/tests/962019/file/autoinst-log.txt
```
[2019-06-18T08:53:00.0081 CEST] [debug] Downloading opensuse-Tumbleweed-aarch64-20190614-textmode@aarch64.qcow2 - request sent to Cache Service.
[2019-06-18T08:53:05.0141 CEST] [debug] Download of opensuse-Tumbleweed-aarch64-20190614-textmode@aarch64.qcow2 processed
[2019-06-18T08:53:05.0145 CEST] [debug]
[2019-06-18T08:53:05.0169 CEST] [debug] Downloading openSUSE-Tumbleweed-DVD-aarch64-Snapshot20190614-Media.iso - request sent to Cache Service.
[2019-06-18T08:53:10.0218 CEST] [debug] Download of openSUSE-Tumbleweed-DVD-aarch64-Snapshot20190614-Media.iso processed
[2019-06-18T08:53:10.0221 CEST] [debug]
```
This can be prevented by …

Prevent blank line in worker caching output

---

lib/OpenQA/WebSockets.pm
lib/OpenQA/WebSockets/Model/Status.pm
lib/OpenQA/WebSockets/Plugin/Helpers.pm
t/20-workers-ws.t
t/27-websockets.t
t/lib/OpenQA/Test/Utils.pm

I made a small mistake when refactoring the websocket server. Those helpers should have been part of the model. There might be more opportunities to move code from `OpenQA::WebSockets::Controller::Worker` to the model, but that's more complicated, so we can see about that later.

Move websocket server helpers to the model

---

script/openqa-bootstrap

- Add clone-job at the end of the bootstrap script, in case there are parameters passed in this. the script will expands them after `clone_job.pl -from·openqa.opensuse.org`.

Integrate clone-job into bootstrap

---

docker/travis_test/Dockerfile

For https://github.com/os-autoinst/openQA/pull/2134

travis_test: Ensure shellcheck is installed as part of dependencies

---

lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
lib/OpenQA/WebAPI/Controller/Step.pm
lib/OpenQA/WebAPI/Controller/Test.pm
public/schema/JobTemplate.yaml
t/api/08-jobtemplates.t
templates/admin/job_template/index.html.ep

Despite we might think that spelling out words is better for
understanding we have to stick to our defined wording and also the API.
http://open.qa/docs/#concepts defines the word "distri" and we also use
that in os-autoinst as well as the actual test distributions, e.g.
os-autoinst-distri-opensuse. In case we really want to change that we
would need to handle all downstream uses as well.
Related progress issue: https://progress.opensuse.org/issues/46667

Revert to usual wording "distri" in YAML schedules

---

script/openqa-clone-custom-git-refspec

Message from "shellcheck":
"SC2070: -n doesn't work with unquoted arguments. Quote or use [[ ]]."

openqa-clone-custom-git-refspec: Fix use of "-n" on GITHUB_TOKEN

---

t/full-stack.t
t/lib/OpenQA/SeleniumTest.pm

In the full-stack test the cleanup code in the `END` block got triggered twice because one of the forked selenium processes used `exit` instead of `POSIX::_exit`. This fixes the problem #2147 was adding workarounds for.

Do not trigger test cleanup code from forked processes

---

script/client

In case of no useful HTML status code received at all the openQA client
would previously output two misleading perl warnings about the comparison
with undefined values. This commit provides fallback values in this case
while preserving the code and error message output when available.
Example output when trying to connect to an unavailable local https
server and against a local http server without using valid credentials:
```
$ openqa-client --host https://localhost jobs post
ERROR:  - Connection refused
$ openqa-client --host http://localhost jobs post
ERROR: 403 - Forbidden
{ error => "Not authorized", error_status => 403 }
```

client: Prevent warnings when receiving no HTML status code at all

---

assets/javascripts/job_templates.js

Although tabs are valid characters in YAML, spaces are used for indentation and mixing tabs with spaces for indentation results in error messages that can be very confusing to deal with.
We always indent with spaces, so it makes sense to enforce spaces.
The code is based [on a snippet](https://codemirror.net/doc/manual.html#keymaps) from the official docs.

Always use spaces in CodeMirror editor

---

script/fetchneedles

For a shell script which does not support a "quiet" mode we should try
to stick to the *nix best practices of not outputtin anything unless it
is an error. The main reason for that is to not spam the cron account
running "fetchneedles" recurringly with unneeded cron output emails.

fetchneedles: Go back to old, quiet mode

---

script/openqa-clone-job

Instead of needing the job ID split out we can also specify full test
URLs which makes copy-paste easier :)

openqa-clone-job: Add support for full test URLs

---

script/modify_needle
script/tidy

This fixes tidy exchanging symlinks with file-copies in case the symlink
target appears later in the alphabet. Also we previously did not cover
the files in the "script/" subdirectory unless we used the '.pl'
extensions.
Therefore also apply current tidy rules to all script files in script/.

tidy: Apply to all regular perl modules and scripts

---

lib/OpenQA/WebSockets/Controller/Worker.pm
t/27-websockets.t

Currently the websocket server responds with a 500 error when a worker tries to connect that is not in the database. This patch fixes the broken render call responsible and replaces the useless `Unauthorized` message with `Unknown worker`.

Fix handling of unknown workers in the websocket server

---

assets/javascripts/job_templates.js
lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
t/api/08-jobtemplates.t

Updating or deleting test suites which are associated with a group managed in a YAML template should be an error.
- `create` and `destroy` render an error if a YAML template is set
- Deletion of templates needs to handle errors
Follow-up for: #2103

Lock test suites in YAML-based groups for manual updates and deletion

---

Makefile
docs/Contributing.asciidoc
openQA.spec

https://build.opensuse.org/package/live_build_log/home:okurz:branches:devel:openQA:make_test_with_database/openQA/openSUSE_Tumbleweed/x86_64 shows the verification in the package build

Add make target "test-with-database" for easier test database setup

---

openQA-worker-test.spec

See https://build.opensuse.org/package/live_build_log/home:okurz:branches:devel:openQA:worker_spec_test/openQA-worker-test/openSUSE_Tumbleweed/x86_64 for for the successful execution of the self-test within OBS based on the linked package "openQA-worker-test"

Add package self-test for worker as well

---

script/openqa-bootstrap-container

See https://openqa.opensuse.org/tests/976530#step/openqa_bootstrap_container/15

openqa-bootstrap-container: Fix package list passed as single string

---

docker/travis_test/Dockerfile

Tested with
```
docker run -it --rm -v $PWD:/opt/openqa:ro registry.opensuse.org/opensuse/leap:42.3 sh -c 'zypper ref && zypper -n in python3-future python3-requests python3-base && /opt/openqa/script/openqa-label-all --help'
```

travis_test: Fix typo in 'python3-future'

---

script/openqa-clone-job

* Use 'http' scheme if omitted instead of printing Perl warnings
* Allow specifying only a domain
The openqa-clone-job script worked this way before support for full test URLs was added (https://github.com/os-autoinst/openQA/pull/2137).

openqa-clone-job: Improve handling --from parameter

---

lib/OpenQA/Utils.pm

This came up in #2102 as an unrelated warning.
```
Prototype mismatch: sub OpenQA::Git::run_cmd_with_log_return_error ($) vs none at /usr/lib/perl5/vendor_perl/5.18.2/Test/MockModule.pm line 135.
Prototype mismatch: sub OpenQA::Git::run_cmd_with_log_return_error: none vs ($) at /usr/lib/perl5/vendor_perl/5.18.2/Test/MockModule.pm line 135.
```
Unsurprisingly all uses of prototypes in `OpenQA::Utils` were pointless, so i just removed them, fixing the warnings in the process.
The `exists_worker` function appears to be dead code that was [never used](https://github.com/os-autoinst/openQA/commit/2f4280b3229cf3e6c172664485a31d1ef7ff760c).

Remove dead code from OpenQA::Utils

---

docker/openqa_data/Dockerfile
docker/webui/Dockerfile
docker/worker/Dockerfile
docker/worker/kvm-mknod.sh
script/openqa-bootstrap-container

`script/openqa-bootstrap-container` has been tested successfully on aarch64.

Make containers non-x86 archs friendly and update to leap 15.1

---

script/generate-documentation

Related progress issue: https://progress.opensuse.org/issues/52730

generate-documentation: Fix wrong script path introduced by 81df2fd

---

docs/Installing.asciidoc
docs/UsersGuide.asciidoc

As observed on e.g.
http://open.qa/docs/#_show_previous_results_in_test_results_page_gh538
the quotes and apostrophes were rendered incorrectly by asciidoctor as
well as github in e.g.
https://github.com/os-autoinst/openQA/blob/master/docs/Installing.asciidoc#introduction
whereas locally using the tool "asciidoc" or pandoc – as used for
conversion in https://github.com/os-autoinst/openQA/pull/2127 – renders
fine with the `` style. This commit changes to the style preferred by
asciidoctor which we use to generate the documentation to fix the
rendering on our official documentation page.
https://github.com/asciidoc/asciidoc which is the upstream of the
openSUSE "asciidoc" package declares itself obsolete in favor of
asciidoctor so one more reason to go for that style :)

docs: Fix quotes and apostrophes for asciidoctor/github style

---

lib/OpenQA/Worker/Settings.pm
t/24-worker-job.t
t/24-worker-overall.t
t/24-worker-webui-connection.t

Especially prevent any error messages from showing up because these might be confused with real errors.

Make log messages of worker tests less verbose

---

lib/OpenQA/Setup.pm
t/22-dashboard.t
t/config.t
templates/layouts/navbar.html.ep

This feature is for #2173. It allows plugins to add new links to the operator and admin menus with a config option, like:
```perl
$app->config->{plugin_links}{operator}{'Link Name'} = 'route_name';
```
I'm not too fond of the name `plugin_links`, but couldn't really think of something more fitting.

Allow plugins to add links to the menu

---

lib/OpenQA/WebAPI.pm
t/ui/05-auth.t

This is also for #2173. I just wanted to make sure the routing hooks plugins are supposed to use are treated as a security feature and have tests.

Give the authentication routes plugins will use names and test them

---

cpanfile
docker/travis_test/Dockerfile
lib/OpenQA/Worker/Cache/Service.pm
openQA.spec
script/create_admin
script/load_templates
script/openqa
script/openqa-websockets
t/01-compile-check-all.t
t/fake-isotovideo.pl
t/fixtures/01-jobs.pl
t/fixtures/02-workers.pl
t/fixtures/03-users.pl
t/fixtures/04-products.pl
t/fixtures/05-job_modules.pl
t/fixtures/06-job_dependencies.pl
t/fixtures/07-needles.pl
t/lib/OpenQA/FakePlugin/FooBar.pm

* Use Test::Strict instead of Test::Compile
* Check for presence of 'use strict;'
* Check for presence of 'use warnings;'
* Cover all Perl files (was not possible with
Test::Compile because it tried to load scripts
as modules)
* Simplify code of 01-compile-check-all.t
* Adjust all files to comply with the new checks

Improve and simplify compile check

---

lib/OpenQA/Parser/Format/TAP.pm
t/30-test_parser.t
t/data/tap_format_example2.tap
t/data/tap_format_example3.tap

This will allow also to write bash scripts named `something.bash` to output TAP and get it parsed.
Also this fixes the regex by swapping ':?' to '?:'

Allow any suffix for TAP source files

---

script/fetchneedles

* fetchneedles: Use subshells efficiently for dir changes
* fetchneedles: Fix indention
* fetchneedles: Prevent noisy output about auto-packing git repos
Tested manually with:
```shell
scp script/fetchneedles o3:/tmp && ssh o3 "sudo -u geekotest bash -ex /tmp/fetchneedles"
```

fetchneedles enhancements

---

templates/admin/job_template/index.html.ep

Defaults and products have been moved to the top. This adapts the example to the new order.

Adapt order of job template example

---

lib/OpenQA/WebSockets/Client.pm

Simple change to remove these and similar lines from the test output:
```
./t/05-scheduler-full.t ................... skipped: set SCHEDULER_FULLSTACK=1 (be careful)
[2019-07-13 15:12:13.73972] [1345] [info] Listening at "http://127.0.0.1"
[2019-07-13 15:12:15.28877] [1345] [debug] POST "/api/send_msg" (3f9ae2ed)
[2019-07-13 15:12:15.29244] [1345] [debug] Routing to controller "OpenQA::Shared::Controller::Auth" and action "check"
[2019-07-13 15:12:15.29419] [1345] [debug] Routing to controller "OpenQA::WebSockets::Controller::API" and action "send_msg"
[2019-07-13 15:12:15.29514] [1345] [debug] 200 OK (0.006352s, 157.431/s)
[2019-07-13 15:12:15.34022] [1345] [debug] POST "/api/send_msg" (4a082453)
[2019-07-13 15:12:15.34168] [1345] [debug] Routing to controller …
```

Make the websocket server tests less noisy

---

script/client

There's a problem with `openqa.opensuse.org` where all HTTP requests are redirected to HTTPS and changed to GET requests. Technically, this is not really a bug, but i think defaulting to HTTP for hosts without a scheme should be considered a minor security flaw. Credentials can be accidentally leaked very easily if one is not careful.
I think it's better to be more secure by default and require HTTP to be selected explicitly. So `--host openqa.opensuse.org` would be equivalent to `--host https://openqa.opensuse.org` from now on.
Progress: https://progress.opensuse.org/issues/53891

Default to HTTPS instead of HTTP with openqa-client

---

t/lib/OpenQA/SeleniumTest.pm
t/ui/06-operator_links.t

By default [Selenium::Remote::Driver](https://metacpan.org/pod/Selenium::Remote::Driver#error_handler) will croak and generate a stack
trace at the end of the test run. There's a couple issues with this:
- It looks like an internal error.
- The stack trace isn't useful outside of developing the driver.
- Context is lost. The referenced code is not linked to the test case.
Overriding the handler, we can [fail](https://metacpan.org/pod/Test::More#fail) and get a message within the
context of the test that actually failed.

Add Test::More based error handler to SeleniumTest

---

codecov.yml

It seems with our recent work, e.g. a bigger worker restructuring, we
have effectively "lost coverage" in the numbers as codecov gathers them.
It does not make sense to keep ignoring the failed coverage test and
force the merge so we should rather adjust the target numbers to what we
currently have and improve from there.
Related progress issue: https://progress.opensuse.org/issues/54278

Adapt codecov target to current coverage

---

t/31-client_file.t

This is an alternative solution for #2193. The return value of `OpenQA::Files->verify_chunks` is a `Mojo::Exception` object. So it should be treated as an exception and only the beginning of the stringified value checked with a regular expression.

Fix test doing an equality check on exceptions

---

lib/OpenQA/WebAPI.pm
t/api/03-auth.t

This is also for #2173, and a followup to #2182. Again making sure everything is tested properly.

Give the API authentication routes plugins will use names and test them

---

.travis.yml

Run the whole documentation generation job only in case it is really
needed, i.e. if a push happens to the master branch in the original repo
itself. Previously the job would be triggered also on pushes to feature
branches in forks but abort early in the doc generation script anyway.
See https://travis-ci.org/os-autoinst/openQA/builds/558244401?utm_source=github_status&utm_medium=notification

.travis.yml: Save travis CI some testing time

---

lib/OpenQA/Worker.pm
lib/OpenQA/Worker/WebUIConnection.pm
t/24-worker-job.t
t/24-worker-overall.t
t/24-worker-webui-connection.t
t/lib/OpenQA/Test/FullstackUtils.pm

* Add test for this as well
* Add test for worker behaviour when stopped due to an API failure
* It is not supposed to upload results anymore to the web UI
because that would likely fail, too. Note that the API client
has already tried to query the web UI multiple times at this
point. Maybe the web UI even already considers the job dead.
* It is supposed to re-register which might help in situations
like https://progress.opensuse.org/issues/47060#note-19.

Stop job directly with reason 'api-failure' on API failures

---

lib/OpenQA/Worker/Job.pm

It can have many reasons why the command server is not reachable anymore at this point. Those messages can be useful but are completely uncritical and very unlikely the cause of potential subsequent errors.

Set log for failing to stop cmd srv to info level

---

lib/OpenQA/Worker.pm
t/24-worker-overall.t

* Seems the last PR missed one place where the cleanup was done, see https://progress.opensuse.org/issues/54203#note-5
* Extended unit tests and this time I also tested all cases manually, too.

Prevent cleaning pool directory in worker availability check

---

lib/OpenQA/WebAPI.pm
t/api/03-auth.t

This PR is a followup to #2198. We have four levels of API access (public, user, operator and admin), but so far only operator and admin were available for use in plugins.

Make sure all four levels of API access have named routes

---

lib/OpenQA/ExpandPlaceholder.pm
lib/OpenQA/Schema/Result/ScheduledProducts.pm
lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
t/40-expand_placeholders.t
t/api/02-iso.t
t/api/04-jobs.t

When users created jobs using 'client jobs post', the jobs settings did
not expand Machine and Medium Type settings. This PR is used to support
to expand settings from Machine and Medium Type when creating jobs with
'jobs post'.
See: https://progress.opensuse.org/issues/20464
Related: https://progress.opensuse.org/issues/51479

Expand Machine and Medium Type settings when creating job with 'jobs post'

---

cpanfile
openQA.spec

This change fixes warnings that started to appear in Travis tests today.
```
./t/13-joblocks.t ......................... ok
(in cleanup) Can't locate object method "DELETE" via package "DBI::db" at /usr/lib/perl5/vendor_perl/5.18.2/Mojo/Pg.pm line 105.
(in cleanup) Can't locate object method "DELETE" via package "DBI::db" at /usr/lib/perl5/vendor_perl/5.18.2/Mojo/Pg.pm line 105.
(in cleanup) Can't locate object method "DELETE" via package "DBI::db" at /usr/lib/perl5/vendor_perl/5.18.2/Mojo/Pg.pm line 105.
```
Unfortunately we use `Test::Warnings`, so these warnings resulted in test failures.

Update DBI requirement

---

public/schema/JobTemplate.yaml
t/api/08-jobtemplates.t

Without these, even the schema validation itself doesn't fail but the regex is effectively ignored and typos in property names aren't caught early.
We're still catching errors with product definitions as-is but the error is much less clear than it could be.

Add type/additionalProperties to products spec

---

docs/UsersGuide.asciidoc
templates/admin/job_template/index.html.ep

Two new sections
- Job group editor
- Job template YAML (REST API)
And the guide in the YAML editor links to the docs as well, instead of the not so useful tooltip.

Docs for the job group editor and YAML REST

---

lib/OpenQA/WebAPI/Plugin/AMQP.pm
t/23-amqp.t

Fedora's new AMQP-based messaging system requires messages to
have certain headers:
https://fedora-messaging.readthedocs.io/en/stable/wire-format.html
I'm planning to write a plugin for emitting Fedora-compliant
AMQP messages as a subclass of the existing AMQP plugin, but in
order to be able to use `publish_amqp` in that plugin, I need to
be able to pass it headers like this. Otherwise I'd have to
reimplement it.
This implementation aims to ensure it works just as before if
you *don't* want to pass it headers, and without needing to
duplicate the `publish_p` calls for "headers" and "no headers"
cases - that's the reason for making `$headers` a reference to
an empty hash if it's not defined, and then checking that it's
a hashref: to be sure about what we're asking `publish_p` to do. …

AMQP: allow passing headers to publish_amqp

---

lib/OpenQA/WebAPI/Plugin/AMQP.pm
t/23-amqp.t

Mojo::RabbitMQ::Client::Publisher will do this for us if we just
pass it a reference. This makes three things better in one go:
1) By encoding to a JSON string in publish_amqp and passing a
string to publish_p, but not including a content_type header,
we're actually doing it wrong: the published message will get
'text/plain' as its content_type header. If we pass publish_p a
reference like this it will automatically encode it to JSON and
set the content_type header to 'application/json'
2) Removes an unnecessary use of CPanel::JSON::XS
3) Lets us make the test cleaner, as we can compare the message
body as a hash ref rather than a JSON string, which reads much
more nicely
One note about this: the publisher uses Mojo::JSON to do the
encoding, which escapes forward slashes. CPanel::JSON::XS …

AMQP: don't encode message body to JSON before publishing

---

lib/OpenQA/Schema/Result/JobTemplates.pm
lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
script/dump_templates
script/load_templates
t/api/08-jobtemplates.t

- Add a new "table" option `JobGroups` to `{dump,load}_templates`
- Add and use `str` type to accept `<name:str>` in routes
- Expose YAML of multiple groups as strings with their group names
- Error handling fixes handling unset `code` and invalid "table"
- Accept `STDIN` as input for `load_templates`
Fixes: [poo#54143](https://progress.opensuse.org/issues/54143)

Add YAML support to {dump,load}_templates

---

lib/OpenQA/Worker/Job.pm
lib/OpenQA/Worker/WebUIConnection.pm
t/24-worker-job.t

* Prevent incomplete jobs when restarting the websocket server
* The web socket connection is mainly for receiving and accepting new jobs and not strictly required when already working on a job
* This still does a clean re-registration after a disconnect. With changes from https://github.com/os-autoinst/openQA/pull/2227 this will not cause incompletes.
* Tested by restarting the web socket server locally multiple times while a job is executed.

worker: Consider ws disconnects as uncritical during job execution

---

lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
t/api/02-iso.t
t/api/08-jobtemplates.t

Default should only be used when a scenario is defined once per architecture, at least in the initial generated YAML.
Fixes: [poo#53588](https://progress.opensuse.org/issues/53588)
Note: `t/api/02-iso.t` doesn't require changes, but trying to debug failures before I reconsidered changes to the fixtures, these changes made it a little bit easier.

YAML: don't merge scenarios with multiple machines with defaults

---

t/lib/OpenQA/SeleniumTest.pm

This function currently has two flaws:
- if jQuery is not defined, it'll produce errors forever
- if jQuery.active is never set to  1, the test will run forever
There should be a maximum timeout for the wait, as well as a check that
avoids repeated Javascript errors which turn into redundant test failures.
As a bonus, showing successful waits is probably nice to have.

Timeout for wait_for_ajax

---

docs/UsersGuide.asciidoc
lib/OpenQA/Schema/Result/ScheduledProducts.pm
t/api/02-iso.t

When users use 'client isos post' to schedule test suite, if they specify
'_NO_TRIGGER_DEPENDENCY=1', do not schedule parent test suites that defined by
'START_AFTER_TEST'.
See: https://progress.opensuse.org/issues/30730

Add a new parameter to support not schedule parent test suite

---

lib/OpenQA/Worker.pm

Previously, with the latest worker rework the pool directory was not
cleanup up with '--no-cleanup' on stopping a job but still when a job is
started. The option for '--no-cleanup' should simply not clean up
anything at all, the user needs to take care about this then.

Fix '--no-cleanup' on worker start regression

---

lib/OpenQA/Schema/Result/Jobs.pm

This function is not used anywhere and duplicates code from set_assigned_worker.

Remove OpenQA::Schema::Result::Jobs::set_scheduling_worker

---

assets/javascripts/job_templates.js
lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
t/ui/13-admin.t
templates/admin/job_template/index.html.ep

- Expose Save button in the UI
- Hide legacy UI when YAML is/was stored
- Handle conflicts via the `reference` feature (no diff here, just a simple error)
Prerequisite: #2103 
Fixes: [poo#54146](https://progress.opensuse.org/issues/54146)

Expose saving of YAML templates and hide the legacy UI

---

lib/OpenQA/WebAPI/Plugin/AMQP.pm
t/23-amqp.t

For Fedora messages we do not actually want a prefix, the topic
is *just* openqa.job.done or whatever. This allows setting
'topic_prefix = ' in the config file to make that work.

AMQP: allow no message prefix

---

lib/OpenQA/WebAPI/Controller/Test.pm
lib/OpenQA/WebAPI/Plugin/Helpers.pm
t/25-bugs.t
t/ui/15-comments.t
t/ui/16-tests_job_next_previous.t

* Additionally, add tests for the two occurrences of bug-title rendering in our code (test result overview and 'Next & Previous' tab via JavaScript)
* See https://progress.opensuse.org/issues/53420
By the way, this is *not* security relevant because we were previously escaping one time too often.

Prevent over-escaping of bug titles in test result overview

---

public/schema/JobTemplate.yaml
t/api/08-jobtemplates.t

Fixes: [poo#55121](https://progress.opensuse.org/issues/55121)

Allow * placeholders in product names

---

docs/Networking.asciidoc

The entries for "Pros of wicked" were marked correctly by `**` at the
beginning of the line of each time however the list was not correctly
rendered because the items on the 1st list level were missing.

docs: Fix marking for 2nd level list about "wicked pros"

---

lib/OpenQA/Worker/Settings.pm
lib/OpenQA/Worker/WebUIConnection.pm
t/24-worker-settings.t
t/24-worker-webui-connection.t
t/data/24-worker-settings/workers.ini

This should reduce load on the web UI and helps to reduce the number of incomplete jobs. Regular API errors (no timeout) are treated as before.

Extend retry delay of worker to 60 seconds if web UI busy

---

script/load_templates

This fixes two bugs in load_templates since #2204 landed. First,
`--clean` couldn't work once JobGroups was added to `@tables`
because that API endpoint returns an array (not a hash) and the
script would choke on that (it only knows how to handle hashes).
The correct fix is just to skip JobGroups when doing `--clean`
because we usually cannot delete them anyway, as non-empty job
groups cannot be deleted. There's no point trying to handle the
array.
Second, loading perl format template files was broken by the
change to make `$datafile` the slurped contents of the file
rather than simply the filename. We have to change `do` to `eval`
to handle that change.

load_templates: fix --clean and reading perl templates

---

openQA.spec

I forgot this when i submitted #2233, so tests fail currently because `@INC` is wrong.

Fix PROVE_ARGS in spec file

---

docs/Networking.asciidoc

* docs: Fix explanation for masquerading which is needed on all involved zones
* docs: Simplify firewalld commands by using the runtime variants
* docs: Make the current "firewalld" approach more prominent than old SuSEfirewall2
* docs: Remove obsolete section about "wicked < 0.6.23"

Enhance Networking docs

---

lib/OpenQA/File.pm
lib/OpenQA/Files.pm
lib/OpenQA/Parser/Format/JUnit.pm
lib/OpenQA/Parser/Format/XUnit.pm
lib/OpenQA/Schema/Result/Jobs.pm
t/30-test_parser.t
t/31-client_file.t
t/32-openqa_client.t
t/api/04-jobs.t

While learning more about how the worker uploads results i stumbled over a few issues. The most noticeable change in this PR will be lack of this block of warnings from test results.
```
Serialization is offically supported only if object can be turned into an array with ->to_array() at lib/OpenQA/Parser.pm line 105.
Serialization is offically supported only if object can be turned into an array with ->to_array() at lib/OpenQA/Parser.pm line 105.
Serialization is offically supported only if object can be turned into an array with ->to_array() at lib/OpenQA/Parser.pm line 105.
Serialization is offically supported only if object can be turned into an array with ->to_array() at lib/OpenQA/Parser.pm line 105.
Serialization is offically supported only if object can be turned into an array with …
```

Fix warnings in 30-test_parser.t

---

lib/OpenQA/Task/Needle/Save.pm
t/ui/12-needle-edit.t

Otherwise saving needles fails with the error message `syntax error: malformed UTF-8 character in JSON string`.
(Noticed when testing https://github.com/os-autoinst/openQA/pull/2070.)

Fix error when saving needle JSON with non-ASCII characters

---

profiles/apparmor.d/usr.share.openqa.script.openqa

* apparmor: Allow loading of client.conf in usual home of geekotest
* apparmor: Allow loading override templates in /etc/openqa/templates/

Fix apparmor profile for access of client.conf and override templates directory

---

profiles/apparmor.d/usr.share.openqa.script.worker

Necessary for https://github.com/os-autoinst/os-autoinst/pull/1182
Related progress issue: https://progress.opensuse.org/issues/55412

apparmor: Allow virtio_console based on named PIPE

---

script/openqa-bootstrap

We want to clone if the directory does *not* yet exist

openqa-bootstrap: Fix logic of git clone

---

templates/branding/openSUSE/external_reporting.html.ep

Related progress issue: https://progress.opensuse.org/issues/51989

branding: Prevent warnings about undefined $distri in external_reporting.html.ep

---

lib/OpenQA/WebAPI/Plugin/ObsRsync/Controller.pm

Fixes url to openqa.cmd used to trigger build and logs of the command execution.

Fix rendering of the openqa.cmd

---

lib/OpenQA/WebAPI/Controller/Test.pm

* Make result deterministic in case multiple machines occur equally often (see https://progress.opensuse.org/issues/16354)
* Improve comments

Improve calculating preferred machine

---

assets/javascripts/needleeditor.js
lib/OpenQA/Utils.pm
lib/OpenQA/WebAPI/Controller/Step.pm
t/16-utils.t
t/ui/12-needle-edit.t
templates/step/edit.html.ep

See https://progress.opensuse.org/issues/33706
By now we recommend adding related ticket number in needle name
when tester create a new needle with workaround property.
Modify the code to support adding workaround reason when create
needles with workaround property.

Modify workaround property to support adding reason

---

lib/OpenQA/Schema/ResultSet/Jobs.pm

See issue https://progress.opensuse.org/issues/55631
Use of uninitialized value in addition (+) at
.../lib/OpenQA/Schema/ResultSet/Jobs.pm line 451

job cancel: Explicitly return a number to avoid warning

---

t/ui/13-admin.t
templates/admin/job_template/index.html.ep

The include ended up inside the if block by mistake, which results in a
silent failure when trying to toggle it later. Only the media
selection should be hidden if the group is configured in YAML.
Fixes: [poo#55646](https://progress.opensuse.org/issues/55646)

Always include the group property editor

---

script/client

This makes `openqa-client ... jobs/1/comment post $'text=test\n\n123'` work. This is now required because proper Markdown requires newlines where previously raw HTML tags like `<br>` could be used in comments.
Progress: https://progress.opensuse.org/issues/55751

Handle newline characters in form parameters correctly with openqa-client

---

lib/OpenQA/Worker.pm
t/24-worker-overall.t

Clean the pool directory only before starting the next job and not after finishing a job. This should be sufficient and allows the detection for stuck QEMU processes to work also without "--no-cleanup" (see https://progress.opensuse.org/issues/55526).
With "--no-cleanup" the pool directory is still never cleaned up.

Preserve QEMU PID file on pool dir cleanup if QEMU still running

---

t/ui/12-needle-edit.t

In accordance with https://github.com/os-autoinst/openQA/pull/2263

Test support for non-ASCII chars in needle JSON only in description

---

Makefile

Fixes the problem introduced with 5ea07a550 in a way
that the instructions from documentation are valid again.

Makefile: Allow again to select single test cases with PROVE_ARGS

---

assets/stylesheets/openqa_theme.scss
lib/OpenQA/WebAPI/Controller/Test.pm
t/10-tests_overview.t
templates/test/tr_job_result.html.ep

See https://progress.opensuse.org/issues/43112

Distinguish scheduled and blocked jobs on test result overview & Use purple for blocked jobs 

---

lib/OpenQA/Setup.pm
openQA.spec

The meaning of "t_requires" was probably not really clear to many so this commit
provides better names to explain the meaning. In the same go we split the
requirements per sub-package and pull in all runtime requirements as needed
into the build environment to execute the tests without pulling in more
runtime dependencies into the individual tickets than needed.
https://build.opensuse.org/package/show/home:okurz:branches:devel:openQA:feature:spec_split_deps/openQA shows the build results based on this branch

spec: Split out all dependencies properly per sub-package

---

lib/OpenQA/Task/Asset/Download.pm
lib/OpenQA/Task/Asset/Limit.pm
lib/OpenQA/Task/AuditEvents/Limit.pm
lib/OpenQA/Task/Job/Limit.pm
lib/OpenQA/Task/Needle/Delete.pm
lib/OpenQA/Task/Needle/Save.pm
lib/OpenQA/Task/Screenshot/Scan.pm

The short lock timeout just became a problem on OSD with a `limit_results_and_logs` job. There is actually very little reason to not be generous with timeouts, since the chance that one of them doesn't get cleared automatically at the end of a job is very small. So i've increased most of them to 1 day.

Increase lock timeouts a bit

---

assets/javascripts/needleeditor.js
assets/stylesheets/forms.scss
templates/step/edit.html.ep

Currently, it is possible to add a tag with spaces or other arbitrary
characters. Spaces are only inconvenient, as they are only visible when
inspecting the generated JSON, other characters may have worse effects.
Use the HTML5 "pattern" attribute to check the value, and reflect the
state in the form field background (light red) and submit button.

Validate tag input field in needleeditor

---

assets/javascripts/running.js
t/ui/25-developer_mode.t

Hello, it'd be nice if the developer panel showed expected needle tags when openQA worker is waiting for check_screen/assert_screen.
Here's a patch.

Show needle tags for assert_screen/check_screen

---

documentation.html

Add link to [os-autoinst-distri-opensuse docs](https://os-autoinst.github.io/os-autoinst-distri-opensuse/)

Add link to test distribution docs

---

docker/travis_test/Dockerfile

All Travis tests currently fail because #2225 accidentally removed a dependency required by os-autoinst. This PR is required to fix the container again, tests are expected to fail until it has been merged.

Fix accidentally removed dependency

---

openQA.spec

This is a quick fix to prevent the package build being blocked however
there are actually more packages required for a complete development
environment. This will be covered in another change.

Fix 'devel' package

---

assets/assetpack.def

After adding codemirro diff.js in css label, the code container in
the webpage is short. Try to fix this issue by moving it.

Move codemirror javascript file to javescript label

---

lib/OpenQA/Worker/WebUIConnection.pm

Small followup to #2270, there was a typo in the error message so it showed the hash address in the logs instead of the error message.

Fix artefact upload errors to show the message

---

docs/Contributing.asciidoc

docs: Render code correctly

---

lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/Schema/Result/Screenshots.pm
lib/OpenQA/Task/Job/Limit.pm
t/42-screenshots.t

Going though all screenshots like this takes a little bit less than a minute on my machine with OSD data (not taking file system lookup into account). So this is the alternative to https://github.com/os-autoinst/openQA/pull/2294.
Note that an existing problem with our deletion code is not fixed: If a screenshot can not be deleted in the file system (e.g. permission error) it is still deleted from the database. However, this is not that easy to solve because the database deletion should be done first to catch possible failures because a new link has been created in the meantime.
I also added a small test to check whether the deletion works (and screenshots still referenced are preserved).

Delete unused screenshots in separate loop

---

lib/OpenQA/Schema/Result/Jobs.pm

The job will fail when the length of the test result directory is more than 255. Because there is a limit in creating directory that the directory name length cannot exceed 255. 
See: https://progress.opensuse.org/issues/56405

Cut the test result directory shorter when its length is more than 255

---

docker/travis_test/Dockerfile

Hardcoding devel:openQA defeats the purpose of being able to test in developer branches

Fix container image to use repository paths

---

lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
public/schema/JobTemplate.yaml
t/api/08-jobtemplates.t

Settings defined as defaults are merged into scenarios along with
machine and priority values, and will be overridden by explicitly
defined settings.
Fixes: [poo#55829](https://progress.opensuse.org/issues/55829)

Implement optional defaults.settings key in YAML

---

dbicdh/PostgreSQL/deploy/80/001-auto-__VERSION.sql
dbicdh/PostgreSQL/deploy/80/001-auto.sql
dbicdh/PostgreSQL/upgrade/79-80/001-auto.sql
dbicdh/_source/deploy/80/001-auto-__VERSION.yml
dbicdh/_source/deploy/80/001-auto.yml
lib/OpenQA/Schema.pm
lib/OpenQA/Schema/Result/JobTemplates.pm
lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/Schema/Result/ScheduledProducts.pm
lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
public/schema/JobTemplate.yaml
t/api/04-jobs.t
t/api/08-jobtemplates.t
t/ui/13-admin.t

- Allow an optional `testsuite` key in scenarios
- Add a `name` string to the job templates table
- Defining duplicate scenarios is an error
- Render the scenario name in place of the test suite name
Fixes: [poo#55454](https://progress.opensuse.org/issues/55454)

Scenarios can have different settings

---

script/openqa-clone-custom-git-refspec

This change can let script support first parameter like: https://github.com/coolgw/os-autoinst-distri-opensuse/tree/nfs , the reason why i add this is sometimes we need do some verification before create PR.
linux-4360:~/openqa/openQA/script # dry_run=echo sh  ./openqa-clone-custom-git-refspec https://github.com/coolgw/os-autoinst-distri-opensuse/tree/nfs  http://openqa.suse.de/tests/3235878
openqa-clone-job --skip-chained-deps --within-instance http://openqa.suse.de 3235878 _GROUP=0 TEST=offline_sles12sp2_ltss_pscc_sdk+we+lp+asmm+contm+lgm+pcm+tcm+wsm+ltss_all_full_x86_64@coolgw/os-autoinst-distri-opensuse#nfs BUILD=coolgw/os-autoinst-distri-opensuse# CASEDIR=https://github.com/coolgw/os-autoinst-distri-opensuse.git#nfs PRODUCTDIR=os-autoinst-distri-opensuse/products/sle …

Support branch url on openqa-clone-custom-git-refspec

---

lib/OpenQA/File.pm

This was introduced with e98e83f2 but never used.

Cleanup disabled code about 'Sereal'

---

assets/javascripts/job_templates.js
lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
lib/OpenQA/WebAPI/Plugin/YAMLRenderer.pm
public/schema/JobTemplates-01.yaml
script/dump_templates
script/load_templates
t/api/08-jobtemplates.t

Fixes: [poo#56426](https://progress.opensuse.org/issues/56426)

Non-experimental YAML routes with explicit schema

---

assets/javascripts/job_templates.js

Normally only the visible lines are rendered (and a little more). We can just override that, though, to work around issues with searching the text.
Fixes: [poo#56480](https://progress.opensuse.org/issues/56480)

Allow CodeMirror to render off screen

---

lib/OpenQA/Worker/Job.pm

This resolves #2321. The filename was getting removed in `Mojo::UserAgent` during HTTP message body generation, since form hashrefs are not actually meant to be reusable.
```
[debug] [pid:1382] Optimizing /home/sri/work/openQA/openqa/pool/1/testresults/boot5-2.png
[debug] [pid:1382] Uploading artefact boot5-2.png as 29e32850478011f9ddd98948593de9d7
[debug] [pid:1382] Optimizing /home/sri/work/openQA/openqa/pool/1/testresults/.thumbs/boot5-2.png
Use of uninitialized value $name in concatenation (.) or string at /home/sri/work/openQA/repos/openQA/script/../lib/OpenQA/Worker/WebUIConnection.pm line 421.
[debug] [pid:1382] Uploading artefact  as 29e32850478011f9ddd98948593de9d7
```

Fix warning caused by filename getting removed from form hashref

---

assets/stylesheets/admin-pages.scss
public/schema/JobTemplates-01.yaml
templates/admin/job_template/index.html.ep

- Explain the significance of job template names in the schema
- Document testsuite in the YAML guide
- Update sizing and disable line breaks to keep layout stable
Fixes: [poo#55454#note-13](https://progress.opensuse.org/issues/55454#note-13)

Update YAML guide and schema to explain custom job template names

---

lib/OpenQA/WebAPI/Plugin/ObsRsync.pm
lib/OpenQA/WebAPI/Plugin/ObsRsync/templates/ObsRsync_folder.html.ep

While adding Gru Controller to the plugin duplicate path was introduced. So this PR fixes the problem.
No test case is provided, because automated check of every path name expansion or every link is costly and other tasks have higher priority. (E.g. it will be more beneficial to add link crawler which ensures that all links in forms are resolvable or duplicate path names finder).

Fix duplicate path name in ObsRsync Plugin

---

lib/OpenQA/Schema/Result/Workers.pm
lib/OpenQA/WebAPI/Controller/Running.pm

This modification is just used to avoid reporting deprecate warning message
when querying running job modules.
As Sebastian and Tina mentioned, the true reason is that there are two same
name job modules in one job.
See: https://progress.opensuse.org/issues/55541

Ignore SQL deprecate warning when querying job modules that are running

---

lib/OpenQA/WebAPI/Plugin/ObsRsync.pm
lib/OpenQA/WebAPI/Plugin/ObsRsync/Controller/Folders.pm
lib/OpenQA/WebAPI/Plugin/ObsRsync/templates/ObsRsync_folder.html.ep
lib/OpenQA/WebAPI/Plugin/ObsRsync/templates/ObsRsync_gru_index.html.ep
lib/OpenQA/WebAPI/Plugin/ObsRsync/templates/ObsRsync_index.html.ep
lib/OpenQA/WebAPI/Plugin/ObsRsync/templates/ObsRsync_logfiles.html.ep
lib/OpenQA/WebAPI/Plugin/ObsRsync/templates/ObsRsync_logs.html.ep
t/ui/27-plugin_obs_rsync_obs_status.t

Polish OSB plugin

---

assets/stylesheets/dependency_graph.scss
lib/OpenQA/Worker.pm

So especially parallel failed jobs are not confused with skipped ones.

Add colors for more job results in dependency graph

---

lib/OpenQA/Utils.pm
lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
lib/OpenQA/WebAPI/Controller/Step.pm
lib/OpenQA/WebAPI/Plugin/Helpers.pm

While working on another bug i noticed that there was a helper in `OpenQA::Utils` that should have been in the helper plugin. And i've given it a more descriptive name because in two instances it had actually been used wrong (a response was rendered more than once).

Move helper from OpenQA::Utils to plugin

---

lib/OpenQA/Schema/Result/Workers.pm
lib/OpenQA/WebSockets.pm
lib/OpenQA/WebSockets/Model/Status.pm
t/11-commands.t

This should prevent https://progress.opensuse.org/issues/57017 from happening.
Note that the ws server is supposed to be reactive and the possibly extensive task of cancelling job clusters should be moved to the scheduler in the future.

Prevent the ws server to query itself

---

openQA.spec

Related progress issue: https://progress.opensuse.org/issues/57251

spec: Fix missing dependency on IPC::Run in client

---

.circleci/config.yml

File `dependencies.txt` will become outdated unless somebody updates it regularly.
The nightly job is intended to create PR with updates.

Enable nightly circleci dependency job on master

---

dbicdh/PostgreSQL/deploy/82/001-auto-__VERSION.sql
dbicdh/PostgreSQL/deploy/82/001-auto.sql
dbicdh/PostgreSQL/upgrade/81-82/001-update.sql
dbicdh/PostgreSQL/upgrade/81-82/002-auto.sql
dbicdh/_source/deploy/82/001-auto-__VERSION.yml
dbicdh/_source/deploy/82/001-auto.yml
lib/OpenQA/Schema.pm
lib/OpenQA/Schema/Result/JobTemplates.pm
lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
t/api/08-jobtemplates.t
t/lib/OpenQA/Test/Database.pm

We apparently can't assume that the constraints are effective unless they're specified explicitly via `key`.
Further more the group name completely overrides the constraint without a check that it matches.
See https://metacpan.org/pod/DBIx::Class::ResultSet#find_or_create
Fixes: [poo#57143](https://progress.opensuse.org/issues/57143)

Explicitly specify constraint with JobTemplates->find_or_create

---

.circleci/config.yml

Somehow tests from t/api/ were not run in .circleci so far.

Add missing api tests to circleci

---

lib/OpenQA/Worker/Job.pm
t/24-worker-jobs.t

Test schedules are sometimes generated from configuration files installed by a testcase (e.g. `install_ltp`). Running both installation and the tests themselves in a single job would solve some outstanding issues with baremetal kernel testing. While it's possible to call `autotest::loadtest()` at the end of installation task to append additional modules to test schedule of the current job, the test results will be ignored by OpenQA.
This pull request simply checks whether `test_order.json` has changed on every test result upload and updates the test schedule in OpenQA if it did. The ony minor outstanding issue is that the user will need to refresh the job webpage manually to see the updated schedule before the job finishes. The testcase that schedules additional modules is responsible for …

Allow scheduling additional test modules at job runtime

---

assets/stylesheets/dependency_graph.scss

In Firefox nodes in different states had different sizes which didn't look very nice.

Enforce same width for nodes in dependency graph

---

t/lib/OpenQA/SeleniumTest.pm
t/ui/24-feature-tour.t

See particular commit messages. This will hopefully prevent
```
not ok 6 - tour popover is displayed again
```
which has been observed quite often lately in the CI.

Improve tour test

---

assets/javascripts/filter_form.js
assets/javascripts/fullscreen.js
assets/javascripts/index.js
lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Controller/Main.pm
t/17-build_tagging.t
t/22-dashboard.t
t/api/04-jobs.t
t/api/10-jobgroups.t
t/ui/14-dashboard-parents.t
t/ui/14-dashboard.t
t/ui/15-comments.t
templates/main/dashboard_build_results.html.ep
templates/main/group_overview.html.ep
templates/main/index.html.ep

So it works like the dashboard on GitHub. Additionally, when submitting the filter form the whole page doesn't need to reload anymore.
See https://progress.opensuse.org/issues/55112
---
This was quite easy. I guess adapting the tests will be the annoying part.
---
Note that the `.json` representation of the index page (which is not considered part of openQA's stable API) is removed by this change but the same info is now available via `/dashboard_build_results.json`.

Load build results on dashboard via AJAX

---

lib/OpenQA/Scheduler.pm
lib/OpenQA/Scheduler/Model/Jobs.pm
lib/OpenQA/Schema/Result/Workers.pm
lib/OpenQA/Schema/ResultSet/Jobs.pm
lib/OpenQA/WebAPI/Controller/API/V1/Worker.pm
lib/OpenQA/WebSockets.pm
lib/OpenQA/WebSockets/Client.pm
lib/OpenQA/WebSockets/Controller/API.pm
lib/OpenQA/WebSockets/Controller/Worker.pm
lib/OpenQA/WebSockets/Model/Status.pm
t/05-scheduler-full.t
t/20-stale-job-detection.t
t/27-websockets.t
t/33-developer_mode.t
t/api/01-workers.t
t/full-stack.t
t/lib/OpenQA/Test/Utils.pm
templates/admin/workers/worker_status.html.ep

* See the individual commit messages
* Supersedes https://github.com/os-autoinst/openQA/pull/2344
* Solves one part of https://progress.opensuse.org/issues/57017
* Solves https://progress.opensuse.org/issues/27454

Move stale job detection from ws server to scheduler relying on t_updated for the worker's online status

---

script/generate-documentation

Instead, show the error message which is already present (but never shown).

Don't silently exit doc generation if asciidoctor not available

---

lib/OpenQA/Task/Asset/Limit.pm
t/37-limit_assets.t

Make t/37-limit_assets.t independent of t/14-grutasks.t
---
Retry limit asset job on key constraint violations
These errors are mostly caused by race conditions but we want to avoid locking the tables, see https://progress.opensuse.org/issues/57287#note-3.
Note that none of the logic within the try block changed.

Retry limit asset tasks on key constraint violations

---

profiles/apparmor.d/usr.share.openqa.script.openqa

* Sort alphabetically
* Updated profile with `aa-logprof /var/log/audit/audit.log.1`
Related progress issue: https://progress.opensuse.org/issues/57680

apparmor: Update profile based on current o3 state

---

systemd/openqa-webui.service

We currently allow up to 1000 (the default) requests to be handled concurrently by every webui worker. Unfortunately that doesn't always work, because many requests take multiple seconds to be processed and they block during this time with database queries and the like.
This becomes a problem when a purely non-blocking request (such as an upload) is in progress, while another request arrives that will block the worker process for a few seconds (such as a worker status update). In this case both requests would be blocked for a few seconds, the upload might even be stalled and new incoming data could not be received from the socket until the status update is finished.
So, this PR changes the `-c` option of the prefork command to `1`, enforcing that only one request can be processed at a …

Limit concurrency for webui workers

---

templates/test/settings.html.ep

See https://progress.opensuse.org/issues/15384
It simply checks if the setting starts with `https?://` and creates a clickable link.

Make clickable links if a setting looks like a URL

---

.circleci/build_dependencies.sh
.circleci/config.yml
.circleci/dependencies.txt
script/tidy

Rather than dumping verbose logs, we should generate proper test results that can be read by CircleCI. [TAP::Harness::JUnit](https://metacpan.org/pod/TAP::Harness::JUnit) is a module that effectively allows `prove` to output `JUnit XML`. See [Configuring CircleCI](https://circleci.com/docs/2.0/configuration-reference/#store_test_results) on the mechanism used here.

Store test JUnit results for CircleCI

---

assets/javascripts/job_templates.js
t/ui/13-admin.t

The API verifies that the YAML document given as a reference matches the current state in the database, so that mid-air collisions can be caught when two people edit the same group.
The editor needs to update its reference after saving, otherwise it'll provoke false conflict errors.
Fixes: [poo#57065](https://progress.opensuse.org/issues/57065)

Update reference after saving YAML in editor

---

lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
t/api/08-jobtemplates.t

Going through the code with @perlpunk and answering some questions made me realize I've been putting off splitting of this logic for long enough. And it should be a good idea to do that before adding more features like [poo#56534](https://progress.opensuse.org/issues/56534) which will add more complexity.
I feel like this might not be the most elegant method signature.. although the most important thing is to split off the actual creation of job templates from the whole YAML parsing, so this is where I'm starting. Suggestions to make it more beautiful are welcome, though.
There's no functional changes here.

Split off creation/ update of job templates

---

lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
public/schema/JobTemplates-01.yaml
t/api/08-jobtemplates.t

In case of a hash we only expect one key. This way it is clearer and
will also die if we get more than one key.

Make job template code for testsuites clearer

---

lib/OpenQA/WebAPI/Controller/API/V1/Table.pm
t/api/08-jobtemplates.t

- Prevent update (post route)
- Prevent destroy (delete route)
Fixes: [poo#57266](https://progress.opensuse.org/issues/57266)

Lock test suites/machines/products used in YAML

---

lib/OpenQA/Schema/Result/Jobs.pm
t/10-jobs.t
t/21-needles.t

According to my profiling data, worker status updates containing `test_order` data are by far the slowest. They can take over 60 seconds for large jobs (LTP). This change slightly optimizes one of the responsible hot spots and increases performance by roughly 30%. Much of the overhead is caused by `DBIx::Class`, so i'm not sure i can improve it much more without adding custom SQL queries.
Progress: https://progress.opensuse.org/issues/55904

Improve worker status update performance

---

lib/OpenQA/Worker/Engines/isotovideo.pm

* Pass name to groupv2 function to prevent `Failed creating CGroup subtree 'Invalid path at /usr/lib/perl5/vendor_perl/5.26.1/Mojo/IOLoop/ReadWriteProcess/CGroup.pm line 35.`
* Improve coding style
* Improve error messages
* Separate temp dir creation from code dealing with cgroups
* See https://progress.opensuse.org/issues/56993

Fix cgroup creation

---

lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
public/schema/JobTemplates-01.yaml
t/api/08-jobtemplates.t
templates/admin/job_template/index.html.ep

- Extend the schema to accept an array of strings or a string
- Transparently convert a single machine to an array
- Loop through the machines to create/ update the job template
Fixes: [poo#56534](https://progress.opensuse.org/issues/56534)

Accept a list of machines in defaults and job templates

---

docs/UsersGuide.asciidoc

@Amrysliu mentioned in the chat that the documentation is wrong.
---
The `--group` parameter is only used with `openqa-dump-templates` to filter the output and must not be used with `openqa-load-templates` to load the (already filtered) JSON file.

Fix openqa-load-templates example in documentation

---

openQA.spec

The dockerfile is now self contained and shouldn't be part of the Factory sources

Remove openqa_dev from our spec file

---

docs/UsersGuide.asciidoc

While the editor shows a small guide that's more of a cheatsheet and the semantics should be explained explicitly in the docs.
**Configuring job groups via YAML documents**
A new job group starts out empty, which in YAML means that the two mandatory
sections are present but contain nothing. This is what can be seen when
editing a completely group, and what is also the state to revert to before
deleting a job group that is no longer useful:
```yaml
products: {}
scenarios: {}
```
A job group is comprised of up to three main sections. `products` defines
one or more mediums to run the scenarios in the group. At least one needs to
be specified to be able to run tests. Going by an example of openSUSE 15.1
the name, distri, flavor and version could be written like so. Note that the
version is a …

Add a docs section elaborating on YAML by way of example

---

public/schema/JobTemplates-01.yaml
t/api/08-jobtemplates.t

- Update the schema
- Use . in validation unit test
Fixes: [poo#58130](https://progress.opensuse.org/issues/58130)

Allow . for job template name/ test suite in schema

---

.circleci/config.yml

- We collect JUnit XML as well as verbatim TAP output as artifacts, so we don't actually want verbose logs on stdout in CI.
- We should also avoid having a multi-line job script be re-used for the name of the job in the web interface.
- Package lists should be build artifacts rather than output to stdout
Note: Apparently overriding the name for `build.docs` doesn't work. I'm guessing that's a bug in CircleCI? So it'll say "Running unit tests" even when building docs.

Drop -v flag on test runs and avoid noisy job "name"

---

lib/OpenQA/Worker.pm

Related progress issue: https://progress.opensuse.org/issues/57620

worker: Do not treat reconnect attempts as errors but with warning only

---

lib/OpenQA/Scheduler.pm
lib/OpenQA/Scheduler/Client.pm
lib/OpenQA/Schema/Result/Workers.pm
lib/OpenQA/WebSockets.pm
lib/OpenQA/WebSockets/Client.pm
t/11-commands.t
t/31-client.t

This prevents the scheduler and ws server from querying itself which would lead to a deadlock (see https://progress.opensuse.org/issues/57017).
This change makes problems like this easier to debug by letting the scheduler and ws server die in that situation with a clear error message.
OpenQA::Schema::Result::Workers::send_command is still handling the case that it is being called from the ws server itself because that function is called all over the place and I like to keep it robust. However, the hack to use the application's name for that check has been removed.

Prevent potential deadlocks in scheduler and ws server

---

lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/Schema/ResultSet/Screenshots.pm

This problem can happen when you initialize your PostgreSQL database with a non-english [locale](https://www.postgresql.org/docs/current/locale.html). Suddenly PostgreSQL error messages cannot be string matched anymore. There are other ways to detect unique constraint violations, like:
```perl
log_debug "creating $img";
local our $is_unique_violation;
try {
my $dbh = $self->result_source->storage->dbh;
local $dbh->{HandleError} = sub { $is_unique_violation = $dbh->state eq '23505' };
$ids{$img} = $self->create({filename => $img, t_created => $now})->id;
}
catch {
my $err = $_;
die $err unless $is_unique_violation;
$ids{$img} = $self->find({filename => $img})->id;
};
```
But it requires some trickery that's not easily explained, like the use of `local our`. So i think for now just using …

Avoid problems with localized PostgreSQL error messages

---

Makefile
profiles/apparmor.d/local/usr.share.openqa.script.openqa

Without empty profile apparmor shows error:
```
sudo aa-complain /usr/share/openqa/script/openqa
ERROR: Include file /etc/apparmor.d/local/usr.share.openqa.script.openqa not found
```
Related to https://github.com/os-autoinst/openQA/pull/2386

Add empty local apparmor profile

---

lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/Schema/ResultSet/Screenshots.pm

E.g. here the error message is actually
```
doppelter Schlüsselwert verletzt Unique-Constraint »screenshots_filename«
```

Remove possibly localized quotes when checking PostgreSQL errors

---

script/fetchneedles

This decreases execution time on o3 from 17s to 9s.

fetchneedles: Save on execution time by skipping over needle dir symlinks

---

script/client

e3557fcd2 tried to make openqa-client more secure by defaulting to https
however this is not that suitable for localhost which is also the
default.

client: Fix the default host 'http://localhost' instead of https

---

lib/OpenQA/Worker/Cache.pm

Some cleanups in preparation for more cache service changes. I'll try to split them up into smaller PRs for easier review.
There were a lot of public methods in `OpenQA::Worker::Cache` that should have been private. Some dead code, unnecessary use of the shell, and the usual (`$_[0]` followed by `pop`/`shift`...) Perl style quirks that make the code a bit hard to read. Overall this patch should cause no functional differences.

Make OpenQA::Worker::Cache easier to read

---

.circleci/config.yml

I'm not sure why this started failing... the dep change in #2417 doesn't seem like it would have caused it.
This is a simple fix, though, which basically changes a fatal error to an empty log file.

Don't fail if there's no package logs

---

lib/OpenQA/Utils.pm
lib/OpenQA/Worker/Cache.pm
lib/OpenQA/Worker/Cache/Client.pm
lib/OpenQA/Worker/Engines/isotovideo.pm
t/16-utils.t
t/25-cache.t

Functions used across multiple classes belong in `OpenQA::Utils`. Just cleanup, no functional changes.

Move private function used across multiple classes into OpenQA::Utils

---

lib/OpenQA/Schema/Result/JobModules.pm
lib/OpenQA/Schema/Result/Needles.pm
lib/OpenQA/Utils.pm
lib/OpenQA/WebAPI/Controller/File.pm
lib/OpenQA/WebAPI/Controller/Step.pm
lib/OpenQA/Worker/Engines/isotovideo.pm
t/21-needles.t

* Locate needles relative to the job's needles directory
* No longer pass the project dir to isotovideo
* See https://progress.opensuse.org/issues/56789 and https://progress.opensuse.org/issues/58184
---
The os-autoinst part is still missing.

Reduce use of project dir to be more flexible regarding custom test runs

---

.circleci/config.yml

Previously coverage was not calculated on local branches (unless PR is created) to reduce testing time (sometimes down to 50%).
But developers' workflow was affected in negative way, because creating PR will not re-trigger CI until next commit. So we disable the feature and CI will always calculate coverage.
After the change having own fork enabled in CircleCI permanently should be enough for PR to be properly tested in CI.

Calculate coverage in Circleci in all branches

---

openQA.spec

As qemu-kvm is not provided on e.g. ppc64le and aarch64 we should not
try to pull it in. This should fix unresolvables as reported in
https://build.opensuse.org/package/show/devel:openQA/openQA

Fix missing 'qemu-kvm' in non-x86_64 package tests

---

lib/OpenQA/Schema/Profiler.pm

...so that all SQL debug goes to the same filehandle
Currently statements like `BEGIN WORK` and `COMMIT` are printed to the default debug handle via `$storage->debugfh`, while SQL statements are printed via `log_debug`.
Issue: https://progress.opensuse.org/issues/57107

Schema Profiler: override print method with log_debug

---

.circleci/config.yml
script/generate-documentation

Since we don't want to give CI push permissions to upstream, this PR will generate and push documentation nightly to openqabot fork, then create PR on upstream with daily changes.
(Very similar to nightly dependencies job).
Fixes: [poo#57548](https://progress.opensuse.org/issues/57548)

Push documentation nightly to openqabot fork

---

openQA.spec

Most failures are because chromedriver isn't working.
Issue: https://progress.opensuse.org/issues/19652

OBS: Skip tests which are failing in OBS

---

lib/OpenQA/Worker/Engines/isotovideo.pm

Apparently the needle directory used by os-autoinst so far is relative to the test case directory and not the share directory.

Fix needle lookup for current os-autoinst version

---

assets/javascripts/admintable.js
templates/admin/machine/index.html.ep
templates/admin/product/index.html.ep
templates/admin/test_suite/index.html.ep

* All admin tables have a regex-enabled search now
* Fix https://progress.opensuse.org/issues/58625

Enable regex search in 'Medium types' table

---

lib/OpenQA/Utils.pm
t/28-logging.t

...instead of die.
This way we will get the correct location of the calling method
Issue: https://progress.opensuse.org/issues/57776
I accidentally deleted my branch in #2436, so this is the same change

Use `croak` in OpenQA::Utils::log_fatal

---

lib/OpenQA/Worker/Job.pm

When `_test_order_mtime` isn't set, then it's the first read of `test_order.json`
Currently the message `Test schedule has changed, reloading test_order.json` appears in ever job at least once.
Issue: https://progress.opensuse.org/issues/58700

Only log if test schedule has really changed

---

lib/OpenQA/CacheService.pm
lib/OpenQA/CacheService/Client.pm
lib/OpenQA/CacheService/Model/Cache.pm
lib/OpenQA/CacheService/Request.pm
lib/OpenQA/CacheService/Request/Asset.pm
lib/OpenQA/CacheService/Request/Sync.pm
lib/OpenQA/CacheService/Task/Asset.pm
lib/OpenQA/CacheService/Task/Sync.pm
lib/OpenQA/Worker.pm
lib/OpenQA/Worker/Engines/isotovideo.pm
script/openqa-workercache
t/25-cache-service.t
t/25-cache.t
t/full-stack.t
t/lib/OpenQA/Test/Utils.pm

When i first started learning how the worker code actually works, one of the biggest problems was understanding how all the modules in the `OpenQA::Worker` namespace are actually connected. The cache service has been a bit of a special case, since it is not part of the worker service, but started as two separate services. And all communication goes exclusively through a client module and a REST API application that triggers background jobs.
So this PR adds the `OpenQA::CacheService` namespace, turning the cache service into a micro service similar to `OpenQA::Scheduler` and `OpenQA::WebSockets` (sharing the same application structure), just on the worker side instead of webui. And all code in `OpenQA::Worker` communicates with this micro service exclusively through …

Move cache service into OpenQA::CacheService namespace

---

Makefile

Previously `make test` did not correctly propagate exit code when RETRY=N parameter is provided and the tests had failed in each attempt

Fix retry logic in make test

---

openQA.spec

Regardless if '=>' works for version comparison we should use the more
common '>=' style as pointed out by adamw in
irc://chat.freenode.net/opensuse-factory

spec: Use more common '>=' rather than '=>'

---

lib/OpenQA/CacheService.pm
lib/OpenQA/CacheService/Controller/API.pm
lib/OpenQA/CacheService/Model/Locks.pm
script/openqa-websockets
script/openqa-workercache
t/25-cache-service.t
t/lib/OpenQA/Test/Utils.pm

This patch turns the cache service into a full Mojolicious application, just like the scheduler and websocket services. There should be no functional changes, just a cleaner structure and less dead code.

Turn cache service into a full Mojolicious application

---

t/full-stack.t

Startup time of the backend can take several seconds.
When sending the set_pause_at_test command too early, the backend doesn't read it.
(Still have to figure out where the command is lost exactly.)

full-stack.t: Add sleep before sending first command

---

lib/OpenQA/WebAPI/Controller/File.pm
t/ui/07-file.t
t/ui/12-needle-edit.t

As discussed in the POO, this was broken by PR #2410 commit
36aa974 - it assumes you can always find a needle simply by
sticking the needle filename on the end of a `needledir` call,
but you can't, needles are allowed to be in subdirectories of
needledir. This should hopefully fix that without breaking
the custom run case by using the *whole* of the JSON file path -
we just figure out the subdirectory component from it. This works
for me in the 'needle is in a subdirectory of the normal needle
dir' case, but I didn't test it in the custom run case.

Fix URLs for needles in subdirectories (POO #58959)

---

Makefile
t/lib/OpenQA/Test/PatchDeparse.pm

We are getting a lot of warnings like this in our tests when run with Devel::Cover:
```
Use of uninitialized value $expr in concatenation (.) or string at /usr/lib/perl5/5.26.1/B/Deparse.pm line 1794.
```
Problem seems to be a bug in B::Deparse
https://progress.opensuse.org/issues/40895

Test/Coverage: Monkeypatch B::Deparse

---

docs/Installing.asciidoc
script/openqa-bootstrap

Related progress issue: https://progress.opensuse.org/issues/43928

docs: Clarify that the cache service needs full read permission in CACHEDIRECTORY

---

lib/OpenQA/Worker/Engines/isotovideo.pm

PERL5OPT may contain Devel::Cover options. When spawning isotovideo, we don't need and want that, as that's not code in openQA itself.
Related issue: https://progress.opensuse.org/issues/40895

Unset PERL5OPT when executing isotovideo

---

lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
script/load_templates

The reason for this failure message is when update the job group using load_templates, there is no group_id in `$self->param`, so we need to pass the group_id to the function.
Fixes: [poo#58490](https://progress.opensuse.org/issues/58490)

Fix bug that cannot update job group using load_templates

---

assets/javascripts/job_templates.js
lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
t/api/08-jobtemplates.t
t/ui/13-admin.t
templates/admin/job_template/index.html.ep

We have the parsed scenarios in a hash. Generating a result is as easy as feeding the data back into the job template format.
The API takes an additional `expand` option to compute the result YAML after expanding aliases, settings and defaults.
The web UI exposes the feature as a new `Show expanded version` button which doesn't save the changes.
This also adds additional documentation on the API response to be clearer about the available fields with different options.
Fixes: [poo#56279](https://progress.opensuse.org/issues/56279)

Implement an expand feature for job group YAML

---

script/openqa-clone-custom-git-refspec

This fixes a regression due to the recent changes in os-autoinst and
openQA where the needle dir might not be computed because reverting to
default internally without computing the resulting variable value.
Related progress issue: https://progress.opensuse.org/issues/59330

Fix empty needles dir in openqa-clone-custom-git-refspec

---

script/generate-documentation

Removed parameter --depth while cloning in script/generate-documentation
because it will result in error (shallow update not allowed) while pushing
new branch

Fix error in nightly doc CI job

---

lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/WebAPI/Controller/Test.pm
t/ui/16-tests_dependencies.t

See https://progress.opensuse.org/issues/59082

Show machine in dependency graph

---

lib/OpenQA/Setup.pm
lib/OpenQA/WebAPI/Plugin/MIMETypes.pm
lib/OpenQA/WebAPI/Plugin/YAMLRenderer.pm
t/22-dashboard.t

Small change so `.bz2` and `.xz` files do not get served with `text/plain` MIME type.
Progress: https://progress.opensuse.org/issues/44564

Add more MIME types so test assets do not get served as text/plain

---

docs/WritingTests.asciidoc
lib/OpenQA/Schema/Result/ScheduledProducts.pm
t/api/02-iso.t
t/ui/17-product-log.t

See https://progress.opensuse.org/issues/56813
---
This does not contain a migration (as suggested in the ticket) yet. For now I've just kept backwards compatibility by still supporting the colon.
A migration would likely touch *every* place where we save job settings: That is of course the job settings table itself but also all scheduling related tables (basically all `lib/OpenQA/Schema/Result/*Settings.pm`).

Allow '@' separator to specify machine dependency

---

docs/UsersGuide.asciidoc
lib/OpenQA/Setup.pm
lib/OpenQA/Task/Asset/Limit.pm
t/37-limit_assets.t

Support configurable patterns for asset cleanup
Patterns match the basename and map to a time in days which overrides the default for untracked assets.
While #2460 removes the hard-coded behavior to never delete repos with `CURRENT` in the name, we want to specify when these files will be cleaned up and it should be longer than the default (30 vs 2 days).
Fixes: [poo#59103](https://progress.opensuse.org/issues/59103)

Support configurable patterns for asset cleanup

---

lib/OpenQA/Task/Asset/Limit.pm

Depending on the time, the string would be a day or two off. This happens because subtracting seconds from days is not correct.

Correctly format the age in days string

---

lib/OpenQA/Utils.pm

Any variable with the suffix "_URL" was understood as an asset by openQA so a
setting like "OPENQA_HOST_URL=https://openqa.opensuse.org" would cause a
warning "Unable to get filename from http://openqa.opensuse.org" which we can
accept with a simple debug message and ignore.
Related progress issue: https://progress.opensuse.org/issues/53399

Treat all non-asset "_URL" settings as debug message only, not warning

---

Makefile
docs/Contributing.asciidoc
script/run-tests-within-container

The test matrix part "FULLSTACK=0 UITESTS=0" was commonly the longest
running on travis CI already with about 23 minutes in comparison to the
next longest which is "FULLSTACK=0 UITESTS=1" with about 17 minutes.
Other parts take even less then that. This commit will conduct the style
checks in parallel to get earlier feedback on style issues as well as
save overall test runtime.

Provide style check feedback earlier with parallel execution

---

.circleci/config.yml

Calling "make test" within a for loop will ignore all results for final
exit code evaluation except the last run which was for
"t/ui/26-jobs_restart.t". This means that all other tests within
"unstable_tests.txt" were effectively ignored. This can for example be
seen in
https://app.circleci.com/jobs/github/os-autoinst/openQA/6274/parallel-runs/0/steps/0-108
This commit fixes this by aborting the for-loop with a failure properly
propagated if any of the "make test" runs fails to succeed within the
specified retries.

.circleci: Fix ignored test results of unstable tests within loop

---

t/25-cache-service.t

The runtime is 196s+-2s vs. 201s+-2s in before

Reduce sleep times in 25-cache-service.t to slightly save testing time

---

assets/javascripts/job_templates.js
assets/stylesheets/codemirror_customization.css
assets/stylesheets/forms.scss
templates/admin/job_template/index.html.ep

Since the sizing relied on the visibility of the guide, we also need to
switch from javascript to CSS for the height adjustment.
Fixes: [poo#59094](https://progress.opensuse.org/issues/59094)

Hide YAML guide by default, expose via a button

---

script/fetchneedles

fetchneedles: Fix missing usage of 'git_update_needles' in 2aadd3e56

---

docker/travis_test/Dockerfile

All dependencies are now provided in devel:openQA:Leap:15.1

travis_test: Switch to supported Leap base after 42.3 is EOL

---

script/client

ObsRsync client uses status codes > 200 to report outcome of operations
https://github.com/os-autoinst/openQA/blob/127fcf3355203c9e5d039cc04c16250478c96013/lib/OpenQA/WebAPI/Plugin/ObsRsync/Controller/Gru.pm#L42

Extend range for success error codes in openqa-client

---

templates/admin/job_template/index.html.ep

In the near future we plan to remove the old job group UI editor fully
replacing it by job group definitions in YAML. As the old editor is
already not easily accessible anymore, e.g. only shown for old
non-migrated job groups the switch would not concern new users or
already migrated job groups.
Related progress issue: https://progress.opensuse.org/issues/44360

Add deprecation notice for old job template editor pointing to YAML

---

.circleci/config.yml
script/generate-documentation

https://progress.opensuse.org/issues/59957
First commit should fix cosmetic problem when too many documentation changes are detected in CI run for every PR
Before: https://circleci.com/gh/os-autoinst/openQA/6397 : `4 files changed, 13617 insertions(+), 9819 deletions(-)`
After: 'Documentation is up to date' if nothing changes, otherwise relevant diff info.
Second commit is challenged by inability of `git diff` to ignore specific lines and introduces more reliable hacks to detect actual changes.

Fix empty documentation commits

---

assets/stylesheets/test-details.scss
lib/OpenQA/WebAPI/Controller/Test.pm
lib/OpenQA/WebAPI/Plugin/Helpers.pm
templates/branding/openSUSE/external_reporting.html.ep
templates/test/module_table.html.ep

Allow branding to set external reporting link to parsed results too.
Since parsed results are all rendered as part of a single template,
module and step id needs to be set directly in a template during
the iteration. And branding template modified to actually use those
values.
I'm not an expert in CSS, and this is the best I can do - the action link is at the bottom right of expanded parsed result text. If anyone know how to put it at the top right (but not increasing height of the collapsed row), that would be more consistent with other places.
You can see how it looks now here: https://openqa.qubes-os.org/tests/4710#step/QubeManagerTest/69
I've included changes to openSUSE branding, but in fact I've tested it on a Qubes OS one (not published yet). BTW is there a way to load branding …

Include external reporting template for parsed results too

---

lib/OpenQA/Worker/Isotovideo/Client.pm
lib/OpenQA/Worker/Job.pm

This code is not used anymore since we use the status file instead of the API.

Remove dead code from isotovideo client

---

docs/UsersGuide.asciidoc

As the old job templates editor is deprecated we should more prominently
describe the new YAML job templates editor but also describe better how
to migrate including a scripted way to batch-process.
Related progress issue: https://progress.opensuse.org/issues/60020#change-258569

docs: Describe YAML job templates editor as default with migration script from old

---

docker/travis_test/Dockerfile

See https://build.opensuse.org/package/show/devel:openQA/openqa_dev
for current test results where I deleted the _service file and maintained the
Dockerfile manually.
https://github.com/os-autoinst/os-autoinst/pull/1271#issuecomment-556009996
shows that the generated container can be used within os-autoinst tests.
Related progress issue: https://progress.opensuse.org/issues/53915

travis_test: Fix Dockerfile based on tests in OBS

---

lib/OpenQA/Schema/Result/Jobs.pm
t/24-worker-jobs.t

See POO #60059 - this fixes one part, by making the logs of
virtio consoles after the first show up as result files in the
Logs & Assets tab.

Make virtio_console1.log etc. show up as result files

---

docs/UsersGuide.asciidoc

I reworded the sentence about aliases because I think it's important to use the official YAML names for `&` and `*`.
I also changed the layout of the YAML slightly because I find it more readable to have the alias on the same line, and we're saving more space.

doc: Reword sentence about alias

---

docker/devel:openQA:ci/base/Dockerfile
docker/travis_test/Dockerfile
openQA.spec

This should help Fedora where the package does not exist.
Most likely we do not actually need this package. If it all we might
need it for xterm-console in os-autoinst for some remote backends.
OBS test project: https://build.opensuse.org/project/show/home:okurz:branches:devel:openQA:enhance:fonts

Remove likely unneeded dependency xorg-x11-fonts

---

docker/devel:openQA:ci/base/Dockerfile
docker/travis_test/Dockerfile
openQA.spec

This reverts commit 123bd1e80dd8722b98edf63838c713a101d2f78c as our
circle CI tests in follow-up PRs showed that chromium could not start up
anymore.

Bring back 'xorg-x11-fonts' needed for chromium startup

---

README.asciidoc
docs/Contributing.asciidoc
script/generate-documentation

https://progress.opensuse.org/issues/60056

Change CI badge in README.asciidoc

---

.circleci/dependencies.txt
cpanfile
docker/travis_test/Dockerfile
lib/OpenQA/WebAPI/Command/gru/run.pm
openQA.spec
systemd/openqa-gru.service

Small change to trigger a reset of all remaining Gru locks after a restart of the service. It does require Minion 10.0 though.
Progress: https://progress.opensuse.org/issues/57689

Reset all leftover Gru locks after restart

---

lib/OpenQA/CacheService.pm
lib/OpenQA/CacheService/Model/Cache.pm
lib/OpenQA/CacheService/Task/Asset.pm
lib/OpenQA/CacheService/Task/Sync.pm
lib/OpenQA/Worker/Engines/isotovideo.pm
t/25-cache-service.t
t/25-cache.t

This PR is a followup to #2463. It will allow us to finally follow the entire life cycle of every asset processed by the cache service.
Asset download and test sync tasks used to only send their logs to the `autoinst-log.txt` file of the job that requested the task first. This PR ensures that all those log messages are also written to the cache service journal. So we can from now on always look at the `openqa-worker-cacheservice-minion` journal to see exactly what happened with a specific asset.
Additionally the content of the cache service log messages has been rephrased a bit to make it easier to understand what actually happened and to follow the flow of events. Some log messages got moved to a higher level to be able to add more context information.
Progress: …

Forward asset and sync job logs to the cache service journal

---

templates/admin/group/group_property_editor.html.ep

Just a few changes I've came up with when working on the size limit for assets on parent group level.
---
* Avoid redundant code
* <s>Don't use 'Job group properties' on parent group page</s>
* Remove wrong for attribute of one of the labels

Improve group property HTML template

---

script/generate-documentation

https://progress.opensuse.org/issues/60278

Check generate-documentation if target branch exists

---

t/fixtures/01-jobs.pl
t/testresults/00099/00099926-opensuse-Factory-staging_e-x86_64-Build87.5011-minimalx
t/ui/18-tests-details.t
templates/test/result.html.ep

If job results do not have any test modules a job very likely aborted
very early and an empty details tab would not provide useful information
so instead we show the content of the log directly in the details tab
where a test reviewer can most likely see the failure reason.
Related progress issue: https://progress.opensuse.org/issues/35017

Show log content in test details tab on no module results

---

lib/OpenQA/CacheService.pm
lib/OpenQA/CacheService/Model/Cache.pm
lib/OpenQA/CacheService/Task/Asset.pm
t/25-cache-service.t
t/25-cache.t

This PR increases the SQLite busy timeout from 30 seconds to 5 minutes. That should give slower operations like Minion queue repairs enough time to finish even on very slow workers. I've also removed the explicit `exclusive` locks, since we only perform a single query in every case, and those will automatically acquire the lock they need. And finally each process will now only use one SQLite connection.
All of this should be enough to resolve the problems we had with jobs getting stuck and the cache service dying.
Progress: https://progress.opensuse.org/issues/58484

Increase SQLite busy timeout and reduce the number of SQLite connections

---

lib/OpenQA/Jobs/Constants.pm
lib/OpenQA/WebAPI/Controller/Test.pm
t/10-tests_overview.t

See https://progress.opensuse.org/issues/60458

Take all incomplete results into account in overview statistics

---

cpanfile
openQA.spec

The log context feature requires Mojolicious 8.24. This resulted in OSD job failures without useful error messages in `autoinst-log.txt` after upgrading the workers. We did not notice this problem earlier because we install the latest Mojolicious version (8.26) on Circle CI, the staging machines and O3 automatically.
Progress: https://progress.opensuse.org/issues/60626

For the log context feature we require Mojolicious 8.24 or newer

---

lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/Schema/Result/ScheduledProducts.pm
lib/OpenQA/WebAPI/Controller/Test.pm
t/api/02-iso.t
t/ui/01-list.t
t/ui/10-tests_overview.t

This pull request has two purposes:
1. After we defined a test suite in YAML with an alias, the `Test result overview` page
and the `All Test` page will show the job template name (the new alias).
2. When triggering a job using `isos post`, the parameter `TEST` support using
job template name.
See: https://progress.opensuse.org/issues/59097

Show job template names if defined instead of test suites

---

docs/images/architecture.graphml
docs/images/architecture.svg
lib/OpenQA/CacheService/Client.pm
lib/OpenQA/Utils.pm
script/openqa-workercache
t/16-utils.t
t/lib/OpenQA/Test/Utils.pm

Small change to include the cache service in `OPENQA_BASE_PORT` for consistency. Just in case someone wants to run the cache service for local development.

Include the cache service when generating ports dynamically

---

assets/javascripts/test_result.js
lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Controller/Test.pm
t/10-jobs.t
t/data/first_bad.json
t/data/last_good.json
t/ui/18-tests-details.t
templates/test/dependencies.html.ep
templates/test/infopanel.html.ep
templates/test/investigation.html.ep
templates/test/result.html.ep

In the case of a failed job where not carry over is available, for
example in the common case of a failed job following a passed one, the
important question to answer in general is "what changed" which can have 
multiple different angles. This commit adds a simple "diff" of the "last
good" job vs. the current "first bad" relying on the file vars.json from
the os-autoinst backend which provides all relevant information for the
most cases.
This commit adds a plain HTML route as well as JSON routes. The route is
called from test details when a user clicks on a tab to gather the
investigation details.
Example output corresponding to the investigation details:
Last good: 99983
Difference of job data:
```
--- t/data/openqa/testresults/00099/00099983-Unicorn-42-pink-x86_64-Build667-K@RainbowPC/va …
```

Provide investigation hints for failed jobs on request

---

lib/OpenQA/CacheService.pm
lib/OpenQA/CacheService/Controller/Influxdb.pm
lib/OpenQA/WebAPI/Controller/Admin/Influxdb.pm
systemd/openqa-worker-cacheservice.service
t/25-cache-service.t

This is a fairly small change to allow the job queue on the worker side to be monitored just like we already monitor the job queue on the webui side. Format is exactly the same, just the route is `/influxdb/minion` instead of `/admin/influxdb/minion`.
To make sure normal cache service operations are not affected negatively in any way by the extra load, this patch also switched from `daemon` to `prefork`, with similar settings as the webui. That should also be a pretty harmless change after the recent refactorings, but i will test it on the staging machines anyway before merging this PR.
Progress: https://progress.opensuse.org/issues/60440

Allow monitoring of Minion jobs on every worker

---

docker/travis_test/Dockerfile

travis tests for os-autoinst find aspell but no dic.

travis_test: Add missing dictionary for os-autoinst

---

t/25-cache-service.t

To fix the currently failing tests in the repo.

Use the correct new port in cache service monitoring tests

---

assets/javascripts/test_result.js
assets/stylesheets/test-details.scss
t/ui/18-tests-details.t
templates/test/result.html.ep

* Just use an ordinary pre element and load contents via AJAX
* Remove previous attempts to set the height
* Adding further embedded logfiles is possible without further JavaScript (just add an element with attributes class="embedded-logfile" and data-src)

Fix height of embedded logfile

---

script/openqa-clone-custom-git-refspec

This adds support to specify a comma-separated list of job URLs instead of a
single one as second command line parameter. The clone with according
parameters is then conducted for each specified list.
Also this adds a "markdown" mode especially useful when a list of jobs is
specified and one wants to copy the command output into a github pull request
in markdown list format.
$ env MARKDOWN=1 openqa-clone-custom-git-refspec \
https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/7084 \
https://openqa.opensuse.org/tests/1105660,\
https://openqa.opensuse.org/tests/1105386,\
https://openqa.suse.de/tests/3676702
* [opensuse-Tumbleweed-DVD-x86_64-Build20191206-kde-wayland@64bit_virtio](https://openqa.opensuse.org/t1105940)
* …

openqa-clone-custom-git-refspec: Add support for comma-separated job list

---

lib/OpenQA/CacheService/Model/Cache.pm
lib/OpenQA/Schema/ResultSet/Assets.pm
t/14-grutasks.t
t/25-cache.t

Small change requested by @okurz that changes all cache service log messages to use more readable size values like `50GiB` instead of `53687091200`.
Progress: https://progress.opensuse.org/issues/60389

Use human readable size values in cache service logs

---

lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
t/api/08-jobtemplates.t

`$` in a regex means
Match the end of the string or before newline at the end of the string
`\z` really means end of the string.
Also submitting an invalid prio didn't result in the correct error message.

Fix regex and error message for prio

---

lib/OpenQA/Task/Asset/Download.pm
t/14-grutasks.t

* Remove unreachable code
* Add test for download errors
* Make code more readable, e.g. avoid nesting
* Improve error messages, e.g. include HTTP return code
See https://progress.opensuse.org/issues/57782

Improve asset download

---

lib/OpenQA/WebAPI/Controller/File.pm
t/ui/07-file.t

This fixes the problem @Martchus ran into yesterday where requesting a non-existing asset results in a connection timeout without any response at all.

Missing assets should not result in a connection timeout

---

lib/OpenQA/Schema/Result/Screenshots.pm
lib/OpenQA/Schema/ResultSet/Screenshots.pm
t/42-screenshots.t

The previous approach was to catch conflicts on screenshot insertion in
perl context yielding the right functional behaviour but also causing a
log entry for every image object amounting to multiple gigabytes of
postgres database error log files which can cause obvious problems. By
using a similar approach as is already done in
lib/OpenQA/Schema/Result/Jobs.pm with raw SQL we can ask the database
for silent conflict handling and more efficiently not involving perl
exception handling.
Related progress issue: https://progress.opensuse.org/issues/60926

Prevent massive database errors on screenshot insertion

---

lib/OpenQA/WebAPI/Controller/Step.pm

Related progress issue: https://progress.opensuse.org/issues/39917

Remove "Jump to video" icon from "needle view" when video is unavailable

---

lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/Schema/ResultSet/Screenshots.pm
t/42-screenshots.t

* t: Use more concise code in t/42-screenshots.t
* Use more conventional variable name '' for raw db calls

Improvements for '$sth' and t/42-screenshots.t

---

Makefile
lib/OpenQA/Schema/Result/ScheduledProducts.pm
lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
openQA.spec
systemd/openqa-enqueue-asset-and-result-cleanup.service
systemd/openqa-enqueue-asset-and-result-cleanup.timer
systemd/openqa-webui.service

instead every time after a job or an ISO has been posted which can happen quite frequently.
See https://progress.opensuse.org/issues/55241

Trigger tasks for limiting assets and results/logs hourly

---

t/lib/OpenQA/SeleniumTest.pm
t/ui/18-tests-details.t

For me this reduces the test run time from 44s to 23s.

t: Save execution time in 18-tests-details by disabling wait timeout when expecting 0 needles

---

assets/assetpack.def
assets/stylesheets/video.scss
lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Plugin/Helpers.pm
t/ui/18-tests-details.t
templates/test/downloads.html.ep
templates/test/video.html.ep

Based on an idea by Stefan Bruens we can use timestamp information
relating the video runtime to realtime in a video player.
Related progress issue: https://progress.opensuse.org/issues/42050

Improve video player

---

lib/OpenQA/Schema/Result/JobGroups.pm
lib/OpenQA/Schema/ResultSet/JobTemplates.pm
lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
t/api/08-jobtemplates.t

Split into subroutines, move code to
OpenQA::Schema:Result::JobGroups
OpenQA::Schema::ResultSet::JobTemplates
This will make testing easier.
Some templates don't have a final newline, which resulted in the last line not being indented correctly
This is a followup to #2589 
Related ticket: https://progress.opensuse.org/issues/60782

Refactor JobTemplates and fix regex substitution

---

lib/OpenQA/Scheduler.pm
lib/OpenQA/Scheduler/Client.pm
lib/OpenQA/Scheduler/Controller/API.pm
lib/OpenQA/Scheduler/Model/Jobs.pm
lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/WebAPI/Controller/API/V1/Worker.pm
lib/OpenQA/WebSockets/Controller/Worker.pm
t/04-scheduler.t
t/05-scheduler-full.t
t/lib/OpenQA/Test/Utils.pm

Same as https://github.com/os-autoinst/openQA/pull/2595 which was buggy.
Marking previous jobs of a worker as incomplete when it shows up again is so far handled within the web socket server and the registration API route. This change moves all aspects of handling this to the API. This will hopefully scale better because the regular API can use preforking.
See https://progress.opensuse.org/issues/60866

Move worker reported back from scheduler to webui

---

lib/OpenQA/Schema/Result/Jobs.pm
t/10-jobs.t

Looking up the git log diff between "last good" and "first bad" of a
scenario history can yield an empty result meaning that there are no
changes, i.e. both git hashes most likely match. If this is the case we
can point the reviewer to the likely hypothesis that test changes are
not the cause of a job failure.
Related progress issue: https://progress.opensuse.org/issues/19720

job investigation: Give explanation on no test changes

---

lib/OpenQA/Schema/Result/Assets.pm
lib/OpenQA/Task/Asset/Limit.pm
t/37-limit_assets.t

* Log exactly one message per removal attempts (either asset does
not exist, can not be removed or the removal failed)
* Don't distinguish assets by their type; just remove files
via unlink() and try remove_tree() otherwise
* Add tests

Remove registered assets regardless of the type

---

lib/OpenQA/CacheService.pm
lib/OpenQA/CacheService/Controller/API.pm
lib/OpenQA/CacheService/Model/Cache.pm
lib/OpenQA/CacheService/Model/Downloads.pm
lib/OpenQA/CacheService/Plugin/Helpers.pm
lib/OpenQA/CacheService/Task/Asset.pm
lib/OpenQA/CacheService/Task/Sync.pm
lib/OpenQA/Worker/Engines/isotovideo.pm
t/25-cache-service.t
t/25-cache.t
t/api/02-assets.t
t/basic.t
templates/test/downloads.html.ep

This fixes the problem where only the first job requesting an asset from the Cache Service gets the logs. Every other job requesting the same asset would have gotten `Asset "..." was downloaded by another job, details are therefore unavailable here` previously. Making it non-trivial for test developers to find the cause for many cache service problems.
There was also a race condition in `25-cache-service.t`, so that test should be much more stable now.

Share Cache Service logs between multiple concurrent downloads

---

lib/OpenQA/CacheService/Client.pm

Small change that should help with some cache service issues. The default inactivity timeout of `Mojo::UserAgent` is only 20 seconds. That can be a bit low in cases where the SQLite database is locked by a bigger query. We set 5 minutes for the SQLite busy timeout in the cache service, so using the same value for the client would seem reasonable.
Progress: https://progress.opensuse.org/issues/60866

Increase the inactivity timeout of the cache service client

---

lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/WebAPI/Controller/Test.pm
t/10-jobs.t

A simpler variant of https://github.com/os-autoinst/openQA/pull/2623 without the HTML table changes for now
* job investigation: Ensure consistent output with sorted hash keys
* job investigation: Provide test+needles git log diff and files stat diff
* job investigation: Skip "merge" commits with no helpful information in git log diff

job investigation: test+needle git log+stats, skip merge commits in git log

---

lib/OpenQA/Schema/ResultSet/JobTemplates.pm
lib/OpenQA/WebAPI/Controller/Test.pm

- Do only one `update` call
- Restructure `%settings_by_job_id`
Followup-To: https://github.com/os-autoinst/openQA/pull/2602
Issue: https://progress.opensuse.org/issues/60782

Minor cleanups for job settings

---

lib/OpenQA/Task/Asset/Download.pm

It looks like @Martchus just did a search-and-replace on all
occurrences of `return`, changing them to `return undef`, but
that broke this line which actually returns something. It causes
test failures with this error:
Gru job failed
Reason: Can't modify non-lvalue subroutine call of &Minion::Job::retry at /usr/share/openqa/script/../lib/OpenQA/Task/Asset/Download.pm line 37.

Asset download: fix return statement broken in f0d70f1

---

script/openqa-clone-custom-git-refspec

Add a space between `curl` and options. This fixes usage of requests with a github token.

openqa-clone-custom-git-refspec: fix curl_github

---

assets/javascripts/admin_assets.js
assets/stylesheets/admin-pages.scss
dbicdh/PostgreSQL/deploy/85/001-auto-__VERSION.sql
dbicdh/PostgreSQL/deploy/85/001-auto.sql
dbicdh/PostgreSQL/upgrade/84-85/001-auto.sql
dbicdh/_common/upgrade/84-85/000-backup-asset-size-defaults-of-parents.pl
dbicdh/_source/deploy/85/001-auto-__VERSION.yml
dbicdh/_source/deploy/85/001-auto.yml
docs/UsersGuide.asciidoc
etc/openqa/openqa.ini
lib/OpenQA/Schema.pm
lib/OpenQA/Schema/Result/JobGroupParents.pm
lib/OpenQA/Schema/Result/JobGroups.pm
lib/OpenQA/Schema/ResultSet/Assets.pm
lib/OpenQA/Task/Asset/Limit.pm
lib/OpenQA/WebAPI/Controller/API/V1/JobGroup.pm
t/14-grutasks.t
t/36-job_group_defaults.t
t/37-limit_assets.t
t/api/10-jobgroups.t
t/ui/13-admin.t
templates/admin/group/group_property_editor.html.ep

See https://progress.opensuse.org/issues/56453
---
The fact that we have job groups not within parents makes describing the logic a little bit complicated:
1. If an asset belongs to a job group which is part of a parent group the limit defined on job group level is ignored. Instead, the asset is only accounted to the parent group if it fits in. If it doesn't fit in it doesn't matter if it would have fit into the job group because that limit is ignored.
2. If an asset belongs to a job group which is not part of a parent group the size limit of the job group is used as usual.
3. An asset is only accounted to one parent group or job group at the same time. If an asset is used across groups it will be accounted to the largest parent or job group with enough space according to (1) and (2). …

Allow overriding asset size limit on parent group level

---

lib/OpenQA/CacheService/Model/Cache.pm
t/25-cache.t

This fixes the problem we noticed earlier during the OSD deployment. Unfortunately we allow the webui host to be configured with and without scheme and port. The tests only ever covered one case, so everything seemed fine when we merged #2639.

Fix webui host handling in the cache service

---

lib/OpenQA/WebAPI.pm

Save unnecessary database queries
Issue: https://progress.opensuse.org/issues/61919

Only fetch job groups when delivering HTML

---

lib/OpenQA/Schema.pm
t/deploy.t

* Try to access common pages in the migrated state
* Have the db populated with fixtures when testing migrations so it is at least a little bit closer to migrations in production
---
This should prevent problems like the one we found yesterday. I also checked whether it actually fails if one removes the line `ALTER TABLE job_group_parents ADD COLUMN size_limit_gb integer;` from `001-auto.sql`.

Test whether web UI actually works after db migration

---

lib/OpenQA/Worker/Engines/isotovideo.pm
t/full-stack.t

Currently it is possible that on a busy worker assets get deleted from the cache before the job that requested them last is finished. By using hardlinks instead of symlinks we can keep using the same cleanup logic we have in the past, but all assets will also be referenced from the pool directory of the job. So from now on assets can only ever vanish from the worker once all references have been purged from `/var/lib/openqa/cache` and `/var/lib/openqa/pool`.
There are two possible solutions, one is to first check if both locations are on the same device and only then create the hardlink, the other is to always try to create a hardlink first and to fall back to symlinks. We've talked about this on Rocket Chat and the former got more votes.
Progress: …

Create hardlinks instead of symlinks for cached assets when possible

---

docs/UsersGuide.asciidoc
etc/openqa/openqa.ini
lib/OpenQA/Schema/Result/JobGroupParents.pm
lib/OpenQA/Schema/ResultSet/Assets.pm
t/14-grutasks.t
t/36-job_group_defaults.t
t/37-limit_assets.t

* The default specified in the config file is only used for job groups but not parent groups.
* If no size limit on parent group level is specified the old behavior of only considering limits on job group level is retained.
---
I was convinced that https://github.com/os-autoinst/openQA/pull/2536 already made openQA behave like this. Otherwise the UI commits contained by that PR wouldn't make any sense, too. But I also remember that I implemented this some time ago and quickly reconstructed the changes. Seems like I accidentally dropped the commit when rebasing https://github.com/os-autoinst/openQA/pull/2536.

Don't have a default size limit on parent group level

---

script/openqa-clone-job

The problem has been introducted by https://github.com/os-autoinst/openQA/commit/aab8829739e26b18b52d2691f307cc16c6164f50. This fix simply touches assets after the download so they appear new.

Prevent old but newly cloned assets from being cleaned up immediately

---

docs/Contributing.asciidoc
docs/Installing.asciidoc
script/generate-documentation
script/openqa-bootstrap

This gives a better introduction for making a development setup. Parts of it are from the openQA-helper repository which is also linked as a concrete example.

Upstream documentation from openQA-helper

---

lib/OpenQA/CacheService/Model/Cache.pm
t/25-cache.t

While testing #2652 on the staging machines last week, i noticed that symlinked cache directories on workers did not actually work yet. This should resolve the problem.
Progress: https://progress.opensuse.org/issues/55373

Fix support for symlinked cache dirs

---

lib/OpenQA/CacheService.pm

Small patch to turn this
```
Jan 10 17:08:54 openqaworker11 openqa-workercache[15565]: [2020-01-10 17:08:54.15458] [1756] [info] [#10278] Downloading: "SLES-15-SP1-x86_64-Installtest.qcow2"
Jan 10 17:08:54 openqaworker11 openqa-workercache[15565]: [2020-01-10 17:08:54.15815] [1756] [info] [#10278] Cache size of "/var/lib/openqa/cache" is 7.4GiB, with limit 20GiB
```
into this
```
Jan 13 16:48:37 openqaworker11 openqa-workercache[15562]: [15614] [i] [#10281] Downloading: "SLES-15-SP1-x86_64-Installtest.qcow2"
Jan 13 16:48:37 openqaworker11 openqa-workercache[15562]: [15614] [i] [#10281] Cache size of "/var/lib/openqa/cache" is 7.4GiB, with limit 20GiB
```
in the journal.

Fix cache service log formatting

---

lib/OpenQA/Script.pm
script/openqa-clone-job
t/35-script_clone_job.t

* See https://progress.opensuse.org/issues/62021
* Moves the asset and job download into the `OpenQA::Scripts` module to ease testing

Test asset download of openqa-clone-job script

---

.circleci/config.yml

The actual code is always visible in the details, so this just makes the overview more readable without.

Add labels to auth, git and dependency PR steps in CircleCI

---

lib/OpenQA/CacheService/Model/Cache.pm
t/25-cache.t
t/lib/OpenQA/Test/Utils.pm

This patch makes the cache service retry downloads for almost every error type 5 times (with a small sleep in between each attempt). Server as well as network errors.
Progress: https://progress.opensuse.org/issues/55529

Retry cache service downloads for many more errors

---

.circleci/build_dependencies.sh
.circleci/config.yml

Previous implementation tried to run tidy inside dependency_bot container which is only suitable to run docker. This PR moves tidy logic inside proper container.

Fix tidy in night job

---

systemd/openqa-worker-cacheservice.service

I made a small mistake when i copied the prefork parameters from the webui to the cache service API server. The webui has an Apache reverse proxy to handle HTTP keep-alive connections, but the cache service does not.
That means when a worker is under heavy load you can start seeing errors like `[2020-01-17T11:29:56.0370 CET] [error] [pid:47664] Unable to setup job 3801895: Cache service not reachable: Inactivity timeout`, because other workers were blocking access to the API server with their keep-alive connections.

Allow more than one keepalive connection per cache service worker

---

lib/OpenQA/Resource/Jobs.pm
lib/OpenQA/Scheduler/Model/Jobs.pm
lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/Schema/Result/Workers.pm
lib/OpenQA/WebSockets/Controller/Worker.pm
t/04-scheduler.t
t/05-scheduler-capabilities.t
t/05-scheduler-dependencies.t
t/05-scheduler-full.t

* Associate workers and jobs before sending the job to the worker
* Set the worker's current job only when the worker reports it
* Consider all unfinished jobs in stale job handling on worker status updates via web sockets
This should help to avoid the problems mentioned in the ticket https://progress.opensuse.org/issues/62015.
---
In overall this change is actually a simplification (also in terms of lines of code; 54 additions, 81 deletions). So things should work as before but with less effort and of course avoiding the race condition from the issue.
I've tested this locally by simulating a slow scheduler, a worker which doesn't accept jobs and other problems which cause the changed code to be executed. It seems to work although I've once managed to have an assigned job which had …

Avoid race condition in job scheduling

---

lib/OpenQA/CacheService/Model/Cache.pm
t/25-cache.t
t/lib/OpenQA/Test/Utils.pm

Currently the cache service retries all downloads that result in 4xx and 5xx responses, as well as connection errors. But unless 4xx responses are misused by the server, there should be no chance to ever get a successful response just by retrying 5 times. So i believe it is more efficient to disable that case in the retry logic.
Progress: https://progress.opensuse.org/issues/55529

Do not retry downloads with 4xx response

---

.circleci/dependencies.txt
cpanfile
lib/OpenQA/JobTemplates.pm
lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
lib/OpenQA/WebAPI/Plugin/YAMLRenderer.pm
openQA.spec
script/openqa-validate-yaml
t/16-utils-job-templates.t
t/data/job-templates/openqa.yaml
t/data/job-templates/schema-invalid.yaml

So one can easily validate local YAML files without having to post to the API.
* Move validation code to OpenQA::JobTemplates
* Add test for invalid schema
Related issue: https://progress.opensuse.org/issues/60329

Add CLI tool openqa-validate-yaml

---

lib/OpenQA/WebAPI/Plugin/ObsRsync/Controller/Folders.pm

ObsRsync Plugin UI allows downloading logs and scripts used in synchronization.
It will be more practical if correct MIME is set for that.

Set text mime in ObsRsync download

---

lib/OpenQA/Schema/Result/JobModules.pm
t/10-jobs.t

This is fixing a mistake within https://github.com/os-autoinst/openQA/pull/2654. Otherwise the execution time would be discarded by openQA and never displayed.

Use new format to store job module details

---

script/load_templates
t/01-compile-check-all.t
t/40-script_load_templates.t
t/data/40-templates.pl

It makes no sense to run other commands in this case lest we end up with inconsistent changes on the off chance that it comes up again.
Add an initial unit test for load_templates.
Related to: [poo#60118](https://progress.opensuse.org/issues/60118)

load_templates: fail early if host is unreachable

---

assets/javascripts/index.js

This will allow setting the get parameter `interval` to a value of seconds after which the index page is reloaded - but without loading indicator to always show results.
This is intended for dashboard usage.

Add silent reload of dashboard contents for fullscreen mode

---

lib/OpenQA/WebAPI/Plugin/ObsRsync.pm

Plugin UI allows requesting current build id from OBS. Now add support for snapshot id as well

Parse Snapshot number in ObsRsync plugin

---

lib/OpenQA/WebAPI/Plugin/ObsRsync.pm
t/ui/27-plugin_obs_rsync_obs_status.t

Current implementation doesnt support configuration of api url per project jet, so needs a workaround

Workaround api request in ObsRsync Plugin

---

.circleci/config.yml
.circleci/unstable_tests.txt
t/lib/OpenQA/SeleniumTest.pm
t/ui/14-dashboard-parents.t
t/ui/14-dashboard.t
t/ui/18-tests-details.t

* Treat all previously unstable tests as stable after proof of stability
* t: Extract method for ajax/animation handling
* Stabilize t/ui/14-dashboard-parents.t by relying on "collapsed" only
All previously unstable tests are now proven to be stable, see https://app.circleci.com/jobs/github/os-autoinst/openQA/12038/parallel-runs/0/steps/0-108 for test results.
Related progress issue: https://progress.opensuse.org/issues/53498

Fix unstable tests

---

script/openqa-clone-custom-git-refspec
t/40-script_openqa-clone-custom-git-refspec.t

Related progress issue: https://progress.opensuse.org/issues/62600

openqa-clone-custom-git-refspec: Provide option parsing with help text

---

lib/OpenQA/Setup.pm
lib/OpenQA/WebAPI/Plugin/ObsRsync.pm
lib/OpenQA/WebAPI/Plugin/ObsRsync/Task.pm
t/api/14-plugin_obs_rsync_async.t
t/config.t

Current goal is to have up to ~24h waiting time, which should be enough for OBS publisher finish work on corresponding repositories' metainfo.

Limit ObsRsync task retries

---

public/schema/JobTemplates-01.yaml

to avoid duplication
Note that the regex for the settings and for the default settings were
different and I made them the same as I assumed this was an oversight.
Related issue: https://progress.opensuse.org/issues/60371

Use aliases in JobTemplate schema

---

t/40-script_openqa-clone-custom-git-refspec.t

Without the local override, failures point to the wrong line.
**Before**
```
not ok 18 - accepts comma-separated list of jobs
#
```
**After**
```
not ok 18 - accepts comma-separated list of jobs
#
```

Have test_once in clone-custom-git-refspec test report errors correctly

---

t/ui/17-product-log.t

This changes simply scrolls to the right before clicking the buttons to ensure they are always visible. Otherwise the test sometimes fails.

Fix product log test which might fail when table slightly overflows

---

script/fetchneedles
script/openqa-bootstrap

Seems I ran into https://github.com/koalaman/shellcheck/wiki/SC2015
Related progress issue: https://progress.opensuse.org/issues/62549

fetchneedles: Do not fail the script when we are on the correct branch

---

templates/layouts/error.html.ep
templates/not_found.html.ep

Otherwise non-existance of these variables raises an exception because templates are evaluted `strict`ly i.e.
```
Global symbol "$appname" requires explicit package name
```
Note: As discussed this still leaves using different templates in our micro services.

Avoid undefined $appname/$api_description errors by using the stash

---

script/fetchneedles

2aadd3e56 was probably incomplete in the sense that we recreate the master
branch but never set the upstream information causing the problem:
```
There is no tracking information for the current branch.
Please specify which branch you want to rebase against.
```
To prevent that we can set the upstream branch when recreating a branch.
Additionally it is a safer approach if we specify explicitly which branch to
fetch and rebase against as we already have the branch/needles_branch as
configuration parameters supplied.
Tested manually:
* Test 1: needles repo on valid branch -> fetch+rebase with explicit branch
works fine
* Test 2: `git co HEAD^^^^` to detach from master -> fetchneedles calls
self-repair including `git branch --set-upstream-to=origin/master master`
Related progress issue: …

fetchneedles: Fix "no tracking information for the current branch" on self-repair

---

script/openqa-clone-custom-git-refspec
t/40-script_openqa-clone-custom-git-refspec.t

Given a PR on GitHub, having one or more tests in the description should be sufficient to run them without having to specify them on the command line.
This is a prerequisite to automated test runs for PRs in CI.

Have openqa-clone-custom-git-refspec parse PR for test URLs

---

lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
script/load_templates
t/05-scheduler-full.t
t/14-grutasks.t
t/40-script_load_templates.t
t/data/40-templates.json
t/lib/OpenQA/SeleniumTest.pm
t/lib/OpenQA/Test/Utils.pm
t/ui/27-plugin_obs_rsync_status_details.t

- The unit test also runs a webui with fixtures to verify how templates are loaded and how errors are handled.
- `SeleniumTest::start_app` is re-based onto `OpenQA::TEST::Utils::create_webapi` since both do the same except the latter was missing the schema hook.
- Fail cleanly in `JobTemplate::update` if not template was specified.
- Make Selenium start helpers internal
Related to: [poo#60118](https://progress.opensuse.org/issues/60118)

load_templates: better error handling

---

lib/OpenQA/WebAPI/Command/gru/run.pm
lib/OpenQA/WebAPI/Plugin/Gru.pm
t/14-grutasks.t
t/17-build_tagging.t
t/api/02-iso.t
t/api/14-plugin_obs_rsync.t
t/ui/27-plugin_obs_rsync_obs_status.t

Every time the "--oneshot" command runs it registers yet another worker
event handler. Causing more and more overhead each time. But we don't
actually need to use commands to run jobs in tests. Minion already has
method for that we can use instead.

Only rebless gru jobs once

---

lib/OpenQA/WebAPI/GruJob.pm
t/14-grutasks.t
t/lib/OpenQA/Test/Utils.pm

Previously gru would always capture STDOUT/STDERR for every job, but
often just throw it away without storing it anywhere. This made
debugging often rather problematic. Now it is always available in the
"output" note, which is easily introspectable from the Minion ui.
Additionally there is now also a "run_gru_job" test utility, that will
enqueue and perform a single job safely. There was a possible race
condition before, because the previously used "--oneshot" feature does
not run jobs selectively with id.

Consistently store gru job output as a note

---

lib/OpenQA/Worker.pm
lib/OpenQA/Worker/WebUIConnection.pm
t/24-worker-overall.t
t/24-worker-webui-connection.t

This helps with incompletes like https://openqa.suse.de/tests/3863913
* The reason for the API failure is consistent with how it is usually provided (e.g. has a details error message).
* If the authentication error only happened once the job wouldn't even be incomplete. The worker would still be restarted after the job is done (e.g. reloading credentials from the config file might help).

worker: Improve inconsistent reason and logging

---

lib/OpenQA/Worker/Engines/isotovideo.pm

* worker: Remove redundant worker information log output
* worker: Simplify '->stop' call slightly
* Remove redundant timestamp output in worker log

worker: Enhance log output slightly

---

script/openqa-clone-custom-git-refspec
t/40-script_openqa-clone-custom-git-refspec.t

When running openqa-clone-custom-git-refspec with arguments containing
bash special chars like '(' we get an syntax error.
e.g:
```
openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/9253 https://openqa.suse.de/tests/3851992 'COMMAND_EXCLUDE=^(?!abort01)'
```

Fix extra arg escaping on clone_custom_git_refspec

---

lib/OpenQA/CacheService/Model/Cache.pm
lib/OpenQA/Downloader.pm
lib/OpenQA/Task/Asset/Download.pm
lib/OpenQA/WebAPI/GruJob.pm
t/14-grutasks.t
t/25-cache.t
t/25-downloader.t
t/lib/OpenQA/Test/Utils.pm

This makes all the features the cache service currently has, such as retries, available for asset downloads in the webui. Just need to make sure test coverage is good enough. As it turns out, features like auto-extract did not have any tests at all.
Progress: https://progress.opensuse.org/issues/62459

Use a shared downloader for cache service and webui

---

lib/OpenQA/Task/Job/Limit.pm

This change gets rid of some test warnings that were no longer hidden since #2736 was applied yesterday.
```
t/14-grutasks.t ................................ 24/? Use of uninitialized value $max_id in numeric le (<=) at /home/squamata/project/lib/OpenQA/Task/Job/Limit.pm line 63.
Use of uninitialized value $i in numeric le (<=) at /home/squamata/project/lib/OpenQA/Task/Job/Limit.pm line 63.
Use of uninitialized value $i in addition (+) at /home/squamata/project/lib/OpenQA/Task/Job/Limit.pm line 64.
Use of uninitialized value $max_id in numeric le (<=) at /home/squamata/project/lib/OpenQA/Task/Job/Limit.pm line 63.
t/14-grutasks.t ................................ 27/? Use of uninitialized value $max_id in numeric le (<=) at /home/squamata/project/lib/OpenQA/Task/Job/Limit.pm line 63.
Use …
```

Handle the case where there are no screenshots more gracefully

---

t/24-worker-overall.t

One of the tests in #2723 contained some bad code that caused a warning. I guess it was meant to call the original code from the mock.
```
t/24-worker-overall.t .......................... 1/? Mojo::Reactor::Poll: Timer failed: Undefined subroutine &OpenQA::Worker::WebUIConnection called at t/24-worker-overall.t line 351.
```

Silence a warning in 24-worker-overall.t

---

docs/Installing.asciidoc

Related progress issue: https://progress.opensuse.org/issues/46742

docs: Add hint about importance of using the same filesystem for cache+pool

---

assets/javascripts/openqa.js
assets/javascripts/overview.js
assets/javascripts/tests.js
lib/OpenQA/Resource/Jobs.pm
lib/OpenQA/Schema/Result/Assets.pm
lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
t/15-assets.t
t/api/04-jobs.t
t/ui/26-jobs_restart.t
templates/webapi/test/list.html.ep
templates/webapi/test/overview.html.ep

**See https://github.com/os-autoinst/openQA/pull/2676#issuecomment-578792752 for the current state.**
---
Related issue: https://progress.opensuse.org/issues/34783
This is WIP as it turns out to be not so easy as expected:
* The required assets need to be parsed from the settings again because the assets of the job might have already been deleted from the database.
* "Hidden" assets such as repositories need to be ignored.
* So far the error is thrown in the duplicate function which means that this change would prevent any job duplication unless the assets are present.
Note that this is only about restarting assets to prevent the creation of a clone in the first place.

Show warning when restarting job and assets are missing

---

lib/OpenQA/Constants.pm
lib/OpenQA/Scheduler/Model/Jobs.pm
lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/Schema/Result/Workers.pm
lib/OpenQA/WebSockets.pm
lib/OpenQA/WebSockets/Controller/Worker.pm
lib/OpenQA/Worker/CommandHandler.pm
lib/OpenQA/Worker/WebUIConnection.pm
t/05-scheduler-full.t
t/24-worker-webui-connection.t
t/27-websockets.t
t/38-workers-table.t
t/lib/OpenQA/Test/Utils.pm

This change is again a little bit bigger for "just" fixing a race condition. However, it involves changing the protocol a little bit (see commit messages for a description of the actual changes).
But now there should be tests for all relevant communication bits between the worker and the web UI so this likely works as expected. However, the race condition I'm trying to fix here might have become even worse by previously [fixing another race condition](https://github.com/os-autoinst/openQA/commit/f3ea708082fac95684ca5f925bb356ced1c1705e). So who knows which race condition I'm now overlooking. But when this is merged at least 2 problems should be finally addressed:
1. The worker takes the job faster than the web UI fully processes the job-worker assignment. (That was …

Fix scheduler ws race condition

---

lib/OpenQA/WebAPI/Controller/Admin/Needle.pm
t/ui/21-admin-needles.t

See: https://progress.opensuse.org/issues/53762

Dereference symlink when displaying needle info

---

lib/OpenQA/Constants.pm
lib/OpenQA/Scheduler/Model/Jobs.pm
lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/Schema/Result/Workers.pm
lib/OpenQA/WebSockets.pm
lib/OpenQA/WebSockets/Controller/Worker.pm
lib/OpenQA/Worker/CommandHandler.pm
lib/OpenQA/Worker/WebUIConnection.pm
t/05-scheduler-full.t
t/24-worker-webui-connection.t
t/27-websockets.t
t/38-workers-table.t
t/lib/OpenQA/Test/Utils.pm

This reverts commit 369ae3176c43a05ceb291d2db6b31e47c097435d, reversing
changes made to 73b75d1a43aad92debefae87364d7ed91c9a7ca3 due to many
worker instances being stuck in "assigned" state as reported on
https://progress.opensuse.org/issues/62984#note-27 and following.

Revert "Merge pull request #2750 from Martchus/fix-scheduler-ws-race-condition"

---

assets/stylesheets/admin-pages.scss

* The z-index of those menus is 1000 so the z-index of the the icons must be lower
* See https://progress.opensuse.org/issues/63856

Prevent search popover icons from appearing on top of menus

---

assets/stylesheets/forms.scss
templates/webapi/admin/job_template/index.html.ep

Currently it's aligned to the right, so all YAML examples start at different columns.
I find it more readable at the left.

Align jobtemplate inline help to left

---

lib/OpenQA/WebAPI/Controller/API/V1/JobGroup.pm
script/load_templates
t/40-script_load_templates.t

The new code uses `form =>` syntax to post without making use of the query and also `is_success` to bail out.
Fixes: [poo#60118](https://progress.opensuse.org/issues/60118)

load_templates: Create groups that do not exist

---

t/test_postgresql

- The `$USER` variable may not be set in a container and thus lead to an  argument error  - `id -u -n` is posix compliant.
- Redirecting the log is problematic if the user can't write the log  file and in turn produces a permission error even in case of success.
- Use overridable $LOGFILE defaulting to shared memory.

Alleviate debugging of test_postgresql

---

lib/OpenQA/Worker/Job.pm
t/05-scheduler-full.t

Just a few unrelated changed I've come up with when writing the [scalability test](https://github.com/os-autoinst/openQA/pull/2777); see particular commit messages.

Polish scheduler fullstack test and worker log

---

script/load_templates

This is a follow-up to #2770. Re-using the URL can lead to problems which are difficult to diagnose. Instead we should always use the form style which works for get, put and post.

load_templates: Remove query uses from table requests

---

systemd/openqa-livehandler.service
systemd/openqa-scheduler.service
systemd/openqa-websockets.service
systemd/openqa-webui.service

On a system where the network setup is not instantanious, e.g. NetworkManager+DHCP, when openQA systemd services are enabled to automatically startup, they can fail like
```
openqa-scheduler[1282]: Can't create listen socket: Address family for hostname not supported at /usr/lib/perl5/vendor_perl/5.26.1/Mojo/IOLoop.pm line 124.
openqa-websockets[1283]: Can't create listen socket: Address family for hostname not supported at /usr/lib/perl5/vendor_perl/5.26.1/Mojo/IOLoop.pm line 124.
openqa-livehandler[1248]: Can't create listen socket: Address family for hostname not supported at /usr/lib/perl5/vendor_perl/5.26.1/Mojo/IOLoop.pm line 124.
openqa[1284]: Can't create listen socket: Address family for hostname not supported at /usr/lib/perl5/vendor_perl/5.26.1/Mojo/IOLoop.pm line 124.
``` …

systemd: Fix premature startup of services when network is not fully up yet

---

systemd/openqa-worker-cacheservice.service
systemd/openqa-worker@.service

Following a066ce630 for the webUI related services we can use the same
dependencies for worker and cacheservice to be more correct and
potentially save some seconds of service startup time while still
ensuring all required dependencies are fulfilled.
Related progress issue: https://progress.opensuse.org/issues/62567

systemd: Make worker also only depend necessary network related targets

---

docs/Contributing.asciidoc
openQA.spec
script/openqa-bootstrap
script/setup-db
systemd/openqa-setup-db.service

This reduces the duplication among bootstrap script and systemd service
and can help in other environments, e.g. without systemd.

Extract a script "openqa-setup-db" for local database setup

---

openQA.spec

Problem introduced with 833d31513 by incorrectly grouping with python
scripts.

Fix 'openqa-setup-db' on SLE12 builds

---

.circleci/config.yml
Makefile

Currently 't' is taking longer than 30m whereas all other test
collections take 20m or less. Having 'checkstyle' a separate test
collection should reduce overall runtime with the additional benefit of
identifying style issues earlier without needing to wait for other
tests.
This reduces the overall runtime from about 1h 4m to 48m, e.g. compare
a workflow before:
https://app.circleci.com/github/os-autoinst/openQA/pipelines/6f7ddd8c-30fc-4afc-8255-6e048434d328/workflows/8893b002-0ec9-45be-a3c6-fb4bb64c1ee1
with the new workflow:
https://app.circleci.com/github/os-autoinst/openQA/pipelines/c0c3f8d9-1cd9-43a4-9d00-a222ad1db1a7/workflows/9bc277da-296a-4396-a352-bef188d01d1d

Split 'checkstyle' tests within circle CI to reduce overall runtime

---

script/openqa-bootstrap

Ticket: https://progress.opensuse.org/issues/57014

Bootstrap: Install required dep qemu-tools

---

script/openqa-clone-custom-git-refspec
t/40-script_openqa-clone-custom-git-refspec.t

Related progress issue: https://progress.opensuse.org/issues/62600

openqa-clone-custom-git-refspec: Add option to pass clone-job arguments

---

script/retry

When the command within "run_once" fails we must not only break the loop
but also preserve the exit code. This was observed when trying out
STABILITY_TEST in more cases which is not affecting our current circle
CI based tests as they do not use STABILITY_TEST anywhere in the current
state.

Fix script/retry for STABILITY_TEST preventing false-negatives

---

script/retry
t/lib/OpenQA/SeleniumTest.pm
t/ui/15-admin-workers.t
t/ui/16-tests_job_next_previous.t
t/ui/19-tests-links.t

To not rely on a global Selenium timeout in test functions we should use
our explicit wait functions where they are needed.

t: Use explicit wait functions where needed

---

t/24-worker-jobs.t

This helps to provide consistent, reproducible coverage for code that
seems to have been covered only by the full stack test but not
reproducible causing flaky coverage reports, e.g. by circleci+codecov.

t: Add explicit coverage for "_read_result_file" to fix flaky reports

---

Makefile
lib/OpenQA/Constants.pm
lib/OpenQA/Schema/Result/Workers.pm
lib/OpenQA/WebAPI.pm
lib/OpenQA/WebSockets/Controller/Worker.pm
lib/OpenQA/Worker.pm
lib/OpenQA/Worker/CommandHandler.pm
lib/OpenQA/Worker/Job.pm
lib/OpenQA/Worker/WebUIConnection.pm
t/05-scheduler-full.t
t/24-worker-overall.t
t/24-worker-webui-connection.t
t/27-websockets.t
t/38-workers-table.t
t/43-scheduling-and-worker-scalability.t
t/dummy-isotovideo.sh
t/lib/OpenQA/Test/Utils.pm

For details about the race condition and the fix itself, see the commit message of "Prevent race condition when assigning and sending jobs to a worker".
Change regarding the [first attempt](https://github.com/os-autoinst/openQA/pull/2750): This time the re-scheduling when the worker reports a status update is not completely taken out. It is only omitted on the first status update. That should be sufficient to fix the race condition without risking jobs being stuck in the assigned state. The worst case is that a job is twice as long in the assigned state as it was possible before. However, in the good case jobs are now hopefully even less long assigned because I've kept the "rejection" message from the first attempt.
This also introduces a "scalability test" which allows to reproduce the …

Fix race condition when on job assignment

---

lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
lib/OpenQA/WebAPI/Plugin/Helpers.pm
lib/OpenQA/WebAPI/Plugin/YAMLRenderer.pm
t/13-joblocks.t
t/40-script_load_templates.t
t/api/08-jobtemplates.t

- Schema filename validation should be done in the controller, for that reason the tests are also updated.
- ~With debugging enabled, unknown parameters result in an error.~
- `$validation->param` is used, except params which are part of the path get validated through typed routes.
- The `validation_error` helper now speaks JSON, too, and distinguishes between invalid and missing parameters.
This came up in the context of #2270 where the re-use of the URL object caused unrelated parameters to be merged until it corrupted the response. Disallowing unknown parameters would've caught this.
See [poo#64075](https://progress.opensuse.org/issues/64075)

Consistent validation in JobTemplate update route

---

lib/OpenQA/Worker/Job.pm

I consider a "which" call for every "system" to be wasteful as we ignore
the fact if optipng is not found anyway. So just ignore any problem
encountered with the system call instead.
The additional difference would be that the debug log message would be
printed regardless in before.

Optimize _optimize_image

---

lib/OpenQA/Scheduler/Model/Jobs.pm
lib/OpenQA/WebAPI/Controller/API/V1/Worker.pm
t/05-scheduler-full.t
t/20-stale-job-detection.t

With this change we have the relevant worker name directly available when investigating incomplete jobs without having to do more complicated queries.

Add worker name to reason when stale job detection incompletes job

---

etc/openqa/openqa.ini
lib/OpenQA/Setup.pm
lib/OpenQA/Task/Job/Limit.pm
t/42-screenshots.t
t/config.t

On different production instances the runtime of the splitted cleanup tasks differs a lot so it makes sense to make the parameters for splitting configurable.
---
See https://progress.opensuse.org/issues/55922#note-18

Make parameters for splitting screenshot cleanup configurable

---

t/api/08-jobtemplates.t
t/data/08-create-modify-group.yaml
t/data/08-merge-expanded.yaml
t/data/08-merge.yaml
t/data/08-opensuse-2.yaml
t/data/08-opensuse-test.yaml
t/data/08-opensuse.yaml
t/data/08-refs-vars.yaml
t/data/08-refs.yaml
t/data/08-testsuite-multiple-keys.yaml
t/data/08-testsuite-null.yaml

- YAML snippets should be kept in separate files.
- Early explain and returns can be one-liners
This is a follow-up to #2781.

Split YAML out of JobTemplate API tests

---

t/api/08-jobtemplates.t

The behaviour of JSON::Validator changed (presumably in 3.24), and it
reports the first of the anyOf rule now.
Issue: https://progress.opensuse.org/issues/64454
Tested with JSON::Validator 3.17 and 3.24

Job templates test: update check for error message

---

script/dump_templates
script/load_templates
t/40-script_load_templates.t

- `get` apparently modifies the URL even with `form` so we need to clone the URL before using it.
- We should always sort the keys from the YAML.
- A new test checks that a re-import has the expected contents.
Fixes: [poo#64361](https://progress.opensuse.org/issues/64361)

Fix ARRAY in loaded job template settings

---

t/40-script_openqa-clone-custom-git-refspec.t

As observed on circle CI master.

Fix t/40-script_openqa-clone-custom-git-refspec.t failing when github auth token defined

---

lib/OpenQA/WebAPI/Plugin/ObsRsync.pm

I'm getting this:
```
lib/OpenQA/WebAPI/Plugin/ObsRsync.pm: Loop iterator is not lexical at line 388, column 5.  See page 108 of PBP.  (Severity: 4)
```
with Perl::Critic 1.136

Fix perlcritic issue

---

lib/OpenQA/Schema/Result/JobGroups.pm
lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
lib/OpenQA/WebAPI/Plugin/YAMLRenderer.pm
lib/OpenQA/YAML.pm
script/dump_templates
script/openqa-validate-yaml
t/16-utils-job-templates.t
t/api/08-jobtemplates.t

Whilst the code originated in the JobTemplates controller there is not a single reference to job templates. The module provides YAML support.

Rename the JobTemplates module to YAML

---

lib/OpenQA/Schema/Result/JobModules.pm
lib/OpenQA/Schema/Result/Jobs.pm
t/10-jobs.t
t/fixtures/01-jobs.pl
t/fixtures/05-job_modules.pl

For https://progress.opensuse.org/issues/64298. Let's see what tests this breaks (hopefully none).

Prevent flooding PostgreSQL logs with errors when inserting job modules

---

lib/OpenQA/Scheduler/Model/Jobs.pm
lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/Schema/Result/Workers.pm
lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
lib/OpenQA/WebSockets/Controller/Worker.pm
t/25-bugs.t

* Remove uncovered code which was obsolete anyways
* Mark code as uncoverable which we will hardly ever cover

Improve test coverage; remove support for old workers relying on redirection for ws route

---

docs/Contributing.asciidoc

Following the steps as described will in practice results in several
error messages like these ones:
...
pg_restore: error: could not execute query: ERROR:  role "geekotest" does not exist
...
pg_restore: error: could not execute query: ERROR:  role "telegraf" does not exist

docs: Clarify users and expected errors during an import

---

Makefile
docs/Contributing.asciidoc

Up to now one could use:
```
make test CHECKSTYLE=0 PROVE_ARGS=t/42-my-test.t
```
to run just a single test. Of course one can just use
```
make test-with-database PROVE_ARGS=t/42-my-test.t
```
instead but it's not less typing :)
This commit adds a new test variable TESTS with which we can now do
```
make test TESTS=t/42-my-test.t
```
which internally switches off CHECKSTYLE by default.
Test runs:
* We can select individual test modules with TESTS
```
$ make -n test TESTS=t/config.t
test -d /dev/shm/tpg && (pg_ctl -D /dev/shm/tpg -s status >&/dev/null || pg_ctl -D /dev/shm/tpg -s start) || ./t/test_postgresql /dev/shm/tpg
PERL5OPT=" -I/home/okurz/local/os-autoinst/openQA/t/lib -MOpenQA::Test::PatchDeparse" make test-unit-and-integration …
```

Makefile: Add convenience variable "TESTS" for easier selection

---

lib/OpenQA/WebSockets/Controller/Worker.pm
t/27-websockets.t

This is an amendment for the original fix 74f41436. The original fix was not sufficient because it did not take into account that workers might be actually idling for a while. These status updates should not already count as first chance for the worker to process a job assignment.

Prevent race condition when assigning and sending jobs to a worker

---

lib/OpenQA/Schema/Result/Jobs.pm

A small fix I made when working on https://github.com/os-autoinst/openQA/pull/2832. It is based on that PR.

Prevent possible DBIx warnings when updating job modules

---

t/43-scheduling-and-worker-scalability.t

The scalability test sometimes fails in the CI and it looks like spawning the workers is simply slower than expected. Maybe the CI servers are sometimes just very busy. To make the test more stable this change reduces the number of workers and increases the timeout.

Avoid scalability test failures in the CI

---

lib/OpenQA/Downloader.pm
t/25-downloader.t
t/lib/OpenQA/Test/Utils.pm

This regressed in #2736. When we want to download a compressed
file and extract it to produce the 'final' asset, we'll be doing
something like downloading 'http://example.com/file.img.gz' to
an asset called 'file.img'. After we download the asset, we write
it to a temporary file and feed that temporary file into
Archive::Extract, then extract it to the final asset location.
Archive::Extract uses the filename of the input file to determine
its type, so we should base the name of the temporary file on the
path component of the URL (where the compression is indicated) -
'file.img.gz' in this case - and not on the final target filename
(where the compression is not indicated) - 'file.img' in this
case. Before #2736, that's what the code did, but in #2736 it was
changed so the temporary …

Fix extracting compressed downloaded files

---

lib/OpenQA/WebAPI/Controller/Admin/Needle.pm
t/lib/OpenQA/SeleniumTest.pm
t/ui/21-admin-needles.t

* Simplify update of seen/match in OpenQA::WebAPI::Controller::Admin::Needle
* Simplify 'prepare_data_function' as followup to #2793
* t: Bail out early on Selenium reported errors for concise log
* t: Ensure necessary test dirs exist for ui/21-admin-needles.t

Simplify OpenQA::WebAPI::Controller::Admin::Needle and enhance tests

---

assets/javascripts/job_templates.js
lib/OpenQA/UserAgent.pm
lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
script/client
script/dump_templates
t/api/08-jobtemplates.t

This commit changes the response of the `job_templates_scheduling` endpoint,
if `Accept: application/json` was requested explicitly, it will return the
job template YAML encoded in a JSON string.
With an unspecific request header (or explicitly text/yaml) it will return
YAML as before.
OpenQA::UserAgent allows overriding the Accept header now.
The command line client can deal with different combinations of response type
and output options.
Issue: https://progress.opensuse.org/issues/64496
I did not add tests for the new `script/client` options. Any hints on how to test that appreciated.

Return JSON for all API routes

---

lib/OpenQA/Worker/Engines/isotovideo.pm

In the case of a job incompleting with "died" most likely a problem
within the backend triggered the premature termination.
Results (up to that point) and logs are usually available. These can
provide further information. As it is not feasible to provide only the
"relevant lines" from the log easily an easy thing we can do is provide
a pointer for test reviewers in the reason itself pointing to the
details from log files which are either available in the attached logs
of a job or already directly output in the "details" tab of the web view
when there are no module results at all.
Related progress issue: https://progress.opensuse.org/issues/63718

Add pointer to log details for incomplete jobs with reason "died"

---

lib/OpenQA/Worker/Job.pm
t/24-worker-jobs.t

I've marked it as "not-ready" because we need to adjust our monitoring queries before merging.

Extend reason quit

---

Makefile
openQA.spec
script/openqa-bootstrap
t/dummy-isotovideo.sh

As shown in https://github.com/os-autoinst/openQA/pull/2831
more recent versions of perlcritic can find different issues and the
same can happen for other style checks.
This commit enables all the common style checks additionally.
Some tests are still excluded as in before, e.g. t/00-tidy.t

openQA.spec: Run style checks in %check to detect issues in other products

---

openQA-client-test.spec
openQA.spec
script/client
script/openqa-clone-job
t/40-openqa-clone-job.t

So we can test if the client package has all dependencies
* Add openQA-client-test.spec
* Add JSON::Validator, YAML::PP, YAML::XS to client_requires
* Fix `script/client` to exit with 0 when called with `--help`
Currently testing in https://build.opensuse.org/package/show/home:tinita:branches:devel:openQA/openQA

Test client in OBS

---

lib/OpenQA/Worker/Engines/isotovideo.pm
t/24-worker-engine.t

Extract all cacheable assets from job settings. Also cache generic assets defined using `ASSET_*` settings and ignore external assets (`*_URL`) which are handled elsewhere.
This will also help resolve issues with LTP runfile assets on O3 where one of the workers is losing the NFS mount for shared asset directory.

Rewrite asset list generation for cache service

---

lib/OpenQA/WebAPI/Plugin/ObsRsync/Controller/Gru.pm
t/01-compile-check-all.t
t/api/14-plugin_obs_rsync.t

Parameter repository was ignored in Sync request if folder with default repository exists for the same project in ObsRsync Plugin

Fix triggering ObsSync using repository

---

lib/OpenQA/JobSettings.pm
lib/OpenQA/Schema/Result/ScheduledProducts.pm
lib/OpenQA/Script.pm
lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
t/35-script_clone_job.t
t/40-job_settings.t
t/api/04-jobs.t

In the current code, the settings start with `+` will be added to the job when creating a job using `jobs post` as `{+key => value}`. 
Handle this by following the rule that defined in `schedule_iso`
When we cloning a job, the settings that removed by clone script are added into the job's settings again if the settings are defined in TestSuite or Product or Machine. Because the create job function re-generate the settings.
See: https://progress.opensuse.org/issues/63883
https://progress.opensuse.org/issues/63565

Improve the operation of 'jobs post'

---

lib/OpenQA/Worker/Engines/isotovideo.pm
t/24-worker-engine.t

Reverts os-autoinst/openQA#2860 due to
https://progress.opensuse.org/issues/64866
breaking jobs using dynamic asset downloading.

Revert "Rewrite asset list generation for cache service"

---

lib/OpenQA/ExpandPlaceholder.pm
lib/OpenQA/Schema/Result/ScheduledProducts.pm
lib/OpenQA/Script.pm
lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
t/35-script_clone_job.t
t/40-expand_placeholders.t
t/api/04-jobs.t

Reverts os-autoinst/openQA#2861 due to https://progress.opensuse.org/issues/64938

Revert "Improve the operation of 'jobs post'"

---

lib/OpenQA/Worker/Engines/isotovideo.pm

See: https://progress.opensuse.org/issues/64938

Skip detecting asset key when asset value is null

---

lib/OpenQA/WebAPI/Controller/API/V1/JobGroup.pm
t/api/10-jobgroups.t

See also #2781 for validation in JobTemplate.
See: [poo#64075](https://progress.opensuse.org/issues/64075)

Validate parameters passed to job group API routes

---

lib/OpenQA/CacheService/Task/Sync.pm
lib/OpenQA/Worker/Engines/isotovideo.pm
t/25-cache-service.t

Very simple patch, for something that should happen very very rarely.
While the happy path of the sync job always results in an exit code for
the job result, a catastrophic failure in the job will store the
exception as a string. So make sure isotovideo.pm can handle both cases
gracefully.
Progress: https://progress.opensuse.org/issues/64743

The job result is a string and not a number

---

assets/javascripts/openqa.js
assets/javascripts/overview.js
assets/javascripts/tests.js
lib/OpenQA/Resource/Jobs.pm
lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
t/05-scheduler-restart-and-duplicate.t
t/15-assets.t
t/api/04-jobs.t
t/ui/26-jobs_restart.t

* Allow forcing the restart via API
* Suggest restarting parent job if there is one
* See https://progress.opensuse.org/issues/34783
---

Turn warning about missing assets when restarting jobs into error

---

openQA.spec
script/openqa-enqueue-asset-cleanup
script/openqa-enqueue-audit-event-cleanup
script/openqa-enqueue-bug-cleanup
script/openqa-enqueue-result-cleanup
systemd/openqa-enqueue-asset-cleanup.service
systemd/openqa-enqueue-audit-event-cleanup.service
systemd/openqa-enqueue-bug-cleanup.service
systemd/openqa-enqueue-result-cleanup.service

systemd startup scripts should not have too much business logic and not
duplicate what a startup in other environments e.g. containers would
need as well. This can simplify containerization of services at least
regarding the job enqueue services we have.

Provide enqueue convenience scripts rather than systemd

---

lib/OpenQA/Worker/WebUIConnection.pm
t/24-worker-webui-connection.t

Retry connection attempts to web UI for multiple minutes to ensure we
can continue jobs when for example the web UI host reboots.
Related progress issue: https://progress.opensuse.org/issues/57620

Cover web UI being down multiple minutes in worker connection retries

---

lib/OpenQA/Schema/Result/Needles.pm
lib/OpenQA/WebAPI/Controller/File.pm
lib/OpenQA/WebAPI/Controller/Step.pm
t/ui/12-needle-edit.t

- Distinguish parsing errors from "Not found"
- Failure to parse the JSON was not covered
- The found log should appear only when it was found
- Use refresh API in webdriver

Cover broken needle code path in a unit test

---

t/40-openqa-clone-job.t
t/40-script_load_templates.t
t/40-script_openqa-clone-custom-git-refspec.t

* The script directory does not contain any Perl modules so it is not useful to add it to the search path
* Add the lib directory to the search path where it was missing so one does not have to care about passing `-Ilib` manually.

Improve Perl module search paths of some tests

---

lib/OpenQA/Schema/Result/Jobs.pm
t/api/02-iso-download.t
t/api/02-iso.t

Our CI tests show that t/api/02-iso.t has a runtime for about 170s with
one section in output showing when code takes exceptionally long:
```
debug] [#1] Downloading "http://localhost/nonexistent.iso" to "t/data/openqa/share/factory/iso/nonexistent.iso"
[info] [#1] Downloading "nonexistent.iso" from "http://localhost/nonexistent.iso"
[info] [#1] Download of "t/data/openqa/share/factory/iso/nonexistent.iso" failed: 521 Connection refused
[info] [#1] Download error 521, waiting 5 seconds for next try (4 remaining)
...
[info] [#1] Download of "t/data/openqa/share/factory/iso/nonexistent.iso" failed: 521 Connection refused
[error] [#1] Downloading "http://localhost/nonexistent.iso" failed because of too many download errors
[error] Gru job error: Downloading "http://localhost/nonexistent.iso" …
```

t: Fix overly long runtime in api/02-iso.t

---

lib/OpenQA/WebAPI/Controller/Step.pm

Related progress issue: https://progress.opensuse.org/issues/65283

Fix missing method import "find_bug_number"

---

t/43-scheduling-and-worker-scalability.t

The test 43-scheduling-and-worker-scalability.t calls the internal
output helper function "job_info" only on failure but so far uses "note"
which only logs in verbose mode or into the external harness log files.
In case of failure we can benefit from a more verbose output in both CI
as well as local runs directly next to the test results.
```
t/43-scheduling-and-worker-scalability.t .. 1/?
```

t: Provide info in 43-scheduling-and-worker-scalability.t also in non-verbose

---

t/ui/12-needle-edit.t

The tests cover creating and editing needles, but new and old property formats are not covered.
The "string" case specifically fails without the import fix because that hits the compatibility code path.
Follow-up for #2906
See: [poo#65283](https://progress.opensuse.org/issues/65283)

Add unit test scenarios for different needle property types

---

docs/Contributing.asciidoc
lib/OpenQA/LiveHandler.pm
lib/OpenQA/Log.pm
lib/OpenQA/Scheduler.pm
lib/OpenQA/Setup.pm
lib/OpenQA/WebAPI.pm
lib/OpenQA/WebSockets.pm
lib/OpenQA/Worker/Settings.pm
t/24-worker-settings.t
t/25-serverstartup.t
t/28-logging.t

This is the additional step to stop requiring Setup to use logs.
Fixes: https://progress.opensuse.org/issues/27868

Move log setup into log module

---

t/14-grutasks.t

* Previously the test didn't really work, e.g. when breaking the condition
in OpenQA::Schema::ResultSet::Assets::status the test still passed
* Now the test checks whether the asset is deleted if when the job is
not pending anymore to see whether the pending state actually makes a
difference (and the test setup is correct)
* See https://progress.opensuse.org/issues/64544 (it does not fix that
issue but problems with the test became apparent when investigating
it)

Improve test for preserving pending assets

---

lib/OpenQA/Schema/ResultSet/Assets.pm

Checking for the result is slightly wrong, e.g. a job can be in state cancelled with no result and should not be considered pending anymore.

asset cleanup: Consider all jobs which are not done or cancelled as pending

---

lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
t/api/04-jobs.t

This limits the length of the reason as mentioned in https://progress.opensuse.org/issues/25814#note-15. It felt a bit weird to limit the reason but allow the result to be of any length. So I also added a commit to validate the result.

Validate result and cut reason after 300 characters

---

script/tidy

If "tidy" fails in "--check" mode on untidied files the .tdy files were
left in place. These files are then also picked up by
t/01-compile-check-all.t which subsequently fails and confused reviewers
of the failed test runs.
This commit changes tidy to conduct a full cleanup of all .tdy files
when exiting also on abnormal aborts.

script: Ensure no left over .tdy files on aborted/failed tidy

---

docs/Contributing.asciidoc
script/openqa-clone-custom-git-refspec
t/40-script_openqa-clone-custom-git-refspec.t

Previous parsing was broken when branch contained slash.

openqa-clone-custom-git-refspec: Allow '/' in branch name

---

t/04-scheduler.t
t/05-scheduler-cancel.t
t/05-scheduler-dependencies.t
t/05-scheduler-full.t
t/11-commands.t
t/14-grutasks.t
t/15-assets.t
t/16-utils-runcmd.t
t/20-stale-job-detection.t
t/23-amqp.t
t/24-worker-jobs.t
t/24-worker-overall.t
t/24-worker-webui-connection.t
t/25-cache-service.t
t/28-logging.t
t/34-developer_mode-unit.t
t/37-limit_assets.t
t/39-scheduled_products-table.t
t/43-scheduling-and-worker-scalability.t
t/api/03-auth.t
t/api/08-jobtemplates.t
t/lib/OpenQA/Test/Utils.pm
t/ui/25-developer_mode.t

Redefine fails early if a sub is not found in the mocked module.
ag -l -- '->mock' | xargs sed -i 's@->mock@->redefine@'

Replace all uses of mock with redefine

---

lib/OpenQA/JobSettings.pm
lib/OpenQA/Schema/Result/ScheduledProducts.pm
lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
t/api/04-jobs.t

Both in the operation `isos post` and `jobs post`, there are some code used to generate job settings, this pr used to reduce the duplicated code.

Extract duplicated code from generating job settings

---

lib/OpenQA/Schema/Result/Jobs.pm
t/10-jobs.t

I went over the complete file and applied the following changes among
others:
* Use post-condition where feasible to save lines
* Use map rather for-loops with push
* Extract methods for common code
* Use early returns rather than big indented if-blocks
I am open to feedback for all the little details and can easily split my commits or PRs as required.

Simplify Schema::Results::Jobs

---

t/ui/01-list.t

After following /tests, before trying to access jobs that are only shown
asynchronously we need to wait for all ajax actions to be completed.
This fixes instabilities encountered in recent tests as well as
potentially already sporadically in the past.

t: Fix instabilities in ui/01-list.t on accessing /tests

---

t/ui/13-admin.t
t/ui/14-dashboard-parents.t
t/ui/16-tests_job_next_previous.t
tools/retry

* t: Stabilize ui tests waiting for ajax
* t: Stabilize ui/14-dashboard-parents.t waiting for build results
* t: Use descriptive string in wait_for_ajax rather than comment
* Add output of each try in tools/retry

Further stabilize UI tests, part of #2626

---

t/ui/10-tests_overview.t

This fixes "Failed test 'description popover shows content' at
t/ui/10-tests_overview.t line 168." that we see often recently. Probably
reading the description is a tad slower but the test was not taking the
popup time into account anyway so this should be fixed.

t: Stabilize ui/10-tests_overview.t

---

lib/OpenQA/WebAPI/Controller/Running.pm

Seen in test output 't/ui/25-developer_mode.t ................... 1/? Mojo::Reactor::EV: I/O watcher failed: Undefined subroutine &OpenQA::WebAPI::Controller::Running::log_error called at /home/okurz/local/os-autoinst/openQA/lib/OpenQA/WebAPI/Controller/Running.pm line 235.'

Fix missing import 'log_error' in WebAPI::Controller::Running

---

lib/OpenQA/WebAPI/Controller/API/V1/Worker.pm
t/api/01-workers.t

Note: Dropping the extra log message. Validation errors are fatal.
See:[poo#64075]( https://progress.opensuse.org/issues/64075)

Validate parameters passed to Worker API routes

---

script/load_templates
t/01-compile-check-all.t
t/40-script_load_templates.t
t/data/40-templates-more.pl

1400d8a8dd inverted the logic here - instead of exiting the loop
on a *failure* we now exit it on *success*. So each time --clean
is run it will only wipe one entry per table. This obviously
breaks things badly (the clean phase doesn't clean things right
at all, so the subsequent load phase fails because we try to add
entries that already exist, and you wind up with a mess).
This flips the logic back, and adds a test.

Fix load_templates --clean to wipe more than one entry per table

---

.circleci/config.yml
codecov.yml
script/load_templates
script/modify_needle
t/40-script_load_templates.t
t/44-scripts.t

I excluded the following scripts:
* `check_dependencies`, `openqa-workercache` All our other scripts use `pod2usage` for `--help` but those script have no pod yet.
* `openqa`, `openqa-livehandler` these scripts are failing in CI (https://app.circleci.com/pipelines/github/os-autoinst/openQA/2406/workflows/6a8c5689-a0aa-40e1-a8c9-f2107b493c35/jobs/22618):
```
[13:01:59] t/44-scripts.t ................................. 7/? m
[13:01:59] t/44-scripts.t ................................. 9/? 
```

Add script directory to coverage; test all scripts with --help

---

lib/OpenQA/Schema/Result/Jobs.pm
t/37-limit_assets.t

Considering https://progress.opensuse.org/issues/65627 it seems that directly chained parents need to be taken into account similarly to regularly chained parents when registering assets.
This change implements that and adds and explicit test for both cases.

Consider directly chained dependencies when registering assets

---

t/ui/14-dashboard-parents.t
t/ui/14-dashboard.t

Avoid instantiating `Test::Mojo->new('OpenQA::WebAPI')` in these tests. This also avoids initializing the database twice in `t/ui/14-dashboard.t`.

Speed up dashboard tests

---

t/ui/02-list-group.t

The previous fix to wait for an element should be applied before
counting the displayed entries, not only looking for an individual entry
afterwards.
Also simplifying the test module according to common style.
Related progress issue: https://progress.opensuse.org/issues/59043

t: Stabilize and simplify ui/02-list-group.t (again)

---

lib/OpenQA/Worker/Engines/isotovideo.pm
t/24-worker-jobs.t

See: https://progress.opensuse.org/issues/65840

Return error when error happens in caching assets

---

t/33-developer_mode.t
t/full-stack.t
t/lib/OpenQA/Test/FullstackUtils.pm

* Improve test stack reporting by avoiding Test::More tests in helper libs
* t: Extract common full stack function "schedule_one_job_over_api_and_verify"
* t: Add timeout for loops in full-stack.t
* t: Speedup full stack test with KVM when available

Enhance full-stack test

---

assets/javascripts/openqa.js
assets/javascripts/overview.js
assets/javascripts/tests.js
lib/OpenQA/Resource/Jobs.pm
lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
t/api/04-jobs.t
t/ui/26-jobs_restart.t

Even when https://github.com/os-autoinst/openQA/pull/2676#issuecomment-615926604 is sorted out it makes sense to be able to force a job restart conveniently via the web UI (and not only via the API).

Allow to force restarting jobs

---

t/lib/OpenQA/Test/Utils.pm

Noticed a small race condition in the asset tests while investigating the test failures from yesterday. An inactivity timeout of just 1 second has a decent chance of closing the connection a bit too early if tests run slow enough.

Remove a small race condition in asset tests

---

lib/OpenQA/JobSettings.pm
lib/OpenQA/Schema/Result/ScheduledProducts.pm
lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
t/api/02-iso.t
t/api/04-jobs.t

Related: https://progress.opensuse.org/issues/63883#note-8

Rework extracting duplicated code from generating job settings

---

lib/OpenQA/Script.pm
script/openqa-clone-custom-git-refspec

Related progress issue: https://progress.opensuse.org/issues/66013

Fix warning about undefined empty arg on clone

---

lib/OpenQA/Schema/Result/Jobs.pm
t/15-assets.t

Inspired by register_assets_from_settings, check using _asset_find()
instead of database query. What does matter here is not really looking
for the actual file, but that _asset_find() also consider private assets
named after parent job id.
For this purpose, query also parent(s) job ids in missing_assets().
Related to #2676
---
A draft PR for now - tests are not updated (and TBH not sure how to do that when now it looks for files, not db entries). Any hints?

Improve the check for missing assets

---

t/lib/OpenQA/Test/Case.pm

Unit tests using `find_most_recent_event` may log this message:
Can't call method "event_data" on an undefined value[...]
This happens when there is no event of that type.

Check if there is a recent event before returning it

---

lib/OpenQA/Parser/Format/JUnit.pm
t/30-test_parser.t
t/data/junit-results-output-softfail.xml
t/data/slenkins_control-junit-results-fail.xml

At the test suite level if there is counter that indicates soft failures exist and at the same time no failures exist, the overall test result should be softfail.
At the test case level if individual test case status indicates soft falure judging by leading 'softfail' string, it will be replaced by status 'softfail'. And if the overall test result had not been determined by then, it still can be decided by the status of individual test case, for example, the overall test result should be 'softfail' if it is not 'fail' and 'softfail' test case exists.
Also added new JUnit parser unit test into t/30-test_parser.t, including slenkins_control-junit-results-fail and junit-results-output-softfail to make test and coverage test. So the changed part has been tested and the coverage percentage …

JUnit log parser should support softfail overall

---

assets/javascripts/comments.js

From time to time our CI tests show a problem like the following:
```
not ok 4 - heading text
```
I managed to reproduce it locally although this was really hard.  One of two
runs of
```
STABILITY_TEST=1 RETRY=200 tools/retry prove -v -l t/ui/15-comments.t
```
could reproduce it in "Rerun 125 of 200 …" for the first time.
The problem most likely appears in javascript when we want to update the
comment header line but there is an incorrect "edited" appended as the creation
and update time might not be set to exactly the same in the database row.
To verify a fix I ran:
```
STABILITY_TEST=1 RETRY=500 tools/retry prove -l t/ui/15-comments.t
```
successfully with no failed tests.
Related progress issue: https://progress.opensuse.org/issues/53771

Fix a very sporadic issue of a wrong comment header applied

---

lib/OpenQA/Setup.pm
lib/OpenQA/WebAPI/Plugin/YAML.pm

- The plugin contains a renderer.
- And, too, the helper for validation.
- Other plugins have short base names as well.

Rename YAMLRenderer plugin to YAML

---

lib/OpenQA/Client.pm
script/client
t/31-client.t

Fixes a problem introduced with 5c9068a3d.

Fix exit code returned by client

---

t/full-stack.t

Generalize the cache log message we look for to fix local runs of
full-stack test or actually all runs depending on the log level
configured as the relevant tests are only executed if the condition
`!$ENV{MOJO_LOG_LEVEL} || $ENV{MOJO_LOG_LEVEL} =~ /DEBUG|INFO/i` is met,
which does not seem to be the case in circleCI.
The failing test is
```
not ok 33 - Test 7 Core-7.2.iso has not changed
```
As can be seen in the last line the message format is different than the
expected regex, hence generalizing it in the current commit. The commit
that introduced the change in the log message was c4fa5d28d.

Fix local runs of full-stack test failing on "Content has not changed"

---

t/ui/01-list.t

We do not really expect "animations" in this step but it might be the
data table is built not immediately after user actions to provide a more
responsive user interface.
I failed to reliably reproduce the problem so the fix is without actual
verification.
Related progress issue: https://progress.opensuse.org/issues/59043

t: Try to stabilize t/ui/01-list.t

---

lib/OpenQA/Worker/WebUIConnection.pm
t/full-stack.t

This commit adds the possibility to override the worker config setting
'RETRIES' with an optional environment variable
'OPENQA_WORKER_CONNECT_RETRIES' that the full stack test can immediately
use to significantly reduce runtime from 4m for just the *first*
internal job runs to about 2m.

Allow to overwrite 'worker connect retries' by environment variable

---

docs/GettingStarted.asciidoc
docs/UsersGuide.asciidoc
docs/WritingTests.asciidoc
lib/OpenQA/CLI.pm
lib/OpenQA/CLI/api.pm
lib/OpenQA/CLI/archive.pm
lib/OpenQA/Command.pm
openQA-client-test.spec
openQA.spec
script/openqa-cli
t/05-scheduler-full.t
t/43-cli-api.t
t/43-cli-archive.t
t/43-cli.t
t/full-stack.t
t/lib/OpenQA/Test/FullstackUtils.pm
t/lib/OpenQA/Test/Utils.pm

A first proof of concept for a new openQA client with extensions and full test coverage.
**Todo:**
**Bonus:**
**Up for discussion**
We need to decide what to do with the legacy client, we could:
- Deprecate it for a few months/years and then just remove it completely
- Try to replace it with a wrapper script around `openqa-cli`, translating arguments as best as possible (some things would break immediately though, like output formatting)
Progress: https://progress.opensuse.org/issues/10316

New openQA client

---

t/lib/OpenQA/Test/Database.pm

The original project https://github.com/tempire/MojoExample describes
that code is usable under same terms and license as Perl, which is GPL,
so we are good.

t: Use proper copyright header for OpenQA::Test::Database

---

openQA.spec
script/openqa-gru
script/openqa-livehandler-daemon
script/openqa-scheduler-daemon
script/openqa-slirpvde
script/openqa-vde_switch
script/openqa-websockets-daemon
script/openqa-webui-daemon
script/openqa-worker-cacheservice-minion
script/openqa-workercache-daemon
systemd/openqa-gru.service
systemd/openqa-livehandler.service
systemd/openqa-scheduler.service
systemd/openqa-slirpvde.service
systemd/openqa-vde_switch.service
systemd/openqa-websockets.service
systemd/openqa-webui.service
systemd/openqa-worker-cacheservice-minion.service
systemd/openqa-worker-cacheservice.service

systemd startup scripts should not have too much business logic and not
duplicate what a startup in other environments e.g. containers would
need as well. This can simplify containerization of services.

Use defaults already in startup scripts rather than systemd (alternative to #2864 with shell wrappers)

---

t/lib/OpenQA/Test/FullstackUtils.pm

Seems I made a mistake rebasing on my own commits :)

t: Fix 'QEMU_NO_KVM' incorrectly added in QEMU_NO_KVM=1

---

openQA.spec
script/openqa-gru
script/openqa-livehandler-daemon
script/openqa-scheduler-daemon
script/openqa-slirpvde
script/openqa-vde_switch
script/openqa-websockets-daemon
script/openqa-webui-daemon
script/openqa-worker-cacheservice-minion
script/openqa-workercache-daemon
systemd/openqa-gru.service
systemd/openqa-livehandler.service
systemd/openqa-scheduler.service
systemd/openqa-slirpvde.service
systemd/openqa-vde_switch.service
systemd/openqa-websockets.service
systemd/openqa-webui.service
systemd/openqa-worker-cacheservice-minion.service
systemd/openqa-worker-cacheservice.service

Completely broke all services due to a broken path in `openqa-webui.service` and missing `#!/bin/sh` in all scripts.

Revert "Use defaults already in startup scripts rather than systemd (alternative to #2864 with shell wrappers)"

---

etc/apache2/vhosts.d/openqa-common.inc

Issue: https://progress.opensuse.org/issues/63244
Problem: Apache2 proxy sets the timeout by default to 60s. But sometimes
openQA-webui need more than this time to finish parsing and rendering.
Solution: Increase the timeout in the proxy configuration file to 300s.
It indicates that it took around 103 seconds for openQA-webui
to finish parsing, rendering.
Weheras the apache2 proxy waiting timeout defaults to 60s. That was why
my browser couldn't load results page.

Increase proxy timeout

---

lib/OpenQA/JobSettings.pm
lib/OpenQA/Schema/Result/ScheduledProducts.pm
t/api/02-iso.t

`TEST` is set value after replacing the specify values `%TEST%`, so the
`TEST` in setting is not replaced.

Fix `TEST` is not replaced when using `isos post`

---

lib/OpenQA/CLI/api.pm
lib/OpenQA/Command.pm
t/43-cli-api.t

Small change to add a `--verbose` option to `openqa-cli api`. This was suggested by @perlpunk as a debug feature, and i find it quite useful.
Instead of:
```
{"error":"no api key","error_status":403}
```
You can now also use the `--verbose` option to get:
```
HTTP/1.1 403 Forbidden
Content-Type: application/json;charset=UTF-8
Strict-Transport-Security: max-age=31536000; includeSubDomains
Server: Mojolicious (Perl)
Content-Length: 41
Date: Wed, 29 Apr 2020 12:03:11 GMT
{"error":"no api key","error_status":403}
```
And the `--pretty` option still works independently on the JSON:
```
HTTP/1.1 403 Forbidden
Content-Type: application/json;charset=UTF-8
Strict-Transport-Security: max-age=31536000; includeSubDomains
Server: Mojolicious (Perl)
Content-Length: 41
Date: Wed, 29 Apr 2020 12:03:11 …
```

Add --verbose option to "openqa-cli api"

---

cpanfile
dependencies.yaml
openQA.spec

A couple of the tests use these, but they were never added to the
RPM spec dependencies.

Add Test::MockObject and Test::Exception to test dependencies

---

t/full-stack.t
t/lib/OpenQA/Test/Utils.pm

Instead of sleeping and wasting 1s five times for generating fake assets
with differing timestamps instead we can simply increment the timestamp with
which we create assets in the cache database with no sleep time at all.

t: Save 5s test execution time in full-stack.t with smarter timestamps

---

lib/OpenQA/CacheService.pm
lib/OpenQA/LiveHandler.pm
lib/OpenQA/WebAPI.pm
t/44-scripts.t

Mojo services already have an internal help options but in some cases we
could not reach it so we should treat '--help' in a special way to allow
users to reach help :)
This also removes all TODOs from t/44-scripts.t

Provide a '--help' option to all our scripts

---

t/full-stack.t

Some part of the code in t/full-stack.t was only executed if the
condition `!$ENV{MOJO_LOG_LEVEL} || $ENV{MOJO_LOG_LEVEL} =~
/DEBUG|INFO/i` is true which apparently was not the case in circleCI
causing relevant test code not never be executed in circleCI but when
executing the full stack test locally the test would fail since the test
is in need of adaption. We should not have conditional test code that is
never executed in our CI environment. In this case we should be able to
rely on the worker being correctly started so that any other configured
log level selection has no effect.

t: Ensure all test code is executed in every environment

---

Makefile

In a8537863d we enabled one test as "unstable" again but the test rule
within "test-unstable" was never passing the parsed unstable tests as
test arguments.
Tested locally with:
```
timeout 1 make test-unstable; timeout 1 make test-ui; pkill -f prove
```
```
for f in $(cat .circleci/unstable_tests.txt); do make test-with-database TIMEOUT_M=5 PROVE_ARGS="$HARNESS $f" RETRY=3 || break; done
make[1]: Entering directory '/home/okurz/local/os-autoinst/openQA'
test -d /dev/shm/tpg && (pg_ctl -D /dev/shm/tpg -s status >&/dev/null || pg_ctl -D /dev/shm/tpg -s start) || ./t/test_postgresql /dev/shm/tpg
PERL5OPT=" -I/home/okurz/local/os-autoinst/openQA/t/lib -MOpenQA::Test::PatchDeparse" make test-unit-and-integration TEST_PG="DBI:Pg:dbname=openqa_test;host=/dev/shm/tpg"
make[2]: …
```

Makefile: Fix evaluation for 'test-unstable' as followup to a8537863d

---

t/33-developer_mode.t
t/deploy.t
t/full-stack.t
t/lib/OpenQA/Test/Database.pm

* t: Correct cache test wait loop condition in full-stack.t
* t: Add wait for UI instrumentation instability in full-stack.t
* t: Phrase test message positively to prevent confusion
* Use more Mojo::File in t/full-stack.t
* t: Use existing dataset as time reference for stability
* t: Add test messages to javascript_console_has_no_warnings_or_errors in full-stack.t
* t: Fix missing leading double quote in plan skip message

Stabilize full-stack.t

---

t/33-developer_mode.t
t/deploy.t
t/full-stack.t

As a followup to 6afde4caf I figured that relying on the time of the
already existing last asset can be even more stable rather than getting
another absolute timestamp in t/full-stack.t.

t: Use existing dataset as time reference for stability

---

lib/OpenQA/Setup.pm
lib/OpenQA/WebAPI/Auth/Fake.pm
lib/OpenQA/WebAPI/Auth/OpenID.pm
lib/OpenQA/WebAPI/Controller/Session.pm

This is a followup to #3019 and finishes the transition from `->import` to `->can`. That's quite a bit more efficient and also means the auth modules no longer need to export anything.

The exporter is not needed for authentication modules

---

docs/Installing.asciidoc
openQA.spec
script/openqa-bootstrap
script/openqa-bootstrap-container

* Add convenience sub-package 'openQA-single-instance'
* docs: Mention installation of openQA-worker explicitly
* docs: Correct reference to main package as "openQA server package"
* docs: Simplify reference to minimum Leap/Fedora version

Package installation enhancements; 'openQA-single-instance' package

---

lib/OpenQA/Schema/Result/Jobs.pm
t/15-assets.t

As discussed in
https://github.com/os-autoinst/openQA/pull/2676#issuecomment-615951653
and follow-ups, this check misunderstands the "hidden" attribute.
The code assumes that "hidden" assets are the same thing as
"assets we don't really want to copy down when cloning jobs",
but they are not. The "hidden" attribute was written (by me) to
mean "asset types not to be shown for downloading in the web UI".
For SUSE, it happens to be the case that ["repo"] would be the
right array of both "not-to-be-shown-in-the-web-ui assets" and
"non-clonable assets", so this bug wasn't apparent, as SUSE
deployments leave the `hide_asset_types` config setting at its
default value of just 'repo'. But on Fedora deployments, this
setting is changed to 'repo iso hdd' (because we don't want to
show those asset …

Fix missing_assets to ignore repos, not 'hidden assets'

---

lib/OpenQA/CacheService.pm
t/25-cache-service.t

```
$ env OPENQA_CACHE_DIR=/var/lib/openqa/cache sudo -u _openqa-worker script/openqa-workercache-daemon
Cache directory unspecified. Set environment variable 'OPENQA_CACHE_DIR' or config variable 'CACHEDIRECTORY'
```

Add specific error messages for cache directory unspecified

---

t/33-developer_mode.t
t/full-stack.t
t/lib/OpenQA/Test/FullstackUtils.pm

* t: Abbreviate 'wait_for_developer_console_contains_log_message' for nicer line wraps
* t: Properly export functions from Open::Test::FullstackUtils

t: Export all functions in FullstackUtils; abbreviate helper method

---

lib/OpenQA/LiveHandler.pm
lib/OpenQA/WebAPI/Controller/LiveViewHandler.pm
lib/OpenQA/Worker/WebUIConnection.pm

While reviewing #3036 i noticed that we had workaround code for handling WebSocket redirects. While WebSocket redirects were not officially supported upstream in Mojolicious (they are an optional feature in RFC 6455), it turned out that they already worked and [just needed some tests](https://github.com/mojolicious/mojo/compare/8fc68f476968...16d8d4c7304b).
So now we can safely rely on `Mojo::UserAgent` to handle redirects for openQA. That also means there is now a limit of 3 redirects, and no risk of circular redirects anymore.

Let Mojo::UserAgent deal with WebSocket redirects

---

lib/OpenQA/JobSettings.pm
lib/OpenQA/Schema/Result/ScheduledProducts.pm
t/api/02-iso.t

PR https://github.com/os-autoinst/openQA/pull/2959 caused a regression
issue that the `DISTRI` is not converted into lowercase.
Here is the comments and example: https://github.com/os-autoinst/openQA/pull/2959/files#r420928584

Convert DISTRI into lowercase before replacing variables

---

t/full-stack.t
t/lib/OpenQA/Test/FullstackUtils.pm

Given that with https://github.com/os-autoinst/os-autoinst/pull/1390 the
os-autoinst full stack test was made way faster it can happen that the
"shutdown" module was already passed. This happened when executing the
full stack test locally at least once. With this we are most likely not
loosing functional test coverage as t/33-developer_mode.t uses the
"pause" command as well without PAUSE_AT.

t: Ensure full stack test run has not passed "shutdown" module

---

lib/OpenQA/WebAPI/Controller/Test.pm

The machine is nullable and hence might be undef wich is not taken into account. I like to remove the code completely because the debug message does not seem to be generally useful anyways.

Remove debug message leading to "Use of uninitialized value [...]" warnings

---

lib/OpenQA/WebAPI/Plugin/ObsRsync.pm

Link .run_last actually contains a full path, while the code was covering relative paths only.
The fix doesnt try anymore to check whether the destination of the link exists.

Fix get_last_test() in ObsRsync Plugin

---

lib/OpenQA/UserAgent.pm

I have to use `http_proxy` environment variable to access some of the webs in an isolated network.
But openqa-clone-job didn't understand this environment variable.
It will report the following words:
`failed to get job '1255533':  Connect timeout at /usr/share/openqa/script/../lib/OpenQA/Script/CloneJob.pm line 92.
`
Signed-off-by: James.W <jnwang@linux-alibaba.com>

Add proxy detect for OpenQA::Client

---

docker/devel:openQA:ci/base/Dockerfile

So the `mkdir` and `chown` is not needed

docker: Use useradd -m (--create-home)

---

openQA.spec
script/openqa-gru
script/openqa-livehandler-daemon
script/openqa-scheduler-daemon
script/openqa-slirpvde
script/openqa-vde_switch
script/openqa-websockets-daemon
script/openqa-webui-daemon
script/openqa-worker-cacheservice-minion
script/openqa-workercache-daemon
systemd/openqa-gru.service
systemd/openqa-livehandler.service
systemd/openqa-scheduler.service
systemd/openqa-slirpvde.service
systemd/openqa-vde_switch.service
systemd/openqa-websockets.service
systemd/openqa-webui.service
systemd/openqa-worker-cacheservice-minion.service
systemd/openqa-worker-cacheservice.service

Second try after previously reverted in 392db5dfd729e1145d55b36b751c1ec05e3a276d.
In the first try I did not specify a shebang in the simple one-line
shell scripts. Seems that this is required for systemd service targets
though. Also fixed the path in systemd/openqa-webui to point to the
"…-daemon" script instead.
Tested locally by symlinking the systemd service files from my local git
checkout into /etc/systemd/system/openqa-$service.service and calling
with
```
systemctl daemon-reload && systemctl start openqa-$service ; systemctl status openqa-$service
```

Use defaults already in startup scripts rather than systemd (2nd)

---

t/lib/OpenQA/SeleniumTest.pm

A test failure with a line reported in a helper lib and not the calling
place is not more helpful than the already existing diag line.
Instead of
```
t/full-stack.t .. 15/?     # javascript console output: [
```
no one can get:
```
t/full-stack.t .. 16/?     # javascript console output, waiting for paused: [
```

t: Change javascript_console_has_no_warnings_or_errors to only output once

---

lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
t/api/04-jobs.t

Related: https://progress.opensuse.org/issues/66268

Fix the issue `_URL` in jobs post is different from that in isos post

---

.circleci/unstable_tests.txt

See https://app.circleci.com/pipelines/github/os-autoinst/openQA/2827/workflows/13672907-1ad3-48d0-a1b2-e210991ed1f8/jobs/26708/steps :
```
[22:54:20] t/ui/27-plugin_obs_rsync_status_details.t .. 19/? [22:54:20] t/ui/27-plugin_obs_rsync_status_details.t .. 24/?
[22:54:20] t/ui/27-plugin_obs_rsync_status_details.t .. 27/? [22:54:20] t/ui/27-plugin_obs_rsync_status_details.t .. 28/? [22:54:20] t/ui/27-plugin_obs_rsync_status_details.t .. …60/? # Looks like you failed 1 test of 60.
[22:54:20] t/ui/27-plugin_obs_rsync_status_details.t .. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/60 subtests
```
t/ui/27-plugin_obs_rsync_status_details.t failed in 1/2 runs within a stability test
Related progress issue: https://progress.opensuse.org/issues/66718

Mark unstable/flaky t/ui/27-plugin_obs_rsync_status_details.t as such

---

t/33-developer_mode.t
t/full-stack.t
t/ui/13-admin.t

prove already provides color by default and Test::More::Color does not
add anything more so we can safely remove this questionable code.

Remove references to Test::More::Color not adding benefit

---

t/05-scheduler-full.t

Instead of
```
t/05-scheduler-full.t .. 3/?
Can't use an undefined value as a HASH reference at t/05-scheduler-full.t line 137.
```
get something like
```
t/05-scheduler-full.t .. 3/?
t/05-scheduler-full.t .. 5/? # Looks like you failed 1 test of 5.
t/05-scheduler-full.t .. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/5 subtests
```
including the proper test summary.

t: Prevent perl warning when 05-scheduler-full fails

---

docs/GettingStarted.asciidoc
docs/Installing.asciidoc

Previously our documentation was already correct stating the
requirements but to make it more obvious that running the openQA web UI
as well as the openQA worker instances is also perfectly possible in the
cloud we can rephrase in a positive notion and mention "cloud"
explicitly as an option as well.

docs: Describe the possibility for cloud instances explicitly

---

Makefile

Commonly a complete run of "test-t" within circleci takes 18-20 minutes
as visible on
https://app.circleci.com/pipelines/github/os-autoinst/openQA?branch=master
but sometimes we seem to hit a slow run which does not seem to be linked
to the tested changes at all as in the example
https://app.circleci.com/pipelines/github/os-autoinst/openQA/2790/workflows/e54a972e-c2dd-4e17-9a15-128130a6a702/jobs/26344/steps
where it can be seen that the setup takes longer  as well as each
individual test module takes  around double the normal time despite the
general parameters of the circleci environment still being the same
"Docker Medium, 2 CPU / 4 GB RAM".

Makefile: Bump timeout for 't' for accepted slow runs

---

lib/OpenQA/Task/Needle/Save.pm
t/ui/12-needle-edit.t

Since openQA does not support OCR, so forbidden users to create a needle
only contains ocr type area, which will cause the test case to failed.
See: https://progress.opensuse.org/issues/65579

Return error when creating a needle only contains ocr area

---

assets/javascripts/test_result.js
assets/stylesheets/result_preview.scss
lib/OpenQA/Schema/ResultSet/Needles.pm
lib/OpenQA/WebAPI/Controller/Admin/Needle.pm
lib/OpenQA/WebAPI/Controller/Step.pm
lib/OpenQA/WebAPI/Plugin/Helpers.pm
t/ui/18-tests-details.t
templates/webapi/step/viewimg.html.ep

* So one does not have to serach for the needle within the needles table
manually to find out when the needle has been seen or matched the last
time
* See https://progress.opensuse.org/issues/13740

Show candidate needle's last match/seen in the needle diff view

---

lib/OpenQA/Worker/Engines/isotovideo.pm
lib/OpenQA/Worker/Job.pm
t/24-worker-jobs.t

* Take the relevant component into account because for
https://progress.opensuse.org/issues/64884 we need to distinguish
between test crashes and backend crashes
* Ensure retrieving the extended reason does not interfere with stop
reasons from the worker itself by handling worker-specific stop reasons
first
With a change in os-autoinst to propagate the relevant component it will
look like this:
```
Reason: tests died: unable to load, check the log for the cause (e.g. syntax error)
Reason: backend died: Migrate to file failed
```

worker: Improve retrieving extended reason from os-autoinst

---

tools/update-deps

When calling with ./tools/update-deps, the './' will be part of the
filename, so use File::Spec->canonpath to remove it.

update-deps: Fix script path

---

public/schema/JobTemplates-01.yaml
t/16-utils-job-templates.t
t/data/job-templates/openqa-invalid.yaml

Issue: https://progress.opensuse.org/issues/66781
Also add a test to detect invalid top level keys

Job templates: Escape dot in regex

---

t/api/04-jobs.t

Cancelling jobs is covered in other tests, e.g. the csrf test

t: Delete obsolete/disabled code in api/04-jobs.t

---

assets/assetpack.def
assets/javascripts/render.js
assets/javascripts/test_result.js
assets/stylesheets/test-details.scss
lib/OpenQA/WebAPI/Controller/Test.pm
t/ui/18-tests-details.t
templates/webapi/test/details.html.ep
templates/webapi/test/result.html.ep

Server-side template rendering is extremely slow with large number of test modules (100+) in a job. Send module results to client as JSON and render HTML on client side using JavaScript. This makes rendering almost 30 times faster.
Currently, rendering of LTP syscalls job results (1112 modules) into HTML in OpenQA takes over 16 seconds. 3 seconds are spent reading and parsing data from storage, 13 seconds are spent rendering the HTML template. With this PR, HTML rendering takes only 700ms on my machine.
The JavaScript generates HTML functionally equivalent to the `test/module_table` template. The only significant change I did was replacing the `<img>` elements for terminal and audio boxes with CSS-defined equivalent `<span>` elements. This little change sped up rendering of syscalls jobs …

Job details rendering performance optimization

---

lib/OpenQA/Script/CloneJob.pm
script/openqa-clone-job

- Stop using global variables in moved functions.
- Pass @ARGV as $options->{args}.
Retroactive prerequisite for #3088.

Move remaining clone job functions into CloneJob module

---

lib/OpenQA/Schema/Result/Workers.pm
lib/OpenQA/WebAPI/Controller/API/V1/Worker.pm
t/43-scheduling-and-worker-scalability.t
t/api/14-plugin_obs_rsync_async.t
t/lib/OpenQA/SeleniumTest.pm
t/lib/OpenQA/Test/Utils.pm

* Delete unused import in WebAPI::Controller::API::V1::Worker
* Delete obsolete TODO in worker schema implementation
* DRY in name/to_string within worker schema implementation
* t: Provide unique process name for all forked processes
* t: Use IPC::Run for gru service in t/api/14-plugin_obs_rsync_async.t
* t: Simplify sleep, retry and loops in t/api/14-plugin_obs_rsync_async.t
* t: Output port for websocket server same as we do for webapi
* t: Ensure unavailable websocket server is seen by throwing exception
* t: Sort external imports first in 43-scheduling-and-worker-scalability.t

Various, minor enhancement

---

lib/OpenQA/Constants.pm
lib/OpenQA/Worker/Job.pm
t/24-worker-jobs.t

The video contributes significantly to the log size. This is especially the
case for long-running results so it makes sense to disable the video there
by default.
See
* https://progress.opensuse.org/issues/66922
* https://progress.opensuse.org/issues/67087#note-3

Enable NOVIDEO for jobs with increased MAX_JOB_TIME by default

---

assets/assetpack.def
assets/javascripts/parent_group_overview.js
assets/stylesheets/openqa.scss
assets/stylesheets/parent_group_overview.scss
t/17-build_tagging.t
t/ui/14-dashboard-parents.t
templates/webapi/main/build_progressbar.html.ep
templates/webapi/main/group_builds.html.ep
templates/webapi/main/group_builds_functionality_view.html.ep
templates/webapi/main/parent_group_overview.html.ep

https://progress.opensuse.org/issues/33676
- Allows to select how the builds are grouped:
-- By build (is by default): shows a tree grouping first the builds and
its groups results
-- By group (the new view): Shows a tree grouping first the groups and then the builds
- Allows to the user to store the preference in cookies for this product
and for all products
- Allows to select the view through the url

Add "by groups name" as option to organize the builds in parent group overview (by ilausuch, rebased)

---

lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
t/32-openqa_client.t
t/api/04-jobs.t
t/ui/18-tests-details.t

Note: I didn't attempt to use `$validation` for the arrayish values because that seems like it would be using the API for the sake of using it... so I only applied it to the subset which requires specific parameters.
See: [poo#64075](https://progress.opensuse.org/issues/64075)

Validate parameters passed to job API routes

---

lib/OpenQA/Log.pm
t/28-logging.t

* t: Extend 28-logging.t to cover color codes
* Define custom log color selection compatible with reverse video terminals
* Slightly simplify OpenQA::Log
* Add colors to log output when available
* t: Add trivial test for OpenQA::Log::get_channel_handle coverage
* t: Simplify stdout matching in 28-logging.t
* t: Fix warning "Prototype mismatch: sub Time::HiRes::gettimeofday"
Might not make much of a difference for production but makes debugging from log files also within local tests so much more enjoyable :)

Add colors to log output when available

---

t/43-cli-archive.t

To avoid clobbering up `/tmp` with `DFGDF34` folders.
Inspired by os-autoinst unit tests.

Use named tempdir in cli archive unit test

---

assets/stylesheets/test-details.scss

My job details page performance optimization introduced a minor graphical artifact to audio result boxes: https://openqa.suse.de/tests/4288141#step/firefox_audio/4
Fix the icon position in audio result box.

Fix visual artifact in audio result box

---

t/basic.t
t/lib/OpenQA/Test/TimeLimit.pm

Tests are only fun to call when they are not taking too long hence it makes sense to check their runtime against unintended runtime increases as happened some times in the past. Also this helps to save time for persons executing tests encountering other problems that lead to tests getting stuck as the timeout would abort the test early.
This PR is adding a test module that can be included in – at best – all tests setting a reasonable test-specific timeout to prevent an unintented increase of runtime. Also added is the example use of the test module in a single test with the idea to use the test module in more and more cases.

Limit test execution time in tests

---

lib/OpenQA/Schema/Result/JobModules.pm

The `JobModules` class sometimes needs to access the parent job internally. If the job wasn't prefetched, this can lead to hundreds or even thousands of unnecessary DB queries. This patch speeds up server-side generation of job details JSON up to 5 times for ltp_syscalls jobs (1100+ test modules).
You can measure performance improvement on these jobs:
- [ltp_openposix](https://openqa.suse.de/tests/4287498) (1608 modules)
- [ltp_syscalls](https://openqa.suse.de/tests/4287479) (1165 modules)

Prefetch parent job in JobModules::job_modules()

---

t/05-scheduler-full.t
t/14-grutasks.t
t/33-developer_mode.t
t/40-script_load_templates.t
t/43-scheduling-and-worker-scalability.t
t/full-stack.t
t/lib/OpenQA/SeleniumTest.pm
t/lib/OpenQA/Test/FullstackUtils.pm
t/lib/OpenQA/Test/Utils.pm

Whenever processes are spawned they need to be tracked properly for
cleanup. This posed problems of sometimes leaking orphans when tests are
aborted or crashed. As we already use IPC::Run we can use the same for
other cases where we spawn processes with fork by using IPC::Run::start
instead. Additional benefits are that we can debug the process handling
and IPC going with https://metacpan.org/pod/IPC::Run#Debugging-Tip as
well as be able to catch output of the processes.
One example of a recent problem that should be fixed by this is
t/05-scheduler-full.t failing to stop completely when individual test
steps fail. This prevents the RETRY on the level of tools/retry and the
Makefile to work as the former test never completely finishes and is
stuck until the CI aborts the complete test run …

t: Make process handling more robust with IPC::Run

---

t/16-utils-job-templates.t

t/16-utils-job-templates.t .. "my" variable $errors masks earlier declaration in same scope at t/16-utils-job-templates.t line 51.

Do not shadow $errors in utils-job-templates test

---

t/24-worker-jobs.t

[WARN] Found poolr3UU/base_state.json but failed to parse the JSON: '"' expected, at character offset 16 (before "(end of string)") at /usr

Capture base_state.json JSON error warning in worker jobs test

---

.circleci/config.yml

Otherwise some STDERR output will not land in the artifact, so we don't
see some additional warnings.

Add '--merge' option to prove

---

t/lib/OpenQA/Test/TimeLimit.pm

Instead of
```
t/basic.t .. run(/usr/bin/sass) failed: test exceeds runtime limit of '1' seconds
($?=0, $!=29, PATH=/home/okurz/.gem/ruby/2.5.0/bin:/home/okurz/perl5.26/bin:/home/okurz/perl5.26/perlbrew/bin:/home/okurz/perl5.26/bin:/home/okurz/local/os-autoinst/scripts:/suse/bin:/usr/lib/ccache:/home/okurz/local/python_venv-linux-28d6.suse/bin:/home/okurz/.npm-packages/bin:/home/okurz/node_modules/.bin:/opt/bin:/home/okurz/bin:/home/okurz/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/lib/mit/sbin:/home/okurz/.neo:/home/krz/.neo/:/home/okurz/documents/Computer/todo.txt/todo.txt-cli) at /usr/lib/perl5/vendor_perl/5.26.1/Mojolicious/Plugin/AssetPack/Pipe.pm line 30.
t/basic.t .. Dubious, test returned 29 (wstat 7424, 0x1d00)
No subtests run
Test Summary Report
-------------------
t/basic.t …
```

t: Make output nicer on time limit

---

docs/WritingTests.asciidoc

VIRTIO_CONSOLE was enabled in 2018 in 7226ced3 ("qemu: virtio terminal is enabled by default") and yet there are still some confusions about it: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/10424#issuecomment-637095487.

doc: Improve virtio/svirt serial terminal doc

---

lib/OpenQA/Constants.pm
lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/Utils.pm
lib/OpenQA/WebAPI/Controller/Step.pm
lib/OpenQA/WebAPI/Plugin/Helpers.pm
lib/OpenQA/Worker/Job.pm
t/10-jobs.t
t/24-worker-jobs.t
t/ui/07-file.t
t/ui/18-tests-details.t
templates/webapi/step/viewimg.html.ep
templates/webapi/test/downloads.html.ep
templates/webapi/test/video.html.ep

* Nothing changes for regular jobs producing `video.ogv` or no video at all.
* Settings influencing the video encoding are only passed from the worker
config to isotovideo but not from job settings to avoid running arbitrary
commands on the worker.
* All artefacts named like `video.*` will be considered videos. This affects
* files considered to be uploaded by the worker.
* cleanup of results.
* the list in the 'Logs & Assets' tab.
* See https://progress.opensuse.org/issues/67342

Generalize handling the video

---

.circleci/unstable_tests.txt

For example see
https://app.circleci.com/pipelines/github/os-autoinst/openQA/3103/workflows/65a02451-f06f-470b-a677-5cb7d0201f4e/jobs/29589/steps

Mark "25-cache-service.t" as unstable test as observed in circleci

---

lib/OpenQA/WebAPI/Plugin/ObsRsync.pm

Small change to remove some dead code from `OpenQA::WebAPI::Plugin::ObsRsync`. I'm a little disappointed that #3052 got approved despite the objections. But this PR will resolve the issues raised.
1) It's bad practice to wrap `->single` calls in an `eval` (confirmed with a second opinion from the `DBIx::Class` author in #3052).
2) Wrapping `readlink` in an `eval` does nothing, the function only throws an exception if the operating system does not support the required syscall (Win32, RISC OS, VMS), normal errors return `undef` and set `$!`.

Remove dead code from OpenQA::WebAPI::Plugin::ObsRsync

---

t/28-logging.t

This wasn't catched by our CI because it still has
Test::MockModule 0.13, where the strict option is not yet supported.
Test::MockModule didn't warn about that option being unsupported
because it doesn't check for unknown imports.
Created an issue:
https://github.com/geofffranks/test-mockmodule/issues/45

t: Use Test::MockModule->redefine in t/28-logging.t

---

lib/OpenQA/Schema/Result/JobModules.pm
lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/Utils.pm
lib/OpenQA/WebAPI/Controller/Step.pm

While reviewing #3144 i noticed these two functions, they should really be methods. The schema is object-oriented after all.

Turn two schema functions into methods

---

assets/javascripts/running.js
assets/javascripts/test_result.js
lib/OpenQA/Worker/Job.pm

This is an additional tweak for https://progress.opensuse.org/issues/56591.

Hide livestream when loading test details and job is currently uploading

---

assets/stylesheets/comments.scss
templates/webapi/comments/pagination.html.ep

https://progress.opensuse.org/issues/52745
Pagination is not responsive and breaks the screen adding scroll bars
This is a solution based on allow multiple lines and showing all the
pages at the same time without summarizing
Additionally a new css is added to bold the current page in the
pagination bar
Alternative to #3015

Fix pagination in the group overview

---

assets/javascripts/admin_user.js

https://progress.opensuse.org/issues/47210
Problem: In the user administration page. When a role is changed
the page is reloaded loosing the page in the paginator.
Solution: Programmatically summit the form to prevent the page
reload. This solves the problem

Maintain pagination when an user role changes

---

assets/javascripts/index.js
assets/stylesheets/dashboard.scss
templates/webapi/main/index.html.ep

https://progress.opensuse.org/issues/17886
This new feature allows to autorefresh the index page with 30, 60,
120 and 180 seconds. The user controls the interval with the
filter control panel.

Add autorefresh in the index page for fullscreen mode feature

---

lib/OpenQA/Downloader.pm

Prevents
```
Can't use an undefined value as a HASH reference at /usr/share/openqa/script/../lib/OpenQA/Downloader.pm line 85.
```
observed on o3.

Prevent Perl warning in downloader code

---

lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Auth/OpenID.pm

Allow OpenID login via POST request
This is needed because our new ipsilon-based OpenID provider
(sometimes?) sends the response via POST instead of GET.

Allow OpenID login via POST request

---

script/openqa-clone-custom-git-refspec

We can not read out necessary configuration data in any case of
selecting a job that does not exist, is a completely wrong URL or job
without vars.json, e.g. very old job with deleted results or scheduled
or still running job. This commit adds an explanatory error message
including a suggestion with a URL pointing to the "Next & previous" jobs
in the same test scenario.
Related progress issue: https://progress.opensuse.org/issues/67888

Add error message when openqa-clone-custom-git-refspec is called on invalid job

---

profiles/apparmor.d/usr.share.openqa.script.openqa

For some time now we had the problem that the monitoring feature didn't work because its data would get corrupted after some time, resulting in webui processes crashing. The cause is twofold, first `Mojolicious::Plugin::Status` had [a bug](https://github.com/mojolicious/mojo-status/commit/b53759ca0fc2602352ebde377aaa08f9049258d5) causing it to silently ignore `flock` errors, and second our apparmor profile did not allow `flock` on temporary files. This PR fixes the second problem and should make monitoring work again.

Allow flock on temporary files to fix support for monitoring

---

lib/OpenQA/Worker/Job.pm
t/24-worker-jobs.t

This partially reverts the commit
"Only reload test schedule when test_order.json has been changed"
0d1061afd816b190fdd265d7da412ce8f78bbe3b.

Attempt to fix sporadically missing test modules due to 0d1061af

---

lib/OpenQA/CacheService.pm
lib/OpenQA/CacheService/Command/run.pm
script/openqa-worker-cacheservice-minion
t/25-cache-service.t
t/lib/OpenQA/Test/Utils.pm

Otherwise there might be leftover locks that will cause new downloads
for the same files to wait for non-existing download jobs. The
implementation is almost the same as the Gru --reset-locks feature. So
it will be very easy to add more features in the future.
Gru feature: https://github.com/os-autoinst/openQA/commit/040083a1f446653e826c094dd734666424897255
Progress: https://progress.opensuse.org/issues/68131

Reset locks when restarting the cache service Minion worker

---

script/openqa-worker-cacheservice-minion

This fixes https://github.com/os-autoinst/openQA/pull/3177

Fix order of arguments in script/openqa-worker-cacheservice-minion

---

lib/OpenQA/Worker/Job.pm
t/24-worker-jobs.t

It was reporting that the schedule changed too often.
Issue: https://progress.opensuse.org/issues/58700
It's still not clear why we need to reread the schedule whenever
$current_test_module is unset, see code comment.

Fix logic for changed schedule

---

lib/OpenQA/Worker/Job.pm
t/24-worker-jobs.t

This can happen if a test is finished and the new one hasn't started.
(Reproduce by adding a `sleep 10` in basetest.pm after `$self->done()`.
The backend will report an empty `$running_test`, and in this case
`$current_test_module` should keep its last value.
It will also reduce payload of the status posts, because it previously posted
the status of *all* tests when `$current_test_module` was empty.
This also fixes the issue that results of short tests < 10s are only
reported at the end of the job.
Related Issues:
* https://progress.opensuse.org/issues/58826
* https://progress.opensuse.org/issues/58700
* https://progress.opensuse.org/issues/67972

Prevent schedule from being reread unnecessarily

---

docker/devel:openQA:ci/base/Dockerfile

* Workaround an issue within the latest chromeriver as provided by Leap by installing an older version of chromedriver
* See https://progress.opensuse.org/issues/68284

Fix running Selenium tests within CI

---

docker/devel:openQA:ci/base/Dockerfile

Unfortunately this did not work because OBS parses the Dockerfile for zypper invocations and tries to resolve the dependencies.
The suggested alternative is to aggregate the old version in some other repository and add that one as the most important repo.

Remove versioned chromedriver install again

---

docs/GettingStarted.asciidoc

With https://github.com/os-autoinst/openQA/pull/2887 we moved
lib/OpenQA/Schema/JobGroupDefaults.pm → lib/OpenQA/JobGroupDefaults.pm
but we missed to update docs.

docu: Fix href of JobGroupDefaults.pm because of a7fb32a

---

.circleci/config.yml

* Temporary workaround for an issue within the latest chromeriver as provided by Leap
* It is not possible to do this within the Dockerfile, see fb832aaed
* See https://progress.opensuse.org/issues/68284

Downgrade chromedriver to fix running Selenium tests within CI

---

templates/webapi/test/overview.html.ep

When accessing the `overview` page and give only `build=XYZ` as parameter, I do
get all expected jobs listed, but if there is only _one_ version per
`DISTRI` then the `VERSION` isn't displayed even if I have multiple
`DISTRI`'s.
Example:
You have multiple products configured like openSUSE_15.2, SLE-15-SP2 and
SLE-12-SP5.
Then run a `isos post` within each medium and give all them the same
`BUILD` value (e.g. `wip-ifreload-1_sle15-sp2-b34fe756`). Then it would
be nice to see all of them on such a overview page.
Why I would choose the same `BUILD` among different products. Cause I
just don't care about the real `BUILD` what ever that mean. What I'm
going to test is a application (here it is wicked) within different
products. And this application is running with the "BUILD" …

overview: Show version when DISTRI differs

---

README.asciidoc

Point circeci badge directly to master showing release relevant build
results instead of all the results from arbitrary pull requests which
are most likely not relevant for anyone clicking on the badge. Same as
for codecov we link to the master branch as link target as well.

README: Fix circleci badge to master branch

---

t/api/04-jobs.t
t/lib/OpenQA/Test/Database.pm

- add_fixtures takes an optional glob of fixture files
- api/04-jobs uses only relevant fixtures
- fixes for exact dependence on ids and other subtests
- use named tempdir
The overall test run should be faster thanks to reducing the use of unnecessary fixtures at initialization time.

Reduce common fixtures used in api/04-jobs

---

t/api/01-workers.t
t/api/02-assets.t
t/api/02-iso-download.t
t/api/02-iso.t
t/api/03-auth.t
t/api/05-machines.t
t/api/06-products.t
t/api/07-testsuites.t
t/api/08-jobtemplates.t
t/api/09-comments.t
t/api/10-jobgroups.t
t/api/11-bugs.t
t/api/12-admin-workers.t
t/api/13-influxdb.t
t/api/14-plugin_obs_rsync.t
t/api/14-plugin_obs_rsync_async.t

Another follow-up for #3214 reducing fixture use in `api` tests.

Narrow down fixtures needed by api tests

---

assets/javascripts/tests.js
assets/stylesheets/test-details.scss
templates/webapi/test/infopanel.html.ep

https://progress.opensuse.org/issues/44654
This helps to get a quick overview in test details showing grouped results in tab on details page.
unlike in https://github.com/os-autoinst/openQA/pull/3184 this approach used the backend to render the summary

Summarize results in test details tab (alternative)

---

lib/OpenQA/Schema/Result/JobModules.pm
lib/OpenQA/Worker/Job.pm

* Use Mojo::File::slurp instead of using open() and close() manually
* Don't rely on the return value of logging functions for proper error handling
* Don't log every attempt to read a JSON file

Simplify code for reading JSON files

---

lib/OpenQA/CacheService/Client.pm
lib/OpenQA/CacheService/Controller/API.pm
lib/OpenQA/CacheService/Response.pm
lib/OpenQA/CacheService/Response/Info.pm
lib/OpenQA/CacheService/Response/Status.pm
lib/OpenQA/Worker/Engines/isotovideo.pm
t/24-worker-overall.t
t/25-cache-client.t
t/25-cache-service.t

There were quite a few error conditions that could result in the cache service client breaking workers. This PR adds lots of tests for them and will allow the worker to handle all of them gracefully.
Progress: https://progress.opensuse.org/issues/66988

Improve cache service client exception handling

---

systemd/openqa-worker@.service

The dependencies of the openQA worker including the openqa-webui.service have
been added a very long time ago in commit 55a8d9be1 but unfortunately from the
git commit messages we do not know the reason. Likely the use case was for a
single-instance setup to synchronise the services. However in general the
systemd service definition does not know for which openQA webUI instance the
worker is configured, if it is remote or local, so pulling in and waiting for
the local webUI regardless of the configuration is incorrect.
This commit removes both the "Wants=" and "After=" dependency on
openqa-webui.service. The prerequisite to be able to remove the dependency is
that the worker automatically reconnects until it can connect to the configured
webui.  The argument about "the user can configure …

systemd: Prevent worker erroneously pulling in any local openQA webUI service

---

t/10-jobs.t
t/10-tests_overview.t
t/11-commands.t
t/12-profiler.t
t/14-grutasks.t
t/17-build_tagging.t
t/17-labels_carry_over.t
t/22-dashboard.t
t/27-errorpages.t
t/31-client_archive.t
t/32-openqa_client.t
t/34-developer_mode-unit.t
t/36-job_group_defaults.t
t/37-limit_assets.t
t/38-workers-table.t
t/39-scheduled_products-table.t
t/41-audit-log.t
t/43-cli-api.t
t/43-cli-archive.t

Another follow-up for #3214 reducing fixture use in uncategorized tests.

Narrow down fixtures needed by toplevel tests

---

.circleci/ci-packages.txt
cpanfile
dependencies.yaml
docs/Installing.asciidoc
lib/OpenQA/Setup.pm
lib/OpenQA/Shared/Controller/Session.pm
lib/OpenQA/WebAPI/Auth/OAuth2.pm
openQA.spec
t/03-auth.t
t/config.t

- The new method needs to be enabled in the config file, which is described in the installation doc.
- Currently `github` is the only accepted value because authorization with GitHub doesn't follow the _OpenID Connect_ spec. Although adding other providers will be straightforward.
Fixes: [poo#67576](https://progress.opensuse.org/issues/67576)

Add OAuth2 auth method with GitHub provider

---

assets/javascripts/admin_needle.js
assets/stylesheets/admin-pages.scss
lib/OpenQA/WebAPI/Controller/Admin/Needle.pm
t/ui/21-admin-needles.t
templates/webapi/admin/needle/index.html.ep
templates/webapi/admin/needle/needle_search.html.ep

See: https://progress.opensuse.org/issues/53675

Expand the search range in used/match when querying needles

---

.circleci/ci-packages.txt

Version 0.25 is not available anymore, so all PRs will fail until the
next nightly

deps: Update Mojo-IOLoop-ReadWriteProcess

---

dbicdh/PostgreSQL/deploy/89/001-auto-__VERSION.sql
dbicdh/PostgreSQL/deploy/89/001-auto.sql
dbicdh/PostgreSQL/upgrade/88-89/001-auto.sql
dbicdh/_source/deploy/89/001-auto-__VERSION.yml
dbicdh/_source/deploy/89/001-auto.yml
lib/OpenQA/Schema.pm
lib/OpenQA/Schema/Result/Jobs.pm
t/fixtures/01-jobs.pl
t/ui/01-list.t
t/ui/12-needle-edit.t
t/ui/14-dashboard-parents.t
t/ui/16-tests_job_next_previous.t
t/ui/26-jobs_restart.t

We do not test anything about the value of the "backend" job table
column since 08e4af3f2 in 2015. Also checking on common instances, e.g.
openqa.opensuse.org with an SQL query
```
openqa=> select id,t_created,backend from jobs where backend is not null order by t_created desc limit 3;
id   |      t_created      | backend
-------+---------------------+---------
98179 | 2015-11-04 12:04:17 | qemu
98176 | 2015-11-04 12:02:24 | qemu
97714 | 2015-11-01 12:09:57 | qemu
(3 rows)
```
reveals that the column has been last filled with a non-null value in late 2015.
During database migration to the new version the column will be dropped
causing unrecoverable loss of the corresponding data. If the data is
used by any manual database readout by users a backup and manual
migration to an external …

Remove obsolete table column 'backend'

---

cpanfile
dependencies.yaml
lib/OpenQA/Worker/Engines/isotovideo.pm
openQA.spec

* Do not send SIGTERM repeatedly (without waiting time between the
attempts) so the video encoder (e.g. ffmpeg) will be able to finalize
the file (e.g. write the index and total duration).
* SIGKILL is still sent after 10 seconds to deal with stuck processes.
* See https://progress.opensuse.org/issues/67342#note-5

worker: Allow video encoder to finalize the file

---

dependencies.yaml
openQA.spec

Split subpackage "no-selenium-devel" out of "devel" so that we can
provide a sensible variant for cases when chromedriver is not available,
e.g. as is the case for ppc64le on openSUSE/SLE.

spec: Prevent unresolvable on ppc64le with no-selenium-devel subpackage

---

openQA.spec

Doing "%ifarch" in noarch packages seems to be problematic.

spec: Fix build missing "devel" package

---

openQA.spec

Related progress issue: https://progress.opensuse.org/issues/68836

spec: Exclude flaky t/api/14-plugin_obs_rsync_async.t from tests

---

assets/javascripts/test_result.js

Collapse content of initial rows in investigation tab when content becomes too big, e.g. more than 10 lines
https://progress.opensuse.org/issues/19720
- Shows only the 10 initial lines
- Add a link to show the rest of lines

Collapse content of in investigation when content is too big

---

lib/OpenQA/WebAPI/Auth/OAuth2.pm

create_user takes hash keys without parens.

Fix user creation in OAuth2 plugin

---

docs/Networking.asciidoc

The two sections "TAP Based Network" and "VDE Based Network" were below
"QEMU User Networking" which is wrong. Over time the section "Multi
Machine Tests Setup" was added which is specific to the use of
openvswitch equivalent to "TAP Based Network" so we should combine both
sections. And as "VDE Based Network" is less used I move it to the
bottom.
Related progress issue: https://progress.opensuse.org/issues/33697

docs: Fix and improve networking sections

---

script/openqa-clone-custom-git-refspec

A problem was observed in jq version 1.5 that the JSON document was
properly evaluated but still jq would return an exit code of 2 instead
of 0 unless a scope is given, e.g. with ".".

openqa-clone-custom-git-refspec: Fix curl+jq check for jq < 1.6

---

docs/WritingTests.asciidoc

Add a short explanation how to add a systemd override file that adds the `--no-cleanup` parameter to the worker for snapshots to work.

Add docs how to set the --no-cleanup parameter in the systemd units

---

assets/javascripts/admin_user.js
lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Controller/API/V1/User.pm
lib/OpenQA/WebAPI/Plugin/AuditLog.pm
t/api/15-users.t
templates/webapi/admin/user/index.html.ep

https://progress.opensuse.org/issues/68702
Add UI support for removing users
- Created API function for removing users
- Created UI elements to perform the action
- Only admins could see the delete button and can delete users
- The table is manipulated by JS instead of reload the page
- Added test to prove that admins can delete users, and other not

Add UI support for removing users

---

assets/javascripts/test_result.js
lib/OpenQA/Schema/Result/Jobs.pm
t/10-jobs.t

https://progress.opensuse.org/issues/19720
If a valid last_good job ID is present in the investigation result
set, then it is replaced by html code <a> to link directly to this job.
In order to tell to the JS that this is a link, the value is a hash
where a type => link is set.
In JS detects if it is an object and if the type has being defined
or not. If is link then creates a link with the information.
In other cases, now only traditional use, then creates a \<pre\> element.
This allows to add typed information like links to files,
tables, but also colorize the values is needed.
Alternative to https://github.com/os-autoinst/openQA/pull/3261 without adding extra information to the name of the variables

Make "last good" a link to a job instead of plain job ID

---

assets/javascripts/running.js
assets/javascripts/test_result.js

These two issues are actually distinct but are observed at the same time when showing job details for a running job with the hash '#dependencies'. As the particular commit message state this change avoids overriding the explicitly specified tab/step when loading a running job. It also ensures that the dependency graph is only rendered while its tab is active to avoid rendering problems.

Fix tab-handling related issues on test details page

---

Makefile

This especially prevents removing the contents of all JavaScript files when js-beautify is not installed.

Fail Makefile targets if checks for certain tools fail

---

assets/javascripts/running.js
assets/stylesheets/test-details.scss
lib/OpenQA/Resource/Jobs.pm
lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
t/05-scheduler-dependencies.t
t/05-scheduler-restart-and-duplicate.t
t/api/04-jobs.t
templates/webapi/test/infopanel.html.ep

It makes sense to restart directly chained parents because otherwise it is
not ensured that the child actually directly after its parent on the same
worker.
See https://progress.opensuse.org/issues/68956

Clone directly chained parents when restarting jobs

---

Makefile

Make *prove* aware of the fact that `timeout` kills it before it can record the results using [--trap](https://perldoc.perl.org/prove.html#--trap) and [-s SIGINT -k 5](https://man7.org/linux/man-pages/man1/timeout.1.html). This allows results to be recorded. There is a fallback timeout in case the process doesn't exit after that.
Fixes: [poo#69148](https://progress.opensuse.org/issues/69148)

Make prove aware of timeout

---

.jsbeautifyrc
Makefile

Although the makefile relies on the command line, a config file is required for editor plugins.
In case you're wondering "what editor" I'm using [VSCodeBeautify](https://github.com/HookyQR/VSCodeBeautify#how-we-determine-what-settings-to-use) which without this will produce the wrong results.

Add .jsbeautifyrc for editor support

---

lib/OpenQA/Schema/Result/Jobs.pm
t/10-jobs.t

Related progress issue: https://progress.opensuse.org/issues/69085

Fix "last good" link introduced in 8fc2dc99a

---

lib/OpenQA/Task/Job/Limit.pm
t/42-screenshots.t

These are mostly micro optimizations to speed up the screenshot deletion loop a bit. Just in case the `unlink` syscalls are not the sole bottleneck in the `limit_screenshots` job.
1. `imagesdir()` call has been moved out of the loops.
2. `log_debug` call has been moved out of the inner loop into the outer loop (less function call, but still an indication for the job still being active in the logs).
3. Change `fetchrow_arrayref` loop to `fetchall_arrayref` call (`DBD::Pg` always retrieves all results at once anyway, so repetitive `fetchrow_arrayref` calls only cause overhead).
4. Combine two `unlink` calls to one (does not reduce the number of syscalls unfortunately, but is a little faster).

Make a few small optimizations to speed up the deletion of screenshots

---

assets/javascripts/overview.js
assets/javascripts/tests.js
lib/OpenQA/WebAPI/Controller/Test.pm
t/ui/10-tests_overview.t
templates/webapi/test/tr_job_result.html.ep

Following the way that used in tests page:
1. use a little branch icon to show the related jobs
2. different color of the branch icon means different status:
a. when the icon is blue, it means the job has no parent job
b. when the icon is red, it means the job's parent job failed
c. when the icon is green, it means the job's parent job success
See: https://progress.opensuse.org/issues/15850

Show job dependency on the Test overview page

---

docker/devel:openQA:ci/base/Dockerfile

This change adds the required dependencies to the Dockerfile without removing old dependencies. This way the existing CI checks keep working.
The actual switch to CMake/ninja is done in a follow-up PR which will also remove the dependencies for autotools.

Prepare using CMake and ninja to build os-autoinst

---

profiles/apparmor.d/usr.share.openqa.script.worker

See https://progress.opensuse.org/issues/68923#note-7

Allow the worker to start ffmpeg to encode the video

---

.circleci/build_autoinst.sh
docker/devel:openQA:ci/base/Dockerfile
tools/run-tests-within-container

I suppose this is actually necessary because os-autoinst-devel will now only pull the dependencies for the CMake build.

Use CMake to build os-autoinst

---

lib/OpenQA/WebAPI/Controller/API/V1/Job.pm

Looks like this code was forgotten when `OpenQA::Events` got added.

Remove dead code from Job controller

---

Makefile

As discussed in https://github.com/os-autoinst/openQA/pull/3194
while changing `-I$(PWD)/t/lib` to `-It/lib` made things work in
Docker, it broke them in Fedora's build system. We really don't
know why and it's a bit of a mystery, but it seems easier to just
have both than try and figure out the causes.

`make test-with-database`: add -I$(PWD)/t/lib back to PERL5OPT

---

assets/javascripts/overview.js
assets/javascripts/tests.js
t/ui/10-tests_overview.t
templates/webapi/test/tr_job_result.html.ep

This is a followup for #3287.
1. when putting the mouse over the branch icon:
a. highlight parent jobs with red color
b. highlight child jobs with blue color
2. Fix a javascript issue
Related: https://github.com/os-autoinst/openQA/pull/3287#issuecomment-665614031

Highlight dependency jobs in the overview page

---

lib/OpenQA/CacheService/Client.pm
t/25-cache-client.t

Default is to retry 3 times and waiting 5 seconds in between attempts. The choice is pretty arbitrary and i welcome arguments for better defaults. The feature should trigger very rarely though, so maybe not worth overthinking it.
Progress: https://progress.opensuse.org/issues/64776

Add retry feature to cache service client

---

assets/javascripts/test_result.js
docs/WritingTests.asciidoc
lib/OpenQA/Resource/Jobs.pm
lib/OpenQA/Schema/Result/Jobs.pm
lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
t/05-scheduler-cancel.t
t/05-scheduler-dependencies.t
t/05-scheduler-restart-and-duplicate.t
t/api/04-jobs.t
templates/webapi/test/infopanel.html.ep

* This is particularly useful for directly chained dependencies where it
does not make sense to restart failed children on-by-one.
* For consistency, expose the ability to skip children generally via the
API as well. That means it is now possible to skip restarting parents and
children and only passed children.
* Also improve the error message when restarting is not possible.
* See https://progress.opensuse.org/issues/68956#note-22

Allow skipping passed children when restarting a job

---

t/43-cli-api.t

Just to make sure GNU style options actually work (since it's an extra option in `Getopt::Long`).

Add tests for GNU style arguments

---

t/05-scheduler-cancel.t
t/05-scheduler-capabilities.t
t/05-scheduler-dependencies.t
t/05-scheduler-serialize-directly-chained-dependencies.t
t/07-api_jobtokens.t
t/07-api_keys.t
t/09-job_clone.t
t/13-joblocks.t
t/15-assets.t
t/19-tests-export.t
t/20-stale-job-detection.t
t/23-amqp.t
t/27-websockets.t
t/42-screenshots.t

* See https://progress.opensuse.org/issues/69868
---
* Move out test for serializing sequence of directly chained dependencies
* This test does not require the database so having it in a separate file does not increase the overall test execution time a lot
* Improve test helper to reduce boilerplate code
* Remove redundant/duplicated checks
* Move the different parts into sub tests

Refactor t/05-scheduler-dependencies.t

---

lib/OpenQA/Command.pm
t/33-developer_mode.t
t/43-cli-api.t
t/full-stack.t
t/lib/OpenQA/Test/FullstackUtils.pm

Simple fix for a problem @Martchus noticed last week. Makes `openqa-cli api -X POST jobs/restart jobs=1611 jobs=1610` work.

Fix support for multiple params with the same name in api command

---

lib/OpenQA/WebAPI.pm
lib/OpenQA/WebAPI/Description.pm
t/31-api_descriptions.t

This variable is undocumented and only works with a system-wide installation in a specific location.

Do not hard-code source tree for API descriptions

---

lib/OpenQA/Resource/Jobs.pm
lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
lib/OpenQA/WebAPI/Plugin/AMQP.pm
lib/OpenQA/WebAPI/Plugin/AuditLog.pm
t/05-scheduler-restart-and-duplicate.t
t/15-assets.t
t/23-amqp.t
t/api/04-jobs.t

* Drop the "job_duplicate" event; only emit "job_restart" events
* Keep the slightly different behavior of "restart" and "duplicate" in
place for compatibility
* Point out the difference between the "duplicate" and "restart" route
* Point out that the "dup_type_auto" parameter has only informal purposes
* Support all the options in both routes
* Allow passing zero values to flag parameters in order to disable defaults
* Share the same implementation
* Improve returning results of "job_restart" (at some point returning an
array becomes unhandy)
* Add explicit test for the "duplicate" route
* See https://progress.opensuse.org/issues/69997

Streamline "duplicate" and "restart" routes

---

lib/OpenQA/Resource/Jobs.pm
lib/OpenQA/Scheduler/Model/Jobs.pm
lib/OpenQA/Schema/Result/Jobs.pm
t/05-scheduler-full.t
t/05-scheduler-restart-and-duplicate.t
t/09-job_clone.t
t/api/04-jobs.t

* Return expected exceptions to the user as error messages
* Avoid returning random exceptions like database errors
* Improve logging
* See https://progress.opensuse.org/issues/69871

Improve error messages when cloning a job
