- t/api/02-iso.t
This should help to make t/api/02-iso.t a little bit more readable by
removing duplication of test settings.
> t: Use a hash with default settings for the common "schedule_iso" calls

- public/schema/JobTemplates-01.yaml
See: https://progress.opensuse.org/issues/60371
> Support job template setting start with plus

- t/ui/01-list.t
- t/ui/10-tests_overview.t
- t/ui/13-admin.t
- t/ui/14-dashboard-parents.t
- t/ui/15-admin-workers.t
- t/ui/15-comments.t
- t/ui/16-tests_job_next_previous.t
- t/ui/17-product-log.t
- t/ui/18-tests-details.t
- t/ui/19-tests-links.t
- t/ui/24-feature-tour.t
- t/ui/25-developer_mode.t
- t/ui/26-jobs_restart.t
see particular commit messages
> Make UI tests a little bit faster

- t/10-jobs.t
* t: Add a description string for each step in 10-jobs.t
* t: Correct order of arguments for comment counting
> test enhancements

- lib/OpenQA/Schema/Result/ScheduledProducts.pm
- lib/OpenQA/Schema/ResultSet/Jobs.pm
- t/api/02-iso.t
- t/api/04-jobs.t
See: https://progress.opensuse.org/issues/54809
> Return error when creating a job with invalid slash value

- .circleci/config.yml
Dependencybot can tidy source code as well when Tidy version changes
> Let nightly job call script/tidy when needed

- lib/OpenQA/Constants.pm
- t/20-stale-job-detection.t
- t/api/01-workers.t
- t/ui/15-admin-workers.t
from 2 minutes to 2 days.
See https://progress.opensuse.org/issues/60866 and discussion in Rocket Chat.
> Increase the inactivity timeout for workers and running jobs

- dbicdh/PostgreSQL/deploy/84/001-auto-__VERSION.sql
- dbicdh/PostgreSQL/deploy/84/001-auto.sql
- dbicdh/PostgreSQL/upgrade/83-84/001-auto.sql
- dbicdh/_source/deploy/84/001-auto-__VERSION.yml
- dbicdh/_source/deploy/84/001-auto.yml
- lib/OpenQA/Schema.pm
- lib/OpenQA/Schema/Result/JobGroups.pm
- lib/OpenQA/Schema/Result/JobTemplates.pm
- lib/OpenQA/Schema/Result/Jobs.pm
- lib/OpenQA/Schema/Result/ScheduledProducts.pm
- lib/OpenQA/Schema/ResultSet/JobTemplates.pm
- lib/OpenQA/WebAPI/Controller/Test.pm
- public/schema/JobTemplates-01.yaml
- t/api/08-jobtemplates.t
- t/fixtures/04-products.pl
- t/ui/13-admin.t
- templates/test/infopanel.html.ep
Depends on: https://github.com/os-autoinst/openQA/pull/2596
Not yet much tests for the new feature
Issue: https://progress.opensuse.org/issues/60782
> Add Descriptions for parameterized Job Templates

- docs/WritingTests.asciidoc
See https://progress.opensuse.org/issues/58166#note-25
> Improve documentation about test flags (especially fatal)

- lib/OpenQA/CacheService/Model/Cache.pm
- t/25-cache.t
- t/lib/OpenQA/Test/Utils.pm
This is an alternative solution for #2638.
Progress: https://progress.opensuse.org/issues/54827
> Support downloading assets with special characters in the name

- assets/javascripts/test_result.js
See https://github.com/os-autoinst/openQA/pull/2623/files#r363766766
> Prevent loading investigation tab contents twice

- lib/OpenQA/Schema/Result/Jobs.pm
- lib/OpenQA/Schema/Result/ScheduledProducts.pm
- lib/OpenQA/WebAPI/Controller/Test.pm
Followup-To: https://github.com/os-autoinst/openQA/pull/2602
How/when do we migrate existing settings in the database?
> Rename TEST_SUITE_DESCRIPTION to JOB_DESCRIPTION

- assets/javascripts/test_result.js
- assets/stylesheets/admin-pages.scss
- assets/stylesheets/test-details.scss
- lib/OpenQA/WebAPI/Controller/Test.pm
- t/ui/18-tests-details.t
* Client-side alternative to https://github.com/os-autoinst/openQA/pull/2623, see https://github.com/os-autoinst/openQA/pull/2623/files#r363755039
* No XSS/CSRF vulnerability
* Styling consistent with settings tab
> Investigation table

- Makefile
- openQA.spec
- systemd/tmpfiles-openqa-webui.conf
* Create tmpfiles.d config for web UI
* See https://progress.opensuse.org/issues/60713
> Add auto-cleanup for temp files created by web UI

- lib/OpenQA/Schema/Result/ScheduledProducts.pm
- t/api/02-iso.t
Set the job_template_name as the TEST value if it exists.
This modification will cause those following changes:
```
- apparmor_variant:
testsuite: apparmor
settings:
START_AFTER_TEST: create_hdd_textmode
- create_hdd_textmode_variant:
testsuite: create_hdd_textmode
```
1. when users want to trigger `apparmor_variant` job with `TEST`
parameter, only `TEST=apparmor_variant` works. In this scenario, specify
the test suite name does not work.
2. When triggering jobs with `TEST=apparmor_variant`, the parent job
won't be triggered. If users want to both trigger the parent job, need
to define `START_AFTER_TEST: create_hdd_textmode_variant`.
Related pr: https://github.com/os-autoinst/openQA/pull/2553
See: https://progress.opensuse.org/issues/59097
> Use job_template_name as the TEST when scheduling jobs

- openQA.spec
Related progress issue: https://progress.opensuse.org/issues/60209
> spec: Exclude flaky 17-labels_carry_over test

- assets/javascripts/job_templates.js
- assets/stylesheets/admin-pages.scss
- t/ui/13-admin.t
- templates/admin/job_template/index.html.ep
> Improve YAML editor

- .circleci/dependencies.txt
- cpanfile
- t/ui/15-admin-workers.t
Update **perltidy** dependency in `cpanfile` and add two spaces.
> Update perltidy to 20200110

- lib/OpenQA/WebAPI/Plugin/ObsRsync.pm
- lib/OpenQA/WebAPI/Plugin/ObsRsync/Task.pm
- t/api/14-plugin_obs_rsync.t
Gru mutex Leak might happend when ObsRsync plugin cannot find sync scripts.
Additionally move Plugin locking code into helpers.
> Fix ObsRsync mutex leak on errors

- lib/OpenQA/Schema/ResultSet/Assets.pm
- lib/OpenQA/WebAPI/Controller/Admin/Asset.pm
- t/15-assets.t
- templates/admin/asset/index.html.ep
See https://progress.opensuse.org/issues/61143
> Show asset stats during cleanup

- t/15-assets.t
See https://progress.opensuse.org/issues/61143#note-3
> Fix asset status test so it works when the cache file does not exist

- lib/OpenQA/Worker/Engines/isotovideo.pm
The info messages regarding asset downloads are printed to the autoinst log file as well. This makes it more consistent. Otherwise it looks like the error message is missing.
An example job which would benefit: https://openqa.opensuse.org/tests/1150659
> Log asset download error to autoinst log file

- openQA.spec
See https://progress.opensuse.org/issues/62510
> Add dependency to client so asset download via SSL works

- Makefile
- script/retry
Related progress issue: https://progress.opensuse.org/issues/53498
> Makefile: Add flag STABILITY_TEST for statistical robustness proofs

- lib/OpenQA/Worker/Job.pm
- t/full-stack.t
- t/lib/OpenQA/Test/FullstackUtils.pm
* t: Add more test strings
* t: Fix typos in full-stack
* Fix "Use of uninitialized value in numeric ne (!=)" in worker
* Fix "Can't use an undefined value as an ARRAY reference" in worker
> Fix warnings, harden full-stack.t

- lib/OpenQA/WebAPI/Plugin/ObsRsync.pm
Match logic with old rsync.pl implementation
> Adjust parsing of project state in ObsRsync Plugin

- lib/OpenQA/Setup.pm
- t/config.t
This fix unblocks functionality provided in #2465
> Read all keys from ini section if none is defined

- lib/OpenQA/Schema/Result/JobGroups.pm
- lib/OpenQA/Schema/ResultSet/JobTemplates.pm
- public/schema/JobTemplates-01.yaml
- t/16-utils-job-templates.t
- t/api/08-jobtemplates.t
- t/data/job-templates/openqa-null.yaml
We create a special empty testsuite in that case.
Issue: https://progress.opensuse.org/issues/62738
> Support 'testsuite: null' in jobtemplates

- Makefile
- openQA.spec
- systemd/openqa-enqueue-asset-and-result-cleanup.service
- systemd/openqa-enqueue-asset-and-result-cleanup.timer
- systemd/openqa-enqueue-asset-cleanup.service
- systemd/openqa-enqueue-asset-cleanup.timer
- systemd/openqa-enqueue-result-cleanup.service
- systemd/openqa-enqueue-result-cleanup.timer
- systemd/openqa-webui.service
see https://github.com/os-autoinst/openQA/pull/2710#issuecomment-580181673
> Run limit results/screenshots/logs job less often

- assets/javascripts/job_templates.js
- t/ui/13-admin.t
Fixes: [poo#57170](https://progress.opensuse.org/issues/57170)
> Reset the editor to the minimum viable YAML if empty

- lib/OpenQA/Schema/Result/Jobs.pm
- lib/OpenQA/WebSockets/Controller/Worker.pm
- lib/OpenQA/Worker.pm
- lib/OpenQA/Worker/CommandHandler.pm
- lib/OpenQA/Worker/Job.pm
- lib/OpenQA/Worker/WebUIConnection.pm
- t/05-scheduler-full.t
- t/24-worker-jobs.t
- t/24-worker-overall.t
- t/24-worker-webui-connection.t
- t/27-websockets.t
- t/api/04-jobs.t
- t/lib/OpenQA/Test/Utils.pm
see https://progress.opensuse.org/issues/62984
> Improve job scheduling and state tracking and related tests

- lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
Files with missing final linebreaks can cause problems (or at least
other code has to do more work to deal with it)
> Add final linebreak to jobtemplate yaml

- lib/OpenQA/Utils.pm
- t/16-utils.t
- t/api/04-jobs.t
- t/ui/18-tests-details.t
- templates/webapi/test/module_table.html.ep
Related: https://github.com/os-autoinst/openQA/pull/2654#issuecomment-575066593
> Improve the format of execution time

- assets/stylesheets/admin-pages.scss
See https://progress.opensuse.org/issues/63098
> Make help icon after search field fully clickable

- script/openqa-clone-custom-git-refspec
- t/40-script_openqa-clone-custom-git-refspec.t
This reverts commit 1e88ba5020916f26607ec68a7b14a2f2e8e4f10a.
> Revert "Have openqa-clone-custom-git-refspec parse PR for test URLs"

- t/api/08-jobtemplates.t
The test was relying on the YAML validation happening in a certain order which is apparently not always the case.
> Fix random failures in t/api/08-jobtemplates.t

- Makefile
- lib/OpenQA/Schema/ResultSet/Comments.pm
- lib/OpenQA/Task/Bug/Limit.pm
- lib/OpenQA/WebAPI/Controller/API/V1/Bug.pm
- lib/OpenQA/WebAPI/Plugin/Gru.pm
- openQA.spec
- systemd/openqa-enqueue-bug-cleanup.service
- systemd/openqa-enqueue-bug-cleanup.timer
- systemd/openqa-webui.service
- t/25-bugs.t
Ticket: https://progress.opensuse.org/issues/51923
> Add GRU task "limit_bugs" to cleanup orphaned bugs

- lib/OpenQA/WebAPI/Plugin/ObsRsync.pm
Need to support expression like Build0204 for SUSE:SLE-12-SP5:Update:Products:SLERT
> Tweak Build regexp in ObsRsync

- lib/OpenQA/WebAPI/Controller/Step.pm
- t/ui/03-source.t
* Simplify "src" method showing source code of test modules
* t: Fix and re-enable ui/03-source.t
> Fix and re-enable ui/03-source.t, simplify src method

- lib/OpenQA/WebAPI/Controller/Step.pm
- t/ui/03-source.t
Followup to 3c4cceefe.
Related progress issue: https://progress.opensuse.org/issues/54965
> Fix source code remote path for optional .git github links

- lib/OpenQA/WebAPI/Controller/Step.pm
- t/testresults/00099/00099938-opensuse-Factory-DVD-x86_64-Build0048-doc/vars.json
- t/ui/03-source.t
Related progress issue: https://progress.opensuse.org/issues/54965
> Use unique git hash from vars.json for src links when possible

- lib/OpenQA/Scheduler/Model/Jobs.pm
- lib/OpenQA/Schema/Result/Jobs.pm
- lib/OpenQA/WebAPI/Controller/API/V1/Worker.pm
- t/05-scheduler-full.t
- t/20-stale-job-detection.t
see particular commit messages
> Misc scheduling improvements

- lib/OpenQA/Utils.pm
- lib/OpenQA/Worker/WebUIConnection.pm
As reported in https://codecov.io/gh/os-autoinst/openQA
> Delete unused and uncovered methods

- systemd/openqa-enqueue-bug-cleanup.timer
https://progress.opensuse.org/issues/51923
> Fix openqa-enqueue-bug-cleanup.timer description

- lib/OpenQA/Scheduler/Model/Jobs.pm
- lib/OpenQA/Schema/Result/Jobs.pm
- lib/OpenQA/WebSockets.pm
- lib/OpenQA/Worker/CommandHandler.pm
- t/05-scheduler-full.t
- t/38-workers-table.t
* Improve logging, error handling and notes for worker-server connection
* Stop the worker as usual when handling 'incompatible' command
> Some minor corrections and improvements based on #2750

- lib/OpenQA/CacheService/Client.pm
- t/05-scheduler-full.t
- t/33-developer_mode.t
- t/full-stack.t
- t/lib/OpenQA/SeleniumTest.pm
- t/lib/OpenQA/Test/Database.pm
- t/lib/OpenQA/Test/FullstackUtils.pm
- t/lib/OpenQA/Test/Utils.pm
* Move setup code to test utilities to be able to re-use it elsewhere
* Simplify database setup 
* Avoid some code duplication
* Remove dead code
* Also see particular commit messages
> Refactor setup of fullstack tests

- .circleci/config.yml
See https://github.com/os-autoinst/openQA/pull/2786#issuecomment-592484089
> Make "developer" test as unstable based on recent results

- script/openqa-clone-job
- t/40-openqa-clone-job.t
- t/40-script_load_templates.t
- t/40-script_openqa-clone-custom-git-refspec.t
- t/lib/OpenQA/Test/Utils.pm
- t/testrules.yml
* Add test for "openqa-clone-job"
* t: Extract functions "run_cmd"/"test_cmd" for reuse in script tests
> Extract run_cmd/test_cmd for tests; Add test for openqa-clone-job

- lib/OpenQA/Schema/Result/Jobs.pm
- t/15-assets.t
See https://progress.opensuse.org/issues/34783#note-21
> Avoid warning about missing UEFI_PFLASH_VARS asset

- cpanfile
- lib/OpenQA/Task/Job/Limit.pm
- openQA.spec
- t/42-screenshots.t
- t/lib/OpenQA/Test/Utils.pm
Fixes: [poo#55922](https://progress.opensuse.org/issues/55922)
> Split minion job for limiting screenshots and run it less often

- lib/OpenQA/WebAPI.pm
While tracking down an unrelated bug i noticed that our route tree had repetitive branches, meaning the same `/admin` path for example had to be matched more than once for every request. That's rather inefficient.
> Speed up route matching

- t/14-grutasks.t
https://app.circleci.com/jobs/github/os-autoinst/openQA/15590 showed that
t/14-grutasks.t was taking 519s (!) to complete , This was not confirmed when
running normal tests locally. In my not so fast environment the test repeatedly
takes about 16s (only). This could explain why "t" seems to take comparably
longer in the recent past. This appears to be a performance regression. I
recorded profiling data locally with
```
PERL5LIB=lib:$PERL5LIB perl -d:NYTProf t/14-grutasks.t
nytprofhtml --open
```
This showed that the biggest time impact is in
```
130 1   1   134s    134s                       Minion::Job::CORE:waitpid (opcode)
```
which I understand as that we simply wait for 130 minion jobs to
succeed. The hypothesis was that when trying to collect coverage data we
call code for every …
> t: Fix grutasks taking excessively wrong while gathering coverage data

- lib/OpenQA/Utils.pm
- lib/OpenQA/Worker/Job.pm
- lib/OpenQA/Worker/Settings.pm
- t/24-worker-jobs.t
- t/24-worker-settings.t
- t/lib/OpenQA/Test/Utils.pm
This helps to provide consistent, reproducible coverage for code that
seems to have been covered only by the full stack test but not
reproducible causing flaky coverage reports, e.g. by circleci+codecov.
> t: Add explicit coverage for "worker stopping while uploading"

- t/42-screenshots.t
Because one cleanup task has been running for 8 hours on o3 I was suspicious that the range might not actually be considered by the splitted cleanup tasks.
> Check whether screenshot cleanup tasks only clean their range

- lib/OpenQA/WebAPI/Controller/Admin/Needle.pm
- t/ui/21-admin-needles.t
There is a bug in PR #2738. If the symlink needle is not loaded with the
real needle file together, the last seen and last match of the symlink
needle are still 'Never'.
Related ticket: https://progress.opensuse.org/issues/53762#note-9
> Fix the bug that only dereference the symlink needle in one page

- lib/OpenQA/Scheduler/Model/Jobs.pm
- t/05-scheduler-dependencies.t
This helps with flaky coverage reports.
> Add explicit test coverage for OpenQA::Scheduler::Model::Jobs::_pick_siblings_of_running

- script/check_dependencies
- script/create_admin
- script/initdb
- script/openqa
- script/openqa-livehandler
- script/openqa-scheduler
- script/openqa-validate-yaml
- script/openqa-websockets
- script/openqa-workercache
- script/upgradedb
- script/worker
Scripts might be called from /usr/bin and are linking to
../share/openqa/script/...
> Fix use lib in script/*

- lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
- lib/OpenQA/Worker/WebUIConnection.pm
- t/24-worker-webui-connection.t
* Slightly simplify code WebAPI::Controller::API::V1::Job and Worker::WebUIConnection
* Mark uncoverage subroutine in OpenQA::Worker::WebUIConnection
* t: Slighty simplify t/24-worker-webui-connection.t
* t: Add explicit to stabilize test coverage for OpenQA::Worker::WebUIConnection
* t: Fix warning '"my" variable %job_info masks earlier declaration'
> More coverage improvements

- lib/OpenQA/WebAPI/Plugin/ObsRsync.pm
- lib/OpenQA/WebAPI/Plugin/ObsRsync/Controller/Folders.pm
- lib/OpenQA/WebAPI/Plugin/ObsRsync/Controller/Gru.pm
- t/01-compile-check-all.t
- t/api/14-plugin_obs_rsync.t
- t/data/openqa-trigger-from-obs/BatchedProj/.api_repo
- t/data/openqa-trigger-from-obs/Proj1/.api_repo
- t/data/openqa-trigger-from-obs/Proj2/.api_package
- t/ui/27-plugin_obs_rsync_obs_status.t
- t/ui/27-plugin_obs_rsync_status_details.t
* Let configure OBS repositories per project;
* Use configured OBS repository in API request for checking dirty status; 
* Add api route to return json with all configured OBS (project, repository) pairs;
* Add optional repository parameter to to sync call to properly react on which repository of OBS project must be synced.
> Obs rsync list of projects

- lib/OpenQA/Schema/ResultSet/DeveloperSessions.pm
- lib/OpenQA/WebAPI/Controller/Running.pm
- t/34-developer_mode-unit.t
When refactoring the fullstack test I did a mistake which uncovered that two error conditions in the live/developer mode code aren't well handled so far. This is an attempt to improve it. I've only tested this via the wrongly configured fullstack test so far.
> Handle web socket errors in live/developer mode code

- Makefile
We have "style checks" or static tests that are called by "prove", i.e.
t/00-tidy.t and t/01-compile-check-all.t, and we have independant tools,
i.e. shellcheck, yamllint and also perlcritic. These had been called in
"checkstyle" and tests called by "prove" have either been called
implicitly when calling all tests by prove without test selection
arguments or explicitly selected, e.g. as done by our circle CI tests.
As we moved the circle CI test selections into named Makefile targets we
ended up with "test-checkstyle" that sounds too similar to "checkstyle"
so that the scope for each was not clear.
This commit tries to improve that situation by putting all static tests
that are not called into a sub-target "test-checkstyle-standalone",
moves the call to tidy/compile with prove selection …
> Makefile: Separate scope of "checkstyle" and "test-checkstyle" for clarity

- lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
- t/api/08-jobtemplates.t
The last known state may mismatch if it was saved before a trailing newline started to be added automatically.
Related: [poo#63136](https://progress.opensuse.org/issues/63136)
The newline handling was introduced in #2729 and should be considered a regression.
> Take automatically added newline into account for the reference

- Makefile
As https://progress.opensuse.org/issues/63985 showed it can happen that
tests increase in the run time they take without us noticing at the time
when a change is introduced. Would be good if we can prevent tests
taking significantly longer than they did before.
With this commit significant increases of test run time can be caught
when running tests locally on a global level as well as on the level of
test groups which is also effective for circle CI. Current timeout
values are a conservative limit rounded up from current run times on
circle CI which seems to provide reliable and reproducible test run
times.
The timeout value is scaled with the number of applied retries as well.
Related progress issue: https://progress.opensuse.org/issues/64216
> Makefile: Prevent unexpected self-test run time increases with timeouts

- lib/OpenQA/Schema/Result/Jobs.pm
- lib/OpenQA/Schema/ResultSet/Jobs.pm
- lib/OpenQA/UserAgent.pm
- lib/OpenQA/Utils.pm
- lib/OpenQA/WebAPI/Auth/OpenID.pm
- t/05-scheduler-dependencies.t
- t/api/03-auth.t
- t/ui/01-list.t
Although each may not be fundamentally evil it can lead to surprises that are perhaps best avoided.
- `each` is never sorted
- The iterator may get stuck
> Convert uses of `each` to `foreach`

- lib/OpenQA/Schema/Result/Jobs.pm
- lib/OpenQA/Schema/ResultSet/Screenshots.pm
Related progress issue: https://progress.opensuse.org/issues/60923
> Extract common screenshot DB insertion function

- lib/OpenQA/WebAPI.pm
- lib/OpenQA/WebAPI/Controller/API/V1/Asset.pm
- t/api/02-assets.t
All arguments are given in the path so we should actually rely on the routes failing with a 404.
See: [poo#64075](https://progress.opensuse.org/issues/64075)
> Validation for Asset controller

- lib/OpenQA/Schema/Result/JobModules.pm
- lib/OpenQA/Schema/Result/Jobs.pm
* Make hash with MD5 sums directly instead of using temporary array
* Avoid unnecessary nesting
---
I came up with this when trying to understand the screenshot upload to account screenshot sizes correctly.
> Refactor saving details/screenshots

- lib/OpenQA/Schema/ResultSet/Bugs.pm
- lib/OpenQA/WebAPI/Controller/API/V1/Bug.pm
- t/api/11-bugs.t
Related: [poo#64075](https://progress.opensuse.org/issues/64075)
> Validate parameters passed to bug API routes

- lib/OpenQA/Schema/Result/JobModules.pm
- lib/OpenQA/Schema/Result/Jobs.pm
- lib/OpenQA/Worker/Job.pm
- t/24-worker-jobs.t
- t/api/04-jobs.t
See https://progress.opensuse.org/issues/64809
> Prevent uploading non-screenshot results twice

- t/ui/10-tests_overview.t
As observed in
https://app.circleci.com/pipelines/github/os-autoinst/openQA/2016/workflows/2ebf3ada-443f-47ea-b9a3-720438e5cb9c/jobs/19142/parallel-runs/0/steps/0-108
> t: Fix sporadic failure in 10-tests_overview.t

- docs/Installing.asciidoc
Related progress issue: https://progress.opensuse.org/issues/41408
> docs: Mention the importance of synchronized clocks for remote worker machines

- lib/OpenQA/Schema/Result/Jobs.pm
- t/10-jobs.t
See https://progress.opensuse.org/issues/64574
> Account freed disk space when deleting logs

- lib/OpenQA/Schema/Result/Jobs.pm
- t/15-assets.t
See https://progress.opensuse.org/issues/34783#note-30
> Allow restarting jobs with empty assets (instead of showing error)

- templates/webapi/test/video.html.ep
See https://progress.opensuse.org/issues/65426
> Prevent warning when showing video without t parameter

- t/api/04-jobs.t
See https://github.com/os-autoinst/openQA/pull/2920#issuecomment-611486279
> Add explicit API test for obsoleting job

- assets/javascripts/running.js
- assets/javascripts/test_result.js
See particular commit messages and https://progress.opensuse.org/issues/32611 and
the https://progress.opensuse.org/issues/65402.
> Refresh details page only when the job state changes

- t/full-stack.t
- t/lib/OpenQA/SeleniumTest.pm
- t/lib/OpenQA/Test/FullstackUtils.pm
- t/ui/12-needle-edit.t
* t: Reduce sleep time in "schedule_one_job" to save testing time
* t: Extract method "find_status_text" for full stack utils
* t: Improve test stack report level for 'wait_for_result_panel'
> Improve full-stack test

- lib/OpenQA/Worker/Engines/isotovideo.pm
- t/24-worker-engine.t
* Add simple start-up smoke test for worker caching
> Cover asset_caching by tests

- tools/retry
* Start with 1 to reach N of N in the end
> tools: Improve output of retry

- lib/OpenQA/JobSettings.pm
- lib/OpenQA/Schema/Result/ScheduledProducts.pm
- lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
- t/api/04-jobs.t
Reverts os-autoinst/openQA#2931 due to https://progress.opensuse.org/issues/65750
> Revert "Extract duplicated code from generating job settings"

- t/ui/13-admin.t
- t/ui/15-admin-workers.t
- t/ui/27-plugin_obs_rsync_status_details.t
* t: Stabilize ui/15-admin-workers.t
* t: Stabilize ui/27-plugin_obs_rsync_status_details.t
* t: Stabilize ui/13-admin.t
> Stabilize more UI tests

- lib/OpenQA/WebAPI/Controller/API/V1/Comment.pm
- t/api/09-comments.t
See: [poo#64075](https://progress.opensuse.org/issues/64075)
> Validate parameter passed to comment API routes

- lib/OpenQA/Worker/Job.pm
- t/24-worker-jobs.t
- It is no error for the file to be absent
- Parsing errors are caught and log a warning
See os-autoinst/os-autoinst#1383 for the change to the baseclass.
Fixes: [poo#64857](https://progress.opensuse.org/issues/64857)
> Pick up extended reason from state file if available

- lib/OpenQA/Client/Archive.pm
While working on #2859 i noticed that the `--with-thumbnails` option of the `client --archive` feature did nothing. The code to make it work was already in place though, so i just fixed it. And while i was at it i've also cleaned up the code a little bit.
> Fix --with-thumbnails option of client --archive feature

- openQA.spec
Issue: https://progress.opensuse.org/issues/56525
Related: #2934
> Dependencies: Remove commas from requirements in spec

- openQA.spec
Issue: https://progress.opensuse.org/issues/56525
Related: #2934
This makes it easier to see diffs in the future
> spec: Sort dependencies

- t/lib/OpenQA/Test/Case.pm
- t/lib/OpenQA/Test/Testresults.pm
- t/ui/02-csrf.t
- t/ui/04-api_keys.t
- t/ui/05-auth.t
- t/ui/09-admin_creation.t
- t/ui/09-users-list.t
- t/ui/16-tests_job_next_previous.t
- t/ui/20-bugzilla-links.t
- t/ui/22-job_group_order.t
- t/ui/26-jobs_restart.t
Seems the last time I used a script that missed some cases.
> Update all overlooked old copyright notices

- t/api/04-jobs.t
Also add more descriptions and replace comments with test messages.
> Refactor jobs tests into subtests

- lib/OpenQA/WebAPI/Auth/OpenID.pm
- lib/OpenQA/WebAPI/Controller/Session.pm
* Simplify WebAPI::Auth::OpenID
* Simplify WebAPI::Controller::Session
* Remove unused import in OpenQA::WebAPI::Controller::Session
> Slightly simplify OpenID modules

- t/33-developer_mode.t
- t/deploy.t
- t/full-stack.t
- t/lib/OpenQA/Test/Database.pm
This simplifies the code and improves the feedback in case of errors.
> Use more Mojo::File in t/full-stack.t

- t/api/04-jobs.t
- Add unit test check for post result
- Add check for emitted event
While working on #2935 I thought to add missing coverage for the result of the post call and the `job_done` event. Turns out it doesn't work, even after subtracting all of my changes.
> Validate job done event

- assets/javascripts/running.js
- assets/javascripts/test_result.js
- assets/stylesheets/test-details.scss
- lib/OpenQA/Schema/Result/Jobs.pm
- lib/OpenQA/WebAPI.pm
- lib/OpenQA/WebAPI/Controller/Running.pm
- lib/OpenQA/WebAPI/Controller/Test.pm
- t/full-stack.t
- t/lib/OpenQA/Test/FullstackUtils.pm
- templates/webapi/layouts/bootstrap.html.ep
- templates/webapi/test/autoinst_log_within_details.html.ep
- templates/webapi/test/infopanel.html.ep
- templates/webapi/test/result.html.ep
See https://progress.opensuse.org/issues/32611
> Avoid refreshing the whole test details page on job state transitions

- docs/Contributing.asciidoc
Issue: https://progress.opensuse.org/issues/56525
> docs: Update Contributing docs regarding dependencies

- assets/javascripts/running.js
See https://progress.opensuse.org/issues/66622
> Fix autoscroll checkbox in live log

- assets/javascripts/running.js
* Context of the regressions is https://progress.opensuse.org/issues/65402
> Fix a few regressions on the test details page

- t/ui/27-plugin_obs_rsync_status_details.t
I couldn't reproduce problems which occasionally happen in stress tests.
But if gru is very slow, then java script updates in ObsRsync projects list may reach timeouts and page refresh is needed to see updated info.
This patch attempts to adjust tests to reflect such scenario.
> Try to stabilize ObsRsync unit test during stresstest

- t/32-openqa_client.t
* Reduce duplication
* Add more unique helpful test description strings
* Extract helper method
* Fix language
* Improve runtime
> t: Improve t/32-openqa_client.t

- assets/javascripts/audit_log.js
- lib/OpenQA/Schema/Result/ScheduledProducts.pm
- lib/OpenQA/WebAPI.pm
- lib/OpenQA/WebAPI/Controller/Admin/AuditLog.pm
- lib/OpenQA/WebAPI/Plugin/Helpers.pm
- t/ui/17-product-log.t
- t/ui/18-tests-details.t
- t/ui/25-developer_mode.t
- templates/webapi/admin/audit_log/productlog.html.ep
- templates/webapi/test/infopanel.html.ep
See https://progress.opensuse.org/issues/65142 and particular commit messages
> Improve UI of scheduled products

- lib/OpenQA/WebAPI/Controller/API/V1/Worker.pm
- lib/OpenQA/Worker.pm
- t/24-worker-overall.t
possible problems related to supported/unsupported instructions.
> Add cpu flags infos to help to debug

- assets/javascripts/audit_log.js
- assets/stylesheets/admin-pages.scss
- assets/stylesheets/test-details.scss
- t/ui/17-product-log.t
- templates/webapi/test/settings.html.ep
* @asdil12 Contains the change to avoid white-spaces
> Tweak UI (mainly scheduled products table)

- assets/javascripts/test_result.js
- lib/OpenQA/WebAPI/Controller/Running.pm
- t/26-controllerrunning.t
See https://progress.opensuse.org/issues/65402
> Fix bugs related to recent changes on the test details page

- t/api/04-jobs.t
Since there is complex parameters replacement check in `40-job_settings.t`,
remove the same test code from `04-jobs.t`.
Put the check for `+` handling and parameters replacement together to
reduce post times.
See: https://github.com/os-autoinst/openQA/pull/3049#pullrequestreview-407768184
> Simplify test code in generating jobs settings

- templates/webapi/branding/openSUSE/external_reporting.html.ep
This should be configured elsewhere, eg in job groups.
> Add MicroOS bug reporting URL

- script/configure-web-proxy
- script/fetchneedles
- script/openqa-bootstrap
- script/openqa-bootstrap-container
- script/setup-db
Related progress issue: https://progress.opensuse.org/issues/65933
> Add '--help' for script/configure-web-proxy

- public/schema/JobTemplates-01.yaml
- t/api/08-jobtemplates.t
- t/data/08-hidden-keys.yaml
Fixes: [poo#66781](https://progress.opensuse.org/issues/66781)
~Alternative to #3093~
> Allow hidden keys in job template YAML

- lib/OpenQA/CacheService/Model/Cache.pm
- lib/OpenQA/CacheService/Model/Downloads.pm
This is a fairly harmless change to try and mitigate conditions that could lead to `DBD::SQLite::st execute failed: database disk image is malformed` errors. I'm not sure if it will change anything at all, but it's probably worth a try.
In theory all SQLite write operations automatically trigger an exclusive lock, and are surrounded by an implicit transaction. But all it takes is a small bug in `DBD::SQLite` to break that theoretical protection, and we've seen enough corrupted SQLite files in recent months to suggest there is a real problem somewhere.
While there is nothing to be found on this subject in the SQLite documentation, i did encounter quite a few stories suggesting that explicit locks might mitigate SQLite file corruption problems.
Progress: …
> Try using exclusive locks explicitly to prevent SQLite file corruption

- t/05-scheduler-full.t
The commit 74f414368 added additional test steps to
t/05-scheduler-full.t but also changed behaviour that dead workers are
handled differently. To fix sporadic problems that jobs are allocated to
the old worker instances which do not actually exist anymore this commit
ensures that the workers are handled as "dead workers" with setting the
last update to be longer ago in time. Also adding calls to
`dead_workers` after stopping worker instances.
Related progress issue: https://progress.opensuse.org/issues/59043
> t: Fix a sporadic problem in 05-scheduler-full about jobs assigned to dead workers

- lib/OpenQA/Schema/Result/Jobs.pm
- t/28-logging.t
- t/basic.t
- t/lib/OpenQA/Test/Utils.pm
* t: Simplify basic.t
* t: Output port for scheduler service as well
* Improve debug message for job-worker assignment
* t: Add trivial test for OpenQA::Log::get_channel_handle coverage
* t: Simplify stdout matching in 28-logging.t
* t: Fix warning "Prototype mismatch: sub Time::HiRes::gettimeofday"
> Various enhancements

- lib/OpenQA/WebAPI/Auth/OpenID.pm
This helps debugging problems like https://progress.opensuse.org/issues/67381.
> Log errors when claiming OpenID identity

- t/42-screenshots.t
[2020-05-29 08:54:48.09714] [8050] [debug] [pid:8050] creating foo
[2020-05-29 08:54:48.09891] [8050] [debug] [pid:8050] creating bar
> Capture screenshot created message in screenshot test

- assets/javascripts/running.js
- assets/javascripts/test_result.js
- lib/OpenQA/WebAPI/Controller/Running.pm
- lib/OpenQA/WebAPI/Controller/Test.pm
- lib/OpenQA/Worker/Job.pm
- t/24-worker-jobs.t
- templates/webapi/test/result.html.ep
See https://progress.opensuse.org/issues/56591 and particular commit messages
> Keep 'live' tab shown while uploading for improved feedback

- Makefile
- t/05-scheduler-full.t
- t/33-developer_mode.t
- t/43-scheduling-and-worker-scalability.t
- t/full-stack.t
- t/lib/OpenQA/Test/Utils.pm
> Fix scheduler test instabilities

- lib/OpenQA/Worker/Job.pm
> Simplify Worker::Job and t/05-scheduler-full

- lib/OpenQA/Worker/Job.pm
- t/24-worker-jobs.t
See: https://progress.opensuse.org/issues/58700
Verify run: 
http://10.67.19.103/tests/119/file/worker-log.txt  This is a static test schedule, there is no `Test schedule has changed ..` in worker log.
http://10.67.19.103/tests/118 This job will add test modules during running. So there is one record `Test schedule has changed ...` in worker log.
> Only reload test schedule when test_order.json has been changed

- .circleci/unstable_tests.txt
See https://app.circleci.com/pipelines/github/os-autoinst/openQA/3239/workflows/4d5ca036-cb47-4a8d-8c63-6dcbec948020/jobs/30925/steps
Related progress issue: https://progress.opensuse.org/issues/59043
> Mark flaky t/ui/26-jobs_restart.t as unstable

- t/basic.t
E.g. see https://app.circleci.com/jobs/github/os-autoinst/openQA/31282
> t: Attempt to fix sporadic timeout in basic.t in circleci

- Makefile
- docs/Contributing.asciidoc
> Ease using `make test` with Docker and improve related documentation

- t/ui/02-csrf.t
- t/ui/02-list-group.t
- t/ui/03-source.t
- t/ui/04-api_keys.t
- t/ui/05-auth.t
- t/ui/06-operator_links.t
- t/ui/07-file.t
- t/ui/09-admin_creation.t
- t/ui/09-users-list.t
- t/ui/10-tests_overview.t
- t/ui/12-needle-edit.t
- t/ui/13-admin-no-login.t
- t/ui/13-admin.t
- t/ui/14-dashboard-parents.t
- t/ui/14-dashboard.t
- t/ui/15-admin-workers.t
- t/ui/15-comments.t
- t/ui/16-tests_dependencies.t
- t/ui/16-tests_job_next_previous.t
- t/ui/17-product-log.t
- t/ui/18-tests-details.t
- t/ui/19-tests-links.t
- t/ui/20-bugzilla-links.t
- t/ui/21-admin-needles.t
- t/ui/22-job_group_order.t
- t/ui/23-audit-log.t
- t/ui/24-feature-tour.t
- t/ui/27-plugin_obs_rsync.t
- t/ui/27-plugin_obs_rsync_gru.t
- t/ui/27-plugin_obs_rsync_obs_status.t
Based on #3214 which introduces the concept of selecting specific fixtures to use.
> Narrow down fixtures needed by ui tests

- docs/Contributing.asciidoc
* Update how to update os-autoinst's dependencies
* Update remarks regarding CI containers
> Update documentation regarding dependency handling

- dependencies.yaml
See also https://github.com/os-autoinst/os-autoinst/pull/1455
This needs to be merged before the update-deps script is made a symlink (see #3231)
> deps: Make cpanfile targets configurable

- lib/OpenQA/WebAPI.pm
by loading plugins before returning early.
> Fix showing help for commands loaded via plugins

- lib/OpenQA/CacheService/Controller/API.pm
- t/25-cache-client.t
This is a followup to #3211 with two additional cache service failure cases i found while testing on the staging machines. The patch ensures that failed cache service Minion jobs are logged just like any other cache service API exception. Previously you would just not see anything useful logged at all and had to dig through the SQLite database to find out what happened.
> Handle failed cache service Minion jobs gracefully

- tools/update-deps
Followup-To: #3232
Since symlinking the script from os-autoinst (See #3231) does not work yet,
copy the file manually.
> deps: Copy update-deps from os-autoinst

- .mergify.yml
* mergify: Add additional automatic merge on special label
* mergify: Only merge automatically when there are no pending reviews
> mergify: no pending reviews + automatic merge on special label

- assets/stylesheets/admin-pages.scss
- templates/webapi/admin/needle/index.html.ep
- templates/webapi/admin/needle/needle_search.html.ep
* Use a uniform height
* Improve appearance on small screens/windows
* Simplify CSS code, remove some classes
---
Before:
After:
> Improve appearance of custom time filter in needles table

- lib/OpenQA/Script/CloneJob.pm
- t/09-job_clone.t
- t/35-script_clone_job.t
- t/40-openqa-clone-job.t
- Add a case for clone_job_get_job
- Also cover missing asset folder
- Use die to allow testing
> Test clone_job_get_job and error messages

- .mergify.yml
Also mention a link to the ticket that describes the setup.
> mergify: Wait for OBS Package Build as well after we have it back

- openQA.spec
- t/14-grutasks.t
* spec: Delete superfluous prove flag already included in PROVE_LIB_ARGS
* Delete obsolete OBS_RUN variable assignment
> OBS_RUN + PROVE_ARGS cleanup

- docs/Installing.asciidoc
- etc/openqa/openqa.ini
- lib/OpenQA/LiveHandler/Controller/LiveViewHandler.pm
- lib/OpenQA/Setup.pm
- lib/OpenQA/Task/Asset/Download.pm
- lib/OpenQA/Utils.pm
- lib/OpenQA/WebAPI/Controller/API/V1/Iso.pm
- lib/OpenQA/WebAPI/Plugin/AuditLog.pm
- t/14-grutasks.t
- t/api/02-iso-download.t
- t/api/04-jobs.t
- t/config.t
- t/data/41-audit-log/openqa.ini
Using `git ls-files | xargs sed -i -e 's/blacklist/blocklist/g' -e
's/whitelist/passlist/g'` following suggestions from
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=49decddd39e5f6132ccd7d9fdc3d7c470b0061bb
> Use inclusive terminology "blocklist/passlist"

- lib/OpenQA/Worker.pm
- t/05-scheduler-full.t
- t/lib/OpenQA/Test/Utils.pm
> Speedup t/05-scheduler-full

- assets/assetpack.def
- assets/javascripts/admin_api_keys.js
- lib/OpenQA/WebAPI/Plugin/REST.pm
- t/ui/13-admin.t
- templates/webapi/api_key/index.html.ep
> Allow adding API keys without expiration date via the UI

- assets/javascripts/overview.js
- assets/javascripts/tests.js
- lib/OpenQA/CLI.pm
- lib/OpenQA/CLI/api.pm
- lib/OpenQA/Schema/Result/Jobs.pm
- lib/OpenQA/WebAPI/Controller/API/V1/Search.pm
- templates/webapi/test/tr_job_result.html.ep
See the particular commit messages
Fixes: [poo#70252](https://progress.opensuse.org/issues/70252)
> Misc small improvements

- lib/OpenQA/WebAPI/Controller/API/V1/Search.pm
- t/api/15-search.t
- templates/webapi/search/search.html.ep
- Search job templates
- Render one or more templates and descriptions per job group
See: [poo#34486](https://progress.opensuse.org/issues/34486)
> Search job templates by name or description

- tools/tidy
So that it can be made equal to os-autoinst/tools/tidy
Issue: https://progress.opensuse.org/issues/70384
PR for os-autoinst: https://github.com/os-autoinst/os-autoinst/pull/1518
> Refactor tools/tidy

- t/04-scheduler.t
* Use subtests
* Use more compact style
* Use constants for job states and results
* Remove obsolete comments
* Avoid repetition of $schema->resultset('Jobs')
> Improve coding style in t/04-scheduler.t

- lib/OpenQA/WebAPI/Controller/API/V1/Table.pm
- t/api/05-machines.t
- t/api/06-products.t
- t/api/07-testsuites.t
> Always emit table_create with an ID

- docs/Contributing.asciidoc
Observed an error myself and I think this hint should help.
> docs: Add simple hint about sass

- .mergify.yml
Reverts os-autoinst/openQA#3386
> Revert "ci: Temporarily exclude broken OBS checks" as problem was fixed on download.o.o

- lib/OpenQA/WebAPI/Controller/API/V1/Search.pm
- t/api/15-search.t
When adding a test suite to a job group directly without specifying an
alias name, the job template's name is null. When searching the job template
by test suite name, the job template cannot be found.
See [poo#70840](https://progress.opensuse.org/issues/70840)
> Support finding job template by test suite name

- lib/OpenQA/Scheduler.pm
- lib/OpenQA/Shared/GruJob.pm
- lib/OpenQA/Shared/Plugin/Gru.pm
- lib/OpenQA/WebAPI/Command/gru/run.pm
- t/15-assets.t
- t/20-stale-job-detection.t
See https://progress.opensuse.org/issues/71386
> Allow scheduler to enqueue finalize jobs tasks when marking stale job as incomplete

- t/25-cache-service.t
Fixes: [poo#71368](https://progress.opensuse.org/issues/71368)
> Be sure to stop services after cache service tests

- .circleci/config.yml
- Makefile
Related progress issue: https://progress.opensuse.org/issues/71449
> Include t/ in our code coverage to prevent test coverage loss

- t/full-stack.t
There's two cases where we either wait indefinitely or proceed regardless of file availability. Overall this makes the waits in the fullstack test more predictable and consistent.
- We get consistent timeouts
- Bail if the file or server never becomes available
See also #3394
> Use wait_for_or_bail_out in fullstack test

- t/full-stack.t
- t/lib/OpenQA/Test/FullstackUtils.pm
* Abort waiting for result panel when there's already a result (but not the
expected one)
* Print contents of result panel if waiting for result panel failed
* Print information about the current job as stored in the database if the
web UI does not show the expected result
> Improve feedback of fullstack test in case of failures

- t/api/02-iso-download.t
- t/api/04-jobs.t
- t/ui/26-jobs_restart.t
See
https://app.circleci.com/pipelines/github/os-autoinst/openQA/4289/workflows/42aaab1f-fb4c-42c4-9cfa-3f38ac6f6c7a/jobs/41116
and
https://app.circleci.com/pipelines/github/os-autoinst/openQA/4289/workflows/42aaab1f-fb4c-42c4-9cfa-3f38ac6f6c7a/jobs/41121
> t: Bump timeouts of recent failures

- t/api/08-jobtemplates.t
- t/api/14-plugin_obs_rsync.t
See https://app.circleci.com/pipelines/github/os-autoinst/openQA/4299/workflows/5d3155af-c445-468b-8401-d0e32ada618a/jobs/41221
> t: Bump timeouts of recent failure api/08-jobtemplates.t and api/14-plugin_obs_rsync.t

- t/01-compile-check-all.t
See https://app.circleci.com/pipelines/github/os-autoinst/openQA/4304/workflows/e2d756ee-d23c-4f2e-965f-b7d391263341/jobs/41276
> t: Bump timeout for compile check

- assets/javascripts/audit_log.js
- t/ui/23-audit-log.t
Requires:
- #3328
- #3356
- #3361
> Render links to items in the audit log

- lib/OpenQA/WebAPI/Controller/Admin/Workers.pm
See https://progress.opensuse.org/issues/71536
> Fix warning in controller for workers table

- t/11-commands.t
- t/lib/OpenQA/Test/Database.pm
Just create the necessary objects for testing.
> t: Optimize t/11-commands.t further with no database at all

- t/14-grutasks.t
There are error messages showing up when calling the test locally. This
output should be handled as we already do in other places using
Test::Output. The problem is not visible due to our current approach to
forward all output to an external artifact file within circleCI.
Related progress issue: https://progress.opensuse.org/issues/71926
> t: Catch unhandled output in t/14-grutasks.t

- t/api/04-jobs.t
Related progress issue: https://progress.opensuse.org/issues/72130
> t: Bump timeout for t/api/04-jobs.t

- lib/OpenQA/Task/Asset/Download.pm
- t/14-grutasks.t
Otherwise it just checks the first destination.
---
Just a small PR for fixing this check because I came across this problem when reading the download code. It is still a draft because tests should likely be extended/adapted.
> Fix check for existing assets if multiple asset destinations are specified

- .circleci/config.yml
Related progress issue: https://progress.opensuse.org/issues/67855
> ci: Try to avoid common download problems with a different time of day

- .circleci/build_cache.sh
- .circleci/build_dependencies.sh
- .circleci/build_local_docker.sh
- Makefile
- tools/retry
Related progress issue: https://progress.opensuse.org/issues/72316
> ci: Retry on temporary zypper repository refresh problems

- docs/Contributing.asciidoc
Related progress issue: https://progress.opensuse.org/issues/69157
> docs: Update contribution hints for package impact

- t/43-cli-archive.t
Just a few more tests for `openqa-cli archive` options.
> Test archive cli command options

- etc/openqa/workers.ini
This commit completes #3303 with the docuemntation to enable this feature and an example
> Document the configuration to enable the packages comparation feature

- assets/javascripts/feature.js
- lib/OpenQA/WebAPI/Controller/API/V1/Feature.pm
- t/full-stack.t
- t/ui/24-feature-tour.t
See particular commit messages and https://progress.opensuse.org/issues/73567
> Fix feature tour

- lib/OpenQA/Worker/Engines/isotovideo.pm
See: https://progress.opensuse.org/issues/73396
> Retry when rsync error code is 23

- t/14-grutasks.t
See https://progress.opensuse.org/issues/73126
> Prevent unhandled output in `t/14-grutasks.t`

- .circleci/build_cache.sh
- .circleci/build_dependencies.sh
- .circleci/build_local_docker.sh
- docker/devel:openQA:ci/base/Dockerfile
- docker/devel:openQA:ci/dependency_bot/Dockerfile
- docker/openqa_data/Dockerfile
- docker/travis_test/Dockerfile
- docker/webui/Dockerfile
- docker/worker/Dockerfile
Related progress issue: https://progress.opensuse.org/issues/69154
> Bump base OS version to Leap 15.2

- t/26-controllerrunning.t
- t/31-client_archive.t
See https://progress.opensuse.org/issues/73126#note-7
> Avoid unhandled output in 26-controllerrunning.t and 31-client_archive.t

- assets/javascripts/test_result.js
See https://progress.opensuse.org/issues/76741
> Fix help popup next to "Submit comment"

- lib/OpenQA/CacheService/Model/Cache.pm
- t/25-cache.t
I've tried quite a few variants of this on the staging machines, and this is the one that performed best for recovering from various cases of corrupted SQLite files on service restart.
Possible addition: The purge code could also make a copy of the corrupted database to `/tmp/cache.sqlite` (maybe there's a better location?) for later investigation.
Progress: https://progress.opensuse.org/issues/67000
> Recover from corrupted cache service SQLite files

- assets/javascripts/openqa.js
- t/ui/16-activity-view.t
Same as #3470, but with a timezone fix for Circle CI.
> activity view: Request events ordered by event ID

- lib/OpenQA/CacheService/Model/Cache.pm
- t/25-cache.t
* Prevents cases like https://progress.opensuse.org/issues/71827#note-11
where an asset is cleaned up to make space for itself
* Does not prevent cases when the asset is purged by another download job
> cache service: Exclude currently downloaded asset from the cleanup

- .gitignore
- Makefile
- docker/webui/Dockerfile
- openQA.spec
* .gitignore: Delete obsolete full-stack.d entry
* Delete old left-over db.sqlite file
> Delete obsolete gitignore entries and db.sqlite file

- codecov.yml
We are much closer to the impossible 100% :)
> Adapt codecov target to current coverage of 95%

- lib/OpenQA/Schema/Result/Jobs.pm
- lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
- t/api/04-jobs.t
see: https://progress.opensuse.org/issues/77215
> Show parent group name and id when getting job details

- t/lib/OpenQA/SeleniumTest.pm
See https://codecov.io/gh/os-autoinst/openQA/pull/3547/changes
> t: Mark uncoverable statement in OpenQA::SeleniumTest

- Makefile
See: https://progress.opensuse.org/issues/75370
> Makefile: Do not retry fullstack tests

- lib/OpenQA/CacheService.pm
- t/25-cache.t
* Alternative to #3586 implementing https://github.com/os-autoinst/openQA/pull/3586#discussion_r529520691a
* I personally would prefer it over #3586.
---
* via OPENQA_CACHE_SERVICE_SQLITE_JOURNAL_MODE
* WAL remains the default mode (Mojo::SQLite previously set it as default)
* journaling mode is now entirely controlled by our code (and not by
Mojo::SQLite)
* checkout the SQLite documentation for more information
* https://www.sqlite.org/pragma.html#pragma_journal_mode
* https://www.sqlite.org/wal.html#backwards_compatibility
> cache service: Allow setting the SQLite journaling mode

- lib/OpenQA/CacheService/Model/Cache.pm
Remove all uncovered error parsing and forwarding for exceptions where
we do not know if they ever happen in production. This brings up the
code statement coverage to 100% for the file
lib/OpenQA/CacheService/Model/Cache.pm
Related progress issue: https://progress.opensuse.org/issues/67000
> worker cache: Simplify error handling for uncovered, exceptional cases

- docs/Installing.asciidoc
Related progress issue: https://progress.opensuse.org/issues/43718
> docs: Mention Dockerfile based container prominently

- lib/OpenQA/Shared/Plugin/Gru.pm
- lib/OpenQA/Worker.pm
- t/33-developer_mode.t
* Simplify OpenQA::Worker::_handle_client_status_changed
* t: Slightly simplify 33-developer_mode.t
* Correct redundant newline in log_info in GRU
> Simplify OpenQA::Worker slightly, simplify 33-developer_mode.t

- t/25-cache-service.t
* t: Fix coverage of separate process in 25-cache-service.t
* t: Increase statement coverage ratio in 25-cache-service.t
* t: Delete unused function _port in 25-cache-client.t
> t: Increase statement coverage of 25-cache-service.t to reliable 100%

- lib/OpenQA/LiveHandler.pm
- lib/OpenQA/Utils.pm
- script/openqa
- script/openqa-cli
- script/openqa-livehandler
- script/openqa-scheduler
- script/openqa-websockets
- script/openqa-workercache
- t/44-scripts.t
- templates/webapi/not_found.html.ep
* See https://progress.opensuse.org/issues/81038
* See https://progress.opensuse.org/issues/81068
* See https://bugzilla.opensuse.org/show_bug.cgi?id=1180048
> Avoid using deprecated Mojolicious functions

- lib/OpenQA/Worker.pm
- lib/OpenQA/Worker/WebUIConnection.pm
- t/24-worker-overall.t
- t/24-worker-webui-connection.t
- t/lib/OpenQA/Test/Utils.pm
Based on #3640
---
It will look like this:
```
[warn] Worker cache not available: Cache service info error: Connection refused - checking again for web UI 'http://localhost:9526' in 100.00 s
```
See #3645
> Improve logging of availability error to show retry interval

- t/01-test-utilities.t
- t/04-scheduler.t
- t/05-scheduler-cancel.t
- t/05-scheduler-dependencies.t
- t/06-users.t
- t/15-assets.t
- t/16-utils-job-templates.t
- t/16-utils-runcmd.t
- t/16-utils.t
- t/24-worker-jobs.t
- t/24-worker-overall.t
- t/24-worker-webui-connection.t
- t/25-downloader.t
- t/26-controllerrunning.t
- t/30-test_parser.t
- t/33-developer_mode.t
- t/43-scheduling-and-worker-scalability.t
- t/deploy.t
- t/fake-isotovideo.pl
- t/full-stack.t
- t/ui/13-admin.t
- t/ui/14-dashboard-parents.t
- t/ui/14-dashboard.t
- t/ui/18-tests-details.t
* t: Refactor and mark multiple test modules for 100% statement coverage
* t: Use more concise one-line Selenium WDKeys init as well
* t: Use more concise one-line Selenium driver initialization (2nd)
> t: Refactor and mark multiple test modules for 100% statement coverage

- t/lib/OpenQA/Test/Utils.pm
Seen in https://codecov.io/gh/os-autoinst/openQA/pull/3652/changes
> t: Prevent unreliable coverage report on sleep line

- script/fetchneedles
See: https://progress.opensuse.org/issues/81180
> Clear any uncommitted changes that would prevent a rebase

- etc/openqa/openqa.ini
- lib/OpenQA/Setup.pm
- lib/OpenQA/WebAPI/Controller/Admin/Influxdb.pm
- t/api/13-influxdb.t
- t/config.t
Related: https://progress.opensuse.org/issues/70768
> Support filtering specified minion jobs

- script/openqa-bootstrap
Ticket: https://progress.opensuse.org/issues/81064
Verification: https://openqa.opensuse.org/tests/1589825
> Install qemu-hw-display-virtio-gpu in openqa-bootstrap

- lib/OpenQA/Worker.pm
* See https://progress.opensuse.org/issues/78390#note-38
* If this actually helps we could try the adjustments to underlying
Perl libraries mentioned in https://progress.opensuse.org/issues/78390#note-41
> Workaround getaddrinfo() being stuck in error state for 127.0.0.1

- templates/webapi/branding/openSUSE/external_reporting.html.ep
We have SLE Micro product which is different than OpenSUSE MicroOS
> Add SUSE Linux Enterprise Micro in the external reporting

- t/api/04-jobs.t
- t/ui/25-developer_mode.t
It failed recently on different PRs exceeding the timeout.
> Increase timeout of t/api/04-jobs.t

- lib/OpenQA/Utils.pm
- lib/OpenQA/Worker/Engines/isotovideo.pm
- t/24-worker-engine.t
- t/43-scheduling-and-worker-scalability.t
One commit is the same as #3604.
Another commit is used to fix the regression issue: https://github.com/os-autoinst/openQA/pull/3604#issuecomment-765888161
Verify run: http://10.67.19.103/tests/432
> Rework symlink CASEDIR and set values to relative path

- lib/OpenQA/Utils.pm
- lib/OpenQA/Worker/Engines/isotovideo.pm
- t/24-worker-engine.t
- t/43-scheduling-and-worker-scalability.t
Reverts os-autoinst/openQA#3696
Here is a case that I did not consider: https://openqa.opensuse.org/tests/1609706#
> Revert "Rework symlink CASEDIR and set values to relative path"

- t/full-stack.t
Sometimes the actual error message for the failed download is available and
therefore that message is logged (instead of the more generic one). The
reason should always contain the "Failed to download…" message so I'm
adding a check for that.
So far I've noticed that problem only when testing locally (to reproduce
https://progress.opensuse.org/issues/80800 which is **not** fixed by this
change).
> Fix problem in fullstack test leading to occasional failures

- t/ui/27-plugin_obs_rsync_status_details.t
The problem happens when gru is slow performing background task. It is reproducible by injecting sleep(2) into update_obs_builds_text().
Previously the test tried to refresh page in hope to get correct info. But that doesn't work for "obs_builds" column.
The fix performs correct UI action instead.
> Stabilize t/ui/27-plugin_obs_rsync_status_details

- lib/OpenQA/Scheduler.pm
- lib/OpenQA/Scheduler/Model/Jobs.pm
See: https://progress.opensuse.org/issues/88459#change-383696
> Make offset for scheduler's starvation protection configurable

- lib/OpenQA/Worker/Job.pm
Asset file is now readable from server side
https://progress.opensuse.org/issues/88347
> Fix local upload for larger assets

- assets/javascripts/needleeditor.js
- lib/OpenQA/Task/Needle/Save.pm
- lib/OpenQA/WebAPI/Controller/Step.pm
- t/16-utils-runcmd.t
- t/ui/12-needle-edit.t
- templates/webapi/step/edit.html.ep
See https://progress.opensuse.org/issues/88564
> Allow specifying a custom commit message in needle editor

- lib/OpenQA/Shared/Controller/Auth.pm
- t/api/03-auth.t
A personal access token can be constructed from existing API keys and secrets. The format is `USER:KEY:SECRET`.
This allows for other clients than OpenQA::Client to access the openQA API with authentication for operator and admin privileges. Since the token is submitted via Basic authentication, which pretty much all HTTP clients support, it is as easy as `curl -u kraih:KEY:SECRET ...` to use.
As a security precaution, personal access tokens are currently limited to HTTPS requests originating from any host, and HTTP requests originating from localhost. This will prevent API secrets from being sent in cleartext over the network.
Reverse proxy setups might need to add an `X-Forwarded-Proto: https` header to properly signal to the application server that the connection to the client is …
> Add personal access tokens as an alternative to X-API-* headers

- .circleci/ci-packages.txt
- .circleci/config.yml
- cpanfile
- dependencies.yaml
- dist/rpm/openQA.spec
See: [poo#88915](https://progress.opensuse.org/issues/88915)
> Use Codecovbash RPM instead of cpanm

- lib/OpenQA/Shared/Controller/Auth.pm
Small followup to #3757. Just splitting up the large auth method and changing the log level consistently to debug.
> Split up large auth method into multiple methods

- docs/Client.asciidoc
> Document personal access tokens

- lib/OpenQA/Schema/Result/Jobs.pm
- lib/OpenQA/Shared/Plugin/Gru.pm
- lib/OpenQA/Task/Job/Limit.pm
- lib/OpenQA/WebAPI/Command/gru/run.pm
- script/openqa-gru
* See particular commit message for details (it is maybe also easier to review the commits individually)
* Related ticket: https://progress.opensuse.org/issues/89224#note-7
> Adjust priorities of Minion tasks and enable use of "fast lane"

- dist/rpm/openQA.spec
This is a follow-up of https://github.com/os-autoinst/openQA/pull/3777
Build tested for SLE15-SP2/ https://build.opensuse.org/package/show/home:Guillaume_G:branches:devel:openQA/openQA
> Package auto-update part on openSUSE only

- .circleci/config.yml
- .github/workflows/check-containers.yml
- Makefile
- container/openqa/Dockerfile
- container/openqa_data/Dockerfile
- container/travis_test/Dockerfile
- container/webui/Dockerfile
- container/webui/Dockerfile-lb
- container/worker/Dockerfile
- tools/static_check_containers
Related progress issue: https://progress.opensuse.org/issues/88451
> Add static Dockerfile checks as in os-autoinst

- t/ui/27-plugin_obs_rsync_status_details.t
This is a followup to #3732 and should further stabilize the test results. Instead of just doing `find_element`/`sleep` we now use `wait_for_element`, like most other ui tests.
Progress: https://progress.opensuse.org/issues/89935
> Wait for the element instead of constantly refreshing the page

- lib/OpenQA/Worker.pm
- lib/OpenQA/Worker/Job.pm
- t/24-worker-jobs.t
- t/24-worker-overall.t
* PR for debugging https://progress.opensuse.org/issues/90152
* See particular commit messages for details
> worker: Improve logging and test

- lib/OpenQA/Utils.pm
- lib/OpenQA/Worker/Engines/isotovideo.pm
- t/24-worker-engine.t
- t/43-scheduling-and-worker-scalability.t
Compare #3712, this pull request includes a switch to enable the symlink feature.
The related code can be found in the separate commit.
> Add a switch to enable the symlink feature

- t/24-worker-jobs.t
See https://progress.opensuse.org/issues/90314
> Fix unhandled output in worker job test

- lib/OpenQA/WebAPI/Plugin/ObsRsync/templates/ObsRsync_folder.html.ep
- lib/OpenQA/WebAPI/Plugin/ObsRsync/templates/ObsRsync_index.html.ep
* Fix syntax errors
* Do not nest block elements into paragraphs; this does *not* work and will
actually close the paragraph instead of nest the elements
> Fix broken HTML in OBS plugin

- lib/OpenQA/Schema.pm
- script/initdb
- script/upgradedb
- t/deploy.t
- t/lib/OpenQA/Test/Database.pm
change 'check' to 'deploy' as it controls whether deployment happens or not
> Improve name of connect_db's param 'check'

- lib/OpenQA/WebAPI/Controller/Main.pm
- t/22-dashboard.t
Found a broken `respond_to` call in the Main controller, then a broken type cast, and then i ended up modernising the whole controller.
> Use form validation in Main controller

- lib/OpenQA/Worker/Job.pm
- t/24-worker-jobs.t
* Fix regression introduced by
https://github.com/os-autoinst/openQA/pull/3849
* See https://progress.opensuse.org/issues/91461
> Fix missing test module results

- lib/OpenQA/Schema/Result/Jobs.pm
- t/10-jobs.t
- t/data/first_bad.json
https://progress.opensuse.org/issues/91521
> Show link to first bad test in investigation tab

- t/01-test-utilities.t
It can happen that the warning in the subprocess happens before the
SIGCHLD handler was installed.
The sleep will fix this in most cases.
(To be really sure one would have to add some method in Utils.pm to check if
the handler has been installed.)
Also I changed combined_like to combined_from, which made it easier to debug
the actual output.
Issue: https://progress.opensuse.org/issues/92164
I ran this in a loop in CircleCI [50 times](https://app.circleci.com/pipelines/github/perlpunk/openQA/171/workflows/a48cf629-ecf2-4ec4-9a1c-f238f0b26968/jobs/751), it always passed.
> CI: Fix 01-test-utilities.t

- docs/GettingStarted.asciidoc
- docs/WritingTests.asciidoc
- lib/OpenQA/Constants.pm
- lib/OpenQA/Worker.pm
- lib/OpenQA/Worker/Engines/isotovideo.pm
- lib/OpenQA/Worker/Job.pm
- t/24-worker-engine.t
- t/24-worker-jobs.t
See particular commit messages and https://progress.opensuse.org/issues/91764
---
It might make sense to checkout the commits individually.
> worker: Improve responsiveness while waiting for worker cache

- assets/stylesheets/test-details.scss
- docs/GettingStarted.asciidoc
- etc/openqa/openqa.ini
- lib/OpenQA/Schema/Result/JobGroups.pm
- lib/OpenQA/Schema/Result/Jobs.pm
- lib/OpenQA/Setup.pm
- lib/OpenQA/Shared/Plugin/Gru.pm
- lib/OpenQA/Task/Job/ArchiveResults.pm
- lib/OpenQA/Task/Job/FinalizeResults.pm
- lib/OpenQA/Task/Job/Limit.pm
- lib/OpenQA/Utils.pm
- t/10-jobs.t
- t/14-grutasks.t
- t/config.t
- t/ui/18-tests-details.t
- templates/webapi/test/infopanel.html.ep
* See https://progress.opensuse.org/issues/91347 and particular commit messages
* Still WIP and related ticket is only "spike" ticket
> Add support for archived jobs

- lib/OpenQA/Schema/Result/Jobs.pm
- t/38-workers-table.t
See https://progress.opensuse.org/issues/92344
> Remove previous tmpdir (on web UI side) when preparing worker for its next job

- .circleci/unstable_tests.txt
- assets/javascripts/obs_rsync.js
- t/api/14-plugin_obs_rsync.t
- t/api/14-plugin_obs_rsync_async.t
- t/lib/OpenQA/Test/ObsRsync.pm
- t/ui/27-plugin_obs_rsync.t
- t/ui/27-plugin_obs_rsync_gru.t
- t/ui/27-plugin_obs_rsync_obs_status.t
- t/ui/27-plugin_obs_rsync_status_details.t
See particular commit messages and https://progress.opensuse.org/issues/89935
> Replace unstable test code in 27-plugin_obs_rsync_status_details.t

- assets/assetpack.def
- assets/javascripts/anser-import.js
- assets/javascripts/running.js
- assets/javascripts/test_result.js
- assets/stylesheets/ansi-colors.scss
- assets/stylesheets/test-details.scss
- lib/OpenQA/WebAPI.pm
- t/ui/18-tests-details.t
- templates/webapi/admin/asset/index.html.ep
- templates/webapi/main/group_overview.html.ep
- templates/webapi/main/parent_group_overview.html.ep
- templates/webapi/test/downloads.html.ep
- templates/webapi/test/logfile.html.ep
- templates/webapi/test/result.html.ep
- templates/webapi/test/result_file_list.html.ep
- templates/webapi/test/video.html.ep
* See https://progress.opensuse.org/issues/92746
* Also contains a few other tweaks, see particular commit messages for details
> Add log view supporting rendering of ANSI escape sequences

- contrib/ay-openqa-worker.xml
- docs/Installing.asciidoc
Related progress issue: https://progress.opensuse.org/issues/80382
> Add automatic installation recipe autoyast profile

- dist/rpm/update-cache.sh
- docs/Contributing.asciidoc
After merge we must update https://build.opensuse.org/package/view_file/devel:openQA/openQA/_service?expand=1 to checkout that file as well.
> dist: Also save update-cache.sh from OBS

- t/data/default-needle.json
- t/lib/OpenQA/Test/Utils.pm
- t/ui/12-needle-edit.t
- t/ui/18-tests-details.t
The test seems stable so I removed the `DO NOT MERGE: Test stability of t/ui/18-tests-details.t` commit. See the particular commit messages of the remaining commits for details.
> Fix t/ui/18-test-details.t

- t/42-df-based-cleanup.t
With bad503c it is no longer necessary to do this because the normal `run_gru_job` avoids forking as well.
---
When running the test locally with coverage it still takes 1 seconds longer to execute (sometimes even 2 seconds). I'm wondering why that is. Without coverage it also takes slightly longer but it is in the range of milliseconds. Maybe just overhead incurred by the Minion framework?
> Remove code for mocking Minion in `t/42-df-based-cleanup.t`

- lib/OpenQA/Schema/Result/JobGroups.pm
- lib/OpenQA/Schema/Result/ScheduledProducts.pm
- lib/OpenQA/Schema/ResultSet/Jobs.pm
- lib/OpenQA/Task/Job/FinalizeResults.pm
- lib/OpenQA/WebAPI/Plugin/HashedParams.pm
- t/37-limit_assets.t
Probably not a fix for the actual issue. But a small mistake i saw while reading the code.
Progress: https://progress.opensuse.org/issues/94531
> Fix a small mistake where "if (%foo" was used instead of "if (keys %foo"

- script/openqa-label-all
Related progress issue: https://progress.opensuse.org/issues/94714
> openqa-label-all: Allow to call without specific build

- Makefile
- t/25-cache-service.t
- t/31-client_file.t
- t/44-scripts.t
- t/api/02-iso-download.t
- t/api/02-iso.t
- t/ui/12-needle-edit.t
due to decreased CircleCI performance
* MOJO_INACTIVITY_TIMEOUT
* TIMEOUT_M
* OpenQA::Test::TimeLimit
Issue: https://progress.opensuse.org/issues/95009
> ci: Increase several timeouts

- t/32-openqa_client.t
- t/44-scripts.t
- t/api/02-iso.t
- t/api/08-jobtemplates.t
- t/api/14-plugin_obs_rsync.t
- t/ui/25-developer_mode.t
- t/ui/27-plugin_obs_rsync_obs_status.t
These tests have been failing several times today due to timeouts
> t: Increase timeouts

- lib/OpenQA/Worker/Engines/isotovideo.pm
- t/10-jobs.t
- t/24-worker-engine.t
* t: Simplify "linked" lookup in 10-jobs.t
* t: Add test for happy-path of OpenQA::Worker::Engines::isotovideo::sync_tests
* OpenQA::Worker::Engines::isotovideo: Remove dead code "_kill"
> Various minor changes

- assets/javascripts/job_next_previous.js
- assets/javascripts/openqa.js
- assets/javascripts/tests.js
- lib/OpenQA/WebAPI/Controller/Test.pm
- t/ui/01-list.t
Reverts os-autoinst/openQA#4014 due to
https://progress.opensuse.org/issues/95281
> Revert "Distinguish comment types on /tests" due to poo#95281

- docs/Client.asciidoc
- docs/UsersGuide.asciidoc
- lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
See https://progress.opensuse.org/issues/95075
> doc: Document finding tests via the REST-API

- lib/OpenQA/Worker/Job.pm
- t/24-worker-jobs.t
See https://progress.opensuse.org/issues/95170 and particular commit messages
> Improve coverage in worker's job handling

- .circleci/config.yml
- t/44-scripts.t
- t/ui/06-operator_links.t
Related progress issue: https://progress.opensuse.org/issues/95263
> Bump timeouts for various scripts and circleCI

- docs/WritingTests.asciidoc
See: https://progress.opensuse.org/issues/91257
> docs: Add a test example written in Python

- lib/OpenQA/Worker/Job.pm
- t/24-worker-jobs.t
See https://progress.opensuse.org/issues/95170
> t: Cover worker's log file upload

- lib/OpenQA/LiveHandler/Controller/LiveViewHandler.pm
Noticed some dead code while investigating an unrelated test coverage issue.
> Remove dead code from LiveViewHandler

- external/os-autoinst-common/.gitrepo
- external/os-autoinst-common/lib/OpenQA/Test/TimeLimit.pm
subrepo:
subdir:   "external/os-autoinst-common"
merged:   "14156e0d8"
upstream:
origin:   "git@github.com:os-autoinst/os-autoinst-common.git"
branch:   "master"
commit:   "9acf1fb0e"
git-subrepo:
version:  "0.4.3"
origin:   "???"
commit:   "???"
> git subrepo commit (merge) external/os-autoinst-common

- lib/OpenQA/Worker/Engines/isotovideo.pm
Automerge merged this PR although the tidy failed:
https://github.com/os-autoinst/openQA/pull/3807
> Run tools/tidy

- lib/OpenQA/Worker/Job.pm
- lib/OpenQA/Worker/WebUIConnection.pm
- t/24-worker-jobs.t
Based on #4063, see particular commit messages and https://progress.opensuse.org/issues/94531
>  worker: Unify retry-behavior of artefact file uploads with regular API calls

- lib/OpenQA/Schema/Result/Jobs.pm
- t/09-job_clone.t
Previously we used the same message in two locations
> Make message about clone error unique

- lib/OpenQA/WebAPI/Plugin/Helpers.pm
While helping with another issue i noticed that these two helpers are not used anymore.
> Remove two dead helpers

- t/ui/14-dashboard.t
See https://progress.opensuse.org/issues/95839
---
Since https://github.com/os-autoinst/openQA/pull/4079 is already at 162 of 200 retries (https://app.circleci.com/pipelines/github/os-autoinst/openQA/7226/workflows/a03ad42e-7967-4447-8698-9aa3b930a7c4/jobs/68213) and locally 200 of 200 runs have already passed I'm preparing this PR.
> Fix stability of check for scroll-up button in `t/ui/14-dashboard.t`

- t/10-jobs.t
- t/14-grutasks.t
- t/17-build_tagging.t
- t/25-bugs.t
- t/42-screenshots.t
- t/api/02-iso.t
- t/api/14-plugin_obs_rsync.t
- t/ui/27-plugin_obs_rsync_obs_status.t
See https://progress.opensuse.org/issues/93883 and particular commit messages
> Reduce use of `collect_coverage_of_gru_jobs` to speed up tests

- lib/OpenQA/CacheService/Controller/API.pm
I believe this is beneficial because many jobs can benefit/proceed if
`cache_tests` jobs are processed (as the have only a few number of test
distributions compared to the number different assets).
Tested by starting a job locally with caching enabled.
See https://progress.opensuse.org/issues/96557#note-36
> Create `cache_tests` jobs with increased prio

- lib/OpenQA/CacheService/Response.pm
- lib/OpenQA/CacheService/Response/Info.pm
- t/25-cache-service.t
Ticket: https://progress.opensuse.org/issues/96623
> Let workers declare themselves as broken if asset downloads are piling

- lib/OpenQA/Task/Job/FinalizeResults.pm
- t/10-jobs.t
See: https://progress.opensuse.org/issues/96959
> job: Record hook_cmd in minion job notes

- templates/webapi/branding/openSUSE/external_reporting.html.ep
Related progress issue: https://progress.opensuse.org/issues/96744
> Fix bug reporting link for SUSE 15 SP4

- t/25-cache-service.t
Before:
```
t/25-cache-service.t .. ok    
All tests successful.
Files=1, Tests=23, 165 wallclock secs ( 0.04 usr  0.01 sys + 92.98 cusr 11.65 csys = 104.68 CPU)
Result: PASS
```
After:
```
t/25-cache-service.t .. ok    
All tests successful.
Files=1, Tests=23, 122 wallclock secs ( 0.04 usr  0.00 sys + 50.59 cusr 14.96 csys = 65.59 CPU)
Result: PASS
```
Progress: https://progress.opensuse.org/issues/96561
> Speed up cache service tests by not forking Minion jobs

- docs/Pitfalls.asciidoc
- etc/openqa/workers.ini
See https://progress.opensuse.org/issues/97952
> Make it harder to misconfigure `WORKER_HOSTNAME`

- assets/javascripts/overview.js
- lib/OpenQA/Schema/ResultSet/Jobs.pm
- lib/OpenQA/WebAPI/Plugin/Helpers.pm
- t/data/openqa/share/tests/opensuse/tests/openQA/kate.pm
- t/ui/10-tests_overview.t
- templates/webapi/test/overview.html.ep
poo#96058
Adds 'module_re' parameter to /test/overview which
used as regular expresion for git grep over distri directories.
> Add filter for searching modules by regular expression 

- script/openqa-bootstrap
Ticket: https://bugzilla.suse.com/show_bug.cgi?id=1189909
> openqa-bootstrap: Don't check for unset var BYPASS_SYSTEMD_CHECK

- t/lib/OpenQA/SeleniumTest.pm
- t/lib/OpenQA/Test/Utils.pm
- t/ui/21-admin-needles.t
- t/ui/27-plugin_obs_rsync_status_details.t
Followup to #4165.
Progress: Progress: https://progress.opensuse.org/issues/96564
> Speed up 21-admin-needles.t by running all Minion jobs in foreground

- assets/javascripts/running.js
- docs/Pitfalls.asciidoc
- t/ui/25-developer_mode.t
See https://progress.opensuse.org/issues/97952 and particular commit messages
> Improve references regarding devel mode documentation

- assets/javascripts/openqa.js
- package.json
- t/ui/16-activity-view.t
Running and scheduled weren't highlighted, and cancelled icons were not
aligned correctly.
> Fix job status icons in activity view

- lib/OpenQA/Shared/Controller/Session.pm
- lib/OpenQA/WebAPI/Auth/OpenID.pm
- t/03-auth.t
Ticket: https://progress.opensuse.org/issues/89710
> Redirect to original page even on automatic login redirect

- lib/OpenQA/Schema/ResultSet/Assets.pm
This patch gets rid of almost all `stat` syscalls when scanning for untracked files during asset cleanup. I did a benchmark with 60k files on a very very fast SSD, and the result was a performance gain of about 25%.
Progress: https://progress.opensuse.org/issues/97979
> Speed up scan_for_untracked_assets by using less syscalls

- container/worker/Dockerfile
Ticket: https://progress.opensuse.org/issues/97751
> Install recommended deps in worker container

- container/worker/run_openqa_worker.sh
Ticket: https://progress.opensuse.org/issues/97751
> Install os-autoinst-distri-opensuse-deps in worker container

- lib/OpenQA/CLI.pm
- script/client
- script/dump_templates
- script/load_templates
- script/modify_needle
- script/openqa-clone-job
This fixes a few complaints by pod2man about missing =back's and =items outside an =over etc.
> Stop upsetting pod2man

- t/24-worker-jobs.t
* Add an explicit unit test for the worker's error handling when the final image upload fails
* See https://progress.opensuse.org/issues/98655
> Explicitly cover code with unstable test coverage

- t/24-worker-jobs.t
See https://progress.opensuse.org/issues/98655#note-5
> Increase test coverage of `OpenQA::Worker::Job` to 100 %

- t/ui/07-file.t
- t/ui/18-tests-details.t
- templates/webapi/test/downloads.html.ep
* It was brought up in the chat that the UI could be more clear here
* Maybe helps with https://progress.opensuse.org/issues/98388 as well
> Mark non-existing asset as such in the downloads tab

- Makefile
Related progress issue: https://progress.opensuse.org/issues/98952
> Makefile: Add retries for current instabilities of t/full-stack.t

- container/webui/conf/client.conf
- container/webui/conf/openqa.ini
- container/worker/run_openqa_worker.sh
- docs/ContainerizedSetup.asciidoc
- lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
* There's no ticket, these are just fixes for problems I've run into when using the setup with OpenID and no manual CLI parameters for API key/secret.
> Small improvements for container setup

- docs/Installing.asciidoc
- docs/UsersGuide.asciidoc
- etc/openqa/openqa.ini
- lib/OpenQA/Setup.pm
- lib/OpenQA/Task/Job/FinalizeResults.pm
- t/42-df-based-cleanup.t
- t/config.t
Fixes: https://progress.opensuse.org/issues/97763
Alternative to #4181
> Trigger minion tasks when jobs are done

- lib/OpenQA/Schema/ResultSet/Jobs.pm
- lib/OpenQA/WebAPI/Plugin/Helpers.pm
- t/10-tests_overview.t
Fixes https://progress.opensuse.org/issues/98258
> Fix build in tests/overview when groupid is defined

- etc/openqa/openqa.ini
- lib/OpenQA/Setup.pm
Related progress issue: https://progress.opensuse.org/issues/99396
> Ensure that temporary HTTP 503 errors are handled with auto-clone

- lib/OpenQA/Task/Job/FinalizeResults.pm
- t/10-jobs.t
Issue: https://progress.opensuse.org/issues/99519
> Log return code of hook command

- container/openqa_data/Dockerfile
- container/webui/Dockerfile
- container/webui/Dockerfile-lb
- container/worker/Dockerfile
- docs/Installing.asciidoc
* See https://progress.opensuse.org/issues/99240 although updating the
containerized setup is not strictly part of it
> Upgrade containers for containerized setup to Leap 15.3

- .circleci/build_cache.sh
- .circleci/build_dependencies.sh
- .circleci/build_local_container.sh
* See https://progress.opensuse.org/issues/99240
> Upgrade CI scripts for using Leap 15.3 based container images

- etc/openqa/openqa.ini
- lib/OpenQA/Scheduler/Model/Jobs.pm
- lib/OpenQA/Setup.pm
- t/04-scheduler.t
- t/config.t
https://progress.opensuse.org/issues/100973
> Unschedule jobs which are too long in 'SCHEDULED' state

- docs/Networking.asciidoc
See https://progress.opensuse.org/issues/101950
> doc: Consider nftables being used in modern systems

- t/ui/14-dashboard-parents.t
- templates/webapi/main/group_builds.html.ep
Progress bar links for builds with children were previously broken
https://progress.opensuse.org/issues/98403
> Fix parent progressbar links

- t/full-stack.t
See: https://progress.opensuse.org/issues/102578
> fullstack: Log worker-log.txt on test bail

- container/webui/Dockerfile
- container/webui/docker-compose.yaml
- container/webui/run_openqa.sh
I was recently experimenting with a container based openQA setup and found a couple issues that had simple fixes.
> Container setup fixes

- t/lib/OpenQA/Test/FullstackUtils.pm
* t: Simplify OpenQA::Test::FullstackUtils
* t: Use signatures in OpenQA::Test::FullstackUtils
* t: Add timeout to developer console waiting status log message
> Improve full-stack.t

- assets/javascripts/admin_groups.js
- templates/webapi/admin/group/group_property_editor.html.ep
> Fix issues in group properties form

- .mergify.yml
> mergify: Add more useful checks

- lib/OpenQA/Schema/Result/Jobs.pm
- lib/OpenQA/Schema/ResultSet/Comments.pm
- lib/OpenQA/Schema/ResultSet/Jobs.pm
- lib/OpenQA/WebAPI/Plugin/AMQP.pm
- t/10-jobs.t
- t/23-amqp.t
See https://progress.opensuse.org/issues/103398 and particular commit messages
> Send AMQP event for internally created comments

- lib/OpenQA/Task/Needle/Scan.pm
Related progress issue: https://progress.opensuse.org/issues/104116
> Add proper signal handling in needle scan minion task

- lib/OpenQA/Schema/Result/JobModules.pm
Reverts os-autoinst/openQA#4412 due to regression:
See https://progress.opensuse.org/issues/104262
> Revert "Missing details-*-.json files are expected"

- assets/javascripts/tests.js
- t/ui/26-jobs_restart.t
- templates/webapi/test/infopanel.html.ep
Related progress issue: https://progress.opensuse.org/issues/69979
> templates: Fix redirection to clones on advanced restart actions

- lib/OpenQA/Schema/Result/JobModules.pm
- t/10-jobs-results.t
Same as #4412, but with tests for the regression.
Progress: https://progress.opensuse.org/issues/102332
> Remove log messages because missing details-*-.json files are expected

- lib/OpenQA/Worker/Engines/isotovideo.pm
- t/24-worker-engine.t
Issue: https://progress.opensuse.org/issues/98577
> Pass the correct asset variable to _handle_asset_processed

- templates/webapi/test/infopanel.html.ep
The related ticket https://progress.opensuse.org/issues/69979 is on feedback so here's some in form of a PR. See particular commit messages for details.
> Improve documentation for advanced restarting UI

- t/14-grutasks.t
- t/23-amqp.t
- t/24-worker-jobs.t
See https://progress.opensuse.org/issues/103617
> Avoid unhandled output in tests

- lib/OpenQA/Markdown.pm
- lib/OpenQA/Utils.pm
Small cleanup. The `bugref_regex` function should have been a constant.
> Replace bugref_regex function with BUGREF_REGEX constant

- assets/javascripts/render.js
- assets/javascripts/running.js
- t/testresults/00099/00099963-opensuse-13.1-DVD-x86_64-Build0091-kde/details-aplay.json
- t/ui/18-tests-details.t
See https://progress.opensuse.org/issues/102786
> Try reloading not yet available text results

- external/os-autoinst-common/.gitrepo
- external/os-autoinst-common/.mergify.yml
- external/os-autoinst-common/lib/OpenQA/Test/TimeLimit.pm
subrepo:
subdir:   "external/os-autoinst-common"
merged:   "24ff317a3"
upstream:
origin:   "git@github.com:os-autoinst/os-autoinst-common.git"
branch:   "master"
commit:   "a6cbaa31f"
git-subrepo:
version:  "0.4.3"
origin:   "???"
commit:   "???"
> git subrepo pull (merge) external/os-autoinst-common

- assets/javascripts/tests.js
- lib/OpenQA/WebAPI/Controller/Test.pm
- t/ui/01-list.t
Works similar to the parameter on /tests/overview
Issue: https://progress.opensuse.org/issues/103765
> Add todo parameter to /tests

- assets/stylesheets/comments.scss
- lib/OpenQA/Markdown.pm
- lib/OpenQA/Schema/Result/Comments.pm
- lib/OpenQA/Utils.pm
- t/16-markdown.t
- t/16-utils.t
- t/17-labels_carry_over.t
Progress: https://progress.opensuse.org/issues/104616
> Make openQA labels clearly visible

- lib/OpenQA/Schema/Result/Jobs.pm
- lib/OpenQA/WebAPI/Controller/Test.pm
- t/ui/18-tests-details.t
- templates/webapi/test/infopanel.html.ep
See https://progress.opensuse.org/issues/105019
> Show number of restarts of a job within info box on details page

- lib/OpenQA/App.pm
- lib/OpenQA/BuildResults.pm
Some more perl signatures in OpenQA
Also, especially for BuildResults, where does the `-signatures` go? Do I do something like `use feature 'signatures'`?
> Add some perl signatures in OpenQA/

- lib/OpenQA/Schema/Result/Jobs.pm
- lib/OpenQA/WebAPI/Controller/API/V1.pm
- t/13-joblocks.t
* Reduce verbosity of very common calls about artefacts and images
* Reduce verbosity of very common calls in WebAPI::Controller::API::V1
> Reduce verbosity

- docs/UsersGuide.asciidoc
Add some explanation of the todo-status to the documentation.
https://progress.opensuse.org/issues/105001
> Add TODO to openQA documentation

- lib/OpenQA/CacheService/Command/run.pm
- lib/OpenQA/CacheService/Controller/Influxdb.pm
- lib/OpenQA/CacheService/Model/Cache.pm
- lib/OpenQA/CacheService/Model/Downloads.pm
- lib/OpenQA/CacheService/Plugin/Helpers.pm
Once more, some more perl signatures
These are all in lib/openQA/CacheService
> Add some more perl signatures

- .gitignore
- .perltidyrc
- .tidyallrc
- t/01-test-utilities.t
- tools/tidy
Same as in os-autoinst, see
https://github.com/os-autoinst/os-autoinst/pull/1795
> Use tidyall instead of custom implementation

- lib/OpenQA/Command.pm
- lib/OpenQA/Events.pm
- lib/OpenQA/File.pm
Add perl signatures to lib/openQA/ Command.pm, Events.pm and Files.pm
> Add more perl signatures in lib:OpenQA

- lib/OpenQA/CacheService/Task/Sync.pm
- t/25-cache-service.t
https://progress.opensuse.org/issues/103771
> Add retry to rsync in cacheservice

- .mergify.yml
Issue: https://progress.opensuse.org/issues/102464
> Add new OBS checks to mergify config

- .circleci/config.yml
- tools/ci/run_unit_tests.sh
Fixes: https://progress.opensuse.org/issues/107002
> ci: Retain fullstack temp folder in artifacts

- lib/OpenQA/WebSockets/Controller/Worker.pm
This is a race condition we likely cannot easily avoid but it should
already be handled gracefully.
> Turn `Worker … accepted job … which was never assigned …` into info level

- lib/OpenQA/CacheService/Client.pm
- lib/OpenQA/CacheService/Command/run.pm
- lib/OpenQA/CacheService/Request.pm
- lib/OpenQA/CacheService/Request/Asset.pm
- lib/OpenQA/CacheService/Request/Sync.pm
- lib/OpenQA/CacheService/Task/Asset.pm
> Part 2: Use signatures in OpenQA::CacheService - based on #4510

- lib/OpenQA/Schema/Result/Jobs.pm
- lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
For /jobs?... API requests, for each job found, another ~ 4 SQL queries
are executed.
Prefetching data will be faster (50% in my local tests).
Issue: https://progress.opensuse.org/issues/94111
> Optimize jobs API by prefetching data

- lib/OpenQA/CLI/api.pm
See https://progress.opensuse.org/issues/71809#note-16
> Add example for triggering a single set of jobs to CLI help

- assets/assetpack.def
- assets/javascripts/feature.js
- assets/stylesheets/openqa.scss
- assets/stylesheets/shepherd.scss
- t/full-stack.t
- t/lib/OpenQA/SeleniumTest.pm
- t/ui/19-tests-links.t
- t/ui/21-admin-needles.t
- t/ui/24-feature-tour.t
Bootstrap-Tour isn't supported anymore and blocks bootstrap upgrade
See: https://progress.opensuse.org/issues/101385
> Move Tour to shepherd.js

- lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
- t/api/04-jobs.t
Issue: https://progress.opensuse.org/issues/108401
> Return 404 for Jobs not found

- lib/OpenQA/WebAPI.pm
Issue: https://progress.opensuse.org/issues/108533
> Validate assetid in /tests/id/asset/assetid

- lib/OpenQA/Worker/Engines/isotovideo.pm
- script/openqa
- script/openqa-websockets
- script/worker
See https://progress.opensuse.org/issues/108281 and particular commit messages
> Avoid overriding upload limit

- docs/UsersGuide.asciidoc
See particular commit messages and https://progress.opensuse.org/issues/109319
> Improve documentation about asset handling

- profiles/apparmor.d/usr.share.openqa.script.openqa
Issue: https://progress.opensuse.org/issues/91605
> Allow mutt in apparmor

- dist/rpm/openQA.spec
- docs/Installing.asciidoc
- script/openqa-continuous-update
- systemd/opensuse/openqa-continuous-update.service
- systemd/opensuse/openqa-continuous-update.timer
See https://progress.opensuse.org/issues/105379
---
Deployed on openqaworker7, see https://progress.opensuse.org/issues/105379#note-8
> Add systemd unit to trigger continous deployment from devel:openQA

- profiles/apparmor.d/usr.share.openqa.script.worker
See: https://progress.opensuse.org/issues/108530
> apparmor: Allow podman to be called on workers

- lib/OpenQA/Setup.pm
* Use signatures in OpenQA::WebAPI::Plugin::REST
* Use signatures in OpenQA::Schema
* Use signatures in OpenQA::Setup
* Simplify OpenQA::Setup
> Use more signatures

- tools/generate-documentation
Issue: https://progress.opensuse.org/issues/110181
> Pin asciidoctor-pdf to a Ruby 2.5 compatible version

- t/03-auth.t
Progress: https://progress.opensuse.org/issues/110509
> Fix controller reuse bug in 03-auth.t

- lib/OpenQA/Schema/Result/Jobs.pm
- t/10-jobs.t
If vars.json doesn't exist (any more), don't try to open it and leave
an error in the log.
Issue: https://progress.opensuse.org/issues/110392
> Deal with cleaned up vars.json on investigation tab

- lib/OpenQA/Script/CloneJob.pm
- script/openqa-clone-job
- t/35-script_clone_job.t
See https://progress.opensuse.org/issues/110515
> Allow exporting openqa-clone-job's API call for posting jobs

- lib/OpenQA/Scheduler/Model/Jobs.pm
See https://progress.opensuse.org/issues/110785 and particular commit messages
> Improve log messages regarding job assignment during scheduling

- lib/OpenQA/WebSockets/Model/Status.pm
- t/27-websockets.t
* So far the previous connection is kept open but not actively used anymore
* So the new connection already wins; this change is making it merely
explicit with a corresponding log message on the web socket server
side which will also end up on the worker side
* Avoid a worker from assuming it is still properly connected when its ws
connection has in fact been superseded
* This fix is motivated by my investigation of the web socket code for
https://progress.opensuse.org/issues/110785 but this change will likely
not fix that issue
> Drop previous web socket connection when worker opens a second one

- assets/javascripts/overview.js
- t/ui/10-tests_overview.t
https://progress.opensuse.org/issues/110719
> Collapse parallel children by default if cluster is passed/softfailed

- etc/openqa/openqa.ini
- lib/OpenQA/Setup.pm
- lib/OpenQA/Shared/Plugin/Gru.pm
- t/config.t
Issue: https://progress.opensuse.org/issues/111152
> Add configuration for expiring minion jobs

- lib/OpenQA/Schema/ResultSet/Jobs.pm
> Fix missing import of 'log_info'

- assets/javascripts/overview.js
- assets/stylesheets/overview.scss
See https://progress.opensuse.org/issues/111470
> Add "Expand all parallel children" button on test result overview

- profiles/apparmor.d/usr.share.openqa.script.openqa
Issue: https://progress.opensuse.org/issues/111215
> Allow markdown in apparmor

- t/ui/10-tests_overview.t
* Test expand button
* Check number of collapse/expand buttons in the case multiple parallel
clusters are present (fixed by
https://github.com/os-autoinst/openQA/pull/4670)
> Extend tests for expanding/collapsing feature in test overview

- lib/OpenQA/Schema/ResultSet/DeveloperSessions.pm
- lib/OpenQA/Schema/ResultSet/Jobs.pm
- lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
- t/05-scheduler-cancel.t
- t/23-amqp.t
- t/api/04-jobs.t
Also allow API calls to specify a reason.
See: https://progress.opensuse.org/issues/111590#note-5
> jobs: Supply a reason in all cases

- docs/Installing.asciidoc
Document slight changes in service files.
Reference: https://progress.opensuse.org/issues/109734
> doc: Add note about openqa-worker-plain@.service

- .mergify.yml
- .obs/workflows.yml
Issue: https://progress.opensuse.org/issues/111887
Tested with a dummy PR: https://github.com/perlpunk/openQA/pull/2
> ci: Test on Leap 15.4

- lib/OpenQA/Schema/ResultSet/Jobs.pm
Related progress issue: https://progress.opensuse.org/issues/112718
> The message about unrecognized referer is a bit too verbose

- script/openqa-continuous-update
> Fix use of --no-refresh in continuous-update

- tools/ci/build_dependencies.sh
CircleCI showed problems trying to retrieve and install packages
sometimes.
See https://app.circleci.com/pipelines/github/os-autoinst/openQA/9884/workflows/c5bb53a3-3405-4e6f-8881-c552fb915ffb/jobs/93292
> CI: Retry also on sporadic install errors

- container/devel:openQA:ci/base/Dockerfile
Related progress issue: https://progress.opensuse.org/issues/111881
> container: Fix unresolved opencv dependency on Leap15.4+Tumbleweed

- docs/Networking.asciidoc
Related progress issue: https://progress.opensuse.org/issues/64700
> docs: Add note about gre_tunnel_preup executable bit

- docs/Networking.asciidoc
* See particular commit messages; it likely makes sense to review commits individually
* Contains https://github.com/os-autoinst/openQA/pull/4773
* Related progress issue: https://progress.opensuse.org/issues/64700
> docs: Improve MM setup documentation

- assets/stylesheets/result_preview.scss
Reference: https://progress.opensuse.org/issues/115943
> Add one line padding to allow space for scrollbar in FF

- .mergify.yml
- tools/ci/build-docs
- tools/ci/prepare_dependency_pr.sh
- tools/generate-documentation
See https://progress.opensuse.org/issues/116593
---
Still a draft as I'm not sure whether that will be sufficient and already work.
> Replace references of `openqabot` with new bot user `os-autoinst-bot`

- .circleci/config.yml
See https://progress.opensuse.org/issues/116593
> Document GitHub user setup for nightly jobs

- t/25-cache-service.t
* t: Improve scope of daemon variable in 25-cache-service.t
* t: Correct naming "start_servers" in 25-cache-service.t
* t: Fix sporadic failure in 25-cache-service
> t: Improve 25-cache-service.t

- documentation.html
Adds a section for blogs and other external links to the documentation page.
> Add external links to documentation

- lib/OpenQA/WebAPI/Plugin/Helpers.pm
- templates/webapi/test/list.html.ep
See https://progress.opensuse.org/issues/111770
> Add help popover for limiting number of finished jobs

- lib/OpenQA/WebAPI.pm
Ticket: https://progress.opensuse.org/issues/100967
> Add signatures to lib/OpenQA/WebAPI.pm

- lib/OpenQA/LiveHandler.pm
Ticket: https://progress.opensuse.org/issues/100967
> Use signatures in lib/OpenQA/LiveHandler.pm

- lib/OpenQA/WebAPI/Auth/Fake.pm
- lib/OpenQA/WebAPI/Auth/OpenID.pm
Ticket: https://progress.opensuse.org/issues/100967
> Switch to signatures for Auth/Fake.pm and Auth/OpenID.pm

- lib/OpenQA/Log.pm
- lib/OpenQA/Worker/Job.pm
- t/24-worker-jobs.t
* This needs to be done in the worker because the code in os-autoinst is not effective if os-autoinst does not terminate cleanly (e.g. killed by the worker due to a timeout or a crash). In these cases the worker should and will still upload logs but then needs to take care of handling secrets itself.
* The worker already strips secrets when logging the vars before starting a job so this does *not* introduce yet another place we check for secrets.
* See https://progress.opensuse.org/issues/114766
> Ensure no more secrets are present in `vars.json` before uploading it

- lib/OpenQA/CacheService/Client.pm
- lib/OpenQA/Worker.pm
- t/24-worker-overall.t
* Related ticket: https://progress.opensuse.org/issues/117631
> Make cacheservice URL configurable

- templates/webapi/test/infopanel.html.ep
* Avoid additional space before comma
* Improve formatting
> Improve rendering "waiting for background (GRU) tasks"

- lib/OpenQA/CacheService/Client.pm
- t/25-cache-client.t
Ticket: https://progress.opensuse.org/issues/117631
> Fix cache service host config for IPs != 127.0.0.1

- lib/OpenQA/WebAPI/Controller/ApiKey.pm
- lib/OpenQA/WebAPI/Controller/Developer.pm
- lib/OpenQA/WebAPI/Controller/File.pm
- lib/OpenQA/WebAPI/Controller/Main.pm
* Use signatures in WebAPI::Controller::Main
* Use signatures in WebAPI::Controller::File
* Use signatures in WebAPI::Controller::Developer
* Use signatures in WebAPI::Controller::ApiKey
> Use signatures in some WebAPI::Controller modules

- lib/OpenQA/Scheduler.pm
- lib/OpenQA/Scheduler/Client.pm
- lib/OpenQA/Scheduler/Controller/API.pm
- lib/OpenQA/Scheduler/Model/Jobs.pm
Including Client, Controller::API and Model::Jobs
> Use signatures in OpenQA::Scheduler

- lib/OpenQA/Log.pm
`canonical` will sort the output.
Otherwise we will get a lot of differences in the diff_to_last_good output.
> Sort vars.json by key

- lib/OpenQA/Schema/Result/Jobs.pm
- t/10-jobs.t
* Avoid throwing an exception when accounting a job assets size and the job has already been deleted; in this case the failed update should not be a big deal since the job is gone anyways.
* There is further code updating jobs which could be improved as well. This change is only fixing the error from issue https://progress.opensuse.org/issues/119866.
> Handle concurrent job deletion when updating job result size

- lib/OpenQA/WebAPI/Plugin/REST.pm
> Use signatures in OpenQA::WebAPI::Plugin::REST

- docs/Pitfalls.asciidoc
- etc/openqa/workers.ini
- lib/OpenQA/Worker.pm
See particular commit messages and https://progress.opensuse.org/issues/120261#note-8
> Improve misleading mentions of "hostname"

- lib/OpenQA/Worker.pm
Fixes regression in 79ab25d32
Related progress issue: https://progress.opensuse.org/issues/120579
> Fix "Use of uninitialized value" in OpenQA/Worker.pm

- lib/OpenQA/Worker.pm
* Use `POSIX::uname` to determine worker registration name after all because the function from `Net::Domain` seems to rely on a functioning DNS setup
* Revert 79ab25d32b52170eebff868efa2c7dee8f533bf8 partially
* See https://progress.opensuse.org/issues/120579
> Avoid relying on DNS setup to determine worker registration name

- lib/OpenQA/Schema.pm
- lib/OpenQA/Shared/Plugin/Gru.pm
Reverts os-autoinst/openQA#4922
> Revert "Use signatures in OpenQA::Shared::Plugin::Gru"

- assets/javascripts/running.js
- lib/OpenQA/LiveHandler/Controller/LiveViewHandler.pm
- t/ui/25-developer_mode.t
- templates/webapi/test/live.html.ep
* Add checkbox to enable/disable whether to pause on failures
* Add button to resume ignoring the failure
* Related ticket: https://progress.opensuse.org/issues/119380
> Add UI for pausing on failure via developer mode

- assets/javascripts/running.js
See https://progress.opensuse.org/issues/119380
> Allow ignoring failure when paused on specific command

- lib/OpenQA/WebAPI/Controller/Test.pm
- t/10-tests_overview.t
Ticket: https://progress.opensuse.org/issues/121441
> Catch error and return 404 for module_fails with non existing test

- t/04-scheduler.t
See: https://progress.opensuse.org/issues/121366
> tests: Consume expected fake error from web socket

- lib/OpenQA/Shared/Plugin/Gru.pm
Second try after
* #4922
~~Should be done after #4947~~
excluding the uncovered code section
> Use signatures in OpenQA::Shared::Plugin::Gru

- lib/OpenQA/WebAPI/Controller/Running.pm
Introduce signatures in all methods which are properly covered by tests and
code coverage collection.
Extracted as part of
* #4898
as I could not yet find out why code is not covered by tests.
> Use signatures in WebAPI::Controller::Running

- tools/generate-documentation
https://progress.opensuse.org/issues/122584
> Pin css_parser to version 1.12.0 because newer need ruby 2.7

- assets/javascripts/admin_assets.js
- t/ui/18-tests-details.t
- templates/webapi/test/downloads.html.ep
* See https://progress.opensuse.org/issues/123175#note-19 for the motivation
* Provide a link from the "Downloads" tab to the assets table
* See particular commit messages for further details
> Improve various details about asset-related UI

- lib/OpenQA/WebAPI/Controller/API/V1/Worker.pm
- t/api/01-workers.t
Progress: https://progress.opensuse.org/issues/121108
> Add pagination for GET /api/v1/workers

- documentation.html
https://progress.opensuse.org/issues/94114
> Add SUSE QE Tools Workshop youtube playlist link

- README.asciidoc
Now that we have badges let's use them!
> Add bage for openQA in openQA test (appliance)

- lib/OpenQA/Schema/Result/ScheduledProducts.pm
- t/api/02-iso.t
I made those improvements when investigating https://progress.opensuse.org/issues/124469. See particular commit messages for details.
> Improvements for product scheduling code

- lib/OpenQA/WebAPI/Controller/Test.pm
Fetch dependencies and failed modules for all jobs in one go instead of doing up to 500-1000 * 3 queries.
The duration of that route went down locally from 1.25s to 0.2s for a job with more than 50 next/previous pages.
As we do this optimization already for the /tests/overview page I put some code into subroutines.
edit: Looking at osd logs, this route can take up to 20 seconds...
> Optimize database queries for next/previous

- lib/OpenQA/Shared/Controller/Auth.pm
- lib/OpenQA/Worker/WebUIConnection.pm
- t/api/03-auth.t
https://progress.opensuse.org/issues/125372
> Add advice to timestamp mismatch error

- docs/WritingTests.asciidoc
Related ticket: https://progress.opensuse.org/issues/125723
> Add documentation for running openQA jobs as CI checks

- lib/OpenQA/Worker/Job.pm
- t/24-worker-jobs.t
The current implementation of enabling the live log does nothing at all when the backend hasn't been started yet. This is a problem if asset caching is enabled because then the backend startup is delayed until all assets have been cached and the frontend likely sends the command for enabling the live log before the backend has been started.
This change causes the worker to track the number of live log viewers regardless of whether the backend is running or not. After the backend has been initialized the current number of live log viewers is evaluated and handled accordingly (in the same way as changes in viewership are handled normally).
Related ticket: https://progress.opensuse.org/issues/113318
> Fix enabling live stream/log when the backend is not up yet

- templates/webapi/test/live.html.ep
See https://progress.opensuse.org/issues/126704
> Clarify "Pause on failure" does *not* affect screen mismatch

- docs/Installing.asciidoc
Related progress issue: https://progress.opensuse.org/issues/127034
> docs: Add SLE installation instructions

- .circleci/config.yml
- codecov.yml
Following
https://docs.codecov.com/docs/github-2-getting-a-codecov-account-and-uploading-coverage
Related progress issue: https://progress.opensuse.org/issues/128129
> CI: Try to fix codecov upload with circleCI orb

- lib/OpenQA/Schema/Result/Comments.pm
- t/17-build_tagging.t
See: https://progress.opensuse.org/issues/126623
> Allow datetime in tag's build

- lib/OpenQA/WebAPI/Controller/API/V1/Webhook.pm
- t/api/16-webhooks.t
- t/data/example-webhook-payload.json
* See individual commit messages
* Related ticket: https://progress.opensuse.org/issues/127949
> Improve webhook/CI related code

- lib/OpenQA/Shared/Controller/Auth.pm
- t/43-cli-api.t
Reference: https://progress.opensuse.org/issues/128795
> Remove slash from the path if base_url ends with one

- docs/GettingStarted.asciidoc
- etc/openqa/openqa.ini
- lib/OpenQA/Schema/Result/JobGroups.pm
- lib/OpenQA/Setup.pm
- t/14-grutasks.t
- t/36-job_group_settings.t
- t/config.t
* Related ticket: https://progress.opensuse.org/issues/129412
> Improve cleanup of groupless jobs

- docs/WritingTests.asciidoc
See https://progress.opensuse.org/issues/128360
> Mention required permisson for webhook based CI setup

- container/devel/Dockerfile
This container contains everything needed for development of openQA for use with distrobox/toolbox
> Add development container for openQA

- container/single-instance/Dockerfile
- container/webui/run_openqa.sh
- script/openqa-bootstrap
* openqa-bootstrap: Speedup package installation
* openqa-bootstrap: Optionally configure SUSE-specifics and tests initialization
* openqa-bootstrap: Support systemd-less environments
* container: Handle potentially already existing certificates gracefully
> single-instance container (poo#129883)

- lib/OpenQA/WebAPI/Controller/Admin/Influxdb.pm
- t/api/13-influxdb.t
https://progress.opensuse.org/issues/99741
> Show number of minion jobs with hook_rc indicating failure

- docs/Contributing.asciidoc
* Reference sections explaining how to import production data and how to tackle performance problems as both are very relevant when creating database migrations
* Related ticket: https://progress.opensuse.org/issues/112946
> Reference further documentation for database migrations

- lib/OpenQA/Worker/WebUIConnection.pm
As observed in
https://github.com/os-autoinst/openQA/pull/5182#issuecomment-1576849678
> Fix flaky coverage in Worker::WebUIConnection

- t/ui/15-comments.t
This should workaround https://progress.opensuse.org/issues/129946 which even still happens after waiting until
`document.forms.commentForm.text.value` is no longer empty. I have only seen this problems in CI runs and never for real so it is supposedly safe to just workaround it in test code.
I've tested this via `$e->send_keys($text) if $attempts > 1;` to simulate the problem locally.
> Add re-try in comments test to mitigate alert problem

- lib/OpenQA/WebAPI/Controller/Admin/Influxdb.pm
- t/api/13-influxdb.t
https://progress.opensuse.org/issues/99741
> Fix timestamp to be actual ns

- .obs/workflows.yml
Reference: https://progress.opensuse.org/issues/130603
> Switch to Leap 15.5 in CI workflow

- lib/OpenQA/Schema/Result/Jobs.pm
- t/10-jobs.t
Issue: https://progress.opensuse.org/issues/130258
> Limit git diff to a maximum number of commits

- contrib/munin/minion
- t/46-munin.t
- t/data/46-contrib-minion.html
Issue: https://progress.opensuse.org/issues/99741
> munin: Make alert thresholds configurable

- contrib/munin/config/minion.config
- contrib/munin/plugins/minion
- dist/rpm/openQA.spec
- t/46-munin.t
Issue: https://progress.opensuse.org/issues/99741
Tested here:
* OBS https://build.opensuse.org/package/show/home:tinita:branches:devel:openQA/openQA
* Download: https://download.opensuse.org/repositories/home:/tinita:/branches:/devel:/openQA/openSUSE_Tumbleweed/x86_64/
> Add subpackage openQA-munin

- lib/OpenQA/Scheduler/Model/Jobs.pm
- lib/OpenQA/Schema/Result/Jobs.pm
It's easier to identify in case of problems.
Issue: https://progress.opensuse.org/issues/131465
> Use a unique template for worker tempdir

- Makefile
- t/33-developer_mode.t
- t/lib/OpenQA/Test/Utils.pm
* Retry re-login in developer mode test
* Related ticket: https://progress.opensuse.org/issues/128807
> Workaround sporadic failures of developer mode test

- Makefile
- t/ui/21-admin-needles.t
Eg by calling `make test TESTS=t/api/04-jobs.t`
> Fix tests due to postgres error msg filtered in wrong language

- script/openqa-bootstrap
https://bugzilla.suse.com/show_bug.cgi?id=1213160
https://progress.opensuse.org/issues/131024
> Fix openqa-bootstrap script referencing unbound var

- dist/rpm/openQA.spec
Ticket: https://progress.opensuse.org/issues/131024
> Fix openQA spec to actually build single-instance-nginx subpkg

- etc/nginx/vhosts.d/openqa.conf.template
Fixes https://github.com/os-autoinst/openQA/pull/5243
> Comment out TLS section in nginx config by default as there are no certs

- script/fetchneedles
https://progress.opensuse.org/issues/131024
Fixes errors like https://openqa.opensuse.org/tests/3439538#step/openqa_bootstrap/14
> Don't use apache specific www group in fetchneedles

- assets/javascripts/audit_log.js
The backtics upset Javascript::Minifier
Related: https://progress.opensuse.org/issues/124469
> Use regular single quotes in javascript code

- etc/openqa/openqa.ini
- lib/OpenQA/Scheduler/Model/Jobs.pm
- t/04-scheduler.t
Issue: https://progress.opensuse.org/issues/129619
> Limit number of running jobs per webui instance

- lib/OpenQA/WebAPI/Controller/Admin/Influxdb.pm
For some reason I was only looking at one of the parameters...
Issue: https://progress.opensuse.org/issues/133889
> Add timezone to SQL

- lib/OpenQA/WebSockets/Controller/Worker.pm
This patch removes the redundant `SELECT` on the workers table, as well as the transaction, which didn't do anything of significance (no `FOR UPDATE`).
1000 status updates **before**:
1000 status updates **after**:
> Remove redundant worker SELECT query

- cpanfile
- dependencies.yaml
- tools/ci/build_dependencies.sh
I forgot to add the dot to the `sed` line.
> Fix perltidy dependency update

- lib/OpenQA/Command.pm
Issue: https://progress.opensuse.org/issues/138545
> Increase MOJO_CONNECT_TIMEOUT in openqa-cli

- assets/javascripts/test_result.js
- assets/stylesheets/comments.scss
- t/ui/15-comments.t
Ticket: https://progress.opensuse.org/issues/138299
> Fix test short reference rendering

- docs/Networking.asciidoc
Those were basically the steps we took to reproduce https://progress.opensuse.org/issues/151612.
> Document testing the MM setup by launching a VM manually

- docs/Networking.asciidoc
Related ticket: https://progress.opensuse.org/issues/152389
> Document further ovs commands

- .circleci/config.yml
Related progress issue: https://progress.opensuse.org/issues/152941
> CI: Shift nightly schedule further trying to avoid download problems

- documentation.html
The name is wrong, and the domain changed as well.
> Update mention of Liv's blog

- lib/OpenQA/WebAPI/Plugin/ObsRsync/Controller/Folders.pm
- lib/OpenQA/WebAPI/Plugin/ObsRsync/Controller/Gru.pm
This fascilitates debugging of issues with sync.
See: https://progress.opensuse.org/issues/112871
> ObsRsync: Include URL in GRU task

- lib/OpenQA/WebAPI/Plugin/ObsRsync/Controller/Gru.pm
See: https://progress.opensuse.org/issues/112871
> ObsRsync: Consistently expand status URL

- .obs/workflows.yml
Expands CI checks against SLE16 backports build
> Add SLE15SP6 Backports OBS CI integration

- lib/OpenQA/Schema/Result/Assets.pm
- lib/OpenQA/Utils.pm
- t/37-limit_assets.t
See https://progress.opensuse.org/issues/152377
> Preserve assets that are symlinks to the fixed directory

- dependencies.yaml
- dist/rpm/openQA.spec
Related progress issue: https://progress.opensuse.org/issues/153793
> Add shfmt to devel requires for preparation

- profiles/apparmor.d/usr.share.openqa.script.worker
See https://progress.opensuse.org/issues/154156
> Ensure the worker can call `du` for space aware cleanup of Git caching

- Makefile
- cpanfile
- dependencies.yaml
The cpanfile now needs to be added on the commandline explicitly
Also fix the develop cpanfile target
The script had been fixed, but not our yaml file yet.
> Adapt usage of tools/update-deps

- docs/Networking.asciidoc
Reference: https://progress.opensuse.org/issues/152095
> docs: Add instructions for pinging over GRE tunnels

- contrib/ay-openqa-worker.xml.erb
https://progress.opensuse.org/issues/155305
> Add chronyd service in OpenQA Autoyast installation

- docs/WritingTests.asciidoc
Related ticket: https://progress.opensuse.org/issues/130934
> Document GitHub action for cloning job from PR description

- contrib/ay-openqa-worker-leap-3-nvme.xml
https://progress.opensuse.org/issues/155305
> Update Autoyast profile for nvme to include chrony

- docs/Contributing.asciidoc
Those are some improvements I could come up with after helping @b10n1k setting up openQA. See the particular commit message for details/reasoning.
> Improve contributing documentation

- t/lib/OpenQA/Test/Utils.pm
- t/ui/23-audit-log.t
See particular commit messages and https://progress.opensuse.org/issues/157543
> Avoid potential problems in UI test of audit log possibly fixing sporadic failures

- assets/javascripts/overview.js
- lib/OpenQA/WebAPI/Controller/Test.pm
- t/ui/10-tests_overview.t
- templates/webapi/test/overview.html.ep
See individual commit messages and https://progress.opensuse.org/issues/154261
> Improve commenting on test results overview according to feedback

- lib/OpenQA/Schema/Result/Jobs.pm
* Use raw SQL with "ON CONFLICT DO NOTHING" like we already do in other cases to prevent this kind of error
* See https://progress.opensuse.org/issues/157912
> Avoid possible errors on asset creation about unique constraint

- lib/OpenQA/Worker.pm
* Remove obsolete FIXME in OpenQA::Worker
* Use signatures in complete OpenQA::Worker
* worker: Extract method 'store_package_list'
> Minor worker code improvements

- container/webui/docker-compose.yaml
- container/webui/nginx-entrypoint.sh
- tools/test_containers_compose
Container names get generated with dashes instead of underscores.
> Fix docker compose V2 usage

- lib/OpenQA/WebAPI/Controller/API/V1/Search.pm
- lib/OpenQA/WebAPI/Controller/Admin/Needle.pm
- lib/OpenQA/WebAPI/Controller/Test.pm
- t/ui/21-admin-needles.t
See particular commit messages and https://progress.opensuse.org/issues/158808
> Fix misc errors and warnings showing up in web UI log

- systemd/openqa-webui.service
Reference: https://progress.opensuse.org/issues/158814
> Pull path unit file to auto restart after Minion update

- Makefile
- dist/rpm/openQA-test.spec
- lib/OpenQA/Setup.pm
- lib/OpenQA/WebAPI.pm
- t/25-serverstartup.t
See https://progress.opensuse.org/issues/159411
> Add check for loading assets via openQA-test package

- lib/OpenQA/Resource/Locks.pm
Ticket: https://progress.opensuse.org/issues/159639
> Fix Lock locking race condition

- docs/Contributing.asciidoc
Add note about how to render documentation locally inside a container as suggested in out GitHub workflow comment.
> Document rendering documentation locally

- .obs/workflows.yml
- container/openqa_data/Dockerfile
- container/webui/Dockerfile
- container/webui/Dockerfile-lb
- container/worker/Dockerfile
- docs/Installing.asciidoc
- tools/ci/build_cache.sh
- tools/ci/build_dependencies.sh
- tools/ci/build_local_container.sh
After
* #5629
Related progress issue: https://progress.opensuse.org/issues/157984
> Update to Leap 15.6 where applicable

- tools/generate-documentation
Reference: https://progress.opensuse.org/issues/160400
> Pin version of pygments gem to fix docs building on Leap

- container/devel:openQA:ci/base/Dockerfile
Reference: https://progress.opensuse.org/issues/160400
> Add ruby-devel to allow building native extensions

- script/openqa-bootstrap
Support running it multiple times without having to startup a fresh container.
> Restructure openqa-bootstrap

- README.asciidoc
- docs/Installing.asciidoc
> Add documentation for codespaces

- docs/WritingTests.asciidoc
Relevant ticket: https://progress.opensuse.org/issues/130940
> Document cloning jobs mentioned in PR comments

- script/openqa-bootstrap
Ticket: https://progress.opensuse.org/issues/132236
> Fix SUSE:CA repo selection on SLE

- lib/OpenQA/WebAPI/Controller/API/V1/JobGroup.pm
- t/ui/13-admin.t
Issue: https://progress.opensuse.org/issues/161957
Broken for four years 4495ec42e181a3e0f92ad876f93312f8a80a6e57 Apparently noone needed it since then ;-)
> Fix editing parent job group properties

- docs/Installing.asciidoc
Reference: https://progress.opensuse.org/issues/155491
> docs: Add instruction how to trigger and clone tests

- lib/OpenQA/Schema/Result/Jobs.pm
- templates/webapi/test/infopanel.html.ep
See particular commit messages and https://progress.opensuse.org/issues/138593
> Improve actions on test details page

- lib/OpenQA/Worker/WebUIConnection.pm
- t/24-worker-webui-connection.t
Related progress issue: https://progress.opensuse.org/issues/161327
> Prevent ambiguous 'localhost' worker connection

- docs/WritingTests.asciidoc
See https://progress.opensuse.org/issues/159399
> Mention possibility to run `isotovideo` in a CI runner

- assets/javascripts/audit_log.js
- assets/javascripts/job_next_previous.js
- assets/stylesheets/tables.scss
- t/ui/10-tests_overview.t
- templates/webapi/admin/audit_log/index.html.ep
- templates/webapi/admin/audit_log/productlog.html.ep
- templates/webapi/admin/machine/index.html.ep
- templates/webapi/admin/needle/index.html.ep
- templates/webapi/admin/product/index.html.ep
- templates/webapi/admin/test_suite/index.html.ep
- templates/webapi/admin/user/index.html.ep
- templates/webapi/admin/workers/index.html.ep
- templates/webapi/test/infopanel.html.ep
- templates/webapi/test/overview.html.ep
See particular commit messages and https://progress.opensuse.org/issues/159408
> Fix some UI issues after Bootstrap 5 migration

- lib/OpenQA/Schema/Result/ScheduledProducts.pm
- t/api/02-iso.t
This is about what I mentioned in the second paragraph of https://github.com/os-autoinst/openQA/pull/5706#issue-2357700968. So it is a continuation of this PR. I also added a few other improvements as a separate commit.
---
* Extend checks in unit tests to verify whether not only the expected set
of tests is created but also the dependencies between them
* Remove cyclic dependency in setup of unit tests as it would now that the
dependencies are actually considered lead to unwanted errors
* Change dependency creation code to also consider chained dependencies
when `_INCLUDE_CHILDREN` is used (despite `_SKIP_CHAINED_DEPS` also being
used)
* Remove error checking for dependency typos in that case as the "missing"
dependency just might have been skipped; distinguishing an actual typo
from a …
> Ensure dependencies of partially re-scheduled product are correct

- script/openqa-bootstrap
The INI section needs to be uncommented as well.
Related ticket: https://progress.opensuse.org/issues/161771
> Fix enabling auto cloning in bootstrap script

- lib/OpenQA/Command.pm
- t/43-cli-api.t
We need to create a new transaction after the previous transaction failed before retrying. Otherwise errors from the previous transaction will still be present even if the new transaction succeeds. Since the callers of `retry_tx` will still look at the initial transaction to get the result we need to assign it to the original transaction.
Related ticket: https://progress.opensuse.org/issues/160877
> Fix `openqa-cli` getting stuck on retrying

- docs/GettingStarted.asciidoc
Related ticket: https://progress.opensuse.org/issues/161771
> Document automatic Git checkouts

- documentation.html
Related progress issue: https://progress.opensuse.org/issues/162893
> Add direct links to progress.o.o projects

- docs/Branding.asciidoc
The links were broken. Add the correspoding ones.
> Fix links in Branding.asciidoc

- lib/OpenQA/Shared/Controller/Running.pm
Statement coverage is incomplete but this is only introducing better checks with signatures so I would treat it as exception.
> Use signatures in Shared::Controller::Running

- docs/Installing.asciidoc
- script/configure-web-proxy
See: https://progress.opensuse.org/issues/162611
> Allow configure-web-proxy to use a custom port

- tools/retry
- tools/test_containers_compose
Related progress issue: https://progress.opensuse.org/issues/162848
> CI: Cover repo errors with exponential retries

- .devcontainer/devcontainer.json
- container/single-instance/Dockerfile
> Switch codespaces devcontainer to single-instance-codespaces

- lib/OpenQA/Schema/Result/ScheduledProducts.pm
- lib/OpenQA/Schema/ResultSet/Jobs.pm
- lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
- t/api/04-jobs.t
Also see the individual commit messages for further improvements and https://progress.opensuse.org/issues/162029
> Allow specifying priority when creating a single set of jobs

- lib/OpenQA/Worker/Engines/isotovideo.pm
Related issue: https://progress.opensuse.org/issues/155188
> Remove duplicated use

- t/05-scheduler-full.t
- t/24-worker-overall.t
- t/43-scheduling-and-worker-scalability.t
- t/lib/OpenQA/Test/Utils.pm
Issue: https://progress.opensuse.org/issues/165198
> Move simulating load to a function

- docs/UsersGuide.asciidoc
See https://github.com/os-autoinst/openQA/pull/5829#discussion_r1705530848
> Mention the possibility to specify a URL via `SCENARIO_DEF…S_YAML_FILE`

- lib/OpenQA/Git.pm
- lib/OpenQA/Task/Git/Clone.pm
- t/14-grutasks.t
- t/16-utils-runcmd.t
Reverts os-autoinst/openQA#5863
> Revert "Refactor generic git functions into git module"

- assets/javascripts/openqa.js
- assets/javascripts/test_result.js
- assets/stylesheets/test-details.scss
- t/ui/18-tests-details.t
- templates/webapi/test/autoinst_log_within_details.html.ep
- templates/webapi/test/logfile.html.ep
Related ticket: https://progress.opensuse.org/issues/165402
---
---
> Add line numbers with anchoring in log viewer

- .github/workflows/obs-helper.yaml
It needs to access the secret
Issue: https://progress.opensuse.org/issues/165144
> Run OBS helper for pull_request_target

- lib/OpenQA/CLI/api.pm
Related ticket: https://progress.opensuse.org/issues/160820
> openqa-cli: Document changed behavior regarding STDIN	after de2a210ce

- lib/OpenQA/Schema/Result/ScheduledProducts.pm
Issue: https://progress.opensuse.org/issues/165866
This doesn't solve the problem, but I found `_schedule_iso` hard to read.
> Refactor ScheduledProducts

- lib/OpenQA/Git.pm
- lib/OpenQA/Task/Git/Clone.pm
- t/14-grutasks.t
Ticket: https://progress.opensuse.org/issues/165066
> Only update clean git checkouts

- lib/OpenQA/Schema.pm
- t/14-grutasks-git.t
- t/14-grutasks.t
- t/16-utils.t
This just moves code around. Any improvements can be suggested, but I will add them in a followup PR.
> Move some tests out of 14-grutasks.t

- lib/OpenQA/Worker.pm
- t/24-worker-overall.t
See https://progress.opensuse.org/issues/166025
> Improve unit tests for check whether QEMU is running

- lib/OpenQA/Worker.pm
- lib/OpenQA/Worker/Settings.pm
- t/24-worker-overall.t
See https://progress.opensuse.org/issues/162284
> Avoid incomplete jobs if Open vSwitch related service is not running

- lib/OpenQA/Schema/Result/ScheduledProducts.pm
This commit extracts a function instead of a code block with comment and
uses post-for calls for two loops.
Inspired by https://github.com/os-autoinst/openQA/pull/5902
> Slightly simplify Schema::Result::ScheduledProducts

- external/os-autoinst-common/.gitrepo
- external/os-autoinst-common/tools/tidyall
```
subrepo:
subdir:   "external/os-autoinst-common"
merged:   "d8da3bc11"
upstream:
origin:   "git@github.com:os-autoinst/os-autoinst-common.git"
branch:   "master"
commit:   "d8da3bc11"
git-subrepo:
version:  "0.4.6"
origin:   "???"
commit:   "???"
```
> Update "subrepo" directory `external/os-autoinst-common`

- t/ui/21-admin-needles.t
Issue: https://progress.opensuse.org/issues/167635
> Make t/ui/21-admin-needles.t work for every timezone

- script/client
- script/modify_needle
- script/openqa-clone-job
- script/openqa-dump-templates
- script/openqa-load-templates
- script/worker
Issue: https://progress.opensuse.org/issues/165393
> Mark obviously uncoverable lines in scripts

- lib/OpenQA/WebAPI/Auth/OpenID.pm
Follow-up to
* #5952
Related progress issue: https://progress.opensuse.org/issues/167266
> OpenID: Clarify the impact of errors to users and admins

- lib/OpenQA/Resource/Jobs.pm
- lib/OpenQA/Schema/Result/Comments.pm
- lib/OpenQA/Schema/Result/Jobs.pm
- lib/OpenQA/Schema/ResultSet/Comments.pm
- lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
- t/05-scheduler-restart-and-duplicate.t
- t/api/04-jobs.t
See https://progress.opensuse.org/issues/167827
> Allow adding a comment when restarting jobs

- lib/OpenQA/Resource/Jobs.pm
- t/api/04-jobs.t
> Trigger git_clone also for Job restart

- docs/Installing.asciidoc
Ticket: https://progress.opensuse.org/issues/132458
> Install docs: Clarify when and how to add repos on SLE

- .circleci/config.yml
Use the latest codecov version for the CI
https://progress.opensuse.org/issues/167482
> Update circleci config to codecov@4.2

- lib/OpenQA/WebAPI/Controller/API/V1/Table.pm
- t/ui/13-admin.t
Ticket: https://progress.opensuse.org/issues/104631
> Show error when admintable settings key contains invalid chars

- t/33-developer_mode.t
- t/full-stack.t
- t/lib/OpenQA/SeleniumTest.pm
- t/ui/21-admin-needles.t
- t/ui/23-audit-log.t
- templates/webapi/admin/needle/index.html.ep
See individual commit messages and https://progress.opensuse.org/issues/167611.
> Stabilize `t/ui/21-admin-needles.t`

- codecov.yml
- lib/OpenQA/Worker/CommandHandler.pm
- lib/OpenQA/Worker/Engines/isotovideo.pm
- lib/OpenQA/Worker/WebUIConnection.pm
- t/24-worker-engine.t
- t/24-worker-webui-connection.t
- t/lib/OpenQA/Test/FakeWorker.pm
See individual commit messages and https://progress.opensuse.org/issues/167914
> Improve test coverage of worker code

- codecov.yml
- lib/OpenQA/Worker.pm
- t/24-worker-overall.t
Related ticket: https://progress.opensuse.org/issues/167914
> Extend worker tests to reach 100 % statement coverage

- lib/OpenQA/Schema/ResultSet/Jobs.pm
- t/10-jobs.t
As mentioned in: https://progress.opensuse.org/issues/166154
> Consistently handle settings with multiple values

- docs/GettingStarted.asciidoc
- etc/openqa/openqa.ini
- lib/OpenQA/Setup.pm
- t/15-assets.t
- t/23-amqp.t
- t/43-cli-schedule.t
- t/api/04-jobs.t
- t/api/08-jobtemplates.t
- t/config.t
- t/data/openqa.ini
- t/ui/01-list.t
See individual commit messages and https://progress.opensuse.org/issues/168379
> Enable automatic updates of test code and needles by default

- lib/OpenQA/Shared/Plugin/Gru.pm
- t/api/04-jobs.t
Ticket: https://progress.opensuse.org/issues/168400
> Resolve symlinks before enqueuing git_clone GRU task

- templates/webapi/step/edit.html.ep
And also put dash at the end instead of escaping.
> webapi: allow dots in needle tags

- .github/workflows/check-helm-chart.yml
Reference: https://progress.opensuse.org/issues/174499
> Update Python version in Helm chart checks

- tools/unstable_tests.txt
https://progress.opensuse.org/issues/175060
> Apply t/full-stack.t as unstable to mitigate the failing test

- Makefile
https://progress.opensuse.org/issues/175060
> Mitigate failing circleci

- lib/OpenQA/Script/CloneJob.pm
- lib/OpenQA/UserAgent.pm
- t/35-script_clone_job.t
- t/api/03-auth.t
Checkout https://github.com/os-autoinst/openQA/pull/6120 first as this PR is based on it.
Otherwise, see the commit message of the last commit and https://progress.opensuse.org/issues/170380 for details.
> Make openqa-clone-job work with authenticated assets downloads

- lib/OpenQA/CLI/monitor.pm
- lib/OpenQA/CLI/schedule.pm
- lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
- lib/OpenQA/WebAPI/Plugin/Helpers.pm
- t/43-cli-schedule.t
Ticket: https://progress.opensuse.org/issues/175305
> Add jobs API option "follow" to return latest clone of queried job

- lib/OpenQA/Scheduler/Model/Jobs.pm
- t/05-scheduler-dependencies.t
* Avoid keeping worker slot allocated if job was not allocated after all
because the host did not match
* Avoid logging `Skipping job … because dependent jobs are not ready` when
the job could not be assigned when repairing half-assigned parallel
clusters because no matching slots are available on the host where the
cluster is running on and `PARALLEL_ONE_HOST_ONLY` is enabled
* Take the `PARALLEL_ONE_HOST_ONLY` setting correctly into account when
repairing half-assigned parallel clusters so the setting is actually
taken into account regardless which of the involved jobs and worker slots
specify it
* Keep repairing half-scheduled clusters; don't abort on the first job that
has not relevant running cluster jobs
* Simplify code by removing the function `_allocate_worker_slot` again and
the …
> Fix repairing half-assigned parallel clusters with PARALLEL_ONE_HOST_ONLY

- assets/javascripts/needleeditor.js
Ticket: https://progress.opensuse.org/issues/176214
> Report actual server errors in via JS

- lib/OpenQA/Git.pm
- lib/OpenQA/Task/Git/Clone.pm
- lib/OpenQA/Utils.pm
- t/14-grutasks-git.t
- t/16-utils-runcmd.t
See https://progress.opensuse.org/issues/169522 and particular commit messages
> Improve Git-related log messages

- lib/OpenQA/Setup.pm
- lib/OpenQA/WebAPI/Controller/Test.pm
- t/25-serverstartup.t
- t/config.t
Related ticket: https://progress.opensuse.org/issues/176421
> Allow reading web UI config from INI files under `openqa.d`

- assets/javascripts/admin_assets.js
- assets/javascripts/admin_groups.js
- assets/javascripts/admin_needle.js
- assets/javascripts/admin_user.js
- assets/javascripts/comments.js
- assets/javascripts/fetch_status.js
- assets/javascripts/job_templates.js
- assets/javascripts/obs_rsync.js
- assets/javascripts/openqa.js
- assets/javascripts/running.js
- assets/javascripts/tests.js
- lib/OpenQA/Shared/Controller/Session.pm
- lib/OpenQA/WebAPI/Controller/Admin/User.pm
- t/ui/09-users-list.t
Ticket: https://progress.opensuse.org/issues/176214
> Propagate json errors to user on fetch requests with non-200 status code

- t/01-style.t
- t/04-scheduler.t
- t/22-dashboard.t
- t/32-openqa_client-script.t
- t/35-script_clone_job.t
- t/full-stack.t
> t: Use implicit Test::Exception in all places

- t/ui/12-needle-edit.t
See particular commit messages and https://progress.opensuse.org/issues/177564
> Improve needle editor tests

- lib/OpenQA/Downloader.pm
- lib/OpenQA/Schema/Result/Assets.pm
- lib/OpenQA/Schema/Result/DeveloperSessions.pm
- lib/OpenQA/Schema/Result/JobModules.pm
- lib/OpenQA/Schema/Result/Jobs.pm
- lib/OpenQA/WebAPI/Controller/API/V1/Bug.pm
- lib/OpenQA/WebAPI/Plugin/ObsRsync/Controller/Folders.pm
- lib/OpenQA/Worker.pm
- lib/OpenQA/Worker/Job.pm
> Remove unused imports on modules which do not have try/catch block

- lib/OpenQA/LiveHandler/Controller/LiveViewHandler.pm
- lib/OpenQA/Scheduler/Model/Jobs.pm
- lib/OpenQA/Schema.pm
- lib/OpenQA/Schema/Result/ScheduledProducts.pm
- lib/OpenQA/Schema/Result/Workers.pm
- lib/OpenQA/Schema/ResultSet/Assets.pm
- lib/OpenQA/Schema/ResultSet/DeveloperSessions.pm
- lib/OpenQA/Task/Asset/Limit.pm
- lib/OpenQA/Utils.pm
- lib/OpenQA/WebAPI.pm
- lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
- lib/OpenQA/WebAPI/Controller/API/V1/Table.pm
- lib/OpenQA/WebAPI/Controller/API/V1/Worker.pm
- lib/OpenQA/WebAPI/Plugin/YAML.pm
- lib/OpenQA/YAML.pm
In general straight forward refactoring.
However there are some points which needs some additional attention:
- when return try..catch
- the return value (either $_, or other complex structure)
- when return from try block
Two modules which has `return` inside _try_ have been left out and
they will be worked in another PR to enphasize to the quality and
proper refactoring.
> Replace Try::Tiny with Feature::Compat::Try

- lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
- wrap and extract context of the try block in a separate function
That is an extra layer to prevent early returns from inside the `try` block
> Extract methods in JobTemplate::update

- t/16-utils-runcmd.t
- t/21-needles.t
https://progress.opensuse.org/issues/162035
> Handle unhandled git output by not outputting it

- t/05-scheduler-restart-and-duplicate.t
- t/api/09-comments.t
- t/deploy.t
Issues:
* https://progress.opensuse.org/issues/178114
* https://progress.opensuse.org/issues/178111
> t: Avoid output in non-verbose mode

- lib/OpenQA/WebSockets/Controller/Worker.pm
If `$worker` is undef, the rest of the statements in the try block don't get executed and the final return value will be false anyway.
`$current_job_id` will be only set if there is a `$current_job`, and all statements after that will only be true if `$current_job_id` is defined, expect some `log_trace` statements, which we can probably consider not important.
We can move most of the statements out of the try block because they are not changing anything in the database or can fail in an expected way. The "skip any further actions" if statement is only true when `$job_id` is defined, and the final statement is only true if `$job_id` is not defined, so it can return from the sub directly.
The only code left in the try is `reschedule_assigned_jobs()`.
> Simplify WebSockets::Worker::Controller

- lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
https://github.com/os-autoinst/openQA/pull/6214 adds some internal functions under the perldoc. perldoc should be above the function which it describes.
> Use perldoc above the corresponding functions

- t/14-grutasks-git.t
- t/14-grutasks.t
- t/16-utils-runcmd.t
- t/21-needles.t
Issues:
* https://progress.opensuse.org/issues/178174
* https://progress.opensuse.org/issues/178177
* https://progress.opensuse.org/issues/178180
> t: Prevent git in tests use tester's ~/.gitconfig

- dbicdh/_common/upgrade/76-77/001-migrate-audit-events-to-scheduled-products.pl
- script/openqa-load-templates
- t/01-style.t
- t/deploy.t
- t/lib/OpenQA/SeleniumTest.pm
Refactor the deploy.t to remove the Try::Tiny dependency in order to use the explicit function from Test::Exception.
> Remove any Try::Tiny reference and add check

- t/lib/OpenQA/Test/FullstackUtils.pm
Issue: https://progress.opensuse.org/issues/175060
See https://github.com/os-autoinst/openQA/pull/6244#discussion_r1979983862
> ci: Reduce timeout for wait_for_result_panel

- Makefile
reference: https://progress.opensuse.org/issues/175060
> Apply mitigation for failing circleci with 7 retry attempts

- t/15-assets.t
- t/16-utils-job-templates.t
- t/28-logging.t
- t/30-test_parser.t
- t/31-client_archive.t
- t/32-openqa_client.t
- t/ui/15-comments.t
> t: Use implicit Test::Exception functions for the test

- t/ui/10-tests_overview.t
Commit 7dc98eb has already addressed some cases where this test fails due to an exception because a stale element is accessed. This change covers all places where the filter form is submitted and subsequently checked in a similar way. It will hopefully make the entire test stable.
> Fix more sporadic test failures in `t/ui/10-tests_overview.t`

- t/32-openqa_client.t
Sorting out the comments on this thread
https://github.com/os-autoinst/openQA/pull/6263#discussion_r1984879191
> Make the tests consistent with the behaviour before 0b78fa6

- assets/javascripts/render.js
https://progress.opensuse.org/issues/178597
> Mitigate textData undef failure

- lib/OpenQA/Schema/Result/JobModules.pm
Issue: https://progress.opensuse.org/issues/178597
> Improve reading of text_data in module results

- t/data/workers.ini
https://progress.opensuse.org/issues/175060
> Ensure fullstack tests run under high system load

- templates/webapi/branding/openSUSE/external_reporting.html.ep
https://progress.opensuse.org/issues/176979
> Fix bugzilla product entry for SL Micro

- docs/index.asciidoc
related: https://progress.opensuse.org/issues/90341
> Add section numbering in OpenQA Documentation

- lib/OpenQA/WebAPI/Plugin/AMQP.pm
- t/23-amqp.t
Related ticket: https://progress.opensuse.org/issues/178147
> Log AMQP errors only as such when retries exhausted

- .gitignore
- t/24-worker-overall.t
related: https://progress.opensuse.org/issues/178207
> Update tempdir path to /tmp to cleanup worktree for workers tests

- templates/webapi/test/infopanel.html.ep
related: https://progress.opensuse.org/issues/179395
> Check if the taskname exists if not avoid undefined value

- t/24-worker-engine.t
- t/24-worker-jobs.t
- t/24-worker-overall.t
- t/24-worker-settings.t
- t/24-worker-webui-connection.t
related: https://progress.opensuse.org/issues/178207
> Update worker tests with tempdirs under /tmp and not in worktree

- codecov.yml
- t/16-utils.t
https://progress.opensuse.org/issues/178942
> Add Utils.pm to fully_covered in Codecov

- Makefile
- dist/rpm/openQA.spec
- docs/Branding.asciidoc
- docs/Contributing.asciidoc
- docs/GettingStarted.asciidoc
- docs/Installing.asciidoc
- docs/Networking.asciidoc
- docs/Pitfalls.asciidoc
- docs/UsersGuide.asciidoc
- docs/WritingTests.asciidoc
- lib/OpenQA/Config.pm
See particular commit messages and https://progress.opensuse.org/issues/179359.
> Install default config under `/usr/share/doc/openqa/examples`

- script/configure-web-proxy
- script/openqa-bootstrap
* Use drop-in config files instead of modifying main config (which is not installed anymore)
* See https://progress.opensuse.org/issues/179359
> Adapt scripts to recent config file changes

- t/14-grutasks.t
> Remove unhandled output generated by log over jobs resultset

- assets/javascripts/audit_log.js
Fixes the URLs for each row in the table
> Fix URLs in admin/productlog

- lib/OpenQA/Schema/ResultSet/JobTemplates.pm
- t/api/08-jobtemplates.t
https://progress.opensuse.org/issues/180650
Show more information when there is an error during creating and/or editing a job template.
> More verbose error message for job template update

- Makefile
- docs/Contributing.asciidoc
- tools/ci/run_unit_tests.sh
- tools/prove_wrapper
related: https://progress.opensuse.org/issues/178117
> Wrap prove to prevent unhandled output

- lib/OpenQA/Shared/GruJob.pm
- t/14-grutasks.t
I missed to adjust the test previously, which was expecting the job to fail.
Issue: https://progress.opensuse.org/issues/181400
> Fix result in case of giving up gru jobs without GruTasks

- t/03-auth-openid.t
it is just the test description but still..
> Fix typo in 03-auth-openid.t

- systemd/openqa-enqueue-asset-cleanup.service
- systemd/openqa-enqueue-audit-event-cleanup.service
- systemd/openqa-enqueue-bug-cleanup.service
- systemd/openqa-enqueue-git-auto-update.service
- systemd/openqa-enqueue-needle-ref-cleanup.service
- systemd/openqa-enqueue-result-cleanup.service
- systemd/openqa-gru.service
- systemd/openqa-livehandler.service
- systemd/openqa-minion-restart.service
- systemd/openqa-reload-worker-auto-restart@.service
- systemd/openqa-webui.service
- systemd/openqa-worker-cacheservice-minion.service
- systemd/openqa-worker-cacheservice.service
Ticket: https://progress.opensuse.org/issues/181370
> On shutdown keep openqa-webui and web server running until gru stopped

- t/full-stack.t
Related ticket: https://progress.opensuse.org/issues/182279
> Fix wrong test name and improve wording in fullstack test

- assets/javascripts/overview.js
- lib/OpenQA/WebAPI/Plugin/Helpers.pm
- t/ui/10-tests_overview.t
- templates/webapi/test/overview.html.ep
https://progress.opensuse.org/issues/113432
> Allow comma-separated filtering of flavor

- container/helm/README.md
https://progress.opensuse.org/issues/183056
> Update documentation with the new helm chart postgres format

- assets/javascripts/openqa.js
- assets/javascripts/test_result.js
- t/ui/28-keys_to_render_as_links.t
resolves: https://github.com/os-autoinst/openQA/issues/6505
> Print one url per line in test settings

- lib/OpenQA/Task/Needle/Save.pm
- t/16-utils-runcmd.t
Reference: https://progress.opensuse.org/issues/108989
> Change `do_cleanup` definition in test using `scm git`

- docs/Installing.asciidoc
https://progress.opensuse.org/issues/183617
> Extend single-instance container documentation

- lib/OpenQA/Script/CloneJob.pm
- script/openqa-clone-job
- t/40-openqa-clone-job.t
Issue: https://progress.opensuse.org/issues/184735
See commit messages.
> openqa-clone-job: Support schemeless addresses

- lib/OpenQA/BuildResults.pm
Ticket: https://progress.opensuse.org/issues/185494
> Fix race cond when date ref job got deleted while serving build list

- lib/OpenQA/Schema/Result/Jobs.pm
Related progress issue: https://progress.opensuse.org/issues/185515
> Schema::Result::Jobs: Catch undefined parent jobs

- lib/OpenQA/Worker/Job.pm
Trying to upload those will lead to errors as openQA requires a name. It is probably better to avoid any fatal errors here so the rest of the results can still be uploaded.
Related ticket: https://progress.opensuse.org/issues/185497
---
Still a draft because I might want to test this for real first.
> Skip upload of test modules and extra tests with no name

- Makefile
- docs/Contributing.asciidoc
- tools/js-tidy
Otherwise unsafe code may be executed.
> Use and recommend --ignore-scripts with npm install

- docs/WritingTests.asciidoc
* Update introduction
* Add examples
* See https://progress.opensuse.org/issues/184888
> Mention Lua based tests in documentation

- docs/WritingTests.asciidoc
See: https://progress.opensuse.org/issues/175060
> Mention use of CRITICAL_LOAD_AVG_THRESHOLD

- lib/OpenQA/Shared/Plugin/Gru.pm
- lib/OpenQA/WebAPI/Controller/Test.pm
- t/ui/18-tests-details.t
- templates/webapi/test/infopanel.html.ep
related to: https://progress.opensuse.org/issues/169144
> Link minion job from openQA job with waiting task

- t/api/02-iso.t
Found it by accident while working on
https://progress.opensuse.org/issues/188595
> t: Fix comparison by interpolating variable

- assets/javascripts/job_templates.js
See https://progress.opensuse.org/issues/187698 and individual commit messages.
> Improve client-side validation in group property editor

- etc/openqa/workers.ini
- lib/OpenQA/Worker.pm
- t/24-worker-overall.t
Ticket: https://progress.opensuse.org/issues/185992
> Worker: Detect IPMI config and shutdown SUT when unused

- lib/OpenQA/WebAPI/Plugin/ObsRsync.pm
Reference: https://progress.opensuse.org/issues/178948
> Replace argument assignment with signatures on ObsRsync 

- lib/OpenQA/WebAPI/Controller/File.pm
Ticket: https://progress.opensuse.org/issues/189795
> Don't redirect to asset domain via /needles/<id>/(image|json) route

- lib/OpenQA/Parser/Format/KTAP.pm
- t/30-test_parser.t
- t/data/ktap_correct.tap
Verification runs:
- https://rmarliere-openqa.qe.prg2.suse.org/tests/1599#step/selftests:cgroup:test_freezer/11 **before**
- https://rmarliere-openqa.qe.prg2.suse.org/tests/1604#step/selftests:cgroup:test_freezer/10 **after**
> parser: ktap: Fix SKIP case
