- assets/javascripts/openqa.js
- assets/stylesheets/navigation.scss
- lib/OpenQA/Setup.pm
- lib/OpenQA/Utils.pm
- lib/OpenQA/WebAPI.pm
- lib/OpenQA/WebAPI/Controller/API/V1/Search.pm
- t/api/15-search.t
- t/config.t
- t/ui/13-admin.t
- t/ui/15-search.t
- t/ui/23-audit-log.t
- templates/webapi/layouts/navbar.html.ep
- templates/webapi/search/search.html.ep
- Global search field
- A new search template to render results
- New "Search" controller
- AT3-4 - Search for Perl modules by filename
- AT3-5 - Search Perl module contents
- Results are rendered via a new REST API route
Related: [poo#34486](https://progress.opensuse.org/issues/34486)
> Implement test search route and results view

- lib/OpenQA/CLI/api.pm
- lib/OpenQA/Command.pm
- t/43-cli-api.t
This came up on Rocket Chat. Trivial change to make shell scripting with `openqa-cli api` a bit easier.
> Make openqa-cli set a non-zero exit code on failures

- assets/javascripts/openqa.js
- lib/OpenQA/Setup.pm
- lib/OpenQA/WebAPI/Controller/API/V1/Search.pm
- t/api/15-search.t
- t/config.t
- templates/webapi/search/search.html.ep
- Show a spinner while results are being fetched
- Append results only after creating the elements
- Limit the total amount of matches (configurable)
Performance measured with `(performance.now() - t0).toFixed(1)` went from 3700 to 2900 with a big resultset on the same system.
> Make global search more responsive

- lib/OpenQA/WebAPI/Controller/API/V1/Search.pm
This fixes the following error on osd:
Grep failed: fatal:
cannot change to '/var/lib/openqa/share/tests/old-tests-sle12-and_older.tar.xz': Not a directory
For whatever reason the test root contains old archived tests which trips up the search, which assumes folders containing test distributions.
> Omit files in the test root from test search

- openQA.spec
With %{_libexcdir} changing from /usr/lib to /usr/libexec, this would
no longer work in the not too far future.
> packaging: do not abuse %{_libexecdir} for systemd directories

- script/openqa-clone-custom-git-refspec
In general, the PRODUCTDIR and CASEDIR in a job settings are:
```
CASRDIR    = /var/lib/openqa/cache/openqa.suse.de/tests/sle
PRODUCTDIR = /var/lib/openqa/cache/openqa.suse.de/tests/sle/products/sle
```
But in some particular jobs, such as
https://openqa.suse.de/tests/4427385 or the job which is triggered by
openqa-clone-custom-git-refspec, its PRODUCTDIR is different:
```
CASEDIR    = /var/lib/openqa/pool/25/os-autoinst-distri-opensuse
PRODUCTDIR = os-autoinst-distri-opensuse/products/sle
```
So we could not use the general way to produce the PRODUCTDIR in this
script. For the particular job, when using
openqa-clone-custom-git-refspec to trigger it, the PRODUCTDIR is
reproduced wrongly in current code, e.g.
`PRODUCTDIR="os-autoinst-distri-opensuseos-autoinst-distri-opensuse/products/sle"` …
> Fix PRODUCT issue when trigger a particular job

- lib/OpenQA/WebAPI/Controller/API/V1/Search.pm
Due to the special symlink setup, sle and opensuse distributions currently lead to redundant results. This can be fixed by making sure we only look at unique resolved paths.
Note: As a side effect the total of results is reduced significantly which speeds up client-side rendering.
See: [poo#34486](https://progress.opensuse.org/issues/34486)
> Deduplicate test distribution listings in search

- lib/OpenQA/WebAPI/Controller/API/V1/Search.pm
- t/api/15-search.t
- t/data/openqa/share/tests/opensuse/tests/installation/installer_timezone.pm
- t/ui/15-search.t
- Enable line numbers on matches
- Merge subsequent matches with the same filename
- Specify split limit to avoid : in source getting parsed
Note: As a side effect the total of results is reduced significantly which speeds up client-side rendering.
> Merge module search results from the same file

- lib/OpenQA/Scheduler/Model/Jobs.pm
- lib/OpenQA/Schema/Result/Jobs.pm
- t/05-scheduler-cancel.t
- t/05-scheduler-dependencies.t
- t/05-scheduler-restart-and-duplicate.t
- t/05-scheduler-serialize-directly-chained-dependencies.t
* PR https://github.com/os-autoinst/openQA/pull/3300 allows avoiding the
restart of passed/softfailed children. However, so far the scheduler can
not deal with the situation when not all directly chained children have
been restarted and just skips the new directly chained job cluster.
* This change tries to fix that by simply ignoring direct (sub)chains which
are not scheduled (which means they have not bene restarted).
* See https://progress.opensuse.org/issues/68956#note-33
> Fix scheduling directly chained dependencies when not all children restarted

- lib/OpenQA/Schema/Result/ScheduledProducts.pm
- lib/OpenQA/Task/Asset/Download.pm
- t/14-grutasks.t
- t/api/02-iso-download.t
Failed to create assets download lists when trigger jobs by using 'isos
post' without '_URL=' arguments, even though the test suites or others
already have a setting '_URL'. This is because the assets download lists
is created by using arguments.
Change this behavior to use job settings.
See: https://progress.opensuse.org/issues/62159
> Add gru download assets by using job settings

- .circleci/config.yml
Reverts os-autoinst/openQA#3207; this workaround for https://progress.opensuse.org/issues/68284 should be no longer required.
> Revert "Downgrade chromedriver to fix running Selenium tests within CI"

- t/lib/OpenQA/Test/Case.pm
The {limit =>} qualifier is a no-op. There is no difference in the result except it's faster when there's many events.
> Slice find_most_recent_event to only get one result

- lib/OpenQA/Downloader.pm
The old limit could be hit easily:
https://download.opensuse.org/tumbleweed/appliances/openSUSE-Tumbleweed-JeOS.x86_64-kvm-and-xen.qcow2
http://ftp.uni-erlangen.de/pub/mirrors/opensuse/tumbleweed/appliances/openSUSE-Tumbleweed-JeOS.x86_64-15.1.0-kvm-and-xen-Snapshot20200824.qcow2
http://ftp.uni-erlangen.de/pub/opensuse/tumbleweed/appliances/openSUSE-Tumbleweed-JeOS.x86_64-15.1.0-kvm-and-xen-Snapshot20200824.qcow2
http://ftp.uni-erlangen.de/opensuse/tumbleweed/appliances/openSUSE-Tumbleweed-JeOS.x86_64-15.1.0-kvm-and-xen-Snapshot20200824.qcow2
Bump it to 5 to have some more room.
> Bump max_redirects in OpenQA::Downloader to 5

- .circleci/config.yml
Add dbicdh and dependencies.yaml to the files that might have been changed by perltidy
Last PR was failing because of that: https://github.com/os-autoinst/openQA/pull/3342
> Fix nightly dependency checker

- lib/OpenQA/WebAPI/Controller/API/V1/JobGroup.pm
- t/api/10-jobgroups.t
Note: Currently `$properties` typically carries the name of the group. As per conversations I'm simply replacing it with the ID.
> Emit jobgroup_create with an ID

- lib/OpenQA/WebAPI/Controller/API/V1/Search.pm
- t/api/15-search.t
- Each result type is moved to a helper function
- The implementation of job template results erroneously ended up as part of going through test distribution folders.
- Keep track of cap correctly
Also, `undef` seems to raise a warning with ==.
> Refactor searching perl modules and job templates

- script/openqa-cli
- t/43-cli-api.t
Small followup for #3316, the actual `exit` call  was forgotten, oops.
> Add missing exit call to openqa-cli

- assets/javascripts/render.js
- assets/javascripts/test_result.js
- assets/stylesheets/result_preview.scss
- assets/stylesheets/test-details.scss
- templates/webapi/test/module_table.html.ep
- templates/webapi/test/result.html.ep
UI-wise this is kind of a revert of #3340 because of https://progress.opensuse.org/issues/70648#note-3:
However, there's still at least a tiny bit of a preview and no loading time to see the full text.
I know that there's still room for improvement, e.g. the tooltip could contain a preview and it would possibly be nicer not use use the same element for the "thumbnail" and for the expanded view. However, before doing that it would be nice to unify the code in `module_table.html.ep` with the code in `render.js` because currently these places always need to be adjusted simultaneously.
I hope this is sufficient so people annoyed by #3340 can live with it until I do further improvements. For people who wanted the new behavior: You can still browse very quickly though the serial results using …
> Render serial results inline when collapsed

- lib/OpenQA/Schema/Result/ScheduledProducts.pm
- lib/OpenQA/WebAPI/Controller/API/V1/Iso.pm
- t/api/02-iso.t
- Like the version fallback message, the message about not finding the product should be visible in the notes.
- Don't mention the VERSION since at that point we're already looking for all versions.
@emiura
> Surface scheduled product not found in the web UI

- docs/Networking.asciidoc
Before this patch documentation was missing STP enable. Which should prevent a loops in ovs switches for multi-machine tests when using >2 hosts - bridges are connected in mesh topology (each with each).
> docs: Align gre tunnel script with real use case

- lib/OpenQA/Schema/Result/ScheduledProducts.pm
- t/api/02-iso.t
Route "isos post" was always used to "run tests if configured". After recent changes, client exits with error code when no tests are
configured for architecture. 
This makes a problem for scenario when one needs to run tests for all architectures which are configured in OpenQA
> Treat as success when schedule_iso() cannot find product-arch combination

- tools/tidy
In certain cases, file --mime-type doesn't return perl, and so the
grep would actually fail, and abort the script.
This was the case on travis ci for os-autoinst-distri-opensuse.
See also https://github.com/os-autoinst/os-autoinst/pull/1524
> Fix tools/tidy

- lib/OpenQA/WebAPI/Controller/API/V1/Worker.pm
- t/api/01-workers.t
- These values aren't required and jobs can be inspected by looking up the worker afterwards
- Also, add unit test coverage (the original motivation for this branch)
> Emit worker_register event w/o caps or job ID's

- lib/OpenQA/Worker/Job.pm
- t/24-worker-jobs.t
See https://progress.opensuse.org/issues/63718#note-18
> Add generic phrase to 'died' reason if there's no more information

- lib/OpenQA/Schema/Result/Assets.pm
"result" => "Undefined subroutine &OpenQA::Schema::Result::Assets::log_error called at /usr/share/openqa/script/../lib/OpenQA/Schema/Result/Assets.pm line 128.\n"
> Import log_error used when removing asset from disk fails

- templates/webapi/branding/openSUSE/external_reporting.html.ep
Since there's now a value for openQA in the 'Found By' custom field, we can now tag bugs created from openQA directly,
and query that later, without having to rely on text, that could have been changed accidentally.
> Select 'Found by' when creating new bugs in bugzilla

- lib/OpenQA/Schema/Result/JobModules.pm
* These are likely the result of upload errors and there's nothing to be done about them at this point.
* See https://progress.opensuse.org/issues/70972
> Skip empty details JSON files when finalizing jobs

- assets/javascripts/render.js
- assets/stylesheets/test-details.scss
- t/ui/18-tests-details.t
- templates/webapi/test/result.html.ep
* Show the serial text within the tooltip (instead of just "wait_serial")
* Keep preview visible in expanded state
* Strip additional info before the actual result in preview
---
---
And yes, I haven't implemented all [suggestions from the ticket](https://progress.opensuse.org/issues/70648) but I guess this is a start.
> Improve displaying serial results

- dbicdh/PostgreSQL/deploy/90/001-auto-__VERSION.sql
- dbicdh/PostgreSQL/deploy/90/001-auto.sql
- dbicdh/PostgreSQL/upgrade/89-90/001-auto.sql
- dbicdh/_common/upgrade/89-90/002-initialized-worker-last-seen.pl
- dbicdh/_source/deploy/90/001-auto-__VERSION.yml
- dbicdh/_source/deploy/90/001-auto.yml
- lib/OpenQA/Schema.pm
- lib/OpenQA/Schema/Result/Workers.pm
* Intended to track the worker's last seen date explicitly instead of using
t_updated to avoid interference with other updates, e.g. done by the
scheduler
* Does not contain the actual fix yet, just the database migration
* See https://progress.opensuse.org/issues/69784
> Introduce 't_seen' column to be able to fix worker's online/offline status

- tools/retry
The retry script can re-run a test that fails at the cost of losing the results (since we do not store them anywhere). We can get failures from TAP output (even if the testplan broken). This relies on the hardness dump which we use in CI. It can be enabled locally by setting the variable if desired.
See: [poo#66664](https://progress.opensuse.org/issues/66664)
> Surface errors from failed test tries

- .mergify.yml
Related progress issue: https://progress.opensuse.org/issues/71182
> ci: Temporarily exclude broken OBS checks

- Makefile
Previously the output list of "make help" would include entries like:
```
mkfile_path
current_dir
docker_env_file
unstables := $(shell cat .circleci/unstable_tests.txt | tr '\n'
…
comma
space
```
This can be prevented simply by not allowing arbitrary characters
following valid make target identifiers as long as we only have sane
make targets following the common convention of lowercase alphabetic
characters only.
> Makefile: Prevent "make help" outputting make variable definitions

- lib/OpenQA/Schema/Result/Workers.pm
- lib/OpenQA/Schema/ResultSet/Jobs.pm
- lib/OpenQA/WebAPI/Controller/API/V1/Worker.pm
- lib/OpenQA/WebAPI/Controller/Admin/Workers.pm
- lib/OpenQA/WebSockets/Controller/Worker.pm
- t/04-scheduler.t
- t/05-scheduler-full.t
- t/20-stale-job-detection.t
- t/27-websockets.t
- t/api/01-workers.t
- t/ui/15-admin-workers.t
- templates/webapi/admin/workers/show.html.ep
- templates/webapi/admin/workers/worker_status.html.ep
See https://progress.opensuse.org/issues/69784 and particular commit messages.
---
To avoid a regression in the case of a graceful disconnect I added some extra handling for it, so as a bonus we get:
> Fix worker's online/offline status

- lib/OpenQA/WebAPI/Controller/API/V1/Search.pm
- t/api/15-search.t
- t/ui/15-search.t
- templates/webapi/search/search.html.ep
- Search job modules by `name` only (to avoid unrelated hits from the same category)
- Return early if the limit is hit
- Unlike SQL with DBIX a limit of 0 is an error and with  the additional result type this can lead to an exception. Put another way, this PR fails without the fix, but the test won't fail without it.
See: [poo#33486](https://progress.opensuse.org/issues/34486)
> Search job templates by test module name

- t/ui/25-developer_mode.t
Otherwise clicking non-existant items breaks the test plan.
Inspired by a failure on #3317:
[13:53:34] t/ui/25-developer_mode.t ............... 11/? Bailout called.  Further testing stopped:  isElementSelected: stale element reference: element is not attached to the page document at /home/squamata/project/t/ui/../lib/OpenQA/SeleniumTest.pm:103
FAILED--Further testing stopped: isElementSelected: stale element reference: element is not attached to the page document at /home/squamata/project/t/ui/../lib/OpenQA/SeleniumTest.pm:103
Which locally resulted in messages like this:
Can't call method "click" on an undefined value at t/ui/25-developer_mode.t line 369.
For now this PR is not fixing any bugs, but making the test more robust.
> Check option existence in developer_mode test

- assets/javascripts/admintable.js
- assets/javascripts/audit_log.js
- assets/javascripts/openqa.js
- t/ui/13-admin-no-login.t
When initializing the table, the initial keywords should be set so that individual items can be linked.
This PR also adds basic test coverage for products and machines tables which we don't currently have. And optimizations for existing search parsing, see the respective commits for details.
> Make use of query params in admin datatables

- t/25-cache-service.t
- t/25-cache.t
- t/25-downloader.t
- t/lib/OpenQA/Test/Utils.pm
- t/ui/27-plugin_obs_rsync_obs_status.t
- t/ui/27-plugin_obs_rsync_status_details.t
- 600 seconds is too long to wait for the service
- The test should fail if the service never comes up
- Going one step further all tests should have a timeout
- Introduce a helper function for this
Fixes: https://progress.opensuse.org/issues/66664
> Sensible timeouts for server waits in tests and fail hard

- lib/OpenQA/Schema/Result/ScheduledProducts.pm
- lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
- lib/OpenQA/WebAPI/Plugin/Gru.pm
- t/api/02-iso-download.t
- t/api/04-jobs.t
The gru download task will block all scheduled jobs when using `isos
post`, even the `_URL` is set in a single test suite. With this change,
only related jobs that have settings `_URL` will be blocked.
See: https://progress.opensuse.org/issues/70687
> Block related jobs when doing 'isos post'

- lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
- t/api/08-jobtemplates.t
Aggregated events with a number of rows are not meaningful after the fact.
- Every `jobtemplate_create` emission should have an `ids` array, with one or more job template IDs.
- The `job_group_id` points to the job group that the template is part of.
- The old `id` which was sometimes defined before, and could be the ID of the job group or an individual job template is kept for backwards compatibility.
Note: The `job_group_id` is not guaranteed with events emitted by individual job templates created via the API, not backed by YAML. Since we mainly care about YAML going forward I decided not to add the extra code to lookup the group in this branch.
> Always emit jobtemplate_create with an ID

- t/05-scheduler-full.t
- t/25-cache-service.t
- t/25-cache.t
- t/43-scheduling-and-worker-scalability.t
- t/full-stack.t
Specifying generous timeouts gives better, faster failures (as opposed to being stopped forcibly by CircleCI with no error message).
See: [poo#66664](https://progress.opensuse.org/issues/66664)
> Add TimeLimit to more unit tests

- assets/javascripts/index.js
- t/ui/14-dashboard-parents.t
- t/ui/14-dashboard.t
- templates/webapi/main/index.html.ep
https://progress.opensuse.org/issues/17886
Actually the selector for the automatic refresh is several radio
buttons with hardcoded values.
In order to offer flexibility now is a numeric field
A enhancement of #3141
> Change auto-refresh selector

- etc/openqa/openqa.ini
- lib/OpenQA/Constants.pm
- lib/OpenQA/Log.pm
- lib/OpenQA/Scheduler/Model/Jobs.pm
- lib/OpenQA/Schema/Result/Jobs.pm
- lib/OpenQA/Schema/Result/Workers.pm
- lib/OpenQA/Schema/ResultSet/Jobs.pm
- lib/OpenQA/Setup.pm
- lib/OpenQA/WebSockets/Controller/Worker.pm
- lib/OpenQA/Worker/WebUIConnection.pm
- t/04-scheduler.t
- t/05-scheduler-capabilities.t
- t/05-scheduler-full.t
- t/20-stale-job-detection.t
- t/24-worker-webui-connection.t
- t/43-scheduling-and-worker-scalability.t
- t/api/01-workers.t
- t/config.t
- t/lib/OpenQA/Test/Utils.pm
- t/ui/15-admin-workers.t
See https://progress.opensuse.org/issues/69784#note-12
> Make the timeout to consider workers offline configurable

- t/lib/OpenQA/Test/FullstackUtils.pm
The job may never become available if there is a problem.
> Make schedule_one_job a wait with a timeout

- t/33-developer_mode.t
In
https://app.circleci.com/pipelines/github/os-autoinst/openQA/4208/workflows/a42f68e0-60c7-46e0-88f3-2ace61b3c2b1/jobs/40235
we can see that the test 33-developer_mode.t took 115s so I selected a
conservative value of 180s.
> t: Set time limit for 33-developer_mode.t

- Makefile
We observed the problem that probably since
https://github.com/os-autoinst/openQA/pull/3242
t/25-cache-service.t which is part of "unstable_tests.txt" always fails
in all retries. The other unstable tests were never executed but the
final exit code was reported as 0 so also circleCI reported the test as
successful. The root cause is the "break" in the for-loop not forwarding
the exit code of the underlying failing test. Using a call to "exit"
without argument in the shell code will exit the rule in make with the
according exit code of the underlying test correctly.
Related progress issue: https://progress.opensuse.org/issues/71449
> Makefile: Fix evaluation of failing unstable tests

- t/04-scheduler.t
If what is written to the db is what we want to compare, ad the value can be off by a second, maybe we should use whatever was written in the first place.
> scheduler tests: Take t_seen from the database

- assets/javascripts/openqa.js
- lib/OpenQA/Resource/Jobs.pm
- lib/OpenQA/Schema/Result/Jobs.pm
- t/05-scheduler-restart-and-duplicate.t
* Suggest restarting the parent instead, show link to documentation
* Allow to force the restart anyways
* See https://progress.opensuse.org/issues/70720
> Avoid restarting jobs which have a directly chained parent by default

- .circleci/config.yml
We have some long running tests and especially with internal retrying
aborting after 10m prevents access to helpful details what actually went
wrong. This commit increases the timeout when circleci aborts a job from
10m without output to 30m to help in these cases. Still our goal should
be for each individual test to finish much faster of course.
Related progress issue: https://progress.opensuse.org/issues/66664
> ci: Prevent too early circleci timeout on no output

- t/04-scheduler.t
This unstable and unreliable check was added recently. Unstable tests
quickly lead to alarm fatigue so I consider removing the check is a
better option for now until we might come to a stable solution.
The commit 870f23eda tried to solve the instability without success. The
initial commit that introduced the check was commit d5c0edab9.
Related progress issue: https://progress.opensuse.org/issues/71551
> t: Remove unreliable check for t_seen from t/04-scheduler

- t/05-scheduler-full.t
- t/33-developer_mode.t
- t/api/02-iso.t
- t/full-stack.t
- t/lib/OpenQA/SeleniumTest.pm
- t/ui/06-operator_links.t
- t/ui/13-admin-no-login.t
- t/ui/14-dashboard.t
- t/ui/15-search.t
- t/ui/19-tests-links.t
- t/ui/23-audit-log.t
- t/ui/27-plugin_obs_rsync_status_details.t
- t/ui/28-keys_to_render_as_links.t
- templates/webapi/admin/product/index.html.ep
Our OpenQA::SeleniumTest::call_driver function when called without
arguments would implicitly create a test database. In all cases where
this was used the database was not used at all and just takes time to
initialize and is prone to confuse test writers with two parallel test
database instances.
This commit changes `call_driver` to not initialize its own database
anymore. If potentially necessary one could pass an externally created
database.
Related progress issue: https://progress.opensuse.org/issues/71500
> t: Prevent duplicate test database initialization

- assets/javascripts/openqa.js
- lib/OpenQA/Jobs/Constants.pm
- lib/OpenQA/Resource/Jobs.pm
- lib/OpenQA/Schema/Result/Jobs.pm
- lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
- lib/OpenQA/Worker/Job.pm
- t/05-scheduler-restart-and-duplicate.t
- t/09-job_clone.t
- t/15-assets.t
- t/24-worker-jobs.t
- t/24-worker-overall.t
- t/api/04-jobs.t
- templates/webapi/test/infopanel.html.ep
The worker's status updates are already rejected by the web UI when the ID
specified by the worker does not match the ID of the actually assigned
worker. This change applies the same check to the API function to mark a
job as done.
So now, when a worker is assumed offline the job can be re-scheduled and
assigned to a different worker without running into problems when the
worker assumed to be offline comes back after all.
See https://progress.opensuse.org/issues/64520
---
I've also tested this locally with the full stack using a worker which needs 30 seconds to accept a job. In the 30 seconds I've re-scheduled the job and assigned it to a different worker. After the 30 seconds the first worker runs into API errors as expected but it no longer interferes with the job execution on the other …
>  Avoid worker assumed to be offline from interfering when it comes back after all

- assets/javascripts/render.js
- assets/javascripts/test_result.js
* Fix regression introduced by https://github.com/os-autoinst/openQA/pull/3352
* Use same JavaScript code in any case (module rendered while running or in
final state)
* Pass the step preview container directly and use better variable name (it
is not an 'a' element)
* See https://progress.opensuse.org/issues/69490
> Fix showing preview of modules rendered while the test was running

- t/33-developer_mode.t
- t/full-stack.t
- t/lib/OpenQA/SeleniumTest.pm
- t/lib/OpenQA/Test/Utils.pm
- t/ui/01-list.t
- t/ui/02-list-group.t
- t/ui/06-operator_links.t
- t/ui/10-tests_overview.t
- t/ui/12-needle-edit.t
- t/ui/13-admin.t
- t/ui/14-dashboard-parents.t
- t/ui/14-dashboard.t
- t/ui/15-admin-workers.t
- t/ui/15-comments.t
- t/ui/15-search.t
- t/ui/16-tests_dependencies.t
- t/ui/16-tests_job_next_previous.t
- t/ui/17-product-log.t
- t/ui/18-tests-details.t
- t/ui/19-tests-links.t
- t/ui/21-admin-needles.t
- t/ui/23-audit-log.t
- t/ui/24-feature-tour.t
- t/ui/25-developer_mode.t
- t/ui/26-jobs_restart.t
- t/ui/27-plugin_obs_rsync_status_details.t
- t/ui/28-keys_to_render_as_links.t
* t: Replace all schema hooks by more simple schema updates
* t: Use more concise one-line Selenium driver initialization
* t: Completely remove unused schema_hook functionality
> t: Use more concise one-line Selenium driver initialization; Completely remove unused schema_hook functionality

- lib/OpenQA/Worker/Engines/isotovideo.pm
Related progress issue: https://progress.opensuse.org/issues/69451
> Add specific error message for premature asset cache pruning

- docs/Contributing.asciidoc
- t/lib/OpenQA/Test/TimeLimit.pm
* docs: Add section about "Test runtime limits"
* t: Add scaling parameters for OpenQA::Test::TimeLimit
Related progress issue: https://progress.opensuse.org/issues/71845
> Use alarm scaling factors

- lib/OpenQA/Schema.pm
- script/initdb
- script/upgradedb
- t/deploy.t
- t/lib/OpenQA/Test/Database.pm
* Improve name of method 'deployment_check' to prevent confusion
* t: Remove unused and useless 'skip_deployment_check'
Related progress issue: https://progress.opensuse.org/issues/71500
> Remove unused 'skip_deployment_check'; Prevent confusion on 'deployment_check' with rename

- .circleci/config.yml
- Makefile
Increase circleCI timeout to be bigger than the sum of the number of
retries times the timeout for a single test run while still keeping the
timeout for a single test run higher than the test module internal
timeout.
Related progress issue: https://progress.opensuse.org/issues/71554
> Tweak test timeouts for full-stack

- t/01-test-utilities.t
- t/lib/OpenQA/Test/Utils.pm
See the message of the first commit for details and an example how it looks like in the error case. I'm not sure whether this is a clear win. The tests will be only aborted as a consequence of the child not being available. If the sub process is actually supposed to "passively do its thing" like the scheduler it might not immediately abort the test and the reason for the failure wouldn't be as easy to spot than in my example. Maybe it is better to explicitly handle `SIGCHLD` and call `BAIL_OUT` if it was an unexpected exit.
> Catch warnings from sub processes during tests

- t/lib/OpenQA/SeleniumTest.pm
By default scripts can literally take forever to execute.
See: https://progress.opensuse.org/issues/71554
> Configure a timeout for javascript in webdriver

- t/44-scripts.t
The recent reduction to 20s can lead to problems as observed on circleCI
as well as locally reproducible.
Related progress issue: https://progress.opensuse.org/issues/72127
> t: Bump timeout for 44-scripts

- lib/OpenQA/Scheduler/Model/Jobs.pm
- lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
- t/api/04-jobs.t
* Use a transaction when creating a job in 'jobs post' controller so
queries by the scheduler don't see the new job until all download tasks
have been created as well.
* See https://progress.opensuse.org/issues/72055
> Prevent scheduler from assigning jobs while download tasks being created

- openQA.spec
As we build against other repositories and architectures and our tests
are more stable we could benefit from testing on these as well using the
power of OBS. Enabling tests on openSUSE Leap helps us to prevent
deploying known broken package combinations which is not tested during
openQA development using circleCI, e.g. when a dependency has been
updated in openSUSE:Factory already, as happened in the past.
Related progress issue: https://progress.opensuse.org/issues/69160
> spec: Enable tests on Leap as well to prevent breakage on known supported versions

- .circleci/config.yml
This reverts the change from f62ce8d8e where we added `--merge` to show
stderr along with stdout in the test artifact output which however makes
stderr output disappear from the log view where the initial information
about failed information is useful as well as where we want to see any
undhandled output.
This commit changes the behaviour back to what we had previously
comparable to what a local call to 
`PERL_TEST_HARNESS_DUMP_TAP=<dir> prove`
would also supply. Additionally we can benefit from colored test output
in the circleCI log view. One more issue tackled is that we try to cover
all error log output with Test::Output alike and now the output shows up 
again in the log view.
Previously the output in the circle CI log view looked like this:
```
[13:26:45] t/10-jobs.t …
```
> ci: Bring back error context in log view as well as show unhandled test output

- assets/javascripts/render.js
This should fix https://progress.opensuse.org/issues/72289 and other
cases where the test details rendering was so far stopped by an exception
because a template snipped was not available.
I also improved the coding style and fixed some warnings reported by jshint.
> Fix details rendering if template snippet not available

- t/lib/OpenQA/Test/Case.pm
Since a very long time in our initialization of test database entries we 
updated the timestamp of one job, 99937. This was likely necessary for a
specific test and definitely not needed in all test modules that use the
same test database. Apparently the timestamp update is not even
necessary anymore in any current test module so this commit is removing
the according code completely.
> t: Remove obsolete test job database entry in all initializations

- script/openqa-enqueue-audit-event-cleanup
- script/openqa-enqueue-bug-cleanup
- script/openqa-gru
- script/openqa-slirpvde
- script/openqa-vde_switch
- script/openqa-worker-cacheservice-minion
- t/44-scripts.t
Test output:
```
$ prove -l -v t/44-scripts.t
t/44-scripts.t ..
ok 1 - Calling 'client --help' returns exit code 0
ok 2 - Calling 'configure-web-proxy --help' returns exit code 0
ok 3 - Calling 'create_admin --help' returns exit code 0
ok 4 - Calling 'dump_templates --help' returns exit code 0
ok 5 - Calling 'fetchneedles --help' returns exit code 0
ok 6 - Calling 'initdb --help' returns exit code 0
ok 7 - Calling 'load_templates --help' returns exit code 0
ok 8 - Calling 'modify_needle --help' returns exit code 0
ok 9 - Calling 'openqa --help' returns exit code 0
ok 10 - Calling 'openqa-bootstrap --help' returns exit code 0
ok 11 - Calling 'openqa-bootstrap-container --help' returns exit code 0
ok 12 - Calling 'openqa-cli --help' returns exit code 0
ok 13 - Calling …
```
> Add simple "--help" test for all shell scripts in scripts/

- assets/javascripts/openqa.js
- lib/OpenQA/Schema/Result/Jobs.pm
- lib/OpenQA/WebAPI.pm
- lib/OpenQA/WebAPI/Controller/Admin/ActivityView.pm
- t/ui/16-activity-view.t
- templates/webapi/admin/activity_view/user.html.ep
- templates/webapi/layouts/navbar.html.ep
- A new item *Activity View* is available from the menu
- The view is based off of the search view, although it's backed by the audit log and public jobs API
- The `parents_ok` state is added to the public jobs API
- Running jobs are updated dynamically without requiring a refresh (5s like test result pages)
Fixes: [poo#58304](https://progress.opensuse.org/issues/58304)
> Add a personal activity view based on audit events

- templates/webapi/comments/comment_row.html.ep
The commit d674bdf397dfc4a77cdef95091b2078a50e9d096 tried to fix an
instability with an update of javascript code. A test failed in circleCI
again with:
```
[debug] [8YmjWcRI] POST "/api/v1/parent_groups/1/comments"
[debug] [8YmjWcRI] Routing to controller "OpenQA::Shared::Controller::Auth" and action "auth"
[debug] API auth by user: Demo, operator: 1
[debug] [8YmjWcRI] Routing to controller "OpenQA::WebAPI::Controller::API::V1::Comment" and action "create"
[debug] [8YmjWcRI] 200 OK (0.019251s, 51.945/s)
[debug] [j8Rvzc5Z] GET "/api/v1/parent_groups/1/comments/11"
[debug] [j8Rvzc5Z] Routing to controller "OpenQA::WebAPI::Controller::API::V1::Comment" and action "text"
[debug] [j8Rvzc5Z] 200 OK (0.017316s, 57.750/s)
ok 1 - Wait for jQuery successful: comment added to group
ok 2 - exactly …
```
> Try to fix instability in comment update detection

- etc/openqa/workers.ini
- lib/OpenQA/Worker/Job.pm
- t/full-stack.t
I went with the most minimal solution i could think of and didn't rename the option. Anyone who has `LOCAL_UPLOAD = 1` configured already will have the feature still working as expected.
At first i wanted to just disable the feature in the full-stack test to keep coverage as it was before. But in the middle of the test we restart the worker with a new configuration anyway, so that seemed like a good opportunity to include both cases.
Progress: https://progress.opensuse.org/issues/69637
> Enable faster local host uploads by default

- tools/retry
As we moved back to showing test failure output in the console running
prove we also do not need this approach anymore.
> tools: Revert change f3b5dd95c surfacing TAP failures via retry

- lib/OpenQA/Parser/Format/XUnit.pm
XUnit files generated by some external tools (such as the [robot framework](https://robotframework.org/)), identify failed test cases with a children `failure` (in singular) and does not summarize the failures in a plural `failures` as expected by the current version of the XUnit openQA parser.
This can prevent external failed results from being properly rendered: http://1a102.qa.suse.de/tests/5546
As can be seen on one of the XUnit [files](http://1a102.qa.suse.de/tests/5546/file/robot_fw-limits.robot.xml) from that test, the plural `failures` is used in the test suite, while the singular `failure` is used in the test cases without summarization.
This PR marks the test case as `failed` when encountering test cases with children that have the tags `failure` (singular) or `error`. …
> Add testcase "failure" (singular) to XUnit parser

- Makefile
After recent work done it seems that we can regard full-stack.t again as
more stable and also faster. Also, if there are test failures then we
can expect the test to timeout faster.
In
https://app.circleci.com/pipelines/github/os-autoinst/openQA?branch=master
I looked after recent past occurences of t/full-stack.t and found that
in 7/7 cases no retry was conducted and the runtime was always below 6m.
This commit therefore removes the retries on t/full-stack.t as well as
reduces the make-level timeout accordingly.
Related progress issue: https://progress.opensuse.org/issues/71554
> Mark full-stack.t as stable and faster after recent stabilization

- .mergify.yml
- "strict merge" means that open PRs are checked again whenever the target branch has changed. Affected branches can be rebase automatically.
- Behavior for `merge-fast` will not change.
- The new label `no-automatic-rebase` can be used to retain the current behavior (i.e. your branch is not touched and only merged as-is if possible).
See https://docs.mergify.io/merge-action.html#strict-merge
> Enable strict merge on Mergify

- lib/OpenQA/CLI/api.pm
- lib/OpenQA/CLI/archive.pm
- t/43-cli-api.t
- t/43-cli-archive.t
This was inspired by #3441 and makes `openqa-cli` behave [the same as all commands](https://github.com/mojolicious/mojo/commit/82efa95bbe28a69df57e16ffe3232e3ab8b3f766) we inherit from Mojolicious.
> Handle unknown options consistently with Mojolicious 8.63 in openqa-cli

- script/configure-web-proxy
- script/create_admin
- script/initdb
- script/openqa-clone-custom-git-refspec
- script/openqa-livehandler
- script/openqa-websockets
- script/upgradedb
- t/40-script_openqa-clone-custom-git-refspec.t
- t/44-scripts.t
To prevent incorrect setup of services or scripts in automation we
should ensure that all scripts return a non-zero exit code signalling a
failure.
This commit adds corresponding handling of parameter parsing and
forwarding of the corresponding exit code in all scripts where not
already present. Also adding a corresponding test in t/44-scripts.t.
This increases the runtime especially due to the costly startup of
services but I consider it still beneficial to cover.
Related progress issue: https://progress.opensuse.org/issues/68167
> Ensure all scripts exit non-zero in case of invalid parameters

- assets/javascripts/feature.js
- templates/webapi/layouts/navbar.html.ep
To make this work, a step for the user menu is also added.
See: https://progress.opensuse.org/issues/58304
Note: I could not find a way to get the popover to anchor to the Activity View menu item or make it appear selected respectively. I'm also not 100% sure if the feature levels work properly. The docs are not very helpful either. So this is my best effort.
> tour: Introduce the activity view

- t/01-test-utilities.t
- t/lib/OpenQA/Test/TimeLimit.pm
We've seen the following test failure on OBS (see https://progress.opensuse.org/issues/73162):
```
[ 1108s]     #   Failed test 'manual termination via stop_service does not trigger _fail_and_exit'
[ 1108s]     #   at ./t/01-test-utilities.t line 58.
[ 1108s]     #          got: '1'
[ 1108s]     #     expected: '0'
[ 1108s]     # Looks like you failed 2 tests of 5.
```
The test is actually just running into a timeout. The exact failure can be
reproduced locally by adding a sleep at the right place to run there into
the timeout as well.
This PR adds an explicit log message if the test runs into the timeout and
applies the same scaling used for the overall timeout to the other timeouts
within the test.
> Scale timeout in t/01-test-utilities.t to prevent failures observed on OBS

- templates/webapi/branding/openSUSE/external_reporting.html.ep
This is recommended by the SUSE bug reporting policy for bugs reported
for automatic test cases. A reason is that an issue found in openQA
commonly is making the test fail hence implicitly the bug always
"blocks" further execution.
> branding: Set "blocker" flag automatically in bugzilla bug reports

- t/25-downloader.t
See https://progress.opensuse.org/issues/73156
---
And unfortunately also this test takes a ridiculous time to run. Here its not because of all the forking but because the downloader which is tested here has so many sleeps and tries often multiple times. (Not sure how the test passed within 20 seconds at some point. I had to comment out the time limit to run it locally.)
> Avoid unhandled output in `t/25-downloader.t`

- assets/javascripts/overview.js
- assets/stylesheets/overview.scss
- lib/OpenQA/Schema/ResultSet/Jobs.pm
- lib/OpenQA/WebAPI/Controller/Test.pm
- t/10-tests_overview.t
- t/fixtures/01-jobs.pl
- t/ui/10-tests_overview.t
- t/ui/16-tests_job_next_previous.t
- templates/webapi/test/overview.html.ep
The test overview page only shows the latest jobs by default. The new
parameter shows the overview page like it looked like at the specified
time.
See https://progress.opensuse.org/issues/70792
---
This is only the parameter itself so far. I still need to add the actual link somewhere or maybe add a datetime picker or time slider to the filter form.
> Add timestamp parameter to test overview to show only jobs older than that

- openQA.spec
Related progress issue: https://progress.opensuse.org/issues/73162
> spec: Exclude flaky 01-test-utilities.t from OBS checks

- lib/OpenQA/Scheduler/Model/Jobs.pm
- t/05-scheduler-dependencies.t
Otherwise the unhandled exception prevents the scheduler from processing
*any* further scheduled jobs and jobs are stuck in the scheduled state.
See https://progress.opensuse.org/issues/32545#note-37 for a graph with
an example of such a problematic directly chained cluster.
> scheduler: Handle cycles in directly chained dependencies

- lib/OpenQA/Schema/Result/Jobs.pm
- t/14-grutasks.t
Prevent failed 'finalize_job_results' Minion jobs for skipped jobs
I'm not sure why openQA jobs are sometimes immediately cancelled (after
just being scheduled). This change prevents enqueuing a
'finalize_job_results' Minion job for these openQA jobs because they
sometimes fail (see https://progress.opensuse.org/issues/75073). This can
also be seen as an optimization because the Minion jobs are not required
anyways.
The enqueuing has been moved out of store_column because this function is
invoked by DBIx for each column individually in a random order. Since the
condition for enqueuing the job depends on both - state and result - it can
not (easily) be evaluated within store_column. It is likely cleaner to
enqueue the job explicitly within done/cancel which are the only places
where it …
> Prevent failed 'finalize_job_results' Minion jobs for skipped jobs

- lib/OpenQA/Worker.pm
- lib/OpenQA/Worker/Job.pm
- t/24-worker-jobs.t
- t/24-worker-overall.t
- t/data/24-worker-overall/workers.ini
Otherwise the "setup info" output is potentially misleading.
i.e.
worker hostname:      code
instead of
worker hostname:      localhost
assuming my `workers.ini` contains the following line:
WORKER_HOSTNAME = 127.0.0.1
I realize our example config says the setting is needed by the developer mode in some cases, but during debugging it made me think back and wonder, if my config was actually broken - and it probably is, but not in this regard.
1. Should the setting be used consistently?
2. If not, for whatever reason, it should probably be revealed in the "setup info" anyway
> worker: Use WORKER_HOSTNAME instead of real hostname

- t/34-developer_mode-unit.t
- t/lib/OpenQA/SeleniumTest.pm
- `wait_for_finished_handler` has a timer, which is dead code unless the test is slow enough
- `wait_for_element` has a conditional return, which is dead code unless the test is slow enough
Fixes: [poo#71857](https://progress.opensuse.org/issues/71857)
> coverage: Ensure developer mode unit test has no dead code depending on success

- docs/Contributing.asciidoc
Motivated by http://open.qa/docs/#_test_runtime_limits
> docs: Explain that test runtime limits are automatically scaled

- Makefile
In ac0ccca26 we have removed the retries for the full stack test
assuming that it would be stable enough but
https://app.circleci.com/pipelines/github/os-autoinst/openQA/4698/workflows/3fc8c9cf-feb8-435d-b868-76fee3b20bb7/jobs/44844
showed that the test still can fail:
```
[09:55:15] t/full-stack.t .. 374/? # full result panel contents:
[09:55:15] t/full-stack.t .. 376/?
[09:55:15] t/full-stack.t .. 377/?
Bailout called.  Further testing stopped:  findElement: no such element: Unable to locate element: {"method":"css selector","selector":"#log"} at /home/squamata/project/t/lib/OpenQA/SeleniumTest.pm:101
FAILED--Further testing stopped: findElement: no such element: Unable to locate element: {"method":"css selector","selector":"#log"} at …
```
> Makefile: Add back retries for full-stack.t after sporadic failure

- docker/worker/Dockerfile
- docker/worker/kvm-mknod.sh
Docker image didn't build. This PR solves the problems:
Problem: gunzip is not in the repositories anymore. 
Solution: gzip replaces gunzip
Problem: when /proc/config.gz doesn't exists the execution of kvm-mknod.sh during the build fails. 
Solution: check that /proc/config.gz exists before to use this
Problem: kvm-mknod.sh tries to create /dev/kvm failing if exists
Solution: check /dev/kvm before
https://progress.opensuse.org/issues/43715
> Docker: Fix worker dockerfile 

- t/34-developer_mode-unit.t
The function "dump_websocket_state" has been introduced with fc67d9bbf
but is not actively used. We should not keep disabled code around which
leads to cluttered source code and in the end likely debugging is
conducted differently anyway or the "useful debug code" is overlooked.
Removing the dead code here also ensures 100% statement coverage of the
complete test module.
Related progress issue: https://progress.opensuse.org/issues/71857
> t: Remove unused debug code to ensure 100% statement coverage in 34-developer-mode-unit.t

- t/full-stack.t
- t/lib/OpenQA/Test/FullstackUtils.pm
- The current timeout claims to be one minute but it doesn't take the time actually slept into account.
- Maybe we should increase the timeout since it occasionally fails on CI.
See: https://progress.opensuse.org/issues/76900
> FullStackUtils: More generous wait on developer console

- Makefile
- docker/README.md
- docker/worker/Dockerfile
- docker/worker/kvm-mknod.sh
- docker/worker/launch_workers_pool.sh
- docker/worker/run_openqa_worker.sh
Problem: To launch a pool of workers is a manual process
Solution: To prevent manual errors and work the script
launch_workers_pool.sh creates a pool of workers in one call.
Related with https://progress.opensuse.org/issues/43715
> Add an easy way to run a pool of workers

- docker/worker/kvm-mknod.sh
There is a problem with the shellcheck in this file
... test $(gzip -c /proc/config.gz | grep CONFIG_KVM=y))
^-- SC2046: Quote this to prevent word splitting.
> Fix kvm-mknod.sh shellcheck

- lib/OpenQA/Worker/Engines/isotovideo.pm
This is a small followup to #3476. [Socket I/O error](https://lxadm.com/Rsync_exit_codes) is very similar to the rsync exit codes already covered by the other PR and should also trigger a retry.
Progress: https://progress.opensuse.org/issues/69553
> Retry on rsync error code 10

- docs/Installing.asciidoc
Make the code section simpler with moving the "get root" part into the
description in before.
Related progress issue: https://progress.opensuse.org/issues/76978
> docs: Simplify the curl based bootstrap instruction

- docker/README.md
* Fix typos, grammar, missing articles
* Consistently wrap at 78 characters
* Avoid contractions
* Consolidate on names, e.g. "openQA web UI"
* Add missing markup, e.g. for verbatim terms
> docker: Improve complete README document

- lib/OpenQA/Downloader.pm
- t/25-cache.t
Before:
```
ok
All tests successful.
Files=1, Tests=78, 48 wallclock secs ( 0.03 usr  0.00 sys +  1.14 cusr  0.18 csys =  1.35 CPU)
Result: PASS
```
After:
```
ok
All tests successful.
Files=1, Tests=78,  5 wallclock secs ( 0.03 usr  0.01 sys +  1.13 cusr  0.10 csys =  1.27 CPU)
Result: PASS
```
Progress: https://progress.opensuse.org/issues/77032
> Speed up 25-cache.t

- t/34-developer_mode-unit.t
This reverts commit bbcead4e3fa7272ce28ba1d57b216b0a4bd32fd6 as
t/34-developer_mode-unit.t fails often in local runs, in circleCI as
well as our OBS checks.
Using https://github.com/okurz/scripts/blob/master/count_fail_ratio I ran
```
count_fail_ratio prove -l t/34-developer_mode-unit.t
```
and found
```
```
with the failures being stopped by the timeout and increasing timeout does not help – as https://github.com/os-autoinst/openQA/pull/3510 already showed yesterday.
Reverting your PR shows
```
```
Related progress issue: https://progress.opensuse.org/issues/71857
> Revert "No empty IOLoop timer for 5 second wait" to fix current test failures

- lib/OpenQA/Worker.pm
- lib/OpenQA/Worker/Job.pm
- t/24-worker-jobs.t
- t/24-worker-overall.t
- t/data/24-worker-overall/workers.ini
This reverts commit 1786e30b528cb888fa49474d39cd25b80415d629 to prevent
raw IP addresses being shown in web UIs.
Related progress issue: https://progress.opensuse.org/issues/77014
> Revert "worker: Use WORKER_HOSTNAME instead of real hostname"

- t/25-downloader.t
Zero actually stands for an infinite timeout which is not what we want here.
> Remove infinite timeout the downloader test

- lib/OpenQA/CacheService/Client.pm
- t/25-cache-client.t
- t/25-cache-service.t
The commit 99746775b added retrying. There have been cases where 3*5s
have not been enough retries so this commits bumps up the values to also
cover longer unavailablities of the openQA webUI.
Related progress issue: https://progress.opensuse.org/issues/71185
> Cover much longer web UI unavailabilities in the cache service client

- docker/devel:openQA:ci/base/Dockerfile
Reference:
https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.building.html#id-1.5.8.3.8
The combination of a heavy image in combination with downloading from
slow registry.opensuse.org to circleCI workers have a significant impact
causing frequent failures in the "cache" step of circleCI when the 542MB
blob of the base image is downloaded. As we can not configure circleCI
to retry the download or apply a longer timeout than 20 minutes this
means that manual interaction is necessary to retry.
This commit changes the base image to preserve individual layers within the
container image which makes downloading much more likely to succeed.
See test in https://github.com/os-autoinst/openQA/pull/3527
Related progress issue: https://progress.opensuse.org/issues/67855
> docker: Ask to not squash base image layers to fix circleCI download

- docker/worker/Dockerfile
- docker/worker/kvm-mknod.sh
Problems
- kvm-mknod shouldn't fail if /proc/config.gz doesn't exist
- kvm-mknod was copied to the wrong directory
> docker: Fix kvm-mknod script in worker container

- dependencies.yaml
- lib/OpenQA/CacheService.pm
- lib/OpenQA/CacheService/Model/Cache.pm
- openQA.spec
- t/25-cache.t
So far it is not guaranteed that an asset is preserved from purging while
being downloaded. Considering that we've seen cases where an asset is
immediately purged after its own download to make room for itself it also
makes sense to prevent an asset from being purged while being downloaded.
Note that an asset's last use is only updated after but not during its
download. So assets are "aging" while being downloaded and old assets are
preferred by the purging algorithm.
See https://progress.opensuse.org/issues/71827#note-14
> cache service: Avoid purging assets which are currently being downloaded

- lib/OpenQA/Task/Job/FinalizeResults.pm
- t/14-grutasks.t
The openQA job likely just has been removed. Removing an openQA job
while the finalize Minion job is being executed would still screw
things up.
See https://progress.opensuse.org/issues/75073
> Consider finalize jobs successful if the openQA job does not exist

- t/34-developer_mode-unit.t
Avoid creating a timer conditionally and always act on the timeout.
Manual verification:
1. Try e.g. `make coverage TESTS=t/34-developer_mode-unit.t | grep 't/34-developer_mode-unit.t.'` toverify if the fix works locally
2. See if CircleCI agrees.
See: https://progress.opensuse.org/issues/71857
> coverage: unconditional finished_handled timeout

- docker/webui/Dockerfile-lb
Problem: OBS cannot deal with the current repositories format (obs://)
More info at openSUSE/open-build-service#10438
Solution: Change the repositories to be downloaded from
http://download.opensuse.org
Problem: OBS doesn't have a correct tag when build the images
Solution: Provide a tag
https://progress.opensuse.org/issues/43712#change-346618
> docker: Fix web UI Dockerfile-lb to be buildable on OBS 

- .gitignore
Mojo::Log writes to log/ if it exists instead of outputting content to
the calling terminal which can be confusing for local development. If
one has a log/ dir we can at least show it up as untracked by git :)
> Remove log/ and log_test_postgresql from .gitignore which can confuse developers

- docker/webui/Dockerfile
Problem: OBS cannot deal with the current repositories format (obs://)
There is more information on this problem at 
https://github.com/openSUSE/open-build-service/issues/10438
Solution: Change the repositories to be downloaded from
http://download.opensuse.org
Problem: OBS doesn't have a correct tag when build the images
Solution: Provide a tag
https://progress.opensuse.org/issues/43712#change-346618
> Docker: Fix web UI Dockerfile to be buildable on OBS

- docker/worker/Dockerfile
- docker/worker/run_openqa_worker.sh
Problem: OBS cannot deal with the current repositories format (obs://)
More info at openSUSE/open-build-service#10438
Solution: Change the repositories to be downloaded from
http://download.opensuse.org
Problem: OBS doesn't have a correct tag when build the images
Solution: Provide a tag
Problem: kvm operations cannot be instantiated during the building 
because the workers may have kvm but the build machine don't
have to
Solution: Move script execution to the container execution time
Problem: OBS cannot build the image with the old way of choosing 
to install between the x86 or ARM package. 
Solution Since the objective is to create the image for x86, the ARM 
part is eliminated
https://progress.opensuse.org/issues/43715
> Docker: Fix worker Dockerfile to be buildable on OBS

- lib/OpenQA/CacheService.pm
- lib/OpenQA/CacheService/Model/Cache.pm
- lib/OpenQA/CacheService/Model/Downloads.pm
- script/openqa-workercache
- t/25-cache-service.t
- t/25-cache.t
* See https://progress.opensuse.org/issues/67000#note-28
* Extend checks for broken database (see commit message for details)
* Stop service after a critical database error
* Example output:
```
<6>[15849] [i] Listening at "http://[::1]:9530"
<7>[15849] [d] [f36HfV4M] GET "/info"
<7>[15849] [d] [f36HfV4M] Routing to controller "OpenQA::CacheService::Controller::API" and action "info"
<3>[15849] [e] some non critical error at /usr/lib/perl5/vendor_perl/5.32.0/Minion/Backend/SQLite.pm line 366.
<7>[15849] [d] [f36HfV4M] 500 Internal Server Error (0.002338s, 427.716/s)
<7>[15849] [d] [J-Go_bwG] GET "/info"
<7>[15849] [d] [J-Go_bwG] Routing to controller "OpenQA::CacheService::Controller::API" and action "info"
<3>[15849] [e] DBD::SQLite::st execute failed: database disk image is malformed at …
```
> Stop cache service after critical database error

- lib/OpenQA/CacheService/Model/Cache.pm
- t/25-cache.t
* Run vacuum when repairing SQLite database
* Without this change the database repairing will throw away
databases needlessly due to `Page 2923 is never used`
reported by the integrity check
* See https://progress.opensuse.org/issues/67000
> cache service: Avoid throwing away database needlessly

- lib/OpenQA/JobSettings.pm
- lib/OpenQA/Utils.pm
- t/api/02-iso-download.t
This is an alternative to #3560 , using the approach suggested by @Amrysliu (thanks) - we split up the "generate FOO from FOO_URL" and "produce download list" parts of `create_downloads_list` so we can do the "generate FOO from FOO_URL" part before handling placeholders. This should fix the issue with placeholders referring to _URL-parsed settings that I identified in comments on #3309 .
We also "properly" fix the issue with a test suite or similar wanting to set a potentially-_URL-parsed setting to a false-y value that's discussed in https://github.com/os-autoinst/openQA/pull/3560#issuecomment-729103247 , by changing the test we use to decide whether to set the short form to check if it's already defined, rather than checking if it evaluates true.
> Handle placeholders after parsing _URL settings, don't set FOO from FOO_URL if FOO is defined but false

- lib/OpenQA/CacheService/Model/Cache.pm
* Otherwise the re-indexing seems not visible and we run into the die.
* I've tested this with a broken SQLite file from o3 worker openqaworker4
and only with this change 'Unable to fix errors… Purging cache directory…'
is prevented and instead 'Database integrity check passed' shown.
* Note that unlinking the SQLite file (log message 'Purging cache
directory…') is actually problematic:
https://www.sqlite.org/howtocorrupt.html#_unlinking_or_renaming_a_database_file_while_in_use
* See https://progress.opensuse.org/issues/67000
> cache service: Do not perform re-indexing within a transaction

- .circleci/config.yml
The COMMIT_AUTHOR_EMAIL from &docker_config is not available
in &dependencybot
And for example `git-subrepo` seems to stumble over the empty email address.
> Add git email address for dependency bot

- docker/devel:openQA:ci/base/Dockerfile
Reverts #3536 as we had multiple problems, e.g. see #3572 for trying to fix the problems encountered in CI pipelines
> Partially revert "circleci: Strip down base image to prevent "cache" jobs failing" due to failures

- dependencies.yaml
- dist/rpm/openQA.spec
- lib/OpenQA/CacheService/Model/Cache.pm
- profiles/apparmor.d/usr.share.openqa.script.worker
- t/25-cache.t
Other processes might still have an open database connection. According to
sqlite.org/howtocorrupt.html#_unlinking_or_renaming_a_database_file_while_in_use
this can lead to database corruption.
This commit triggers killing all processes that access the relevant
files that we removed. This kills, not terminates, to prevent any other
processes even flushing or anything. Also we effectively kill the own
process which is a good thing here
The scope that started the cache services must then handle any restarts.
With our systemd services we already do that automatically. For this
note that openqa-worker-cacheservice-minion depends on
openqa-worker-cacheservice so if openqa-worker-cacheservice restarts
this also triggers a restart of openqa-worker-cacheservice-minion but
not the other way …
> worker cache: Try to prevent any process accessing still malformed database file handles

- lib/OpenQA/CacheService/Model/Cache.pm
- t/25-cache.t
If we encounter integrity errors in database files we should treat the
database as corrupted and not try any repair attempts which might make
the problem worse by hiding the underlying root causes.
Related progress issue: https://progress.opensuse.org/issues/67000
> worker cache: Prevent hiding errors due to repair attempts in corrupted database

- dist/rpm/openQA.spec
The service openqa-auto-update might trigger an update of the package
that includes the service openqa-auto-update itself which would trigger
a stop request for the service which can not be fulfilled as rpm does
not react on termination when trying to stop a systemd service causing a
deadlock until the service is killed which triggers errors despite
everything else seems to work just fine.
This commit changes the package pre/post scripts to only touch the timer
and not the service. I think it's fine because the script that is
started by the service has nothing to do with any other files from the
package. So I consider it safe because the script would already be fully
in memory during execution while the according service and package might
be replaced in an upgrade.
This is inspired by …
> systemd: Prevent error reports in journal of openqa-auto-update service

- .mergify.yml
Reverts os-autoinst/openQA#3452
The Mergify behavior doesn't seem to work as well as intended. It's come up a few times that it causes considerable delay and very often gets *stuck* because rebasing causes a failure or a failure prevents it from trying to rebase in the first place.
On the bright side we have [poo#76738](https://progress.opensuse.org/issues/76738) with a proposal for a better solution.
> Revert "Enable strict merge on Mergify"

- lib/OpenQA/CacheService/Model/Cache.pm
- t/25-cache.t
* Pass full path to `fuser` to avoid
`Specified filename cache.sqlite* does not exist.`
* Remove files after calling `fuser` because otherwise it has no effect.
* See https://progress.opensuse.org/issues/80202#note-8
> cache service: Fix workaround for deleting broken database

- assets/stylesheets/dashboard.scss
Problem: The right side of some build bars of is
misaligned when the screen is less wide than 880
pixels. This occurs because some bars have more
text than others and this text forces a minimum size.
Solution: a minimum size is set for all bars to
ensure the maximum possible text size.
https://progress.opensuse.org/issues/77929
> Fix UI build bar alignment broken on index page

- lib/OpenQA/CacheService.pm
- t/25-cache.t
* Tested on one of our production workers for almost 24 hours and the usual problems (see https://progress.opensuse.org/issues/67000) have not occurred yet.
* Match SQLite's default
> cache service: Use DELETE journaling mode by default

- lib/OpenQA/Script/Client.pm
Tested manually by putting a true unicode character into an openQA
job comment and reading that with
```
script/client --host openqa.suse.de --json-output jobs/$job/comments
```
Related progress issue: https://progress.opensuse.org/issues/76912
> client: Fix warning "Wide character in print"

- lib/OpenQA/WebSockets.pm
- lib/OpenQA/WebSockets/Controller/Worker.pm
- lib/OpenQA/WebSockets/Model/Status.pm
As mentioned in
https://github.com/os-autoinst/openQA/pull/3588#discussion_r529614510
likely we can get rid of the "worker_status" property completely.
Related progress issue: https://progress.opensuse.org/issues/80298
> Remove obsolete websockets module property "worker_status"

- t/05-scheduler-full.t
Some steps are only sometimes reached based on timing behaviour in our
tests which we can not rely upon. So we should mark the according
statements as uncoverable to show us that we have covered everything
coverable as well as provide consistent coverage reports.
Related progress issue: https://progress.opensuse.org/issues/80268
> t: Fix flaky/incomplete coverage in 05-scheduler-full with uncoverable statements

- lib/OpenQA/WebAPI.pm
See https://progress.opensuse.org/issues/80492
> Fix description in 404 page for table APIs

- t/05-scheduler-restart-and-duplicate.t
- t/16-utils-runcmd.t
- t/40-script_load_templates.t
- t/ui/25-developer_mode.t
- t/ui/28-keys_to_render_as_links.t
To lower runtimes in tests when using the default parameter we should be
explicit about which fixtures are needed as already done in other test
modules.
Related progress issue: https://progress.opensuse.org/issues/71500
> t: Use fixtures explicitly in more tests to speedup runtime

- script/openqa-livehandler
- script/openqa-websockets
- t/44-scripts.t
* The return value is always `undef` and therefore not meaningful to pass as
exit code. Besides, passing `undef` here leads to Perl warnings, see
https://progress.opensuse.org/issues/80576.
* Invalid arguments should be handled (and tested) within Mojolicious itself.
It actually already handles invalid arguments within a command and invalid
commands. For now I've adjusted the tests pass invalid flags all scripts
consider invalid at this point.
* With Mojolicious 8.67 it will also work in the case the tests tried so far:
https://github.com/mojolicious/mojo/commit/d0093749c73557bf0be66f76f541749667d04511
I've already tested the Mojolicious commit together with this commit. The
Mojolicious commit also contains a unit test so I wouldn't add another
test in openQA itself as the scripts tests …
> Don't try to use return value from run function as exit code

- lib/OpenQA/WebSockets.pm
Statements that are currently not covered by tests or do not yield
reliable coverage results are marked as explicitly uncoverable to mark
all what *is* covered and also to prevent flaky coverage results.
Related progress issue: https://progress.opensuse.org/issues/80298
> Mark exceptional websocket error handling as explicitly untested for coverage

- t/43-scheduling-and-worker-scalability.t
* I've also ran it locally with a higher job/worker count and it still
works.
* I still allow to opt-out because this test can be useful when
developing to track scheduling and worker-job assignment issues and
then one might find this disturbing.
* See https://progress.opensuse.org/issues/78390
> Test whether worker still accepts jobs when a configured web UI is offline

- lib/OpenQA/CacheService/Model/Cache.pm
I never saw that this check took effect in production. Either the database
was completely screwed and we failed before or the integrity check which
is done afterwards only showed issues.
> cache service: Remove creating/dropping table to test database

- script/load_templates
See https://progress.opensuse.org/issues/80662
> load_templates: Use ref instead of reftype to avoid Perl warning

- lib/OpenQA/Schema.pm
- script/initdb
- script/upgradedb
- t/deploy.t
I found that our statement coverage analysis showed the
"sqlt_deploy_hook" methods that we have in OpenQA::Schema::Result were
never covered. As I learned from my helpful colleagues these methods are
never called from production code but only if users explicitly trigger
"initdb" or "upgradedb" for schema initialization scripts.
This commit adds a corresponding test to t/deploy.t which triggers the
exact same workflow users would follow for a schema version bump with
the mere difference that the test does not change our source files
directly but works with a schema version environment override and
writing the schema initialization and upgrade files into a temporary
directory. With this all "sqlt_deploy_hook" methods are called and
included in code coverage reports. A simple mutation test …
> t: Add full schema init+upgrade cycle test

- templates/webapi/not_found.html.ep
* Remove route names because these names are not really useful for a user
* Rename the "Pattern" column to "Path" despite the use of placeholders
because "Path" is still the more commonly used term
> Improve 404 page

- docs/Installing.asciidoc
- etc/openqa/openqa.ini
- lib/OpenQA/Schema/Result/Jobs.pm
- lib/OpenQA/Task/Job/FinalizeResults.pm
- t/10-jobs.t
If a job is done, especially if no label could be found for carry-over,
often more steps are needed for the review of the test result or
providing the information to either external systems or users. As there
can be very custom requirements we should offer a point for
optional configuration to let the instance administrators define
specific actions.
There is already an approach called "auto-review"
https://github.com/os-autoinst/scripts/#auto-review---automatically-detect-known-issues-in-openqa-jobs-label-openqa-jobs-with-ticket-references-and-optionally-retrigger
which offers helpful, external scripts. With this commit it is possible
to call external scripts if defined and based on the selected either
environment variables or config settings. For example config settings
for …
> Add possibility to call custom hook scripts on "job done" based on result

- lib/OpenQA/Constants.pm
- lib/OpenQA/Worker/Engines/isotovideo.pm
- lib/OpenQA/Worker/Job.pm
- t/24-worker-engine.t
- t/24-worker-jobs.t
* Use `asset failure: …` if an asset could not be downloaded by the cache
service due to an 4xx error
* Use `asset failure: …` if an asset can not be located locally if the
cache service is disabled
* Use `cache failure: …` if the cache service returned an error
* Keep  using `setup failure: …` in other cases, e.g. isotovideo can not be
started
* See https://progress.opensuse.org/issues/80202#note-15
> Distinguish different types of setup failures

- docs/Installing.asciidoc
- lib/OpenQA/Setup.pm
- t/10-jobs.t
As it turned out reading job hook settings from configuration does not
work for a separate GRU service. Likely because this service never reads
the config file /etc/openqa/openqa.ini . Hence it is questionable if we
want to support reading from the generic config file considering that
the GRU service is standalone and can be run in a separate environment,
e.g. a separate host or container.
This commit removes the ineffective code for reading the config settings
and also clarifies some further caveats in the documentation, e.g.
apparmor rules as well as where the overall status can be found.
Related progress issue: https://progress.opensuse.org/issues/80736
> Clarify caveats with custom job hooks after 6cf76ae8b

- docker/webui/run_openqa.sh
When web UI is executed in a container executes the script run_openqa.sh
if this is executed in the default mode with all components together
uses the function all_together_apache(). This function has some errors
that avoid the execution of the scheduler, websockets and livehandler
because some parameters for the command start_daemon are missing.
Additionally the same simplification applied here to the gru daemon
is also applied to the function gru() which is used by the load balance
execution mode.
progress.opensuse.org/issues/80534
> docker: Fix web UI container script in basic execution

- docs/UsersGuide.asciidoc
Add a clarification that the carry-over works based on failed test
modules and add an alternative proposals which is more suitable for
incomplete jobs as well based on hook scripts, e.g. the "auto-review"
procedure.
Related progress issue: https://progress.opensuse.org/issues/80746
> docs: Explain the concept of "carry-over" better

- docs/Installing.asciidoc
- etc/openqa/openqa.ini
- lib/OpenQA/Schema/Result/Jobs.pm
- lib/OpenQA/Setup.pm
- t/api/04-jobs.t
- t/config.t
* It is possible to configure the regex being used
* It is possible to disable this kind of automatic cloning
* See https://progress.opensuse.org/issues/80202#note-15
---
* ~~Based on https://github.com/os-autoinst/openQA/pull/3618 which could be reviewed individually first~~ rebased on master after #3618 was merged
* See last commit for only the additional change
> Clone incompletes caused by cache service errors automatically

- Makefile
- dist/rpm/openQA.spec
- etc/openqa/workers.ini
- lib/OpenQA/Worker.pm
- lib/OpenQA/Worker/Job.pm
- lib/OpenQA/Worker/Settings.pm
- t/24-worker-overall.t
- t/24-worker-settings.t
See https://progress.opensuse.org/issues/80986
Besides the unit tests I've also conducted 2 full test runs (one with and one without the configuration) and both worked as expected.
> Allow configuring the worker to terminate after all jobs have been processed

- lib/OpenQA/Worker.pm
- t/24-worker-overall.t
When the worker checks for the availability of the cache service the normal
behavior of the cache service client is applied (huge number of attempts,
high inactivity timeout). This is not nice for the availability check
because it leads to the worker getting stuck and not even reacting to
signals.
---
By the way, to reproduce this, just configure the worker to use the cache
service but don't start it. Then you can not stop the worker via `Ctrl+C`.
> Avoid worker from appearing stuck (e.g. not reacting to SIGTERM) on cache check

- lib/OpenQA/Worker/Engines/isotovideo.pm
* The check has been introduced with
https://github.com/os-autoinst/openQA/pull/3418 in order to match
messages like
```
Purging "…" because we need space for new assets, reclaiming …
```
* See https://progress.opensuse.org/issues/71827#note-11
* The regex it too generic and therefore matches in unrelated cases, e.g.:
```
Purging "…" because of too many download errors
```
* See https://progress.opensuse.org/issues/81022#note-5 as well
> Refine check for error message about immediately pruned assets

- t/24-worker-overall.t
- t/lib/OpenQA/Test/Utils.pm
See particular commit messages and https://github.com/os-autoinst/openQA/pull/3646#issuecomment-746967848
I wasn't able to fix the coverage for the `c_worker` function. Somehow the coverage collection via `Devel::Cover::report() if Devel::Cover->can('report');` doesn't work. (Increasing the time before we send `SIGKILL` didn't work.)
> Improve worker tests

- lib/OpenQA/Worker/Settings.pm
- t/24-worker-settings.t
* and not vice verca; environment settings should have precedence unless
they are empty.
* This is also consistent with how it is already documented.
* This change also prevents the following warning showing up in the
fullstack test:
```
[10:23:04] t/full-stack.t .. 16/? Use of uninitialized value $vars{"TERMINATE_AFTER_JOBS_DONE"} in concatenation (.) or string at /home/squamata/project/script/../lib/OpenQA/Worker/Engines/isotovideo.pm line 314.
```
> Override TERMINATE_AFTER_JOBS_DONE setting from environment variable

- lib/OpenQA/Worker.pm
- t/24-worker-overall.t
* Fix regression of d3d33b54affa617d9c54a2eac40804d9d1da2f51
* See https://progress.opensuse.org/issues/81228
> worker: Fix clearing current error on status updates when idling

- profiles/apparmor.d/local/usr.share.openqa.script.openqa
- profiles/apparmor.d/usr.share.openqa.script.openqa-cli
From openqa.opensuse.org we can store already existing "site-specific"
apparmor profile extensions to save our necessary configuration for
openqa-trigger-from-obs and "job done" hooks.
Related progress issue: https://progress.opensuse.org/issues/80830
> profiles: Add examples for "site-specific" apparmor profiles extensions

- script/openqa-bootstrap
Ticket: https://progress.opensuse.org/issues/81064
qemu-hw-display-virtio-gpu-pci is not required but only recommended.
So it needs to be explicitly installed.
> Install qemu-hw-display-virtio-gpu-pci in openqa-bootstrap

- tools/generate-documentation
This way one does not need to install asciidoctor-pdf which is not packaged
for Tumbleweed.
> Allow skipping generation of PDF documentation

- script/fetchneedles
Follow-up for #3658
See: https://progress.opensuse.org/issues/81180
> fetchneedles: Do a quiet git reset to avoid log spam

- templates/webapi/branding/openSUSE/external_reporting.html.ep
According to the mail "Opening our Bugzilla - SLE 15 SP3 QA bugs" sent to
the "qa-team" mailing list the Bugzilla product name for certain for SLE 15
SP3 product changes. This commit adjusts our error reporting template
accordingly. It takes only the products mentioned within that mail into
account but the approach allows to add more public products easily later.
> Adjust Bugzilla links for SLE 15 SP3 products to add new "PUBLIC" prefix

- lib/OpenQA/UserAgent.pm
When trying to debug why e.g. `/etc/openqa/client.conf` is not working it might be because `~/.config/openqa/client.conf` takes precedence. That could be seen more easily if we print the filename verbosely.
See: [poo#820670](https://progress.opensuse.org/issues/820670)
> client: Log what config file is being read

- templates/webapi/branding/openSUSE/external_reporting.html.ep
@jlausuch 
> Looks like the change `Add SUSE Linux Enterprise Micro in the external reporting`
> in this PR https://github.com/os-autoinst/openQA/pull/3678
> didn’t work..
> I don’t see the “bug” icon when clicking on some frame…
> https://openqa.suse.de/tests/5318460#step/disk_boot/7
> Any ideas why?
It needs it own branch and apparently the product name does not contain the `VERSION` here.
> Fix error reporting link for SLE Micro

- script/openqa-clone-custom-git-refspec
I spent a little while being confused why a change wasn't working like I expected. Turns out clone-custom-refspec relies on the system path.
I would expect all commands calling into each other to be from the same install. Which is predictable. And avoids potential incompatibilities.
> clone-custom-git-refspec: Call clone-job from same install

- docs/Installing.asciidoc
* See https://progress.opensuse.org/issues/80908#note-10
---
<s>Still a draft because I want to test whether it actually works on a staging worker (in particular whether the globbing in the example works as expected).</s> The comand `systemctl kill --signal SIGHUP 'openqa-worker-auto-restart@*.service'` works on our staging worker as expected. All currently active worker units (10 slots in this case) receive the signal and are restarted.
> Document restarting workers without interrupting ongoing testing

- docs/Installing.asciidoc
This number is called instance number in accordance with the workers help
and command line options. The instance number has nothing to do with the
worker IDs used by the web UI to track workers.
> doc: Avoid calling the worker instance number 'worker id'

- lib/OpenQA/UserAgent.pm
This reverts commit b3ee9d2139dd77d6ad8ddebfb597fd81af7ad9f8. (https://github.com/os-autoinst/openQA/pull/3679)
Issue: https://progress.opensuse.org/issues/88053
> Revert "client: Log what config file is being read"

- .circleci/ci-packages.txt
- container/travis_test/Dockerfile
- cpanfile
- dependencies.yaml
- dist/rpm/openQA.spec
- etc/openqa/openqa.ini
- lib/OpenQA/Setup.pm
- lib/OpenQA/Worker/Job.pm
- t/24-worker-jobs.t
Relate: https://progress.opensuse.org/issues/80334
> Automatically rerun incompleted jobs because of no space left

- lib/OpenQA/Utils.pm
- lib/OpenQA/Worker/Engines/isotovideo.pm
- t/24-worker-engine.t
- t/43-scheduling-and-worker-scalability.t
1. symlink test repository from CASEDIR to POOLDIR (using CASEDIR's 
basename as the destdir name).
2. set the CASEDIR and PRODUCTDIR as relative values.
3. when uing `openqa-clone-custom-git-refspec`, set the NEEDLES_DIR to
`needles`, because code in openQA worker will symlink the needles
directory to it.
Verify run:
The source job run on a remote worker: http://10.67.19.103/tests/413
The clone job run on a local worker: http://10.67.19.103/tests/414#settings
A simple case use relative path as CASEDIR and PRODUCTDIR: http://10.67.19.103/tests/408/file/vars.json
Relate: https://progress.opensuse.org/issues/80372
> Symlink CASEDIR and set values to relative path

- lib/OpenQA/Utils.pm
- lib/OpenQA/Worker/Engines/isotovideo.pm
- t/24-worker-engine.t
- t/43-scheduling-and-worker-scalability.t
Reverts os-autoinst/openQA#3604 due to the report in
https://github.com/os-autoinst/openQA/pull/3604#issuecomment-765888161
> Revert "Symlink CASEDIR and set values to relative path"

- .circleci/ci-packages.txt
- t/lib/OpenQA/Test/PatchDeparse.pm
Issue: https://progress.opensuse.org/issues/40895
Now also $expr2 seems to be uninitialized.
Use of uninitialized value $expr2 in concatenation (.) or string at /home/squamata/project/t/lib/OpenQA/Test/PatchDeparse.pm line 44.
Use of uninitialized value $expr2 in substitution (s///) at /home/squamata/project/t/lib/OpenQA/Test/PatchDeparse.pm line 43.
Also update the version to 1.54 (perl 5.32.0) since the sub hasn't changed.
> Update patch for B::Deparse

- Makefile
- dist/rpm/openQA.spec
- docs/Installing.asciidoc
- systemd/openqa-reload-worker-auto-restart@.path
- systemd/openqa-reload-worker-auto-restart@.service
* As long as e.g. `openqa-soft-restart-worker@1.path` is running
the worker started via the corresponding service unit
`openqa-worker-auto-restart@1.service` is restarted as soon as it
becomes idle (and immediately if it is already idling) when
`/etc/openqa/workers.ini` is edited.
* See https://progress.opensuse.org/issues/80910
and https://progress.opensuse.org/issues/80908#note-8
---
* ~~We could actually also watch for a packaged file so it would also apply
to package updates.~~ Maybe that's better done on RPM level as suggested in https://progress.opensuse.org/issues/80908#note-8 (point 2.)?
* Then we could also get rid of `OPENQA_WORKER_TERMINATE_AFTER_JOBS_DONE=1`
in the auto-restart service file.
> Add service files to restart worker after config changes without interrupting running jobs

- t/09-job_clone.t
This adds test coverage for the regression addressed by #3688.
- In non-verbose mode there should be no output in normal operation.
- In verbose mode a dump of the job settings is expected.
> tests: Test expected output from job cloning

- lib/OpenQA/CacheService/Client.pm
- t/25-cache-client.t
* Mojo::UserAgent::socket_options is available as of Mojolicious 8.72 so
when using at least this version "Running patched getaddrinfo() …" should
no longer occur within the debug log
* See https://progress.opensuse.org/issues/78390
> Use Mojo::UserAgent::socket_options if available to avoid relying on monkey patch

- lib/OpenQA/Schema/Result/Jobs.pm
- t/10-jobs.t
Otherwise we would take files which are symlinks into account twice. Note
that the screenshots are already taken into account when they are deleted
at their real location. So it makes no sense to consider their real size
when deleting their symlinks within the results directory of a job.
---
(part of https://progress.opensuse.org/issues/76984)
> Return size of symlink (and not its target) when deleting job results

- dist/rpm/openQA.spec
* Only affects `openqa-worker-auto-restart@.service` units but not other
worker units
* Does nothing if no such units are running
* The shell code is adapted from the `%service_del_postun` macro (from
`/usr/lib/rpm/macros.d/macros.systemd` as provided by the
`systemd-rpm-macros` package)
* See https://progress.opensuse.org/issues/80908#note-8
> Restart openqa-worker-auto-restart@.service on pkg upgrade without interrupting jobs

- systemd/openqa-reload-worker-auto-restart@.service
to avoid
```
openqaworker-arm-1 systemd[1]: /usr/lib/systemd/system/openqa-reload-worker-auto-restart@.service:6: Executable path is not absolute: systemctl kill --signal SIGHUP openqa-worker-auto-restart@%i.service
```
when using it on production workers with older systemd version.
Related ticket: https://progress.opensuse.org/issues/80908#note-8
> Use full path in openqa-reload-….service to support

- script/create_admin
a2d64957 inadvertently broke this script. It kept a check that
bails out unless ARGV is longer than 1, which was I think meant
to at least make sure the user passed more than one argument, but
moved option parsing to *before* that check. GetOptions consumes
the items it parses, so if you run the script as intended, then
after option parsing is done, only one thing is left in ARGV (the
user ID) and the check fails. You could force the script to run
by putting some extra argument after the user ID, but otherwise
it would always bail out.
This fixes it by moving the ARGV length check back to before we
parse the options. It seems like an odd check to me - why do we
want to check just that *at least one* of the allegedly-optional
arguments is passed? - but I figured for now minimal change is …
> Fix create_admin by not expecting ARGV after parsing it

- t/25-cache.t
This is an optional follow-up to https://github.com/os-autoinst/openQA/pull/3590 with additionally replacing Mojo::IOLoop::ReadWriteProcess with IPC::Run which we might consider a better long-term choice.
> t: Simplify 25-cache.t with IPC::Run instead of Mojo::IOLoop::ReadWriteProcess

- .circleci/config.yml
- Makefile
- docs/Contributing.asciidoc
- t/10-jobs.t
- t/14-grutasks.t
- t/32-openqa_client.t
- t/44-scripts.t
Combine "scheduler"+"developer" test runs into one to save time
Both the scheduler-tests as well as developer-tests in relation to other
test runs do not take that long in comparison. Hence we can save time by
combining both test runs, save one circleCI job while saving the time
for duplicate test run setup.
Mark known slow tests as "heavy" so that it is easier to separate good
and fast tests from slow ones and to prevent premature Makefile-level
timeouts due to recent slowdown observed in CI environments.
Related progress issue: https://progress.opensuse.org/issues/88496
> Prevent test timeouts with the introduction of "heavy" tests

- script/openqa-bootstrap-container
Older versions of systemd-run do not have the `-P` parameter. We
originally envisioned that newer versions of Leap would get support but
as the main version of systemd stays the same as in the SLE15 codestream
understandably also the parameters stay the same.
This commit actively checks if the parameter is available. If it is
available it is used, otherwise it will output a message to the user
accordingly.
This is based on a user support question brought up in text chat.
> script: Fallback to running openqa-bootstrap-container without pipe

- lib/OpenQA/CacheService/Client.pm
- t/ui/12-needle-edit.t
This conversion was started in #3704 with one method. Converting the rest now too should be very harmless.
> Use signatures for all OpenQA::CacheService::Client methods

- docs/Contributing.asciidoc
This PR extends the code style section with a few rules for how to get the most value out of [signatures](https://perldoc.perl.org/perlsub#Signatures). So far it only discourages the most risky features (sub attribute order and complex computational default values). But i'm happy to bikeshed about what might be best for openQA specifically. How we activate signatures consistently, or if we want to use nameless parameters at all for examples would be candidates.
~~While looking at the use statement section, i noticed that the order was incorrect (`use lib` statements should have been higher up), and fixed that too.~~ Changed that back after noticing that the order in most of our tests is random and nobody follows the code style section anyway. 🤦 So that topic is for a future PR.
> Document how to use Perl signatures

- lib/OpenQA/Scheduler/Model/Jobs.pm
- t/43-scheduling-and-worker-scalability.t
- t/full-stack.t
- t/lib/OpenQA/Test/FullstackUtils.pm
by ensuring the worker property WEBSOCKET_API_VERSION (which is checked by
the scheduler) is passed before considering worker idle.
---
I thought I might be able to reproduce poo#80800 via the scalability test, see https://progress.opensuse.org/issues/80800#note-12. However, I didn't actually manage to do this. This PR fixes *another* issue I found along the way.
> Stabilize scalability and fullstack test

- lib/OpenQA/Worker/WebUIConnection.pm
Unreliable coverage observed in tests for
https://github.com/os-autoinst/openQA/pull/3713
> Mark uncoverage statements in OpenQA::Worker::WebUIConnection

- assets/images/logo.svg
The svg of the logo still contained a bunch of WIP logos that were left in there
but were invisible because they were outside of the shown image. This commit
removes them, because they just bloat the file, albeit they are quite
interesting to look at ;-)
> Remove invisible WIP logos from logo.svg

- Makefile
- codecov.yml
- t/ui/27-plugin_obs_rsync_status_details.t
Related progress issue: https://progress.opensuse.org/issues/88594
> Fix broken lookup of paths in coverage reports

- container/worker/Dockerfile
- container/worker/run_openqa_worker.sh
Problem: Container workers are unable to execute jobs because they
do not have permissions on the kvm device
Solution: Include the _openqa-worker user in the same group than /dev/kvm
Problem: qemu-tools is necessary when running a job. Otherwise it shows
the error: no kvm-img/qemu-img found
Notes: Using docker the container has to be runned using --device=/dev/kvm
https://progress.opensuse.org/issues/76978
> Fix worker container to allow job executions relying on KVM

- .circleci/ci-packages.txt
- lib/OpenQA/Log.pm
- lib/OpenQA/WebAPI.pm
- lib/OpenQA/WebAPI/Controller/API/V1/Mm.pm
- t/26-controllerrunning.t
- t/ui/27-plugin_obs_rsync_status_details.t
1. Reserved stash values.
```
Route pattern "/children/:status" contains a reserved stash value at lib/OpenQA/WebAPI.pm line 361.
```
It is forbidden to use reserved stash values as placeholders in routes.
2. New log formatting
Individual log messages are now joined with a whitespace character instead of a newline. Additionally `Mojo::Log::Colored` is incompatible with Mojolicious 9.0 (reported upstream).
3. Missing controllers are now an exception
```
[error] [1Whlu6Jt] Controller "OpenQA::WebAPI::Search" does not exist at extlib/lib/perl5/Mojolicious.pm line 124.
```
One of the routes used `->to('search#search')` as a hack to render the template `search/search.html.ep`.
4. `Mojo::IOLoop::Delay` no longer exists
```
Can't locate object method "delay" via package "Mojo::IOLoop" at …
```
> Fix Mojolicious 9.0 compatibility

- Makefile
- lib/OpenQA/Scheduler/Client.pm
- lib/OpenQA/UserAgent.pm
- lib/OpenQA/WebSockets/Client.pm
- t/31-client.t
* This allows to run the web UI, websocket server and scheduler on
different hosts (e.g. a load balanced environment) provided the newly
introduced environment variables are set
* See https://progress.opensuse.org/issues/88187
> Make host names used by internal clients configurable

- assets/javascripts/admin_assets.js
Problem: Clicking on "Untracked" on /admin/assets yields "Not Found" page
Solution: Remove the clickable link at all
https://progress.opensuse.org/issues/88745
> Fix remove link configuration for "Untracked" groups in /admin/assets

- .circleci/ci-packages.txt
- .circleci/config.yml
- Makefile
- cpanfile
- dependencies.yaml
- dist/rpm/openQA.spec
As per suggestion in [poo#88915](https://progress.opensuse.org/issues/88915) since it was't much work and I was still investigating the upload errors. And despite this being reproduced in other projects, *codecov-bash* seems to work fine.
- Add JSON::MaybeXS and use JSON for codecov db in CI
- Update and use makefile targets in CI
- Replace codecov (perl) with codecov-bash
**Note**: [Devel::Cover::Report::Codecovbash](https://metacpan.org/pod/Devel::Cover::Report::Codecovbash) is used in CI via CPAN
> Use codecov-bash to upload coverage reports

- etc/openqa/openqa.ini
- lib/OpenQA/Setup.pm
- lib/OpenQA/Task/Asset/Limit.pm
- lib/OpenQA/Task/Job/Limit.pm
- lib/OpenQA/Task/Utils.pm
- t/37-limit_assets.t
- t/42-df-based-cleanup.t
- t/config.t
* Make the minimum used disk space configurable having the new behavior not
enabled by default
* See https://progress.opensuse.org/issues/88121#note-10
> Add "early-abort" in asset/results cleanup jobs based on df-output

- docs/Installing.asciidoc
- lib/OpenQA/Task/Job/FinalizeResults.pm
- t/10-jobs.t
This should prevent blocking Minion workers for a long time and other Minion jobs piling up for too long.
See https://progress.opensuse.org/issues/89224
> Limit execution time of hook scripts run within Minion

- t/ui/27-plugin_obs_rsync_status_details.t
Sometimes gru is very slow in CI, so the test reports a failure.
This change aims to wait longer for gru to catch up.
> t: Increase timeout in 27-plugin_obs_rsync_status_details.t

- t/api/03-auth.t
Followup to #3774 with a few extra tests.
> Test personal access tokens with an OpenID user

- .circleci/config.yml
- Makefile
- CI can use the new -report variants of the targets
- Cover format and options are enabled via COVERAGE=1
```
COVERAGE=1 make test-with-database
make coverage-report-html
```
and
make coverage-html
are analoguous, the former way is used in CI.
See [poo#88915](https://progress.opensuse.org/issues/88915)
> Restore cover and run makefile targets

- lib/OpenQA/Utils.pm
- lib/OpenQA/Worker/Engines/isotovideo.pm
- t/24-worker-engine.t
- t/43-scheduling-and-worker-scalability.t
The third commit is used to fix the issues mentioned in:
https://progress.opensuse.org/issues/67723#note-44
Here is also another about needles_dir. If users use `openqa-clone-custom-git-refspec` to trigger a new job whose CASEDIR is a basename, the needles_dir will be set as a relative path, the job will incomplete because fail to do NEEDLES_DIR symlink.
Verify run:
For PRODUCTDIR: http://10.67.19.103/tests/448#settings
For NEEDLES_DIR: http://10.67.19.103/tests/449#settings
> Rework symlink CASEDIR and set values to relative path

- Makefile
COVERDB_SUFFIX should be '' which means the assignment trails off in
makefile syntax. This is only visible locally with something like this
since in CI the suffix is used for different jobs:
make coverage TESTS=t/api/03-auth.t
This fixes a regression introduced in #3753
> Fix default cover db suffix/filename i.e. cover_db

- docs/Contributing.asciidoc
These `+` signs must have been wrongly added when changing the quotation style.
> Remove surplus `+` signs in documentation for importing production data

- dbicdh/PostgreSQL/deploy/92/001-auto-__VERSION.sql
- dbicdh/PostgreSQL/deploy/92/001-auto.sql
- dbicdh/PostgreSQL/upgrade/91-92/001-auto.sql
- dbicdh/_source/deploy/92/001-auto-__VERSION.yml
- dbicdh/_source/deploy/92/001-auto.yml
- lib/OpenQA/Schema.pm
- lib/OpenQA/Schema/Result/Jobs.pm
* I was made aware of this limitation by the following error showing up in
a cleanup task on OSD:
```
DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::Pg::st execute failed: ERROR:  integer out of range [for Statement "UPDATE jobs SET logs_present = ?, result_size = result_size - 9511751560, t_updated = ? WHERE id = ?" with ParamValues: 1=\'0\', 2=\'2021-03-12 23:23:27\', 3=\'5572530\'] at /usr/share/openqa/script/../lib/OpenQA/Schema/Result/Jobs.pm line 1185
```
* Requires 4 more byte per job
* Migration might take a while to execute
---
The change itself is pretty simple. I still make it a draft because I'd like to test how long the migration would take with a production database.
> Use bigint to store job's result size to increase the limit ~2 GiB to ~8 EiB

- lib/OpenQA/Schema/Result/Jobs.pm
- t/10-jobs.t
The accounting is not 100 % accurate so we might otherwise end up with jobs
having a negative result size.
I was made aware of this limitation by the following error showing up in a
cleanup task on OSD:
```
DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::Pg::st execute failed: ERROR:  integer out of range [for Statement "UPDATE jobs SET logs_present = ?, result_size = result_size - 9511751560, t_updated = ? WHERE id = ?" with ParamValues: 1=\'0\', 2=\'2021-03-12 23:23:27\', 3=\'5572530\'] at /usr/share/openqa/script/../lib/OpenQA/Schema/Result/Jobs.pm line 1185
```
> Avoid assigning a negative result_size to a job when cleaning up results

- lib/OpenQA/WebAPI/Plugin/ObsRsync/Controller/Gru.pm
- t/ui/27-plugin_obs_rsync_status_details.t
It seems #3784 already made Codecov results quite a bit more stable (looking at recent PRs). This PR should raise coverage percentage of the flaky files to 100% consistently. Making Codecov hiccups less likely.
Progress: https://progress.opensuse.org/issues/89899
> Make codecov results more stable

- lib/OpenQA/Worker.pm
- lib/OpenQA/Worker/Job.pm
- t/24-worker-jobs.t
- t/24-worker-overall.t
* Add test so `_upload_results` has full test coverage
* Move common code for concluding the upload to its own function
* Improve logging of concluded upload further (see extra commit for details)
---
This fixes a problem I've found when investigating https://progress.opensuse.org/issues/90152 but does *not* fix the issue mentioned in that ticket.
> Prevent worker from getting stuck in final upload when no tests are scheduled

- .github/workflows/compose.yml
- Makefile
- container/webui/docker-compose.yaml
- dist/rpm/openQA.spec
- tools/test_containers_compose
Now docker-compose is able to build the images before try to start
the containers
https://progress.opensuse.org/issues/89719
> docker: Allow docker-compose build images

- lib/OpenQA/Script/CloneJob.pm
* Pass settings in body (application/x-www-form-urlencoded)
* See https://progress.opensuse.org/issues/90299
> Fix 414 failures when cloning jobs with too long settings

- .circleci/unstable_tests.txt
- lib/OpenQA/Worker/Engines/isotovideo.pm
os-autoinst includes multiple backends which can require changes to 
support different technologies or specific testing needs. Also, the
worker environment needs to provide requirements to run tests which
include more package than originally required for os-autoinst or newer
versions.
This commit introduces the possibility to customize the actual worker
engine that is started with keeping the default of starting "perl
$isotovideo -d". For example a different location for isotovideo can be 
specified or a container providing different versions of packages or 
even a completely different worker engine that is interface-compatible.
Working on https://github.com/os-autoinst/os-autoinst/pull/1558 this
idea came back to mind. I had already thought about doing something
similar couple of times, …
> Allow to override isotovideo executable with command line

- Makefile
Devel::Cover uses Cpanel::JSON::XS which has a bug (defining JSON::PP::Boolean
namespace which the actual module will try to overwrite later).
perl -wE 'use Cpanel::JSON::XS (); use JSON::PP ()'
Subroutine JSON::PP::Boolean::(++ redefined at /usr/lib/perl5/5.26.1/overload.pm line 48.
...
Issue: https://progress.opensuse.org/issues/90371
See also https://github.com/rurban/Cpanel-JSON-XS/issues/65
> t: use JSON::PP when using Devel::Cover

- container/webui/docker-compose.yaml
- Check and complete with the missing directories
The directories 'tmp' and 'others' were missing.
Added all the required directories as volumes.
- Check and fix the permissions over these directories for the gekotest user
Because this directories are shared between all the containers and also
with the host. This PR assign the write permissions for the directories that
the containers write.
https://progress.opensuse.org/issues/89755
> container: Fix missing shared directories and its permissions

- lib/OpenQA/CLI/api.pm
- lib/OpenQA/Command.pm
- t/43-cli-api.t
Currently, openQA client's help recommends the following to configure a job group from a YAML template:
```
openqa-cli api -X POST job_templates_scheduling/1 \
schema=JobTemplates-01.yaml preview=0 template="$(cat foo.yaml)"
```
A potential issue with this, is that when the YAML file reaches a certain size, such a command can hit the `Argument list too long` error on a shell, for example:
```
openqa-cli api --host http://mango.qa.suse.de --apikey **** --apisecret **** -X POST \
job_templates_scheduling/2 schema=JobTemplates-01.yaml preview=1 \
template="$(cat sle15_sp3_ha.yml)"
-bash: /usr/bin/openqa-cli: Argument list too long
```
Or:
```
cat sle15_sp3_ha.yml | openqa-cli api --host http://mango.qa.suse.de --apikey **** --apisecret **** \
-X POST job_templates_scheduling/2 …
```
> Allow client to get YAML job templates from a file

- lib/OpenQA/Schema/Result/Jobs.pm
- t/api/04-jobs.t
The worker reads the test order and updates it before each upload attempt
so the web UI should be aware of all test modules even if the test schedule
changes in the middle. So it should be safe to treat this situation as an
error.
This should improve the error feedback in cases like
https://progress.opensuse.org/issues/90152 where the logs tell us currently
that the result upload worked but in the end nothing is there. Of course
this just improves the symptom. The cause is likely that the test order
could not be uploaded in the first place.
> Treat result uploads for non-existant modules as error

- dist/rpm/openQA.spec
- script/openqa-rollback
We used the same approach within automatic deployment of the SUSE
internal instance openqa.suse.de within a gitlab CI YAML document
already. As debugging and improvement can become tricky in shell code
maintained in a YAML document calling a remote shell with eval code,
multiple levels of quoting, etc., I moved the functionality into a
dedicated shell script.
Tested manually with
```
cat script/openqa-rollback | ssh osd "cat - > /tmp/openqa-rollback && env webui_before=/tmp/before worker_before=/tmp/osd-deployment_rpm_q bash -ex /tmp/openqa-rollback --dry-run"
```
Related progress issue: https://progress.opensuse.org/issues/89993
```
diff --git a/script/openqa-rollback b/script/openqa-rollback
new file mode 100755
index 000000000..b39d30a60
--- /dev/null
+++ b/script/openqa-rollback
@@ …
```
> Add script for package installation rollback on demand

- lib/OpenQA/WebAPI.pm
- t/43-cli-api.t
- t/lib/OpenQA/Test/Utils.pm
- t/ui/18-tests-details.t
Alternative to #3816. This should be the minimal fix to make openQA work with Mojolicious 9.01 and 9.11. [Here's](https://github.com/os-autoinst/openQA/compare/k/mojo_911) the same patch in a different branch running CI tests against 9.14.
```
sudo perl - -M https://cpan.metacpan.org -n Mojolicious@9.14
curl -L https://cpanmin.us
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  295k  100  295k    0     0  5097k      0 --:--:-- --:--:-- --:--:-- 5097k
--> Working on Mojolicious
Fetching https://cpan.metacpan.org/authors/id/S/SR/SRI/Mojolicious-9.14.tar.gz ... OK
Configuring Mojolicious-9.14 ... OK
Building Mojolicious-9.14 ... OK
Successfully installed Mojolicious-9.14 (upgraded from 9.01)
1 distribution …
```
> Fix Mojolicious 9.11 compatibility

- .circleci/unstable_tests.txt
This reverts commit 424154d7b829dd95e91f183ff9bd985529b6e244 due to more
recent failures.
Related progress issue: https://progress.opensuse.org/issues/89935
> Mark t/ui/27-plugin_obs_rsync_status_details.t as unstable again

- lib/OpenQA/Worker/Engines/isotovideo.pm
- t/24-worker-engine.t
Users can disable this feature by setting `ABSOLUTE_TEST_CONFIG_PATHS=1`.
See: https://progress.opensuse.org/issues/90293#note-11
> Set using relative path as the default operation

- script/openqa-rollback
The additional quotes around the dry-run parameter would add an empty
string argument if dry-run is not set causing invalid syntax calling
zypper.
Tested manually on OSD.
Related progress issue: https://progress.opensuse.org/issues/89993
> Fix openqa-rollback for non-dry-run

- lib/OpenQA/WebAPI.pm
- t/22-dashboard.t
Mojolicious 9.11 disables request "format detection" - where a route declared for `/foo` will be used for `/foo.iso` by default, with the 'format' included in the request stash - to improve security. There are several cases where we relied on this; these commits change those routes to explicitly declare the formats they accept. I hope this covers everything, it at least makes all the tests we run on Fedora package build work with Mojolicious 9.15.
> Fix request routing for Mojolicious 9.11

- container/worker/conf/client.conf
- container/worker/conf/workers.ini
- container/worker/docker-compose.yaml
- container/worker/run_openqa_worker.sh
- tools/test_containers_compose
Problem:
The current entrypoint.sh is generating this error
groupmod GID '0' already exists
Solution: Remove the group number in groupmod
Additionally
- Add qemu_no_kvm flag
- Provided a test for qemu
https://progress.opensuse.org/issues/88754
> containers: Fix worker container entrypoint script

- .github/workflows/compose.yml
The test webui-docker-compose exceeds 30 minutes and is cancelled with the message
"The job running on runner Hosted Agent has exceeded the maximum execution time of 30 minutes."
Increased to 60 minutes
https://progress.opensuse.org/issues/90767
> containers: fix github test webui-docker-compose timeout

- lib/OpenQA/WebAPI/Controller/Admin/Workers.pm
- t/ui/15-admin-workers.t
The code so far relied on the fact that `t_seen` is unset on a graceful
disconnect. However, in practice that does not always work, likely due to
some race condition. So let's just not rely on that. Considering any worker
offline with the error 'gracefully disconnected at …' is simple and not a
problem because that error is unset when the worker connects again.
> Ensure workers are shown as offline after disconnecting gracefully immediately

- container/webui/docker-compose.yaml
Eventually the startup using docker-compose fails several seconds after all is up. The reason is because the webui do operations over the DB and because we have concurrent webui containers can cause race conditions
For instance:
```
Webui_1 failed to run SQL in
/usr/share/openqa/script/../dbicdh/PostgreSQL/deploy/92/001-auto-__VERSION.sql:
DBIx::Class::DeploymentHandler::DeployMethod::SQL::Translator::try {...} ():
DBI Exception: DBD::Pg::db do failed:
ERROR:  duplicate key value violates unique constraint "pg_type_typname_nsp_index"
```
An example of this failure could be found at: #3818
The reason for the problem is that all webui containers try to create and initialize the database at the same time, and since all webui replicas are launched at the same time by the docker-compose and we …
> containers: Add healthchecks to organize the docker-compose startup

- docs/ContainerizedSetup.asciidoc
* Separate instructions for "Fedora" and "docker-compose" setups more from
each other because the interleaving made it quite hard to follow
* Improve wording
* Fix references to "Keeping all data …" sections
* Merge section explaining the data storage with the directory structure
setup because these seem to be very related
* See https://progress.opensuse.org/issues/76990
> Improve container documentation

- .mergify.yml
mergify only merges if also webui-docker-compose and likely others are passed
https://progress.opensuse.org/issues/90614
> CI: Add checks over static-check-containers and webui-docker-compose in mergify

- docs/Installing.asciidoc
- etc/openqa/openqa.ini
- lib/OpenQA/Setup.pm
- lib/OpenQA/WebAPI/Auth/OAuth2.pm
- t/03-auth.t
- t/config.t
In the diff you'll see a load of config hash keys of the form FIXME_oauth2_*
I had rather hoped that I'd be able to put the data contained in them into the $prov_args hash, and thus attach them as extra fields to the provider's defaults, but I'm obviously not quite understanding all the perl5-isms (my perl is quite rusty ;-) )
If someone can have a look at this, and point out how to do this properly, that would be great.
BTW this is a patch arising from my current quest to a) get openqa.debian.net to be more useful, and more widely used, and b) to get an OpenQA package into the Debian package archive at some point soon.
Cheers, Phil.
> Make OAuth2 parameters customizable, get OAuth2 to work with salsa.debian.org (gitlab)

- container/webui/docker-compose.yaml
In #89731 we introduced a initial webui container in charge of initializing
the database. We have a test where the health check failed
https://github.com/os-autoinst/openQA/pull/3838/checks?check_run_id=2329551052
There are several detected problems:
- The db healthcheck command doesn't generate an errorcode when fails
echo 'select * from api_keys;' | psql -U openqa openqa
- There is a deathlock between db and webui: db healthcheck checks that
the table api_keys exists, but this table is created by webui_init, and
webui_init depends on the healthy start of the db to start
Solutions:
- Fix the DB healthcheck
- DB and webui_init are started at the same time
- webui pool starts when DB is healthy
https://progress.opensuse.org/issues/91046
> CI: Fix db & webui_init startup

- tools/test_containers_compose
The flag -q is silencing all the logs when the container images
are building. So when it fails we don't have enough information about
the failure.
This commit removes this flag.
https://progress.opensuse.org/issues/91097
> CI: Remove -q flag in docker-compose build in test_containers_compose 

- lib/OpenQA/Schema/Result/JobGroups.pm
- t/36-job_group_settings.t
- t/37-limit_assets.t
See https://progress.opensuse.org/issues/91157
> Fix result cleanup when retention period configured on job group level is zero

- tools/test_containers_compose
Eventually docker-compose build fails because of the zypper
respositories. This commit sets 3 retries before consider the test
failed
https://progress.opensuse.org/issues/90614
> CI: Retry if docker-compose build fails in webui-docker-compose test

- container/travis_test/Dockerfile
- container/webui/Dockerfile
- container/webui/docker-compose.yaml
- container/worker/Dockerfile
This check has recently been added to the linter, see
https://github.com/hadolint/hadolint/commit/4cb8f28ebecfd0343241369952fc9b3e7e4ea866 and https://progress.opensuse.org/issues/91377
> Fix failing CI check for container file (static check DL3059)

- lib/OpenQA/Worker/Job.pm
Uploading the test order on the final upload (when stopping the job) was
broken because the function for loading the test module results cleared the
array holding the test order when the test has already been finished. So if
the test order hasn't been uploaded before because the test execution was
very short the test order couldn't be uploaded at all.
This change basically restores the array holding the test order before the
final upload. The worker will now post the entire test order and the all
information from result files again in the end to ensure everything is in
place. Images/files will known by the web UI will still be skipped and the
uploads during the test execution will still avoid uploading everything.
So I suppose this change will fix …
> worker: Make uploading test order on final upload (when stopping job) work

- lib/OpenQA/Worker/Job.pm
- t/24-worker-jobs.t
Making the worker go though every test module again during the final
upload (https://github.com/os-autoinst/openQA/pull/3849) introduced the
problem of uploading images again during the final upload. This should have
been prevented by the usual skipping of known images. However, since we now
re-read the test module results the checksums were re-computed during the
final upload which breaks the matching. That's because the checksums
actually differ due to running optipng before the image upload. This change
restores the matching by simply caching and reusing the md5sum from before
the optimization.
Related issue: https://progress.opensuse.org/issues/90152
> worker: Avoid running optipng/upload twice

- lib/OpenQA/Schema/Result/Jobs.pm
* Fix declaration of needle_dir
* Fix string literal '…' as this apparently also pulls in changed UTF-8 handling
---
When enabling signatures in `…::Result::Jobs` in https://github.com/os-autoinst/openQA/pull/3858 I've noticed that this is not completely straight forward as these two issues need to be fixed. So I've created a separate PR to have these fixes independently of https://github.com/os-autoinst/openQA/pull/3858.
> Enable signatures in …::Result::Jobs and fix issues

- assets/assetpack.def
- assets/javascripts/back_to_top.js
- assets/stylesheets/back_to_top.css
- t/ui/14-dashboard.t
- templates/webapi/layouts/bootstrap.html.ep
The button looks a little different than on the QAM Dashboard because openQA doesn't use Bootstrap defaults. But it's consistent with the look of other buttons.
Progress: https://progress.opensuse.org/issues/91601
> Add back to top button to layout

- lib/OpenQA/CLI/api.pm
Our documentation for spawning a single job mentions this so it makes sense to actually add such an example.
> Add example for triggering single job to `openqa-cli api --help`

- docs/Installing.asciidoc
The missing `a` is pointed out in the issue. I'm also changing *dare* to *need* because there's no reason to be cheeky here.
Fixes: #3691
> doc: Improve phrasing regarding worker instance number

- lib/OpenQA/BuildResults.pm
- lib/OpenQA/Schema/Result/Jobs.pm
- lib/OpenQA/Schema/ResultSet/Comments.pm
- lib/OpenQA/WebAPI/Controller/Test.pm
- t/22-dashboard.t
* Do *not* count any kind of comment anymore when computing black
certificate icon; only count bugrefs/labels in consistency with TODO
parameter of test results overview page
* Use the same code for checking bugrefs/labels for certificate, test
results overview page and 'Next & previous results' tab
* See https://progress.opensuse.org/issues/91658
> Only consider bugrefs/labels for black certificate icon

- lib/OpenQA/Schema/Result/Jobs.pm
- lib/OpenQA/Worker/WebUIConnection.pm
- t/api/04-jobs.t
* Avoid incompletes with the reason "Failed modules: …"
* Weaken error handling introduced in
a34d89c4a2a78d874c84596257ac28f27f20d892 so the worker would try the
upload again
* Affected tests actually have the failing test modules so it is likely
that a retry would help
* See https://progress.opensuse.org/issues/91902
> Let the worker retry uploading when updating module results failed

- lib/OpenQA/Schema/Result/Jobs.pm
- t/10-jobs.t
- t/23-amqp.t
- t/api/04-jobs.t
* Consider jobs with no modules incomplete when the worker does not
explicitly pass a result
* Use `no test modules scheduled/uploaded` as reason if there's no other
reason
* Compilation errors, needle initialization errors and other early
errors (before the test module creation) still have a specific reason
* Tested manually by breaking controller code to simulate
https://progress.opensuse.org/issues/90152
> Consider jobs with no modules incomplete

- Makefile
The documentation states that the coverage of individual test files can be
checked via e.g. `make coverage TESTS=t/24-worker-engine.t`. This change
restores this possibility by avoiding the execution of the container test
when `TESTS` has been specified.
> Prevent execution of container test when `TESTS` has been specified

- profiles/apparmor.d/usr.share.openqa.script.worker
This is used by WSL tests which otherwise fail with log messages like
```
QEMU: qemu-system-x86_64: Slirp: fork_exec: Failed to execute child process /usr/sbin/smbd (Permission denied)
```
(example failure: https://openqa.opensuse.org/tests/1727032#step/prepare_wsl_feature/14)
> apparmor: Allow execution of smbd which is required for QEMU_ENABLE_SMBD

- Makefile
To reproduce:
make coverage  TESTS=t/01-test-utilities.t
This didn't work for Oli and me on Leap 15.2
cover was failing with:
Can't read /home/okurz/local/os-autoinst/openQA/cover_db/runs/1620219503.14849.03766/cover.14 with Sereal: Sereal: Error: Bad Sereal header: Not a valid Sereal document. at offset 1 of input at srl_decoder.c line 600 at /usr/lib/perl5/vendor_perl/5.26.1/x86_64-linux-thread-multi/Devel/Cover/DB/IO/Sereal.pm line 34, <$fh> chunk 1.
So apparently DEVEL_COVER_DB_FORMAT got lost somewhere.
Issue: https://progress.opensuse.org/issues/92179
> Makefile: set DEVEL_COVER_DB_FORMAT

- .circleci/unstable_tests.txt
See https://circleci.com/gh/os-autoinst/openQA/60185
Related progress issue: https://progress.opensuse.org/issues/80374
> Mark t/ui/25-developer_mode.t as unstable due to recent failures

- lib/OpenQA/Worker/WebUIConnection.pm
Default values of parameters are only used if the parameter has not been
specified but can not be used to ensure a parameter's value is not
undefined (as `undef` might be passed as parameter value explicitly).
> Prevent Perl warning in worker code introduced by 4c2e8c8a63

- lib/OpenQA/BuildResults.pm
Helps with statement coverage in tests as well :) 
Encountered while looking at code statement coverage reports on codecov,
in particular
https://codecov.io/gh/os-autoinst/openQA/src/master/lib/OpenQA/BuildResults.pm
> Simplify handling of potential not-implemented states of jobs

- docs/UsersGuide.asciidoc
- lib/OpenQA/Schema/Result/ScheduledProducts.pm
- t/39-scheduled_products-table.t
- t/api/02-iso.t
When only scheduling a single scenario it is likely not intended to
deprioritize/obsolete which can be rather confusing. We've seen this
problem in production where a product has been scheduled with
`TEST=containers_sle_image_on_sle_host` and `_DEPRIORITIZEBUILD=1` which
deprioritized all previous jobs with the same DISTRI/VERSION/FLAVOR/ARCH.
> Do not allow to deprioritize/obsolete build when specifying TEST

- t/ui/27-plugin_obs_rsync_status_details.t
* Enqueuing even more `obs_rsync_update_builds_text` jobs only decreases
the likeliness of processing all Minion jobs which need to run within the
test in time
* See https://progress.opensuse.org/issues/89935
>  Do not enqueue more Minion jobs while waiting in 27-plugin_obs_rsync_status_details.t

- Makefile
- dist/rpm/openQA.spec
This will reduce the gap between Leap and SLE and it will also fix the build when targeting Backports repos in OBS.
> Install auto-update systemd files for SUSE as well and not only openSUSE

- assets/javascripts/test_result.js
- t/ui/18-tests-details.t
Issue: https://progress.opensuse.org/issues/92188
In the investigation tab, if this is not the first bad test, an alert box
will be shown linking to the first bad test's investigation tab directly.
> Show alert box linking to first bad test

- dist/rpm/openQA-devel-test.spec
- dist/rpm/openQA.spec
chromedriver does not exist under ppc ppc64 ppc64le s390x so only the
package opennQA-no-selenium-devel can be used there.
> Do not build openQA-devel for archs where it would be unresolvable

- lib/OpenQA/Task/Job/FinalizeResults.pm
This fixes
```
Can't locate object method "delay" via package "OpenQA::Shared::GruJob" at /usr/share/openqa/script/../lib/OpenQA/Task/Job/FinalizeResults.pm line 31.
```
introduced by b9ff4a43c5240e4c4207c8059ba7dd7e3852318e
> Fix retry/delay in FinalizeResults.pm leading to failing Minion jobs

- Makefile
- tools/tidy
As observed in https://github.com/os-autoinst/openQA/pull/3915 we did
not cover some shell scripts as part of our shellcheck calls. This
commit extends the shellcheck call to also look for shell scripts in
tools. I considered the alternative to use 'git ls-files' to list all
files and find shell scripts. However this takes significantly longer,
6s on my machine so this is not done right now.
> Also cover shell scripts in tools/ by shellcheck

- profiles/apparmor.d/usr.share.openqa.script.worker
We would like to read the dmesg and find out if the qemu is killed
because of out of memory. So we give the permisson to worker.
Relate: https://progress.opensuse.org/issues/90974
> Give permission of dmesg to worker

- docs/UsersGuide.asciidoc
The docs state that variable values set as part of the API request that triggers the jobs will
'win' over values set at any of the other locations, but this is not true for the special case of BACKEND variable.
> Update docs about the special case of  BACKEND variable precedence.

- tools/test_containers_compose
Prevents
```
In tools/test_containers_compose line 23:
sudo MOJO_CLIENT_DEBUG=1 docker-compose up -d &&
^-- SC2015: Note that A && B || C is not if-then-else. C may run when A is true.
```
It doesn't make much sense to use `&&` here anyways because the script uses
`-e`.
> Fix failing stylecheck for tools/test_containers_compose

- .circleci/config.yml
Looks like we have a chromedriver regression again.
Progress: https://progress.opensuse.org/issues/93453
> Downgrade chromedriver from problematic version

- t/10-jobs.t
- t/lib/OpenQA/Test/Utils.pm
I've added a `OpenQA::Test::Utils::perform_minion_jobs_in_foreground` function for now, but might also add this as an upstream feature to Minion, since there's enough reasonable use cases for it now.
Before:
```
[15:07:34] t/10-jobs.t ........... ok   160051 ms ( 0.06 usr  0.01 sys + 154.81 cusr  4.02 csys = 158.90 CPU)
```
After:
```
[15:39:48] t/10-jobs.t ........... ok    19263 ms ( 0.07 usr  0.01 sys + 18.16 cusr  0.66 csys = 18.90 CPU)
```
Progress: https://progress.opensuse.org/issues/93086
> Run 10-jobs.t really fast

- lib/OpenQA/Worker/Engines/isotovideo.pm
- t/24-worker-engine.t
worker: Fix handling CASEDIR/PRODUCTDIR/NEEDLES_DIR in certain cases
This change ensures that the default-assignment for PRODUCTDIR is a
relative directory (unless the feature switch to use absolute paths is
turned on). That is required when a custom CASEDIR has been specified
because in this case it is expected that not only Perl modules but also
`main.pm` itself is loaded from that custom CASEDIR (unless PRODUCTDIR is
set explicitly to some other location). So this should fix
https://progress.opensuse.org/issues/93101.
When only changing the behavior for PRODUCTDIR the needles could not be
loaded anymore (unless NEEDLES_DIR is specified explicitly) because the
checkout of CASEDIR does not necessarily contain needles. To fix this, the
symlinking of the needles directory is done in that …
> worker: Fix handling CASEDIR/PRODUCTDIR/NEEDLES_DIR in certain cases

- profiles/apparmor.d/usr.share.openqa.script.worker
After https://github.com/os-autoinst/os-autoinst/pull/1672 was merged,
there was a `Permission denied` when doing `check_qemu_oom`. So give
the permission of `check_qemu_oom` to worker.
Adding `/dev/kmsg r` is used to avoid the message in audit.log
```
apparmor="DENIED" operation="open" profile="/usr/share/openqa/script/
worker///usr/lib/os-autoinst/check_qemu_oom" name="/dev/kmsg" pid=8915
comm="dmesg" requested_mask="r" denied_mask="r" fsuid=457 ouid=0
```
> Give permission of check_qemu_oom

- lib/OpenQA/WebAPI.pm
- t/27-errorpages.t
A small regression caused by the same breaking change in Mojolicious that broke all the other routes before.
Progress: https://progress.opensuse.org/issues/93345
> Fix content negotiation with .txt file extension for module source

- t/14-grutasks.t
- t/lib/OpenQA/Test/Utils.pm
Small followup to #3934. Not as much of a win as the other change, but at least some improvement.
Before:
```
[15:10:15] t/14-grutasks.t ....... ok   261493 ms ( 0.21 usr  0.01 sys + 252.87 cusr  7.09 csys = 260.18 CPU)
```
After:
```
[13:00:57] t/14-grutasks.t ....... ok   128464 ms ( 0.21 usr  0.00 sys + 123.11 cusr  3.72 csys = 127.04 CPU)
```
> Make run_gru_job perform jobs without forking

- lib/OpenQA/WebAPI/Controller/Test.pm
for loading job settings in /tests/overview
Sometimes we are loading job settings for hundreds of job ids, and
then an `IN` can be significantly faster than an `OR`.
It turns out that I accidentally dropped the `-in` in this
commit: 819374a556d5bd122856bb0e3f1173416e093a0e
assuming that DBIx::Class would automatically turn it into an `IN` clause.
Test runs for an example Build with 273 jobs showed 55-61ms for `OR`,
and 16-21ms for `IN`.
> Minor optimization: Turn SQL 'OR' into 'IN'

- t/ui/13-admin.t
As seen in
https://codecov.io/gh/os-autoinst/openQA/src/master/t/ui/13-admin.t the
function `is_element_text` was never called so we can delete it to reach
100% statement coverage.
> t: Delete unused function in t/ui/13-admin.t

- .circleci/config.yml
- .circleci/unstable_tests.txt
- assets/assetpack.def
- assets/javascripts/disable_status_updates.js
- assets/javascripts/running.js
- t/lib/OpenQA/SeleniumTest.pm
- t/ui/01-list.t
- t/ui/10-tests_overview.t
- t/ui/12-needle-edit.t
- t/ui/13-admin.t
- t/ui/15-comments.t
- t/ui/25-developer_mode.t
Version 91.0.4472.77 of `chromedriver` changed its behavior so
`Selenium::Remote::WebElement` behaves different as well. This change
adapts our tests to the following changes (in a backwards compatible way):
* `Selenium::Remote::WebElement::get_attribute()` now returns `undef`
instead of an empty string if the attribute is not present at all.
* `Selenium::Remote::WebElement::get_value()` and `is_selected()` sometimes
no longer return a value. Likely it depends on how these form properties
are populated. Possible an unwanted side-effect of the `get_attribute()`
change.
See https://progress.opensuse.org/issues/93453#note-11 and particular commit messages
> Adapt UI tests to chromedriver changes, make devel mode test stable

- container/webui/docker-compose.yaml
The containers will fail to launch on systems where SELinux is in enforcing mode
as the shared volumes have the wrong labels. Thus we must label all shared
volumens with :z (even /conf as that one is shared by webui replicas and
:Z *will* cause this to fail!).
> Correct volume labels to allow running on SELinux enabled systems

- script/client
openqa-client is replaced by openqa-cli within the openQA repo and
should be removed eventually.
> Mark openqa-client as deprecated

- lib/OpenQA/Schema/Result/Jobs.pm
- lib/OpenQA/WebAPI/Controller/Test.pm
When a build has hundreds of jobs, for example
`/tests/overview?distri=microos&distri=opensuse&version=Tumbleweed&build=20210607&groupid=1`, then for each job several SQL queries are executed:
```
SELECT me.child_job_id, me.parent_job_id, me.dependency FROM job_dependencies me WHERE ( me.child_job_id = ? ): '1773830'
SELECT me.child_job_id, me.parent_job_id, me.dependency FROM job_dependencies me WHERE ( me.parent_job_id = ? ): '1773830'
SELECT me.id, me.job_id, me.name, me.script, me.category, me.milestone, me.important, me.fatal, me.always_rollback, me.result, me.t_created, me.t_updated FROM job_modules me WHERE ( ( me.job_id = ? AND result = ? ) )  ORDER BY t_updated: '1
773829', 'failed' …
```
> Optimize /tests/overview by combining SQL

- script/openqa-bootstrap
* Use "https:" URL because the "obs:" one is not resolved correctly
* Tested using
```
docker run -v "$PWD:/tmp/checkout" --rm -it registry.opensuse.org/opensuse/leap:15.3 sh -c 'bash /tmp/checkout/script/openqa-bootstrap'
```
* See https://progress.opensuse.org/issues/93609
> Fix repository used by openqa-bootstrap under Leap 15.3

- script/openqa-bootstrap
Same as e4053f76ab364c738d2497c642e7880588ad22c4 but for the repository for
the internal CA. I haven't noticed it in the first place because the ping
dependency was missing which was only fixed by
254d23d0ec92545c28979a50bb6c92a7e7da5031.
See https://progress.opensuse.org/issues/93609
> Fix repository used by openqa-bootstrap under Leap 15.3 for internal CA

- lib/OpenQA/WebAPI/Controller/API/V1/Search.pm
Currently for every job-module result a `SELECT FROM job` is executed,
when calling `$job_module->job->name`.
The prefetch will save the job data in the object and so the extra
SELECT is avoided.
Additionally this commit reduces the selected columns to what is actually
needed.
A search for 'vlc' `/api/v1/experimental/search?q=vlc` was reduced from 39s to 7s locally.
> Optimize search: prefetch job columns

- lib/OpenQA/Schema/ResultSet/Comments.pm
- lib/OpenQA/WebAPI/Controller/Test.pm
This will affect /group_overview/ pages and the homepage.
Also select only relevant columns from Comments.
Issue: https://progress.opensuse.org/issues/94354
> Optimize group_overview: don't fetch bugdetails where not needed

- lib/OpenQA/WebAPI/Controller/Test.pm
- lib/OpenQA/WebAPI/Plugin/Helpers.pm
- t/10-tests_overview.t
When the query has different groupid and every group
different builds the current operation only returns the jobs
for the last build of the first group.
This PR ensures to return all the jobs for all the last builds for
all the selected groups
https://progress.opensuse.org/issues/91650
Supersedes #3971
> Fix show results for multiple groups in /test/overview

- Makefile
- dist/rpm/openQA.spec
- usr/lib/sysusers.d/geekotest.conf
- usr/lib/sysusers.d/openQA-worker.conf
This will allows openqa to be installed on systems with / mounted read-only
> Switch to sysusers

- Makefile
- dist/rpm/openQA.spec
- usr/lib/sysusers.d/geekotest.conf
- usr/lib/sysusers.d/openQA-worker.conf
This reverts commit 72a6d7f87b8773d3ffa8116e02f100966c0064eb.
The sysusers switch will not work until https://build.opensuse.org/request/show/901701 is in Factory.
> Revert "Switch to systemd-sysusers instead of getent + useradd"

- t/22-dashboard.t
- templates/webapi/main/parent_group_overview.html.ep
Provides link to /tests/overview of latest builds of all job groups
within a parent job group
https://progress.opensuse.org/issues/94732
> Add link to /test/overview from a parent job group

- lib/OpenQA/Schema/ResultSet/Jobs.pm
- t/10-jobs.t
Ticket: https://progress.opensuse.org/issues/94774
All common bugtrackers use decimal bugids so check if
the referer URL is complete by making sure that it contains
a digit.
> BugLinks: Do not attempt label with incomplete referer URLs

- lib/OpenQA/Schema/Result/Jobs.pm
- t/17-labels_carry_over.t
* Fix carry-over only due to one matching bugref in step title
* Prevent carry-over despite a mismatch of failing test modules like in
https://progress.opensuse.org/issues/94880
* Still allow carry-over when the same bug is found via different modules
(ef5f07c561cb4bb6139d17b98b616af6b81a8fff) but only if the other failing
test modules match as well
* Consider all modules on carry over, despite missing/broken results
* If it isn't possible to read the results/details of some (soft)failed
modules that doesn't mean we should ignore them completely. In addition,
further (soft)failed modules should not be ignored as well.
---
I've been adding tests now. I've also been testing that tests fail without the change (as there was already a similar test in place which wasn't good enough).
> Fix carry-over only due to one matching bugref in step title

- lib/OpenQA/Schema/Result/Jobs.pm
- t/17-labels_carry_over.t
This should be a small fix for https://progress.opensuse.org/issues/70915 (based on #3988).
> Take test modules without result into account for carry-over

- lib/OpenQA/WebAPI/Controller/API/V1/Search.pm
$current_user is an object, $username is the user's name
> search: Correctly use username for gru lock if logged in

- t/full-stack.t
* Also show the `autoinst-log.txt` of the test run.
* Previously it waited until the timeout was exceeded for the test to be
running although it has already been incompleted anyways.
> fullstack test: Stop when first test incompletes

- lib/OpenQA/WebAPI/Plugin/Helpers.pm
- t/ui/10-tests_overview.t
As discussed earlier in the weekly meeting, just the most minimal validation (not even actual validation, just filtering of parameters). It prevents `/tests/overview?...&flavor=` from affecting the database query and loading 70k+ jobs on O3, instead of just jobs from the latest build. Right now this is unlikely to happen, but we want to extend the filter form with new options, including `flavor`.
Progress: https://progress.opensuse.org/issues/94901
> Fix performance issue with `/tests/overview?...&flavor=`

- assets/javascripts/overview.js
- lib/OpenQA/WebAPI/Controller/Test.pm
- t/ui/10-tests_overview.t
- templates/webapi/test/overview.html.ep
Just flavor and test for now, since i'm not sure how to best fit job groups into the form without making it look like a total mess.
This should also not be merged before #4003, since the form can create empty flavor values.
Progress: https://progress.opensuse.org/issues/91647
> Add filter options for flavor and test

- t/full-stack.t
I measured 2m 40s for this module so the internal timeout
should be at least 200s instead of 90.
When running in CI the default factor is 3 so the make level
timeout should be 12m to provide some selectivity over the
200s*3=10m internal timeout.
Ticket: https://progress.opensuse.org/issues/93677
> Use a more feasible timeout for t/full-stack.t

- t/22-dashboard.t
- templates/webapi/main/parent_group_overview.html.ep
0e0094d72 added a link to a test overview page for multiple job groups
within one parent group. The link by mistake includes the query
parameter "todo=1" which should not be the case to show all test results
as the link description explains.
> Fix the multi-job-group overview link to show all results

- assets/stylesheets/test-details.scss
- t/22-dashboard.t
- templates/webapi/main/dashboard_build_results.html.ep
- templates/webapi/main/parent_group_overview.html.ep
- templates/webapi/main/test_result_overview_link.html.ep
Provides link to /tests/overview of latest builds of all job groups
that are listed in the index page
https://progress.opensuse.org/issues/94732
Example in the index page
Example in the parent group page
> Add link to /test/overview from index page

- t/deploy.t
As observed in
https://app.circleci.com/pipelines/github/os-autoinst/openQA/6946/workflows/e5885c62-0f96-4fa2-bdd3-608f53a0caf0/jobs/65509
Just executing the test once locally already failed it for me.
Increasing the timeout to 20s I could verify stability with
```
make test RETRY=20 STABILITY_TEST=1 KEEP_DB=1 TESTS=t/deploy.t
```
> t: Bump timeout for deploy.t after recent slowdown

- lib/OpenQA/Schema/ResultSet/JobSettings.pm
Maybe we are just missing tests for this, maybe we do not need it at
all.
I have also tried to trigger the additional query condition over
/tests/overview, e.g.
https://openqa.opensuse.org/tests/overview?distri=opensuse&groupid=1&version=Tumbleweed&HDD_1=opensuse-Tumbleweed-x86_64-20210629-textmode@64bit.qcow2
but to no effect. Tests that do not have that HDD_1 setting still show
up so the filter is not effective.
See https://codecov.io/gh/os-autoinst/openQA/src/master/lib/OpenQA/Schema/ResultSet/JobSettings.pm
> Remove uncovered conditions for internal search of job settings

- assets/javascripts/job_next_previous.js
- assets/javascripts/openqa.js
- assets/javascripts/tests.js
- lib/OpenQA/WebAPI/Controller/Test.pm
- t/ui/01-list.t
For finished tests (/tests/list_ajax):
Like in /tests/overview, figure out the type of comment (bug, closed/open,
label) and display them including links.
Issue: https://progress.opensuse.org/issues/94937
Edit: request times are going up from around 570-620ms to 620-720ms
> Distinguish comment types on /tests

- t/api/14-plugin_obs_rsync.t
- t/ui/25-developer_mode.t
- t/ui/26-jobs_restart.t
- t/ui/27-plugin_obs_rsync_obs_status.t
Since recently same like other test files also t/ui/26-jobs_restart.t runs into
timeouts both in CI as well as locally.
Before changes locally `count_fail_ratio prove -l t/ui/26-jobs_restart.t`
using
https://github.com/okurz/scripts/tree/master/count_fail_ratio
```
t/ui/26-jobs_restart.t .. 4/? Bailout called.  Further testing stopped:  findElement: Server returned error message Label not found for "last T2_SUBTEST_WRAPPER" at /usr/lib/perl5/vendor_perl/5.26.1/Test2/Hub/Subtest.pm line 67. at /home/okurz/local/os-autoinst/openQA/t/ui/../lib/OpenQA/SeleniumTest.pm:95
FAILED--Further testing stopped: findElement: Server returned error message Label not found for "last T2_SUBTEST_WRAPPER" at /usr/lib/perl5/vendor_perl/5.26.1/Test2/Hub/Subtest.pm line 67. at …
```
> t: Bump timeout for ui/26-jobs_restart.t

- lib/OpenQA/Downloader.pm
- lib/OpenQA/Task/Asset/Download.pm
- t/14-grutasks.t
Otherwise we'll get lots of failed Minion jobs which usually means
something is broken on our side. However, client errors are most likely
caused by users, e.g. by specifying an invalid asset URL which just
returns a 404 page. This change prevents unnecessary alerts in such cases.
> Do not fail Minion jobs when asset download fails due to a client error

- Makefile
- dist/rpm/openQA-test.spec
- dist/rpm/openQA-worker-test.spec
- dist/rpm/openQA.spec
- usr/lib/sysusers.d/geekotest.conf
- usr/lib/sysusers.d/openQA-worker.conf
This is essentially a second try at https://github.com/os-autoinst/openQA/pull/3977, however now with additional checks in place to ensure that the user & group creation actually works. If I implemented the checks correctly, then the CI *should* fail on Tumbleweed until https://build.opensuse.org/request/show/901701 is accepted.
> Reenable sysusers

- t/lib/OpenQA/Test/Utils.pm
I broke this in 71bef7e because it is one of the false-positive changes
done by codespell.
> Fix use of `isnt` in `t/lib/OpenQA/Test/Utils.pm`

- lib/OpenQA/Schema/Result/Assets.pm
- lib/OpenQA/Schema/Result/GruTasks.pm
- lib/OpenQA/Schema/ResultSet/Assets.pm
- lib/OpenQA/Schema/ResultSet/AuditEvents.pm
- lib/OpenQA/Schema/ResultSet/JobSettings.pm
* Mark uncovered line in OpenQA::Schema::Result::Assets
* Delete unused args special case handling in OpenQA::Schema::Result::GruTasks
* Slightly simplify OpenQA::Schma::ResultSet::Assets for full statement coverage
* Slightly simplify OpenQA::Schma::ResultSet::AuditEvents for full statement coverage
* Remove uncovered conditions for internal search of job settings
* Simplify OpenQA::Schema::ResultSet::JobSettings
> More coverage improvements

- container/webui/run_openqa.sh
The output of the command should not get executed as another command.
This should fix problems like https://openqa.opensuse.org/tests/1832939#step/multiple_container_webui/3
```
This account is currently not available.
```
> Fix 'This: command not found' errors

- Makefile
- dist/rpm/openQA-test.spec
- dist/rpm/openQA-worker-test.spec
- dist/rpm/openQA.spec
- usr/lib/sysusers.d/geekotest.conf
- usr/lib/sysusers.d/openQA-worker.conf
Reverts os-autoinst/openQA#3987
@dcermak https://build.opensuse.org/package/live_build_log/devel:openQA/openQA/SLE_15_SP3/aarch64 looks like caused by this. I will prepare this revert in case you don't have time to fix that soon
> Revert "Reenable sysusers"

- lib/OpenQA/Worker/Job.pm
- t/24-worker-jobs.t
- t/api/04-jobs.t
- t/lib/OpenQA/Test/Utils.pm
* See https://progress.opensuse.org/issues/95170
* This also removes the necessity of using `shared_hash` simplifying the
test setup
> Avoid forking in t/24-worker-jobs.t to collect coverage of upload code

- script/openqa-bootstrap
Ticket: https://progress.opensuse.org/issues/95185
Calling `systemctl` ensures that
* systemd is installed
* systemd is running as PID=1
> openqa-bootstrap: Check that systemd is available

- lib/OpenQA/WebAPI/Plugin/Helpers.pm
Small followup to #4003. The code is a little cleaner if it uses validation filters.
> Clean up param_hash helper code

- tools/test_containers_compose
When docker-compose up fails we don't have information to investigate.
This PR show the logs when something wrong happens.
To test the failure case and see the logs. Introduce an "exit 1" as the first line in the script containers/webui/run_openqa.sh. The logs will be showed on the terminal as:
```
Creating webui_db_1 ... done
Creating webui_webui_db_init_1 ... done
ERROR: for webui  Container "XXXXXXXXXXXX" is unhealthy.
ERROR: Encountered errors while bringing up the project.
docker-compose exited with non-zero code 1, showing logs:
Attaching to webui_webui_db_init_1, webui_db_1
....
```
https://progress.opensuse.org/issues/95374
> Show logs when docker compose up fails in the test_containers_compose

- lib/OpenQA/CacheService/Task/Sync.pm
- t/25-cache-service.t
See https://progress.opensuse.org/issues/95299
> Avoid getting stuck syncing tests by adding timeout to `rsync` call

- lib/OpenQA/Schema/Result/JobModules.pm
I guess in case the `details-$name.json` file cannot be read, it makes sense
to report the full filename and not just the test name.
Found this while looking through the code.
> Improve error message (report filename instead of test name)

- lib/OpenQA/WebAPI/Controller/Running.pm
- t/26-controllerrunning.t
* Handle exceptions when reading the image to close the connection in that
case and return the error to the client
* Avoid spamming the log with the exception
* See https://progress.opensuse.org/issues/95290
---
So far I only tested this with a live test and producing errors manually (e.g. by setting a wrong image path after 5 updates).
> Improve error handling when streaming images for live view

- container/webui/run_openqa.sh
With this commit we ensure that the geekotest can execute commands,
and therefore we could use su to execute commands with this user.
During the investigation of the issue https://progress.opensuse.org/issues/95374
The execution of all the comands in run_openqa.sh script that were executed by
geekotest user (using su), exited with the error "This account is currently not available."
The reason for that is because that the user geekotest exists but doesn't have a default
shell assigned.
`webui_db_init_1 | geekotest:x:479:479:openQA user:/dev/null:/sbin/nologin`
https://progress.opensuse.org/issues/95374
> Containers: Fix use of su by providing shell for geekotest

- cpanfile
- dependencies.yaml
- dist/rpm/openQA.spec
- lib/OpenQA/CacheService/Model/Cache.pm
Turns log messages like
```
Can't opendir(/var/lib/openqa/cache/bar): Permission denied
at  … line …
Can't opendir(/var/lib/openqa/cache/lost+found): Permission denied
at  … line …
```
into
```
Unable to fully sync cache directory:
Can't opendir(/var/lib/openqa/cache/bar): Permission denied
```
So the context `Unable to …` is added and `at … line …` omitted instead.
The message for `lost+found` is removed completely.
See https://progress.opensuse.org/issues/95299#note-6
> cache service: Avoid logging back-traces when scanning

- t/21-needles.t
The column is actually initialized with `t_updated`, not with `t_created`.
This should fix sporadic test failures like:
```
[08:34:24] t/21-needles.t ............................................ 1/?
```
---
This PR also contains a few style changes, checkout the particular commit (messages) for details.
> t: Fix check for last_updated column of needles

- container/webui/Dockerfile
We observed that some openqa tests fails with this error:
`Mojolicious::Plugin::AssetPack::Pipe::Sass requires ruby`
With this commit we ensure that the required libraries are
installed in the container.
We launched this test https://openqa.opensuse.org/tests/1844018 10 times without errors
https://progress.opensuse.org/issues/95179
> containers: Install ruby and rubygem-sass

- script/openqa-bootstrap
- script/openqa-bootstrap-container
Verified manually locally with
```
podman run --rm -it -v .:/opt/openqa registry.opensuse.org/opensuse/leap:15.3 sh -c 'zypper -n in curl && /opt/openqa/script/openqa-bootstrap'
```
aborting after some time as expected with
```
+ systemctl enable --now postgresql
Created symlink /etc/systemd/system/multi-user.target.wants/postgresql.service → /usr/lib/systemd/system/postgresql.service.
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
```
Related progress issue: https://progress.opensuse.org/issues/95185
> openqa-bootstrap: Ensure to enforce expected error handling

- lib/OpenQA/Utils.pm
- lib/OpenQA/Worker/Job.pm
- t/16-utils.t
- t/24-worker-jobs.t
The `wait_with_progress` function in `OpenQA::Utils` is only used in one place. That place got test coverage [a few days ago](https://github.com/os-autoinst/openQA/commit/0858fdf42e4482808819c7b90bb202b9e37198f8), but `wait_with_progress` was mocked for the test. So it has no coverage itself currently.
Progress: https://progress.opensuse.org/issues/95170
> Cover wait_with_progress with basic tests

- .jsbeautifyrc
I missed this in #4042 with the switch to ESLint.
> Remove .jsbeautifyrc, since it is no longer needed

- lib/OpenQA/Schema/Result/Jobs.pm
Issue: https://progress.opensuse.org/issues/95730
We try to search for a Job with `$self->id` and no `clone_id`, and update
it with the new `clone_id`.
If no rows are affected then it means that `$self` had already set a
`clone_id` in the database, but we didn't reload the values of self, that's why
it is undef and producing a warning.
Instead we search for the Job again now.
> Avoid perl warning in string concatenation

- t/21-needles.t
b863ebe1c31 did not help. I assume the code
`$self->update({last_updated => $self->t_updated});` does not ensure that
both values are in sync with a very high accuracy. This shouldn't be a
real problem so I'm just updating the test.
> t: Fix check for `last_updated` column of needles

- t/ui/14-dashboard.t
This fixes running the test in non-headless mode on a big screen and it
likely also prevents sporadic failures in headless mode (see
https://progress.opensuse.org/issues/95839).
> t: Ensure `t/ui/14-dashboard.t` passes also when browser window is big

- t/lib/OpenQA/Test/Utils.pm
The test is not all that flaky when i run it locally, but in 20 runs i did see 3 cases where the unstable worker code did not run. We'll have to see after a few Circle CI runs if that does the trick.
Progress: https://progress.opensuse.org/issues/80274
> Mark most of the unstable worker test code as uncoverable

- t/43-scheduling-and-worker-scalability.t
- t/lib/OpenQA/Test/Utils.pm
Preferred alternative to https://github.com/os-autoinst/openQA/pull/4070 (as it actually makes the test faster).
---
This speeds up the test significantly when coverage analysis is enabled
and fix https://progress.opensuse.org/issues/95851.
Before:
```
NAME                        TIME        CUMULATIVE      PERCENTAGE
wait for workers to be idle 3.113       3.113           24.538%
assign and run jobs         6.884       9.997           54.265%
stop all workers            2.689       12.686          21.198%
```
After:
```
NAME                        TIME        CUMULATIVE      PERCENTAGE
wait for workers to be idle 2.530       2.530           57.529%
assign and run jobs         1.838       4.368           41.803%
stop all workers            0.029       4.397           0.667%
```
> t: Disable coverage report for forked processes in scalability test

- t/ui/14-dashboard.t
With
```
count_fail_ratio prove -l t/ui/14-dashboard.t
```
in my local environment I get 20/20 passed with a runtime of 21-23s.
> t: Bump timeout for ui/14-dashboard.t

- t/43-scheduling-and-worker-scalability.t
See https://github.com/os-autoinst/openQA/pull/4084#issuecomment-889132807
> Make scalability test setup independent of test data from `os-autoinst`

- .circleci/config.yml
- Makefile
Previously we called prove with the parameter "-v" from within the
Makefile which can make tests quite noisy. As prove already outputs
context to errors in case any happen I consider a better default to run
without "-v" but keep the verbose parameter for CI runs, hence this
commit is removing the "-v" from prove arguments by default but adding
them instead in .circleci/config.yml. With the new Makefile variable
"EXTRA_PROVE_ARGS" one can still select the verbose mode when calling
make without needing to replicate any other necessary prove arguments.
> Make default test runs less noisy

- .eslintrc.json
- assets/javascripts/audit_log.js
- assets/javascripts/job_templates.js
- assets/javascripts/openqa.js
A first followup to #4042. It enables all rules from the `eslint:recommended` set that are related to syntax and logic errors. We had quite a few violations of the [no-prototype-builtins](https://eslint.org/docs/rules/no-prototype-builtins) rule for example.
Progress: https://progress.opensuse.org/issues/91638
> Enable eslint:recommended rules related to syntax and logic errors

- t/api/02-iso-download.t
It should not be required, see https://progress.opensuse.org/issues/93883
> Remove `collect_coverage_of_gru_jobs` from `t/api/02-iso-download.t`

- tools/generate-packed-assets
We observed this kind of errors in the openqa test at install_from_git
[warn] [AssetPack] Unable to download https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.css: Connect timeout
This PR introduces a retry on the tools/generate-packet-assets in
case the asset download fails
https://progress.opensuse.org/issues/95995
> Retry the assets package generation if a CDN fails

- lib/OpenQA/Constants.pm
- lib/OpenQA/Markdown.pm
- lib/OpenQA/Utils.pm
- t/16-markdown.t
The regex used until now would not recognize fragment identifiers (part of the url that comes after '#'), which is now fixed. 
The accepted characters for fragments were derived from it's definition in https://datatracker.ietf.org/doc/html/rfc3986#section-3.5.
> Add regex and tests for fragment identifier recognition

- dist/rpm/openQA.spec
Changing the test flags in
https://github.com/os-autoinst/openQA/pull/4084 caused
t/43-scheduling-and-worker-scalability.t to be added to tests when
previously we never ran (and could not run) this test in OBS.
Related progress issue: https://progress.opensuse.org/issues/96545
> spec: Exclude t/43-scheduling-and-worker-scalability.t from tests again

- t/33-developer_mode.t
- t/full-stack.t
- t/lib/OpenQA/SeleniumTest.pm
- t/ui/01-list.t
- t/ui/02-list-group.t
- t/ui/06-operator_links.t
- t/ui/10-tests_overview.t
- t/ui/12-needle-edit.t
- t/ui/13-admin-no-login.t
- t/ui/13-admin.t
- t/ui/14-dashboard-parents.t
- t/ui/14-dashboard.t
- t/ui/15-admin-workers.t
- t/ui/15-comments.t
- t/ui/15-search.t
- t/ui/16-activity-view.t
- t/ui/16-tests_dependencies.t
- t/ui/16-tests_job_next_previous.t
- t/ui/17-product-log.t
- t/ui/18-tests-details.t
- t/ui/19-tests-links.t
- t/ui/21-admin-needles.t
- t/ui/23-audit-log.t
- t/ui/24-feature-tour.t
- t/ui/25-developer_mode.t
- t/ui/26-jobs_restart.t
- t/ui/27-plugin_obs_rsync_status_details.t
- t/ui/28-keys_to_render_as_links.t
Where it is is too late; if you actually hit the condition, you
get this error:
Parse errors: Plan (1..0) must be at the beginning or end of the TAP output
Bad plan.  You planned 0 tests but ran 3.
This fixes that by moving it up a line.
> Fix skip_all in 27-plugin_obs_rsync_status_details.t

- dist/rpm/openQA.spec
The UnXz module is required to decompress .xz files which are commonly created
by the kiwi appliance builder on OBS. If this package is not required, then its
availability on the webui is accidental and can cause hard to debug "download"
errors like reported in https://progress.opensuse.org/issues/94997
> Add IO::Uncompress::UnXz to dependencies

- lib/OpenQA/WebAPI/Controller/API/V1/Search.pm
- t/api/15-search.t
- t/data/openqa/share/tests/opensuse/tests/openQA/search.py
- templates/webapi/search/search.html.ep
The code actually hard-codes *.pm to avoid picking up other files but this should include *.py since test modules can be written in Python.
Related: [poo#91257](https://progress.opensuse.org/issues/91257)
> search: Search Python filenames and contents

- .github/workflows/commit_message_checker.yml
see https://progress.opensuse.org/issues/95581
The rules that are checked against are:
- commit subject must begin either with a capital letter (A-Z) or with a tag ([A-Za-z0-9_]:).
- commit subject must be no longer than 72 characters
- commit subject and commit body must be separated by at least one blank line
- each line in commit body must be no longer than 80 characters
> Add yaml file to enable commit message checks

- lib/OpenQA/WebAPI/Auth/OAuth2.pm
When the error "User data returned by OAuth2 provider is insufficient"
appears, it's important for admin to see what data the identity provider
actually returned.
This info will only be logged when log level is set to `debug`.
> Log user data received during OAuth2

- script/fetchneedles
The `$dbuser` only belongs to `www` on openSUSE, on other distributions this group can be different. With this commit, the group becomes configurable and allows to execute this script on systems where there is no `www` group.
> Allow users to change which group $dbuser belongs to

- tools/static_check_containers
Issues:
* https://progress.opensuse.org/issues/96636
* https://github.com/hadolint/hadolint/issues/475
It seems repeated calls to docker can lead to rare unexpected exits with code
127.
While this commit does not fix the cause, it avoids calling docker repeatedly,
which also makes the test faster.
I tested that the check works by introducing an error in one of the files:
```
container/webui/Dockerfile-lb:2:1 unexpected 'F' expecting '#', '\', ADD, ARG, CMD, COPY, ENTRYPOINT, ENV, EXPOSE, FROM, HEALTHCHECK, LABEL, MAINTAINER, ONBUILD, RUN, SHELL, STOPSIGNAL, USER, VOLUME, WORKDIR, a pragma, at least one space, or end of input
```
> ci: Improve hadolint check

- lib/OpenQA/WebAPI/Controller/Admin/Needle.pm
- t/ui/21-admin-needles.t
If you set the "Limit Use:" or "Limit Match:" filter in the
Needles admin UI page to one of the "not last X" options, the
results don't include needles for which the "last use" or "last
match" value is "never" (shown as 'never' in the UI, represented
in the DB as null and in the abstraction layer as undef). This
is a bigger problem than it may seem at first glance because the
value can be 'never' for needles which *have* been seen/matched,
but only a long time ago and all those tests have now been
garbage-collected.
This fixes that, and also enhances the test to check these cases
(using both the 'custom' option and a pre-rolled option, as
those actually hit two different code paths). It also corrects
the existing tests a bit.
> Fix "not last X" needle searches to include "never" results

- lib/OpenQA/Worker.pm
- t/24-worker-overall.t
A few changes I came up with when investigating https://progress.opensuse.org/issues/96710. See particular commit messages for details.
> worker: Do not remove timer after delay and extend unit tests

- t/lib/OpenQA/Test/FullstackUtils.pm
fullstack test: Extended wait for result panel
- The job is still running and the check times out
-  Bail out whenever the expected result was not found
See: https://progress.opensuse.org/issues/95836
> fullstack: Extended wait for result panel

- lib/OpenQA/Worker.pm
- t/24-worker-overall.t
* Turn `try` into `eval` so the contained `return` actually returns from
the enclosing `sub`
* No longer log `Another error occurred…` when that's not actually the
case
* No longer stop the worker immediately after the first exception
* Log error message from the `eval` block
* Improve tests
* Check whether the event loop is actually stopped in a controlled way
* Check whether all error messages are logged
* Check whether relevant functions are called exactly as many times as
expected
* See https://progress.opensuse.org/issues/96710
> Improve worker's exception handling and related test

- lib/OpenQA/Worker.pm
* Use a normal sleep when waiting for the worker cache instead of running
the event loop
* Handling `MAX_SETUP_TIME` will no longer work
* Handling job cancellation during the setup will no longer work
* See https://progress.opensuse.org/issues/96710#note-15
> worker: Workaround errors in web socket handling

- t/full-stack.t
- Mojo::File::path->slurp croaks on error
- This way the test plan won't be broken
See: https://progress.opensuse.org/issues/95836
> fullstack: Return early if stat fails to avoid file errors

- lib/OpenQA/Worker.pm
- lib/OpenQA/Worker/Engines/isotovideo.pm
- lib/OpenQA/Worker/Job.pm
- t/24-worker-engine.t
- t/24-worker-jobs.t
- t/24-worker-overall.t
* Possibly fix crashes in web socket processing during setup
* Use proper callback instead of `delay` function when waiting for the
cache service
* See https://progress.opensuse.org/issues/96710#note-15
---
The `delay` function can later be removed from the worker. This is not
included to avoid conflicts with #4123 (which we might want to merge
fast). Removing the delay function would [save use 44 lines of code](https://github.com/os-autoinst/openQA/commit/9b0a11ca499f48d6f760077a59ac260227e1cc82)
so in total the additional number of lines due to this change is < 30 and
it is less hacky.
Before merging this PR I need to do some more testing, possibly even
applying it on one production worker (e.g. openqaworker5).
> worker: Use proper callback instead of `delay` function during setup

- docs/WritingTests.asciidoc
This should clear up the confusion about how we currently load needles if
`CASEDIR` is customized which came up in the ticket
https://progress.opensuse.org/issues/94735.
> Document that needles will not be loaded from a custom CASEDIR

- t/lib/OpenQA/Test/FullstackUtils.pm
Rather than increasing the timeouts, we can scale them. This requires tests to use TimeLimit but we should do that anyway.
See: https://progress.opensuse.org/issues/95836
> fullstack: scale panel waits via TimeLimit

- t/24-worker-engine.t
The `package …` lines for sub packages sometimes show up as uncovered lines
so this change marks them as uncoverable like we already do in other
places.
> Avoid uncovered lines in `t/24-worker-engine.t`

- lib/OpenQA/Scheduler.pm
- t/lib/OpenQA/Test/Utils.pm
I've tried a few different things, like running the stale job detection code on scheduler startup, but that doesn't really gain us anything. So, in the end the simplest solution won, and i just marked the line as uncoverable. There is only one test (`33-developer_mode.t`) that starts a scheduler with the timer active anyway. And the stale detection code has reasonable coverage independently through `20-stale-job-detection.t`.
Progress: https://progress.opensuse.org/issues/96519.
> Fix flaky coverage of lib/OpenQA/Scheduler.pm

- docs/WritingTests.asciidoc
It was rather unclear what the last two paragraphs of docs/WritingTests.asciidoc mean. With this commit, this should now be a bit better.
> [doc] Make the PRODUCTDIR overwrite docs less confusing

- Makefile
- dist/rpm/openQA-test.spec
- dist/rpm/openQA-worker-test.spec
- dist/rpm/openQA.spec
- usr/lib/sysusers.d/geekotest.conf
- usr/lib/sysusers.d/openQA-worker.conf
Next try at enabling systemd-sysusers, this time with the `_openqa-worker` and `geekotest` users having a login shell set.
This reverts commit c5ef15d99194f0f0600d2df5716643cc107c8231.
> Reenable sysusers once again

- lib/OpenQA/WebAPI/Auth/OpenID.pm
- t/03-auth.t
Ticket: https://progress.opensuse.org/issues/89710
I'm introducing a new dependency `Convert::Base32` to encode the return url parameter.
If I don't do this and only do the regular urlencoding that should normally be sufficient,
this error appears:
```
[debug] [Vsohuwj_cWLv] Routing to controller "OpenQA::Shared::Controller::Session" and action "response"
[debug] Net::OpenID::Consumer: Cache MISS for https://www.opensuse.org/openid/user/dheidler
[debug] Net::OpenID::Consumer: Cache MISS for https://www.opensuse.org/openid/yadis/dheidler.xrds
[debug] Net::OpenID::Consumer: Cache MISS for https://www.opensuse.org/openid/user/dheidler
[debug] Net::OpenID::Consumer: semantic info (https://www.opensuse.org/openid/user/dheidler) =
[debug] Net::OpenID::Consumer: Server is …
```
> Return to previous page on openID login

- t/lib/OpenQA/SeleniumTest.pm
- t/ui/12-needle-edit.t
Not a huge win, but a win.
Before
```
t/ui/12-needle-edit.t .. ok    
All tests successful.
Files=1, Tests=19, 77 wallclock secs ( 0.10 usr  0.04 sys + 190.67 cusr 15.16 csys = 205.97 CPU)
Result: PASS
```
After:
```
t/ui/12-needle-edit.t .. ok    
All tests successful.
Files=1, Tests=19, 42 wallclock secs ( 0.12 usr  0.01 sys + 23.23 cusr  1.20 csys = 24.56 CPU)
Result: PASS
```
Progress: https://progress.opensuse.org/issues/96564
> Speed up 12-needle-edit.t by running all Minion jobs in foreground

- lib/OpenQA/BuildResults.pm
Comments were fetched for every job, although those with keys already seen
were skipped and those comments never processed.
This resulted in response times up to 51 seconds for job groups with builds with many jobs.
I tested with the job group 309 locally, and it went from 4.6 to 0.9s.
> Optimize group_overview

- docs/Installing.asciidoc
See https://progress.opensuse.org/issues/76924#note-10
> Add documentation for upgrading PostgreSQL database

- tools/tidy
Otherwise one gets the following error messages when running tidy because
the database directory for the docker-compose setup is not accessible:
```
find: ‘./container/webui/workdir/db’: Keine Berechtigung
```
Due to the strict error handling of the script this prevents tidy to work.
This change simply prevents `find` from traversing the directory.
> Fix permission errors when running tidy after creating docker-compose setup

- lib/OpenQA/Worker/Job.pm
- lib/OpenQA/Worker/WebUIConnection.pm
- t/24-worker-jobs.t
It'll look like this:
```
[debug]   Uploading artefact bar
[warning] Error uploading bar: 500 response: Foo
[warning] Uploading artefact bar (attempts remaining: 4/5)
…
[warning] Uploading artefact bar (attempts remaining: 1/5)
[warning] All 5 upload attempts have failed for bar
[error]   Error uploading bar: 500 response: Foo
```
So the reason for failing attempts is logged and it is clear that a new
upload attempt starts. Previously the message
```
[warning] Upload attempts remaining: 4/5 for bar
```
was logged but not `Uploading artefact bar` anymore which made it look
like no further attempt was actually made.
Related to https://progress.opensuse.org/issues/94531 but not a fix.
> Improve logging for artefact uploads

- lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
- t/api/04-jobs.t
* Return a 400/500 error when creating an artefact fails so the worker
would log the error and retry in case of the 500 error
* We've seen cases in production where result files are missing but no
final upload error (after exhausing all attempts) is logged, see
https://progress.opensuse.org/issues/94531#note-35. This change might
fix those problems.
> Return errors on artefact creation correctly 

- assets/stylesheets/admin-pages.scss
- templates/webapi/admin/user/index.html.ep
Additionally, use consistent colors and avoid rendering `ARRAY(0x…)`.
Just checkout https://openqa.opensuse.org/admin/users to see the problem.
The fixed version looks like this:
> Fix checkboxes on users table broken by ForkAwesome migration (35a5333) 

- lib/OpenQA/Schema/Result/Jobs.pm
When investigating for https://progress.opensuse.org/issues/98388 I came across this code we might want to change. I suppose it makes generally sense to reduce the redundancy here.
> Simplify code for making asset hash

- docs/Pitfalls.asciidoc
Add the error message `unable to upgrade ws to command server` in the Pitfalls debug developer mode section
Related ticket: https://progress.opensuse.org/issues/97952
> Add common error message in pitfalls.asciidoc

- lib/OpenQA/Schema/Result/Jobs.pm
- lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
* Remove code for initializing otherwise unused variable `$days`
* Remove code checking for return codes because the involved functions
actually throw exceptions; this code paths were not covered by tests
anyways and would have already lead to a 500 response
* Write code in a more compact way
> Simplify code for artefact creation

- lib/OpenQA/Schema/ResultSet/Assets.pm
This should bring statement coverage for the file to 100%
> OpenQA::Schema::ResultSet::Assets: Mark single exception log as uncoverable

- assets/javascripts/openqa.js
- assets/javascripts/test_result.js
- lib/OpenQA/WebAPI.pm
- lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
- t/api/04-jobs.t
- t/ui/15-comments.t
Issue: https://progress.opensuse.org/issues/91773
TODO:
~~- [ ] Make it a feature switch (Don't know yet how to do that from client side)~~
I added a new API route `/experimental/jobs/<id>/status` because it is much cheaper than `/jobs/<id>` which fetches also job_dependencies (2 selects) and assets (1 select per asset).
This is up for discussion, but it could be useful for other tools fetching the status of a job regularly.
Edit: I skip the feature switch as discussed in the daily. We don't expect a high performance impact, if any.
> Fetch and display job status for test urls in comments

- docs/Installing.asciidoc
This commit moves the database migration section to the advanced chapter
to keep the basic installation simpler for new users. Existing and
advanced users might need to follow a database version migration but
there are also use cases of fresh reinstalls if the test results in the
database are not worth to keep or container setups with externally
maintained databases.
This is a follow-up to commit 413abd4,
https://github.com/os-autoinst/openQA/pull/4171
which introduced the section about database migration.
> docs: Treat database migration as advanced topic

- lib/OpenQA/WebAPI/Controller/Main.pm
OPENQA_WEBUI_INACTIVITY_TIMEOUT allows overriding the 90s default.
See: https://progress.opensuse.org/issues/97856
> overview: Add higher inactivity timeout

- lib/OpenQA/Schema/ResultSet/Assets.pm
- lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
- t/api/04-jobs.t
Otherwise it looks like the asset is known but does not exist and one gets
an error about the missing asset when trying to restart a job requiring it.
This is basically a follow-up of
https://github.com/os-autoinst/openQA/pull/4136 which introduced the
regression.
---
@mdoucha This fixes the problem you've mentioned in chat.
> Refresh asset size after the upload has been completed

- lib/OpenQA/WebAPI/Plugin/Helpers.pm
- t/ui/18-tests-details.t
Some very long tests, such as https://openqa.opensuse.org/tests/1851295 (very slow because no KVM acceleration is used) can exceed 24 hours. 
Duration is currently shown as `25:23` minutes. With this patch, it will be shown properly as `1 day 00:25 hours`
> format_time_duration: Also display days in test duration

- container/worker/Dockerfile
As OBS seems to do some black magic zypper commandline parsing
and not supporting recommends.
https://progress.opensuse.org/issues/97751
> Explicitly install os-autoinst dependencies in container

- lib/OpenQA/Worker/Job.pm
When a worker is shared for certain jobs, specially when it comes to svirt jobs, can become a bit difficult to figure out in which webUI a job has been executed or triggered from, leaving room for potential collisions (see poo#97532 for instance).
Depends on: https://github.com/os-autoinst/os-autoinst/pull/1777
> Add OPENQA_HOSTNAME to the job settings

- templates/webapi/test/overview.html.ep
Current 'module' and 'module_re' are confusing for openqa users
> Make clear 'Module' field in test overview page

- lib/OpenQA/Worker.pm
Printing directory name helps new users to investigate permissions.
Also this is the only related error message which does not print the directory name.
Signed-off-by: Petr Vorel <pvorel@suse.cz>
> Worker.pm: Print pool directory on error

- profiles/apparmor.d/usr.share.openqa.script.worker
Reverting a mistaken change, as requested here:  https://github.com/os-autoinst/openQA/pull/4199#discussion_r713637429
> Revert mistaken worker write access to needles

- docs/GettingStarted.asciidoc
- docs/Installing.asciidoc
- docs/UsersGuide.asciidoc
- etc/openqa/openqa.ini
- lib/OpenQA/Setup.pm
- lib/OpenQA/Task/Asset/Limit.pm
- lib/OpenQA/Task/AuditEvents/Limit.pm
- lib/OpenQA/Task/Bug/Limit.pm
- lib/OpenQA/Task/Job/Limit.pm
- lib/OpenQA/Task/Utils.pm
- t/37-limit_assets.t
- t/config.t
* Default behavior remains unchanged (all cleanup tasks block each other)
* For simplicity this setting affects all cleanup tasks (and not just asset
and result cleanup).
* See https://progress.opensuse.org/issues/98922
> Allow configuring concurrent cleanup

- lib/OpenQA/Utils.pm
- lib/OpenQA/WebAPI/Plugin/Helpers.pm
- t/14-grutasks.t
- t/25-cache.t
- t/ui/18-tests-details.t
- templates/webapi/test/downloads.html.ep
Verification run: http://quasar.suse.cz/tests/7187#downloads
Obviously https://github.com/os-autoinst/openQA/pull/4212, i.e. printing "(does not exist)" still works :)
> Display asset size

- templates/webapi/test/overview.html.ep
We have filter options applying to the complete job as well as the
test modules. For modules we already prefix the strings with "Module".
So to be extra-explicit we can add "Job" as prefix for "Result" and
"State".
Related progress issue: https://progress.opensuse.org/issues/98460
> templates: Clarify which filter options in /overview apply to the job

- lib/OpenQA/Schema/Result/Assets.pm
- lib/OpenQA/Schema/ResultSet/Assets.pm
- lib/OpenQA/Task/Asset/Limit.pm
- t/37-limit_assets.t
See particular commit messages and https://progress.opensuse.org/issues/97979#note-13 and further comments.
> Optimize asset cleanup

- t/05-scheduler-full.t
Use `wait_for_or_bail_out` instead of for-loop.
Ticket: https://progress.opensuse.org/issues/98898
> Try to fix sporadic CircleCI issues in 05-scheduler-full.t

- lib/OpenQA/Schema/Result/Jobs.pm
- t/15-assets.t
Apparently DBIx produces invalid SQL if the array for the "or" condition
is empty so we need to handle this case specifically to prevent an SQL
exception.
Without the `return [] unless @assets_query;` the extended test fails in
the same way as in https://progress.opensuse.org/issues/99327 so this
change should this this issue.
> Fix computation of missing assets if there are no relevant assets

- lib/OpenQA/Schema/ResultSet/Assets.pm
This avoids the warning
```
Sep 25 23:49:29 openqa openqa[20390]: DBIx::Class::Storage::DBI::select_single(): Query returned more than one row.  SQL that returns multiple rows is DEPRECATED for ->find and ->single at /usr/share/openqa/script/../lib/OpenQA/Schema/ResultSet/Assets.pm line 353
```
which I have observed in OSD logs.
According to my tests with `DBI_TRACE=1` the join does *not* help to avoid
an additional query for the number of jobs (of the asset) anyways.
> Avoid warning in `untie_asset_from_job_and_unregister_if_unused`

- lib/OpenQA/Schema/ResultSet/Assets.pm
- t/15-assets.t
Otherwise the asset cleanup fails due to an SQL error:
```
DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::Pg::st execute failed: ERROR:  invalid input syntax for type boolean: "" [for Statement "UPDATE assets SET fixed = ?, t_updated = ? WHERE id = ?" with ParamValues: 1='', 2='2021-09-28 15:01:21', 3='27487345'] at /usr/share/openqa/script/../lib/OpenQA/Schema/ResultSet/Assets.pm line 99
```
Apparently DBIx cannot cope with the boolean here so one
has to convert to int manually.
See https://progress.opensuse.org/issues/97979#note-26
> Fix SQL error in `refresh_assets` caused by 5b14fe

- container/ci/Dockerfile
- container/devel:openQA:ci/base/Dockerfile
- container/devel:openQA:ci/dependency_bot/Dockerfile
* Base containers for CircleCI jobs on openSUSE Leap 15.3
* Keep other containers as-is
* See https://progress.opensuse.org/issues/99240
> Upgrade CI container image versions to Leap 15.3

- lib/OpenQA/Script/CloneJob.pm
- script/openqa-clone-job
- t/35-script_clone_job.t
Avoid problems when some assets are missing (i.e uefi-pvars), which
aren't really needed for specific cases
```
https://openqa.suse.de/tests/7126208/asset/hdd/SLES-15-SP4-x86_64-Build36.1@64bit-gnome-uefi-vars.qcow2 to 
/srv/data/openqa/development_basedir/openqa/share/factory//hdd/SLES-15-SP4-x86_64-Build36.1@64bit-gnome-uefi-vars.qcow2
7126208 failed: SLES-15-SP4-x86_64-Build36.1@64bit-gnome-uefi-vars.qcow2404 Not Found
```
> Add ignore-missing-assets to clone-job

- profiles/apparmor.d/usr.share.openqa.script.openqa
Issue: https://progress.opensuse.org/issues/99195
In Leap 15.2, /bin/sh points to /bin/bash, while in 15.3,
it points to /usr/bin/sh -> /usr/bin/bash
Using the opportunity to also allow dash.
> Allow more shells in apparmor profile

- lib/OpenQA/Task/Job/FinalizeResults.pm
So we actually get something in stderr in case it times out
Issues: https://progress.opensuse.org/issues/99519, https://progress.opensuse.org/issues/99741
> Run hook script timeout in verbose mode

- tools/ci/run_unit_tests.sh
* https://bugzilla.opensuse.org/show_bug.cgi?id=1191429 has been marked as
fixed so the workaround should no longer be required
* See https://progress.opensuse.org/issues/100850
> Remove workaround for broken Chromium on Leap 15.3

- lib/OpenQA/Worker/Isotovideo/Client.pm
* Use only the debug level because for the user these messages are not
important
* Clearly state that this is *not* the reason for the test failure
* Change phrasing to make it sound less severe
> Make logging when stopping command server gracefully less confusing

- systemd/openqa-reload-worker-auto-restart@.path
Add an `[Install]` section to the unit. Otherwise, trying to enable it only
results in the message "The unit files have no installation config. … This
means they are not meant to be enabled using systemctl.". However, this
unit is actually meant to be enabled as implied by `Installing.asciidoc`.
> Fix enabling systemd unit `openqa-reload-worker-auto-restart@.path`

- t/25-cache-service.t
Even on a very fast machine i can't get below 103 seconds for this test. And it's been like this since at least January.
Progress: https://progress.opensuse.org/issues/102221
> Increase time limit for 25-cache-service.t a little

- assets/javascripts/test_result.js
The `href` values were mixed between the _needle_log_ and _test_log_ items.
Fix using and making unique names for each of them.
Signed-off-by: ybonatakis <ybonatakis@suse.com>
> Fix conflicting attr names in collapse class of the investigation tab

- lib/OpenQA/Schema/Result/Comments.pm
- t/17-build_tagging.t
As of SP4 we have build names like `Alpha-202111-1`
which would be displayed as `Alpha` at the moment.
See https://openqa.suse.de/parent_group_overview/15 for example.
> Allow some special characters in tag labels

- t/25-cache-service.t
- t/lib/OpenQA/Test/Utils.pm
Turns out the test spends most of its time in a blocking SQL loop in `Minion::Backend::SQLite`.
Before:
```
All tests successful.
Files=1, Tests=23, 103 wallclock secs ( 0.07 usr  0.01 sys + 15.86 cusr  1.72 csys = 17.66 CPU)
Result: PASS
```
After:
```
All tests successful.
Files=1, Tests=23, 51 wallclock secs ( 0.05 usr  0.01 sys +  5.39 cusr  0.97 csys =  6.42 CPU)
Result: PASS
```
Progress: https://progress.opensuse.org/issues/102221
> Speed up 25-cache-service.t with a shorter worker timeout

- lib/OpenQA/Utils.pm
- t/16-utils.t
The `gitrepodir` returns the url directly as it appears in the config file,
when the `renderInvestigationTab` expects the value of `data-testgiturl` retrieved from `investigation_ajax`
in the form of _http://github.com/<user>/<repo>/commit_
Apply the same substitution as in git before return
Signed-off-by: ybonatakis <ybonatakis@suse.com>
> Render the test_log value correctly when config has http url

- t/full-stack.t
- t/lib/OpenQA/SeleniumTest.pm
- t/lib/OpenQA/Test/FullstackUtils.pm
- t/ui/15-comments.t
- t/ui/16-tests_dependencies.t
The function merely returns a truthy value. Let's fail always without relying on the caller. This means we will see errors in all cases, not just when something else happens to fail.
I'm also dropping a comment claiming the function aborts.
See: https://progress.opensuse.org/issues/98952
> Fail on unexpected Javascript console errors

- assets/javascripts/tests.js
- docs/UsersGuide.asciidoc
- lib/OpenQA/Scheduler/Model/Jobs.pm
- public/schema/JobTemplates-01.yaml
- t/data/job-templates/schema-invalid.yaml
- templates/webapi/test/infopanel.html.ep
For the openQA "priority" higher numbers mean actually "less priority"
so we considered different words to use, e.g. "niceness" as described on 
https://en.wikipedia.org/wiki/Nice_%28Unix%29 but is also a very
Unix-specific concept. We might prefer more generic terms. Also such
rename would be a breaking change and would need to provide
backward-compatibility and/or a migration path.
Instead here I opted in documentation, help texts and comments to better
express that the specified value is *only* a value and not the priority
per se which is computed internally based on multiple factors.
This commit also adds a help text for the two -/+ buttons where
previously was no help text at all.
This commit was motivated by recurring user questions about the meaning
and the wish to clarify.
> Prevent confusion about "priority"

- script/fetchneedles
This is mostly about making it easy to subsequently tune options used by downstream distros, but I think the changes should be of some benefit for OpenSUSE too.
I've not enabled the git-lfs change here (since you don't use it) but can assure you that it's been in use for openqa.debian.net (and workers) for months, and it works well.
> Fetchneedles improvements

- Makefile
- dist/rpm/openQA.spec
- profiles/apparmor.d/local/usr.share.openqa.script.worker
- profiles/apparmor.d/usr.share.openqa.script.worker
This is useful for example with generalhw backend, which uses
site-specific auxiliary scripts that may need extra profile entries
(or even subprofiles).
This is kind of related to https://github.com/os-autoinst/os-autoinst/pull/1741, but is useful independently too.
> apparmor: allow local additions to the worker profile

- .circleci/config.yml
- .github/workflows/prove.yml
- tools/ci/build_autoinst.sh
- tools/ci/run_unit_tests.sh
- This is not expected to replace or replicate our CircleCI setup,
so no setup of coverage or caches is done here.
- Triggering arbitrary test targets is out of scope.
Fixes: https://progress.opensuse.org/issues/102581
> ci: Execute fullstack tests via GHA

- assets/javascripts/test_result.js
- t/ui/18-tests-details.t
* Remove extra case for displaying errors. This way our tests (which 
render errors) will automatically cover rendering arbitrary fields.
* Remove check for displaying only certain fields; just use the same code
path for all the fields as it already handles the case when there is no
Git repository associated with the diff.
* Otherwise no code has changed. Everything within the previous
`if ([…].indexOf(key) >= 0) { }`-block is just reindentated.
---
* Fix a few other details, see also further commit messages
* See https://progress.opensuse.org/issues/103032
> Fix displaying investigation fields like `diff_to_last_good`

- docs/UsersGuide.asciidoc
The documentation do not make clear what tags exists or whether there are specific ones.
So reading the documentation and wanting to use tagging, user will wonder which tag he needs.
However Openqa does not define further tags other than important in my understanding.
Signed-off-by: ybonatakis <ybonatakis@suse.com>
> Amend description of tag usage in the documentation

- lib/OpenQA/Setup.pm
- lib/OpenQA/WebAPI/Plugin/AMQP.pm
- t/23-amqp.t
- t/config.t
We need to set these query parameters in Fedora infrastructure
in order for message publishing to work. Note they're kind of
odd: they aren't intended for the server to parse, they actually
get consumed on the client before the query is sent, by a rather
indirect route. Mojo::RabbitMQ::Client parses them twice -
first turning 'cacertfile' into 'ca' and 'certfile' into 'cert',
then turning 'certfile' into 'tls_cert' and 'ca' into 'tls_ca'
as options used in a call to `$self->_loop->client`. I didn't
trace it any further than that in detail, but I think these
eventually get used by `Mojo::IOLoop::TLS::negotiate` in
negotiating the TLS connection before the query is sent.
Per its documentation here:
https://metacpan.org/pod/Mojo::RabbitMQ::Client#SUPPORTED-QUERY-PARAMETERS …
> AMQP: allow and handle some TLS-related query parameters

- t/lib/OpenQA/SeleniumTest.pm
- t/lib/OpenQA/Test/FullstackUtils.pm
* t: Prevent non-deterministic test step calculation using wait_for_ajax
* t: Fix timeout calculation in wait_for_developer_console_like
* t: Prevent trying to wait longer for dev console than overall timeout
> Improve full-stack.t - take 2

- t/16-utils.t
Ensure the `.git` directory is cleaned up before testing the case when it
is missing.
> Fix running `t/16-utils.t` multiple times

- lib/OpenQA/Task/Job/Limit.pm
- lib/OpenQA/Task/SignalGuard.pm
- lib/OpenQA/Task/Utils.pm
- lib/OpenQA/Utils.pm
- t/16-utils.t
* Prevent `limit_results_and_logs` jobs and follow-up Minion jobs from
running into "Job terminated unexpectedly" by retrying the jobs instead
* See https://progress.opensuse.org/issues/103416
> Retry Minion jobs for cleaning job results on SIGTERM/SIGINT

- .github/workflows/commit_message_checker.yml
When updating "master" in my personal fork I realized that the git
commit message checker is called and fails due to a commit in master
which by now we can not fix anymore unless we would rewrite the history
in master which we should avoid.
This commit excludes the commit message check to run on pushes to
master.
> CI: Prevent commit message check on master when it is too late

- t/01-compile-check-all.t
- t/01-style.t
- t/24-worker-overall.t
- t/31-client_archive.t
- t/32-openqa_client-script.t
- t/35-script_clone_job.t
- t/43-cli-api.t
- t/43-cli-archive.t
- t/43-cli.t
Also adding a style check to ensure that.
Related progress issue: https://progress.opensuse.org/issues/103617
> t: Consistently use Test::Most everwhere

- lib/OpenQA/Task/Asset/Limit.pm
- lib/OpenQA/Task/AuditEvents/Limit.pm
- lib/OpenQA/Task/Bug/Limit.pm
- lib/OpenQA/Task/Job/Limit.pm
* Use the signal guard introduced by d90f00fd/8b96b710 for all the "limit"
jobs to avoid them failing with "Job terminated unexpectedly"
* See https://progress.opensuse.org/issues/103416 and
https://progress.opensuse.org/issues/99831
---
The code is covered by tests. Not sure whether it is necessary to add explicit checks for all these tasks. I did at least a full stack test for all tasks manually.
> Retry Minion jobs for cleanup on SIGTERM/SIGINT (e.g. service restarts)

- profiles/apparmor.d/usr.share.openqa.script.openqa
I just found this in the openqa-gru log on o3:
```
/opt/os-autoinst-scripts/openqa-label-known-issues: line 84: /usr/bin/hxnormalize: Permission denied
```
> Allow hxnormalize in apparmor config

- t/01-compile-check-all.t
- t/01-test-utilities.t
- t/02-pod.t
- t/05-scheduler-full.t
- t/16-markdown.t
- t/16-utils.t
- t/24-worker-jobs.t
- t/24-worker-settings.t
- t/24-worker-webui-connection.t
- t/25-cache-client.t
- t/25-downloader.t
- t/25-serverstartup.t
- t/27-websockets.t
- t/31-api_descriptions.t
- t/31-client_archive.t
- t/31-client_file.t
- t/32-openqa_client-script.t
- t/32-openqa_client.t
- t/33-developer_mode.t
- t/35-script_clone_job.t
- t/40-job_settings.t
- t/40-openqa-clone-job.t
- t/43-cli.t
- t/44-scripts-modify_needle.t
- t/44-scripts.t
First part of https://github.com/os-autoinst/openQA/pull/4393 . All tests that should pass without problems.
Related progress issue: https://progress.opensuse.org/issues/103617
> t: Add Test::Warnings to most files where missing

- container/worker/launch_workers_pool.sh
- dist/rpm/openQA.spec
- script/configure-web-proxy
- script/openqa-auto-update
- script/openqa-check-devel-repo
- script/openqa-clone-custom-git-refspec
- script/openqa-rollback
- tools/js-tidy
- tools/tidy
* Move the code into a separate file and multiple lines
* Log error details in case something goes wrong by adding the curl flag
`-S` and by printing the OBS response via `trap` to make it clear why
subsequent actions are skipped
* For https://progress.opensuse.org/issues/103692
> Improve health-check for `devel:openQA` repository

- templates/webapi/branding/openSUSE/external_reporting.html.ep
Related to a request brought up by Vincent Moutoussamy.
In 2021-08 there was a product in bugzilla but it was not public so we
adjusted again the bug reporting template in openQA for
https://progress.opensuse.org/issues/96744 , see
https://github.com/os-autoinst/openQA/commit/339968ebc2fd6bedc290a077d19396172c9c4055#diff-2ccd52e84db0aec326ae41923febd47d8d1877952e3abb00dec955ee346342b6
. With going back and forth I am sure that we will not be able to ensure
this for automatic tooling as well as human reporters. So it would be
better find a way where we don't need to change URLs every couple of
months as we will most likely not succeed this way.
> branding: Again adapt bug reporting link for SUSE 15 SP4

- profiles/apparmor.d/usr.share.openqa.script.openqa
As observed on openqa.opensuse.org after enabling archiving.
Related progress issue: https://progress.opensuse.org/issues/103953
> apparmor: Add rules for default archive folder

- lib/OpenQA/CLI/api.pm
- lib/OpenQA/Constants.pm
- lib/OpenQA/WebAPI/Plugin/Helpers.pm
- t/43-cli-api.t
Output in the openqa-cli help:
```
openqa-cli api --osd jobs/overview groupid=135 distri=caasp version=3.0
```
Related progress issue: https://progress.opensuse.org/issues/103864
> cli: List supported search criteria for jobs/overview route

- assets/javascripts/admin_groups.js
- t/ui/13-admin.t
Typing in any `input` affects the modified state. The description
however is a `textarea`.
See: https://progress.opensuse.org/issues/104037
> admin: Check textarea when checking for key input

- lib/OpenQA/Schema/Result/Jobs.pm
* Create archive destination manually before invoking
`File::Copy::Recursive::dircopy` to avoid running into race condition
of the directory creation code of that module
* See https://progress.opensuse.org/issues/104136#note-5
> Avoid "File exists" errors when running archiving jobs concurrently

- lib/OpenQA/Schema/Result/Jobs.pm
- lib/OpenQA/Task/Job/ArchiveResults.pm
- t/10-jobs.t
- t/14-grutasks.t
* Retry archiving jobs when receiving SIGTERM/SIGINT
* Try to conclude cleanup if almost done (should not take long anymore)
* See https://progress.opensuse.org/issues/104116
> Avoid archiving jobs to fail with "Job terminated unexpectedly"

- lib/OpenQA/Schema/Result/JobModules.pm
Fix for these log messages:
```
[2021-11-12T10:41:41.829383Z] [debug] [pid:16406] Unable to read /var/lib/openqa/testresults/02027/02027472-opensuse-15.3-JeOS-for-AArch64-aarch64-Build9.277-jeos@USBboot_aarch64/details-http_srv.json: Can't open file "/var/lib/openqa/testresults/02027/02027472-opensuse-15.3-JeOS-for-AArch64-aarch64-Build9.277-jeos@USBboot_aarch64/details-http_srv.json": No such file or directory at /usr/share/openqa/script/../lib/OpenQA/Schema/Result/JobModules.pm line 99.
```
Progress: https://progress.opensuse.org/issues/102332
> Missing details-*-.json files are expected

- container/openqa/entrypoint.sh
- dist/rpm/openQA.spec
- tools/generate-documentation
- tools/run-tests-within-container
This is the HTTPS mirror run by Fastly on their CDN.
Progress: https://progress.opensuse.org/issues/104164
> Force cpanm to always use a trusted HTTPS mirror

- t/ui/26-jobs_restart.t
- templates/webapi/test/infopanel.html.ep
Screenshot of the new button group:
Advanced restart menu shown:
No restart menu shown where not applicable (on jobs without dependencies), preserving old design:
Related progress issue: https://progress.opensuse.org/issues/69979
> Add advanced restart dropdown menu

- docs/Installing.asciidoc
- docs/WritingTests.asciidoc
- lib/OpenQA/Downloader.pm
- lib/OpenQA/Schema/Result/Assets.pm
- lib/OpenQA/Schema/Result/Jobs.pm
- t/10-jobs-referal.t
- t/10-jobs-results.t
- t/10-jobs.t
- t/25-downloader.t
Motivation: Similar as in
https://docs.microsoft.com/en-us/azure/devops/release-notes/2021/sprint-195-update#automatic-retries-for-a-task
and https://docs.gitlab.com/ee/ci/yaml/#retry and
https://github.com/marketplace/actions/retry-step
Acceptance criteria:
* **AC1:** openQA jobs are automatically retriggered with a maximum amount
specified in test variables
* **AC2:** By default openQA tests apply no automatic retry
Acceptance tests:
* **AT1-1:** *Given* an unfinished openQA test with the special `RETRY`
variable given with value `N` *When* the job fails *And* the current job is
not already the N-th clone of an original job *Then* an automatic clone is
created
* **AT1-2:** *Given* an unfinished openQA test with the special `RETRY`
variable given with value `N` *When* the job fails *And* …
> Add retry of openQA jobs based on test variables

- profiles/apparmor.d/usr.share.openqa.script.worker
`**` is required to allow subfolders (slashes):
https://man.archlinux.org/man/extra/apparmor/apparmor.d.5.en#Globbing
See: https://progress.opensuse.org/issues/103683
> apparmor: Allow access to subfolders under /tmp

- profiles/apparmor.d/usr.share.openqa.script.worker
See: https://progress.opensuse.org/issues/103683
> apparmor: Allow /bin/mkdir as needed on 15.3

- lib/OpenQA/Utils.pm
- t/16-markdown.t
Trying to simplify the comment rules openQA users have to follow for bugrefs.
Progress: https://progress.opensuse.org/issues/104199
> Prevent bugrefs in comments from getting expanded if they are part of a larger string

- script/fetchneedles
GitHub does no longer support unencrypted git: protocol.
See https://progress.opensuse.org/issues/104794
> Change git protocol from git: to https: in fetchneedles

- lib/OpenQA/Shared/GruJob.pm
- lib/OpenQA/Utils.pm
- lib/OpenQA/WebAPI/Auth/OAuth2.pm
- t/14-grutasks.t
Having `use OpenQA::Utils` change the global behaviour of `Data::Dumper` is rather unintuitive. The Mojolicious helper function `Mojo::Util::dumper` should match our `Data::Dumper` requirements with `->Indent(1)->Sortkeys(1)->Terse(1)->Useqq(1)`.
> Avoid action at a distance issues with global config changes

- lib/OpenQA/Utils.pm
Small cleanup. It seems somewhere along the way the `OpenQA::Utils` imports got split up into two blocks.
> Fix OpenQA::Utils import statements

- tools/generate-documentation
In
https://github.com/os-autoinst/openQA/pull/4445
the documentation was generated with the test API content mostly
deleted.
The "last good" CI job in
https://app.circleci.com/pipelines/github/os-autoinst/openQA/8706/workflows/1ba62a05-5bba-4355-9074-b13874ca081b/jobs/82071?invite=true#step-108-292
says from curl "72124" bytes have been received. This is also the number
I get locally. The "first bad" says "54894" bytes have been downloaded
so this is not complete.
To be sure that the HTTP response code actually does not point to an
error we should only continue execution if we really received HTTP
status code "200", similar as we already do for example in
https://github.com/os-autoinst/scripts/blob/8aff4acbd225c4ce614fdc44a7903cffa7c05889/_common#L47
Tested locally with
```
FORMATS=html …
```
> Prevent failed testapi.pm download in doc generation

- profiles/apparmor.d/usr.share.openqa.script.worker
See: https://progress.opensuse.org/issues/103683
> apparmor: Allow /usr/bin/swtpm used by os-autoinst

- lib/OpenQA/CLI/api.pm
res_code isn't initialized if no openQA server is running.
It now defaults to 0 if there is no connection, the "Connection refused" message still appears.
progress.opensuse.org/issues/104836
> Give default value for uninitialized response code

- lib/OpenQA/WebSockets/Controller/Worker.pm
- t/27-websockets.t
Those messages make a great share of openQA's logging as they contain the
full list of job settings. The log message can be useful in certain
debugging scenarios so it can still be enabled via
`OPENQA_LOG_WORKER_STATUS_MESSAGES`. The current worker status (just the
status itself, e.g. 'broken') which is the most important information is
now included in the update log message so it is still there by default.
Related ticket: https://progress.opensuse.org/issues/104967
> Avoid logging worker status messages by default

- assets/javascripts/openqa.js
- t/ui/25-developer_mode.t
This especially concerns the flash messages shown within the developer
mode panel, see https://progress.opensuse.org/issues/104917.
> Fix rendering HTML elements when updating unique flash messages

- assets/javascripts/tests.js
- lib/OpenQA/WebAPI/Controller/Test.pm
- lib/OpenQA/WebAPI/Plugin/Helpers.pm
- t/ui/01-list.t
- templates/webapi/test/list.html.ep
- templates/webapi/test/overview.html.ep
* Deduce initial state of filters from query parameters
* Unify code for making AJAX query parameters and reloading the table
contents
* Make code for help popover a helper to use it on multiple pages
* See https://progress.opensuse.org/issues/104995
> Add checkbox for "TODO" filter unifying code with "relevant" filter

- templates/webapi/branding/openSUSE/external_reporting.html.ep
Available options are:
- `product=SUSE Linux Enterprise Micro 5.0`
- `product=SUSE Linux Enterprise Micro 5.1`
- `product=SUSE Linux Enterprise Micro 5.2`
> Fix reporting URL for SLE Micro

- lib/OpenQA/CLI/api.pm
- lib/OpenQA/CLI/archive.pm
OpenQA/CLI/api.pm and OpenQA/CLI/archive.pm now use signatures.
> Use signatures in OpenQA::CLI::api and OpenQA::CLI::archive

- Makefile
* Conducted 75 runs in the CI which all passed so it seems stable again
* See https://progress.opensuse.org/issues/98952
> Remove retry from fullstack test as it seems stable again

- templates/webapi/test/infopanel.html.ep
"VNC port" makes it sound like a TCP port but a number like "90" or
"104" is not really that. The correct wording should be "VNC display
number".
This was wrong from the beginning, e.g. see 330c949b0 from 2014.
> templates: Fix wording for the "VNC display number"

- lib/OpenQA/Schema/Result/JobGroups.pm
- lib/OpenQA/Schema/Result/Jobs.pm
- lib/OpenQA/Schema/ResultSet/Comments.pm
- lib/OpenQA/Schema/ResultSet/Jobs.pm
- lib/OpenQA/Schema/ResultSet/Users.pm
- t/01-style.t
- t/lib/OpenQA/SeleniumTest.pm
Wherever we use "Mojo::Base" as well as "base" we can simply combine the
both including some redundant "strict" and "warnings" statements which
are also implicitly included with Mojo::Base.
> Simplify base inheritance statement with Mojo::Base everywhere

- assets/javascripts/test_result.js
- lib/OpenQA/Jobs/Constants.pm
- lib/OpenQA/Schema/Result/Jobs.pm
- t/ui/18-tests-details.t
Also in case of incomplete jobs the problem can be caused by something
that the investigation tab could reveal, e.g. invalid test code that
causes the job to abort prematurely with incomplete.
Related progress issue: https://progress.opensuse.org/issues/94792
> Also show "investigation" tabs for incomplete jobs

- lib/OpenQA/Resource/Jobs.pm
- lib/OpenQA/Schema/Result/Jobs.pm
- lib/OpenQA/Schema/ResultSet/Jobs.pm
- lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
- t/api/04-jobs.t
So `openqa-investigate` can use it to handle jobs with parallel
and directly chained dependencies, see
https://progress.opensuse.org/issues/95783.
> Allow changing job settings via restart API

- lib/OpenQA/Schema/Result/Jobs.pm
- t/api/04-jobs.t
* Prevent erroneous dependency creation for parallel parent when the
creation of the clone has been skipped leading to transaction rollback
* Prevent the warning `Duplication rolled back after error: Can't call
method "id" on an undefined` being logged
* Note that the unit test passed before because they didn't check the API
call response, only that certain clones are not present (which is also
the case when the transaction has been rolled back)
> Prevent error when restarting jobs with `skip_parents=1`

- .obs/workflows.yml
I did not add it to .mergify for now. We can just see which tests
will be reported, and then add them to mergify.
Maybe the bug with not reporting the pending status is fixed by then.
Issue: https://progress.opensuse.org/issues/102464
Same as https://github.com/os-autoinst/os-autoinst/pull/1929
> Add OBS workflow

- lib/OpenQA/BuildResults.pm
- lib/OpenQA/Resource/Jobs.pm
- lib/OpenQA/Schema/Result/Jobs.pm
- lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
- t/api/04-jobs.t
This allows to restart jobs so the new jobs are not considered clones. It
will be used by the investigation script as investigation jobs should not
prevent one from restarting the original job as-is.
Related ticket: https://progress.opensuse.org/issues/95783
> Add clone parameter to restart API

- container/ci/Dockerfile
Notably on aarch64 this is package not available.
See: https://progress.opensuse.org/issues/105432
> ci: Conditionally install kvm in container

- .obs/workflows.yml
The changes in this PR are needed due to a breaking change in the
configure_repositories step.
https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.scm_ci_workflow_integration.html#sec.obs.obs_scm_ci_workflow_integration.obs_workflows.steps.configure_repositories_architectures_for_a_project
See also https://github.com/os-autoinst/os-autoinst/pull/1944
> Update the format of the OBS workflow file

- lib/OpenQA/Files.pm
- lib/OpenQA/Git.pm
Adds more perl signatures to `lib/OpenQA/Files.pm` and `lib/OpenQA/Git.pm`
> Add more perl signatures to lib::OpenQA::Files and Git

- t/16-utils-runcmd.t
During my last pull request I noticed a small typo in t/16-utils-runcmd
> Fix typo in t::16-utils-runcmd

- assets/stylesheets/tables.scss
Especially with the new openQA feature of "force_result" it is more
common to see openQA jobs where the result is passed or soft-failed
while there are still failed modules. Right now e.g. in /tests/overview
"failed modules" show up on a green background which could confuse
people thinking of these modules as not failed. We should reconsider
the coloring. This commit changes the styling so that the failed modules
in openQA are rendered with a slightly more alarming design using a
light red background and red border which I made a bit thicker.
**Before:**
**After:**
Related progress issue: https://progress.opensuse.org/issues/95479
> Show "failed modules" with a coloring resembling an failed state

- lib/OpenQA/JobDependencies/Constants.pm
- lib/OpenQA/JobSettings.pm
Adds more perl signatures in lib::OpenQA::JobSettings and lib::OpenQA::JobDependencies::Constants
> Add more perl signatures in lib::OpenQA JobSettings and JobDependencies::Constants

- .tidyallrc
- external/os-autoinst-common/.gitrepo
- external/os-autoinst-common/tools/update-deps
- tools/tidy
Fix includes of script/ in tidyall config
Within the script/ dir we have Perl scripts and other scripts. Just
asking tidyall to include all in script/ would mean that tidyall tries
to apply a Perl style to shell scripts which will obviously fail. So I
am reincluding parts of the rule we had before in tools/tidy to
explicitly select Perl scripts and Perl modules and tests as file
parameters to tidyall. We still need to include the script directory in
.tidyallrc so that it's not excluded even if tidyall is called with an
explicit file list as arguments.
Related progress issue: https://progress.opensuse.org/issues/99678
> Fix includes of script/ in tidyall config

- t/lib/OpenQA/Test/FullstackUtils.pm
- t/ui/25-developer_mode.t
In these tests it is not possible to use
`$driver->find_element('#info_box .card-body')->get_text` because the
element might be swapped out by JavaScript under the hood after it has been
returned by `find_element` and before the text is queried via `get_text`.
This leads to errors like:
```
[16:04:54] t/full-stack.t .. 35/? getElementText: stale element reference: element is not attached to the page document at /home/squamata/project/t/lib/OpenQA/SeleniumTest.pm:80 at /home/squamata/project/t/lib/OpenQA/SeleniumTest.pm line 83.
…
Selenium::Remote::WebElement::get_text(Test::Selenium::Remote::WebElement=HASH(0x55903e1b63d8)) called at /home/squamata/project/t/lib/OpenQA/Test/FullstackUtils.pm line 64
OpenQA::Test::FullstackUtils::find_status_text(Test::Selenium::Chrome=HASH(0x55903dd0fc40)) …
```
> t: Fix querying stale reference in fullstack and developer mode test

- etc/openqa/openqa.ini
- lib/OpenQA/Schema/Result/Jobs.pm
- lib/OpenQA/Setup.pm
- t/config.t
We might want to tweak these settings. It is not clear whether the defaults
are the best for all use-cases.
> Make parameters for carry-over configurable

- lib/OpenQA/Command.pm
- t/43-cli-api.t
Triggered by a Slack discussion. There's really no reason why the path doesn't allow query parameters currently.
> Add support for query parameters to api command

- docs/UsersGuide.asciidoc
- lib/OpenQA/CLI/api.pm
See https://progress.opensuse.org/issues/106762
> doc: Use `async=1` flag in examples for posting a scheduled product (iso)

- tools/generate-documentation
Don't mention the ruby version explicitly (it needs to be ruby 3.1 under TW
now) and make it one command.
> Improve message for installing asciidoctor via zypper

- t/33-developer_mode.t
- t/lib/OpenQA/Test/Utils.pm
I noticed this when reviewing #4517 
* Add `$!` to symlink error message
* Fix setup_fullstack_temp_dir argument
> t: Small fullstack  improvements

- assets/javascripts/test_result.js
- lib/OpenQA/Schema/Result/Jobs.pm
- lib/OpenQA/WebAPI/Controller/Test.pm
- t/ui/16-tests_dependencies.t
* Do not blindly follow the clone chain to the latest job anymore
* Display always the current job, even if it is not the latest clone
* Avoid following the clone chain to the latest job for children if
the child's clone is not a dependency of the parent job anymore
* Avoid following the clone chain to the latest job for parents
* Do not display (directly) chained children of jobs when the clone depth
does not match the one from the current job to avoid dragging too many
jobs into the tree
* See https://progress.opensuse.org/issues/69976
> Show dependency graph also for cloned/restarted jobs

- docs/Installing.asciidoc
Not stopping these services will cause them to fail which one likely wants
to avoid, see https://progress.opensuse.org/issues/107152.
> doc: Mention to stop `…-reload-worker-…`-service in auto-restart setup

- t/lib/OpenQA/Test/Utils.pm
Issue: https://progress.opensuse.org/issues/107002
Alternative to #4524
Note: remove_tree just does nothing if the dir doesn't exist
> t: Cleanup fullstack tempdir before using it again

- lib/OpenQA/Schema/Result/JobGroups.pm
- lib/OpenQA/Schema/ResultSet/JobTemplates.pm
- lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
- lib/OpenQA/WebAPI/Controller/API/V1/Table.pm
- lib/OpenQA/WebAPI/Plugin/YAML.pm
- t/api/08-jobtemplates.t
* Distinguish between errors caused by user-input (1) and unhandled
errors (2)
* Report only (1) to the user and log only (2) to the server log
* Treat constraint violations as user-input related as they are most likely
caused by the input as well
* See https://progress.opensuse.org/issues/106880
> Avoid logging user-input related errors in YAML to server log

- templates/webapi/admin/workers/index.html.ep
The table on the "Workers" admin page shows a column "Arch" which is the
detected architecture on the host running a worker instance. This "Arch"
can be misleading if a worker is used to connect to another, potential
remote architecture system under test. This commit changes the wording
to "Host Architecture" to unambiguously refer to the architecture on the
host machine, not what the backend of a specific openQA worker instance
might refer to.
Related progress issue: https://progress.opensuse.org/issues/107197
> templates: Clarify which "Arch" we refer to on "Workers" page

- script/openqa-bootstrap-container
Call update-ca-certificates in bootstrap-container.
The automated execution of update-ca-certificates now seems to
depend on ca-certificates.path running which is not the case
before the container is started.
Ticket: https://progress.opensuse.org/issues/107242
> Fix outgoing TLS connections in bootstrap-container

- lib/OpenQA/Script/CloneJob.pm
- t/35-script_clone_job.t
The `clone_job` function is called recursively and the recursive call might
already handle the job for which we make the recursive call. In this case
we can simply stop further processing the job to prevent cloning it twice.
This fixes https://progress.opensuse.org/issues/107311.
---
I'll still have to come up with a unit test. So far I only tested locally as
mentioned in https://progress.opensuse.org/issues/107311#note-9.
> openqa-clone-job: Prevent cloning jobs accidentally multiple times

- lib/OpenQA/Schema/Result/Comments.pm
- t/ui/15-comments.t
Removed the regex that specifically excluded `label:force_result` from showing a label icon.
This didn't break any tests locally, but I'm still curious why it was there
https://progress.opensuse.org/issues/105370
> Make force results show a label icon

- lib/OpenQA/CacheService.pm
- lib/OpenQA/CacheService/Controller/Influxdb.pm
- lib/OpenQA/CacheService/Model/Cache.pm
- lib/OpenQA/Utils.pm
- t/16-utils.t
- t/25-cache-service.t
- t/25-cache.t
Progress: https://progress.opensuse.org/issues/106901
> Expose bandwidth data for worker cache via InfluxDB

- etc/openqa/openqa.ini
- t/config.t
- templates/webapi/branding/openqa.suse.de/docbox.html.ep
* branding: Use non-personal daily openQA review links
* branding: Remove outdated reference to caasp staging
* branding: Use new SUSE internal chat reference
* Delete outdated references to novell or microfocus after SUSE split out some time ago
> Update SUSE links for openqa.suse.de branding

- lib/OpenQA/Schema/Result/Jobs.pm
We only want to know if there are modules or not, so a COUNT
is sufficient (and will also not confuse postgres' query planner ;-)
Issue: https://progress.opensuse.org/issues/107701
> Use simpler SQL for has_modules

- lib/OpenQA/WebAPI.pm
- lib/OpenQA/WebAPI/Plugin/Helpers.pm
- templates/webapi/test/logfile.html.ep
- templates/webapi/test/video.html.ep
* This is about the routes for serving the video/logfile pages.
* Prevent log message "Could not render a response …" and 500 response
* See https://progress.opensuse.org/issues/107719
> Avoid 500 response and error in logs when `filename` param not specified

- templates/webapi/main/group_builds.html.ep
- templates/webapi/main/group_builds_functionality_view.html.ep
See https://github.com/os-autoinst/openQA/issues/4311
---
Before:
After:
1
Of course the same applies to the (parent) group overview page as well.
> Avoid horizontal scroll bars on dashboard pages

- lib/OpenQA/WebAPI/Plugin/Helpers.pm
- t/ui/14-dashboard-parents.t
The dashboard's progress bar sections combine certain results. The link
should contain filter parameters for all those results - otherwise the
list of jobs shown in the linked overview page does not match the figure
from the progress bar.
See https://progress.opensuse.org/issues/107878
> Use correct filters in progress bar links

- lib/OpenQA/Worker.pm
- lib/OpenQA/Worker/Job.pm
- t/24-worker-engine.t
- t/24-worker-jobs.t
- t/24-worker-overall.t
- t/24-worker-webui-connection.t
- t/lib/OpenQA/Test/FakeWorker.pm
The worker doesn't retry accepting a job so far. That makes actually sense
because at this point no work has been done anyways and the worker can just
wait for the scheduler to re-assign the job. However, for directly chained
jobs this is not true because the whole chain needed to be restarted in the
case of an error. So we should try a little bit harder - similarly to how
it is already done when the connection is lost during the job execution.
See https://progress.opensuse.org/issues/107746
> Re-try accepting directly chained jobs to avoid skipping whole chain

- lib/OpenQA/WebAPI/Plugin/Helpers.pm
- t/10-tests_overview.t
- templates/webapi/layouts/info.html.ep
- templates/webapi/test/overview.html.ep
In contrast to the other test overview search parameters it must be an
integer. Otherwise we end up with an SQL error (see
https://progress.opensuse.org/issues/107926).
If the `groupid` is invalid a flash message will be shown about it on the
page. Note that this kind of user feedback is not useful for the other
parameters because we only use the validation to filter out empty values
here. So I'm only covering `groupid` here.
> Validate `groupid` parameter properly to avoid SQL errors in logs

- templates/webapi/step/edit.html.ep
Fixes: https://progress.opensuse.org/issues/105157
Before:
After:
> Remove background color and redundant margin in needle editor

- docs/UsersGuide.asciidoc
- docs/WritingTests.asciidoc
* Simplify the wording while trying to be more accurate at the same time
* Add reference to examples for creating a single set of jobs
* Make a clear distinction between the concept of dependency types and the
concept of parents/children
* Wrap paragraphs consistently
* Explain the term "cluster" as it is also often used as there are certain
consequences applying to a "cluster"
* Mention that errors can be checked in the "scheduled product"
* See https://progress.opensuse.org/issues/103962
> doc: Improve documentation about job dependencies

- lib/OpenQA/Script/CloneJob.pm
- script/openqa-clone-job
- t/35-script_clone_job.t
Printing the result of `openqa-clone-job` as JSON would likely be useful
for `openqa-investigate`'s dependency handling (see
https://progress.opensuse.org/issues/95783) but I suppose it is a good idea
in general to provide a machine-readable output format.
> openqa-clone-job: Allow printing result as JSON

- lib/OpenQA/WebAPI/Controller/Test.pm
Related progress issue: https://progress.opensuse.org/issues/108662
> Prevent error about undefined value in next_previous route

- lib/OpenQA/Schema/Result/Jobs.pm
- lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
- lib/OpenQA/Worker.pm
- lib/OpenQA/Worker/Job.pm
- t/05-scheduler-dependencies.t
- t/05-scheduler-serialize-directly-chained-dependencies.t
- t/15-assets.t
- t/24-worker-jobs.t
- t/24-worker-overall.t
- t/api/04-jobs.t
* Consider the result of the relevant directly chained parent job when
deciding whether to skip the next job (instead of just considering the
result of the last job that has been executed)
* Rework queuing logic accordingly
* In particular, keep track of the currently relevant parent when
grabbing the next job from the queue
* See https://progress.opensuse.org/issues/108476
---
~~Still a draft because there's another problem to solve: The worker
doesn't really know whether a test has failed or not at this point (except
when the backend process exists with a non-zero exit code or some
other worker-related error happened). Hence the the logic for skipping
directly chained jobs is still flawed.~~
This is solved now by simply taking the web UI's response into account
when setting a job to …
> Fix wrongly skipping directly chained jobs

- systemd/openqa-websockets.service
- systemd/openqa-worker-cacheservice.service
- systemd/openqa-worker@.service
One should never "Want" the network target as it is meant primarily for
ordering. Also see
https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/
Our systemd services already handle all cases properly at least on the
systemd level by restarting on failure which can happen here e.g. if the
network stack is not properly initialized yet on system start. This
shows up as errors in the service's journal but in the end is properly
handled with a ready and responsive service.
Related progress issue: https://progress.opensuse.org/issues/108091
Related https://bugzilla.suse.com/show_bug.cgi?id=1196359
> systemd: Remove undesired Wants=network.target (boo#1196359)

- docs/WritingTests.asciidoc
- lib/OpenQA/Script/CloneJob.pm
- script/openqa-clone-custom-git-refspec
- script/openqa-clone-job
- t/35-script_clone_job.t
- t/40-script_openqa-clone-custom-git-refspec.t
* Specify the `openqa-clone-job` parameter `--parental-inheritance` so the
modified variables end up in all jobs which are possibly cloned
* We specify `--skip-chained-deps` but for parallel dependencies
parents are cloned as well so it makes a difference here.
* Do *not* override the `TEST` variable. Otherwise all cloned jobs will
have the same `TEST` value which is very confusing, e.g. only one of the
jobs will be shown within the test result overview. Instead, the branch
name is only appended.
* Based on user feedback on https://github.com/os-autoinst/openQA/pull/4537
* Related to the https://progress.opensuse.org/issues/103971 epic
* Tested locally by modifying the script to clone to my local openQA
instance
> Let `openqa-clone-custom-git-refspec` handle dependencies better

- assets/stylesheets/dashboard.scss
- assets/stylesheets/openqa.scss
The previous PR (https://github.com/os-autoinst/openQA/pull/4323) missed one occurrence where we still referenced the old version.
> Update to Bootstrap v4.6.1 for real

- docs/WritingTests.asciidoc
Tested rendering locally with `asciidoctor docs/WritingTests.asciidoc`
Related progress issue: https://progress.opensuse.org/issues/90359
> docs: Add documentation for custom worker engine command ISOTOVIDEO

- lib/OpenQA/Schema/ResultSet/Assets.pm
* Avoid using DBIx's `find_or_create` function which is not atomic¹ and
therefore not race-free which can lead to errors like:
```
duplicate key value violates unique constraint \"assets_type_name\"\nDETAIL:  Key (type, name)=(iso, foo.iso) already exists.
```
* Use `INSERT INTO … ON CONFLICT DO NOTHING` instead (which unfortunately
requires the use of raw SQL)
* See https://progress.opensuse.org/issues/109292 although this is not a
new issue; the oldest scheduled product I found in production was from 3
years ago
---
¹ https://metacpan.org/dist/DBIx-Class/view/lib/DBIx/Class/ResultSet.pm#find_or_create
> Fix race condition during asset registration

- lib/OpenQA/Schema/Result/Jobs.pm
- t/05-scheduler-cancel.t
* Cancel regularly and directly chained dependencies consistently only down
the chain
* Keep the behavior for parallel dependencies as-is (so they are still
canceled up the hierarchy except PARALLEL_CANCEL_WHOLE_CLUSTER is set
to a falsy value)
* Cancellation of the entire chain at once is still possible by
canceling from the root (unless there are multiple roots)
* The cancellation up the chain was already prevented before in certain
cases but whether it worked depended on the internal order in which
dependencies have been traversed
* Be more in-line with user expectations, at least judging by
https://progress.opensuse.org/issues/108476 it expected that
cancellation only affects jobs down the chain
* Track whether the job cluster is computed for cancellation on all levels
of nested …
> Ensure consistent cancellation of chained dependent jobs

- assets/javascripts/audit_log.js
- assets/javascripts/openqa.js
- docs/UsersGuide.asciidoc
- lib/OpenQA/Schema/Result/ScheduledProducts.pm
- t/api/02-iso.t
- t/ui/28-keys_to_render_as_links.t
Those settings will *not* be added scheduled openQA jobs and can be used to
store additional information about the scheduled product itsef, e.g. an URL
to SMELT.
As a bonus I've added a small change to render those setting values as link if
they are HTTP(S)-URLs.
See https://progress.opensuse.org/issues/109554
> Allow adding scheduling settings for informal purposes via `__`-prefix

- lib/OpenQA/Schema/Result/Jobs.pm
- t/32-openqa_client.t
- t/api/04-jobs.t
* Write temporary files to a job-specific location so multiple uploads
don't interfere with each other
* The move in the end should be atomic as it is likely a move within the
same file system (if not I suppose file corruption can still happen)
* See https://progress.opensuse.org/issues/109319
> Avoid corrupted assets on concurrent uploads of same asset

- lib/OpenQA/Utils.pm
- t/api/02-iso.t
Those settings don't need to be checked against the passlist because they
are now actually downloaded as they only serve informational purposes.
(These settings are deleted before `_generate_jobs` so it is ensured they
are not passed to `create_downloads_list`.)
See https://progress.opensuse.org/issues/109512
and https://github.com/openSUSE/qem-bot/pull/13.
> Allow scheduling settings like `__…_URL`

- assets/javascripts/openqa.js
- t/ui/28-keys_to_render_as_links.t
Considering https://github.com/openSUSE/qem-bot/pull/16 and existing code
the same setting value might contain multiple URLs (separated by colons).
This change will render them as individual links.
See https://progress.opensuse.org/issues/109512
> Render multiple URLs in scheduled products table correctly

- profiles/apparmor.d/usr.share.openqa.script.openqa
Likely related issue: https://progress.opensuse.org/issues/107014
> Allow python3 in apparmor

- dbicdh/PostgreSQL/deploy/94/001-auto-__VERSION.sql
- dbicdh/PostgreSQL/deploy/94/001-auto.sql
- dbicdh/PostgreSQL/upgrade/93-94/001-auto.sql
- dbicdh/_source/deploy/94/001-auto-__VERSION.yml
- dbicdh/_source/deploy/94/001-auto.yml
- lib/OpenQA/Schema.pm
- lib/OpenQA/Schema/Result/JobModules.pm
- lib/OpenQA/Schema/Result/Needles.pm
* Migrate job_modules ID to bigint
* Works also if those columns are already bigint (so deployment on manually
migrated instances should not be a problem)
* See https://progress.opensuse.org/issues/109849
> Avoid running into limit when creating job modules

- tools/perlfiles
- tools/tidy
* Document --list
* Add --force option
* Add tools/perlfiles to allow special selection
Issue: https://progress.opensuse.org/issues/110142
For now I'm not adding this to os-autoinst-common because I have to solve the problem that os-autoinst-distri-opensuse uses `readlink -f $0` to get the `os-autoinst/cpanfile`.
See also https://github.com/os-autoinst/os-autoinst/pull/2034
> Sync tools/tidy with os-autoinst

- docs/Contributing.asciidoc
- docs/Installing.asciidoc
- tools/generate-documentation
* Use regular asciidoctor-pdf release
* Fix doc headings and numbers
Issue: https://progress.opensuse.org/issues/110181
> Fix documentation

- systemd/tmpfiles-openqa-webui.conf
Considering 133 GiB of data has piled up on our production instance we
should decrease the retention time. Those files are only used for file
uploads so a value within the range of hours makes more sense.
> Reduce retention of temporary files created by the web UI

- profiles/apparmor.d/usr.share.openqa.script.openqa
Issue: https://progress.opensuse.org/issues/91605
Tested locally on o3
> Allow python3.6 in apparmor

- .github/checklist.yml
- .gitignore
- tools/generate-htmldoc
- tools/generate-htmldoc-in-container
tools/generate-htmldoc
will generate the HTML documentation in a container and
write it to openqa-documentation.html
The checklist suggestes to run this command to check if any asciidoc changes
are looking good, instead of the previous non functioning
tools/generate-documentation suggestion.
Issue: https://progress.opensuse.org/issues/110181
> Add simple command to generate HTML documentation

- profiles/apparmor.d/usr.share.openqa.script.openqa
See also https://github.com/os-autoinst/scripts/pull/150
Issue: https://progress.opensuse.org/issues/91605
> Allow mailx in apparmor

- lib/OpenQA/Schema/Result/Jobs.pm
- t/10-jobs.t
TEST_GIT_HASH or NEEDLES_GIT_HASH might contain UNKNOWN.
To avoid error messages in the log, check and return early.
I moved the git_log_diff mocking to the subtests because it was global and
in my new test I actually did *not* want to mock that method.
Issue: https://progress.opensuse.org/issues/110389
> Deal with unknown git revision

- .circleci/config.yml
This should prevent
```
[09:07:33] t/full-stack.t .. 9/? fatal: unsafe repository ('/home/squamata/os-autoinst' is owned by someone else)
```
> Fix fullstack test by ensuring whole os-autoinst checkout has right owner

- lib/OpenQA/WebAPI/Controller/API/V1/Iso.pm
Progress: https://progress.opensuse.org/issues/110032
> Do not let schedule_iso jobs expire

- lib/OpenQA/CacheService/Controller/Influxdb.pm
If no downloads have been done yet the download rate is unknown. We should
not return 0 in that case as it leads to false alerts.
See https://progress.opensuse.org/issues/110497
> cache service: Emit download rate only if known

- lib/OpenQA/Shared/Plugin/Gru.pm
- t/03-auth.t
Allow the continuously polled stats to be available on an
unauthenticated route to prevent recurring broken requests to the login
provider if not logged in to prevent unnecessary and harmful recurring
traffic to the login provider service, e.g. id.opensuse.org, which
caused the login provider service to misbehave.
First to reproduce the issue what I did was to start a bare openQA
instance with config `httpsonly=0` in etc/openqa/openqa.ini of my openQA
working copy and keeping everything else in place. Then started
`sudo -u
geekotest env OPENQA_BASEDIR=$tmp script/openqa-webui-daemon`
with $tmp
being a directory owned by geekotest and an empty subdirectory db to
prevent an error about unable to create a lock file. Then I went to
http://127.0.0.1:9526/, logged in, then to …
> Fix minion jobs stats retrieval DoS on login provider

- container/worker/Dockerfile
To be able to use cache service, one need to have rsync client in the
worker image. As it is only a recommended package, we need to install it
explicitly.
Related issue: https://progress.opensuse.org/issues/110524
> Install rsync to worker container image

- script/fetchneedles
When running :
`sudo force=1  /usr/share/openqa/script/fetchneedles`
the script takes care to call itself with **sudo -u geekotest** forwarding one by one all the configurations variables.
Add **force** parameter forwarding  to script internal **exec sudo env**
> Add force parameter forwarding in fetchneedles script

- docs/Installing.asciidoc
See 6897a556 for the according implementation fix.
Related progress issue: https://progress.opensuse.org/issues/110899
> docs: Update audit event names according to implementation

- lib/OpenQA/Schema/Result/Jobs.pm
A common use case for job_done_hooks is to handle failed jobs. However
there can be that case that we already sufficiently handle any such
failures by retrying test cases using the openQA retry feature. So if
test maintainers signal the intent that the right approach to handle
failed jobs is to retry we should ensure that we trigger a retry and
hence put a comment on an openQA job to provide a consistent state
before we trigger any asynchronous job_done_hooks which can evaluate
such information, e.g. as
https://github.com/os-autoinst/scripts/blob/master/openqa-investigate
does to detect if an issue is "known" or "unknown" based on the presence
of a comment.
Related progress issue: https://progress.opensuse.org/issues/110911
> Prevent job_done_hooks not knowing that jobs will be retried anyway

- assets/javascripts/test_result.js
Related issue: https://progress.opensuse.org/issues/110677
Due to the lookahead in the
/(\<a.+?)(?=(\<a))/gms
regex the last entry was always omitted.
I used the opportunity to make this a bit cleaner, avoiding
matching HTML.
> Fix displaying of investigation git log

- assets/javascripts/audit_log.js
- lib/OpenQA/Schema/Result/Comments.pm
- lib/OpenQA/Schema/ResultSet/Comments.pm
- lib/OpenQA/WebAPI/Controller/API/V1/Comment.pm
- t/ui/23-audit-log.t
Alternative approach for #4652. Discussions on Slack about another comment related bug showed that it can be quite useful to have `job_id`/`group_id`/`parent_group_id` in the audit log.
Progress: https://progress.opensuse.org/issues/111060
> Link to individual comments from the audit log

- lib/OpenQA/Log.pm
- lib/OpenQA/Worker/Engines/isotovideo.pm
- t/24-worker-engine.t
- t/28-logging.t
Using the same regex we also use in os-autoinst to filter secrets
> worker: Avoid logging secret variables

- etc/openqa/openqa.ini
- lib/OpenQA/Schema/Result/Jobs.pm
- lib/OpenQA/Setup.pm
- lib/OpenQA/WebAPI/Controller/Test.pm
- t/10-jobs.t
- t/config.t
A `git log --stat` can take a long time for several thousands of
commits, especially if there are many changes.
Issue: https://progress.opensuse.org/issues/110677
This commit limits the log to 200 commits.
Currently it is not configurable.
I have tested the `git log --stat` and `git diff --stat` commands, and the worst is the `git log --stat` on the needles repo, it took over 3 minutes in our case. `git diff --stat` is not that bad, so I left it alone.
> Limit git log in investigation tab

- assets/javascripts/comments.js
- assets/stylesheets/comments.scss
- t/ui/15-comments.t
- templates/webapi/comments/add_comment_form_groups.html.ep
- templates/webapi/main/comment_area.html.ep
- templates/webapi/test/comments.html.ep
* [Add button to insert (force result) label into comment text](https://github.com/os-autoinst/openQA/commit/8be09a3e064f27913f3524fbf2ac06d55e999cbb):
* On job page, showing tooltip: ![screenshot_20220519_170804](https://user-images.githubusercontent.com/10248953/169329430-83f51bf9-2427-423a-8a76-c73a0ba91f13.png)
* On group page: ![screenshot_20220519_170934](https://user-images.githubusercontent.com/10248953/169329978-2e7cb42c-4a7f-46cb-a51d-79f0247f5c2a.png)
* [Fix alignment of avatar icons beside comments](https://github.com/os-autoinst/openQA/commit/2406d2a2e77f57338e2fec3ad5d4b4745dbb581b)
* Before:  
* After:
> Improve commenting UI

- container/webui/nginx.conf
- etc/apache2/vhosts.d/openqa-common.inc
- etc/nginx/vhosts.d/openqa.conf
Make websockets server understand the `/api/v1/ws` route which is
currently rewritten by a reverse-proxy to `/ws`. This should remove the
need for having a reverse-proxy as all paths are now handled as are.
There is no need to change anything in the setup as the other route
(i.e. `/ws`) is also handled in the same way.
Prerequisites:
* #4660
> Simplify setup by removing path rewrite

- lib/OpenQA/Schema/ResultSet/Jobs.pm
When users trigger jobs with an invalid job group we already ignore the
setting but so far we reported it as "warning". Well, I do not see what
we could do about this so let's just handle as "info".
Related progress issue: https://progress.opensuse.org/issues/105909
> Reduce log-level of non-critical issue

- lib/OpenQA/Git.pm
- lib/OpenQA/Schema/Result/Jobs.pm
- lib/OpenQA/Utils.pm
- t/16-utils-runcmd.t
The output might be very long and usually not needed in
debug level.
Related issue: https://progress.opensuse.org/issues/110677
> Don't log_debug git stdout in all cases

- etc/openqa/openqa.ini
- lib/OpenQA/Schema/ResultSet/Jobs.pm
- lib/OpenQA/Setup.pm
- lib/OpenQA/WebAPI/Controller/Test.pm
- t/10-tests_overview.t
- t/config.t
- templates/webapi/test/overview.html.ep
Before:
After:
The default of 500 jobs is an arbitrary choice, based on the number of jobs i saw clicking around the latest builds in the O3 database. Around 300 was the maximum i saw there. Happy to change it though.
Progress: https://progress.opensuse.org/issues/110680
> Add a limit for the maximum number of jobs to include in /tests/overview

- docs/Installing.asciidoc
- etc/openqa/openqa.ini
- lib/OpenQA/Task/Job/FinalizeResults.pm
- t/10-jobs.t
This setting allows to disable/enable the hook script per job (or test
suite or wherever the setting is specified). It also comes with a generic
`job_done_hook` configuration setting which will be used in case
`_TRIGGER_JOB_DONE_HOOK=1` is specified and no result-specific job done
hook is configured anyways.
See
* https://progress.opensuse.org/issues/110518
* https://progress.opensuse.org/issues/110530
> Introduce job setting _TRIGGER_JOB_DONE_HOOK to disable/enable hook

- assets/javascripts/comments.js
- lib/OpenQA/Schema/ResultSet/Comments.pm
- lib/OpenQA/WebAPI/Controller/API/V1/Comment.pm
The timestamps `t_created` and `t_updated` are used to check whether a
comment has been edited. They are computed in Perl code (via the package
`DBIx::Class::Timestamps` from our repository). Unfortunately it's `now`
function is invoked for each column individually, e.g. some debug printing
reveals:
```
called DBIx::Class::Timestamps::now: OpenQA::Schema::Result::Comments=HASH(0x55a31d4d9980)
called DBIx::Class::Timestamps::now: OpenQA::Schema::Result::Comments=HASH(0x55a31d4d9980)
called DBIx::Class::Timestamps::now: OpenQA::Schema::Result::AuditEvents=HASH(0x55a31d4d5080)
called DBIx::Class::Timestamps::now: OpenQA::Schema::Result::AuditEvents=HASH(0x55a31d4d5080)
```
That explains why the timestamps might be inconsistent leading to
https://progress.opensuse.org/issues/111542.
Having …
> Prevent new comments from being considered edited

- container/webui/Dockerfile
- container/webui/Dockerfile-lb
- script/openqa-auto-update
Whenever zypper repositories are unavailable or incompletely read it can
happen (and did happen) that packages are forcefully removed as zypper
was forced by us to find a resolution which is not what we want.
Related progress issue: https://progress.opensuse.org/issues/111755
> Prevent dangerous package removal by forcing resolution

- lib/OpenQA/Utils.pm
- t/16-utils.t
```
[2022-04-25T09:17:28.805933Z] [warn] [pid:8752] /var/lib/openqa/share/tests/obs/needles is not a git directory
```
The warning does look very pointless in the openQA log. The `gitrepodir` function is written in a way that encourages probing for information, with a proper return value to indicate failure, and the investigate feature uses it that way already.
Progress: https://progress.opensuse.org/issues/110260
> Remove a pointless git warning

- lib/OpenQA/Schema/ResultSet/Jobs.pm
While looking at that file for another PR, the "monkey patch" caught my eye, which is apparently unnecessary.
Looking further down, the repeated assigning between `$jobs` and `$jobs_to_cancel` confused me, so I generously gave the code two new variables.
> Tiny code improvement

- t/42-df-based-cleanup.t
The new carry-over debugging was producing output here.
Issue: https://progress.opensuse.org/issues/111152
> Avoid unhandled log output

- lib/OpenQA/Schema/ResultSet/Jobs.pm
- lib/OpenQA/WebAPI/Controller/Test.pm
- t/10-tests_overview.t
Every time there are more than 500 jobs in the results we don't know if
the wrong ones have been left out. Because theoretically all 500 could
be sharing the same de-duplication key, taking up the space required by
other more releavant jobs.
The problem is that the de-duplication step needs to happen before jobs
get filtered out by conditions like the result. Unfortunately that
happens in Perl, after the main SQL has already been processed. I've
looked into doing the de-duplication in SQL too, but couldn't find a
solution that was good enough. So for now the best solution is to move
the limit from SQL back to Perl. Which fortunately seems to still be
fast enough for all the cases we care about.
What makes this issue so complicated is that the request and response
data goes through …
> Fix regression by moving tests/overview limit from SQL back to Perl

- systemd/openqa-worker-plain@.service
If the system has a unit implementing time-sync the worker service will
not come up until it can rely on the time. This prevents authentication
errors due to a timestamp mismatch.
See: https://progress.opensuse.org/issues/105855
> systemd: Depend on time being in sync if possible

- etc/openqa/openqa.ini
- lib/OpenQA/Setup.pm
We still see these errors from time to time (see
https://progress.opensuse.org/issues/99345#note-42) and currently there's
no better solution than restarting those jobs.
> Extend regex to restart jobs in case of VNC errors automatically

- docs/WritingTests.asciidoc
TIMEOUT_SCALE is not only affecting MAX_JOB_TIME but test API functions
and other backend specific implementations as well.
> docs: Fix explanation for TIMEOUT_SCALE

- dbicdh/PostgreSQL/deploy/95/001-auto-__VERSION.sql
- dbicdh/PostgreSQL/deploy/95/001-auto.sql
- dbicdh/PostgreSQL/upgrade/94-95/000-warning.pl
- dbicdh/PostgreSQL/upgrade/94-95/001-auto.sql
- dbicdh/_source/deploy/95/001-auto-__VERSION.yml
- dbicdh/_source/deploy/95/001-auto.yml
- lib/OpenQA/Schema.pm
- lib/OpenQA/Schema/Result/Assets.pm
- lib/OpenQA/Schema/Result/Comments.pm
- lib/OpenQA/Schema/Result/DeveloperSessions.pm
- lib/OpenQA/Schema/Result/GruDependencies.pm
- lib/OpenQA/Schema/Result/JobDependencies.pm
- lib/OpenQA/Schema/Result/JobModules.pm
- lib/OpenQA/Schema/Result/JobNetworks.pm
- lib/OpenQA/Schema/Result/JobSettings.pm
- lib/OpenQA/Schema/Result/Jobs.pm
- lib/OpenQA/Schema/Result/JobsAssets.pm
- lib/OpenQA/Schema/Result/ScreenshotLinks.pm
- lib/OpenQA/Schema/Result/Workers.pm
* Convert all database ID-columns of the jobs table and related tables
from integer to bigint
* Adapt code that specifies the types explicitly
* See https://progress.opensuse.org/issues/112265
> Avoid running out of database IDs - jobs table

- lib/OpenQA/Log.pm
- lib/OpenQA/Worker/Engines/isotovideo.pm
- script/openqa-dump-templates
- t/api/04-jobs.t
As with os-autoinst, building openQA with perl 5.36 results in
test failures due to several cases of subs with signatures using
`@_`, which they are not supposed to do. Fortunately the fixes
are fairly straightforward here.
> Fix perl 5.36 warnings on use of @_ in functions with signature

- dbicdh/PostgreSQL/deploy/96/001-auto-__VERSION.sql
- dbicdh/PostgreSQL/deploy/96/001-auto.sql
- dbicdh/PostgreSQL/upgrade/95-96/000-warning.pl
- dbicdh/PostgreSQL/upgrade/95-96/001-auto.sql
- dbicdh/_source/deploy/96/001-auto-__VERSION.yml
- dbicdh/_source/deploy/96/001-auto.yml
- lib/OpenQA/Schema.pm
- lib/OpenQA/Schema/Result/WorkerProperties.pm
- lib/OpenQA/Schema/Result/Workers.pm
* Convert all database ID-columns of worker tables from integer to
bigint
* Re-establishes consistency as `assigned_worker_id` was already converted
to `bigint` in the previous migration
* See https://progress.opensuse.org/issues/112265
> Avoid running out of database IDs - worker tables

- lib/OpenQA/Schema/ResultSet/Jobs.pm
Related progress issue: https://progress.opensuse.org/issues/112718
> Fix warning "Query returned more than one row" for linked comments

- docs/Installing.asciidoc
These things were useful when debugging
https://progress.opensuse.org/issues/112718.
> Document debugging database-related performance problems

- lib/OpenQA/Shared/Plugin/Gru.pm
- lib/OpenQA/Task/Job/FinalizeResults.pm
- lib/OpenQA/Task/Job/HookScript.pm
- t/10-jobs.t
This patch turns the previous proof of concept into a proper feature for
making hook scripts restartable with a special exit code. The hook
script now runs in a separate Minion job, and all parameters are
configurable with environment variables and job settings.
Progress: https://progress.opensuse.org/issues/112523
> Retry hook scripts that use the exit code 142

- .circleci/config.yml
- Makefile
- dist/rpm/openQA.spec
Running all tests as part of the "test" target is the safer approach to
ensure that no tests are overlooked. Many developers will unfortunately
not have all prerequisites to run all the tests necessary locally but
that was already the case in before. Indidvidual test parts can still be
selected explicitly as well as excluded based on variables. So this
commit adds the helm-chart test to the generic "test" target while
configuring it based on the HELM_TEST variable and same as the
CONTAINER_TEST excluding the helm-chart test when the TESTS variable is
specified to select individual test modules.
> Makefile: Ensure "test" includes also helm tests

- lib/OpenQA/Scheduler/Model/Jobs.pm
- lib/OpenQA/Schema/Result/Jobs.pm
- t/38-workers-table.t
This's my Hackweek project :)
The issue ticket: https://progress.opensuse.org/issues/110824
The root cause:
The commit below introduced a regression.   live view and live log of directly chained jobs are not able to work due to this regression. https://github.com/os-autoinst/openQA/commit/591fba9fe7948f963300ff66074c6dd22092f4f1
In lib/OpenQA/Scheduler/Model/Jobs.pm, the line 476:
```$job_data{$_->id} = $_->prepare_for_work($worker, \%worker_properties) for @$jobs``` calls "prepare_for_work" multiples times .  Each call will delete the worker tmp directory created by previous call. In the end, no tmp directory exits so live view and live log can't be generated.
Below is the fix:
The fix will still clean up the tmp directory created by previous schedule, create new tmp directory and assign …
> Fix live view dysfunctional with directly chained jobs

- assets/javascripts/overview.js
- etc/openqa/openqa.ini
- lib/OpenQA/Setup.pm
- lib/OpenQA/WebAPI/Controller/Test.pm
- t/config.t
- templates/webapi/test/overview.html.ep
See https://progress.opensuse.org/issues/111470#note-5
@AdamWill
> Allow configuring results to collapse as parallel children on overview

- t/ui/23-audit-log.t
- tools/unstable_tests.txt
* Wait until the expected number of rows show up in the DataTable (with a
timeout) instead of using `sleep 1` to prevent failures when the one
second is not enough
* See https://progress.opensuse.org/issues/113138
> Fix unstable `t/ui/23-audit-log.t` by implementing wait condition

- assets/javascripts/test_result.js
- t/ui/28-keys_to_render_as_links.t
- templates/webapi/test/settings.html.ep
* Use the JavaScript function that is already used for rendering such URLs
in scheduled product settings
* See https://github.com/os-autoinst/openQA/issues/4740
> Render multi-URLs in job settings correctly

- container/ci/Dockerfile
First needed for
https://build.opensuse.org/package/show/devel:openQA/openqa_dev
Related progress issue: https://progress.opensuse.org/issues/111881
> container: Update CI base to Leap 15.4

- lib/OpenQA/Worker/WebUIConnection.pm
- t/24-worker-overall.t
Also respect OPENQA_WORKER_CONNECT_INTERVAL like in existing cases.
See: https://progress.opensuse.org/issues/105855
> worker: Retry registration on timestamp mismatch

- container/helm/charts/webui/values.yaml
- container/helm/charts/worker/values.yaml
Doing this separately after base images had a chance to be built on Leap
15.4.
After:
* #4745
Related progress issue: https://progress.opensuse.org/issues/111881
> PART 2: Switch helm charts to current openSUSE Leap 15.4 as well - after #4745

- lib/OpenQA/WebAPI/Controller/Test.pm
Comments are accessed via `$job->comments` when rendering them so the
sorting is expected to be ascending by ID via
`__PACKAGE__->has_many(comments => 'OpenQA::Schema::Result::Comments',
'job_id', {order_by => 'id'});` in `Jobs.pm`. However, that's not effective
since we're prefetching the comments here. So it is necessary to specify
the order of the comments when querying the job (where comments are
prefetched).
---
I found this bug when testing #4717. So far I've only tested it manually.
I can extend tests if that's required.
> Fix sort order of comments on job details page

- lib/OpenQA/WebAPI/Controller/Test.pm
If jobs have no `t_finished` timestamp (as they've never run) they are
currently shown before any other jobs. In production that's not a problem
because we hardly cancel jobs before they had a chance to run. However, on
a local system where one experiments with openqa-clone-job that can easily
be the case. This change simply considers `t_updated` if `t_finished` is
not set. That should be good enough because `t_updated` is normally last
set when the job is canceled.
---
Note that this is just something I personally find annoying. I admit that with this
change it is a bit weird that the time of cancellation is shown within the "Finished"
column but I find it better than having the sorting out of place.
> Fix sorting of jobs that have never run on 'All tests' page

- lib/OpenQA/Schema/Result/Jobs.pm
When the investigation route of openQA is called involving jobs that
have an "unreadable git hash", an error message used by os-autoinst in
some conditions, we should ignore the hash same as for the value
"UNKNOWN".
Also tested manually on o3 by looking at investigation tabs of jobs like https://openqa.opensuse.org/tests/2466846#investigation and hot-patching o3 source code.
Related progress issue: https://progress.opensuse.org/issues/113030
> Prevent error about "unreadable git hash"

- lib/OpenQA/Utils.pm
- t/api/02-iso-download.t
This fixes an unexpected error when passing seemingly arbitrary test
variables into openQA that end with _URL. While we treat _URL variables
as special to render clickable links we should not deny scheduling
products when URLs correspond to domains not on the passlist which was
only ever intended for asset downloading.
> Only apply the domain passlist-check for ASSETS as documented

- lib/OpenQA/Schema/Result/Jobs.pm
- t/10-jobs.t
Issue: https://progress.opensuse.org/issues/114829
This can happen if the test failed early, e,g, when downloading an image
failed.
> Avoid server error if vars.json is missing

- profiles/apparmor.d/usr.share.openqa.script.worker
ping is called in backend/ipmi.pm but failed to run in workers due to `sh: /usr/bin/ping: Permission denied`. fg. https://openqa.opensuse.org/tests/2506550.
backend/ipmi.pm:
```
my $ping_cmd = "ping -c$ping_count '$bmwqemu::vars{IPMI_HOSTNAME}'";
eval { system($ping_cmd); };
```
> apparmor: Allow run of ping which is required for ipmi backend jobs

- contrib/ay-openqa-worker.xml
Current versions of Leap would need an explicit Leap selection so the
profile would not be usable for both Tumbleweed and Leap but it seems we
can just rely on the default without an explicit product.
> contrib: Remove conflicting product selection in autoyast

- lib/OpenQA/Task/Job/FinalizeResults.pm
- lib/OpenQA/Task/Job/HookScript.pm
On OSD there are many failed `hook_script`-jobs with with result
`Job terminated unexpectedly (exit code: 0, signal: 15)`. Previously this
was prevented by using `OpenQA::Task::SignalGuard` but when the hook script
was moved to its own Minion job this hasn't been taken into account.
This change removes guard-handling from the finalize task which is now
useless there and introduces guard-handling in the hook script task.
> Fix signal guard for hook script since it is a separate Minion task

- lib/OpenQA/Script/CloneJob.pm
- lib/OpenQA/Script/CloneJobSUSE.pm
- t/35-script_clone_job_suse.t
Before cloning or restarting a job, verify the maintenance update has already been released.  
- Related ticket: https://progress.opensuse.org/issues/109707
> Verify when maintenance update has already been released

- lib/OpenQA/Utils.pm
- t/16-markdown.t
- t/16-utils.t
These have some little quirks: the weird useless /-/ that gitlab
puts in issue URLs, and how pagure uses /issue/ not /issues/ .
> Add support for pagure.io and gitlab.gnome.org trackers

- lib/OpenQA/WebAPI/Controller/API/V1/Worker.pm
I saw some workers on one of our instance were stuck in a failed
registration loop caused by this:
worker[16088]: [info] Registering with openQA http://localhost
worker[16088]: [warn] Failed to register at http://localhost - 500 response: Failed: Undefined subroutine &OpenQA::WebAPI::Controller::API::V1::Worker::log_warning called at /usr/share/openqa/script/../lib/OpenQA/WebAPI/Controller/API/V1/Worker.pm line 114.
worker[16088]:  - trying again in 10 seconds
The log statement was moved from another file in 4928543c86, but
the import wasn't also moved into the new file.
> Don't try and log without importing the log function

- lib/OpenQA/WebAPI/Controller/Admin/Needle.pm
The date/time picker of Firefox and Chromium passes a timestamp without
seconds when a timestamp on a whole minute is selected. So far this is not
accepted by the controller code leading to an alert box complaining about
an AJAX error. This change fixes the issue by allowing the format on the
controller side. Note that minutes and hours always seem to be present.
This issue has been found due to a test failure when the date/time picker
was randomly on a whole minute (see
https://github.com/os-autoinst/openQA/pull/4791#issuecomment-1234391043 and
further comments).
> Fix AJAX/parsing error in needle tables

- lib/OpenQA/Script/CloneJob.pm
I modified the verification flow of maintenance releases. First apply the manually set variable to settings and then verify the maintenance, later download the assets.
Progress Ticket: https://progress.opensuse.org/issues/116788
> Fix the cloning of job when the corresponding variable is manually set

- lib/OpenQA/WebAPI/Controller/API/V1/Table.pm
`/api/v1/products`, `/api/v1/machines`, and `/api/v1/test_suites` share the same backend code for fetching data. The current implementation makes thousands of select queries to fetch settings. That is very inefficient, so this patch switches to a join/collapse based prefetch approach. This is slightly more efficient than a plain prefetch, because it avoids the creation of DateTime objects. See https://metacpan.org/pod/DBIx::Class::ResultSet#collapse for more information about the collapse feature.
Progress: https://progress.opensuse.org/issues/94667
> Improve performance of 3 api endpoints by about 312% (for O3 data)

- .github/stale.yml
Those issues might still be valid, see
https://progress.opensuse.org/issues/117136
> Prevent stalebot from closing stale issues

- container/worker/Dockerfile
This was previously available and got removed somewhere in the 15.3 container lifecycle.
The effect on image size is negligible and it is useful to test images with kernels that only support the 'virtio' graphics driver without requiring a custom worker container.
Fixes https://github.com/os-autoinst/openQA/issues/4795
> Include virtio VGA support in the openqa_worker container

- templates/webapi/branding/openSUSE/external_reporting.html.ep
OpenQA ALP runs are missing the bugzilla report button.
> Add bugzilla link for ALP in webUI

- etc/openqa/openqa.ini
- lib/OpenQA/Setup.pm
- lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
- t/api/08-jobtemplates.t
- t/config.t
We already have a limit for the 'All tests' pages, this implementation follows the same approach.
Might need adjustments based on performance tests with production data.
see: https://progress.opensuse.org/issues/114421
> Limit listing of job_templates to avoid timeouts

- lib/OpenQA/Schema/ResultSet/Screenshots.pm
- lib/OpenQA/WebAPI/Controller/API/V1.pm
- t/42-screenshots.t
On big openQA instances with debug log level enabled I can see multiple
log messages every second which is much more verbose than other type of
messages during normal operation.
> Reduce two verbose log messages to trace level

- script/fetchneedles
Git refuses to override an existing lock file, even if no process seems to use it anymore. When our server crashes such a stale lockfile often remains as leftover. This change will remove the stale lockfile automatically. It will of course keep the lock file in-place if it is still owned by at least one process.
See https://progress.opensuse.org/issues/116911
> Clean stale lockfiles when fetching needles

- Makefile
- docs/Contributing.asciidoc
---
Maybe we should merge the different sections within our documentation where we explain how to run openQA's unit tests. For the sake of the PR I've just adjusted both places (as it is not a big change and relevant to both sections).
> Avoid test failures due to localized error messages

- lib/OpenQA/Schema/Result/GruTasks.pm
- lib/OpenQA/Shared/GruJob.pm
- lib/OpenQA/Task/Asset/Download.pm
- t/14-grutasks.t
* This affects only expected download errors (connection errors, error
responses) but not any kind of unhandled exception or setup related
errors.
* See https://progress.opensuse.org/issues/118969
> Avoid alerts by not failing Minion jobs when downloads fail

- assets/stylesheets/ansi-colors.scss
- assets/stylesheets/comments.scss
- assets/stylesheets/dashboard.scss
- assets/stylesheets/forms.scss
- assets/stylesheets/navigation.scss
- assets/stylesheets/openqa_theme.scss
- assets/stylesheets/overall.scss
- assets/stylesheets/overview.scss
- assets/stylesheets/parent_group_overview.scss
- assets/stylesheets/result_preview.scss
- assets/stylesheets/tables.scss
- assets/stylesheets/test-details.scss
- docs/UsersGuide.asciidoc
- lib/OpenQA/WebAPI.pm
- lib/OpenQA/WebAPI/Controller/Appearance.pm
- lib/OpenQA/WebAPI/Plugin/Helpers.pm
- t/ui/04-appearance.t
- t/ui/05-auth.t
- templates/webapi/appearance/index.html.ep
- templates/webapi/layouts/bootstrap.html.ep
- templates/webapi/layouts/navbar.html.ep
This PR adds theme settings to #4724. The CSS has been reorganised to work with a `.darkmode` class on the `<body>` element. And there is a new "Appearance" menu entry for all logged in users:
The default theme is `light`, same as it used to be. And it can be switched manually to `dark` or browser detection (based on Chrome flag):
Since this feature is only available for logged in users, we can store the theme setting in the session cookie, together with login information. That means we have no additional privacy considerations regarding cookies.
P.S.: I did not make any changes to the darkmode theme itself. There are still some rough edges, but since it is completely opt-in there should be no disruptions for our users.
Progress: https://progress.opensuse.org/issues/119032
> Add darkmode

- lib/OpenQA/Task/Asset/Download.pm
- t/14-grutasks.t
* Commit 4cee25f5feb49e7ee393c1702d52ce10136c2ffd did not consider that `OpenQA::Downloader` might have a successful result but still returns an error which should be treated as such.
* See https://progress.opensuse.org/issues/119182
> Fix error handling in web UI download jobs since 4cee25f

- t/ui/16-tests_job_next_previous.t
`time` is called three times and might return a different number of epoch seconds, resulting in a slight mismatch:
Failed test 'finished and duration of 99901'
at t/ui/16-tests_job_next_previous.t line 143.
got: 'about 4 hours ago ( 59:59 minutes )'
expected: 'about 4 hours ago ( 01:00 hours )'
Seen in #4860
> t: Fix timing error

- assets/stylesheets/comments.scss
- assets/stylesheets/dashboard.scss
- assets/stylesheets/forms.scss
- assets/stylesheets/navigation.scss
- assets/stylesheets/overall.scss
- assets/stylesheets/result_preview.scss
- assets/stylesheets/tables.scss
- assets/stylesheets/test-details.scss
https://github.com/os-autoinst/openQA/commit/28fa7fdd591fac0a0c41a51b03d9281ebc005426 introduced some changes to the default theme. This patch reverts them all, so the default light theme should look the same again. It does make darkmode look worse, but there is no way around that if we want to fix lightmode quickly.
> Bring back the old light theme

- assets/stylesheets/tables.scss
This should be very easy to accept. 😁 
Before:
After:
Progress: https://progress.opensuse.org/issues/119362
> Fix overview table header in darkmode

- assets/stylesheets/overall.scss
**Edit: Outdated screenshots, see last post!**
Before:
After:
I'm starting small. This makes the jumbotron and bootstrap cards visible again.
> Fix jumbotron and card background in darkmode

- assets/stylesheets/overall.scss
Another simple one, `<button>` styling was fine, but `<input>` was not. Now they have a consistent border.
Before:
After:
Progress: https://progress.opensuse.org/issues/119365
> Fix invisible buttons in some forms with darkmode

- templates/webapi/layouts/bootstrap.html.ep
This problem can be observed when loading a very large and slow page like https://openqa.opensuse.org/admin/users. By changing the timing of when we execute the JavaScript code that applies the `.darkmode` class we can prevent this problem.
Progress: https://progress.opensuse.org/issues/119386
> Fix bug where some pages briefly show up with light theme in darkmode

- docs/WritingTests.asciidoc
- lib/OpenQA/Worker/Engines/isotovideo.pm
- t/24-worker-engine.t
* Allows prepending `%CASEDIR%` to relative `NEEDLES_DIR` so `%CASEDIR%` is replaced with the path where the custom `CASEDIR` will be checked out
* Enables use-case of specifying a custom `CASEDIR` and a custom `NEEDLES_DIR` where the custom needles dir is a relative path within the custom `CASEDIR` (and *not* a separate repository or a relative path within the default needles directory).
* See https://progress.opensuse.org/issues/117133
* See https://github.com/os-autoinst/openQA/issues/4576
> Allow specifying `NEEDLES_DIR` to be relative to `CASEDIR`

- templates/webapi/branding/openqa.suse.de/commenting_tools.html.ep
- templates/webapi/comments/add_comment_form_groups.html.ep
Related ticket: https://progress.opensuse.org/issues/107923
> Add button to insert marker for unblocking incident to OSD branding

- etc/openqa/openqa.ini
- lib/OpenQA/Setup.pm
- lib/OpenQA/WebAPI/Controller/Test.pm
- t/config.t
- t/ui/16-tests_job_next_previous.t
This limit implementation follows the same approach as the default and maximum limits for the 'All tests' page as well as the limits for the API call listing JobTemplates
see: https://progress.opensuse.org/issues/114421
> Add default and max limits to job_next_previous_ajax

- templates/webapi/branding/openqa.suse.de/commenting_tools.html.ep
- templates/webapi/comments/add_comment_form_groups.html.ep
Reverts os-autoinst/openQA#4867 due to
https://progress.opensuse.org/issues/119467,
a problem on the group overview page where the comment edit field is also used
> Revert "Add button to insert marker for unblocking incident to OSD branding"

- lib/OpenQA/Worker.pm
We observed a problem that the os-autoinst command server received log
upload attempts but failed with
```
Mojo::Reactor::Poll: I/O watcher failed: Error in tempfile() using template /var/lib/openqa/cache/tmp/mojo.tmp.XXXXXXXXXXXXXXXX: Could not create temp file /var/lib/openqa/cache/tmp/mojo.tmp.mbmTdPv6NyxTOBTy: Permission denied at /usr/lib/perl5/5.26.1/File/Temp.pm line 1102.
```
Setting the environment variable MOJO_TMPDIR from the worker will mean
that also the os-autoinst command server effectively started by
the openQA worker will inherit
The original change was done at a time when the openQA worker itself
downloaded assets before the introduction of the separate cache service
so we can simply remove the corresponding code without replacement.
Related progress issue: …
> Fix log upload from openQA jobs in case of read-only cache directory

- container/openqa_data/data.template/conf/openqa.ini
- docs/Installing.asciidoc
- etc/openqa/openqa.ini
- lib/OpenQA/Git.pm
- lib/OpenQA/Setup.pm
- t/16-utils-runcmd.t
- t/config.t
If there have been previous failures when adding new needles through the needle editor it is possible for the rebase to fail due to uncommitted changes. This commit will ensure that any uncommitted changes are cleaned up before attempting to rebase
> Clean up git repository before rebase

- etc/openqa/openqa.ini
- lib/OpenQA/Schema/ResultSet/JobSettings.pm
- lib/OpenQA/Setup.pm
- lib/OpenQA/WebAPI.pm
- lib/OpenQA/WebAPI/Controller/API/V1/JobSettings.pm
- t/api/04-jobs.t
- t/config.t
- t/fixtures/01-jobs.pl
This PR implements the solution we discussed, which limits the query to the 20000 most recent job ids in the `job_settings` table.
Progress: https://progress.opensuse.org/issues/117655
> Add an API endpoint to find jobs with certain job settings

- etc/openqa/openqa.ini
- lib/OpenQA/Setup.pm
- lib/OpenQA/WebAPI/Controller/API/V1/Asset.pm
- t/api/02-assets.t
- t/config.t
The generic default limit (that was taken from the "All tests" page for jobs) doesn't make any sense here so this change allows us to configure the limit for asset queries separately.
Related ticket: https://progress.opensuse.org/issues/120315
> Add distinct set of limits for assets

- docs/UsersGuide.asciidoc
Within https://progress.opensuse.org/issues/91914 we have implemented
notifications which can be configured per job group. Together with
multiple other features teams can define their testing scope within job
groups and review test results within their scope accordingly. So far we
describe individual features within openQA documentation. We should
extend the openQA documentation to explain the motivation and how to
build a process around job groups.
Related progress issue: https://progress.opensuse.org/issues/111066
> docs: Add a suggested workflow documentation for test review

- assets/javascripts/running.js
- t/ui/25-developer_mode.t
When (un)checking the checkbox "Pause on next command" of the developer mode and then clicking on "Confirm …" the checkbox is reset to its previous state. This changes fixes this so the selection is actually submitted.
> Fix submitting "Pause on next command" selection of developer mode

- lib/OpenQA/Worker.pm
* Make it unnecessary to specify `WORKER_HOSTNAME` in `workers.ini` if `hostname --fqdn` returns the expected name.
* Tested the used functions of the `Net::Domain` module on multiple production worker hosts (using Leap 15.3 and 15.4). They behave as expected (so workers will still register using the short hostname and `WORKER_HOSTNAME` will be set to `hostname --fqdn`).
* Required on worker level for the developer mode (independently of how the variable is handled by os-autoinst)
* See https://progress.opensuse.org/issues/120261#note-8
> Auto-detect `WORKER_HOSTNAME` on worker startup if not set explicitly

- etc/openqa/openqa.ini
Same as for assets there had been problems reported for other queries
and webUI views, e.g. test suites where the limit of 500 was just way
too strict. And without the users being able to select more entries to
show easily we should be more conservative regarding limits. Limits will
still have an effect although potentially systems can be loaded a bit
more with higher limits.
I am selecting reasonable higher values for default and max limits based
on my experiences how heavy the individual data sources are.
Related progress issue: https://progress.opensuse.org/issues/120315
> Bump query limits to higher limits to fix users unable to get results

- tools/static_check_containers
Set the `HOME` variable explicitly as the current container image otherwise fails with:
```
hadolint: getXdgDirectory:getHomeDirectory:getUserEntryForID: does not exist (No such file or directory)
make: *** [Makefile:309: test-check-containers] Error 1
Error: Process completed with exit code 2.
```
> Fix hadolint check

- lib/OpenQA/WebAPI/Controller/Step.pm
* Use signatures in WebAPI::Controller::Step
* Use signatures in WebAPI::Controller::Running
* Use signatures in WebAPI::Controller::Main
* Use signatures in WebAPI::Controller::File
* Use signatures in WebAPI::Controller::Developer
* Use signatures in WebAPI::Controller::ApiKey
After:
* https://github.com/os-autoinst/openQA/pull/4882
> Use signatures in WebAPI::Controller::Step

- tools/static_check_containers
This is required to run hadolint on systems with SELinux enabled
> Relabel the shared volumes for hadolint

- lib/OpenQA/CacheService.pm
* Set SQLite busy timeout before invoking first query/pragma so the extended busy timeout we already apply counts for the first query/pargma as well. This should avoid the `database is locked` error we see on PowerPC workers when setting the journal mode.
* Tested locally by provoking a timeout via `$db->begin('exclusive')` and then never releasing the lock. Before this change `database is locked` is logged rather quickly on another connection attempt. With this change the error occurs only after 10 minutes. The database is still using the `DELETE` journaling mode.
* See https://progress.opensuse.org/issues/120744
> Avoid `database is locked` errors if SQLite writes are slow

- lib/OpenQA/CacheService.pm
When working on https://progress.opensuse.org/issues/120744 I first thought I need to implement a retry so I did this refactoring to avoid the startup function from becoming to big. I suppose it is still nice to split this already long function into smaller ones. This PR incorporates https://github.com/os-autoinst/openQA/pull/4931.
> Extract opening/configuring cache service SQLite db into functions

- dist/rpm/openQA.spec
- docs/Pitfalls.asciidoc
- lib/OpenQA/Worker/Job.pm
- profiles/apparmor.d/usr.share.openqa.script.worker
- t/24-worker-jobs.t
pngquant is significantly faster than optipng. On powerful server it
probably doesn't matter much, but on Raspberry Pi, optipng is unusably
slow (it takes over 15s to process one image). pngquant is significantly
faster - about 1s on the same image.
> Prefer 'pngquant' over 'optipng' if it is installed

- lib/OpenQA/CLI/api.pm
- lib/OpenQA/Command.pm
- t/43-cli-api.t
I've been thinking about how to use pagination from `openqa-cli`, and a flag that prints all the links to STDERR seems like a reasonable first step.
It's a very unobtrusive change, since you have to opt-in with the `--links` flag. The green highlighting helps to separate it from the normal response body on STDOUT.
> Add --links option to openqa-cli for pagination

- dist/rpm/openQA.spec
So far openQA-single-instance pulls in openQA itself only indirectly via openQA-local-db package that doesn't require a specific openQA version. However, for openQA-single-instance it makes sense to require a specific version of openQA and the worker to avoid pulling in older versions from other repositories (which is likely not expected/wanted by users).
See https://github.com/os-autoinst/openQA/pull/4901 and https://progress.opensuse.org/issues/115784 for additional context.
> Ensure openQA-single-instance pulls in same version of openQA

- lib/OpenQA/Worker.pm
- lib/OpenQA/Worker/Settings.pm
- t/24-worker-overall.t
* Auto-detect worker address as part of availability checks to automatically re-check the FQDN and avoid running jobs without worker address
* See https://progress.opensuse.org/issues/120261
---
Still a draft because tests are missing. I'd just like to show how my idea from the mentioned issue would look like.
Note that for determining the IP address as a fallback there wouldn't be a core Perl module (at least I haven't found one). Supposedly https://metacpan.org/pod/Net::Address::IP::Local would be the best module for that.
> Avoid running jobs with undetermined worker address
