os-autoinst/openQA

lib/OpenQA/Client/Handler.pm, lib/OpenQA/Utils.pm, lib/OpenQA/Worker/Settings.pm, t/24-worker-overall.t, t/24-worker-settings.t
* Allow overriding WORKER_HOSTNAME as before (in which case the
worker never considers itself broken, even if the override is
no valid FQDN/IP)
* Assign "localhost" as fallback for local worker setups (where
all HOSTs are local web UI instances) not requiring an FQDN
* Consider worker still broken for remote worker setups unless
an FQDN could be detected or WORKER_HOSTNAME has been
specified explicitly
* See https://progress.opensuse.org/issues/121567
and https://progress.opensuse.org/issues/120261#note-42
=> Support use-case of "local" worker when detecting worker address

lib/OpenQA/Schema/Result/Jobs.pm
We are dealing with an update order deadlock here. Imagine two processes are running an update query for three rows against the same table. Process 1 updates the rows in order A, B, C. Process 2 updates them in order C, B, A. Now process 1 holds the lock on A and is waiting for the lock on C, while process 2 holds the lock on C and is waiting for A. We have a deadlock that PostgreSQL cannot resolve on its own.
This is a similar case, the random order just happens to come from the Perl side in form of a `values %assets`. To fix that we ensure a consistent order based on the asset name. Additionally we also defensively use a `SELECT...FOR UPDATE` before the `UPDATE`.
Progress: https://progress.opensuse.org/issues/120891
=> Protect second asset size update from possible deadlocks

docs/Contributing.asciidoc
In the contribution documentation running tests is mentioned before the information about dependencies is written.
Since running integration tests requires these dependencies as well it might be preferred to have that information earlier.
=> Docs: Inform about dependencies before information about running tests

t/api/14-plugin_obs_rsync_async.t, t/ui/13-admin.t
This PR would increase the timeout of tests:
- api/14-plugin_obs_rsync_async.t
- ui/13-admin.t
They failed on KVM machine with 14 cores host-passthrough and 16 GiB RAM otherwise.
=> Increase timeouts of tests api/14 and ui/13

lib/OpenQA/Schema/Result/JobModules.pm
A not readable test module result file is handled and gracefully
returned to the web UI and no error in log. The handling should be
atomic, not "check if readable and then read". Instead of trying to read
and then fail we should handle the read attempt as we handle the
exception in line 96 and return {} in case of error.
Related progress issue: https://progress.opensuse.org/issues/121444
=> Fix race-condition reading job module details files

lib/OpenQA/Scheduler/Model/Jobs.pm
* Using a separate transaction per job is likely good enough and has the advantage that other components see changes faster and there's less potential for deadlocks
* Related issue: https://progress.opensuse.org/issues/121768
=> Split big transaction in stale job detection

container/devel:openQA:ci/base/Dockerfile
Without it we're never actually running unit tests for this which also correctly shows up as uncovered code in CI.
See: https://progress.opensuse.org/issues/121357
=> container: Install tessseract so we can test OCR

lib/OpenQA/Schema/Result/Jobs.pm, t/api/04-jobs.t
* Remove `$asset->ensure_size;` on job creation; this breaks the check for assets that's done when restarting jobs, e.g. `t/15-assets.t` fails
* Determine size of assets when restarting jobs as needed so it still works despite the previous point
* See https://progress.opensuse.org/issues/120891
=> Avoid deadlock when updating asset size during job creation

lib/OpenQA/Scheduler/Model/Jobs.pm, lib/OpenQA/Schema/Result/Jobs.pm, t/10-jobs.t
* Set jobs to RUNNING/UPLOADING only if they're still ASSIGNED/SETUP (and not when they have been set back to SCHEDULED)
* Set jobs back to SCHEDULED only if they were still just ASSIGNED (and haven't been entering any subsequent states meanwhile)
* Prevent stale job detection from setting jobs back to SCHEDULED when the worker meanwhile showed up
* See https://progress.opensuse.org/issues/121768
=> Avoid jobs from being stuck in state "running"

codecov.yml
With path specific coverage targets we can introduce the hard
requirement for 100% coverage within the paths where it is feasible. It
makes sense to have 100% statement coverage within test code itself to
prevent relying on tests that are actually not running.
Previously tried in
* https://github.com/os-autoinst/openQA/pull/3938
In os-autoinst we already added according changes in
* https://github.com/os-autoinst/os-autoinst/pull/2016
See https://docs.codecov.com/docs/commit-status#branches
=> codecov.yml: Introduce specific coverage thresholds

systemd/openqa-webui.service
If this unit gets activated, the units listed in Requires= will be activated as well. If one of the other units fails to activate, and an ordering dependency After= on the failing unit is set, this unit will not be started. Besides, with or without specifying After=, this unit will be stopped (or restarted) if one of the other units is explicitly stopped (or restarted).
Reference: https://progress.opensuse.org/issues/122578
=> Add postgresql service to requirements

Makefile
Manual testing has shown the test to be very stable now. So we can try running it without retry in CI. That should give us enough data points to conclude if the sporadic failures have really been resolved.
Progress: https://progress.opensuse.org/issues/120226
=> Try running the full-stack test without retry

systemd/openqa-webui.service
Reverts os-autoinst/openQA#4971 as that would mean any openQA instance using a remote database would fail to start requiring a local postgresql.service running as well.
=> Revert "Add postgresql service to requirements"

t/ui/15-comments.t
It seems there's a race condition where the comment form element is not ready in some cases. I could replicate the issue in about 2 of 300 test runs. After adding the `wait_for_element` call i've had the test pass about 600 times without any issues. So this might be a good enough fix.
Progress: https://progress.opensuse.org/issues/121042
=> Avoid race condition by waiting for the #text element

lib/OpenQA/Schema/ResultSet/Jobs.pm, lib/OpenQA/WebAPI/Controller/API/V1/Job.pm, t/api/04-jobs.t
Cleaned up version of #4964.
Progress: https://progress.opensuse.org/issues/121102
=> Add pagination for GET /api/v1/jobs

lib/OpenQA/CacheService/Client.pm, lib/OpenQA/CacheService/Controller/API.pm, lib/OpenQA/CacheService/Response/Status.pm, lib/OpenQA/CacheService/Task/Asset.pm, lib/OpenQA/Worker/Engines/isotovideo.pm, t/24-worker-engine.t, t/25-cache-service.t, t/25-cache.t
So far the cache service doesn't treat download errors as such when the
asset is still present locally. However, that's not a good idea because the
local version might be outdated and problems on the server-side might only
surface later (on the next cache cleanup) which makes the investigation
more difficult (see https://progress.opensuse.org/issues/122776).
This change tracks whether the download has actually been succeeded instead
of only checking whether the cached asset exists locally.
Note assets that are locally cached are *not* re-downloaded unless the
asset has changed on the server. However, to check whether the asset has
changed on the server an HTTP request is done that might fail. With this
change this error case is now not ignored anymore.
---
~~Still a draft as tests maybe …
=> Fix asset cache error handling to avoid proceeding in case of failures

dbicdh/PostgreSQL/deploy/98/001-auto-__VERSION.sql, dbicdh/PostgreSQL/deploy/98/001-auto.sql, dbicdh/PostgreSQL/upgrade/97-98/001-auto.sql, dbicdh/_source/deploy/98/001-auto-__VERSION.yml, dbicdh/_source/deploy/98/001-auto.yml, lib/OpenQA/Schema.pm, lib/OpenQA/Schema/Result/JobLocks.pm
The `owner` column of the `job_locks` table is referencing a job ID so it should be bigint as we use that type for job IDs.
The `job_locks` table is very small (e.g. less than 50 rows on OSD) so this migration should go very fast.
=> Change type of `owner` column to bigint in consistency with jobs table

dist/rpm/openQA.spec
This should fix the build problem mentioned in #4976 
```
[   59s] ERROR: link target doesn't exist (neither in build root nor in installed system):
[   59s]   /usr/lib/systemd/system/openqa-gru.service.requires/postgresql.service -> /usr/lib/systemd/system/postgresql.service
[   59s] Add the package providing the target to BuildRequires and Requires
```
Reference: https://progress.opensuse.org/issues/122578
=> Fix build by providing postgresql during build

t/ui/15-comments.t
Similar to the previous race condition from #4978. Found by Marius this time, but i've been unable to replicate it locally. Applying the same `wait_for_element` to ensure that the comment field is visible should resolve this as well though. The test code is almost exactly the same.
Progress: https://progress.opensuse.org/issues/121042
=> Avoid another race condition by waiting for the #text element

lib/OpenQA/WebAPI.pm, lib/OpenQA/WebAPI/Controller/File.pm, t/ui/07-file.t
This gets rid of:
```
[2023-01-21T22:04:08.897649Z] [error] [bXpoFGyR3PEg] DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::Pg::st execute failed: ERROR:  invalid input syntax for type bigint: "root-console-20200501"
CONTEXT:  unnamed portal parameter $1 = '...' [for Statement "SELECT me.id, me.dir_id, me.filename, me.last_seen_time, me.last_seen_module_id, me.last_matched_time, me.last_matched_module_id, me.last_updated, me.file_present, me.tags, me.t_created, me.t_updated FROM needles me WHERE ( me.id = ? )" with ParamValues: 1='root-console-20200501'] at /usr/share/openqa/script/../lib/OpenQA/WebAPI/Controller/File.pm line 65
```
Which can happen when someone accidentally requests `GET /needles/root-console-20200501/image`.
Progress: …
=> Fix missing input validation for needle API endpoints

lib/OpenQA/Setup.pm
This fixes the error
```
Too few arguments for subroutine 'OpenQA::Setup::load_plugins' at /usr/share/openqa/script/../lib/OpenQA/WebAPI.pm line 30.
```
when invoking e.g.
```
/usr/share/openqa/script/openqa minion job --help
```
=> Fix error when displaying help for minion sub command

profiles/apparmor.d/usr.share.openqa.script.openqa
* Set working directory explicitly before invoking archive extraction via `Archive::Extract`
* Otherwise `cwd` returns an empty string in the case the working directory doesn't exist anymore which is then used by `Archive::Extract` which then runs into an error due to it.
* Note that the error would not cause an actual problem as it is ignored anyways; however the log message due to it is not nice and avoided by this change.
* See https://progress.opensuse.org/issues/123649
---
Still a draft as I'll have to check whether it actually works on o3. (I've just noticed that my reproducer wouldn't reproduce the issue anymore anyways as the download is already 404.)
=> Avoid errors about changing the working directory after asset extraction

tools/ci/build_or_install_from_cache.sh
The cache is tied to the checksums and may not be generated in time when there is a temporary outage or fewer PRs have been prepared.
See: https://progress.opensuse.org/issues/123867
=> ci: Point out how to fix an empty cache

assets/assetpack.def
* Revert side-effect of 5856b50143038fb121b90b68557092c721167420
* Include CSS for multi-level dropdown extension after Bootstrap itself; otherwise Bootstrap's default won't be overridden by this Bootstrap extension's CSS which is supposedly intended
* See https://progress.opensuse.org/issues/124143
=> Restore font color of main menu actions

lib/OpenQA/WebAPI/Controller/API/V1/Job.pm, t/api/04-jobs.t
See https://progress.opensuse.org/issues/124230
=> Fix off-by-one error when limiting jobs API route using `latest=1`

lib/OpenQA/Markdown.pm, lib/OpenQA/Utils.pm, t/16-markdown.t
So one does not need to add a bugref just for the sake of having a
clickable link. This is especially useful as having a label and a bugref
in one comment has caveats. In particular, a `force_result` will not be
evaluated if the comment is carried over and the carry over itself prevents
hook scripts from running.
With this, the change https://github.com/os-autoinst/scripts/pull/155 could
be reverted.
Related ticket/note: https://progress.opensuse.org/issues/124029#note-4
---
=> Render bugrefs as clickable links within labels

dist/rpm/openQA.spec
As a step one, add version to openQA requirements for openQA-local-db as that package is to be picked and installed by the user.
Reference: https://progress.opensuse.org/issues/124316
=> Ensure consistent openQA version when installing openQA-local-db

assets/javascripts/test_result.js
Don't remove the first item anymore.
Previously the string returned from git_log_diff contained a preceding linebreak. But that was removed in 6b31bdb8acd007de140fe4b7018817e7092174e3
Issue: https://progress.opensuse.org/issues/124476
=> Fix investigation git log

dbicdh/PostgreSQL/deploy/99/001-auto-__VERSION.sql, dbicdh/PostgreSQL/deploy/99/001-auto.sql, dbicdh/PostgreSQL/upgrade/98-99/001-auto.sql, dbicdh/_source/deploy/99/001-auto-__VERSION.yml, dbicdh/_source/deploy/99/001-auto.yml, lib/OpenQA/Schema.pm, lib/OpenQA/Schema/Result/Jobs.pm
The column "backend_info" seems to have been prepared for use by
backends but I also could not find any reference in os-autoinst so this
commit will remove the table in the database, will remove references and
migrate databases by simply removing the column without replacement.
=> Remove unused 'backend_info'

lib/OpenQA/WebAPI.pm
A retry feature has been added upstream to
Mojolicious::Plugin::AssetPack in the 2.14 release. See https://github.com/mojolicious/mojo-assetpack/pull/148 for more. The feature will have to remain optional until openQA can safely depend on 2.14, which is currently unavailable for Tumbleweed aarch64.
Progress: https://progress.opensuse.org/issues/122440
=> Retry asset downloads automatically

dist/rpm/openQA.spec
See https://progress.opensuse.org/issues/124670
=> Enable build for PowerPC after openQA packages are no longer noarch

lib/OpenQA/WebAPI.pm
Reverts os-autoinst/openQA#5008 in case we need it, see https://progress.opensuse.org/issues/124739
=> Revert "Retry asset downloads automatically"

lib/OpenQA/WebAPI.pm, tools/generate-packed-assets
Before it would return this:
% grep 'AssetPack' lib/OpenQA/WebAPI.pm | awk -F '[()]' '{print $3}'
Sass Css JavaScript Fetch Combine
if $Mojolicious::Plugin::AssetPack::VERSION > 2.13;
Now the regex is more specific and also restricted to one line
Issue: https://progress.opensuse.org/issues/124739
Also reverts #5011
=> Fix regex to get AssetPack plugins

.obs/workflows.yml
I was a bit hasty and already removed the Leap 15.3 project from devel:openQA so likely we need this change anyway.
=> OBS: Do not test builds on EOL Leap 15.3

script/openqa-clone-custom-git-refspec
- Note the format for NEEDLES_DIR
- Mention GITHUB_TOKEN in the usage
=> Mention examples for NEEDLES_DIR and GITHUB_TOKEN

docs/WritingTests.asciidoc, lib/OpenQA/JobSettings.pm, t/40-job_settings.t
Sometimes an expression surrounded by `%`-signs should be preserved and not be substituted, e.g. `NEEDLES_DIR=%CASEDIR%/foo` to express a `NEEDLES_DIR` relative to `CASEDIR`. This change enables the use of `NEEDLES_DIR=%%CASEDIR%%/foo` which will always be substituted to `NEEDLES_DIR=%CASEDIR%/foo` (so no real substitution happens, only the outermost pair of `%`-signs is removed).
The documentation for this specific use has also been extended (including how to pass `%`-signs via `curl`).
Of course this could be useful in other cases as well. Note that this particular use case is from day 4 of Oliver's hackweek (see https://hackweek.opensuse.org/22/projects/trigger-actual-openqa-tests-in-pull-requests).
Related ticket: https://progress.opensuse.org/issues/124502
=> Allow escaping percentage signs in job settings to avoid substitution

lib/OpenQA/Schema/Result/Jobs.pm
Job restarts via `RETRY` should skip jobs with OK_RESULTS and also USER_CANCELLED jobs. This means that having retry for complement of `is_ok` is not enough. Introduce `is_ok_to_retry` check to deal with that.
Reference: https://progress.opensuse.org/issues/124961
=> Do not restart user-cancelled job with RETRY

lib/OpenQA/Worker/Job.pm
The test covering this condition (`t/33-developer_mode.t`), specifically checks for two possible results, `user_cancelled` and `passed`. Making this an intentional race condition. So, for now, it seems like the best solution to mark the condition as uncoverable to prevent flaky code coverage data.
Progress: https://progress.opensuse.org/issues/124484
=> Mark WORKER_COMMAND_CANCEL condition as uncoverable

t/10-jobs.t
Test the functionality added in #5021.
=> Extend test for RETRY and user-cancelled jobs

lib/OpenQA/Script/CloneJob.pm, t/35-script_clone_job.t
The documentation says that `--skip-deps` and `--skip-chained-deps` only affects parent jobs. But in the code both flags were applied unconditionally to all dependencies, no matter if `--clone-children` was present as well.
With this patch applied you can use `--skip-deps --clone-children` to clone a job with its children, but without parents.
The documentation was added 7 years ago, together with the dependency cloning feature, which at the time only allowed parents to be cloned. 4 years later another feature was introduced that allows for child jobs to be cloned as well. Here it appears the old documentation was missed, and has been incorrect since then.
Clone dependencies: https://github.com/os-autoinst/openQA/commit/39cbc4051d1eb0fcaeed7339af68475f7619ec30
Clone children: …
=> Make --skip-deps and --skip-chained-deps work as described in the docs

.circleci/config.yml
To prevent empty cache errors that we get from time to time.
Issue: https://progress.opensuse.org/issues/123867
I ran the job on my fork, looked good
=> Run cache.fullstack job also in nightly job

lib/OpenQA/LiveHandler.pm, lib/OpenQA/Schema/Result/Jobs.pm, lib/OpenQA/Shared/Plugin/Gru.pm, lib/OpenQA/Task/Job/FinalizeResults.pm, lib/OpenQA/Task/Job/Restart.pm, t/04-scheduler.t, t/10-jobs-results.t, t/10-jobs.t, t/api/04-jobs.t, t/ui/18-tests-details.t
The web UI automatically restarts a job when it is set to done under certain conditions. So far errors when restarting are ignored. This change moves the restarting into a Minion job. An error will now lead to failing Minion jobs with the error message assigned as result. This should allow us to investigate https://progress.opensuse.org/issues/125276. Minion jobs are also retried a few times before ending up failed which should make it a bit more robust as well.
=> Improve error handling when automatically restarting a job

lib/OpenQA/Task/Job/Restart.pm
Treat also the error "… already has clone …" as non-fatal in the context of automatic restarts. So far only the slightly different error message (when the immediately specified job has already been cloned) was accounted for.
Related ticket: https://progress.opensuse.org/issues/125276
=> Fix `restart_job` jobs failing with `already has clone`

docs/UsersGuide.asciidoc, lib/OpenQA/Jobs/Constants.pm, lib/OpenQA/Schema/Result/Jobs.pm, lib/OpenQA/Schema/Result/ScheduledProducts.pm, lib/OpenQA/Utils.pm, public/schema/JobScenarios-01.yaml, t/api/02-iso-download.t, t/api/02-iso-yaml.t, t/api/02-iso.t, t/data/09-schedule_from_file.yaml, t/data/09-schedule_from_file_incomplete.yaml, t/data/09-schedule_from_file_minimal.yaml, t/lib/OpenQA/Test/Utils.pm
* Revive and rebase #3848 for https://progress.opensuse.org/issues/92311
* Improve tests
---
Open points for discussion:
1. Where should the YAML file come from? The approach from #3848 only allows for local file system paths. Supposedly we want to allow an HTTP-URL here as well (e.g. pointing to some place on GitHub/GitLab/…).
2. It is not to late to tweak the naming. I think `SCHEDULE_FROM_YAML_FILE` is a bad choice as it can be easily confused with `YAML_SCHEDULE`. What about `SCENARIO_DEFINITIONS_YAML_FILE`? After all, that's what this YAML file is going to contain. I don't think we should overuse the work "schedule" because it tends to become more meaningless the more we use it.
3. The YAML file clearly lacks a version field. To be able to extend it in the future, I suggest to add a …
=> Allow loading scenario definitions for scheduling an ISO/product from templates from YAML file

lib/OpenQA/WebAPI/Auth/OpenID.pm, t/03-auth.t
* Add context when logging OpenID-related errors
* Allow to easily ignore OpenID-related errors in tools like logwarn
* Related ticket: https://progress.opensuse.org/issues/125459
=> Make it easier to distinguish OpenID-related errors

lib/OpenQA/Schema/ResultSet/Jobs.pm
Error message:
DBIx::Class::Storage::DBI::_dbh_execute():
DBI Exception: DBD::Pg::st execute failed: ERROR:  column reference "t_created" is ambiguous
=> Make t_created unambiguous in SQL

lib/OpenQA/CLI/api.pm, lib/OpenQA/CLI/schedule.pm, lib/OpenQA/Command.pm, t/43-cli-schedule.t
Related ticket: https://progress.opensuse.org/issues/125720
---
Example invocation:
```
script/openqa-cli schedule --apikey … --apisecret … --host … DISTRI=example VERSION=0 FLAVOR=DVD ARCH=x86_64 TEST=simple_boot FOO=bar --param-file SCENARIO_DEFINITIONS_YAML=/hdd/openqa-devel/openqa/share/tests/example/scenaio-definitions.yaml -r
```
So one can use CLI-flags similar to `openqa-cli api`.
Still a draft because unit tests are missing and the error handling needs to be improved (it should retry like `openqa-cli api`).
=> Allow scheduling and monitoring a product via `openqa-cli`

container/client/Dockerfile
* Provide container with `openqa-cli` and Git pre-installed to utilize 6656bb7275c4e26c0b01afae071d310bb76242bd from CI runs
* Related ticket: https://progress.opensuse.org/issues/125723
---
When this PR has been merged, I'll change the OBS package to pull the Dockerfile from here.
=> Provide container image to trigger/monitor jobs as CI

lib/OpenQA/Shared/Controller/Auth.pm
By invoking `openqa-cli api --host http://myhost/foo/bar --apibase api/v1 …` one can do a request to an openQA instance that has been made available under the nested path `foo/bar` on the specified host using the Mojolicous plugin `RequestBase`.
The client will then compute the hmac for the full path, including the "base"- prefix (e.g. `foo/bar/api/v1/isos`). The web UI will however not take the "base-prefix into account (and compute the hmac just for e.g. `api/v1/isos`). With this change, the web UI will also take the "base"-prefix into account when a `base_url` has been specified (which is not the case for any of our production instances where nothing changes).
=> Make key-auth work for openQA instances under nested path

lib/OpenQA/WebAPI/Controller/Test.pm, t/ui/18-tests-details.t
See https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-anonymized-urls
```
$ curl -sI "https://circleci.com/gh/os-autoinst/openQA/tree/master.svg?style=svg" | grep cache-control
cache-control: max-age=0, no-cache
```
=> Prevent github from caching badges too long

lib/OpenQA/Script/CloneJob.pm, t/35-script_clone_job.t
Previously the clone job code only assigned dependencies when parents were cloned in addition to children. This patch changes the dependency assignment to work in both directions. The code also gets a little easier to follow by moving the `skip-chained-deps`/`skip-deps` handling into the main loop.
Progress: https://progress.opensuse.org/issues/124493
=> Assign dependencies when cloning jobs with children but without parents

lib/OpenQA/CLI/schedule.pm, lib/OpenQA/Script/CloneJob.pm, t/35-script_clone_job.t, t/43-cli-schedule.t
* This makes it more convenient to view the jobs manually in the web UI.
* Related ticket: https://progress.opensuse.org/issues/125723
=> Render web UI URLs for jobs created via `openqa-cli schedule`

assets/javascripts/running.js
If the to be appended part of the received log content does not contain a newline, the code for discarding the first probably partial line can get stuck in an endless loop. This change fixes the loop condition to avoid this.
=> Avoid live view getting stuck in a certain case

lib/OpenQA/CLI/api.pm, lib/OpenQA/CLI/archive.pm, lib/OpenQA/CLI/schedule.pm, lib/OpenQA/Command.pm, t/43-cli-api.t
As a result of our adventure today trying to track down the service unintentionally running a DoS attack against OSD. We should do this for all openQA clients to make them easy to identify in logs.
=> Make it easier to identify openqa-cli in logs

lib/OpenQA/Schema/Result/Jobs.pm, t/10-jobs.t
Issue: https://progress.opensuse.org/issues/126665
Without this, cancelled jobs would not get their final status update and upload of details-*.json, so the uploaded screenshots could not be viewed.
=> Ensure final status update for cancelled jobs

assets/javascripts/comments.js, t/lib/OpenQA/SeleniumTest.pm, t/ui/15-comments.t
So we get e.g. "force_result only allowed on finished jobs" instead of just "BadRequest".
Related ticket: https://progress.opensuse.org/issues/127280
=> Show error message from server when commenting fails

lib/OpenQA/CacheService/Command/run.pm, lib/OpenQA/CacheService/Controller/Influxdb.pm, lib/OpenQA/CacheService/Model/Cache.pm, t/25-cache-service.t
* Return the download count in the same way as we currently the download rate (via the Minion's InfluxDB route)
* Increment the download count when starting one and decrement it when it finished (regardless of the result)
* Reset the download count to zero when starting `openqa-workercache run …` be start counting from scratch after an unclean exit. (still WIP)
* Related ticket: https://progress.opensuse.org/issues/127097
=> Track download count to supress alert if no downloads ongoing

container/webui/Dockerfile, container/webui/run_openqa.sh, docs/Installing.asciidoc
* Configure a default certificate in the container startup
script (as a fallback)
* Start and configure the database inside the container unless
the database has been configured by the user manually
* Improve documentation
* See https://progress.opensuse.org/issues/127091
* See https://progress.opensuse.org/issues/127139
=> Improve out-of-the-box experience when invoking web UI container

lib/OpenQA/Script/CloneJob.pm
This change makes `_GROUP` and `_GROUP_ID` "global" settings so one can clone a set of jobs into another group or no group via, e.g. `openqa-clone-job $some_url _GROUP=0`. Otherwise one needed to take dependencies into account and possibly specify `--parental-inheritance` (which would then apply all settings to the parent which might not be wanted as well).
The downside is that leaving the parent jobs that are cloned as well in their job groups is not possible anymore. However, I don't think that this is a realy use case of our users anyways.
=> openqa-clone-job: Apply group settings to all cloned jobs

lib/OpenQA/Script/CloneJobSUSE.pm, t/35-script_clone_job_suse.t
The function `detect_maintenance_update` sometimes prevents tests from being cloned. Now if the variable `SKIP_MAINTENANCE_UPDATES` is provided this check is skipped.
Test passed OK:
```
test -d /dev/shm/tpg && (pg_ctl -D /dev/shm/tpg -s status >&/dev/null || pg_ctl -D /dev/shm/tpg -s start) || ./t/test_postgresql /dev/shm/tpg
2023-04-19 09:12:15.789 CEST   [10380]LOG:  redirecting log output to logging collector process
2023-04-19 09:12:15.789 CEST   [10380]HINT:  Future log output will appear in directory "log".
make test-unit-and-integration TEST_PG="DBI:Pg:dbname=openqa_test;host=/dev/shm/tpg"
make[1]: Entering directory '/home/pablo.herranz/GitHub/openQA'
export GLOBIGNORE="";\
export DEVEL_COVER_DB_FORMAT=JSON;\
export PERL5OPT=" -It/lib -I/home/pablo.herranz/GitHub/openQA/t/lib …
```
=> Add conditional check to skip maint. updates verification

assets/stylesheets/openqa_theme.scss
This commit aims to enhance the contrast of the progress bar used to display the number of failures. The previous implementation had low contrast, making it difficult to discern the actual progress. The updated design uses a more prominent color scheme, improving visibility and making it easier to understand the number of failures at a glance. This change improves the overall user experience and ensures that the progress bar is more accessible to all users.
=> Improve contrast of progress bar showing number of failures

lib/OpenQA/WebAPI.pm, lib/OpenQA/WebAPI/Controller/Main.pm, t/22-dashboard.t
Related progress issue: https://progress.opensuse.org/issues/127052
=> Add minimalistic "health" check route

lib/OpenQA/Utils.pm
These log lines can take quite some room in our log files and they serve no purpose unless one really wanted develop this
particular feature. However, then it makes more sense to add debug-logging as needed. This feature can be developed
conveniently by running unit tests so I don't think we ever need this debug printing outside of a local development session.
=> Remove mostly useless logging for tag detection

lib/OpenQA/Schema/Result/Jobs.pm, lib/OpenQA/Worker/Job.pm
Use the constant `WORKER_COMMAND_ABORT` so places where we deal with that worker command are easier to find.
Related ticket: https://progress.opensuse.org/issues/128267
=> Use constant `WORKER_COMMAND_ABORT`

lib/OpenQA/Schema/Result/Jobs.pm
`virtio_consoleN.log` logs (e.g. `virtio_console1.log`) are uploaded as `serial_terminalN.txt` (e.g. `serial_terminal1.txt`). Due keeping old name they weren't visible in "Logs & Assets" section.
Fixes: b24718521 ("Worker/Job.pm: Rename all .log to *.txt")
Verification run (wicked):
* http://quasar.suse.cz/tests/2666#downloads (link to http://quasar.suse.cz/tests/2666/logfile?filename=serial_terminal_user.txt)
=> Result/Jobs.pm: Update serial console name

assets/stylesheets/dashboard.scss
This commit addresses the issue of improvement on the contrast of progress bar text, the change in contrast ensured easy readability by the users especially those with visual impairment. The Contrast of the progress bar was changed from #CACACA to #000000 to ensure better visibility on the bar and accessibility for the users.
=> Improve contrast of Progress bar text

lib/OpenQA/Schema/Result/Jobs.pm, t/05-scheduler-restart-and-duplicate.t
This is a follow-up to @martchus #4498. The intent of that PR, as the commit message says, is to "Restart failed chained parents "up the chain"". However, it actually does more than this: it also restarts chained parents that are queued or running, because they also do not have "OK" results.
In a way we cannot know whether restarting a chained parent that is still running is the right thing to do, but doing so definitely causes problems in one real-world case:
https://progress.opensuse.org/projects/openqav3/activity?from=2022-12-19 and from the examples backing the original change here, it seems we only really intended to add the restart behaviour when the parent test definitely failed, not when its result was not yet decided. So on the principle of making minimal changes to the previous …
=> Don't restart scheduled or running chained parents

lib/OpenQA/WebAPI/Controller/API/V1/Table.pm, t/api/01-workers.t, t/api/02-assets.t, t/api/04-jobs.t, t/api/05-machines.t, t/api/06-products.t, t/api/07-testsuites.t, t/api/11-bugs.t
They all share the same controller and action.
Progress: https://progress.opensuse.org/issues/121105
=> Add pagination for /api/v1/test_suites, /api/v1/machines, and /api/v1/products

lib/OpenQA/Parser.pm, lib/OpenQA/Parser/Result.pm, lib/OpenQA/Parser/Results.pm
Serialize the test results in network order to be compatible with the different type of endianness (big-endian and little-endian)
See: https://github.com/os-autoinst/os-autoinst/issues/2312
=> Make serialization of test results portable

Makefile
Same as when generating reports for generating codecov reports we should
specify the variables which help us with local calls in case of "Sereal"
packages being available locally to prevent errors.
=> Makefile: Fix manual calls of codecov report

container/worker/Dockerfile
Hello,
I realize the worker container can't be all things to everyone... but it would be handy for GNOME's OpenQA setup if it contained `xz` so we can uncompress disk images on the worker. The increase in container image size is 319KB, which is not very noticeable in a 1.44GB container image :-)
=> Add `xz` to worker container

lib/OpenQA/Schema/Result/Jobs.pm, t/04-scheduler.t
* Rewrite code to no longer use `next` in `catch` block (which
does not work because this block is actually a nested function)
* Use raw SQL query to simplify code
* A simple insert with `ON CONFLICT DO NOTHING` should be
sufficient (instead of using a transaction)
* Using the same query for applying the network to the whole
job cluster should avoid running into
"duplicate key value violates unique constraint" (see
https://progress.opensuse.org/issues/128267#note-13)
* Die in case of a fatal error (instead of possibly provoking the
error again and again in an endless loop)
* Improve log messages to always include the relevant job ID
* Add explicit unit tests
=> Fix several issues with `allocate_network`

assets/stylesheets/dashboard.scss, assets/stylesheets/openqa_theme.scss
Commit c3af6a39f2e72559c045666d1bafd749001de538 increased the contrast of progress bar segments showing the number of failures by making the color we generally use for failures darker. However, that decreased the difference between the color of failures and incompletes which makes them harder to distinguish. So this commit reverts this original change. To still have a good contrast in the progress bar segment the text color within the progress bar is set to black. This looks good in bright and dark mode (the mode actually makes no difference for the progress bars).
=> Improve contrast between failed and incomplete color

lib/OpenQA/Script/CloneJob.pm, t/35-script_clone_job.t, t/40-openqa-clone-job.t
If one messes up the commandline options, e.g.
--within-instance --json-output http://...
then the error message about the missing credentials can be confusing.
Printing out the host (or in this case the misplaced option) will make it clear what's wrong.
=> Output host of missing api credentials

script/openqa-webui-daemon, script/openqa-workercache-daemon
We have some API endpoints that can run in a blocking manner for 10+ minutes, such as `/api/v1/jobs/:id/set_done`. Which exceeds the 400 second heartbeat timeout we currently use.
Fortunately this timeout only exists so a worker cannot be blocked indefinitely with something like an infinite loop. So increasing it a bit more should not cause any noticeable side effects.
Long term we should consider moving such slow code into Minion background jobs though.
Progress: https://progress.opensuse.org/issues/128345
=> Increase heartbeat timeout to 15 minutes

assets/javascripts/test_result.js
The output can contain things like:
No needle changes recorded, test regression due to needles unlikely
fatal: Invalid revision range abcdef..abc123
If it doesn't look like a git log, just show the text itself
Issue: https://progress.opensuse.org/issues/128588
=> Improve non-matching log output in investigation tab

docs/WritingTests.asciidoc, lib/OpenQA/Schema/Result/Jobs.pm, lib/OpenQA/Schema/Result/ScheduledProducts.pm, lib/OpenQA/Setup.pm, lib/OpenQA/Shared/Controller/Auth.pm, lib/OpenQA/Task/Iso/Schedule.pm, lib/OpenQA/Utils.pm, lib/OpenQA/VcsProvider.pm, lib/OpenQA/WebAPI.pm, lib/OpenQA/WebAPI/Controller/API/V1/Webhook.pm, t/16-utils-vcs-provider.t, t/api/16-webhooks.t, t/config.t, t/data/example-webhook-payload.json
* Sequence of the whole workflow
1. The route `/api/v1/webhooks/product` is called by GitHub when
a PR has been created.
1. openQA creates a scheduled product as if
`/api/v1/isos` was called and adds additional meta-
data to be able to report the result back to GitHub.
It also adds additional parameters like `_GROUP=0`.
2. openQA reports a "pending" status back to GitHub so a
CI check shows up in the PR.
2. openQA downloads the YAML file with the scenario
definitions from GitHub. It downloads the version from
the PR.
3. openQA creates jobs for the scheduled product as usual.
4. Once a scheduled job has completed the status of the
whole scheduled product is checked. Eventually success or
failure is reported back to GitHub.
* Related ticket: https://progress.opensuse.org/issues/127949
=> Add route to schedule a product via a webhook

t/ui/15-comments.t
This will hopefully fix https://progress.opensuse.org/issues/128153 which still sometimes occurs. It explicitly waits until the text form is no longer empty. Maybe this is not sufficient but for now I'll try to keep this workaround as simple as possible. (It is a workaround because `send_keys` should actually only return after the text is present.)
=> Fix sporadic failures of comments test

codecov.yml
According to https://community.codecov.com/t/commit-sha-does-not-match-circle-build/4266/11?u=martchus the problem has been fixed so the token added via
2af754957c56053241a07d05499808ecc236f811 can be removed again.
Related progress issue: https://progress.opensuse.org/issues/128129
=> Remove codecov token again after problem fixed

lib/OpenQA/Script/CloneJob.pm, t/35-script_clone_job.t
If --json-output is used, users expect only JSON and no additional text, so the JSON can easily be parsed.
It was printed to stderr, so it can be treated separately, but still, such text output should only appear when for example in a verbose mode.
Issue: https://progress.opensuse.org/issues/128405
=> Only output JSON when using --json-output

t/35-script_clone_job.t
Fix the warning
```
Use of @_ in array element with signatured subroutine is experimental at t/35-script_clone_job.t line 320.
```
that currently breaks the openQA package build for Tumbleweed.
=> Fix warning related to use of `@_` in signatured subroutine

docs/Installing.asciidoc, docs/UsersGuide.asciidoc, templates/webapi/admin/group/group_property_editor.html.ep
* Fix target of link "cleanup-related properties"; the anchor has been renamed to `basic_cleanup` at some point
* Reduce the "Cleanup" section in the installation guide so it only mentions the most important points and otherwise just directs the user to the "Cleanup …" section in the users guide which some information was moved to. This way the cleanup is still mentioned as configuration step for new installations but does not duplicate information already present elsewhere.
* Rename the "Asset cleanup" section in the users guide to just "Cleanup" and move it out of "Asset handling". This makes more sense because this section is not covering *only* asset cleanup.
* Remove the reference to "Use of the REST API" as this section doesn't contain related information anymore and is also not …
=> Fix issues in the structuring of cleanup-related documentation

t/ui/18-tests-details.t
Fixes
```
getElementText: stale element reference: element is not attached to the page document …
Selenium::Remote::WebElement::get_text(Test::Selenium::Remote::WebElement=HASH(0x563e27154330)) called at t/ui/18-tests-details.t line 340
```
which can occur when the element is swapped out by JavaScript at the wrong moment. That the JavaScript code swaps out the element is actually provoked by this test and supposed to happen.
This change simply does the check in JavaScript to avoid running into this condition.
=> Fix sporadic failure in t/ui/18-tests-details.t

lib/OpenQA/Jobs/Constants.pm, lib/OpenQA/Schema/Result/Jobs.pm
With this change the files `worker-log.txt` and
`worker_packages.txt` will be deleted as well when cleaning up job logs. Those files usually don't take that much disk space which is likely why they haven't been considered for now. However, even just for the sake of consistency it makes sense to delete them - so when looking at job results it is immediately clear that logs have been cleaned up.
Related ticket/note: https://progress.opensuse.org/issues/129244#note-24
=> Delete worker logs as well when cleaning up job logs

docs/ContainerizedSetup.asciidoc
It is `container/` and not `containers/`.
=> doc: Fix wrong paths to container directory

lib/OpenQA/Jobs/Constants.pm, lib/OpenQA/Schema/Result/JobGroups.pm, lib/OpenQA/Task/Job/Limit.pm, t/17-build_tagging.t
When cleaning up job results, jobs being part of an important build are treated differently. So far really only the BUILD variable is used to decide whether a job belongs to an important build - even if the according tag includes a version number.
With this change the version from the tag is considered as well and matched against the job's VERSION variable.
Related ticket/note: https://progress.opensuse.org/issues/129244#note-18
=> Consider a tag's version when cleaning up job results

dbicdh/PostgreSQL/deploy/100/001-auto-__VERSION.sql, dbicdh/PostgreSQL/deploy/100/001-auto.sql, dbicdh/PostgreSQL/upgrade/99-100/001-auto.sql, dbicdh/_source/deploy/100/001-auto-__VERSION.yml, dbicdh/_source/deploy/100/001-auto.yml, lib/OpenQA/Schema.pm, lib/OpenQA/Schema/Result/Jobs.pm, lib/OpenQA/Schema/Result/ScheduledProducts.pm, lib/OpenQA/Schema/ResultSet/ScheduledProducts.pm, lib/OpenQA/WebAPI/Controller/API/V1/Webhook.pm, t/10-jobs.t, t/39-scheduled_products-table.t, t/api/02-iso.t, t/api/16-webhooks.t
* Cancel a previously scheduled product when a PR is updated
or closed.
* Introduce the CANCELLED status of a scheduled product so this
is visible in the UI. Jobs belonging to CANCELLED scheduled
products might later be treated differently by the cleanup as
well.
* Related ticket: https://progress.opensuse.org/issues/127949
=> Handle updated/closed PRs via webhook

docs/ContainerizedSetup.asciidoc, docs/Installing.asciidoc
* State that the approach using Fedora-based images is not
supported
* Mention the one-liners that are already present in the
"Getting started" chapter
* Don't consider the setup proof-of-concept anymore; it
basically works and users are supposed to report issues with
it
* Mention how to configure the worker
* Mention where the config files from the example commands come
from
* Link the "Running openQA workers" and "Triggering tests"
sections for how to continue once the containers are running
* Mention how to invoke other tools within a container
---
@AdamWill We've also noticed that the documentation about Fedora-based container images and how it is currently interleaved with the documentation about "our" containers is supposedly a bit confusing for newcomers. So I suggest we at least …
=> Improve documentation about containerized setup

lib/OpenQA/Script/CloneJob.pm
The `&&` took precendence over the `not`.
Issue: https://progress.opensuse.org/issues/128405
=> Fix logic in openqa-clone-job

docs/GettingStarted.asciidoc, docs/Installing.asciidoc
* Fix the broken reference to the bootstrapping section
* Mention the container-based setup section
* Related ticket: https://progress.opensuse.org/issues/129883
=> doc: Improve references for a quick installation

lib/OpenQA/WebAPI/Controller/API/V1/Job.pm, t/32-openqa_client.t
* Do not use a sub process; this is not useful anymore because we start the web UI service via `… prefork … -c 1 …` to allow only one connection per process (so no other connections are impaired by blocking here)
* Remove event tracking that was only useful for a unit test to track coverage despite using a sub process
* Simplify the error handling and variable passing
=> Improve performance of server-side asset upload handling

assets/javascripts/comments.js
* Avoid one level of indentation via an early return
* Use less jQuery, e.g. replace `editorForm.find('[name="text"]')` with just `form.text` which is much simpler
* Use `const`/`let` to make scope and constness of variables more clear
* Related ticket: https://progress.opensuse.org/issues/129946
=> Simplify JavaScript code for adding/updating comments

container/devel/Dockerfile
currently x86_64 aarch64 riscv64
=> Build openQA devel container only on archs where chromium is built

script/openqa-bootstrap
It is not clear from #5163 if skip_suse_tests also means skip openSUSE specific setup. Call fetchneedles by default to avoid test regression.
Reference: https://progress.opensuse.org/issues/130201
=> Fix condition evaluation for skip variables

t/ui/15-comments.t
This way the code that enters the comment text uses the same selectors than the code under text that reads the comment text. Maybe this helps to fix https://progress.opensuse.org/issues/129946 or at least allows us to rule out certain theories¹ why the test sometimes fails.
---
¹ Somtimes
* there might be multiple elements with the same ID on the page.
* there might be multiple elements with the same name in the form.
* the forms API behaves somehow differently than the normal DOM API.
=> Use same selectors in comments test as in real code

t/ui/18-tests-details.t
* This commit adds tests for 14fe3c67d1ba202cbc7caf4e7ba3fab738fa560a
* Related ticket: https://progress.opensuse.org/issues/128588
=> Add test for rendering Git links in investigation tab

.obs/workflows.yml
The OBS changed how it decides if a service should run for a package. Services in modes that would not run server side are filtered out.
This means packages created with `link_package` steps stopped running services a while ago. 
Using the `branch_package` step with `add_repositories: disabled` is a replacement for having a package with services but only selected repositories in the test build.
=> Switch OBS SCM/CI Workflow to branch_package

etc/nginx/vhosts.d/openqa.conf
While deploying Nginx in production on O3 we learned a couple of important lessons that led to these improvements:
* Buffer sizes better reflect the requests we are dealing with in production and reduce the need to write bodies to disk.
* Large file downloads without sendfile made the whole webui feel sluggish.
* Increased read and write timeouts are necessary for WebSockets, as well as certain HTTP endpoints that have not yet been optimized.
* The missing `Host` header resulted in OpenID authentication breaking because of localhost redirects.
Progress: https://progress.opensuse.org/issues/129490
=> Add various optimizations and bug fixes for O3 deployment

script/openqa-clone-custom-git-refspec, t/40-script_openqa-clone-custom-git-refspec.t
If openqa-clone-custom-git-refspec is called with openQA jobs that already
specify a git repository in CASEDIR the product dir is computed by the
openQA worker as a relative path without the git checkout directory as a
prefix. That so far has led to the problem that the product directory
string that is passed to openqa-clone-job
would be concatenated without separator leading to cases like
"my_distriproducts/foo" when instead "my_distri" and "products/foo"
should be joint with "/" as standard path separator. This commit fixes
this within openqa-clone-custom-git-refspec by always joining the path
components with "/" as path separator while ensuring that no slashes are
duplicated themselves.
Additionally tested by manually scheduling openQA jobs
openqa.opensuse.org with the generated …
=> Fix openqa-clone-custom-git-refspec on git-checkout job sources

lib/OpenQA/Worker/Job.pm, t/24-worker-jobs.t
For reviewing it makes likely most sense to view the particular
commits individually.
---
This allows os-autoinst to explicitly pass a job result to the
web UI in the same way it can already pass a reason.
The main motivation is https://progress.opensuse.org/issues/129068
but this can potentially be useful in other error situations as
well.
=> Pass job result from os-autoinst's state file to web UI

lib/OpenQA/Schema/Result/ScheduledProducts.pm, public/schema/JobScenarios-01.yaml, t/api/02-iso-yaml.t, t/data/09-schedule_from_file_minimal.yaml
This allows each job in a scenario definitions YAML file to be given its own priority value, which takes precedence over any other priority value specified in the file
Given this is possible when creating a job group in the WebUI it seems reasonable that is should exist here too.
=> Add `priority` property to `job_templates` in YAML

etc/nginx/vhosts.d/openqa.conf
The vast majority of requests handled by the webui are artefact uploads. These tend to be around 1mb in size because of the default UPLOAD_CHUNK_SIZE value. Buffering them all to disk is unnecessary and causes quite a bit of disk I/O overhead.
I've tested two solutions for this. The first was
`client_body_buffer_size 2m`, which had the desired effect and only left a very small number of uploads to be buffered to disk. The second was `proxy_request_buffering off` (disabling all upload buffering), which seemed to work as well at first, but then caused the webui app server to be overwhelmed at peak times (502 Bad Gateway responses).
Nginx appears to be doing a pretty good job protecting the webui from traffic spikes with buffering. We should probably leave it enabled for larger HTTP bodies. …
=> Increase client_body_buffer_size to be larger than UPLOAD_CHUNK_SIZE

lib/OpenQA/Schema/Result/ScheduledProducts.pm, t/api/02-iso-yaml.t, t/data/09-schedule_from_file_wildcard.yaml
When using the `SCENARIO_DEFINITIONS_YAML[_FILE]` options, allow the use of a wildcard (`*`) for the version, as is allowed when defining job groups through the webUI
=> Allow wildcard version in scenarios YAML

docs/WritingTests.asciidoc
After https://github.com/os-autoinst/os-autoinst-distri-example/pull/25 the example distribution is going to use `pull_request_target` so the caveat regarding PRs from fork repositories no longer applies.
Related ticket: https://progress.opensuse.org/issues/129730
=> Update CI documentation to use of `pull_request_target`

etc/nginx/vhosts.d/openqa.conf
We were experiencing repeated downloads of the same assets in openqa-clone-job, because the asset is set to the current timestamp after download, but by default nginx wants the exact timestamp match.
=> nginx: Set if_modified_since before

container/devel:openQA:ci/base/Dockerfile
See: https://progress.opensuse.org/issues/130603
=> Update CircleCI image to Leap 15.5

lib/OpenQA/WebAPI/Controller/Step.pm, t/ui/03-source.t
When viewing a source of a test module when CASEDIR was set to a local file instead of an url, the code would be stuck and output these warnings:
Exiting subroutine via last at /lib/OpenQA/WebAPI/Controller/Step.pm line 351.
Exiting eval via last at /lib/OpenQA/WebAPI/Controller/Step.pm line 351.
=> Fix source view of local case dirs

container/single-instance/Dockerfile
* container: Add healthcheck for single-instance
* container: Update single-instance according to best practices
This should address the problem observed in
https://build.opensuse.org/package/live_build_log/devel:openQA/openQA-single-instance-container/containers/x86_64
```
Error: tag openQA:single-instance: invalid reference format: repository name must be lowercase
```
=> Fix openqa-single-instance build tag

docs/Installing.asciidoc
The "single-instance" container should be the easiest and quickest
solution to bring up an openQA instance independant of openSUSE. This
commit rearranges the installation documentation to feature that
solution most prominently and mentioning the "quick bootstrapping under
openSUSE" as second approach next the custom installation is the third
approach.
Related progress issue: https://progress.opensuse.org/issues/129883
=> docs: Feature the "single-instance" container most prominently

lib/OpenQA/Worker/Engines/isotovideo.pm, t/24-worker-engine.t, t/data/openqa/share/factory/hdd/symlink.qcow2
Issue: https://progress.opensuse.org/issues/129340
Hardlinking a symlink will only work if the link is absolute, and we would have to check that recursively if the symlink target itself is a symlink, so just fall back to symlink then.
=> Do not hardlink symlink assets

script/openqa-clone-job
The argument `--within-instance` expects an hostname.
=> Fix example in openqa-clone-job helptext

lib/OpenQA/Scheduler/Model/Jobs.pm
This might help with investigation why the cleanup does not work (we see multiple directories per worker currently).
Issue: https://progress.opensuse.org/issues/131465
=> Improve tempdir template uniqueness

dist/rpm/openQA.spec
Local changes to this file have been overwritten by the latest package update. Using this macro should prevent that.
=> Make sure munin config survives package update

Makefile, dist/rpm/openQA.spec
Ticket: https://progress.opensuse.org/issues/131024
=> Include nginx config in RPM

assets/javascripts/tests.js
See https://progress.opensuse.org/issues/132413
=> Fix escaping in test tables

lib/OpenQA/WebAPI/Controller/API/V1/Job.pm, t/api/04-jobs.t
* Validate job IDs passed to job list API route
* See https://progress.opensuse.org/issues/132545
=> Avoid errors in the logs when invalid job IDs are passed

lib/OpenQA/WebAPI/Controller/API/V1/Job.pm, t/api/04-jobs.t
* Validate group IDs passed to job list API route
* See https://progress.opensuse.org/issues/132545
=> Avoid errors in the logs when invalid group IDs are passed

lib/OpenQA/CacheService/Task/Asset.pm
* Use the `SignalGuard` like in other places to retry the job on
a service restart
* Tested by starting `script/openqa-workercache run` locally and
enqueuing a `cache_asset` job manually:
```
script/openqa-workercache minion job -e cache_asset -a [3421068, "iso", "openSUSE-Leap-15.4-DVD-x86_64.iso", "https://openqa.opensuse.org/"] -n {"lock":"foo"}
```
* Without this change, the job ends up with `Job terminated
unexpectedly` when sending SIGINT to
`script/openqa-workercache run`
* With this change, the job ends up inactive and is retried
when invoking `script/openqa-workercache run` again
* The restarted job finished successfully and the checksum
of the downloaded file matches the one on o3
* See https://progress.opensuse.org/issues/132434
=> Avoid asset caching ending up with `Job terminated unexpectedly`

lib/OpenQA/Worker/Engines/isotovideo.pm, t/24-worker-engine.t
* Abort the job if the asset caching has already run into an error
* Tested locally by enabling the cache service, cloning a job from o3 and patching the worker so it would cache the asset from o3 and not the local web UI * After the caching task had exhausted all retries the Minion job was marked as failed (but not "processed") and then the openQA worker also marked the openQA job as incomplete with the reason `Reason: cache failure: Failed to download …` instead of letting it run into the setup timeout.
* See https://progress.opensuse.org/issues/132434
=> Avoid worker to wait until setup timeout on asset errors

docs/Networking.asciidoc
By using completely executable commands we can have an easier time in
setups without needing to adjust each command or manually enter
filepaths.
=> docs: Make multi-machine related code sections directly executable

assets/javascripts/tests.js, assets/stylesheets/overall.scss, templates/webapi/test/infopanel.html.ep, templates/webapi/test/tr_job_result.html.ep
A lot of online systems allow user to either copy to clipboard or easily select the job/ticket/case ID.
My intention is to enable the same functionality for openQA, so when user wants to f.e. clone the job it will be faster.
There is [fa-copy](https://fontawesome.com/icons/copy?f=classic&s=solid) icon in All tests and in Job group overview and there is job ID printed in job overview and is clickable.
=> Make the job ID copying easier

docs/WritingTests.asciidoc
Add more info on how to write python tests for openQA, based on https://progress.opensuse.org/issues/109891 and https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17325/files findings.
2 main points:
- be able to use other libraries than testapi
- be able to call perl functions that expect named arguments
I am of course open to change it in any way you feel like, the important thing is to have it described somewhere!
=> Enhance Python test docs

etc/nginx/vhosts.d/openqa-locations.inc
Mojolicious requires proper knowledge about the reverse proxy infrastructure for login redirects to work as described in https://docs.mojolicious.org/Mojolicious/Guides/Cookbook#Reverse-proxy. We were missing an additional header which I took from the example in https://docs.mojolicious.org/Mojolicious/Guides/Cookbook#Nginx.
=> Add X-Forwarded-Proto to nginx config

t/ui/18-tests-details.t
A helpful failure might look something like this:
Using `diag explain` here so we're still checking the whole structure.
See: https://progress.opensuse.org/issues/132410
=> tests: Improve failure when comparing expected image results fails

assets/javascripts/audit_log.js, assets/stylesheets/tables.scss
Some values might contain line breaks, for example the relatively new setting SCENARIO_DEFINITIONS_YAML. Before everything was printed in one line. Line breaks got lost.
=> Display line breaks in data tables

assets/javascripts/audit_log.js, assets/javascripts/comments.js, assets/javascripts/openqa.js, assets/javascripts/test_result.js, lib/OpenQA/WebAPI/Controller/API/V1/Iso.pm, t/ui/17-product-log.t, t/ui/18-tests-details.t, templates/webapi/test/infopanel.html.ep
* Fix re-triggering scheduled products with falsy required params
(see commit message for details)
---
* Allow to re-trigger a scheduled product from the job details
page of a job of this product
* Re-schedule the job itself and all its chained children
and parallel dependencies
* Do *not* re-schedule chained parents
* Refactor JavaScript code for re-scheduling so it can be used
on the job details page as well
* Improve error handling in JavaScript code for re-scheduling
* State successful re-triggering via "The product has been
re-triggered as …" with a link (instead of "… should appear
when refreshing page.").
* Related ticket: https://progress.opensuse.org/issues/124469
=> Allow to partially re-schedule a product from a job

docs/Pitfalls.asciidoc
Apparently the service setup commands for the service "isotovideo" need
the parameter "--permanent". Tried this out on a current openSUSE Leap
15.5 multiple times while setting up new openQA workers for
openqa.opensuse.org as part of https://progress.opensuse.org/issues/132134
Related progress issue: https://progress.opensuse.org/issues/133025
=> docs: Fix firewalld service setup commands

docs/Networking.asciidoc, docs/Pitfalls.asciidoc
With os-autoinst now having a setup script
os-autoinst-setup-multi-machine the documentation should clarify that
many steps do not need to be conducted manually anymore but are provided
by a setup script which is also linked as reference.
Related progress issue: https://progress.opensuse.org/issues/133025
=> docs: Point to new multi-machine setup script instead of manual steps

lib/OpenQA/WebAPI/Controller/Admin/Influxdb.pm
DBIx::Class would to the right thing, but we're using DBI directly, and the stringified DateTime object will by default not have the timezone offset appended.
Related issue: https://progress.opensuse.org/issues/133889
=> Add timezone to SQL query

script/openqa-bootstrap
The Leap version specific sub-repo should be preferred over the main
devel:openQA repo so that version-specific package updates can be
supplied and are preferred. This change also aligns the priority values
with the one we have in documentation.
=> openqa-bootstrap: Align Leap repo priorities with documentation

etc/nginx/vhosts.d/openqa-upstreams.inc
Unfortunately `max_conns` does not make much sense for us without the `queue` setting, which is only available in the commercial version of Nginx currently. In the open source version any new incoming request would immediately receive a 502 response if all 30 upstream connections are in use.
However if we ever run into a problem where the openqa-webui service gets hopelessly overloaded because of too many incoming requests, `max_conns` would be a very good temporary measure to protect it. Because it is so easy to set up.
Progress: https://progress.opensuse.org/issues/132167
=> Remove max_conns setting again from Nginx config

assets/javascripts/tests.js, etc/openqa/openqa.ini, lib/OpenQA/Scheduler/Model/Jobs.pm, lib/OpenQA/Setup.pm, lib/OpenQA/WebAPI/Controller/Test.pm, t/config.t, t/ui/01-list.t
See individual commits
~~I think we could also show the actual limit value, e.g. `x jobs are running (limited by server config: 250)`
WDYT?~~
=> Show max running jobs on /tests page

lib/OpenQA/Client/Upload.pm, lib/OpenQA/WebAPI/Controller/API/V1/Job.pm, lib/OpenQA/Worker/Job.pm, t/24-worker-jobs.t, t/32-openqa_client.t
While retries for asset chunks do work correctly, the messages being logged for failures can be a little confusing. By adding the number of remaining retries in a way similar to other log messages, it gets a lot easier to spot what is really going on. And that the "errors" are actually fairly harmless given the context.
Once this has proven itself in production, we might want to redesign the event interface a bit and get rid of a few events. There is a bit of redundancy right now in the logging. But i can see how that might help find issues in the upload logic as it stands right now.
I've also cleaned up the upload code a little bit to bring it closer to our current standards, without making changes to the API (yet).
Progress: https://progress.opensuse.org/issues/132167
=> Log number of remaining retry attempts for asset uploads

etc/openqa/workers.ini, lib/OpenQA/Client/Upload.pm, lib/OpenQA/Worker/Job.pm, t/24-worker-jobs.t, t/32-openqa_client.t
I've only made the number of retries configurable via workers.ini for now. Because i believe it would make sense to replace the hardcoded 5 second delay in between attempts with a smarter backoff algorithm that slowly increases with each attempt.
Progress: https://progress.opensuse.org/issues/132167
=> Make the number of asset upload attempts configurable

lib/OpenQA/Scheduler/Model/Jobs.pm, t/04-scheduler.t
We have to access the config via an OpenQA::App singleton.
$self->{config} simply isn't set, but I was assuming that because
I looked at _update_scheduled_jobs which uses
my $max_job_scheduled_time = $self->{config}->{scheduler}->{max_job_scheduled_time}
So I relied that this would just work. That's also why I had problems to
set the config in the test.
Issue: https://progress.opensuse.org/issues/129619
=> Fix scheduler getting max_running_jobs config

lib/OpenQA/Scheduler/Model/Jobs.pm, lib/OpenQA/WebAPI/Controller/Test.pm, t/05-scheduler-capabilities.t, t/05-scheduler-full.t, t/43-scheduling-and-worker-scalability.t
Issue: https://progress.opensuse.org/issues/134114
=> Remove defaults, should be ensured by OpenQA::Setup already

etc/openqa/workers.ini, lib/OpenQA/Client/Upload.pm, lib/OpenQA/Utils.pm, lib/OpenQA/Worker/Job.pm, t/16-utils.t, t/24-worker-jobs.t, t/32-openqa_client.t
This change introduces a slowly increasing backoff delay (5-30 seconds) into the asset upload retry logic to replace the hardcoded 5 second delay. Additonally a random 0-1 second padding will be used to decrease the chances of multiple workers retrying asset uploads at the exact same time. The algorithm was chosen fairly arbitrarily, i just wanted something that increases linearly and is easy to understand.
Since O3/OSD service restarts usually take around a minute, i've also increased the number of retries from 5 to 10. That should give all our workers more than enough time to recover from any expected webui downtime by default.
Progress: https://progress.opensuse.org/issues/132167
=> Add usleep_backoff function and use it for asset uploads

lib/OpenQA/Schema/Result/Comments.pm, lib/OpenQA/Schema/Result/Jobs.pm, t/api/09-comments.t
In particular, it makes sense to allow this not only for done jobs but also for jobs that are canceled (and have never been assigned to a worker).
See https://progress.opensuse.org/issues/127280
=> Allow using force-result label with all final job states

assets/stylesheets/tables.scss
Settings become unreadable or even hidden when they flow outside of the containing element or window.
Fall back to wrapping the text if nothing else.
See: https://progress.opensuse.org/issues/134897
=> Allow settings to wrap into the next line

lib/OpenQA/Schema/Result/Workers.pm, lib/OpenQA/WebSockets/Controller/Worker.pm
This combines the t_seen and error updates into one. Also removed some dead code in the seen method.
Progress: https://progress.opensuse.org/issues/135122
=> Remove one UPDATE query from worker status updates

Makefile
There is no `Wants` in our unit files, so the `Conflicts` was never added. Change the expression to add it after `After`.
Reference: https://progress.opensuse.org/issues/133352
=> Fix missing Conflicts in unit files

etc/openqa/workers.ini, lib/OpenQA/Constants.pm, lib/OpenQA/Utils.pm, lib/OpenQA/WebSockets/Controller/Worker.pm, lib/OpenQA/Worker.pm, lib/OpenQA/Worker/CommandHandler.pm, lib/OpenQA/Worker/WebUIConnection.pm, t/05-scheduler-full.t, t/24-worker-webui-connection.t, t/27-websockets.t
This patch gets rid of the expensive `SELECT COUNT(*) FROM workers` and replaces the complex status update interval calculation with something simpler.
1000 status updates **before**:
1000 status updates **after**:
Progress: https://progress.opensuse.org/issues/135362
=> Remove worker population broadcasts

lib/OpenQA/Scheduler/Model/Jobs.pm, t/04-scheduler.t, t/05-scheduler-dependencies.t
Before the actual limit would have been max_running_jobs + MAX_JOB_ALLOCATION.
Note that any parallel cluster jobs might still get the number of running jobs
above that limit, but those are usually not more than a handful of jobs.
Issue: https://progress.opensuse.org/issues/129619
See individual commits
=> Make max_running_jobs a hard limit

Makefile
Improve the patterns and append/insert lines around the [Service] line, which should be present in a .service unit file in any case.
Reference: https://progress.opensuse.org/issues/133352
=> Makefile: Make replacements in unit files more robust

lib/OpenQA/Schema/Result/Workers.pm
This is option **B**. See #5301 for option A.
The `$worker->unfinished_jobs` in the websocket server is the last low hanging fruit shown by my profiling data. And it is an interesting one because it has the potential to be a huge improvement, or to be a bit underwhelming. It is entirely dependent on how many previous jobs the worker sending the status update has in the database.
Currently the SQL query generated by DBIx::Class ends up using an index for the `assigned_worker_id` field, but not for `t_finished`. A combined index for both fields has shown the best imporvements. But Tina brought up the idea of using the `state` instead of `t_finished`, which is almost as good.
For the benchmark i've used a real world example from OSD with 1420 previous jobs. Due to DBIx::Class overhead there …
=> Make searching for unfinished jobs faster (Option B)

etc/openqa/workers.ini, lib/OpenQA/WebSockets/Controller/Worker.pm, t/27-websockets.t
This will give us a hint at when the websocket server is falling behind with handling worker status updates. It should usually happen when multiple updates end up in the websocket buffer and are handled right after another.
In the future we could use this condition to ignore the extra status updates. Which would give the websocket server a much better chance to recover on its own, if this was only a temporary performance issue.
Progress: https://progress.opensuse.org/issues/135362
=> Log an info message when worker status updates are too frequent

lib/OpenQA/WebSockets/Controller/Worker.pm, t/27-websockets.t
This is a small correction to #5303. The worker will send an immediate "working" status update
[here](https://github.com/os-autoinst/openQA/blob/98e54f9632959aed6a15e3d0afe0a9bdb6249bd4/lib/OpenQA/Worker/Job.pm#L307) whenever a new job has been started. So that case needs to be excluded. Since we do expect most problematic cases to involve "free" status updates, this shouldn't harm the effectiveness of the feature for detecting scalability issues.
Progress: https://progress.opensuse.org/issues/135362
=> Fix websocket warning not to include the status "working"

assets/javascripts/test_result.js
When viewing a test live and test module details are added to the page dynamically, then the key navigation breaks. It skips steps instead of just selecting the next/previous step. This is because the event handler is registered multiple times. This change fixes the issue by making sure the event handler is only registered once.
=> Fix key navigation on test details

lib/OpenQA/Scheduler/Model/Jobs.pm, t/04-scheduler.t
We want to know how many jobs are skipped because of no available workers matching requested WORKER_CLASS settings.
Related issues:
* https://progress.opensuse.org/issues/135578
* https://progress.opensuse.org/issues/129619
=> scheduler: Log statistics of rejected jobs

lib/OpenQA/WebAPI/Controller/Admin/Influxdb.pm, t/api/13-influxdb.t
We also need to add the timezone offset in the test to tell postgres that the date is meant to be UTC.
Otherwise the test can fail depending on the local timezone.
=> t: Fix api/13-influxdb.t timezone issue

t/04-scheduler.t
I'm now reusing jobs and also reduced the number of workers. This reduced the runtime a bit from 2.07 to 1.84.
Considering that the test before only had one worker and two jobs, and that we want to test code which deals with multiple workers and jobs, I think the increase to before the original pull request is legitimate.
Issue: https://progress.opensuse.org/issues/129619
=> Reduce runtime of t/04-scheduler.t

cpanfile, dependencies.yaml, tools/ci/build_dependencies.sh, tools/ci/ci-packages.txt, tools/tidy
Perl::Tidy version has two dots now, e.g. 20230909.0.0
The original grep for `[0-9]*` resulted in three lines, so that sed complained:
sed: -e expression #1, char 55: unterminated `s' command
See https://app.circleci.com/pipelines/github/os-autoinst/openQA/12241/workflows/6a3918da-3db5-402a-9bc3-b616c7d5715d/jobs/114292
=> Fix dependency update script

lib/OpenQA/Scheduler/Client.pm
Because of how the scheduler is designed, using a timer that can prevent I/O
events from getting handled, multiple wakeups in a short timeframe will trigger
the reschedule often enough to make some of them exceed their request timeout.
And this is actually fine. However, this is therefore no good indicator for
performance issues in other areas of the code, as we've been assuming
previously.
Related progress issue: https://progress.opensuse.org/issues/135380
=> De-prioritize harmless log message about scheduler wakeup

lib/OpenQA/UserAgent.pm
When openqa/client.conf has two sections pointing to the same instance the workers won't be able to boot because the API Key returned by OpenQA::UserAgent will include a line break.
Now only the last value defined in openqa/client.conf will be used.
The issue raises when running `script/openqa-bootstrap` twice, a set of duplicate credentials will be created and trigger the error.
The error msg looks like:
```
+ su _openqa-worker -c '/usr/share/openqa/script/worker --instance 1'
[info] worker 1:
- config file:                      /etc/openqa/workers.ini
- name used to register:            b17139cf73ec
- worker address (WORKER_HOSTNAME): localhost
- isotovideo version:               40
- websocket API version:            1
- web UI hosts:                     localhost
- class: …
```
=> Properly handle duplicate sections on openqa/client.conf

dist/rpm/openQA.spec
This way warnings won't make our builds and PRs fail.
Issue: https://progress.opensuse.org/issues/137105
=> spec: Use PERL_TEST_WARNINGS_ONLY_REPORT_WARNINGS

Makefile, dist/rpm/openQA.spec, systemd/openqa-worker.slice
All workers are already part of openqa-worker.slice, apply memory limit to that slice to ensure that memory cannot be exhausted exclusively by workers.
Reference: https://progress.opensuse.org/issues/133511
=> Apply memory limit for openqa-worker services

container/helm/charts/webui/values.yaml, container/helm/charts/worker/values.yaml, docs/Installing.asciidoc
After we already switched bases for building and CI to a more recent
version long ago we now switch all remaining references before Leap 15.4
goes EOL.
Related progress issue: https://progress.opensuse.org/issues/130597
=> Update all container references to current Leap 15.5

docs/UsersGuide.asciidoc, lib/OpenQA/Script/CloneJob.pm, script/openqa-clone-job, t/35-script_clone_job.t
Reference ticket: https://progress.opensuse.org/issues/122953 
to better support statistical investigation, we want to provide an
immediate way to clone a job multiple times. Till now it has been done
with a for loop similar to
```
for i in {01..50}; do openqa-clone-job … TEST+=-$i; done
```
But we can avoid the API overhead of copying the same parameters and
assets again and again from the original job, simply by cloning it once and
posting the new job(s) N times. The TEST name is automatically numbered, so the
user is not forced to remember any shell syntax.
As the default is `--repeat=1`, the API remains compatible with any shell
script using the `openqa-clone-job` program.
=> Add repeat parameter to clone a job multiple times

lib/OpenQA/Utils.pm, t/16-markdown.t, t/16-utils.t
There's a repo under here we need to reference for Fedora flatpak issues (the URL used in the tests is a real one we need to ref).
=> Add Fedora SIGs gitlab group to bugrefs

docs/WritingTests.asciidoc
- Extended the OpenQA Test Module documentation with improved structure and examples.
The module interface is documented (all the possible routines and their purpose are explained & trackable in the sidebar).
- Explained how the python support works in openQA.
Added a small section on how python support is provided by openqa, as well as the limitations that the FFI Layer brings.
- Reorganized the example test modules.
=> Extend Test Module Documentation & Explain Python integration

.github/workflows/commit_message_checker.yml
- Updated gsactions/commit-message-checker to v2.
- Added a rule for commit subjects. They must not end in dots.
See the discussions in #5430 about commit subject lines.
=> Update commit-message-checker & add extra rule for subject lines

.github/checklist.yml
This is hopefully fixing it; apparently you can't just give it a directory name
=> Warn when modifying files under external directly

t/lib/OpenQA/SeleniumTest.pm, t/ui/27-plugin_obs_rsync_status_details.t
Not sure what changed, but on current Fedora Rawhide, just 'exit'ing like this now results in a 255 exit code and a failed test. Before:
Install Selenium::Remote::Driver and Selenium::Chrome to run these tests
./t/ui/27-plugin_obs_rsync_status_details.t ................. ok
Install Selenium::Remote::Driver and Selenium::Chrome to run these tests
./t/ui/28-keys_to_render_as_links.t ......................... ok All tests successful.
after:
Install Selenium::Remote::Driver and Selenium::Chrome to run these tests
./t/ui/27-plugin_obs_rsync_status_details.t ................. ok
Install Selenium::Remote::Driver and Selenium::Chrome to run these tests
./t/ui/28-keys_to_render_as_links.t ......................... skipped: (no reason given) ...
./t/ui/28-keys_to_render_as_links.t …
=> Fix skipping Selenium tests

contrib/munin/config/minion.config, contrib/munin/plugins/minion, t/46-munin.t
We can disambiguate what aspect of the minion setup the failure stems from.
See: https://progress.opensuse.org/issues/138545
=> munin: Include context in minion plugin title

etc/openqa/openqa.ini
In particular there is no use of a heartbeat_timeout in code and there's a few missing keys.
=> Sync AMQP plugin config defaults with code

templates/webapi/comments/add_comment_form_groups.html.ep
Related progress issue: https://progress.opensuse.org/issues/139055
=> templates: Clarify how issue reference carry over can be prevented

assets/javascripts/openqa.js, lib/OpenQA/WebAPI/Controller/API/V1/Search.pm, t/api/15-search.t, t/ui/15-search.t, templates/webapi/search/search.html.ep
Now one can easily jump to the results by type and see the individual number of results
Slightly related issue: https://progress.opensuse.org/issues/137243
Screenshot:
=> Add headers to search results

lib/OpenQA/Command.pm, t/43-cli-api.t
There may be temporary network problems or an overloaded webui. In those cases we also want to retry.
Issue: https://progress.opensuse.org/issues/138545
=> Make openqa-cli retry also on connection errors

docs/Installing.asciidoc
1. Remove mentioning of version from which PostgreSQL is supported ( this was introduced
so many years ago so no really find version which does not support it)
2. Explicitly state requirements of PostgreSQL setup
=> Update documentation about manual setup of PostgreSQL

assets/stylesheets/comments.scss, docs/UsersGuide.asciidoc, lib/OpenQA/Markdown.pm, lib/OpenQA/Schema/Result/Comments.pm, lib/OpenQA/Schema/Result/Jobs.pm, lib/OpenQA/Utils.pm, lib/OpenQA/WebAPI/Controller/API/V1/Comment.pm, t/16-markdown.t, t/17-labels_carry_over.t, t/23-amqp.t, t/api/09-comments.t, t/ui/14-dashboard.t, t/ui/15-comments.t, templates/webapi/comments/add_comment_form_groups.html.ep
Ticket: https://progress.opensuse.org/issues/136244
=> Add formatted bugref and carryover flag for comments

dependencies.yaml, dist/rpm/openQA.spec, etc/openqa/openqa.ini, lib/OpenQA/Setup.pm, lib/OpenQA/WebAPI/Plugin/ObsRsync.pm, t/config.t, t/ui/27-plugin_obs_rsync_obs_status.t, tools/ci/ci-packages.txt
ObsRsync Plugin now supports the new authentication mechanism of Build Service.
Heavily inspired by:
- https://github.com/openSUSE/obs-build/blob/master/PBuild/SigAuth.pm
- https://github.com/openSUSE/cavil/commit/583009d5476961557802c72250128cc2062c14b2
- https://www.suse.com/c/multi-factor-authentication-on-suses-build-service/
Addresses [poo#139073](https://progress.opensuse.org/issues/139073)
---
**Important:** The production `openqa.ini` config must be updated. `obs_rsync.project_status_url` must not include `/public/`.
=> Add support for SSH Authentication to ObsRsync Plugin

assets/stylesheets/comments.scss
=> Prevent label/flag/bugref overlapping

lib/OpenQA/Schema/Result/Jobs.pm, t/05-scheduler-dependencies.t
See https://progress.opensuse.org/issues/150917
=> Do not associate skipped child jobs with new parent when restarting jobs

assets/javascripts/openqa.js, assets/javascripts/tests.js, t/ui/26-jobs_restart.t
Appending the force-parameter doesn't work that easily when the URL already contains other parameters. So we need to take that case into account when adding the force-parameter.
I made this fix in the context of working on https://progress.opensuse.org/issues/150917.
=> Fix force-restarting jobs when an advanced restarting option was chosen

lib/OpenQA/Schema/Result/ScheduledProducts.pm, t/39-scheduled_products-table.t, t/data/openqa/share/factory/iso/dvdsize42.iso
Assets without a size are treated like they don't exist. With POST isos, referenced assets don't directly get a size and are thus not shown as downloadable. Only the next limit_assets task run changes this by running refresh_assets. Improve this by setting the size for assets on job creation.
=> Set asset size on job creation

lib/OpenQA/WebAPI/Plugin/ObsRsync.pm
- Mojo::tempfile will create a temporary file in the current working directory. Passing TMPDIR=1 forces the function to use the global temp folder instead.
Addresses: [poo#139073](https://progress.opensuse.org/issues/139073)
=> Pass TMPDIR=1 to OBS Rsync authentication

assets/stylesheets/comments.scss
=> Fix testrefs in lists

lib/OpenQA/Schema/Result/Jobs.pm, templates/webapi/test/infopanel.html.ep
I would like to have clickable links in the `JOB_DESCRIPTION`. With this, I could use the `JOB_DESCRIPTION` linking to a corresponding trigger source (e.g. a gitlab pipeline).
=> infopanel: render scenario_description as markdown

lib/OpenQA/Schema/Result/Workers.pm, lib/OpenQA/WebAPI/Controller/Test.pm, t/38-workers-table.t
The `WORKER_HOSTNAME` variable usually contains the worker host's FQDN so it makes sense to show it (instead of just the `host` column) in the VNC instruction.
Related ticket: https://progress.opensuse.org/issues/151576
=> Show FQDN in VNC command if available via `WORKER_HOSTNAME`

assets/javascripts/running.js, assets/stylesheets/overview.scss, lib/OpenQA/LiveHandler/Controller/LiveViewHandler.pm, lib/OpenQA/Schema/Result/Workers.pm, lib/OpenQA/Shared/Plugin/SharedHelpers.pm, lib/OpenQA/WebAPI/Controller/Test.pm, t/34-developer_mode-unit.t, t/38-workers-table.t, t/ui/25-developer_mode.t, templates/webapi/test/live.html.ep
* The `WORKER_HOSTNAME` variable is only available once the test is running
and its value has been passed by the worker via a status update. To use
it in the developer mode's VNC instructions we must pass the VNC argument
dynamically once the web socket connection has been established.
Otherwise one had to reload the page manually.
* See https://progress.opensuse.org/issues/151576
=> Pass VNC argument for developer mode dynamically when test has started

t/ui/15-comments.t
See https://progress.opensuse.org/issues/152077
=> Add additional check in `t/ui/15-comments.t` for easier debugging

lib/OpenQA/CLI/schedule.pm
openqa-cli schedule will only fail if there is error key in the json
root. In our case, the error message is inside the failed job list. Make
openqa-cli fail on that as well.
Reference: https://progress.opensuse.org/issues/138203
=> Parse error messages from scheduling failures

docs/Networking.asciidoc
* Use a MAC address in the example that can actually be used but that also does not conflict with the range we assign in os-autoinst for SUT VMs
* Ensure that the device is up upfront and combine that with setting the MTU
* Make it clear that the tap device must not be used by a SUT-VM at the same time
* See https://progress.opensuse.org/issues/152389
=> Improve instructions for setting up VM to debug MM setup manually

.github/checklist.yml, .gitignore, Makefile, docs/Gemfile, docs/Gemfile.lock, tools/generate-docs, tools/generate-htmldoc, tools/generate-htmldoc-in-container
- Introducing two `Makefile` targets:
* `generate-docs`: Installs all dependencies and compiles the docs.
* `serve-docs`: Spins a local webserver to inspect the compiled docs.
~~Once this is merged it may be possible to delete ruby dependencies from the OpenQA Docker image :thinking:~~
The documentation cron does not depend on this script, it runs isolated in its own way to run directly asciidoctor.
As a first step, for developers this would suffice to easily build docs. In a follow-up the documentation publisher script could be improved.
=> Simplify generation of documentation

etc/openqa/workers.ini
* Document `CACHELIMIT` and `CACHE_MIN_FREE_PERCENTAGE`
* Improve wording in documentation of `CACHEDIRECTORY`
* Make it clear what the default value is
* Related ticket: https://progress.opensuse.org/issues/152545
=> Improve documentation of cache service related variables in config

lib/OpenQA/Schema/Result/Jobs.pm, t/09-job_clone.t
For longer chains of clones it's more efficient. It also avoids a warning:
Deep recursion on subroutine "OpenQA::Schema::Result::Jobs::related_scheduled_product_id"
Issue: https://progress.opensuse.org/issues/152569
=> Use postgresql recursive feature for getting scheduled product

lib/OpenQA/WebAPI/Controller/Test.pm, t/ui/16-tests_dependencies.t
When computing the dependencies to show in the dependency graph we prefer to show the latest child of a parent instead of the child we immediately found when traversing the list of children. This is implemented as an early return. In case of this early return we must *not* count the immediate child as visited. Otherwise we might miss it when traversing the dependency graph further (and it is the latest child from that perspective).
Related ticket: https://progress.opensuse.org/issues/136154
---
I have tested it manually ~~and it works but I'll keep it a draft because I need to extend unit tests~~.
=> Fix dependencies not showing up in graph under certain conditions

t/data/openqa/share/tests/opensuse/tests/openQA/kate.pm
Same as suggested in our documentation we should use Mojo::Base
consistently in openQA test modules which we only have a single one of
within this repository.
Motivated by:
* https://github.com/os-autoinst/os-autoinst-distri-example/pull/28
=> t: Use consistent 'Mojo::Base' instead of strict+warnings

docs/WritingTests.asciidoc
- Explain that it includes default best practices for perl (warnings, strict, utf8, etc.).
- Add a link to `Mojo::Base` upstream docs.
=> Add a note for `Mojo::Base` in Documentation for Tests

lib/OpenQA/Script/CloneJob.pm, script/openqa-clone-job
Introduces the `--skip-checks` parameter to avoid additional checks like maintenance update availability in `openqa-clone-job`.
=> Introduce --skip-checks in openqa-clone-job

docs/WritingTests.asciidoc
This PR is mainly about reformatting and restructuring. Checkout the particular commits for easier review. The real changes in wording/grammar are actually not much.
Note that everything after `==== SCHEDULE + ASSET_<NR>_URL` is wrongly formatted as bold in the diff. However, I don't think this is related and the rendered version https://github.com/Martchus/openQA/blob/23ec4a97b27fd77dc3ad23a1b1b5fec07ff4290b/docs/WritingTests.asciidoc looks good. Of course I also tested the rendering of the whole documentation locally.
=> Improve "How to write tests" documentation

assets/javascripts/tests.js, lib/OpenQA/Constants.pm, lib/OpenQA/WebAPI/Controller/Test.pm, lib/OpenQA/WebAPI/Plugin/Helpers.pm, t/ui/02-list-group.t, templates/webapi/test/list.html.ep
Based on #5388, and reusing most of the same logic, to bring job group filtering to `/tests` from `/tests/overview`. Similar to the `?match=...` option, this does not have a UI element yet and can only be used by manually entering the query parameter. Since the question of how to extend the filter form with text fields is still open, i consider it out of scope for this PR.
Progress: https://progress.opensuse.org/issues/134933
=> Add group filter options for /tests

lib/OpenQA/Schema/Result/Needles.pm, lib/OpenQA/Worker/Engines/isotovideo.pm
We observed that the variable PRJDIR ends up with inconsistent values in
vars.json files which is then rendered as a diff from the openQA
investigation tab even though likely the effective value used within
openQA never differed. The variable PRJDIR is actually never used itself
so to prevent confusion we can simply remove all according references.
The internal function "prjdir()" is untouched.
This change effectively prevents pre-2020 versions of os-autoinst, in
particular before commit 9eb2f564 removing the last use of PRJDIR, to
work which should not be our concern because for multiple reasons it
would be a bad idea if not outright impossible to have a current openQA
working with such old versions of os-autoinst.
Related progress issue: https://progress.opensuse.org/issues/152392
=> Prevent ambiguous PRJDIR ending up in vars.json

lib/OpenQA/WebAPI/Controller/Test.pm, lib/OpenQA/WebAPI/Plugin/Helpers.pm, t/ui/02-list-group.t, t/ui/10-tests_overview.t
This is a followup for #5388 and #5401. When there were no matches for job group globs, no query condition would be generated previously. Giving the false impression that all job groups were matching. So now we just generate an impossible query that cannot match anything with the group id `0`.
Progress: https://progress.opensuse.org/issues/134933
=> Handle no job group filter matches gracefully

docs/GettingStarted.asciidoc
Including the "multiple click points" feature added in <https://github.com/os-autoinst/os-autoinst/pull/2315>.
=> docs: Document how click points work

assets/assetpack.def, dist/rpm/update-cache.sh, tools/ci/ci-packages.txt
Issue: https://progress.opensuse.org/issues/153145
=> Download shepherd.js from cdn.jsdelivr.net

etc/openqa/openqa.ini, lib/OpenQA/Schema/Result/Jobs.pm, lib/OpenQA/Setup.pm, t/09-job_clone.t, t/api/04-jobs.t, t/config.t
It can happen that a job consistently fails with the same error. We want to prevent an endless cloning loop here.
Issue: https://progress.opensuse.org/issues/152569
=> Limit number of auto_clone restarts

docs/Contributing.asciidoc
Issue: https://progress.opensuse.org/issues/153145
=> Update docs for asset cache

assets/javascripts/tests.js, lib/OpenQA/Schema/ResultSet/Jobs.pm, lib/OpenQA/WebAPI/Controller/Test.pm, lib/OpenQA/WebAPI/Plugin/Helpers.pm, t/10-tests_overview.t, t/ui/01-list.t
See particular commit messages and https://progress.opensuse.org/issues/151402
=> Allow searching for jobs by comment text

lib/OpenQA/Schema/Result/Needles.pm, t/lib/OpenQA/Test/Database.pm
* Use raw SQL queries with "ON CONFLICT DO NOTHING" to avoid running into
those errors
* Follow example from `OpenQA::Schema::ResultSet::Assets::register` where
we already use raw queries like that followed by an DBIx call to get the
newly inserted row
* Not using `{for => 'update'}` here to locking as we likely don't need it
here as we don't mind the *exact* last module
* Avoid repeated function calls simplifying the code a little bit
* See https://progress.opensuse.org/issues/153616
=> Fix "duplicate key value violates unique constraint" on needle updates

assets/stylesheets/dashboard.scss, lib/OpenQA/WebAPI/Controller/Main.pm
child_groups was removed in bd79969e32615c8bdacbf8cf1695b8cb60a2c27a but the CSS and the db query were left.
Related issue: https://progress.opensuse.org/issues/152939
=> Remove obsolete entry from group_overview

docs/Networking.asciidoc
See individual commit messages and https://progress.opensuse.org/issues/135914
=> Improve documentation for debugging MM-setup

docs/UsersGuide.asciidoc
* The behavior was recently improved via 707d6bee61804a0c550a4cd61de5ca7ac4e68f4c
* Related ticket: https://progress.opensuse.org/issues/152377
=> Mention handling of symlinks when cleaning up assets in docs

docs/Networking.asciidoc
In the context of verifying the setup it makes most sense to clone jobs on the production instance so `--within-instance` is useful as pointed out in the review.
=> Use `--within-instance` in example for cloning MM jobs

lib/OpenQA/Worker/Job.pm
* Prevent users from cluttering directories when accidentally specifying a wrong `GIT_CACHE_DIR`
* Avoid the Git cache directory configured on a production worker to be used when cloning a job to the local instance (where that directory might not even exists or another cache directory is wanted)
* See https://progress.opensuse.org/issues/154240
---
Note that I haven't extended tests because we already have a test for the changed line and we likely don't need to test the same behavior for all the relevant keys.
=> Ensure only the Git cache directory from the local worker config is used

.github/workflows/javascript.yml
* Update Node version to 20
* Update the version of the actions
* Improve naming of the action/steps
=> Avoid deprecation warnings in GitHub action for JavaScript linting

lib/OpenQA/Parser.pm, lib/OpenQA/WebAPI/Plugin/HashedParams.pm
Those annotations do not need anymore and removed. perlcritic passes the test anyway so no policies need to get enabled.
https://progress.opensuse.org/issues/138416
=> Remove no critic annotation

lib/OpenQA/Parser.pm
Nothing is done here what strict would complain about.
=> Remove unnecessary disabling of strict refs

lib/OpenQA/Scheduler/Model/Jobs.pm, lib/OpenQA/Schema/Result/JobGroups.pm, lib/OpenQA/Schema/ResultSet/Jobs.pm
Simply extract parts of the subroutines which causes perlcritic to complain about deeply nested loops.
https://progress.opensuse.org/issues/138416
=> Refactor methods which violate the deeply nested loops

lib/OpenQA/WebAPI/Controller/API/V1/Worker.pm, t/api/01-workers.t
When working on https://progress.opensuse.org/issues/154927 I noticed that we don't reset the error state of a worker on registration. Normally this is not notable because we do when the worker sends a status update which happens only shortly after the registration. However, it makes still sense to clear the old error status on the registration to avoid workers from possibly being considered broken in the small window between the registration and the first status update. This makes only a difference when the worker did not disconnect gracefully.
=> Avoid workers from showing up shortly as broken after registration

external/os-autoinst-common/.github/workflows/perl-critic.yml, external/os-autoinst-common/.github/workflows/perl-lint-checks.yml, external/os-autoinst-common/.github/workflows/yamllint.yml, external/os-autoinst-common/.gitrepo, external/os-autoinst-common/.mergify.yml, external/os-autoinst-common/Makefile, external/os-autoinst-common/dependencies.yaml, external/os-autoinst-common/lib/perlcritic/Perl/Critic/Policy/HashKeyQuotes.pm
subrepo:
subdir:   "external/os-autoinst-common"
merged:   "eb3e05124"
upstream:
origin:   "git@github.com:os-autoinst/os-autoinst-common.git"
branch:   "master"
commit:   "eb3e05124"
git-subrepo:
version:  "0.4.6"
origin:   "???"
commit:   "???"
=> git subrepo pull (merge) external/os-autoinst-common

lib/OpenQA/BuildResults.pm, lib/OpenQA/WebAPI.pm, lib/OpenQA/WebAPI/Controller/API/V1/JobGroup.pm, lib/OpenQA/WebAPI/Controller/Main.pm, t/api/10-jobgroups.t
Issue: https://progress.opensuse.org/issues/152939
I moved `_map_tags_into_build` into the `compute_build_results()` function.
The command lime to get the last "published" build would look like this:
openqa-cli api job_groups/1/build_results only_tagged=1 limit_builds=1 \
| jq -r '[.build_results[] | select(.tag.description=="published") | select(.version=="Tumbleweed") | .build ][0]'
To only get the latest build:
openqa-cli api job_groups/1/build_results  limit_builds=1| jq -r '[.build_results[] | .build ][0]'
Only normal groups are supported, not parent groups, to keep it simple. I can go though our logs to see if the group_overview.json is ever called for parent groups.
I am seeing a problem with the documentation display of the new function when getting a 404. The documentation for …
=> Add /job_groups/id/build_results API route

t/lib/OpenQA/SeleniumTest.pm, t/ui/16-tests_job_next_previous.t
This test sometimes fails to go to the "Next & previous tab" leading to failures in subsequent test code. This is likely because the navigation handling of Bootstrap's JavaScript plugin hasn't been initialized when the test attempts to click on the tab. This change simply makes the test click again while waiting for the tab's contents to appear which should fix the problem.
Related ticket: https://progress.opensuse.org/issues/155068
=> Avoid sporadic failures in `t/ui/16-tests_job_next_previous.t`

assets/javascripts/filter_form.js, t/ui/10-tests_overview.t
Issue: https://progress.opensuse.org/issues/154537
The code was skipping elements that already existed in the form, and this resulted in elements with multiple values to only keep one value. Now the elements to be added are collected and only added to the form after the loop.
Bug was introduced in 2f6b7e0fd
=> Ensure all hidden form fields in test overview filter

profiles/apparmor.d/usr.share.openqa.script.openqa
* Allow openQA to read packaged node modules
* See https://progress.opensuse.org/issues/153427
=> Adapt AppArmor profile for switch to node modules

container/devel:openQA:ci/base/Dockerfile
* This will allow us to remove the manual zypper call in the asset caching step.
* This was supposed to happen in c5ea52bdc464104d3d60c83d9346f7900e0870f0 but this commit only changed the development container and not the one actually used on CircleCI.
* See https://progress.opensuse.org/issues/153427
=> Install npm in the container we use on CircleCI

container/single-instance/Dockerfile
* Configure the service port delta to zero so the connection to the live view handler is still made via the reverse proxy despite the reverse proxy being exposed on a non-standard port
* Keep docker-compose-based setup as-is because it uses standard ports and also exposes the ports of the individual services
* See https://progress.opensuse.org/issues/153499
---
I tested this manually by building the image locally and then invoking the command from our documentation with my local image. It works (and with the current image the issue was reproducible).
=> Make developer mode work in single-container setup

.circleci/config.yml
Just a draft because we need to merge #5473 first; only then the next paragraph is actually true.
---
This was only required for bootstrapping the switch to using npm. Now the container image we use for the CI has been rebuilt and contains the npm package.
Related ticket: https://progress.opensuse.org/issues/153427
=> Remove manual installation of npm when caching assets

docs/Installing.asciidoc
* Give the container a name for easier reference in further explanations
* Add KVM support; this is very useful as many jobs in our instance seem
to use `QEMUCPU=host` and would therefore otherwise fail because this
setting requires KVM support
* Provide an example command for cloning a job and for making an API query;
otherwise it isn't clear how to proceed with a containerized setup like
that after exploring the web UI
* Explain how to provide test code in a containerized setup like this
* See https://progress.opensuse.org/issues/153499
=> Improve out-of-box experience with single-instance container

assets/stylesheets/forms.scss
Eg. by https://openqa.opensuse.org/tests/3937974#next_previous
Before:
After:
=> Fix select dropdown arrow floating over text

container/single-instance/Dockerfile, lib/OpenQA/Setup.pm
Related progress issue: https://progress.opensuse.org/issues/153499
=> Simplify service_port_delta with environment variable

lib/OpenQA/CLI/monitor.pm, lib/OpenQA/CLI/schedule.pm, t/43-cli-schedule.t
This allows to monitor a set of job which will be useful for further CI-related use cases like cloning existing jobs and monitoring them (see https://progress.opensuse.org/issues/130934).
Of course the existing `openqa-cli schedule` command will continue to support the `--monitor` parameter.
=> Split monitoring of jobs via `openqa-cli` into a separate command

docs/UsersGuide.asciidoc
So far openqa-label-all was not mentioned in the documentation at all.
=> docs: Mention openqa-label-all in documentation

container/worker/Dockerfile
Requires https://github.com/os-autoinst/os-autoinst/pull/2460 to be merged.
Also see https://progress.opensuse.org/issues/153706
=> Add ipmi-deps to our worker container

docs/Networking.asciidoc
Ticket: https://progress.opensuse.org/issues/155929
=> Update networking doc advising RSTP instead of slower STP

Makefile, lib/OpenQA/WebAPI.pm
Tested by removing the `node_modules` directory and invoking commands like
`make test TESTS=t/api/01-workers.t` locally.
`npm install` is only called if `package-lock.json` has been modified since
the last call.
In addition, I also added an additional commit to improve the error message as
this can still be useful (see commit message).
Related ticket: https://progress.opensuse.org/issues/155713
=> Ensure npm packages are installed when invoking tests

lib/OpenQA/Worker/Engines/isotovideo.pm, t/24-worker-engine.t
* Skip syncing the tests directory (usually `/var/lib/openqa/share/tests`) via the cache service when the job is using Git anyway for its `CASEDIR` (and if separate its `NEEDLES_DIR`).
* See https://progress.opensuse.org/issues/154237
=> Avoid syncing tests via the cache service when using Git anyway

lib/OpenQA/Worker/Engines/isotovideo.pm, t/24-worker-engine.t
Reverts os-autoinst/openQA#5496 as https://openqa.opensuse.org/tests/?limit=2000&resultfilter=Incomplete shows a significant number since the original PR was merged
=> Revert "Avoid syncing tests via the cache service when using Git anyway"

lib/OpenQA/CLI/monitor.pm, lib/OpenQA/Command.pm
Issue: https://progress.opensuse.org/issues/156625
=> Log waiting time in monitor script and useragent

tools/generate-documentation
Reference: https://progress.opensuse.org/issues/156769
=> Pin gem ttfunk to version 1.7.0 due to Ruby version requirement

lib/OpenQA/CacheService/Response.pm, lib/OpenQA/CacheService/Response/Info.pm, lib/OpenQA/Worker/Engines/isotovideo.pm, t/24-worker-engine.t
* Introduce a hard-limit for inactive Minion jobs
* Make the hard-limit slightly higher than the normal limit
* Enforce only the hard-limit on openQA job setup; so when the normal Minion queue limit was reached after a job had already been picked-up it can still continue to create Minion jobs instead of ending up as incomplete
* See https://progress.opensuse.org/issues/128276
---
Still a draft because tests are missing.
=> Make it less likely for jobs incompleting with `Cache … queue … full`

assets/javascripts/render.js, assets/stylesheets/test-details.scss
=> Nicely wrap serial text boxes and don't display leading empty line

lib/OpenQA/WebAPI/Controller/Step.pm, t/27-errorpages.t
Issue: https://progress.opensuse.org/issues/156517
=> Return 404 if module not found

assets/javascripts/overview.js, t/ui/10-tests_overview.t
There's no ticket, just something I noticed when working on https://progress.opensuse.org/issues/154261.
=> Fix showing current result/state filters on overview page

.github/dependabot.yml
Apparently it's not possible to tell the dependabot config to only do security update PRs. But there is a workaround by limiting the number of PRs to 0. The limit does not apply to security updates.
Issue: https://progress.opensuse.org/issues/155410
=> Only allow security PRs from dependabot

lib/OpenQA/Resource/Locks.pm, lib/OpenQA/WebAPI/Controller/API/V1/Locks.pm
* Avoid race condition when creating a barrier by using `ON CONFLICT DO
NOTHING` like we already do for job networks
* Avoid race conditions when waiting on and destroying barriers by calling
update/delete on the search results (and not a single search result) so
the update/deletion is just not affecting any rows instead of running
into `row not found`
* See https://progress.opensuse.org/issues/156754
---
The handling of normal locks should probably be improved as well but is not covered here.
=> Fix race conditions when handling barriers

.github/checklist.yml
This manual step is no longer required after using npm packages.
=> Remove obsolete checklist item about asset cache

assets/assetpack.def, package-lock.json, package.json
Issue: https://progress.opensuse.org/issues/157462
Supersedes 
* #5516
The location of d3.min.js changed in the new version.
=> Bump d3 from 4.13.0 to 7.9.0

.github/dependabot.yml
Issue: https://progress.opensuse.org/issues/157462
Allowing only security updates has the disadantage that there might be security update conflicts which require non security updates, and doing them manually is more work.
Let's try without any limit first.
=> Allow all dependabot pull requests

lib/OpenQA/Command.pm
Increase the delay in each retry to handle slow connections. delay is                                                                                                                                                                        
increased exponentially with a factor which by default is 1, meaning                                                                                                                                                                         
exponential backoff is not used.
=> Use exponential increased delay on retry_tx

assets/stylesheets/overall.scss
On an openQA page using a custom links_footer_left and/or
links_footer_right, e.g.
https://openqa.suse.de/tests/overview?distri=sle&build=20240318-1&result=incomplete
the version string in the footer is cropped despite enough white space
being available. The full version string is readable by scrolling down
but the scroll bar should not be necessary. So no cropping and no scroll
bar should appear if there is enough blank space in both the case of
with or without a custom footer_link content used or not.
This problem was originally introduced with 58747a5ef setting a fixed
height which offsets the version string from the bottom to make it more
readable but does not account for the optional custom_footer inclusion.
This commit fixes this by using a bottom padding instead of prescribing
the …
=> style: Fix custom footer overflow

package-lock.json, package.json
* Keep using the latest version of `d3` and its dependencies which we already install via npm
* Override the `d3` dependency of `dagre-d3` so npm is not installing an old version of `d3` and its dependencies such as `d3-color` which we don't use anyway; this removes many dependencies and will avoid the irrelevant security alert
* See https://progress.opensuse.org/issues/157462#note-20
=> Avoid irrelevant security alert due to old version of `d3-color`

docs/WritingTests.asciidoc, lib/OpenQA/Scheduler/Model/Jobs.pm, lib/OpenQA/Scheduler/Model/WorkerSlotPicker.pm, lib/OpenQA/Scheduler/WorkerSlotPicker.pm, lib/OpenQA/Schema/Result/Jobs.pm, t/04-scheduler.t, t/05-scheduler-dependencies.t
* See contained documentation change
* See https://progress.opensuse.org/issues/135035
---
~~A draft because I still need to extend unit tests. Possibly the big function should also be split. It got a little bit involved but I think the algorithm works without being a full-blown SAT solver. You might want to read the test code first (before the implementation) to see what the difficulty here actually is.~~
=> Allow pinning parallel clusters on one host

t/33-developer_mode.t
It looks like c6ffb423e116035ae5d470eadd6473ff31b0a49f was not enough. The test might also run into an unexpected login text when trying to logout (and not only after trying to login again). This problem shows up in the log like this:
```
```
A simple retry like we already do for the login helps will likely help so that's what change is.
Related ticket/comment: https://progress.opensuse.org/issues/157540#note-3
=> Improve workaround for re-login in developer mode test

t/lib/OpenQA/SeleniumTest.pm
The console will retry and in the case we observed all subsequent testing indeed passed (so the whole test really only failed due to this JavaScript error being logged). If this error would be really problematic subsequent tests would also fail so we don't lose test sensitivity.
Related ticket: https://progress.opensuse.org/issues/157540
=> Prevent developer mode test from failing on redirections

tools/test_containers_compose
The docker-compose tool isn't maintained anymore and should be replaced by the docker compose subcommand:
https://docs.docker.com/compose/migrate/
docker-compose: command not found
=> Switch to docker compose subcommand

lib/OpenQA/Schema/Result/Jobs.pm, t/09-job_clone.t
* Avoid use of `$`-sign
* Include number of restarts and limit
* See https://progress.opensuse.org/issues/153475
=> Improve info about auto-restart behavior involving `auto_clone_regex`

assets/javascripts/tests.js, package-lock.json, package.json
Bumping prettier from 2.3.2 to 3.2.5 as proposed by #5518 requires an update of eslint-plugin-prettier and an according style change.
=> Bump prettier to 3.2.5 along with eslint-plugin-prettier 5.0.0.0

etc/openqa/workers.ini, lib/OpenQA/Worker.pm, t/24-worker-overall.t
When the configured value for "load15" is exceeded the worker won't accept new jobs anymore. This might be useful to avoid workers from being under too heavy load (which would otherwise lead to e.g. typing issues).
See https://progress.opensuse.org/issues/158125
=> Allow configuring a critical value for "load15" for openQA workers

t/ui/13-admin.t
There was a sporadic failure originally observed in CI runs with very low
failure ratio looking like this
```
t/ui/13-admin.t .. 14/?
```
I reproduced the problem locally with
```
runs=200 OPENQA_TEST_TIMEOUT_DISABLE=1 count-fail-ratio make test KEEP_DB=1
TESTS=t/ui/13-admin.t
```
with results fails: 4. Fail ratio 2.00±1.94%, mean runtime: 39.0±3.0 s.
With `make coverage` the results were fails 7. Fail ratio 3.50±2.54%,
mean runtime: 80 s so slightly higher fail ratio with double runtime.
This commit uses "wait_for_element" combining the submit action with the lookup
of the resulting table rows to properly synchronize the action and waiting for
result. This fixes the problem. Verified with 400 runs with a computed failure
probability of less than .75%.
Previously I tried to just wait for …
=> t: Fix sporadic test failure in ui/13-admin.t

t/ui/13-admin.t
Just check whether the dashboard is accessible from the menu and do a small
smoke test. This should already catch issues caused by severe JavaScript
errors like https://progress.opensuse.org/issues/158805.
=> Add test for Minion dashboard

dist/rpm/openQA.spec
Similar as in https://progress.opensuse.org/issues/124670 and
corresponding commit 4b6067931 the "ExclusiveArch" setting in the spec
file seems to affect the complete source package and not just affects a
single sub-package preventing to build even the main package on s390x.
This commit removes the section completely accordingly. Any missing
dependencies preventing a sub-package to be used must be handled
differently, e.g. by disabling the build of certain sub-packages per
architecture in OBS.
A verification in
https://build.opensuse.org/package/show/home:okurz:branches:devel:openQA/openQA
shows promising results for building s390x packages in openSUSE Leap.
Related progress issue: https://progress.opensuse.org/issues/158898
=> dist: Allow build on s390x after verification

lib/OpenQA/Worker/Job.pm
* Treat `GIT_CACHE_DIR_LIMIT` like `GIT_CACHE_DIR`
* See 6085a1a88815735f160de07ca58dc7a21743a1c0 for details
=> Ensure the Git cache cleanup is happening according to local settings

assets/stylesheets/overall.scss
The z-index recently added prevents links to be clickable. I suggest to
live with the unlikely bad impact of the content overlapped by the
footer and instead help to make links clickable again.
No visual difference except for the original problem of overlapping a
submit button on tiny window sizes.
=> style: Fix not-clickable links

lib/OpenQA/Worker/Engines/isotovideo.pm, t/24-worker-engine.t
The openQA worker tries to assign the correct `PRODUCTDIR` for a given `CASEDIR`. This is only done if the web UI provides a Git checkout for the specified `CASEDIR` (which is then either made available via NFS or synced via the worker cache). Unfortunately this leads to problems if that checkout is not representing the structure as it is actually in Git. For instance `os-autoinst-distri-openQA` has no `products/openqa` directory in Git but an admin added one within the web UIs checkout so the needle editor works for this test distribution. This leads to the worker assuming that this directory exists and setting `PRODUCTDIR` accordingly. This in turn leads to isotovideo not finding the directory as it is not actually in Git.
To avoid such problems in general it would make sense to simply …
=> Avoid messing with `PRODUCTDIR` if `CASEDIR`/`NEEDLES_DIR` are from Git

public/schema/JobTemplates-01.yaml, t/api/08-jobtemplates.t, t/data/08-testsuite-empty.yaml
The code already assumes we have exactly one test suite.
See: https://progress.opensuse.org/issues/157774
=> JobTemplates-01.yaml: Disallow empty test suites

lib/OpenQA/Schema/Result/JobModules.pm
The code currently checks whether the file is readable and shows an error to the user if not. This check is not atomic so we might still run into e.g. `Can't open file ".../libssh-18.txt": No such file or directory at OpenQA/Schema/Result/JobModules.pm line 113` leading to a server-side error and a 500 response. With this change we always show the error to the user.
This commit also changes another occurrence of the same lookup-pattern to be consistent (although it is probably not strictly required there).
Related ticket: https://progress.opensuse.org/issues/159447
=> Avoid race condition when reading step details

profiles/apparmor.d/usr.share.openqa.script.worker
The code otherwise runs into a permission error leading to the following warning:
```
Apr 23 14:46:30 aarch64-o3 worker[39373]: [warn] Unable to determine average load: Can't open file "/proc/loadavg": Permission denied at /usr/lib/perl5/vendor_perl/5.26.1/Mojo/File.pm line 133.
```
=> Make CRITICAL_LOAD_AVG_THRESHOLD work with AppArmor

assets/assetpack.def, assets/javascripts/job_templates.js, assets/stylesheets/ace.css, assets/stylesheets/codemirror_customization.css, assets/stylesheets/forms.scss, lib/OpenQA/WebAPI/Plugin/ObsRsync/templates/ObsRsync_folder.html.ep, lib/OpenQA/WebAPI/Plugin/ObsRsync/templates/ObsRsync_gru_index.html.ep, lib/OpenQA/WebAPI/Plugin/ObsRsync/templates/ObsRsync_index.html.ep, lib/OpenQA/WebAPI/Plugin/ObsRsync/templates/ObsRsync_logfiles.html.ep, lib/OpenQA/WebAPI/Plugin/ObsRsync/templates/ObsRsync_logs.html.ep, package-lock.json, package.json, t/ui/13-admin.t, t/ui/18-tests-details.t, templates/webapi/admin/job_template/index.html.ep, templates/webapi/layouts/code_editor.html.ep, templates/webapi/layouts/js_editor.html.ep, templates/webapi/step/src.html.ep, templates/webapi/test/link_context.html.ep
The version of CodeMirror we are using is outdated. The latest version of AceEditor seems easier to use than the latest version of CodeMirror (as no bundling is required) and supports everything we need. So it makes sense to switch to AceEditor.
Related ticket: https://progress.opensuse.org/issues/159411
=> Use the latest version of AceEditor instead of CodeMirror

Makefile
See https://progress.opensuse.org/issues/159411
---
Reproduced/tested locally by installing it using some `DESTDIR` and using the installed `node_modules` directory instead of the one populated by NPM. I'll come up with another change to test this, e.g. as part of our package builds. It would also be possible to avoid having to specify those files manually - although I'm not sure whether it is worth the effort.
=> Fix missing installation of further assets required by Ace

Makefile, dependencies.yaml, dist/rpm/openQA-test.spec, dist/rpm/openQA.spec, lib/OpenQA/Assets.pm, lib/OpenQA/Setup.pm, lib/OpenQA/WebAPI.pm, t/25-serverstartup.t
Otherwise we need many additional dependencies at build time. This is notable when those dependencies are not already pulled-in anyways for running tests and thus will fix builds on architectures where we have tests disabled.
=> Move asset-related setup into its own file to avoid extra build requires

container/devel:openQA:ci/README.asciidoc, container/devel:openQA:ci/dependency_bot/Dockerfile
According to the Readme, this container should be used only in CircleCI but that does not correspond to the reality from CircleCI config:
```
- &dependency_bot
image: registry.opensuse.org/devel/openqa/ci/containers/base:latest
```
Reference: https://progress.opensuse.org/issues/159747
=> Remove unused CI dependency bot container

container/devel/Dockerfile
Create a working folder to mount/checkout openQA source code into.
=> Provide volume and default workdir for openqa_devel container

script/openqa-bootstrap
This info message occurs since at least shellcheck 0.9.0 and leads to the tool exiting with a non-zero return code. The variable is not misspelled, it comes from sourcing `/etc/os-release`.
=> Avoid wrong info message from shellcheck about possible misspelling

Makefile, docs/Contributing.asciidoc
Remove obsoleted and non-working makefile targets, those targets were either pulling an obsoleted container or failed to build a custom one. Use-case of those targets is covered by pulling openqa_devel container and running make run-tests-within-container within that container.
Remove out of date documentation about tests in non-CI containers. Most of this is already outdated and the relevant parts are covered in the circleci-local-container section and were mostly redundant.
Reference: https://progress.opensuse.org/issues/159747
=> Remove obsoleted and non-working makefile targets and outdated documentation

tools/generate-documentation
Fix "grep: warning: stray \ before @"; as `@` is not a special character in regex it does not need to be escaped.
=> Fix regular expression in grep

.github/workflows/check-containers.yml, .github/workflows/check-helm-chart.yml, .github/workflows/checklist.yml, .github/workflows/compose.yml, .github/workflows/prove.yml, container/helm/ct.yaml
We have a lot of Node.js 16 deprecation warnings in our workflows. Upgrading the actions should solve that.
=> Update actions versions to latest release

docs/Installing.asciidoc, docs/asciinema/.gitignore, docs/asciinema/Dockerfile, docs/asciinema/Makefile, docs/asciinema/openqa-in-5-minutes.yaml, docs/images/.gitignore
Add scenario for asciinema recording and include it into documentation.
Add Dockerfile and a short Makefile to allow generating GIFs out of autocast yaml files with the asciicast + agg combo without installing anything. The cast will be done inside the container as well, so the recording is done isolated from the rest of the system.
Reference: https://progress.opensuse.org/issues/76978
=> Add recording how to run openQA test in 5 minutes

lib/OpenQA/Setup.pm, lib/OpenQA/WebAPI.pm, t/api/03-auth.t
This is how adding the CORS header on Mojolicious-level would look like. That's probably better than implementing (multiple) reverse-proxy-specific solutions.
Related ticket: https://progress.opensuse.org/issues/159384
=> Allow configuring Cross-Origin Resource Sharing (CORS) for API requests

lib/OpenQA/WebAPI.pm
The `Access-Control-Allow-Origin` only allows specifying one concrete origin or the wildcard `*`. So in order to support multiple allowed origins we must split the header value server-side and return the header value that matches the requests origin (if allowed). This is also what is suggested in the last paragraph of
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin#examples.
This change also only appends the additional value of the Vary header (which is set in accordance with
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin#cors_and_caching) to avoid completely overriding it (e.g. preserving the Mojolicious default).
I tested this locally configuring multiple or just one allowed origins and verifying via the …
=> Allow specifying multiple comma-separated values for CORS header

container/devel:openQA:ci/base/Dockerfile
Related progress issue: https://progress.opensuse.org/issues/157984
=> Update CircleCI image to Leap 15.6

templates/webapi/test/link_context.html.ep
Related ticket: https://progress.opensuse.org/issues/159411
Typo introduced in d818a0eac4bd490cbea302181de2f8ba54a03704
=> Fix HTML for source view

container/devel:openQA:ci/base/Dockerfile
qemu-kvm is now obsolete in Leap 15.6
Related progress issue: https://progress.opensuse.org/issues/157984
=> CI: Fix qemu-kvm dependency in Leap 15.6

container/devel:openQA:ci/base/Dockerfile
As seen in https://github.com/os-autoinst/openQA/pull/5634, gpg in Leap 15.6 has a different default behavior. Creating the default folder should keep it the same as it was (i.e. prevent keyboxd usage).
=> Prevent keyboxd usage when gpg >= 2.4 is used

etc/nginx/vhosts.d/openqa-locations.inc
Without the slash assets will be seen as redirects.
See: https://progress.opensuse.org/issues/160171
=> Add trailing slashes and autoindex to asset config example

container/helm/charts/webui/values.yaml, container/helm/charts/worker/values.yaml
After:
* #5627
Related progress issue: https://progress.opensuse.org/issues/157984
=> PART 3: Update helm charts to Leap 15.6 after base update - After #5627

lib/OpenQA/Worker/Settings.pm
Sometimes the default is already used by another application.
=> Make VNC port offset configurable

docs/WritingTests.asciidoc, lib/OpenQA/Jobs/Constants.pm, lib/OpenQA/Schema/Result/Jobs.pm
In addition to showing diff of worker_packages.txt, include also a diff
of sut_packages.txt. Creating the file is up to the test, but do add it
to list of files uploaded at the job end.
Document how to use this feature. And while at it, document also
`worker_packages.txt` and `PACKAGES_CMD` setting.
=> Compare SUT package versions in investigation, if available

etc/openqa/openqa.ini, lib/OpenQA/Schema/Result/ScheduledProducts.pm, lib/OpenQA/Setup.pm, lib/OpenQA/Shared/Plugin/Gru.pm, lib/OpenQA/Task/Git/Clone.pm, lib/OpenQA/Utils.pm, lib/OpenQA/WebAPI/Controller/API/V1/Job.pm, t/14-grutasks.t, t/api/04-jobs.t, t/config.t
Ticket: https://progress.opensuse.org/issues/159171
=> Add GRU task to update DISTRI and NEEDLES_DIR from git if needed

assets/javascripts/test_result.js, assets/stylesheets/test-details.scss, t/ui/18-tests-details.t, t/ui/26-jobs_restart.t, templates/webapi/test/infopanel.html.ep
* Remove `… (0)` for jobs with undetermined runtime
* Use proper buttons to make it less likely for users to click on the wrong button
* Improve appearance of help popovers next to buttons
* State explicitly that re-scheduling is not limited to the current job group
* Move buttons to their own section at the right
* See https://progress.opensuse.org/issues/138593
---
The buttons are no actually proper bootstrap buttons. The help-popovers are also proper bootstrap buttons (part of the same button group). When focusing/hovering over the button it also becomes clear that the help-popover is actually a separate button.
Of course not always all actions are displayed and then the actions section at the right takes less space:
The menu with additional options for dependencies is also still …
=> Overhaul info panel on job details page

container/single-instance/Dockerfile
We talked about the above ticket, and that codespaces has a problem with tumbleweed containers.
Buildung a new container on every codespaces start was considered too slow, so it was suggested to downgrade the single-instance-container so that we can use it in codespace.
This is needed before #5648
=> Downgrade single-instance-container to Leap

assets/javascripts/openqa.js, assets/stylesheets/dashboard.scss
Long build numbers might be assigned e.g. to incorporate Git commit hashes. So far they can take a huge amount of the available width so there is not much left for the progress bars next to them. This change limits the maximum width of the build numbers leaving room for the progress bars.
Related ticket: https://progress.opensuse.org/issues/130940
=> Avoid long build numbers from taking too much space on dashboard

.devcontainer/devcontainer.json, README.asciidoc
This PR also restructures openqa-bootstrap a bit.
To try it out, go to https://codespaces.new/os-autoinst/openQA/tree/codespace?quickstart=1 and create a new (or resume an existing) codespace. That can take a while.
openqa-bootstrap will automatically start in the background and write to `/var/log/openqa-bootstrap.log`.
Open a terminal:
```
tail -f /var/log/openqa-bootstrap.log
```
After the webserver has started at port 80, you should be able to open the url in the browser.
Now you can start another codespaces terminal and type
```
openqa-clone-job https://openqa.opensuse.org/tests/4191283
```
for example.
When your codespace is stopped after inactivity, you can resume it (that will only take a few seconds), but then you have to start the …
=> Add devcontainer for Codespaces

script/openqa-clone-custom-git-refspec
This PR adds  a feature to `openqa-clone-custom-git-refspec` to read the GitHub access token from a file in addition to attempting to find a environment variable.
=> Read GitHub token from config file

script/openqa-bootstrap
This enables automatic cloning of Git repositories by the web UI when tests using Git sources are scheduled. We should not yet remove the automatic cloning of openSUSE tests and needles in `openqa-boostrap` itself because we still want to support cloning tests from non-Git sources for now. Additionally, the download in advance might still be desirable.
I plan to add an according check in openQA-in-openQA tests as part of the related ticket (https://progress.opensuse.org/issues/161771).
=> Enable automatic cloning of Git repos in openqa-bootstrap setups

lib/OpenQA/WebAPI/Plugin/ObsRsync/Task.pm
And also what details it is not concerned with: It is merely a runner for an external script.
This is relevant for deciding on what level we want to implement https://progress.opensuse.org/issues/161879.
=> Document what the OBS rsync Minion job does

script/openqa-bootstrap
Related ticket: https://progress.opensuse.org/issues/161771
=> Fix `sed` command in `openqa-bootstrap` after f4c71d4ff2

assets/stylesheets/dashboard.scss, t/ui/01-list.t
Related ticket: https://progress.opensuse.org/issues/162488
=> Fix highlighting of parent/child jobs after Bootstrap 5 migration

t/ui/17-product-log.t, templates/webapi/admin/audit_log/productlog.html.ep
After f20a0bf597c495941edda7afaa649d657754b7c1 job settings specified as query parameters are handled also when the `scheduled_product_clone_id` parameter is present. This revealed the problem that we don't correctly pass the `async=1` parameter on the products log page. This change fixes the problem by removing the too excessive escaping.
This also fixes the problem that the async-flag was not actually passed. This is now tested in the UI test (which would fail without this change).
Related ticket: https://progress.opensuse.org/issues/162608
=> Fix products being wrongly re-scheduled with the setting `AMP;ASYNC=1`

profiles/apparmor.d/usr.share.openqa.script.openqa
Related progress issue: https://progress.opensuse.org/issues/162752
=> apparmor: Allow 'sleep' as needed in os-autoinst scripts

docs/WritingTests.asciidoc
Motivated by the 2024-06-29 openQA user meetup at the openSUSE
Conference 2024. For years one can just trigger empty openQA jobs which
do not have any valid worker class set so that they are not picked up by
openQA workers and then can be updated with according calls
afterwards. This commit explains that in our documentation.
Verified on o3 with https://openqa.opensuse.org/tests/4307868
Related progress issue: https://progress.opensuse.org/issues/18000
=> docs: Explain integration of external test results

docs/WritingTests.asciidoc, etc/openqa/workers.ini, lib/OpenQA/Scheduler/Model/Jobs.pm, lib/OpenQA/Scheduler/WorkerSlotPicker.pm, lib/OpenQA/Schema/Result/Workers.pm, lib/OpenQA/WebAPI/Controller/API/V1/Worker.pm, lib/OpenQA/Worker.pm, t/04-scheduler.t, t/05-scheduler-dependencies.t, t/24-worker-overall.t
https://progress.opensuse.org/issues/158146
=> Provide parallel_one_host_only via workers config file

lib/OpenQA/Utils.pm, t/16-utils.t
Add a missing character to the BUGREF_REGEX which is used to render URL links. As such repos with an underscore in its name can be displayed as a link instead of a plain text in the comment section.
https://progress.opensuse.org/issues/163058
=> Fix URL rendering in job tests' comment

assets/stylesheets/disable_animations.css
This also removes the fade animation from popovers which will hopefully avoid random test failures in tests opening/checking help popovers like `t/ui/15-admin-workers.t`.
Related ticket: https://progress.opensuse.org/issues/163127
=> Disable all kinds of CSS animations in tests to increase stability

.circleci/config.yml
* Make configured token available by specifying context
* See https://progress.opensuse.org/issues/163187
=> Use Codecov-related env variables from orga context

.circleci/config.yml
We need to make some variables available on forks but some should better not be available on forks. The security settings of CircleCI contexts on organization-level allow that so it makes sense to avoid relying on project-level variables.
Related ticket: https://progress.opensuse.org/issues/163187
=> Avoid relying on project-level environment variables in CircleCI

assets/javascripts/openqa.js, assets/javascripts/running.js, lib/OpenQA/LiveHandler.pm, lib/OpenQA/Shared/Controller/Running.pm, lib/OpenQA/WebAPI.pm, t/26-controllerrunning.t, templates/webapi/test/live.html.ep
* Avoid live view viewers from occupying too many Mojolicious workers by moving the image streaming of the live mode to the live handler daemon
* Make sure the frontend code can still connect to the streaming route in a development setup by taking the different port into account and by setting CORS headers
* Tested by running the main web UI service allowing only a limited number of connections via `script/openqa prefork -c 1 -w 1`. This causes it to be unresponsive if there is at least one live view tab open. With this change this is no longer a problem and multiple live tabs can be opened and are updated simultaneously.
* Tested without and with reverse proxy.
=> Prevent live view viewers from making openQA unresponsive

lib/OpenQA/WebAPI/Controller/API/V1/Job.pm, t/api/04-jobs.t
The job overview API already supports most filter parameters the overview
web page supports. This change adds support for the two remaining filter
parameters. (The `t` parameter is still not supported.)
=> Support parameters `arch` and `machine` in job overview API

systemd/openqa-minion-restart.service
Not all services we are trying to restart might be installed, e.g. in production setups workers are on separate hosts and therefore no cache service units are present. This change treats the restart still as success if not all units can be found.
Related ticket: https://progress.opensuse.org/issues/163013
=> Prevent failure when restarting Minion-related services

lib/OpenQA/Shared/Plugin/SharedHelpers.pm, lib/OpenQA/WebAPI/Plugin/Helpers.pm
Issues:
* https://progress.opensuse.org/issues/163931
* https://progress.opensuse.org/issues/163592
* https://progress.opensuse.org/issues/163757
Prevents:
Can't locate object method "render_specific_not_found" via package "OpenQA::Shared::Controller::Running"
I'm not sure how to test this. The t/26-controllerrunning.t is mocking that function.
=> Move render_specific_not_found to SharedHelpers

lib/OpenQA/Shared/Controller/Running.pm, lib/OpenQA/WebSockets/Client.pm, t/26-controllerrunning.t
After moving the code for dealing with the live view image streaming to the live handler we should avoid blocking calls in that code because the live handler is not using multiple processes.
Tested by running a test locally and observing that the `live_log` file in the pool directory is created/removed as expected. The unit test has also been extended to cover the error case as well.
Related ticket: https://progress.opensuse.org/issues/163757
=> Avoid potentially slow ws server slowing down live handler as well

t/03-auth.t, t/04-scheduler.t, t/05-scheduler-cancel.t, t/05-scheduler-capabilities.t, t/05-scheduler-dependencies.t, t/05-scheduler-full.t, t/05-scheduler-restart-and-duplicate.t, t/06-users.t, t/07-api_jobtokens.t, t/07-api_keys.t, t/09-job_clone.t, t/13-joblocks.t, t/14-grutasks.t, t/15-assets.t, t/16-utils-vcs-provider.t, t/20-stale-job-detection.t, t/21-needles.t, t/23-amqp.t, t/25-bugs.t, t/27-websockets.t, t/40-script_load_dump_templates.t, t/42-df-based-cleanup.t, t/42-screenshots.t, t/43-scheduling-and-worker-scalability.t, t/basic.t, t/lib/OpenQA/Test/Case.pm, t/ui/01-list.t, t/ui/06-operator_links.t
It does a
plan skip_all ...
in its main code, which is effectively an exit.
Since that happens in a BEGIN block currently during a 'use', it won't execute any INIT blocks any more in perl version >= 5.38. But the -c compile check is running in an INIT block.
Issue: https://progress.opensuse.org/issues/162866
=> Use require for loading OpenQA::Test::Database

systemd/openqa-livehandler.service
* Make `openqa-livehandler.service` depend on `openqa-websockets.service` as it now depends on it for starting/stopping the live view image of running jobs
* Remove dependency on `openqa-webui.service` as it creates a dependency cycle but the livehandler is not depending on the main web UI directly
* The dependency was introduced in 8fe15fc7aed but without stating the reasoning.
* See https://progress.opensuse.org/issues/163757
=> Update systemd dependencies in accordance to moving code to livehandler

lib/OpenQA/WebAPI/Auth/OpenID.pm, t/03-auth-openid.t, t/03-auth.t
* Use signatures in OpenQA::WebAPI::Auth::OpenID
* Simplify OpenQA::WebAPI::Auth::OpenID
=> Simplify OpenQA::WebAPI::Auth::OpenID

tools/test_containers_compose
See: https://progress.opensuse.org/issues/162848
=> Retry docker compose up to accomodate zypper errors

lib/OpenQA/Shared/Plugin/SharedHelpers.pm, t/26-controllerrunning.t, t/ui/12-needle-edit.t
Issue: https://progress.opensuse.org/issues/163931
It now returns a plain text, because we don't have all helpers and variables
for a fully fledged openQA page in the livehandler.
That's probably ok for such pages that you normally don't link to
directly.
=> Add test for render_specific_not_found

lib/OpenQA/Shared/Controller/Auth.pm
This prevents timing attacks on our API endpoints and orders existing use of that function with the secret as last argument as described by the documentation of [Mojo::Util](https://docs.mojolicious.org/Mojo/Util#secure_compare) ("The secret string should be the second argument, to avoid leaking information about the length of the string.").
=> Add proper constant time comparison authentication functions

docs/Installing.asciidoc, etc/nginx/vhosts.d/openqa-upstreams.inc
Minimum zone size is page size * 8.
See: https://progress.opensuse.org/issues/162611
=> Use nginx zone size large enough for 16k pages

t/full-stack.t
Test::Most exports everything from several other modules, including Test::Deep, which exports 'any'.
This lead to:
Prototype mismatch: sub main::any: none vs (&@)
I saw the warning in the reported issue
https://progress.opensuse.org/issues/164239
=> Avoid warning about clashing imported subroutine

tools/ci/run_unit_tests.sh
Issue: https://progress.opensuse.org/issues/164239
=> Downgrade chromedriver to avoid broken version

lib/OpenQA/Shared/Controller/Auth.pm
[`check()`](https://github.com/os-autoinst/openQA/blob/e9a2e4627cc1de788130eff6d6b052e67cd36164/lib/OpenQA/Shared/Controller/Auth.pm#L28) was previously using the current time. [`_key_auth()`](https://github.com/os-autoinst/openQA/blob/e9a2e4627cc1de788130eff6d6b052e67cd36164/lib/OpenQA/Shared/Controller/Auth.pm#L154) however used the time provided in a header (which is attached right as the transaction starts on the server side). This change makes use of the already existing subroutine `_is_timestamp_valid`  for both places and uses the current time instead of one attached in some hook earlier. It also adds a debug log output to print both plain timestamps in case of mismatches.
Related ticket: https://progress.opensuse.org/issues/162038
=> Use common time comparison logic to enable better logging

etc/openqa/openqa.ini, lib/OpenQA/Setup.pm, lib/OpenQA/Shared/Controller/Auth.pm, t/config.t
Let me know if I should split out https://github.com/os-autoinst/openQA/commit/46a4bec8bc8c65a6972ef171fff5b88fcafc2b9a into a different PR
=> Implement option to configure the hmac time difference tolerance

docs/Installing.asciidoc, script/configure-web-proxy
Reverts os-autoinst/openQA#5769
Since I can't reproduce the failures in openQA-in-openQA tests at all, and I'd rather not leave them broken.
See: https://progress.opensuse.org/issues/162611
=> Revert "Allow configure-web-proxy to use a custom port"

docs/Installing.asciidoc, script/configure-web-proxy
Compared to the previous implementation the script code avoids `test` which has the side effect of changing the exit code of the entire script.
See: https://progress.opensuse.org/issues/162611
=> Allow configure-web-proxy to use a custom port

lib/OpenQA/Resource/Jobs.pm, lib/OpenQA/Resource/Locks.pm, script/openqa-validate-yaml
* Simplify Resource::Locks with direct return of booleans
* Use signatures in Resource::Locks
* Use signatures in Resource::Jobs
* Slightly simplify script/openqa-validate-yaml
=> Simplify+signatures

docs/WritingTests.asciidoc
Make it especially more clear what the defaults are, see
https://progress.opensuse.org/issues/164577.
=> doc: Clarify notes about setting `CASEDIR`/`NEEDLES_DIR`

lib/OpenQA/Schema/Result/Jobs.pm, t/10-jobs.t
The 'obsoleted' result indicates the job was cancelled because a new schedule request for the same scenario came in. In this case it probably doesn't make sense to auto-retry the cancelled job because the new request indicates the admin wants the job run with the new settings.
See: https://progress.opensuse.org/issues/164613
=> Do not retry jobs that were obsoleted

lib/OpenQA/Task/Git/Clone.pm, t/14-grutasks.t
* Retry Git processing instead of immediately failing the Minion job (and
thus also setting the related openQA job to incomplete)
* Improve error messages in git_clone tasks (see separate commit message)
* See https://progress.opensuse.org/issues/163784
=> Avoid incomplete jobs when Git cloning fails

lib/OpenQA/Schema/Result/Jobs.pm
In efe1cdef6 next to "USER_CANCELLED" also "OBSOLETED" jobs were added
to the list where to skip a "RETRY" which was the safe choice. I think
we should treat all "aborted results" the same which means now
additionally including SKIPPED, PARALLEL_FAILED, PARALLEL_RESTARTED,
USER_RESTARTED.
As @baierjan explained in
https://github.com/os-autoinst/openQA/pull/5797/files#r1697036344
"restarting jobs which were already restarted (USER_RESTARTED,
PARALLEL_RESTARTED) probably does not make much sense, which leaves
PARALLEL_FAILED and SKIPPED. I guess PARALLEL_FAILED would be restarted
anyway if needed by the parallel job?" The later question can be
answered with yes so we should be good. And "SKIPPED" means "(directly)
chained dependencies failed before starting this job" so I also don't
see a …
=> Consistently skip RETRY on all aborted results

lib/OpenQA/Shared/Controller/Running.pm
This error condition has no impact on the job execution. It just means that the web socket server is not ready yet as we saw in https://progress.opensuse.org/issues/164709#note-4. The request is already retried on the client-side so the live view will be able to resume once the web socket server is ready and the worker connected back. I tested this locally by entering the "Live" tab while the web socket server is not running. When starting it the live view updates itself after a few seconds (without having to switch tabs or reloading the page).
=> Lower the log level of livestream related problem considering low impact

t/ui/18-tests-details.t
`wait_for_ajax_and_animations` does not fully cover the asynchronous behaviors of the code and also doesn't help with animations. (The relevant animation is already globally disabled via `$.fx.off = true;` but this does not mean code becomes synchronous.)
With this change we simply wait for the element to show up instead.
Related ticket: https://progress.opensuse.org/issues/164745
=> Fix sporadic failures in test of candidates menu

lib/OpenQA/Downloader.pm, t/25-cache.t, t/25-downloader.t
* Remove the made-up HTTP response codes introduced by aea93ad55199a661f84d9ef3aaced66b8ba0d433 (e.g. just log `Connect timeout` instead of `521 Connect timeout`)
* Simplify the code
* Keep retry behavior as-is, so if there's no response code at all or a real 5xx error code the downloader tries again
* Simplify code
* See https://progress.opensuse.org/issues/164222
=> Simplify error handling of downloader, avoid confusing error codes

lib/OpenQA/Schema.pm, lib/OpenQA/Shared/Plugin/Gru.pm
Tests did not cover the 'dsn' function anyway.
=> Remove unused 'dsn' function and its usage

lib/OpenQA/Schema.pm, lib/OpenQA/Shared/Plugin/Gru.pm
Reverts os-autoinst/openQA#4928 as it is actually used in production, e.g. o3
=> Revert "Remove unused 'dsn' function and its usage"

script/openqa-bootstrap
Run openqa-worker on background to allow script to continue with openqa-clone-job invocation, then wait for the worker process.
Reference: https://progress.opensuse.org/issues/164595
=> Allow openqa-bootstrap to clone job in non-systemd environments

docs/GettingStarted.asciidoc, etc/openqa/openqa.ini, lib/OpenQA/Setup.pm, script/openqa-bootstrap, t/api/04-jobs.t, t/api/16-webhooks.t, t/config.t
Enable the `git_auto_clone` feature by default as it seems to work well enough in openQA-in-openQA tests.
Related tickets: https://progress.opensuse.org/issues/162077
=> Ease setup for Git-based workflows

t/ui/18-tests-details.t
See https://progress.opensuse.org/issues/164745
---
To check whether this actually works I added an additional commit to run the relevant test 200 times on CircleCI. So this is still a draft.
=> Workaround candidates menu not opening sometimes in UI tests

lib/OpenQA/Schema.pm, lib/OpenQA/Shared/Plugin/Gru.pm, t/15-shared-plugin-gru.t
In b1da48eac I removed the "dsn" function and its usage as it looked
like that would not be necessary anymore at all and we did not have any
test coverage for that. This turned out to be a false assumption leading
to a production openQA instance to not start anymore with the error
message
```
openqa-webui-daemon: Can't connect to data source 'HASH(0x55d82c060598)' because I can't work out what driver to use (it doesn't seem to contain a 'dbi:driver:' prefix and the DBI_DRIVER env var is not set)>
```
so the change was quickly reverted.
This commit now moves the 'dsn' functionality to the only place where
it is needed, simplifies the call and adds complete test coverage for
the according method with a separate, new test module
"t/15-shared-plugin-gru.t".
Tests did not cover the 'dsn' …
=> Move 'dsn' functionality into only place where used

script/openqa-bootstrap
The removal of the 'method = Fake' was an accident.
Issues:
* https://progress.opensuse.org/issues/164940
* https://progress.opensuse.org/issues/164919
edit: tested locally
=> Fix openqa-bootstrap login

container/single-instance-codespaces/Dockerfile
Reference: https://progress.opensuse.org/issues/161399
This is part 1.
=> Define single-instance container for Codespaces

container/single-instance-codespaces/Dockerfile
OBS buildtime service replace_using_package_version needs the package in the zypper cache to be able to extract the version number to replace.
=> Make sure openQA-single-instance package is present in the codespaces container

dist/rpm/openQA.spec, lib/OpenQA/Utils.pm, script/openqa-webui-daemon, systemd/openqa-webui.service
* Allow restarting `openqa-webui-daemon` without downtime by sending SIGHUP to the process or reloading the systemd unit `openqa-webui.service`
* Start the Mojolicious application with `reuse=1` as mentioned on https://docs.mojolicious.org/Mojolicious/Guides/Cookbook#Zero-downtime-software-upgrades
* Note that other services are not covered but those are also not user facing or retried and thus not required
* See https://progress.opensuse.org/issues/162533
=> Allow restarting `openqa-webui-daemon` without downtime

script/openqa-clone-custom-git-refspec, t/40-script_openqa-clone-custom-git-refspec.t
As per https://progress.opensuse.org/issues/162632, openqa-clone-custom-git-refspec might fail in case NEEDLES_DIR is set and contains an absolute path which directs to the pool. Also in contrast of the poo's suggestion there is no change in removal of the vars.json logic.
```
❯ script/openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-opensuse/tree/master https://openqa.opensuse.org/tests/4368385
1 job has been created:
- microos-Tumbleweed-DVD-x86_64-Build20240730-fips-container-host@64bit -> https://openqa.opensuse.org/tests/4369552
❯ script/openqa-clone-custom-git-refspec https://github.com/os-autoinst/os-autoinst-distri-openQA/tree/master https://openqa.opensuse.org/tests/4360621  
1 job has been created:
- …
```
=> Make jobs running without needing to set needles URL specifically

templates/webapi/test/overview_result_table.html.ep
Issue: https://progress.opensuse.org/issues/164973
Spaces, for example in FLAVOR, result in invalid ids for HTML elements.
=> Ensure valid format for HTML element ids

templates/webapi/test/list.html.ep
Add a small help text on how to filter out groupless jobs using the WebUI
Related Ticket: https://progress.opensuse.org/issues/155398
=> Add help on how to exclude groupless jobs from WebUI

script/openqa-bootstrap
Packages may be deleted before they can be installed.
See: https://progress.opensuse.org/issues/165024
=> openqa-bootstrap: Refresh and retry in case of package changes

lib/OpenQA/Schema/ResultSet/Jobs.pm, lib/OpenQA/WebAPI/Controller/API/V1/Job.pm, t/api/04-jobs.t
Related Ticket: https://progress.opensuse.org/issues/155398
=> Add filter to exclude groupless jobs to API/V1

Makefile
docs/Contributing.asciidoc already suggests to setup the test database
manually or run tests with `KEEP_DB=1` to make development more
efficient. We can make this process even easier to discover and use by
extracting a make target "setup-database".
=> Makefile: Extract separate make target "setup-database" for convenience

t/05-scheduler-full.t, t/43-scheduling-and-worker-scalability.t
Workers don't accept jobs if the load is too high.
Issua: https://progress.opensuse.org/issues/165198
=> ci: Ensure tests pass even under high load

templates/webapi/test/live.html.ep
The link to Steps to debug developer mode setup documentation was wrong. Just Updated with the corresponding one.
=> Fix link in live dev mode to docs

t/14-grutasks.t
I was running this test locally and it failed every second time, because it created some directory that wasn't cleaned up.
Now it copies everything it needs to a tempdir and leaves the source dir alone.
Related issue: https://progress.opensuse.org/issues/164883
=> t: Avoid tampering with git checkout

assets/javascripts/anser-import.js, assets/javascripts/test_result.js, t/ui/18-tests-details.t, templates/webapi/test/logfile.html.ep
One can now filter the log files for substring and regexes.
Demo: https://github.com/user-attachments/assets/f6dec605-951a-4e14-8f93-18acd461a708
Issue: https://progress.opensuse.org/issues/162218
=> Add interactive log viewer

assets/javascripts/test_result.js
The 'search' event is triggered when clicking on the little x in a search box.
Issue: https://progress.opensuse.org/issues/162218
~~That also makes the `change` handler superfluous.~~ Apparently it is still needed, test fails without it.
=> Immediately search when clearing search field

script/openqa-webui-daemon
With this we no longer get `Stopping worker … immediately` which means that `SIGKILL` is sent to the worker process. We instead get `Stopping worker … gracefully` and only `SIGQUIT` is sent to the worker process so it can still conclude its current request.
Related ticket/note: https://progress.opensuse.org/issues/162533#note-24
=> Stop openQA worker processes gracefully to avoid 5xx responses

t/16-utils-runcmd.t
Related Ticket: https://progress.opensuse.org/issues/164886
=> Extend test coverage of OpenQA::Git

etc/openqa/openqa.ini
The (by default disabled) setting for asset_size_limit contained a comment after its value. That causes a lot of lines in journalctl when the setting is activated by removing the hash at the beginning of the line:
```
Aug 15 07:00:59 openqa openqa-gru[1588700]: Argument "100 # only used on job group level (parent groups have n..." isn't numeric in multiplication (*) at /usr/share/openqa/script/../lib/OpenQA/Schema/ResultSet/Assets.pm line 237
```
=> openqa.ini: Move comment on template setting

lib/OpenQA/Task/Git/Clone.pm, t/14-grutasks.t
Issue: https://progress.opensuse.org/issues/164883
=> Prevent git_clone to interfere with needle tasks

lib/OpenQA/Script/CloneJob.pm
The --export-command feature by design has no need for credentials.
=> Allow openqa-cli to export commands without an API

lib/OpenQA/Git.pm, lib/OpenQA/Task/Git/Clone.pm, t/14-grutasks.t, t/16-utils-runcmd.t
Refactor generic git related functions from OpenQA::Task::Git::Clone into the OpenQA::Git module for easier re-usability.
Related Ticket: [164886](https://progress.opensuse.org/issues/164886)
=> Refactor generic git functions into git module

lib/OpenQA/Task/Git/Clone.pm, t/14-grutasks.t
As per git documentation the refspec can formed as <src>:<dst> but dst cannot
use arbitrary expressions (SHA) but an actual ref must be named. Its usage
in the `_git_clone` mistakely adds a SHA ref as destination creating a branch
with its name, which is not supported by git.
As far as now the feature is not used in OpenQA so it can be safely removed.
https://progress.opensuse.org/issues/164937
=> Remove git fetch with destination refspec feature

tools/ci/run_unit_tests.sh
This reverts commit 0c5ff16bec21e4d66fdcca65849e37cf6b3c10a2.
The bug is fixed in version 127 as we can see already in pull requests, as the workaround was only applied for version 126.
Issue: https://progress.opensuse.org/issues/164239
=> Remove workaround for broken chromium

cpanfile, dependencies.yaml, dist/rpm/openQA.spec
The RPM builds do not execute style checks (also when `--with-tests` is used) so dependencies like ShellCheck should not be required for the build.
This avoids pulling in a lot of transitive dependencies into the build and thus also greatly reduces the number of packages we need submit to SLE to build openQA on/for SLE.
Related ticket: https://progress.opensuse.org/issues/165683
=> Avoid having RPM build depend on packages only needed for style checks

.mergify.yml
This was increased to 50 in 8ef5aca82c42a2c8b4246ea281056e7d2a04f199 but the correct number seems to be only 45.
=> Fix number of expected CI checks

lib/OpenQA/Task/Git/Clone.pm, t/14-grutasks.t
I rearranged and got rid of some calls.
In case of the initial clone, we don't actually need to do a fetch afterwards, because an initial clone without any restrictions fetches all refs.
Also, we don't need to retrieve the default remote.
For an update we return early if the remote url doesn't match. And then only if there is no url fragment with a ref, we fetch the default remote.
Finally, I removed the second die in case we couldn't get a default remote. _get_remote_default_branch already dies, the outer die would have never been reached. This case is now also tested in a new subtest.
(And I improved the regex to avoid having to escape slashes: `\/ \/`)
The full list of commands is now tested, and better readable what commands are called for which use case.
Related Issue: …
=> Improve git commands in git_clone job

dependencies.yaml, dist/rpm/openQA.spec
After 26586061eb2c8bc5e9929bec9352deef9ae344d5 the RPM build still depends on many development dependencies e.g. for style checks because we still depend on `os-autoinst-devel` which pulls those in.
Related ticket: https://progress.opensuse.org/issues/165683
=> Avoid requiring `ShellCheck` and other style-related deps for RPM build

dependencies.yaml, dist/rpm/openQA.spec
This Python module is only required by the `test-yaml` target which in turn is only invoked by style checks. So it makes sense to treat this dependency like the other dependencies of style checks.
Related ticket: https://progress.opensuse.org/issues/165683
=> Move `python3-yamllint` from test to style-check dependencies

contrib/ay-openqa-worker-leap-3-nvme.xml, contrib/ay-openqa-worker.xml.erb
Configure the firewall properties as SuSEfirewall2 has been replaced by firewalld and the validation produce a warning. FW_CONFIGURATIONS_EXT keeps working so far because is supported but it is deprecated.
* Avoid deprecation warning about using firewall property
from SuSEfirewall2 times
* Use firewalld configuration instead
https://progress.opensuse.org/issues/156169
=> Fix firewall configuration in Autoyast profile

lib/OpenQA/CLI/api.pm, t/43-cli-api.t
* Avoid skipping the rest of a script when that script is invoked via `sh < …` and internally invokes openqa-cli (which in this case must not consume all remaining lines in that script)
* Read only from STDIN if explicitly requested via `--data-file -` in consistency with curl (which also allows using `-` where a file can be specified to use STDIN)
* See https://progress.opensuse.org/issues/160820
=> openqa-cli: Avoid reading unexpectedly from STDIN

container/single-instance/Dockerfile
* Make sure the single-instance container has all packages the boostrap script will install so it is less likely to run into errors
* See https://progress.opensuse.org/issues/165399
=> Avoid zypper errors when using singe-instance container

lib/OpenQA/Git.pm, lib/OpenQA/Task/Git/Clone.pm, t/14-grutasks.t, t/16-utils-runcmd.t
Refactor git related functions from OpenQA::Task::Git::Clone into the OpenQA::Git module for easier re-usability.
Related Ticket: [164886](https://progress.opensuse.org/issues/164886)
- Turn git functions into git module methods
- Avoid array recreation with _run_cmd helper method and optional use_ssh and use_path parameters
- Improve and adjust and test cases
- Fix merge conflicts after rebase to master branch
=> Refactor git functionality into OpenQA::Git

lib/OpenQA/Shared/GruJob.pm, t/14-grutasks.t
It can happen that a GruTasks entry is added in a transaction and the minion
job already enqueued and started before the transaction is committed.
In that case we shouldn't start the minion job (the transaction could have
been rollbacked even).
The task needs to be deleted by the minion job in order to go on with
processing a job, and it can't delete it if it doesn't see the entry in the
database.
But requiring the entry before the start of the job is even more correct IMHO.
Issue: https://progress.opensuse.org/issues/165866
=> Require GruTask in database before running a minion job

lib/OpenQA/Git.pm
A single quote can be part of a URI.
Issue: https://progress.opensuse.org/issues/166676
=> Use double quotes for quoting links

templates/webapi/test/list.html.ep
This page can have flash messages created by ajax events.
=> Add missing flash message box to /tests page

lib/OpenQA/Worker/WebUIConnection.pm, t/24-worker-webui-connection.t
So far the "last error" was only tracked for REST-API calls (used e.g. for worker registration and uploads) but not in other cases (e.g. web socket related errors). This change extends tracking for to cover those cases by setting the last error to the error messages that is always passed to `_set_status`. This way they are available to be added to the reason when declaring the job as incomplete.
Related ticket: https://progress.opensuse.org/issues/163781
=> Ensure the error responsible for API failures is always added

dist/rpm/openQA.spec
As stated in https://build.suse.de/request/show/343857#comment-4023273 not all sub packages are installable on SLE. This only concerns the `devel` and `munin` sub packages which are really optional. So it makes sense to avoid submitting a huge number of Haskell and Perl packages to SLE and exclude those packages instead.
Related ticket: https://progress.opensuse.org/issues/165683
=> Exclude sub packages with many additional dependencies on SLE

cpanfile, dependencies.yaml, dist/rpm/openQA.spec, t/ui/18-tests-details.t
* Ensure `openQA-devel` depends on `perl(Code::TidyAll)` so that package is
available in the CI
* Add the package only to style check dependencies (and not test
dependencies) so the package build does not depend on it
* See https://progress.opensuse.org/issues/166817
---
Note that I have already prepared a [branch](https://github.com/os-autoinst/openQA/compare/master...Martchus:openQA:tidy?expand=1) to merge https://github.com/os-autoinst/os-autoinst-common/pull/55. For now I excluded this commit because we'll have to wait for the OBS package build on `devel:openQA` and the nightly job on CircleCI for this to become effective.
=> Ensure tidyall is available in CI after 28c5dd1

t/ui/10-tests_overview.t
This might fix failures like:
```
[21:00:46] t/ui/10-tests_overview.t ................... 18/?
```
I could not reproduce the issue locally but probably it helps to use
`wait_for_element` here.
Related ticket: https://progress.opensuse.org/issues/166820
=> Avoid sporadic failures of `t/ui/10-tests_overview.t`

lib/OpenQA/Worker/WebUIConnection.pm
Parentheses can be part of a URL.
Issue: https://progress.opensuse.org/issues/166676
=> Quote URLs with double quotes

assets/assetpack.def, assets/javascripts/create_tests.js, etc/openqa/openqa.ini, lib/OpenQA/Setup.pm, lib/OpenQA/WebAPI.pm, lib/OpenQA/WebAPI/Controller/Test.pm, script/fetchneedles, t/17-build_tagging.t, t/config.t, t/data/openqa.ini, t/data/openqa/share/tests/example/scenario-definitions.yaml, t/ui/29-create_tests.t, templates/webapi/layouts/flash_messages.html.ep, templates/webapi/layouts/navbar.html.ep, templates/webapi/test/create.html.ep
Related ticket: https://progress.opensuse.org/issues/166658
---
~~Still a draft because I need to add UI tests and move the so far hard-coded data into `openqa.ini`. It already reads scenario definitions and certain parameters directly from the example distribution, though.~~ Of course this only works if there's a checkout of the example distribution. Maybe we should offer the user to create that checkout in case it is missing (which wouldn't be very hard to do; we'd just add a link on the web UI that'll internally spawn a checkout Minion job we recently implemented anyway).
---
This is how the menu, the form and success/error messages look like in one screenshot:
=> Allow scheduling a (example) product via the web UI

script/fetchneedles
* Specify no branch name at all (unless a specific branch name is set) to clone the default branch by default
* See https://progress.opensuse.org/issues/166658 and failures like https://openqa.opensuse.org/tests/4500449#step/test_distribution/3
* Tested locally where the problem is reproducible after removing the checkout
=> Fix initial cloning via fetchneedles after 313ee7a1

lib/OpenQA/Schema/Result/ScheduledProducts.pm, lib/OpenQA/Schema/ResultSet/JobSettings.pm, lib/OpenQA/Schema/ResultSet/Jobs.pm, t/05-scheduler-dependencies.t, t/10-jobs.t, t/api/02-iso.t
See particular commit messages and https://progress.opensuse.org/issues/154735
=> Fix checks for worker classes in directly chained clusters

dist/rpm/openQA.spec, etc/openqa/openqa.ini, lib/OpenQA/Setup.pm, lib/OpenQA/Shared/Plugin/Gru.pm, lib/OpenQA/Task/Git/Clone.pm, lib/OpenQA/Utils.pm, script/openqa-enqueue-git-auto-update, systemd/openqa-enqueue-git-auto-update.service, systemd/openqa-enqueue-git-auto-update.timer, t/14-grutasks-git.t, t/api/02-iso-download.t, t/api/04-jobs.t, t/config.t, t/lib/OpenQA/Test/Utils.pm
This replaces the update part of `fetchneedles`. It doesn't replace the initial cloning yet.
git is updated when
* scheduling a product / job -> tests and needles of the relevant jobs are updated
* scheduled hourly via service (or cronjob) -> all repos under `OPENQA_BASEDIR` are updated
Note: `fetchneedles` has a `force` option. We set it to true in our cronjob currently.
This can be added later as a config option.
=> Automatically update git for jobs without CASEDIR/NEEDLES_DIR

lib/OpenQA/Git.pm, t/14-grutasks-git.t
Error detecting remote default branch name for "some git":
"ssh -oBatchMode=yes": ssh -oBatchMode=yes: command not found
Since we are passing an array ref to IPC::Run::run, we should not add quotes. git is trying to call `"ssh ..."` including the quotes.
Issues:
* https://progress.opensuse.org/issues/164898
* https://progress.opensuse.org/issues/164886
=> Fix quoting of git ssh arguments

t/05-scheduler-full.t
This line shows consistently up as uncovered on Codecov and and in the HTML report (downloadable via artifacts). The line is however definitely covered and when executing the tests locally it also appears as such in the HTML report. The test is also definitely not skipped in the CI. To avoid the failing checks on all of our PRs I am marking the line as uncoverable for now.
Related ticket: https://progress.opensuse.org/issues/167272
=> Workaround `scheduler_step` showing up as uncovered

t/14-grutasks-git.t
To be able to have valid git commands in our test (e.g. for copy/paste) we now at least quote any argument that has a space in it.
Related issue: https://progress.opensuse.org/issues/164898
=> t: Improve mocked commands

container/webui/docker-compose.yaml
Apparently this would otherwise pull version 17 right now, while we install postgresql16 in the webui, and the psql 16 client is not compatible with version 17.
Issue: https://progress.opensuse.org/issues/167524
=> ci: Set postgres container version to 16 to ensure compatibility

lib/OpenQA/Shared/Plugin/Gru.pm
I forgot that `-d` is actually true for symlinks.
It resulted in the gru task processing over the same realpaths, trying
to get a guard for the same path multiple times, which failed and ran
int an endless retry.
I tested it locally with symlinks and could now reproduce the problem. It tries to get a guard for the same directory multiple times and runs into an endless retry.
=> Skip symlinks in enqueue_git_update_all

docs/UsersGuide.asciidoc, templates/webapi/test/create.html.ep
See particular commit messages https://progress.opensuse.org/issues/166658#note-15
=> Improve documentation related to "Create …" form and scenario definitions

t/lib/OpenQA/SeleniumTest.pm
There can be 4xx errors present, e.g.:
```
…
…
```
This leads to `wait_for_result_panel` returning early causing follow-up failures like `not ok 7 - job 5 passed` when the job was still running and the normal timeout hasn't been exhausted yet, e.g.:
```
ok 5 - No unexpected js warnings
not ok 6 - Expected result not found
not ok 7 - job 5 passed
```
The only route that would reply with "Unable to read image: …" is never returning a 404 response explicitly. Probably the return code is made up by Chromium internally after the stream is finished with this error message by the server. Maybe this behavior has changed recently explaining why the test is only unstable now.
Related ticket: https://progress.opensuse.org/issues/167269
=> Prevent fullstack test from failing early due to 4xx errors

t/05-scheduler-full.t
Related ticket: https://progress.opensuse.org/issues/167272
=> Avoid problem with coverage report

assets/javascripts/anser-import.js
Related progress issue: https://progress.opensuse.org/issues/166676
=> Remove obsolete linkify workaround for anser<2.3

lib/OpenQA/Task/Git/Clone.pm, t/14-grutasks-git.t
Ticket: https://progress.opensuse.org/issues/167386
=> Decrease log level from warn to info for git clone reject

assets/assetpack.def, assets/javascripts/admin_assets.js, assets/javascripts/admin_groups.js, assets/javascripts/admin_needle.js, assets/javascripts/admin_user.js, assets/javascripts/admin_worker.js, assets/javascripts/admintable.js, assets/javascripts/audit_log.js, assets/javascripts/comments.js, assets/javascripts/fetch_status.js, assets/javascripts/index.js, assets/javascripts/job_templates.js, assets/javascripts/needleeditor.js, assets/javascripts/obs_rsync.js, assets/javascripts/openqa.js, assets/javascripts/overview.js, assets/javascripts/running.js, assets/javascripts/test_result.js, assets/javascripts/tests.js, lib/OpenQA/WebAPI/Controller/API/V1/Table.pm, t/api/05-machines.t, t/lib/OpenQA/SeleniumTest.pm, t/ui/13-admin.t, t/ui/27-plugin_obs_rsync_status_details.t
Ticket: https://progress.opensuse.org/issues/166310
=> Replace $.ajax() with fetch()

dist/rpm/openQA.spec
openSUSE Factory since about 20240928 seems to need an explicit addition
of the "kvm" group. This commit tries to fix that same as we do with
"nogroup".
Related progress issue: https://progress.opensuse.org/issues/167587
=> dist: Add required "group(kvm)" for openQA-worker

t/14-grutasks-git.t
Issues:
* https://progress.opensuse.org/issues/164898
* https://progress.opensuse.org/issues/165393
This tests different failures and also adds coverage for the git part in OpenQA::Schema::Result::Needles.
Trying to make small, easy to review PRs.
=> Add test for delete_needles

lib/OpenQA/Task/Git/Clone.pm, lib/OpenQA/Task/Needle/Delete.pm, lib/OpenQA/Task/Needle/Save.pm, t/14-grutasks-git.t
In OpenQA::Task::Needle::Save, OpenQA::Task::Needle::Delete and
OpenQA::Task::Git::Clone we are now using a guard for the individual directory
`git_clone_${needledir}_task` instead of a global guard limit_needle_task.
=> Improve minion guards for needle tasks

lib/OpenQA/WebAPI/Auth/OpenID.pm, t/03-auth-openid.t
Enhanced error handling by including OpenID provider URI in error messages for
invalid data. The error seems sporadic and as part of the research on
https://progress.opensuse.org/issues/167266 we can consider this not a severe
problem. Because of the sensitivity of the arguments, it is not feasible to
add any info from the available data for later debbugging. But at least now
we can tell which server cause problems.
=> Improve OpenID auth handling on not_openid response

container/webui/docker-compose.yaml, container/webui/run_openqa.sh
Reference: https://progress.opensuse.org/issues/167524
=> Remove scripted waiting for db in favor of healthcheck

t/ui/18-tests-details.t
* The synchronization via `wait_for_ajax_and_animations` did likely not work because there is probably still asynchronicity going on despite the attempt to disable animations explicitly. Note that the relevant Ajax code still uses jQuery so this is *not* a regression of 87a7e36.
* Use `wait_for_element` like in many other cases.
* Avoid running into `Can't call method "is_enabled" on an undefined value` in case the test fails.
* Remove code that attempted to find more than one element by ID. (Even if the ID was not unique the test would not be able to find this violation.)
* See https://progress.opensuse.org/issues/167656
=> Fix race condition in `t/ui/18-tests-details.t`

lib/OpenQA/Constants.pm
Since commit [f19726339710](https://github.com/os-autoinst/openQA/commit/f19726339710e9d9deaf55c0ea2b5a84426f9aad) ("Support parameters `arch` and `machine` in job overview API"), user can filter using those. Add them to the constant shown to the user in `openqa-cli api -h`.
Links:
https://github.com/os-autoinst/openQA/pull/4402
https://progress.opensuse.org/issues/103864
=> cli: List 'arch' and 'machine' as supported in API help

templates/webapi/test/create.html.ep
- Rectified typing error for Test names form field in new test creation template: templates/webapi/test/create.html.ep
- Changed "comman-separated" to "comma-separated"
Related: https://progress.opensuse.org/issues/167824
=> Fix typo for Test names form field

lib/OpenQA/Command.pm, t/43-cli-api.t
Otherwise they will end up as content which subsequent processes cannot parse, e.g. if they expect JSON
Issue: https://progress.opensuse.org/issues/167833
=> Print error messages to stderr

docs/Contributing.asciidoc
The current wording and placement of the `TEST_PG='DBI:Pg:dbname=openqa_test;host=/dev/shm/tpg' OPENQA_DATABASE=test OPENQA_BASEDIR=t/data script/openqa daemon` is not ideal. I hope with these changes the line becomes less confusing. Considering that *not* using this line is what one would normally do, I restored the old explanation from before that line was introduced. I made it clear that one needs to do the database setup first and also improved those parts of the documentation.
Note that before this change the documentation sections suggest the following:
1. Customize the config dir.
2. Setup the database and configure it. There is no mentioning that one has to adjust the config dir customized in 1.
3. The setup done in 1. and 2. is not used at all by the problematic command. Instead …
=> Improve documentation about manual database and daemon setup

lib/OpenQA/WebAPI/Controller/Step.pm, t/ui/03-source.t
During running tests we don't have the vars.json from the worker yet. If we don't have a refspec in the URL, we can link to the default branch by specifying `HEAD` in the url.
Issue: https://progress.opensuse.org/issues/167971
=> Fix source view for running tests

lib/OpenQA/Setup.pm, lib/OpenQA/WebAPI/Controller/API/V1/Table.pm, lib/OpenQA/WebAPI/Plugin/HashedParams.pm, t/api/02-iso.t, t/api/05-machines.t, t/api/06-products.t, t/api/07-testsuites.t, t/api/08-jobtemplates.t, t/ui/23-audit-log.t
Revert the server side code but keep using the new API in openqa-load-templates.
This will allow for  openqa-load-templates to hit downstream before we disable the old API.
=> Partially revert "Drop OpenQA::WebAPI::Plugin::HashedParams"

contrib/munin/utils/munin-mail, dist/rpm/openQA.spec
Issue: https://progress.opensuse.org/issues/166739
The only question is to which path this should be deployed as part of the openQA-munin package
=> Add munin alert email wrapper

templates/webapi/layouts/navbar.html.ep
Other users will just end up on a 403 page with the text "Forbidden" so it makes no sense to show these links to them.
Related ticket: https://progress.opensuse.org/issues/167818
=> Show operator links of plugins (like OBS sync) only to operators

assets/javascripts/audit_log.js, assets/javascripts/openqa.js
This PR fixes the scheduled product page loading issues, which occur when job settings contain arrays, mentioned in https://progress.opensuse.org/issues/166154
example:
=> Allow for structured variables on the scheduled product page

lib/OpenQA/CacheService/Task/Sync.pm
* Use a signal guard like we already do in the `cache_asset` task (also part of the cache service)
* Tested by sending SIGTERM to a running `cache_tests` tasks; it went temporarily into the "inactive" state and the openQA job could still run after the Minion job was eventually finished
* See https://progress.opensuse.org/issues/167797
=> Avoid incomplete jobs when restarting Minion while syncing tests

assets/javascripts/openqa.js, lib/OpenQA/WebAPI.pm, lib/OpenQA/WebAPI/Controller/Admin/AuditLog.pm, t/ui/06-operator_links.t, t/ui/16-activity-view.t, templates/webapi/admin/activity_view/user.html.ep, templates/webapi/layouts/navbar.html.ep
* Allow anyone to access the activity view but show the menu item only to
operators because only those users will have any activity (that the
activity view supports, so comments don't count)
* Add additional (internal) route to query only audit events for the current
user to avoid having to expose all audit events to more users
* See https://progress.opensuse.org/issues/167818
=> Make activity view accessible to operators

etc/openqa/openqa.ini
=> etc: Fix wrong default value in comment

lib/OpenQA/WebSockets.pm, t/27-websockets.t, t/43-scheduling-and-worker-scalability.t
See particular commit messages and https://progress.opensuse.org/issues/157690
---
Unfortunately I could not reproduce any issues with the limit so far. I suppose I can still do some further experimentation but spawning the number of workers we have in production is simply not possible locally as it would take too much memory.
=> Improve tests related to worker online limit

lib/OpenQA/Shared/Plugin/Gru.pm, t/14-grutasks-git.t, t/api/04-jobs.t
To avoid calling `git fetch` too often and having too many minion locks,
we skip a task if it has been done less than one minute ago.
https://progress.opensuse.org/issues/164898
=> Reuse existing GruTasks for same git_clone task

lib/OpenQA/Shared/Plugin/Gru.pm, t/14-grutasks-git.t
The job array should not be emptied because there are other functions called after that that work with the job ids.
=> Fix handling of job array in enqueue_git_clones

lib/OpenQA/Shared/Controller/Running.pm, t/26-controllerrunning.t
* Ensure code section mentioned in https://progress.opensuse.org/issues/167803 is consistently covered
* See further commit messages for other improvements; this PR will generally improve the coverage of streaming-related code
=> Avoid inconsistent coverage of drain callback in streaming code

lib/OpenQA/Schema/Result/Needles.pm, lib/OpenQA/WebAPI/Plugin/Helpers.pm, t/fixtures/07-needles.pl, t/ui/18-tests-details.t, t/ui/21-admin-needles.t
Issue: https://progress.opensuse.org/issues/167635
Unfortunately this makes `t/ui/18-tests-details.t` fail, because of a UI problem. The popup is bigger and somehow prevents the click to close the candidates menu.
I can't reproduce it in non headless mode, because I don't know which size the window would have.
=> Return timestamps with offset to client for needle info

lib/OpenQA/Worker.pm, t/24-worker-overall.t
With https://github.com/os-autoinst/openQA/commit/03b301d1df74857f3b3457477857364255a1671a we have a worker load limit which helps but there can still
be cases like happened on a PowerNV machine with the load going way above
the configured load limit. The reason was that when the worker was idle
within a short time frame of roughly one minute multiple jobs were
assigned to individual worker instances on the machine. As we only
looked at load15 which was still low at that time all jobs were picked
up by the machine leading to overload only about one minute later.
Further reducing the load limit would not realistically prevent this
situation but only delay until load15 decays sufficiently enough so that
new jobs will be picked up again. Instead this commit changes the
evaluation to look at …
=> Improve worker load threshold detection

dist/rpm/openQA.spec
* Allow building against SLFO which is not openSUSE but also does not provide the `sles-release` package; packaging for SLFO will not contain SUSE-specific systemd/timer files for now
* See https://progress.opensuse.org/issues/167245
=> Fix rpm build on non-openSUSE distributions that are not SLES

templates/webapi/test/live.html.ep
- This PR makes the box significantly smaller while its empty, i've tested displaying it without fixed size and it was still displayed correctly
Related issue: https://progress.opensuse.org/issues/134840
=> Prevent big empty liveview in early state of running

lib/OpenQA/WebAPI/Plugin/AMQP.pm
Instead of
Can't call method "BUILD" on an undefined value at .../lib/OpenQA/WebAPI/Plugin/AMQP.pm
we would now see the mising job id.
Issue: https://progress.opensuse.org/issues/124487
=> Slightly improve error handling

lib/OpenQA/Git.pm, lib/OpenQA/Task/Git/Clone.pm, t/14-grutasks-git.t
Issue: https://progress.opensuse.org/issues/168400
=> Do not git fetch if requested sha is already present

docs/Installing.asciidoc
Ticket: https://progress.opensuse.org/issues/168880
=> Document wireguard reverse tunnel

lib/OpenQA/Schema/Result/Jobs.pm
t/ui/10-tests_overview.t was failing under perl 5.40:
ok 1 - job href is shown correctly
not ok 2 - dependency is shown correctly
In newer perl versions booleans are preserved, and when Mojolicious sends JSON to the client, it will return it as `true`. To support both older and newer versions, we explicitly return 0 or 1.
=> Return 0/1 explicitly as the client expects it

t/ui/18-tests-details.t
Issue: https://progress.opensuse.org/issues/169096
Calling a URL with a module step makes an ajax call, so we need `wait_for_ajax` here.
It passed 100 times in a row now.
Maybe @r-richardson  can try it out too.
=> t: Fix sporadic stale element failures in t/ui/18-tests-details.t

assets/javascripts/running.js, assets/stylesheets/result_preview.scss, t/ui/18-tests-details.t, templates/webapi/test/live.html.ep
This PR adds a loading animation indicating that the liveview is being loaded. Currently only a empty box is displayed, visible in the webui before liveview content is received by the responsible canvas element.
Test cases are also added to confirm the elements are displayed and hidden as expected.
Related Issue: https://progress.opensuse.org/issues/134840
=> Add loading indicator to the test liveview

assets/javascripts/tests.js, t/ui/10-tests_overview.t
This PR ensures the result filter options only affects the finished jobs table, meaning the scheduled and running jobs tables are no longer affected.
Related Issue: https://progress.opensuse.org/issues/65205
=> Have filter options only affect finished jobs

docs/UsersGuide.asciidoc, lib/OpenQA/JobSettings.pm, lib/OpenQA/Worker/Engines/isotovideo.pm, t/24-worker-engine.t, t/40-job_settings.t
* Allow substituting placeholders that refer to variables that are only
defined in `workers.ini` for the particular worker slot that picked up
the job
* Keep placeholders of non-existing keys when doing the variable
substitution during job creation on the web UI side (instead of removing
them) so the worker still sees the placeholder and can do a final
substitution (removing placeholders of non-existing keys, so the overall
behavior does not change)
* Do *not* propagate settings from the final substitution back to the web
UI as the job might be restarted and then run on a different worker where
settings might be different
* Extend relevant documentation
* See https://progress.opensuse.org/issues/169159
---
@foursixnine @okurz  I have not implemented a default value as suggested in …
=> Extend variable expansion to consider variables from worker config

assets/javascripts/openqa.js, assets/javascripts/overview.js, assets/stylesheets/overview.scss, t/ui/10-tests_overview.t, templates/webapi/test/overview.html.ep
Refactor restartJob in order to make sure that is able to handle request for
multiple restarts. This follows up with some changes to the form and the
javascript part of the overview.html.ep, which triggers the restart with the
use of restartJob, as opposed of reimplement the logic.
The advantage is that we have one common behavior and error handling on the
restart operation.
- An optional comment can be passed not to restartJob, which is included to
the request.
- restartJob handles both single and multible job restarts.
- The form is designed to handle each occasion in separate functions making
the code becomes more modular and easier to maintain.
- The overvies's restartJobs function will restart only jobs with valid id.- Renamed `addComments` to `bulkJobsAction` to handle both …
=> Add option to restart jobs upon comment submission

t/ui/01-list.t, t/ui/10-tests_overview.t
This commit moves the subtest `result filter does not affect scheduled and running jobs` to t/ui/01-list.t, which tests the /tests page.
=> Move finished jobs filter subtest to correct file

tools/generate-documentation
* Pin Ascii85 to 1.1.1 because newer versions need Ruby 2.7
* See https://progress.opensuse.org/issues/169246
=> Fix generation of documentation as PDF document

lib/OpenQA/Scheduler/Model/Jobs.pm, t/05-scheduler-dependencies.t
Some jobs of a parallel cluster can be blocked (by a chained parent or by a pending Gru task) while some jobs can be scheduled. Before this change the scheduler assigns the jobs that can be scheduled which creates a half- scheduled parallel cluster.
This is particularly problematic when `PARALLEL_ONE_HOST_ONLY=1` and `git_auto_update = yes` are used because then repairing half-scheduled clusters is more challenging and the likeliness that a cluster is partially blocked is higher. In theory this is also problematic when jobs within the parallel cluster depend on different asset downloads.
With this change the scheduler skips the whole cluster until all jobs can be scheduled to avoid half-scheduled clusters. Judging by the previous code and its comments this was already intended but the …
=> Avoid scheduling jobs if not all parallel jobs are ready

etc/openqa/openqa.ini, lib/OpenQA/Schema/Result/GruTasks.pm, lib/OpenQA/Setup.pm, lib/OpenQA/Shared/GruJob.pm, lib/OpenQA/Task/Git/Clone.pm, t/14-grutasks-git.t, t/config.t
* Unblock openQA jobs if Git updates failed for two times
* Change the behavior with `git_auto_update = yes` to be more like it
was with the `fetchneedles` approach (that also did not block jobs in
case of failures)
* Avoid running into timeouts in openQA-in-openQA tests which expect
jobs to be scheduled in a more timely manner, see
https://progress.opensuse.org/issues/169204
* Keep blocking openQA jobs if any of the repositories required by the
scheduled jobs was explicitly specified
---
~~Still a draft as I still need to restrict it to network issues.~~
=> Avoid blocking openQA jobs on Git updates

lib/OpenQA/Worker/Engines/isotovideo.pm
Issue: https://progress.opensuse.org/issues/170206
Note that I don't know if it is a bad thing that no `$cgroup_slice` was found.
=> Avoid warning for undefined cgroup slice

lib/OpenQA/Schema/Result/Jobs.pm, lib/OpenQA/Task/Job/FinalizeResults.pm, t/10-jobs.t
* Call the hook script only if the job was not already in state `DONE`.
* Note that the "done" function might be called multiple times, e.g. by the worker and also by the stale job detection.
* There is still a small possibility that the hook script is called multiple times but it is hopefully not relevant in practice.
* See https://progress.opensuse.org/issues/169747
=> Avoid calling hook script multiple times

assets/javascripts/admin_worker.js, lib/OpenQA/Worker.pm, t/ui/15-admin-workers.t, templates/webapi/admin/workers/worker_status.html.ep
This PR displays "Broken" workers as instead "Unavailable", as the previous wording was e.g. not including workers which where unavailable due to 'too high load'.
It also replaces the 'Error' title of the worker states hover popup with 'Details' and enhances the 'too high load' output.
Example:
Related Ticket: https://progress.opensuse.org/issues/164084
=> Make 'Broken' workers show as 'Unavailable' instead

lib/OpenQA/WebAPI.pm, lib/OpenQA/WebAPI/Controller/API/V1/Routes.pm, t/22-dashboard.t
```
% openqa-cli api routes | jq
{                 
"routes": [                     
{             
"methods": [
"GET"                                     
],                                 
"path": "/"
},                                              
...
{
"methods": [
"DELETE",                 
"GET"     
],          
"path": "/api/v1/assets/<id:num>"           
},                                   
```
I find it cumbersome to find out routes currently. The webpage 404 page, e.g. https://openqa.opensuse.org/foo , is very long and I lose the overview under which top level route I am.
This could also be useful later for creating dynamic completion, e.g. `openqa-cli api j<TAB>`
=> Add endpoint for listing all WebAPI routes

etc/openqa/openqa.ini, lib/OpenQA/Setup.pm, lib/OpenQA/WebAPI.pm, t/03-auth.t, t/config.t
* Disallow unauthenticated access to assets in web application routes
* Does NOT cover access served via Apache/NGINX
* Does NOT cover adjusting the cache service and additional tooling like the `openqa-clone-job` script
* See https://progress.opensuse.org/issues/170380
=> Add config option to restrict asset downloads to logged-in users

container/single-instance/Dockerfile, container/webui/Dockerfile
Reference: https://progress.opensuse.org/issues/174607
=> Make sure locale inside webui container supports UTF-8

lib/OpenQA/Assets.pm
This should prevent _setup_sigchld_handler overriding the handler for IPC::Run3 inside AssetPack. Without this, the sass process is not handled correctly inside the tests and the assets are not correctly compiled by the AssetPack.
Reference: https://progress.opensuse.org/issues/174607
=> Prevent SIGCHLD handler override within tests

script/openqa-load-templates, t/40-script_load_dump_templates.t
The `openqa-load-templates` script now checks if a job groups is already present when importing new template data. If a group already exists, there will be no attempt of creating it, but associated templates will still be loaded if the `--update` option is provided.
If the `--update` option is not provided, and a duplicate job group is found, the import will fail.
Related Issue: https://progress.opensuse.org/issues/174808
=> Check for existing job groups during openqa-load-templates

dist/rpm/openQA.spec, docs/Installing.asciidoc, script/openqa-auto-update, script/openqa-clean-repo-cache
* Add a script `openqa-clean-repo-cache` that allows to clean RPM cache repositories keeping a certain number of packages per version; this is similar to the `paccache` script from Arch Linux
* Allow running this script as part of `openqa-auto-update`
* See https://progress.opensuse.org/issues/174313
---
There are no automatic tests but I tested this locally a lot. The interesting part is just 80 lines of code anyway (and that is *with* the help text and argument parsing boiler plate).
=> Allow cleaning up openQA devel packages from the zypper cache directory

lib/OpenQA/Worker/Job.pm
The `stop` function does the same check internally so it isn't required.
Related ticket: https://progress.opensuse.org/issues/170209
=> Avoid calling `is_running` unnecessarily in `kill`

systemd/openqa-gru.service
Related progress issue: https://progress.opensuse.org/issues/175311
=> systemd: Fix premature kill of openqa-gru background processes

etc/nginx/vhosts.d/openqa-locations.inc, lib/OpenQA/Shared/Controller/Auth.pm, lib/OpenQA/WebAPI.pm, t/03-auth.t
See the individual commit messages and https://progress.opensuse.org/issues/174301 for details.
I found out the problem I previously struggled with (see problematic points on https://progress.opensuse.org/issues/174154). With that out of the way there was actually not that much I had to change. With this PR all ATs in https://progress.opensuse.org/issues/174301 work. (I also slightly extended them along the way to cover both relevant routes.)
I haven't tested the cache service yet.
=> Add restricting asset downloads via NGINX using subrequest auth

templates/webapi/test/live.html.ep
Related progress issue: https://progress.opensuse.org/issues/175168
=> UI: Clarify that virtio_console.log is renamed

tools/unstable_tests.txt
This reverts commit https://github.com/os-autoinst/openQA/commit/b6a5681c4c8be9bf343e1d2979a5b4ae2975d48e, reversing
changes made to https://github.com/os-autoinst/openQA/commit/83f2e292d7bda9e9e48740811a82a3f8f682a73b.
https://progress.opensuse.org/issues/175060
=> Rollback of pull request #6107: full-stack.t removed from unstable_tests

lib/OpenQA/CacheService/Model/Cache.pm, lib/OpenQA/Downloader.pm, lib/OpenQA/Shared/Controller/Auth.pm, lib/OpenQA/UserAgent.pm
This PR incorporates https://github.com/os-autoinst/openQA/pull/6114 which should probably be merged first.
It will tweak the cache service and the openQA user agent in general so both work when authenticated asset downloads are enabled. See https://progress.opensuse.org/issues/170380 and individual commit messages for details.
If wanted I can also extend tests. (Maybe I'll have to adapt tests anyway.) I tested this locally. Before this change it didn't work and with it it works when connecting directly and when using NGINX.
=> Make cache service work with authenticated asset downloads

lib/OpenQA/CLI.pm, lib/OpenQA/CLI/monitor.pm, lib/OpenQA/CLI/schedule.pm
* Fix documentation of syntax for displaying help text of nested commands
* Add a short description of what the schedule and monitor commands do on their help texts
=> Improve help texts of `openqa-cli`

lib/OpenQA/Schema/Result/Jobs.pm, t/05-scheduler-cancel.t
* Convert to our current coding style
* Check the state of the job that is set to DONE as well
* Test the case when the parent job is skipped as well
=> Improve test of failure behavior for multiple parallel children

cpanfile, dependencies.yaml, dist/rpm/openQA.spec
It was renamed long ago, and with the next release the old alias will be removed
=> Replace Perl::Critic::Freenode with Perl::Critic::Community

lib/OpenQA/Schema/Result/ScheduledProducts.pm, lib/OpenQA/Schema/ResultSet/Jobs.pm, t/05-scheduler-cancel.t
* Add the ID of the new scheduled product that is obsoleting jobs as reason so we know whether a job has been canceled due when scheduling a product and by which
* Improve and extend test code, e.g. fix wrong 'two jobs cancelled …' when it should be 'three …'
* See https://progress.opensuse.org/issues/174583
=> Track the relevant scheduled product when a job is obsoleted

profiles/apparmor.d/usr.share.openqa.script.worker
Ticket: https://progress.opensuse.org/issues/176049
=> Allow openQA worker to execute check_qemu_oom script in apparmor

lib/OpenQA/Git.pm, t/14-grutasks-git.t, t/16-utils-runcmd.t
There can be situations where git needs credentials and prompts the user,
* Trying to push to via http
* Trying to push via ssh but without having a key, or a key with a passphrase
* Trying to fetch from a private repo via http or ssh
This does not make sense in automated code and results in a hanging process
waitign for input.
We can prevent a prompt by setting the following two variables:
https://git-scm.com/docs/git#Documentation/git.txt-codeGITASKPASScode
`GIT_ASKPASS`
> If this environment variable is set, then Git commands which need to acquire
passwords or passphrases (e.g. for HTTP or IMAP authentication) will call this
program with a suitable prompt as command-line argument and read the password
from its STDOUT. See also the core.askPass option in git-config[1]. …
=> Prevent git from prompting for credentials

docs/Installing.asciidoc
Issue: https://progress.opensuse.org/issues/174592
I will add a link to this documentation to the needle admin error message in a followup PR.
This will take a bit more time because we don't have low level unit tests for needle admin yet. (edit: actually we have, but I will do a followup PR)
=> Add docs about automatically using git ssh urls for pushing

lib/OpenQA/Utils.pm
$stdout_err seems left over from some previous refactoring or something.
=> Remove unused param from run_cmd_with_log_return_error

lib/OpenQA/WebAPI.pm, t/03-auth.t
* Allow unauthorized access to `/tests/…/asset/…` even when `[auth] require_for_assets = 1` is configured because this route never returns any assets itself; it just redirects to `/assets/…` which will still require authorization
* Allow making exceptions for authorized asset downloads on reverse proxy level without having to take `/tests/…/asset/…` into account as well
* See https://progress.opensuse.org/issues/175902
=> Avoid restricting `/tests/…/asset/…` needlessly

lib/OpenQA/Git.pm, t/14-grutasks-git.t, t/16-utils-runcmd.t
Issue: https://progress.opensuse.org/issues/174592
todo: catch stderr output in test
=> Add link to docs if git push failed

lib/OpenQA/Resource/Jobs.pm, lib/OpenQA/Schema/Result/Comments.pm, lib/OpenQA/Schema/Result/Jobs.pm, lib/OpenQA/Shared/Plugin/Gru.pm, t/05-scheduler-full.t, t/api/04-jobs.t, t/lib/OpenQA/Test/Utils.pm
When restarting openQA jobs, additional Minion jobs are enqueued (of
`git_clone` task, this is happening especially often when `git_auto_clone`
is enabled). So far this didn't happen in a transaction. So the scheduler
might see the openQA jobs but not the Minion jobs they are blocked by. This
is problematic because the scheduler might assign jobs too soon to a
worker. This is especially problematic if it does not happen consistently
across a parallel job cluster as it then breaks the
`PARALLEL_ONE_HOST_ONLY=1` feature.
Related ticket: https://progress.opensuse.org/issues/169342
=> Fix enqueueing of Minion jobs breaking `PARALLEL_ONE_HOST_ONLY=1`

etc/openqa/openqa.ini, lib/OpenQA/Setup.pm, lib/OpenQA/WebAPI/Auth/OAuth2.pm, t/03-auth.t, t/config.t
Resubmit of https://github.com/os-autoinst/openQA/pull/6154 rebased on current master to trigger codecov coverage report generation.
=> Support OpenID Connect better in the OAuth2 'custom' provider including codecov trigger

docs/Installing.asciidoc, lib/OpenQA/Worker/Engines/isotovideo.pm, t/24-worker-engine.t, t/data/openqa/share/factory/hdd/symlink.qcow2
This is useful when having site-local cache shared among several worker
hosts. See added documentation for scenario details.
Question: Should this setting be also exclusive to workers.ini, similar to `GENERAL_HW_CMD_DIR` and few others?
=> Add SYNC_ASSETS_HOOK support

lib/OpenQA/Worker/Job.pm
SYNC_ASSETS_HOOK was added in #6131
Since it is a setting supposed for the workers.ini, we should disallow it in the job settings.
=> Restrict SYNC_ASSETS_HOOK to worker settings

lib/OpenQA/WebAPI/Controller/File.pm, t/ui/07-file.t
* Add `X-Content-Type-Options: nosniff` to avoid a download prompt on plain text files with Chromium
* See https://stackoverflow.com/questions/9660514/content-type-of-text-plain-causes-browser-to-download-of-file/9660578#9660578
=> Prevent download prompt on plain text files with Chromium

lib/OpenQA/Script/CloneJob.pm, t/35-script_clone_job.t
Issue: https://progress.opensuse.org/issues/176886
WORKER_CLASS:wsl2-main+systemd=...
was resulting in an error.
This change allows plus signs in test names now, but not at the beginning or
end. It also forbids minus signs at the beginning or end.
=> Allow plus signs in test names for scope settings

templates/webapi/branding/openSUSE/external_reporting.html.ep
Enterprise was removed from this product starting in 6.0
https://progress.opensuse.org/issues/176979
=> Update product name for SUSE Linux Micro

lib/OpenQA/Schema/Result/ScheduledProducts.pm, lib/OpenQA/Schema/ResultSet/Jobs.pm
**Avoid nested transaction when creating jobs from settings**
The transaction in the function `create_from_settings` was introduced by
https://github.com/os-autoinst/openQA/commit/b03aa8d6c68eb631151243d2f262dbdd8471625e. At this point this function was likely not always called within
`txn_do`. It is now, though. So I suppose this extra nested transaction is
not useful anymore.
This nested transaction also doesn't act as a useful save point as the
errors we saw in https://progress.opensuse.org/issues/177048 indicate.
---
**Use a proper save point when creating jobs from settings**
The nested transaction that was previously used did not lead to a sensible
rollback leading to follow-up errors when creating dependencies. This was
presumably the case because all jobs that have been created …
=> Improve error handling when creating jobs from settings

lib/OpenQA/Schema.pm, lib/OpenQA/Schema/Result/ScheduledProducts.pm, lib/OpenQA/WebAPI/Controller/API/V1/Job.pm, t/15-assets.t
* Retry the transaction for creating jobs (when a single set of jobs is posted or when a product is scheduled) in case of a deadlock (as it is hard to ensure a consistent order to prevent deadlocks from happening in the first place)
* Add test provoking deadlocks when registering assets on job creation
* Mark certain statements as uncoverable to avoid inconsistent test coverage as the test is only able to reproduce deadlocks *almost* always
* See https://progress.opensuse.org/issues/177048
=> Avoid errors about deadlocks

script/client, script/openqa-clone-job, script/openqa-dump-templates, script/openqa-load-templates, script/worker
It has been in perl core since 5.6:
http://perlpunks.de/corelist/mversion?module=Pod%3A%3AUsage
=> scripts: Rely on Pod::Usage being installed

script/openqa-dump-templates
The output file in JSON format is now reproducible, because all keys will be sorted before the JSON file is written.
The JSON spec states that objects are unordered, but for the purpose of storing the JSON version of the dump in a VCS it helps that the difference between consecutive commits is minimal.
=> openqa-dump-templates: Reproducible output

t/05-scheduler-full.t
This might help with workers being forcefully terminated leading to test failing with:
```
not ok 36 - sub process openqa-worker-unstable terminated with exit code 9
```
Related ticket: https://progress.opensuse.org/issues/177775
=> Reduce resource usage of fullstack scheduler test in CI

docs/GettingStarted.asciidoc, etc/openqa/openqa.ini, lib/OpenQA/Setup.pm, t/04-scheduler.t, t/05-scheduler-dependencies.t, t/05-scheduler-full.t, t/05-scheduler-restart-and-duplicate.t, t/09-job_clone.t, t/config.t, t/lib/OpenQA/Test/Utils.pm
* Reapply "Enable automatic updates of test code and needles by default" (commit 40ae05a38ed2ee6c686eba7fde715a04cb00e33e) again after fixing problems with scheduling and restarting of parallel clusters
* See https://progress.opensuse.org/issues/168379
=> Enable auto updates of tests/needles by default again

dependencies.yaml, dist/rpm/openQA.spec
The requirement for os-autoinst < 5 was introduced within 757cdbd1a for
no apparent reason. We can just get rid of this to allow to pull in the
new os-autoinst.
=> Allow os-autoinst >= 5

Makefile, t/lib/CoverageWorkaround.pm
See https://metacpan.org/pod/Feature::Compat::Try#COMPATIBILITY-NOTES and https://rt.cpan.org/Transaction/Display.html
We are already seeing this warning in some tests: https://app.circleci.com/pipelines/github/os-autoinst/openQA/15835/workflows/04b2d0e0-d43c-4b80-a064-36ef5bcfcda7/jobs/152282 because Feature::Compat::Try is used indirectly
Issue: https://progress.opensuse.org/issues/176862
Thanks @wchristian for this patch!
=> coverage: Avoid B::Deparse warning with Syntax::Keyword::Try::Deparse

lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
This is exploring some ideas to refactor WebAPI::Controller::API::V1::JobTemplate
based on what we discussed for
* #6199
* #6183
Individual changes
* Use function pointer in JobTemplate method
* Extract method from WebAPI::Controller::API::V1::JobTemplate::update
* Extract method in WebAPI::Controller::API::V1::JobTemplate
* Use proper big-comma style WebAPI::Controller::API::V1::JobTemplate
* Use signatures in WebAPI::Controller::API::V1::JobTemplate
=> Simplify WebAPI::Controller::API::V1::JobTemplate

docs/WritingTests.asciidoc
* Explain relevant variables
* Improve formatting of list in section about logging package versions
* Mention the behavior of the restart button with regard to reproducibility
* Mention `openqa-investigate`
* See https://progress.opensuse.org/issues/173878
=> Document traceability and reproducibility of tests

lib/OpenQA/Jobs/Constants.pm, lib/OpenQA/Schema/ResultSet/Jobs.pm, public/schema/JobScenarios-01.yaml, public/schema/JobTemplates-01.yaml, t/api/04-jobs.t, t/api/08-jobtemplates.t, t/data/job-templates/schema-invalid.yaml
* Use the same regex we already use when validating the YAML schema for job templates
* See https://progress.opensuse.org/issues/177267
=> Validate the test name when creating new jobs

dist/rpm/openQA.spec
As of version 1.1.0 `local-npm-registry` always invokes `npm` with `--no-package-lock`. This means we no longer need to clean up `package-lock.json` and also must not do it because the file will otherwise be missing later on. This change adds the `--no-package-lock` explicitly so we get the same behavior regardless of the `local-npm-registry` version.
Related ticket: https://progress.opensuse.org/issues/177901
=> Adapt use of `local-npm-registry` to version 1.1.0

dist/rpm/openQA.spec, etc/openqa/openqa.ini, lib/OpenQA/Git.pm, lib/OpenQA/Needles.pm, lib/OpenQA/Schema/Result/Needles.pm, lib/OpenQA/Setup.pm, lib/OpenQA/Shared/Plugin/Gru.pm, lib/OpenQA/Task/Needle/LimitTempRefs.pm, lib/OpenQA/Utils.pm, lib/OpenQA/WebAPI/Controller/File.pm, lib/OpenQA/WebAPI/Controller/Step.pm, script/openqa-enqueue-needle-ref-cleanup, systemd/openqa-enqueue-needle-ref-cleanup.service, systemd/openqa-enqueue-needle-ref-cleanup.timer, t/14-grutasks.t, t/16-utils-runcmd.t, t/21-needles.t, t/config.t
This is a limited part of https://github.com/os-autoinst/openQA/pull/5175
taken out to go step by step.
The needle version is only read from vars.json and only supports hashrefs - no branches/tags.
Network interaction by git on showing a needle is limited to the absolute minimum.
Also the needle editor is not changed, yet.
Ticket: https://progress.opensuse.org/issues/162035
=> Show correct needle versions in test result step matches

lib/OpenQA/Schema.pm, t/lib/OpenQA/Test/Database.pm, t/ui/01-list.t, t/ui/10-tests_overview.t, t/ui/12-needle-edit.t, t/ui/13-admin.t, t/ui/14-dashboard-parents.t, t/ui/15-admin-workers.t, t/ui/15-comments.t, t/ui/16-activity-view.t, t/ui/16-tests_dependencies.t, t/ui/16-tests_job_next_previous.t, t/ui/17-product-log.t, t/ui/18-tests-details.t, t/ui/21-admin-needles.t, t/ui/26-jobs_restart.t
Within our Makefile we had the default database path "/dev/shm/tpg" which is
used to create a temporary test database. When calling "prove" or just the test
modules as Perl applications it was necessary to have TEST_PG_PATH exported in
the calling environment. Instead we can set the default already in our test
code and inform the caller if the database can not be found. This allows to
save some time during development by calling a quicker bare "prove" without
needing to rely on make all the time.
Instead of the previous message
```
skipped: set TEST_PG to e.g. "DBI:Pg:dbname=test" to enable this test
```
this will provide a more verbose message, something like
```
DBIx::Class::Storage::DBI::catch {...} (): DBI Connection failed: DBI connect('dbname=openqa_test;host=/dev/shm/tpg','',...) …
```
=> Enable prove to run tests relying on default test database

lib/OpenQA/Schema/Result/ScheduledProducts.pm
The line itself is actually covered, just that the if isn't always true.
Seen during working on https://progress.opensuse.org/issues/176862
=> Remove uncoverable comment from one statement

lib/OpenQA/WebSockets/Controller/Worker.pm
Part of a small refactoring, and as per the openqa intention to move to signatures prototype.
=> Use signatures in WebSockets/Controller/Worker.pm

lib/OpenQA/WebAPI/Auth/OAuth2.pm
The fb002508a commit introduced usage of 'id_from' config parameter. And
while the commit messsage says it defaults to the old value 'id', in
fact the parameter is set only for the custom provider, and in all the
other cases it isn't included in $provider_config at all.
Fix this by having default/fallback value also where the variable is
actually used, thus avoiding the need to set it in every supported
provider.
This un-breaks authentication via Github, among other things.
Fixes: fb002508a "Support OpenID Connect better in the OAuth2 'custom' provider"
=> Fix non-custom OAuth2 providers

lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm, lib/OpenQA/WebSockets/Controller/Worker.pm
=> Replace Try::Tiny from remaining OpenQA modules

lib/OpenQA/WebAPI/Plugin/AMQP.pm
* Ignore non-existing jobs when trying to emit an AMQP event
* This can happen when the job has been deleted meanwhile, e.g. via the API or during cleanup. It makes no sense to emit e.g. a `job_done` event when the job has already been deleted anyway.
* This can also happen on concurrent deletions where one event is enough.
* Treat non-existing jobs similar to non-existing comments which we already ignore
* Avoid error observed in https://progress.opensuse.org/issues/178126
=> Avoid error when emiting an AMQP job event when the job does not exist

t/ui/01-list.t
* Use `wait_for_ajax` to wait for the server-side table like in other places of the same test
* See https://progress.opensuse.org/issues/178315
=> Fix unstable UI test of result filter

lib/OpenQA/Needles.pm, lib/OpenQA/Utils.pm
Calling some tests with ./ in front would make the tests fail because
OPENQA_BASEDIR was set to ./t/data/...
make test TESTS=./t/14-grutasks.t HEAVY=1
make test TESTS=./t/21-needles.t
Issues:
* https://progress.opensuse.org/issues/178177
* https://progress.opensuse.org/issues/178180
=> Improve path handling for needles and OPENQA_BASEDIR

tools/unstable_tests.txt
The test ran [200 times successfully in a row on CircleCI](https://github.com/os-autoinst/openQA/pull/6255#issuecomment-2703792827) after 0b4f441 so it seems stable now.
Related ticket: https://progress.opensuse.org/issues/178315
=> Consider `t/ui/01-list.t` stable again after 0b4f441

t/lib/OpenQA/SeleniumTest.pm, t/ui/10-tests_overview.t
This test sometimes runs into:
```
getElementText: stale element reference: stale element not found at /home/squamata/project/t/ui/../lib/OpenQA/SeleniumTest.pm:77 at /home/squamata/project/t/ui/../lib/OpenQA/SeleniumTest.pm line 80.
OpenQA::SeleniumTest::__ANON__(Test::Selenium::Chrome=HASH(0x561a52552560), "Error while executing command: getElementText: stale element "..., HASH(0x561a528c1030)) called at /usr/lib/perl5/vendor_perl/5.26.1/Selenium/Remote/Driver.pm line 356
Selenium::Remote::Driver::catch {...} ("Error while executing command: getElementText: stale element "...) called at /usr/lib/perl5/vendor_perl/5.26.1/Try/Tiny.pm line 123
…
Selenium::Remote::WebElement::_execute_command(Test::Selenium::Remote::WebElement=HASH(0x561a528b82b0), HASH(0x561a528c1030)) called at …
```
=> Fix sporadic test failure in `t/ui/10-tests_overview.t`

t/lib/OpenQA/SeleniumTest.pm, t/lib/OpenQA/Test/Utils.pm
To be consinstence with the rest of the project, module in the test library have to use also try/catch block. This commit should complete the "migration" to Feature::Compat::Try wherever was applicable.
=> Use of Feature::Compat::Try in the test libraries

t/ui/21-admin-needles.t
* Wait for intermediate state when selecting options to minimize the chance for a race condition leading to sometimes observing the intermediate state in further checks (and thus failing the test)
* See https://progress.opensuse.org/issues/167611#note-6
=> Avoid race condition in `t/ui/21-admin-needles.t`

lib/OpenQA/WebAPI/Plugin/AMQP.pm, t/23-amqp.t
See https://progress.opensuse.org/issues/178147
=> Include IDs in error message when sending AMQP message fails

lib/OpenQA/Parser/Format/XUnit.pm, t/30-test_parser.t
The test case result was not properly set. This fixes it.
- Related ticket: [poo#177321](https://progress.opensuse.org/issues/177321)
- Related pull request: os-autoinst/os-autoinst-distri-opensuse#21304
- Previous pull request: #6227
=> Fix XUnit parser softfail scenario

t/10-tests_overview.t, templates/webapi/test/overview.html.ep
The previous wording for example "from 2 days ago" could be understood
as showing jobs starting 2 days ago until now. This commit changes the
wording to make it clear that we mean jobs until that specified
timestamp. So in the above example the text would say "at the time of 2
days ago".
=> Improve "from" time label in /tests/overview

lib/OpenQA/Setup.pm, t/config.t
See
* https://uapi-group.org/specifications/specs/configuration_files_specification/
* https://en.opensuse.org/openSUSE:Packaging_UsrEtc
The .d/ directory must be in the same directory as the .ini/.conf file
and use the complete name of the overridden config file path including
extension.
As the drop-in config directory is not documented yet and only has
implementation we should be ok to just change that :)
Related progress issue: https://progress.opensuse.org/issues/179359
=> Fix config drop-in path to upstream specifications

dist/rpm/openQA.spec, lib/OpenQA/Setup.pm, t/config.t
Alternative to https://github.com/os-autoinst/openQA/pull/6323 that avoids the symlinking completely.
---
* Read config files directly from `/etc/openqa` if the config directory
doesn't exist under `OPENQA_CONFIG` or the app home
* Keep reading from `OPENQA_CONFIG` and the app home if a config directory
exists under those locations as this is useful for development setups and
running unit tests
* Read config files from `/usr/etc/openqa` if no config directory exists
under any of the other locations to support
https://en.opensuse.org/openSUSE:Packaging_UsrEtc#Variant_1_(ideal_case)
* Remove symlinks in our packaging so an installation from packages will in
fact use all the files from `/etc/openqa` or `/usr/etc/openqa` and not be
stuck with an only partially symlinked config
* See …
=> Make loading nested config files work with our RPM packaging (no symlink)

dist/rpm/openQA.spec, lib/OpenQA/Setup.pm, t/config.t
Reverts os-autoinst/openQA#6324 as it broke the o3 deployment.
=> Revert "Make loading nested config files work with our RPM packaging (no symlink)"

t/ui/14-dashboard.t, templates/webapi/main/more_builds.html.ep
dashboard provides filter for limits and tags.
`url_with` extends the query when options are selected. Which creates a long queries like `?limit_builds=20&only_tagged=1&only_tagged=0&limit_builds=10`. Ideally it should have unique entries with clear a clear query as described in the documentation https://docs.mojolicious.org/Mojolicious/Controller#url_for and seems like it needs a hash instead of a list. This updates the current request as expected.
=> Update url query only with the selected option

dist/rpm/openQA-client-test.spec, dist/rpm/openQA-devel-test.spec, dist/rpm/openQA-test.spec, dist/rpm/openQA-worker-test.spec
https://build.opensuse.org/requests/1256193 was declined with 'does not
appear to have a license. The file needs to contain a free software
license'. This commit takes over mostly what "osc service runall
format_spec_file" adds automatically with exception of the "(c) 2025"
which is not strictly needed and I would like to avoid. If it turns out
to be necessary after all then we should add it later on.
=> dist: Add headers expected by OBS checks

lib/OpenQA/Worker.pm, t/24-worker-overall.t, t/lib/OpenQA/Test/Utils.pm
Just like we do not abort running jobs due to high load we should also avoid interrupting directly chained jobs due to high load as this will be rather disturbing.
Note that directly chained dependencies were added to support bare-metal backends like IPMI where one cannot easily upload/reuse use HDD images. The check for the load was on the other hand introduced specifically for VM-based backends where high load leads to typing and other issues. So considering the high load check non-fatal for directly chained dependencies is not a problem.
Related ticket: https://progress.opensuse.org/issues/179545
=> Avoid interrupting/skipping directly chained jobs due to high load

dist/rpm/openQA.spec, docs/Contributing.asciidoc, lib/OpenQA/Config.pm, lib/OpenQA/Schema.pm, lib/OpenQA/Setup.pm, lib/OpenQA/UserAgent.pm, script/initdb, script/upgradedb, t/config.t
* Read config files directly from `/etc/openqa` if the config directory
doesn't exist under `OPENQA_CONFIG` or the app home
* Keep reading from `OPENQA_CONFIG` and the app home if a config directory
exists under those locations as this is useful for development setups and
running unit tests
* Read config files from `/usr/etc/openqa` if no config directory exists
under any of the other locations to support
https://en.opensuse.org/openSUSE:Packaging_UsrEtc#Variant_1_(ideal_case)
* Remove symlinks in our packaging so an installation from packages will in
fact use all the files from `/etc/openqa` or `/usr/etc/openqa` and not be
stuck with an only partially symlinked config
* See https://progress.opensuse.org/issues/179425
* See https://progress.opensuse.org/issues/179359
=> Make loading nested config files work with RPM packaging (2nd attempt)

docs/Contributing.asciidoc, t/test_postgresql
As we already use /dev/shm/tpg mostly everywhere we can simplify the
call to t/test_postgresql by creating the temporary database in the same
path by default. This way to manually execute tests relying on a
database one can just call "t/test_postgresql && prove -l …".
=> Use consistent temporary database path

lib/OpenQA/Config.pm, lib/OpenQA/Schema.pm, lib/OpenQA/Setup.pm, lib/OpenQA/Worker/Settings.pm, script/initdb, script/upgradedb, t/24-worker-settings.t, t/deploy.t
* Locate the worker config just like the web UI and client config files to support
* Locating the config under `/usr/etc`
* Drop-in configuration files
* Reading the config file from the Git checkout for development without having to set `OPENQA_CONFIG`
* See https://progress.opensuse.org/issues/179359
---
There's no ticket for this but when working on https://progress.opensuse.org/issues/179359 I noticed that I would have to weirdly exclude the worker config from Makefile/specfile/documentation changes. So it make sense to bring the worker in-line with everything else first.
=> Support all config features for `workers.ini` as well

t/03-auth.t, t/43-cli-archive.t, t/api/04-jobs.t
Follow-up of: https://progress.opensuse.org/issues/178207
=> Avoid hardcoding of /tmp to ensure compatibility with different environments. 

lib/OpenQA/Utils.pm
* Use more signatures in OpenQA::Utils
* Simplify Utils::get_url_short
* Use signatures in Utils::get_url_short
=> Use more signatures in OpenQA::Utils and simplify

lib/OpenQA/Task/Asset/Download.pm
Simlar to cd99074a to prevent download_asset running
into `Job terminated unexpectedly`
https://progress.opensuse.org/issues/108980
=> Use the signal guard on download_asset

systemd/openqa-reload-worker-auto-restart@.path
With this the worker is also reloaded when drop-in config files are changed, when config files under `/usr/etc` are changed and when the client config is changed.
I tested locally whether this works for directories and it does. So the worker is reloaded when drop-in config files are added, changed or removed.
=> Consider all config files in unit for auto-reloading workers

Makefile
The retry commit is now possible to rever thanks to the merged pr of Dominik Heidler #2676
This will revert the changes made by prs that mitigate the problem: #6244 and #6115
related: https://progress.opensuse.org/issues/175060
=> Rollback retries applied for full-stack test preventing ci from failing

dist/rpm/openQA.spec
Otherwise changes to the AppArmor profile are only available after a manual restart of the service.
=> Restart AppArmor service when updating workers

Makefile, dist/rpm/openQA.spec, usr/lib/sysctl.d/01-openqa-reload-worker-auto-restart.conf
After recent changes to the path units more inotify watches are requires. The default limit is quite low (at least on openSUSE) so we need to put a higher limit in place.
=> Ensure `…-restart@.path` units don't run into inotify limit

assets/javascripts/audit_log.js
Additionally to the JSON pre-formatted dump, the hyperlinks to the tests are shown. This allows for a bi-directional linking from job to product_log.
=> Bidirectional links for /admin/productlog

docs/GettingStarted.asciidoc
I missed this when adding the drop-in config files in this list.
=> Mention drop-in config file for worker like for the other config files

templates/webapi/main/group_builds_functionality_view.html.ep
The parent_group_overview says `No builds` when the limit_builds are exceeded
as part of another group. However this leads to confusion. For now, try just
to provide a better explaination.
https://progress.opensuse.org/issues/179296
=> Change text body on build absent in parent_group_overview

lib/OpenQA/Git/ServerAvailability.pm, lib/OpenQA/Task/Git/Clone.pm, t/14-grutasks-git.t
Introduce git service outage handler module
This commit creates a outage handling mechanism which allows for smaller gitlab outages to be ignored while prolonged outages still cause a failure as they did before.
Related Issue: https://progress.opensuse.org/issues/179038
=> Ignore short Git service outages

dist/rpm/openQA.spec
As suggested by darix in SR:
> do not restart apparmor during update, you want
> `%apparmor_reload /etc/apparmor.d/yourprofile`
(see https://build.opensuse.org/request/show/1268562)
=> Reload only specific AppArmor profiles on updates

lib/OpenQA/Schema/Result/ScheduledProducts.pm, lib/OpenQA/Schema/ResultSet/Jobs.pm, t/39-scheduled_products-table.t
After adding a retry on deadlocks the function that inserts the jobs into the database might run multiple times. Hence it must not delete the group ID setting (or any other settings) from the previously computed hash. This change deletes the group ID only within `create_from_settings` which only works on a copy of the settings.
Related ticket: https://progress.opensuse.org/issues/180020
=> Fix jobs sometimes ending up without group after retry on deadlocks

dist/rpm/openQA.spec
The config is not required because Tumbleweed has it anyway. So this file only needs to be packaged for Leap where no security review is required.
Security review/ticket: https://bugzilla.suse.com/show_bug.cgi?id=1241146
=> Avoid security review by not packaging sysctl config for Tumbleweed

lib/OpenQA/Schema/Result/ScheduledProducts.pm, lib/OpenQA/Task/Iso/Schedule.pm, lib/OpenQA/WebAPI/Controller/API/V1/Iso.pm, t/39-scheduled_products-table.t
Similar to cd99074 to prevent `Job terminated unexpectedly` on results. This ensures that the minion job will retry in case of interruptions, like network glitch in the system, without kill the process.
https://progress.opensuse.org/issues/108983
=> Add signal guard for schedule_iso minion tasks

lib/OpenQA/WebSockets.pm, lib/OpenQA/WebSockets/Controller/API.pm, lib/OpenQA/WebSockets/Controller/Worker.pm, lib/OpenQA/Worker/CommandHandler.pm, lib/OpenQA/Worker/WebUIConnection.pm, t/24-worker-webui-connection.t
This worked for me when testing it locally with 1500 workers with the database on a very slow HDD. The performance was still not optimal as it took a while until all workers were connected. I also only had up to 100 jobs running in parallel. However, this is a huge improvement to before where no jobs were assigned anymore at all.
See individual commit messages and https://progress.opensuse.org/issues/168178 for details.
=> Improve scalability

dist/rpm/openQA.spec, script/dump-db
Carbon copy of https://github.com/os-autoinst/sync-and-trigger/blob/2b891a67d7509aa589ac108f594d3235826f5ba9/dump-psql
Related issue: https://progress.opensuse.org/issues/181301
It would make sense to include this script here ~(and later package it as part of the [`openQA-local-db`-package](https://build.opensuse.org/projects/devel:openQA/packages/openQA/files/_service:obs_scm:openQA.spec?expand=1))~. I know there is a lot of improvement possible but for now I went with a pure copy to better trace the history of this script in the future.
=> Move database dump script

script/dump-db
This runs the database backup with lower IO and CPU priority thus impacting the system less for users while a backup is running.
This is what openqa.suse.de is using - a openQA instance which is a little more loaded so it might make sense to include it by default in our script here as well.
=> Add nice and ionice to dump-db script

script/dump-db
With the recently added bash restrictions the help text function has to be adjusted to not cause a "unbound variable" error on normal invocation because $1 is unbound without any arguments. Unlike `:-`, this only sets $1 to an empty value if unset.
=> Avoid unbound variable error in dump-db script

docs/Installing.asciidoc, etc/openqa/openqa.ini, lib/OpenQA/Schema/Result/Needles.pm, lib/OpenQA/Setup.pm, lib/OpenQA/Shared/Plugin/Gru.pm, lib/OpenQA/Task/Git/Clone.pm, lib/OpenQA/Task/Needle/Save.pm, lib/OpenQA/Utils.pm, lib/OpenQA/WebAPI/Controller/Step.pm, t/14-grutasks-git.t, t/21-needles.t, t/api/04-jobs.t, t/config.t
This is my attempt to resolve the issues I found diving into the `git_auto_update` and `git_auto_clone` stuff, which is new to me (haven't updated Fedora's openQA since last year). See https://github.com/os-autoinst/openQA/pull/6039#issuecomment-2845218269 for the notes that led me to this.
Most importantly, this attempts to disable all git cloning shenanigans if the global config section does not have `scm = git`, because the older automatic-needle-commit feature kinda establishes that expectation. Beyond that, we add a `git_auto_commit` setting so you can have autoclone and/or autoupdate enabled without autocommit, and try to disentangle `git_auto_clone` and `git_auto_update` so you can have `auto_update` working fully without `auto_clone` (which I don't think is currently possible).
=> Block all distri git operations unless `scm = git` is set, add `git_auto_commit` setting, disentangle `git_auto_clone` and `git_auto_update`

docs/Installing.asciidoc, etc/openqa/openqa.ini, lib/OpenQA/Schema/Result/Needles.pm, lib/OpenQA/Setup.pm, lib/OpenQA/Shared/Plugin/Gru.pm, lib/OpenQA/Task/Git/Clone.pm, lib/OpenQA/Task/Needle/Save.pm, lib/OpenQA/Utils.pm, lib/OpenQA/WebAPI/Controller/Step.pm, t/14-grutasks-git.t, t/21-needles.t, t/api/04-jobs.t, t/config.t
Reverts os-autoinst/openQA#6414 due to unexpected change of default behaviour. I tried to ensure that git auto-clone+update are still enabled by default with #6421 by setting the global config key `scm` by default to `git` however that also means that automatic git commits of needles are enabled. #6414 introduced a new config for automatic git commits but disabling that by default also breaks compatibility with existing instances so I see no better option than to fully revert #6414
=> Revert "Block all distri git operations unless `scm = git` is set" due to unexpected change of default behaviour

lib/OpenQA/Worker/Job.pm
Apparently not all variables are always initialized as we sometimes get the following warning in tests:
```
Use of uninitialized value in numeric ne (!=) at /home/squamata/project/script/../lib/OpenQA/Worker/Job.pm line 770.
```
We can probably ignore this warning and consider the test schedule changed anyway which is what this change does.
Related ticket: https://progress.opensuse.org/issues/181760
=> Avoid potential warning when checking whether the test order has changed

Makefile, dist/rpm/openQA.spec
Only etc/openqa is intended to be used by users. If distributors want
to put things into usr/etc then the according directories should only be
created in the according places but not during generic installation to
prevent problems like distribution specific requirements for such
folders.
This fixes a problem with "ostree" as reported by AdamWill.
Related to
https://progress.opensuse.org/issues/179359#note-33
=> Makefile: Create config folder template only where to be used by users

lib/OpenQA/WebAPI/Auth/OAuth2.pm
I'm setting up oauth2 auth for Fedora ATM (up till now we used OpenID auth, but we're shutting that off). One problem I hit was that this redirect URI generation used the wrong hostname. Our staging instance is at https://openqa.stg.fedoraproject.org. The machine that serves it has the hostname
openqa-lab01.iad2.fedoraproject.org. The redirect_uri was using the machine's hostname, so it was coming out as
https://openqa-lab01.iad2.fedoraproject.org/login , which is not going to work.
This tweaks the redirect URI generation to use the hostname from the openQA config base_url, if it's set. If not, it falls back to the hostname from the request.
=> oauth2: use openQA base_url to create redirect URI if set

t/22-dashboard.t, templates/webapi/branding/openqa.suse.de/commenting_tools.html.ep
This was brought up by colleague Ricardo Branco who expected the button
for the template text. Thanks Ricardo!
=> Render the SUSE "review:acceptable_for" button on overview as well

Makefile, dist/rpm/openQA.spec, lib/OpenQA/Git/ServerAvailability.pm
* Use the usual `webui` sub directory where the web UI services already
have write permissions
* Install all relevant dirs under /var/lib/openqa via Makefile, see separate commit for details
* See https://progress.opensuse.org/issues/179038
=> Avoid permission errors when flagging a Git server outage

t/full-stack.t
Issue: https://progress.opensuse.org/issues/182168
I double checked it by setting CRITICAL_LOAD_AVG_THRESHOLD to 0.1 and it failed.
c0c0d8a8dc595d7da33f9e6f5714f565e1eb83d9 did this change in t/data/workers.ini, but here full-stack.t uses a different file
=> Ensure fullstack tests run even under high load

lib/OpenQA/Task/Git/Clone.pm
* Retry `git_clone` tasks on `SIGTERM` like we do in many other tasks
* See https://progress.opensuse.org/issues/179885
=> Avoid `git_clone` tasks failing with `Job terminated unexpectedly`

t/10-jobs.t
Mainly to verify the state of tests in the default branch.
See: https://github.com/os-autoinst/openQA/pull/6415#issuecomment-2879486482
=> Fix phrasing in jobs comment carry over unit test

script/openqa-load-templates, t/40-script_load_dump_templates.t
When running load-templates --clean, for any job group with a non-empty YAML template string, we should write an empty one (one that defines no scenarios or products). This is most in line with the intended behavior of --clean - to wipe all existing job configuration before loading the data.
We should also clean JobGroups before everything else, otherwise we will often choke on "must be updated through the YAML template" when trying to delete something that openQA realizes is referenced in an existing YAML template string.
This is different from existing behavior if job groups exist that are not included in the data being loaded. Previously we would leave those alone (and probably choke on the error, if they defined any templates). Now, we will 'empty' those groups, and load the data …
=> load-templates: with --clean, empty job group YAML templates

Makefile, docs/Contributing.asciidoc, tools/run-tests-within-container
- Rename to the corresponding phony command in the run-tests-within-containe
- replace tests_failed with a variable flag
- Add note in the documentation for transparency of CONTAINER_TEST impact
- Remove deprecated TRAVIS variable
I hope those changes provide a small improvement. if you run now `podman run --rm -v /home/iob/openqadev/openQA/:/opt/openqa -e CHECKSTYLE=1 -e CONTAINER_TEST=0  openqa_devel:latest make run-tests-within-container` it should run successfully the checkstyle tests. CONTAINER_TEST will still be required as by default is enabled and this didnt change. hopefully the documentation makes this a bit obvious
=> Update checkstyle invocation in run-tests-within-container script

tools/run-tests-within-container
the script expands the ${PROVE_ARGS} to an empty string after --lib which breaks the prove execution.
=> Fix quoting issue in run-tests-within-container script

lib/OpenQA/Script/CloneJob.pm, script/openqa-clone-job
--skip-checks option was disabling opt out checks of maintenance updates repositories.
This has several flaws:
1. It is questionable how much common situation from which check is trying to protect,
so it make sense to invert logic to opt in allowing user to decide whether they need it
or not
2. Only check currently covered by this option is SUSE specific and it is another reason
to switch to opt in
3. skip-checks is confusing name because in a fact there is one and only check of maintenance
repositories
To address this problems two changes were done:
- invert logic from opt out to opt in
- deprecate skip-checks option because it is not needed anymore ( not to do check
from now on is default behavior
- introduce new command line option check-repos which has more accurate
description and …
=> Deprecate skip-checks and add check-repos option

docs/GettingStarted.asciidoc
As noted in https://github.com/os-autoinst/openQA/pull/1229#issuecomment-2687785786 this doc had gotten out of date with how we handle templates now. This updates it to be more-or-less correct (it's still not an awesome doc overall, but oh well).
=> Update GettingStarted.asciidoc Fedora instructions

.obs/workflows.yml
Related progress issue: https://progress.opensuse.org/issues/180737
=> CI: Enable Leap 16.0 OBS build checks

systemd/openqa-websockets.service, systemd/openqa-webui.service
By starting openqa-webui before scheduler+livehandler which are less
time-critical we can increase the availability of openqa-webui which will be
effective on both startup of systems as well as during shutdown when the
openqa-webui is kept around longer after scheduler+livehandler have been
stopped first.
Verified manually on openqa.suse.de
Related progress issue: https://progress.opensuse.org/issues/181370
=> systemd: Increase availability of openqa-webui with ordering

t/ui/18-tests-details.t
* Enable signatures via `use Mojo::Base -signatures`
* Remove "…" as this leads to a warning with `use Mojo::Base -signatures`
* Add checks for whether the candidates menu is present and enabled so in
case the test fails there is better error feedback
* Log present candidate needles in case the corresponding check fails
* Remove unnecessary `if defined $tags`
* See https://progress.opensuse.org/issues/183059
=> Improve details of test details test

docs/WritingTests.asciidoc, lib/OpenQA/Worker/Settings.pm, t/24-worker-settings.t, t/data/24-worker-settings/workers.ini
Related ticket: https://progress.opensuse.org/issues/183101
---
This is so far only introducing list and range specifiers. It doesn't change the overriding behavior. So the behavior is still as follows:
The section `global` is read first. Other sections are read in the order they are defined and values from previous sections are overridden. This is what we want except that it should be possible to concatenate worker classes (instead of overriding). ~~For this I'd go for a `+=` syntax because concatenating by default and only clearing when an empty value occurs would not be backwards compatible/consistent with our current behavior of overriding (even though it only happened between the global and instance-specific section (and perhaps the web UI specific).~~ The `+=` syntax has now been …
=> Allow using list and range specifiers in worker config file

lib/OpenQA/Worker.pm, lib/OpenQA/Worker/WebUIConnection.pm, t/24-worker-webui-connection.t
* Track web socket error individually to be able to clear them in case the
web socket connection could be re-established after all (improving what
the previous commit has already begun)
* Record only failing API errors of critical requests with no retry
attempts remaining as last error (which would later potentially be added
as reason)
* See https://progress.opensuse.org/issues/184022
=> Avoid adding non-fatal API errors as reason of incomplete jobs

profiles/apparmor.d/usr.share.openqa.script.worker
qemu-system-ppc64 needs this for host CPU type determination.
Failure: https://openqa.opensuse.org/tests/5115505
Verification run: https://openqa.opensuse.org/tests/5115519
=> apparmor: Allow read access to device-tree files

script/openqa-bootstrap
We're mainly interested in the http response code but want to follow eventual redirects. To follow these redirects we can use curls `--location`/`-L`-option but this will cause multiple responses (until no redirect is left). Since `--head`/`-I` will always print all headers for all responses, we now need to redirect *everything* to /dev/null and print the actual, last response code with `--write-out`/`-w` only.
=> openqa-bootstrap: Allow curl to follow redirects (boo#1245379)

lib/OpenQA/Log.pm
This broke with recent changes for the config file handling that now require the app singelton to be present when connecting to the database (which is done indirectly by
`OpenQA::Schema::Profiler->enable_sql_debugging`).
=> Fix debugging SQL queries via `OPENQA_SQL_DEBUG`

assets/javascripts/index.js
I tested this locally in Firefox (where the problem is reproducible in contrast do Chromium) with a `sleep` in `dashboard_build_results` to ensure reproducibility. With this change the error is no longer shown when the user is just navigating elsewhere, e.g. clicking on "All tests".
The error is still shown as expected when the web UI is stopped whiel the AJAX request is still ongoing.
Related ticket: https://progress.opensuse.org/issues/185116
=> Avoid showing AJAX	error on index page when user is navigating elsewhere

dist/rpm/openQA.spec
It seems all
https://build.opensuse.org/projects/openSUSE:Leap:16.0/packages/000release-packages/files/Leap-release.spec?expand=1
and
https://build.suse.de/projects/SUSE:SLE-15-SP7:GA/packages/000release-packages/files/SLES-release.spec?expand=1
and
https://build.opensuse.org/projects/openSUSE:Factory/packages/000release-packages/files/openSUSE-release.spec?expand=1
and even something old like
https://build.opensuse.org/projects/openSUSE:Leap:15.3/packages/000release-packages/files/Leap-release.spec?expand=1
provide "distribution-release". So if we require that then we can
simplify our build time dependencies as well as hopefully prevent
further problems in SLE PackageHub.
Related issue: https://bugzilla.opensuse.org/show_bug.cgi?id=1244139
=> dist: Simplify dependency for /etc/os-release (boo#1244139)

lib/OpenQA/Schema/Result/Jobs.pm, lib/OpenQA/Utils.pm, t/10-jobs.t
The code is already mainly just skipping invalid bits. These changes just make the checks for what's considered invalid a bit stricter to avoid Perl warnings and database errors. See the particular commit messages and https://progress.opensuse.org/issues/185497 for details.
=> Improve error handling when handling status updates from worker

script/openqa-clone-custom-git-refspec, t/40-script_openqa-clone-custom-git-refspec.t
I was annoyed by the repeated message that a TODO test was passing:
```
t/40-script_openqa-clone-custom-git-refspec.t           (Wstat: 0 Tests: 45 Failed: 0)
TODO passed:   30, 32
```
Because `test_cmd()` conducts two checks, and only one of them passed, it was not possible to only mark one part of it as `TODO`, so I thought it would be easier to finally implement it.
=> Support short test urls in openqa-clone-custom-git-refspec

lib/OpenQA/Parser/Format/KTAP.pm, t/30-test_parser.t, t/data/ktap_correct.tap, t/data/ktap_incorrect.tap
Progress: https://progress.opensuse.org/issues/182360
VR: https://rmarliere-openqa.qe.prg2.suse.org/tests/1332
This patch introduces a dedicated parser for Linux kernel selftests using the KTAP (Kernel Test Anything Protocol) format.
While KTAP is based on the TAP (Test Anything Protocol) standard, it includes significant extensions tailored for kernel testing. This parser builds on TAP::Parser to handle common TAP elements while providing additional logic to interpret KTAP-specific constructs such as grouped subtests and prefixed comment lines.
For more details on KTAP, see: https://docs.kernel.org/dev-tools/ktap.html
Example output of the ktap test run:
```
TAP version 13
1..13
ok 1 selftests: cgroup: test_core
```
There are group of tests with nested subtests. Each group starts as …
=> parser: Add KTAP parser for handling kernel selftests

lib/OpenQA/Schema/ResultSet/ScheduledProducts.pm, lib/OpenQA/WebAPI.pm, lib/OpenQA/WebAPI/Controller/API/V1/Iso.pm, t/api/02-iso.t
This will allow us to check whether all jobs we scheduled for a certain purpose (e.g. product increment) are done and whether they have passed.
The details of the lookup are explained in the added API documentation.
The query for this is not super efficient as we don't have an index on the required columns on the scheduled products table. However, it seemed to be fast enough when I tested this with production data.
Related ticket: https://progress.opensuse.org/issues/184690
---
This is an alternative to https://github.com/os-autoinst/openQA/pull/6589 which I have started for a hook script based approach. The code is only slightly different, though.
With the approach taken by this PR here we don't need any other changes on the openQA side except for what is provided by the PR right now. …
=> Allow querying the state of scheduled products by distri/version/flavor

lib/OpenQA/Command.pm, t/43-cli-api.t
openqa-cli --apibase ''
did not set the parameter as expected
Issue: https://progress.opensuse.org/issues/186146
Bug introduced in 47c3c7bec
=> Allow empty values in openqa-cli parameters

lib/OpenQA/Setup.pm, lib/OpenQA/WebAPI/Controller/ApiKey.pm, templates/webapi/api_key/index.html.ep
* Remove seconds from the default value so the date time picker is only allowing to select date, hour and minute and will no longer complain about invalid values
* Allow specifying a date time value without seconds in the corresponding API route as removing seconds from the default value would otherwise lead to validation errors
* Note that I could only reproduce the validation errors with Chromium when previously selecting a specific second via the menu of the date time picker; so adding UI tests for this is probably difficult
* See https://progress.opensuse.org/issues/118894
=> Fix weird validation errors of date time on API keys page

lib/OpenQA/WebAPI/Plugin/ObsRsync/Task.pm, t/api/14-plugin_obs_rsync_async.t
Logs remain available, but are not considered actionable in most cases.
See: https://progress.opensuse.org/issues/180962
=> Stop flagging obs_rsync errors as failures

tools/generate-documentation
Pin afm to version 0.2.2
Issue: https://progress.opensuse.org/issues/187266
=> Fix generation of PDF documentation

lib/OpenQA/Shared/Controller/Running.pm, t/26-controllerrunning.t
To prevent `Timer failed: Too few arguments for subroutine`, the `$self` can be removed from the close_connection function because the variable is still accessible within the closure, so it is not needed.
Not directly connected to the issue but related
poo: https://progress.opensuse.org/issues/187014
=> Fix Too few arguments for subroutine error on close_connection

docs/UsersGuide.asciidoc
As per the implementation, important limits are only applied if they are higher than regular limits.
See: https://progress.opensuse.org/issues/187590
=> Document semantics of low limits for important data

Makefile, dist/rpm/openQA.spec, etc/nginx/vhosts.d/openqa-assets.inc, etc/nginx/vhosts.d/openqa-endpoints.inc, etc/nginx/vhosts.d/openqa-locations.inc, etc/nginx/vhosts.d/openqa.conf.template, etc/openqa/openqa.ini, lib/OpenQA/Setup.pm, lib/OpenQA/Shared/Controller/Auth.pm, lib/OpenQA/Shared/Controller/Session.pm, lib/OpenQA/Shared/Plugin/SharedHelpers.pm, lib/OpenQA/WebAPI/Controller/File.pm, t/api/03-auth.t, t/config.t, t/ui/07-file.t
* Based on https://github.com/os-autoinst/openQA/pull/6667 so it makes
most sense to review only the 2nd commit here (after reviewing #6667)
* Allow configuring a redirection to a configurable subdomain
* Update NINGX templates to cover files served directly via NGINX as well
* Move most of `openqa-locations.inc` to a separate file to be able to
include it separately (without asset locations); none of the code in
`openqa-endpoints.inc` is therefore new
* Keep asset location in `openqa-locations.inc` to avoid breaking
too much; this way one can still include `openqa-locations.inc` as
before covering assets and endpoints
* See https://progress.opensuse.org/issues/184456
=> Allow configuring subdomain for serving logs/assets more securely

lib/OpenQA/WebAPI/Plugin/ObsRsync.pm
Related: https://progress.opensuse.org/issues/178948
=> Mark unconfigured api route log as uncoverable statement

etc/nginx/vhosts.d/openqa-locations.inc
This should fix https://progress.opensuse.org/issues/188208 and the [currently failing openqa-in-openqa tests](https://openqa.opensuse.org/tests/5284271/#step/openqa_webui/15).
=> Fix syntax error in nginx config

lib/OpenQA/Client/Archive.pm, lib/OpenQA/Script/CloneJob.pm, t/35-script_clone_job.t
* Avoid running into errors like `can't write /hdd/openqa-devel/openqa/share/factory/hdd` when this directory just doesn't exist; try to create the directory instead
* Keep the `-w $dst_dir` check so one still gets the usual error message when trying to download assets under e.g. `/var/lib/openqa` with a user that cannot write there
* See https://progress.opensuse.org/issues/184909
---
I tested this locally by running `openqa-clone-job` with different users and different `--dir` parameters.
=> Ensure destination dir for asset downloads exists when cloning jobs

lib/OpenQA/Shared/Plugin/Gru.pm, t/14-grutasks-git.t
The exception is misleading as this is expected.
See: https://progress.opensuse.org/issues/188007
=> Stop logging confusing exception when GruTask is gone

lib/OpenQA/Schema/ResultSet/Assets.pm
This is to avoid a race condition where the asset was already registered.
See: https://progress.opensuse.org/issues/188007
=> Use find_or_create when registering assets

contrib/ay-openqa-worker.xml.erb
Related to: https://progress.opensuse.org/issues/186948
This commit introduces an ERB helper template to dynamically generate the AutoYaST profile during OS installation.
Key changes include:
- Automatically selects the smallest disk for OS installation
- Allocates remaining disk(s) for openQA data storage
- Creates a RAID array for openQA data if more than two disks are available
=> Use autoyast ERB helper to detect disk dynamically

lib/OpenQA/Parser/Format/KTAP.pm
Verification runs:
- Before: https://rmarliere-openqa.qe.prg2.suse.org/tests/1555
- After: https://rmarliere-openqa.qe.prg2.suse.org/tests/1556
=> parser: ktap: Don't add skipped subtests to output

t/ui/15-comments.t
It seems that `wait_for_ajax` is not enough here as we sometimes run into this error in the CI:
```
Can't call method "get_attribute" on an undefined value at t/ui/15-comments.t line 328.
```
This change replaces `wait_for_ajax` with `wait_for_element` which will definitely wait until the elements are present.
Related ticket: https://progress.opensuse.org/issues/186092
=> Avoid sporadic test failures in `t/ui/15-comments.t`

lib/OpenQA/WebAPI/Controller/API/V1/Comment.pm
When running `t/ui/15-comments.t` locally with Perl v5.42.0 I run into the following error:
```
[error] [pid:26242] Stopping openqa-webapi process because a Perl warning occurred: DBIx::Class::Storage::TxnScopeGuard::DESTROY(): A DBIx::Class::Storage::TxnScopeGuard went out of scope without explicit commit or error. Rolling back. at /hdd/openqa-devel/repos/openQA/lib/OpenQA/WebAPI/Controller/API/V1/Comment.pm line 144
not ok 2 - sub process openqa-webapi terminated with exit code 42
```
This error is actually just a warning but treated as an error so the test fails.
I probably only run into this locally as it probably only happens with recent versions of Perl. Maybe the reliance on `Feature::Compat::Try` due to the old Perl version we use in the CI (which uses a Leap 15.6 container) …
=> Prevent warning from `DBIx::Class::Storage::TxnScopeGuard`

.mergify.yml
Due to ongoing supply chain attacks it would make sense to put Dependabot PRs at a halt for now. See
https://www.aikido.dev/blog/s1ngularity-nx-attackers-strike-again for the most recent attack.
We should of course also refrain from manually approving these PRs unless we have a really good reason.
=> Temporarily require manual review of Dependabot PRs

lib/OpenQA/Task/Needle/Delete.pm
Reference: https://progress.opensuse.org/issues/183077
=> Prevent abort while doing database interaction in Delete needles

container/openqa_data/Dockerfile
Based on
https://docs.docker.com/reference/build-checks/legacy-key-value-format/ to prevents the warning in the build
=> Fix LegacyKeyValueFormat on openqa_data/Dockerfile

lib/OpenQA/WebAPI/Controller/File.pm, t/ui/07-file.t
This will ensure all assets are served via file_domain if it is set.
Ticket: https://progress.opensuse.org/issues/188226
=> Redirect test assets to file_domain if configured

lib/OpenQA/WebAPI/Plugin/MemoryLimit.pm, t/api/14-plugin_memory_limit.t
Reference: https://progress.opensuse.org/issues/178948
=> Fully Cover OpenQA::WebAPI::Plugin::MemoryLimit

.mergify.yml
This reverts commit 56709e76a5b156c7284596498aea3161ff5229e4.
To me it seems the situation has cooled down. We have reduced our attack
surface with --omit=dev for openQA and have reviewed other practices for
handling updates. In my understanding our previous approach of automated but
slightly delayed updates is still fine.
=> Enable automatic dependabot updates again after improvements

docs/UsersGuide.asciidoc
Formerly on https://progress.opensuse.org/projects/qa/wiki/Core
=> docs: Add instructions for a continuous dashboard setup

README.asciidoc
With
https://github.com/os-autoinst/os-autoinst-distri-openQA/pull/254
the openQA-in-openQA tests switched to UEFI due to the changed default
in openSUSE Tumbleweed. Hence the badge must also not reference the
obsolete 64bit-2G. Instead of hardcoding uefi we can just leave out the
machine definition so that we look up whatever is "last".
=> README: Fix openQA badge after switch to UEFI

container/webui/docker-compose.yaml, container/worker/docker-compose.yaml
The top-level version property is not used anymore from docker-compose and it throws a warning. More info
https://docs.docker.com/reference/compose-file/version-and-name/
=> Remove version property from docker-compose

.github/workflows/check-helm-chart.yml, .mergify.yml
We have to adapt to the change mentioned in the notice on https://github.com/bitnami/charts/blob/main/bitnami/postgresql/README.md before we can run this CI check again.
Related ticket: https://progress.opensuse.org/issues/188982
=> Disable Helm Chart CI checks temporarily

lib/OpenQA/CacheService.pm
The service `openqa-worker-cacheservice-minion.service` already fails quickly if running into some database errors. With this change the same applies to `openqa-worker-cacheservice.service`. It will now also fail if any kind of database error happens. To make this work in as most cases as possible the event loop is now stopped immediately.
With this the availability check of the worker can now detect a broken cache service when the disk where the cache directory is stored is broken (and hence database errors occurs). This way the worker will no longer try to run jobs that would only end up with a cache service error anyway.
Note that before this change `openqa-worker-cacheservice.service` would stay running but fail to process the unavailability of …
=> Ensure a failing cache service is seen as such by the worker/scheduler

lib/OpenQA/WebAPI/Plugin/ObsRsync/Task.pm
This will avoid those jobs running into `Job terminated unexpectedly (exit code: 0,
signal: 15)`.
This change is not covering `obs_rsync_run` because retrying those jobs is not always a good idea.
Related ticket: https://progress.opensuse.org/issues/187068
=> Retry `obs_rsync_update_*` tasks if Gru service terminates
